'use strict';
const L=(en,zh,ms)=>[en,zh,ms];
const FOR_CODE='for ticket in range(3):\n    print("Please wait.")';
const WHILE_CODE='answer = input("Ready for help? Type yes: ")\n\nwhile answer != "yes":\n    answer = input("Type yes when ready: ")\n\nprint("Let us begin.")';
const SYNTAX_CODE='for ticket in range(3)\n    print("Please wait.")';
const NESTED_CODE='for desk in range(2):\n    for ticket in range(3):\n        print(desk, ticket)';
const UI={
 title:L('Loops & debugging','循环与调试','Gelung & penyahpepijatan'),
 subtitle:L('Small changes. Clear checks.','小步修改，清楚检查。','Perubahan kecil. Semakan jelas.'),
 welcome:L('You will read a small program, change one part, and check what happens. Examples stay beside your work.','你会阅读小程序、修改一处，再检查结果。示例会留在旁边。','Baca program ringkas, ubah satu bahagian dan semak hasilnya. Contoh kekal di sisi.'),
 name:L('Your name','你的姓名','Nama anda'),start:L('Start the lesson','开始学习','Mulakan pelajaran'),resume:L('Continue my lesson','继续学习','Sambung pelajaran'),
 lesson:L('Year 9 · Theory · 60 minutes','九年级 · 理论 · 60分钟','Tahun 9 · Teori · 60 minit'),
 saved:L('Saved on this device','已保存在此设备','Disimpan pada peranti ini'),
 saveError:L('This browser could not save your work. Keep this page open and save a PDF before leaving.','浏览器无法保存。请保持页面打开，并在离开前保存PDF。','Pelayar tidak dapat menyimpan kerja. Biarkan halaman terbuka dan simpan PDF sebelum keluar.'),
 next:L('Next','下一步','Seterusnya'),back:L('Back','上一步','Kembali'),check:L('Check my answer','检查答案','Semak jawapan'),
 retry:L('Try again','再试一次','Cuba lagi'),correct:L('Yes — that fits.','正确。','Ya — betul.'),notyet:L('Not yet. Use the clue below.','还没答对。看看提示。','Belum tepat. Gunakan petunjuk di bawah.'),
 teacher:L('Teacher view','教师模式','Paparan guru'),teacherNotes:L('Teacher guidance & answers','教学提示与答案','Panduan guru & jawapan'),
 support:L('Extra guidance','更多引导','Bimbingan tambahan'),supportNote:L('Short steps and Mandarin help are on. You can still try every activity.','已开启小步骤和中文提示。你仍可尝试所有活动。','Langkah ringkas dan bantuan Mandarin dihidupkan. Anda masih boleh mencuba semua aktiviti.'),
 goal:L('WAGBA','学习目标 WAGBA','Matlamat WAGBA'),goalText:L('Explain what a loop repeats, change a small program, and check whether a repair works.','解释循环重复什么，修改小程序，检查修复是否有效。','Terangkan apa yang diulang, ubah program ringkas dan semak pembaikan.'),
 knowledge:L('Knowledge','知识','Pengetahuan'),skills:L('Skills','技能','Kemahiran'),understanding:L('Understanding','理解','Pemahaman'),
 k:L('Recognise for / while loops and three error types.','识别 for / while 循环和三种错误。','Kenal gelung for / while dan tiga jenis ralat.'),
 s:L('Follow code, change one part, then run a check.','跟读代码，修改一处，再运行检查。','Jejak kod, ubah satu bahagian, kemudian semak.'),
 u:L('Explain why a loop stops and why a repair needs testing.','解释循环为何停止，以及修复后为何要测试。','Terangkan mengapa gelung berhenti dan pembaikan perlu diuji.'),
 example:L('Working example','可运行的示例','Contoh yang berfungsi'),job:L('Your job','你的任务','Tugas anda'),
 run:L('▶ Run','▶ 运行','▶ Jalankan'),stop:L('■ Stop','■ 停止','■ Henti'),reset:L('Restore example','恢复示例','Pulihkan contoh'),download:L('Save .py','保存 .py','Simpan .py'),
 console:L('Console · answer input() here','控制台 · 在这里回答 input()','Konsol · jawab input() di sini'),
 consoleReady:L('Press Run. If the program asks a question, an answer box will appear here.','点击运行。程序提问时，这里会出现输入框。','Tekan Jalankan. Jika program bertanya, kotak jawapan muncul di sini.'),
 running:L('Running…','正在运行…','Sedang berjalan…'),finished:L('Program finished.','程序结束。','Program selesai.'),stopped:L('Stopped. Your code is still here.','已停止。代码仍保留。','Dihentikan. Kod anda masih ada.'),
 send:L('Enter','输入','Hantar'),inputLabel:L('Your answer to the program','给程序的回答','Jawapan anda kepada program'),
 limit:L('The program ran too long. Check whether the loop can stop, then try again.','程序运行过久。检查循环能否停止，再试一次。','Program berjalan terlalu lama. Semak sama ada gelung boleh berhenti, kemudian cuba lagi.'),
 syntaxHint:L('Python could not read a line. Check the colon, brackets and indentation near the reported line.','Python无法读懂某一行。检查该行附近的冒号、括号和缩进。','Python tidak dapat membaca baris. Semak titik bertindih, kurungan dan inden berhampiran baris tersebut.'),
 runtimeHint:L('The program stopped while running. Read the error and check the value used on that line.','程序运行时停止了。阅读错误信息，检查该行使用的值。','Program terhenti semasa berjalan. Baca ralat dan semak nilai pada baris itu.'),
 editorHelp:L('Python practice editor · Tab inserts four spaces · Stop ends a loop · Standard lesson Python runs locally. Some Python libraries are unavailable.','Python练习编辑器 · Tab输入四个空格 · 停止按钮可结束循环 · 本课Python在本地运行，部分库不可用。','Editor latihan Python · Tab memasukkan empat ruang · Henti menamatkan gelung · Python pelajaran berjalan secara setempat. Sesetengah pustaka tidak tersedia.'),
 expected:L('Look for this','检查这个结果','Cari hasil ini'),
 selected:L('Selected','已选择','Dipilih'),choose:L('Choose an answer first.','请先选择答案。','Pilih jawapan dahulu.'),
 phases:[L('New learning','新学习','Pembelajaran baharu'),L('Consolidating','巩固','Pengukuhan'),L('Treading water','原地踏步','Terlalu mudah'),L('Drowning','遇到困难','Terlalu sukar')],
 phaseHelp:[L('This is new and takes effort, but I am making progress.','这是新内容，需要努力，但我正在进步。','Ini baharu dan mencabar, tetapi saya sedang maju.'),L('I am practising something I know and getting more secure.','我在练习已学的内容，越来越熟练。','Saya berlatih perkara yang diketahui dan semakin yakin.'),L('This is already easy; I need a further challenge.','这已经很容易；我需要更有挑战的任务。','Ini sudah mudah; saya perlukan cabaran lanjut.'),L('I am stuck and need someone to explain a smaller step.','我卡住了，需要有人解释更小的一步。','Saya buntu dan perlukan penerangan langkah yang lebih kecil.')]
};
const PAGES=[
 ['read',L('Read first','先读一读','Baca dahulu'),'8:50–8:55'],['starter',L('Do Now','立即开始','Aktiviti awal'),'8:55–8:59'],
 ['types',L('Types of Learning','学习类型','Jenis pembelajaran'),'8:59–9:01'],['main1',L('Main Task 1','主要任务一','Tugasan utama 1'),'9:01–9:16'],
 ['quiz',L('Pause & game','休息与游戏','Rehat & permainan'),'9:16–9:27'],['main2',L('Main Task 2','主要任务二','Tugasan utama 2'),'9:27–9:42'],
 ['challenge',L('Further challenge','进阶挑战','Cabaran lanjut'),L('When ready','准备好后','Apabila bersedia')],['pit',L('Learning Pit Stop','学习检查站','Hentian pembelajaran'),'9:42–9:45'],['finish',L('Plenary & save','总结与保存','Penutup & simpan'),'9:45–9:50']
];
const TRACE=[
 {line:1,value:'—',out:0,text:L('Python starts the loop. range(3) supplies three values: 0, 1 and 2.','Python开始循环。range(3)提供三个值：0、1、2。','Python memulakan gelung. range(3) memberikan tiga nilai: 0, 1 dan 2.')},
 {line:2,value:'0',out:1,text:L('First repetition: ticket is 0. The indented print line runs once.','第一次重复：ticket为0。缩进的print行运行一次。','Ulangan pertama: ticket ialah 0. Baris print berinden dijalankan sekali.')},
 {line:2,value:'1',out:2,text:L('Second repetition: ticket is 1. The same print line runs again.','第二次重复：ticket为1。同一个print行再次运行。','Ulangan kedua: ticket ialah 1. Baris print yang sama dijalankan lagi.')},
 {line:2,value:'2',out:3,text:L('Third repetition: ticket is 2. There are now three output lines.','第三次重复：ticket为2。现在共有三行输出。','Ulangan ketiga: ticket ialah 2. Kini terdapat tiga baris output.')},
 {line:1,value:'2',out:3,text:L('There are no more values in range(3). The loop ends. It does not use 3 as another value.','range(3)没有更多值了。循环结束，不会再使用3。','Tiada lagi nilai dalam range(3). Gelung tamat. Nilai 3 tidak digunakan.')}
];
const WHILE_TRACE=[
 {line:1,text:L('The program asks a question. In this example the user types no, so answer stores "no".','程序提问。在此示例中，用户输入no，所以answer存储"no"。','Program bertanya. Dalam contoh ini pengguna menaip no, maka answer menyimpan "no".'),out:'Ready for help? Type yes: no'},
 {line:3,text:L('Read != as “is not equal to”. "no" is not equal to "yes", so the condition is True. Enter the loop.','!=表示“不等于”。"no"不等于"yes"，条件为True，进入循环。','Baca != sebagai “tidak sama dengan”. "no" tidak sama dengan "yes", jadi syarat True. Masuk gelung.'),out:'Ready for help? Type yes: no'},
 {line:4,text:L('Ask again. This time the user types yes. The new value replaces the old answer.','再次提问。这次用户输入yes。新值替换旧回答。','Tanya lagi. Kali ini pengguna menaip yes. Nilai baharu menggantikan jawapan lama.'),out:'Ready for help? Type yes: no\nType yes when ready: yes'},
 {line:3,text:L('Check again: "yes" is not equal to "yes" is False. Leave the loop.','再次检查："yes"不等于"yes"为False。退出循环。','Semak lagi: "yes" tidak sama dengan "yes" ialah False. Keluar gelung.'),out:'Ready for help? Type yes: no\nType yes when ready: yes'},
 {line:6,text:L('This print is outside the loop. It runs after the condition becomes False.','这个print在循环外。条件变为False后，它才运行。','Print ini di luar gelung. Ia dijalankan selepas syarat menjadi False.'),out:'Ready for help? Type yes: no\nType yes when ready: yes\nLet us begin.'}
];
const Q=(id,prompt,options,answer,why,code='')=>({id,prompt,options,answer,why,code});
const STARTER=[
 Q('s1',L('What does print("Hello") do?','print("Hello")有什么作用？','Apakah fungsi print("Hello")?'),[L('Shows Hello','显示Hello','Memaparkan Hello'),L('Asks for an answer','要求输入回答','Meminta jawapan'),L('Stores a number','存储数字','Menyimpan nombor')],0,L('print displays an output. input asks the user for a value.','print显示输出。input向用户索取一个值。','print memaparkan output. input meminta nilai daripada pengguna.')),
 Q('s2',L('Which line repeats in this example?','本例中哪一行会重复？','Baris manakah yang berulang?'),[L('The indented print line','缩进的print行','Baris print yang berinden'),L('Neither line','都不重复','Tiada baris'),L('An input line','input行','Baris input')],0,L('The indentation places print inside the loop. It runs for each value in range(3).','缩进让print位于循环内。range(3)每提供一个值，它就运行一次。','Inden meletakkan print dalam gelung. Ia berjalan bagi setiap nilai dalam range(3).'),FOR_CODE),
 Q('s3',L('How many times does Please wait. appear?','Please wait.会出现几次？','Berapa kali Please wait. muncul?'),[L('2 times','2次','2 kali'),L('3 times','3次','3 kali'),L('4 times','4次','4 kali')],1,L('The values are 0, 1 and 2: three repetitions.','值为0、1、2：共三次。','Nilainya ialah 0, 1 dan 2: tiga ulangan.'),FOR_CODE)
];
const QUIZ=[
 Q('q1',L('What does repetition mean in a program?','程序中的重复是什么意思？','Apakah maksud pengulangan dalam program?'),[L('Run an instruction again','再次运行指令','Jalankan arahan lagi'),L('Delete an instruction','删除指令','Padam arahan'),L('Rename a variable','重命名变量','Namakan semula pemboleh ubah')],0,L('A loop repeats instructions.','循环会重复执行指令。','Gelung mengulangi arahan.')),
 Q('q2',STARTER[0].prompt,STARTER[0].options,0,STARTER[0].why),
 Q('q3',L('What does != mean?','!=是什么意思？','Apakah maksud !=?'),[L('Is equal to','等于','Sama dengan'),L('Is not equal to','不等于','Tidak sama dengan'),L('Stores a value','存储值','Menyimpan nilai')],1,L('!= compares two values. It is True when they are different.','!=比较两个值。不同时为True。','!= membandingkan dua nilai. Hasilnya True apabila nilainya berbeza.')),
 Q('q4',STARTER[1].prompt,STARTER[1].options,0,STARTER[1].why,FOR_CODE),
 Q('q5',L('How many values does range(3) supply?','range(3)提供几个值？','Berapakah nilai yang diberikan oleh range(3)?'),[L('2','2','2'),L('4','4','4'),L('3','3','3')],2,L('It supplies 0, 1 and 2. Count the values, not just the last number.','它提供0、1、2。数一数值的个数，而非只看最后一个数。','Ia memberikan 0, 1 dan 2. Kira bilangan nilai, bukan nilai terakhir.')),
 Q('q6',L('How many output lines will you see?','你会看到几行输出？','Berapa baris output akan muncul?'),[L('1','1','1'),L('3','3','3'),L('0','0','0')],1,L('One print runs on each of three repetitions.','三次重复，每次执行一个print。','Satu print dijalankan dalam setiap tiga ulangan.'),FOR_CODE),
 Q('q7',L('Change range(3) to range(2). What changes?','把range(3)改为range(2)，会怎样？','Tukar range(3) kepada range(2). Apakah perubahannya?'),[L('Two output lines','两行输出','Dua baris output'),L('The message changes','信息内容改变','Mesej berubah'),L('It asks a question','程序会提问','Program bertanya')],0,L('The repetition count changes; the printed words stay the same.','重复次数改变，打印的文字不变。','Bilangan ulangan berubah; perkataan yang dicetak kekal sama.'),FOR_CODE),
 Q('q8',L('answer stores "no". Is this condition True or False?','answer存储"no"。这个条件是True还是False？','answer menyimpan "no". Adakah syarat ini True atau False?'),[L('True','True','True'),L('False','False','False'),L('It stores yes','它会存储yes','Ia menyimpan yes')],0,L('"no" differs from "yes", so != gives True and the loop repeats.','"no"与"yes"不同，所以!=为True，循环继续。','"no" berbeza daripada "yes", maka != menghasilkan True dan gelung berulang.'),'while answer != "yes":'),
 Q('q9',L('answer now stores "yes". What happens?','answer现在存储"yes"。接下来呢？','answer kini menyimpan "yes". Apa berlaku?'),[L('The loop repeats forever','循环永远重复','Gelung berulang selama-lamanya'),L('The condition is False; leave the loop','条件为False；退出循环','Syarat False; keluar gelung'),L('Python changes yes to no','Python把yes改为no','Python menukar yes kepada no')],1,L('"yes" != "yes" is False. Continue with the code after the loop.','"yes" != "yes"为False。继续执行循环后的代码。','"yes" != "yes" ialah False. Teruskan kod selepas gelung.'),'while answer != "yes":'),
 Q('q10',L('Which line stores a new answer?','哪一行存储新的回答？','Baris manakah menyimpan jawapan baharu?'),[L('print("Please wait.")','print("Please wait.")','print("Please wait.")'),L('while answer != "yes":','while answer != "yes":','while answer != "yes":'),L('answer = input("Type yes: ")','answer = input("Type yes: ")','answer = input("Type yes: ")')],2,L('input gets text; = stores that text in answer.','input获取文字，=将文字存入answer。','input mendapatkan teks; = menyimpan teks itu dalam answer.')),
 Q('q11',L('Print exactly four tickets. Which loop fits?','恰好打印四张票。选哪种循环？','Cetak tepat empat tiket. Gelung manakah sesuai?'),[L('for ticket in range(4):','for ticket in range(4):','for ticket in range(4):'),L('for ticket in range(3):','for ticket in range(3):','for ticket in range(3):'),L('print(4)','print(4)','print(4)')],0,L('range(4) supplies four values, so the loop body runs four times.','range(4)提供四个值，所以循环体运行四次。','range(4) memberikan empat nilai, maka badan gelung berjalan empat kali.')),
 Q('q12',L('Keep asking until the user types yes. Which structure fits?','不断提问，直到用户输入yes。选哪个结构？','Terus bertanya sehingga pengguna menaip yes. Struktur manakah sesuai?'),[L('One print statement','一个print语句','Satu pernyataan print'),L('A while loop that checks the answer','检查回答的while循环','Gelung while yang menyemak jawapan'),L('A loop fixed at two attempts','固定两次的循环','Gelung dengan tepat dua cubaan')],1,L('A while loop checks a condition before each repetition. The number of answers can vary.','while在每次重复前检查条件。回答次数可能不同。','Gelung while menyemak syarat sebelum setiap ulangan. Bilangan jawapan boleh berbeza.')),
 Q('q13',L('Which symbol is missing at the end of line 1?','第一行末尾缺少哪个符号？','Simbol apakah yang hilang di hujung baris 1?'),[L('A colon :','冒号 :','Titik bertindih :'),L('A plus +','加号 +','Tambah +'),L('A question mark ?','问号 ?','Tanda soal ?')],0,L('The loop header needs a colon. The next line is indented.','循环头需要冒号，下一行要缩进。','Pengepala gelung memerlukan titik bertindih. Baris seterusnya berinden.'),SYNTAX_CODE),
 Q('q14',L('Inside the while loop, which line allows the condition to change?','在while循环里，哪一行能让条件改变？','Dalam gelung while, baris manakah membolehkan syarat berubah?'),[L('print("Still waiting.")','print("Still waiting.")','print("Still waiting.")'),L('print(answer)','print(answer)','print(answer)'),L('answer = input("Type yes: ")','answer = input("Type yes: ")','answer = input("Type yes: ")')],2,L('A new input can replace no with yes. Reprinting the old answer does not change it.','新输入可以把no替换为yes。重复打印旧回答不会改变它。','Input baharu boleh menggantikan no dengan yes. Mencetak jawapan lama tidak mengubahnya.')),
 Q('q15',L('You repaired the ready-check loop. Which test checks both repeating and stopping?','修复循环后，哪个测试能同时检查重复和停止？','Anda membaiki gelung kesediaan. Ujian manakah menyemak ulangan dan penamatan?'),[L('Only look at the code','只看代码','Lihat kod sahaja'),L('Enter no, then yes; check it asks again and then finishes','输入no再输入yes，检查先重问再结束','Masukkan no, kemudian yes; semak ia bertanya lagi lalu tamat'),L('Change its colour','改变颜色','Tukar warnanya')],1,L('This test follows the repeating path and the stopping path.','这个测试走过重复和停止两条路径。','Ujian ini melalui laluan ulangan dan laluan penamatan.'))
];
const MAIN1=[
 {type:'question',title:L('Predict: count the output','预测：数输出','Ramal: kira output'),instruction:L('Read the two lines. Choose how many messages you expect. You do not need to type code.','阅读两行代码，选择会出现几条信息。不需要编写代码。','Baca dua baris. Pilih bilangan mesej yang dijangka. Tidak perlu menaip kod.'),q:Q('m1predict',STARTER[2].prompt,STARTER[2].options,1,STARTER[2].why,FOR_CODE)},
 {type:'editor',id:'forRun',title:L('Run: check your prediction','运行：检查预测','Jalankan: semak ramalan'),instruction:L('Press Run. Count the three output lines. Keep the code as it is for this step.','点击运行，数三行输出。这一步先保留原代码。','Tekan Jalankan. Kira tiga baris output. Kekalkan kod untuk langkah ini.'),code:FOR_CODE,expect:L('Three lines of Please wait.','三行Please wait.','Tiga baris Please wait.')},
 {type:'trace',title:L('Investigate: follow one repetition','探究：跟踪一次重复','Siasat: jejak satu ulangan'),instruction:L('Use Next step. Watch the highlighted line and the output together.','点击下一步，同时观察高亮代码和输出。','Gunakan Langkah seterusnya. Perhatikan baris diserlahkan dan output bersama.')},
 {type:'parsons',id:'tickets',title:L('Arrange: build a tiny loop','排序：构建小循环','Susun: bina gelung ringkas'),instruction:L('Use ↑ and ↓ to put the loop header first and its indented print underneath. Keep Done. outside the loop and last.','用↑和↓将循环头放前面，缩进的print放下面。Done.应在循环外，放最后。','Gunakan ↑ dan ↓ untuk meletakkan pengepala gelung dahulu dan print berinden di bawahnya. Letakkan Done. di luar gelung dan terakhir.'),lines:['for ticket in range(2):','    print("Ticket ready.")','print("Done.")'],initial:[2,1,0],why:L('The header starts the loop. The indented line repeats twice. Done. prints once afterwards.','循环头开始循环。缩进行重复两次。之后Done.只打印一次。','Pengepala memulakan gelung. Baris berinden berulang dua kali. Done. dicetak sekali selepas itu.')},
 {type:'fill',title:L('Complete: change just one number','补全：只改一个数字','Lengkapkan: ubah satu nombor'),instruction:L('Make four messages. Choose the number for the gap.','打印四条信息。选择填空的数字。','Hasilkan empat mesej. Pilih nombor untuk tempat kosong.'),q:Q('fill4',L('Which number belongs in the gap?','空白处填哪个数字？','Nombor manakah mengisi tempat kosong?'),[L('2','2','2'),L('3','3','3'),L('4','4','4')],2,L('range(4) repeats the print four times.','range(4)让print重复四次。','range(4) mengulangi print empat kali.'),'for ticket in range(___):\n    print("Please wait.")')},
 {type:'editor',id:'forModify',title:L('Modify: make two messages','修改：打印两条信息','Ubah: hasilkan dua mesej'),instruction:L('Find 3 in range(3). Change it so the program prints two messages. Run and count the output.','找到range(3)中的3。修改它，让程序打印两条信息。运行并数输出。','Cari 3 dalam range(3). Ubah supaya program mencetak dua mesej. Jalankan dan kira output.'),code:FOR_CODE,expect:L('Two lines of Please wait. Only the repetition count needs changing.','两行Please wait.。只需改变重复次数。','Dua baris Please wait. Hanya bilangan ulangan perlu diubah.')},
 {type:'while',title:L('Investigate: repeat until ready','探究：重复直到准备好','Siasat: ulang sehingga bersedia'),instruction:L('A while loop checks a condition. Follow the example: the user types no, then yes. Read != as “is not equal to”.','while循环检查条件。跟随示例：用户先输入no，再输入yes。!=表示“不等于”。','Gelung while menyemak syarat. Ikuti contoh: pengguna menaip no, kemudian yes. != bermaksud “tidak sama dengan”.')},
 {type:'editor',id:'whileRun',title:L('Try the two paths','尝试两条路径','Cuba dua laluan'),instruction:L('Run. Type no in the console and press Enter. When asked again, type yes. Watch it stop asking and print the final message.','运行。在控制台输入no并回车。再次被问时输入yes。观察程序停止提问并打印最后的信息。','Jalankan. Taip no dalam konsol dan tekan Hantar. Apabila ditanya lagi, taip yes. Perhatikan soalan berhenti dan mesej akhir dicetak.'),code:WHILE_CODE,expect:L('no → asks again. yes → Let us begin. Use lowercase yes in this example.','no → 再次提问。yes → Let us begin.。本例请使用小写yes。','no → bertanya lagi. yes → Let us begin. Gunakan yes huruf kecil dalam contoh ini.')}
];
const MAIN2=[
 {type:'errors',title:L('Recognise: three kinds of error','识别：三种错误','Kenal: tiga jenis ralat'),instruction:L('Read one row at a time. An error is a clue about what to check. You will repair one small example next.','逐行阅读。错误是检查方向的线索。接下来你会修复一个小示例。','Baca satu baris pada satu masa. Ralat ialah petunjuk perkara untuk disemak. Seterusnya anda membaiki contoh ringkas.')},
 {type:'question',title:L('Predict: what should this do?','预测：它应该做什么？','Ramal: apakah yang sepatutnya berlaku?'),instruction:L('This program should print three waiting messages. It has one syntax error. Find the missing symbol before running it.','程序应打印三条等待信息，但有一个语法错误。运行前找出缺少的符号。','Program ini sepatutnya mencetak tiga mesej menunggu. Terdapat satu ralat sintaks. Cari simbol yang hilang sebelum menjalankannya.'),q:{...QUIZ[12],id:'repairPredict'}},
 {type:'editor',id:'repair',title:L('Run, repair, run again','运行、修复、再运行','Jalankan, baiki, jalankan lagi'),instruction:L('Run the faulty code once and read the error. Add : at the end of the loop header. Run again. Compare the result with three expected messages.','先运行错误代码并阅读提示。在循环头末尾加上:。再运行，检查是否有三条信息。','Jalankan kod rosak sekali dan baca ralat. Tambah : di hujung pengepala gelung. Jalankan lagi. Bandingkan hasil dengan tiga mesej yang dijangka.'),code:SYNTAX_CODE,expect:L('After repair: three waiting messages and no syntax error.','修复后：三条等待信息，没有语法错误。','Selepas pembaikan: tiga mesej menunggu tanpa ralat sintaks.')},
 {type:'question',title:L('Investigate: it runs, but is it right?','探究：能运行就正确吗？','Siasat: berjalan, tetapi betulkah?'),instruction:L('The helpdesk needs THREE tickets. This code runs. Compare its output count with the requirement.','服务台需要三张票。代码可以运行。比较输出数量与要求。','Meja bantuan memerlukan TIGA tiket. Kod ini berjalan. Bandingkan bilangan output dengan keperluan.'),q:Q('logic',L('Which repair meets the requirement?','哪种修复符合要求？','Pembaikan manakah memenuhi keperluan?'),[L('Change range(4) to range(3)','把range(4)改为range(3)','Tukar range(4) kepada range(3)'),L('Remove the colon','删除冒号','Buang titik bertindih'),L('Change only the words','只改变文字','Tukar perkataan sahaja')],0,L('This is a logic error: the program runs but repeats too many times. Change the count, then check for three outputs.','这是逻辑错误：程序运行但重复次数太多。修改次数，再检查三次输出。','Ini ralat logik: program berjalan tetapi terlalu banyak ulangan. Ubah bilangan, kemudian semak tiga output.'),'for ticket in range(4):\n    print("Ticket ready.")')},
 {type:'parsons',id:'ready',title:L('Build: put the ready check together','构建：组合准备检查程序','Bina: susun semakan kesediaan'),instruction:L('Put the first question before the loop. Put the indented question inside it. Finish with the unindented print. Use the example if you need it.','把第一个问题放在循环前。缩进的问题放在循环内。最后放不缩进的print。需要时查看示例。','Letakkan soalan pertama sebelum gelung. Letakkan soalan berinden di dalamnya. Akhiri dengan print tanpa inden. Gunakan contoh jika perlu.'),lines:['answer = input("Ready? Type yes: ")','while answer != "yes":','    answer = input("Type yes when ready: ")','print("Let us begin.")'],initial:[3,2,0,1],why:L('Ask → check → ask again when needed → finish. Updating answer lets the condition become False.','提问→检查→需要时再问→结束。更新answer可让条件变为False。','Tanya → semak → tanya lagi jika perlu → tamat. Mengemas kini answer membolehkan syarat menjadi False.')},
 {type:'editor',id:'readyMake',title:L('Modify: make the message helpful','修改：让提示更清楚','Ubah: jadikan mesej lebih membantu'),instruction:L('Change only the words inside the repeated input prompt. Tell the user exactly what to type. Keep the variable, condition and indentation. Run it.','只改循环内input提示的文字。清楚告诉用户要输入什么。保留变量、条件和缩进。然后运行。','Ubah hanya perkataan dalam arahan input berulang. Beritahu pengguna apa yang perlu ditaip. Kekalkan pemboleh ubah, syarat dan inden. Jalankan.'),code:'answer = input("Ready for help? Type yes: ")\n\nwhile answer != "yes":\n    answer = input("Again: ")\n\nprint("Let us begin.")',expect:L('A useful prompt includes lowercase yes. Try no, then yes.','有用的提示应包含小写yes。试试先no后yes。','Arahan yang berguna menyebut yes huruf kecil. Cuba no, kemudian yes.')},
 {type:'test',title:L('Check: did the improvement work?','检查：改进有效吗？','Semak: adakah penambahbaikan berkesan?'),instruction:L('Use your improved program below. Run each test separately. Record what actually happened, then complete one short explanation.','使用下方改进后的程序。分别运行每项测试，记录实际结果，再完成一个简短解释。','Gunakan program yang ditambah baik di bawah. Jalankan setiap ujian berasingan. Catat hasil sebenar, kemudian lengkapkan satu penerangan ringkas.')}
];
