(() => {
 'use strict';
 const $=id=>document.getElementById(id), E=window.escapeHTML;
 const KIND='mrdave-fitness-v2';
 // Retain the existing device-storage name so previously saved work still opens.
 const STORAGE=atob('bXJkYXZlLWZpdG5lc3MtanVuZTIwMjMtdjE=');
 let state=null,db=null,saveTimer=null,lastKey='',toastTimer=null,writeQueue=Promise.resolve();
 function notify(msg){$('toast').textContent=msg;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,6000);}
 function blank(name,cl,teacher=false){return {kind:KIND,version:1,name,className:cl,teacher,page:0,answers:{},done:{},reveals:{},checks:{},extraTrace:[],images:{trace:[],validation:[]},updated:new Date().toISOString()};}
 function openDB(){return new Promise(resolve=>{try{const req=indexedDB.open(STORAGE,1);req.onupgradeneeded=()=>req.result.createObjectStore('notebooks');req.onsuccess=()=>resolve(req.result);req.onerror=()=>resolve(null);}catch{resolve(null);}});}
 function localKey(name,cl,teacher){return teacher?'teacher-preview':JSON.stringify([name.trim().toLowerCase(),cl.trim().toLowerCase()]);}
 async function readSaved(key){if(db)return new Promise(resolve=>{const r=db.transaction('notebooks').objectStore('notebooks').get(key);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>resolve(null);});try{return JSON.parse(localStorage.getItem(STORAGE+key)||'null');}catch{return null;}}
 function persist(){if(!state)return Promise.resolve();clearTimeout(saveTimer);state.updated=new Date().toISOString();const snapshot=JSON.parse(JSON.stringify(state)),key=lastKey;writeQueue=writeQueue.catch(()=>{}).then(()=>new Promise((resolve,reject)=>{if(db){const tx=db.transaction('notebooks','readwrite');tx.objectStore('notebooks').put(snapshot,key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);}else{try{localStorage.setItem(STORAGE+key,JSON.stringify(snapshot));resolve();}catch(e){reject(e);}}})).then(()=>{if(lastKey===key)$('saveStatus').textContent='Saved on this device';}).catch(()=>{$('saveStatus').textContent='Device save unavailable — use Full backup';});return writeQueue;}
 function queueSave(){if(!state)return;$('saveStatus').textContent='Saving…';clearTimeout(saveTimer);saveTimer=setTimeout(persist,200);}
 function slug(s){return s.trim().replace(/[^\p{L}\p{N}_-]+/gu,'_').slice(0,70)||'Student';}
 function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),20000);}
 function teacherBlock(){if(!state.teacher)return '';return `<div class="teacher-banner"><strong>Teacher preview</strong><p class="small">All pages are available. Your preview uses a separate notebook. The core lesson is 60 minutes; extension is for early finishers.</p><details><summary>Quick teaching notes and validation example</summary><p><strong>Your two checks:</strong> after tracing, ask why record 14 is excluded; during testing, ask a student to show an invalid entry followed by a valid one.</p><p><strong>Trace key:</strong> 1001 / 3 / 10.0 / True / Yes; 1001 / 3 / 10.9 / True / Yes; 1002 / 5 / 20.0 / False / No. The returned list has 13 records after the whole original file is read.</p><p><strong>Common difficulty:</strong> int() before the digit check still crashes on letters. Forgetting the repeated input can leave the loop running forever.</p>${CODE_HTML(TEACHER_MODEL,'One valid solution to this practice task')}<p class="small">Accept other solutions that meet the requirements and pass the tests. This is a practice solution, not the published examination mark scheme.</p></details></div>`;}
 function nav(){const p=state.page;$('lessonNav').innerHTML=PAGES.map((v,i)=>`<button data-go="${i}" ${i===p?'aria-current="page"':''}><span class="nav-num">${String(i).padStart(2,'0')}</span><span>${E(v.title.split(' · ')[0])}</span>${state.done[v.id]?'<span class="nav-done" aria-label="Completed">✓</span>':''}</button>`).join('');$('previousBtn').disabled=p===0;$('nextBtn').disabled=p===PAGES.length-1;$('stagePosition').textContent=`${p+1} / ${PAGES.length} · ${state.name}${state.className?' · '+state.className:''}`;}
 function hydrate(){document.querySelectorAll('[data-field]').forEach(el=>{const val=state.answers[el.dataset.field];if(el.type==='radio')el.checked=val===el.value;else if(el.type==='checkbox')el.checked=val===true;else el.value=typeof val==='string'?val:'';});document.querySelectorAll('details[data-reveal]').forEach(el=>{if(state.reveals[el.dataset.reveal])el.open=true;});renderExtra();renderImages();reflections();if(state.checks.syntax)syntaxFeedback();if(state.checks.trace)traceFeedback();submissionReview();}
 function render(focus=false){if(!state)return;const p=PAGES[state.page];$('content').innerHTML=teacherBlock()+p.html+`<div class="completion"><label><input type="checkbox" id="stageDone" ${state.done[p.id]?'checked':''}>${E(STAGE_FINISH[p.id]||'I have finished this stage.')}</label><p class="small muted">${p.id==='extension'?'Choose Finish with evidence in the menu to save your final work.':'When you are ready, choose Next stage at the bottom of the page.'}</p></div>`;nav();hydrate();if(focus){window.scrollTo({top:0,behavior:'instant'});$('content').focus({preventScroll:true});}}
 function go(n){if(!state)return;state.page=Math.max(0,Math.min(PAGES.length-1,n));render(true);queueSave();}
 async function login(name,cl){const teacher=name.trim().toLowerCase()==='teacher';lastKey=localKey(name,cl,teacher);const saved=await readSaved(lastKey);state=saved&&[KIND,STORAGE].includes(saved.kind)?saved:blank(teacher?'Teacher preview':name.trim(),teacher?'':cl.trim(),teacher);state.kind=KIND;state.teacher=teacher;state.page=Math.max(0,Math.min(PAGES.length-1,state.page||0));$('landing').hidden=true;$('lesson').hidden=false;$('backupBtn').disabled=false;$('pdfBtn').disabled=false;try{localStorage.setItem(STORAGE+'-active',lastKey);}catch{}render(true);await persist();}
 $('loginForm').addEventListener('submit',async e=>{e.preventDefault();const name=$('studentName').value.trim(),cl=$('studentClass').value.trim();if(!name)return;if(name.toLowerCase()!=='teacher'&&!cl){$('loginError').textContent='Please enter your class so your notebook is labelled correctly.';return;}$('loginError').textContent='';await login(name,cl);});
 $('changeStudent').addEventListener('click',async()=>{await persist();state=null;$('lesson').hidden=true;$('landing').hidden=false;$('backupBtn').disabled=true;$('pdfBtn').disabled=true;try{localStorage.removeItem(STORAGE+'-active');}catch{}$('saveStatus').textContent='Your lesson notebook';});
 $('previousBtn').onclick=()=>go(state.page-1);$('nextBtn').onclick=()=>go(state.page+1);
 document.addEventListener('input',e=>{const el=e.target;if(!state)return;if(el.dataset.field){state.answers[el.dataset.field]=el.type==='checkbox'?el.checked:el.value;queueSave();if(el.tagName==='SELECT')reflections();submissionReview();}if(el.dataset.extra!==undefined){state.extraTrace[Number(el.dataset.extra)]=el.value;queueSave();}});
 document.addEventListener('change',e=>{if(e.target.id==='stageDone'){state.done[PAGES[state.page].id]=e.target.checked;nav();queueSave();}if(e.target.dataset.upload)handleImages(e.target);});
 document.addEventListener('toggle',e=>{if(state&&e.target.matches('details[data-reveal]')&&e.target.open){state.reveals[e.target.dataset.reveal]=true;queueSave();}},true);
 document.addEventListener('keydown',e=>{if(e.key==='Tab'&&e.target.classList.contains('code-answer')){e.preventDefault();const el=e.target,start=el.selectionStart;el.setRangeText('    ',start,el.selectionEnd,'end');el.dispatchEvent(new Event('input',{bubbles:true}));}});
 document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||!state)return;if(b.dataset.go!==undefined)go(Number(b.dataset.go));if(b.dataset.copy){const text=COPY_CODE[b.dataset.copy];try{await navigator.clipboard.writeText(text);notify('Code copied. Paste it into your Python IDE.');}catch{const box=document.createElement('textarea');box.value=text;document.body.append(box);box.select();const ok=document.execCommand('copy');box.remove();notify(ok?'Code copied. Paste it into your Python IDE.':'Copy was unavailable. Select the code in the example.');}}if(b.dataset.action==='check-syntax'){state.checks.syntax=true;syntaxFeedback();queueSave();}if(b.dataset.action==='check-trace'){state.checks.trace=true;traceFeedback();queueSave();}if(b.dataset.action==='add-trace'){state.extraTrace.push('');renderExtra();queueSave();}if(b.dataset.removeImage){const [key,i]=b.dataset.removeImage.split(':');state.images[key].splice(Number(i),1);renderImages();queueSave();}});
 function syntaxFeedback(){const el=$('syntaxFeedback');if(!el)return;const names=[['syntax_r','r','The lower-case mode r reads an existing file.'],['syntax_readline','readline','readline() reads one line.'],['syntax_a','a','The lower-case mode a appends at the end.'],['syntax_write','write','write() writes the supplied string.']];const result=names.map(([id,answer,why])=>{const val=String(state.answers[id]||'').trim().replace(/^['"]|['"]$/g,'').replace(/\(\)$/,'');return `<li><strong>${val===answer?'Correct':'Check '+E(FIELDS[id])}:</strong> ${why}</li>`;});el.innerHTML=`<div class="feedback"><ul>${result.join('')}</ul><p class="small">Use the completed examples if you need them, then verify the behaviour in your IDE.</p></div>`;}
 function traceFeedback(){const el=$('traceFeedback');if(!el)return;const keys=['person','week','distance','match','added'];let attempted=0,correct=0;TRACE_ANSWERS.forEach((r,i)=>r.forEach((a,j)=>{const v=String(state.answers[`trace_${i}_${keys[j]}`]||'').trim();if(v){attempted++;if(j===2?Number(v)===Number(a):v.toLowerCase().replace(/["']/g,'')===a.toLowerCase())correct++;}}));el.innerHTML=`<div class="feedback">${state.answers.trace_route==='Paper'?'<p>Compare each cell with your paper trace. Keep your first attempt visible.</p>':`<p>${attempted?`${correct} of ${attempted} entered cells match the worked trace. ${15-attempted} cells are still empty.`:'Use this worked trace to check your reasoning.'}</p>`}<div class="table-scroll"><table><thead><tr><th>Record</th><th>ID</th><th>Week</th><th>Distance</th><th>Matches?</th><th>Added?</th></tr></thead><tbody>${TRACE_ANSWERS.map((r,i)=>`<tr><th>${[1,2,14][i]}</th>${r.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p>Record 14 belongs to <code>"1002"</code>. The current ID is <code>"1001"</code>, so <code>Activity.PersonID == Individual.ID</code> is False and that record is not appended. Removing this check would include other people’s activities.</p><p><code>LoadActivity</code> returns <code>ActivityLog</code>. <code>ActivityLog.append(Activity)</code> updates the list in memory; <code>AppendActivityToFile(Activity)</code> saves the record in the text file for future runs.</p></div>`;}
 function renderExtra(){const el=$('extraTrace');if(!el)return;el.innerHTML=state.extraTrace.map((v,i)=>`<label for="extra_${i}">Additional record / note ${i+1}</label><textarea id="extra_${i}" data-extra="${i}" maxlength="2000">${E(v)}</textarea>`).join('');}
 const focusActions={Knowledge:'Use the file-mode reading. After reading, look away and explain r and a in your own words.',Skills:'Complete one small example, run it, then compare the result with your prediction before moving on.',Understanding:'Follow one record or one invalid input. Explain why the program takes that route.'};
 const nextActions={Knowledge:{'New learning':'Revisit the file-mode and test-data explanations. Recall one meaning without looking.','Consolidating':'Recall r, a and the boundary tests without the notes, then check.','Treading water':'Explain why w would be unsuitable for preserving existing activity records.','Drowning':'Show me the two file examples. We can match one method to one effect together.','Not attempted yet':'Begin with the short file-mode reading and one prediction.'},Skills:{'New learning':'Use the support structure to complete one check, then run a single test.','Consolidating':'Rerun a boundary test and a non-numeric test without prompting.','Treading water':'Try the reusable validation function in the extension.','Drowning':'Show me the first line or test that stops you. We will work through one input together.','Not attempted yet':'Start with the file syntax practice, then run one example.'},Understanding:{'New learning':'Explain why 0 passes a digit check but still needs rejecting.','Consolidating':'Explain why record 1002 is excluded and why abc must be checked before int().','Treading water':'Explain the benefits of separating validation from input in the extension.','Drowning':'Use the first record or the input abc. Ask me to follow its route with you.','Not attempted yet':'Follow the first record through the code with the reading.'}};
 function reflections(){if($('focusAction'))$('focusAction').textContent=focusActions[state.answers.focus]||'Choose the area you most want to develop. You can change your choice as you learn.';document.querySelectorAll('[data-prior]').forEach(el=>{el.textContent='At the start: '+(state.answers['start_'+el.dataset.prior]||'not recorded')+'.';});if($('phaseAction')){const f=state.answers.next_focus,c=CONCEPTS.find(c=>c.title===f),phase=c&&state.answers['end_'+c.id];$('phaseAction').textContent=f&&phase?nextActions[f][phase]:'Choose a phase for each area and one next focus. Use your work to explain the choice.';}}
 function submissionReview(){const el=$('submissionReview');if(!el)return;const trace=state.answers.trace_route==='Paper'?(state.images.trace.length?'Paper photo attached':'Paper photo not yet attached'):`${Object.keys(state.answers).filter(k=>/^trace_\d_/.test(k)&&state.answers[k].trim()).length}/15 digital trace cells filled`;const tests=TESTS.filter((_,i)=>String(state.answers[`test_${i}_actual`]||'').trim()).length;el.textContent=`Notebook check: ${trace}; ${state.answers.validation_code?.trim()?'code recorded':'code not yet recorded'}; actual outcomes recorded for ${tests}/7 tests. This checks evidence present, not whether your answers are correct.`;}
 async function imageData(file){if(file.size>15*1024*1024)throw new Error('Use an image smaller than 15 MB.');if(!/^image\/(jpeg|png|webp)$/.test(file.type))throw new Error('Please choose JPG, PNG or WebP.');const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(new Error('Could not read that file.'));r.readAsDataURL(file);});const img=await new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(new Error('Could not open that image.'));i.src=data;});const scale=Math.min(1,2000/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);return {name:file.name,data:canvas.toDataURL('image/jpeg',.88),width:canvas.width,height:canvas.height};}
 async function handleImages(input){const key=input.dataset.upload,active=state;input.disabled=true;try{for(const file of input.files){if(active.images[key].length>=4){notify('There are already four images in this section. Remove one to replace it.');break;}const data=await imageData(file);if(state!==active)break;active.images[key].push(data);}if(state===active){renderImages();await persist();}}catch(e){notify(e.message);}finally{input.value='';input.disabled=false;}}
 function renderImages(){document.querySelectorAll('[data-upload-list]').forEach(el=>{const key=el.dataset.uploadList;el.innerHTML=state.images[key].map((im,i)=>`<div class="upload-item"><img src="${im.data}" alt="${E(key+' evidence '+(i+1))}"><p class="small">${E(im.name)}</p><button data-remove-image="${key}:${i}">Remove image ${i+1}</button></div>`).join('');});}
 $('backupBtn').onclick=async()=>{await persist();download(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),slug(state.name)+'_Fitness_Full_Backup.json');notify('Full backup downloaded. It includes your answers and attached images.');};
 $('restoreFile').addEventListener('change',async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>40*1024*1024)throw new Error('That backup is too large.');const raw=JSON.parse(await file.text());if(![KIND,STORAGE].includes(raw.kind)||typeof raw.name!=='string'||typeof raw.className!=='string'||!raw.answers||typeof raw.answers!=='object')throw new Error('Choose a full backup from this fitness lesson.');const clean=blank(raw.name.slice(0,80),raw.className.slice(0,40),raw.teacher===true);for(const [k,v]of Object.entries(raw.answers))if(k.length<100&&(typeof v==='string'||typeof v==='boolean'))clean.answers[k]=typeof v==='string'?v.slice(0,30000):v;for(const key of ['done','reveals','checks'])if(raw[key]&&typeof raw[key]==='object')for(const [k,v]of Object.entries(raw[key]))if(v===true)clean[key][k]=true;clean.page=Math.max(0,Math.min(PAGES.length-1,Number(raw.page)||0));clean.extraTrace=Array.isArray(raw.extraTrace)?raw.extraTrace.slice(0,40).filter(x=>typeof x==='string').map(x=>x.slice(0,2000)):[];for(const key of ['trace','validation'])for(const im of (raw.images?.[key]||[]).slice(0,4)){if(typeof im.data==='string'&&/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(im.data)&&im.data.length<6000000&&im.width>0&&im.height>0)clean.images[key].push({name:String(im.name||'Evidence').slice(0,200),data:im.data,width:im.width,height:im.height});}lastKey=localKey(clean.name,clean.className,clean.teacher);const existing=await readSaved(lastKey);if(existing&&!window.confirm('Restore this backup over the notebook saved for this name and class?'))return;state=clean;await persist();$('landing').hidden=true;$('lesson').hidden=false;$('backupBtn').disabled=false;$('pdfBtn').disabled=false;try{localStorage.setItem(STORAGE+'-active',lastKey);}catch{}render(true);notify('Your notebook and images have been restored.');}catch(err){$('loginError').textContent=err.message;}finally{e.target.value='';}});
 async function exportPDF(){if(!state)return;$('pdfBtn').disabled=true;try{await persist();const {jsPDF}=window.jspdf,pdf=new jsPDF({unit:'mm',format:'a4'});pdf.addFileToVFS('Raleway-Regular.ttf',PDF_FONTS.regular);pdf.addFont('Raleway-Regular.ttf','Raleway','normal');pdf.addFileToVFS('Raleway-Bold.ttf',PDF_FONTS.bold);pdf.addFont('Raleway-Bold.ttf','Raleway','bold');let y=22;const left=17,width=176,bottom=278;
 const font=(size=10,bold=false,mono=false)=>{pdf.setFont(mono?'courier':'Raleway',bold?'bold':'normal');pdf.setFontSize(size);pdf.setTextColor(25,35,29);};
 const newPage=()=>{pdf.addPage();y=22;};const ensure=h=>{if(y+h>bottom)newPage();};
 function text(str,{size=10,bold=false,mono=false,space=3}={}){font(size,bold,mono);const lines=pdf.splitTextToSize(String(str||'Not recorded'),width);const step=size*.46;for(const line of lines){ensure(step);font(size,bold,mono);pdf.text(line,left,y);y+=step;}y+=space;}
 function table(headers,rows,widths){const row=(values,header=false)=>{font(8,header);const all=values.map((v,i)=>pdf.splitTextToSize(String(v||'—'),widths[i]-4));let offset=0,total=Math.max(...all.map(a=>a.length));while(offset<total){ensure(12);let take=Math.min(total-offset,Math.max(1,Math.floor((bottom-y-4)/4)));const h=take*4+4;let x=left;all.forEach((lines,i)=>{pdf.setDrawColor(153,165,157);if(header){pdf.setFillColor(234,243,236);pdf.rect(x,y,widths[i],h,'FD');}else pdf.rect(x,y,widths[i],h);font(8,header);pdf.text(lines.slice(offset,offset+take),x+2,y+4,{lineHeightFactor:1.42});x+=widths[i];});y+=h;offset+=take;if(offset<total)newPage();}};row(headers,true);rows.forEach(r=>row(r));y+=5;}
 text('YEAR 11 | PAPER 1 PROGRAMMING',{size:10,bold:true});text('Fitness application: learning evidence',{size:20,bold:true});text(`${state.name} | ${state.className||'Teacher preview'}`,{size:12,bold:true});text(`Saved: ${new Date().toLocaleString()}`,{size:9});text('Files, validation, testing and subroutines. Your recorded answers, corrections and images follow.');
 for(const p of PAGES){if(p.id==='setup')continue;const container=document.createElement('div');container.innerHTML=p.html;const ids=[...new Set([...container.querySelectorAll('[data-field]')].map(x=>x.dataset.field))];const has=ids.some(id=>state.answers[id]!==undefined&&state.answers[id]!==''&&state.answers[id]!==false);if(p.id==='extension'&&!has){ensure(18);text('Extension: not attempted',{size:10});continue;}newPage();text(p.title,{size:17,bold:true});text(state.done[p.id]?'Marked complete by the learner':'Not marked complete',{size:8});
 if(p.id==='trace'){text(`Working format: ${state.answers.trace_route||'Not selected'}`,{bold:true});table(['Record','Person ID','Week','Distance','Matches?','Added?'],[0,1,2].map((i)=>[[1,2,14][i],...['person','week','distance','match','added'].map(k=>state.answers[`trace_${i}_${k}`]||'')]),[24,31,22,31,34,34]);state.extraTrace.forEach((v,i)=>text(`Additional trace note ${i+1}: ${v||'Not recorded'}`));}
 for(const id of ids){if(/^trace_\d_/.test(id)||/^test_\d_/.test(id)||id==='trace_route')continue;ensure(20);text(FIELDS[id]||id,{size:10,bold:true,space:1.5});const v=state.answers[id];text(typeof v==='boolean'?(v?'Yes':'No'):v||'Not recorded',{size:id.endsWith('_code')?9:10,mono:id.endsWith('_code')});}
 if(p.id==='validation'){ensure(20);text('Test results',{size:13,bold:true});table(['Input / test','Expected behaviour','Actual behaviour'],TESTS.map(([v,t],i)=>[v+'\n'+t,state.answers[`test_${i}_expected`]||'',state.answers[`test_${i}_actual`]||'']),[38,69,69]);}
 if(p.id==='learning'||p.id==='pitstop'){const target=p.id==='learning'?state.answers.focus:state.answers.next_focus;const concept=CONCEPTS.find(c=>c.title===target);const action=p.id==='learning'?focusActions[target]:(concept&&nextActions[target]?.[state.answers['end_'+concept.id]]);if(action)text('Suggested next step: '+action,{size:9});}
 if(p.id==='trace'||p.id==='validation'){for(const [i,im]of state.images[p.id].entries()){newPage();text(`${p.title} — image ${i+1}`,{size:13,bold:true});text(im.name,{size:8});const maxH=bottom-y-2,scale=Math.min(width/im.width,maxH/im.height);pdf.addImage(im.data,'JPEG',left,y,im.width*scale,im.height*scale,undefined,'FAST');y+=im.height*scale+5;}}
 }
 newPage();text('Support and review record',{size:16,bold:true});const used=Object.keys(state.reveals).filter(k=>state.reveals[k]);text('Opened reading / feedback: '+(used.length?used.map(k=>({'hint1':'validation hint 1','hint2':'validation hint 2','hint3':'validation support structure','starter_check':'starter feedback','test_check':'expected test outcomes','syntax_help':'file syntax help','saving_code':'saving routines','extension_hint':'extension hint'}[k]||k)).join(', '):'None recorded'));text('Syntax check used: '+(state.checks.syntax?'Yes':'No'));text('Worked trace viewed: '+(state.checks.trace?'Yes':'No'));text('Reflection choices describe the learner’s experience. They are not automatically assessed marks.',{size:9});
 const pages=pdf.getNumberOfPages();for(let i=1;i<=pages;i++){pdf.setPage(i);pdf.setDrawColor(190,200,194);pdf.line(17,285,193,285);font(8);pdf.text('YEAR 11 · ROBUST PROGRAMMING',17,291);pdf.text(`${i} / ${pages}`,193,291,{align:'right'});}pdf.save(slug(state.name)+'_Fitness_Lesson_Evidence.pdf');notify('PDF downloaded. Open it to check your evidence, then submit it in Teams.');}catch(e){notify('The PDF could not be created. Download a full backup first, then try again.');console.error(e);}finally{$('pdfBtn').disabled=false;}}
 $('pdfBtn').onclick=exportPDF;
 document.addEventListener('visibilitychange',()=>{if(document.hidden&&state)persist();});
 (async()=>{db=await openDB();const teacher=new URLSearchParams(location.search).get('teacher')==='1';if(teacher){await login('teacher','');return;}let active='';try{active=localStorage.getItem(STORAGE+'-active')||'';}catch{}if(active){const saved=await readSaved(active);if(saved&&[KIND,STORAGE].includes(saved.kind)){state=saved;state.kind=KIND;lastKey=active;$('landing').hidden=true;$('lesson').hidden=false;$('backupBtn').disabled=false;$('pdfBtn').disabled=false;render();$('saveStatus').textContent='Saved notebook restored';}}})();
})();
