'use strict';
(() => {
  const L=window.Lesson, $=id=>document.getElementById(id), esc=L.esc;
  const fresh=(name,className)=>({lessonId:L.id,version:1,name,className,page:0,answers:{},photos:{},checks:{},checkHistory:[],visited:[],ui:{test:0,extension:0},tutor:{seen:[]},supportLog:[],activity:[],updated:new Date().toISOString()});
  const N=window.Notebook={state:fresh('',''),teacher:false};
  let storageKey='',databasePromise=null,saveTimer=null,saving=false,savePromise=null,dirty=false,storeFailed=false,exportBusy=false;
  const storageId=(name,cls)=>L.id+':'+name.toLowerCase()+':'+cls.toLowerCase();
  const announce=message=>{$('live-message').textContent=message;};
  const cleanName=x=>String(x||'').trim().replace(/\s+/g,' ').slice(0,80);
  function db(){if(!databasePromise)databasePromise=new Promise((resolve,reject)=>{const r=indexedDB.open('cswithmrdave-lesson-notebooks',1);r.onupgradeneeded=()=>r.result.createObjectStore('notebooks');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.onblocked=()=>reject(Error('Browser storage is blocked.'));});return databasePromise;}
  async function readSaved(key){try{const d=await db();return await new Promise((resolve,reject)=>{const r=d.transaction('notebooks').objectStore('notebooks').get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}catch{try{return JSON.parse(localStorage.getItem(key)||'null');}catch{return null;}}}
  async function writeSaved(key,state){try{const d=await db();await new Promise((resolve,reject)=>{const tx=d.transaction('notebooks','readwrite');tx.objectStore('notebooks').put(state,key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}catch{localStorage.setItem(key,JSON.stringify(state));}}
  function persist(){if(!storageKey)return Promise.resolve();if(saving){dirty=true;return savePromise;}saving=true;savePromise=(async()=>{try{do{dirty=false;const key=storageKey,snapshot=structuredClone(N.state);await writeSaved(key,snapshot);}while(dirty);storeFailed=false;$('save-status').textContent='Saved on this browser · '+new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});}catch{storeFailed=true;$('save-status').textContent='Not saved: export a backup now.';announce('Browser storage could not save your work. Export a full backup now.');}finally{saving=false;}})();return savePromise;}
  function save(){N.state.updated=new Date().toISOString();$('save-status').textContent=storeFailed?'Not saved: export a backup now.':'Saving on this browser…';clearTimeout(saveTimer);saveTimer=setTimeout(persist,180);}
  const validImage=s=>typeof s==='string'&&/^data:image\/(png|jpeg);base64,[A-Za-z0-9+/=]+$/.test(s);
  function validated(data){
    if(data?.lessonId!==L.id||!cleanName(data.name)||typeof data.answers!=='object'||!data.answers)throw Error('Choose a notebook backup from this validation lesson.');
    const state=fresh(cleanName(data.name),String(data.className||'').trim().slice(0,40));
    state.page=Number.isInteger(data.page)?Math.max(0,Math.min(L.pages.length-1,data.page)):0;
    for(const q of L.questions)if(typeof data.answers[q.id]==='string')state.answers[q.id]=data.answers[q.id].slice(0,100000);
    if(data.photos&&typeof data.photos==='object')for(const [id,images] of Object.entries(data.photos))if(['plan','program',...L.EXTENSIONS.map((_,i)=>'ext-'+i)].includes(id)&&Array.isArray(images))state.photos[id]=images.filter(x=>validImage(x.data)).map(x=>({id:String(x.id).replace(/[^\w-]/g,'').slice(0,90),filename:String(x.filename||'Screenshot').slice(0,200),caption:String(x.caption||'').slice(0,1000),data:x.data}));
    if(data.checks&&typeof data.checks==='object')for(const [id,f] of Object.entries(data.checks))if(f&&typeof f.message==='string')state.checks[id]={message:f.message.slice(0,3000),correct:f.correct===null?null:!!f.correct,stale:!!f.stale,attempts:Number(f.attempts)||1,time:String(f.time||''),answer:String(f.answer||'').slice(0,2000)};
    state.checkHistory=Array.isArray(data.checkHistory)?data.checkHistory.slice(-300).filter(x=>x&&typeof x.answer==='string').map(x=>({id:String(x.id||'').slice(0,100),answer:x.answer.slice(0,3000),message:String(x.message||'').slice(0,3000),correct:x.correct===null?null:!!x.correct,time:String(x.time||'').slice(0,50)})):[];
    state.visited=Array.isArray(data.visited)?data.visited.filter(x=>L.pages.some(p=>p.id===x)):[];
    state.ui.test=Math.max(0,Math.min(8,Math.floor(Number(data.ui?.test)||0)));state.ui.extension=Math.max(0,Math.min(9,Math.floor(Number(data.ui?.extension)||0)));
    state.tutor={seen:Array.isArray(data.tutor?.seen)?data.tutor.seen.filter(x=>Array.isArray(x.steps)).map(x=>({age:String(x.age).slice(0,3),steps:x.steps.filter(i=>Number.isInteger(i)&&i>=0&&i<=4)})):[],step:Math.max(0,Math.min(4,Number(data.tutor?.step)||0))};
    state.supportLog=Array.isArray(data.supportLog)?data.supportLog.map(x=>({request:String(x.request||'').slice(0,100),note:String(x.note||'').slice(0,300),page:String(x.page||'').slice(0,80),time:String(x.time||'').slice(0,50)})):[];
    state.activity=Array.isArray(data.activity)?data.activity.slice(-300).map(x=>({action:String(x.action||'').slice(0,100),detail:String(x.detail||'').slice(0,300),time:String(x.time||'').slice(0,50)})):[];
    return state;
  }
  const log=(action,detail)=>{N.state.activity.push({action,detail,time:new Date().toISOString()});N.state.activity=N.state.activity.slice(-300);save();};
  async function start(name,cls){
    name=cleanName(name);cls=String(cls||'').trim().replace(/\s+/g,' ').slice(0,40);const teacher=name.toLowerCase()==='teacher'||new URLSearchParams(location.search).get('teacher')==='1';
    if(!name||(!teacher&&!cls)){throw Error('Enter your name and class.');}
    storageKey=storageId(name,cls);const old=await readSaved(storageKey);N.state=old?validated(old):fresh(name,cls);N.teacher=teacher;
    $('landing').hidden=true;$('lesson-shell').hidden=false;for(const id of ['export-backup','export-pdf','support-open'])$(id).disabled=false;
    document.body.classList.toggle('projector',teacher&&new URLSearchParams(location.search).get('projector')==='1');
    render();await persist();
  }
  const isAnswered=q=>typeof N.state.answers[q.id]==='string'&&N.state.answers[q.id].trim()!==''&&!(q.kind==='checkbox'&&N.state.answers[q.id]!=='yes');
  function route(){
    $('identity').textContent=N.teacher?'TEACHER PREVIEW · LOCAL ONLY':N.state.name+' · '+N.state.className;
    $('route').innerHTML=L.pages.map((p,i)=>{const qs=L.questions.filter(q=>q.section===p.section);let count=qs.filter(isAnswered).length,total=qs.length,unit='responses';if(p.id==='types'){count=L.TARGETS.filter(([id])=>N.state.answers['before-'+id]).length;total=6;unit='targets';}if(p.id==='pit'){count=L.TARGETS.filter(([id])=>N.state.answers['after-'+id]&&N.state.answers['phase-'+id]).length;total=6;unit='targets';}if(p.id==='testing'){count=L.TESTS.filter(t=>N.state.answers['test-'+t.id+'-actual']?.trim()&&['matched','different'].includes(N.state.answers['test-'+t.id+'-result'])).length+(N.state.answers['own-test-actual']?.trim()&&['matched','different'].includes(N.state.answers['own-test-result'])?1:0);total=9;unit='tests';}return `<button data-page="${i}" ${i===N.state.page?'aria-current="page"':''}><span>${String(i+1).padStart(2,'0')} · ${esc(p.label)}</span>${total?`<span class="count" aria-label="${count} of ${total} ${unit} recorded">${count}/${total}</span>`:''}</button>`;}).join('');
  }
  function render(){
    const page=L.pages[N.state.page];if(!N.state.visited.includes(page.id))N.state.visited.push(page.id);
    route();const teacher=N.teacher?`<details class="teacher-guide"><summary>Teacher guide / suggested responses</summary><p class="small">This is local preview only. It does not control other devices or show student answers from another notebook.</p><div class="teacher-switch"><button id="projector-toggle">${document.body.classList.contains('projector')?'Return to standard view':'Larger projector view'}</button></div><pre class="example-run">${esc(L.notes[page.id]||'')}</pre></details>`:'';
    $('content').innerHTML=teacher+page.render();$('previous-page').disabled=N.state.page===0;$('next-page').disabled=N.state.page===L.pages.length-1;$('page-position').textContent=`${N.state.page+1} of ${L.pages.length} · ${page.label}`;
    if(page.id==='fact2')drawTutor();if(page.id==='testing')drawTest();if(page.id==='extensions')drawExtension();if(page.id==='types'||page.id==='pit')updateKsu();if(page.id==='submit')completion();renderPhotos();save();window.scrollTo({top:0,behavior:'instant'});$('content').querySelector('h1')?.focus({preventScroll:true});
  }
  function go(index){N.state.page=Math.max(0,Math.min(L.pages.length-1,index));render();}
  function levelCount(prefix){return {independent:L.TARGETS.filter(([id])=>N.state.answers[prefix+id]==='independent').length,support:L.TARGETS.filter(([id])=>N.state.answers[prefix+id]==='support').length,notYet:L.TARGETS.filter(([id])=>N.state.answers[prefix+id]==='not-yet').length,blank:L.TARGETS.filter(([id])=>!N.state.answers[prefix+id]).length};}
  function updateKsu(){const host=$('ksu-summary');if(!host)return;const after=L.pages[N.state.page].id==='pit',c=levelCount(after?'after-':'before-');let text=`Self-reported evidence profile: ${c.independent}/6 independently; ${c.support}/6 with support; ${c.notYet}/6 not yet; ${c.blank}/6 not answered. This is not a grade.`;
    if(after){const old=levelCount('before-');text+=` At the start: ${old.independent}/6 independently, ${old.support}/6 with support, ${old.notYet}/6 not yet.`;const p={new:0,consolidating:0,treading:0,help:0};for(const [id] of L.TARGETS){const v=N.state.answers['phase-'+id];if(v)p[v]++;}text+=` Learning phases: ${p.new} new learning; ${p.consolidating} consolidating; ${p.treading} treading water; ${p.help} needing help. Feelings and evidence levels are separate.`;}
    host.textContent=text;
  }
  function completion(){const groups=['Do Now','Main Activity 1','Main Activity 2','Test evidence','Types of Learning','Learning Pit Stop','Plenary'];$('completion-summary').innerHTML=`<h2>Responses recorded — not marks</h2><ul class="progress-list">${groups.map(g=>{const qs=L.questions.filter(q=>q.section===g);return `<li><span>${esc(g)}</span><span>${qs.filter(isAnswered).length}/${qs.length} responses</span></li>`;}).join('')}</ul><p class="hint">A response count does not verify accuracy or successful execution. Your teacher will review the evidence. Optional extensions are not counted as core completion.</p>`;}
  function drawTest(){const index=N.state.ui.test;$('test-host').innerHTML=L.testHtml(index);$('test-position').textContent=`Test ${index+1} of 9`;$('content').querySelector('[data-test="previous"]').disabled=index===0;$('content').querySelector('[data-test="next"]').disabled=index===8;updateTestCount();}
  function updateTestCount(){if(!$('test-summary'))return;const records=L.TESTS.filter(t=>N.state.answers['test-'+t.id+'-actual']?.trim()&&['matched','different'].includes(N.state.answers['test-'+t.id+'-result'])).length;const own=!!N.state.answers['own-test-actual']?.trim()&&['matched','different'].includes(N.state.answers['own-test-result']);$('test-summary').textContent=`${records}/8 supplied tests have actual output and a comparison recorded. Independent test: ${own?'recorded':'not yet recorded'}. This count is not automatic verification of your program.`;}
  function drawExtension(){const i=N.state.ui.extension;$('extension-host').innerHTML=L.extensionHtml(i);renderPhotos();}
  function tutorPath(age){const invalid=age<5||age>18;return invalid?[0,1,2]:[0,1,3,4];}
  function drawTutor(){
    const selected=N.state.answers['tutor-case'],age=Number(selected),lines=L.READ_CODE.split('\n');
    if(!selected){$('tutor-lines').innerHTML=lines.map((s,i)=>`<div class="tutor-line"><span class="line-num">${i+1}</span><code>${esc(s)}</code></div>`).join('');$('tutor-explanation').textContent='Choose an example input above. Then use Next step to follow what the code does.';document.querySelectorAll('[data-tutor]').forEach(b=>b.disabled=true);return;}
    const path=tutorPath(age),step=Math.min(N.state.tutor.step||0,path.length-1);N.state.tutor.step=step;const active=path[step];
    $('tutor-lines').innerHTML=lines.map((s,i)=>`<div class="tutor-line ${i===active?'active':''} ${step>0&&!path.includes(i)?'skipped':''}" ${i===active?'aria-current="step"':''}><span class="line-num">${i+1}</span><code>${esc(s)}</code></div>`).join('');
    const below=age<5,above=age>18,invalid=below||above;
    const explanations={0:`input() receives the text "${age}". int() converts it to the whole number ${age}, stored in age. Nothing has been printed by a branch yet.`,1:below?`${age} < 5 is True. That is enough for or to be True, so the rejection branch is selected. Python does not need to evaluate the second comparison.`:`${age} < 5 is False. Check the other side: ${age} > 18 is ${above?'True':'False'}. The combined or condition is ${invalid?'True: the rejection branch is selected.':'False: the rejection line is skipped and else is selected.'}`,2:'Display Age not accepted. This input gets no price. The else branch is skipped.',3:'The rejection condition was False. Follow else: this age is accepted by the range rule.',4:'Display Age accepted. This demonstration stops here. Your independent program will choose a price inside this accepted path.'};
    $('tutor-explanation').innerHTML=`<div class="value-strip">Step ${step+1}/${path.length} · current line ${active+1} · <code>age = ${age}</code></div><p>${esc(explanations[active])}</p>`;
    document.querySelector('[data-tutor="previous"]').disabled=step===0;document.querySelector('[data-tutor="next"]').disabled=step===path.length-1;document.querySelector('[data-tutor="restart"]').disabled=false;
    let record=N.state.tutor.seen.find(r=>r.age===selected);if(!record){record={age:selected,steps:[]};N.state.tutor.seen.push(record);}if(!record.steps.includes(active))record.steps.push(active);save();
  }
  function recordCheck(id,correct,message,current){const old=N.state.checks[id],time=new Date().toISOString();N.state.checks[id]={correct,message,answer:current,attempts:(old?.attempts||0)+1,time};N.state.checkHistory.push({id,correct,message,answer:current,time});N.state.checkHistory=N.state.checkHistory.slice(-300);const host=$('feedback-'+id);if(host)host.innerHTML=`<div class="feedback ${correct===false?'revisit':''}" role="status">${esc(message)}</div>`;save();}
  function checkAnswer(id){
    if(id==='plan'){const items=[[4,'reject'],[5,'8'],[12,'8'],[13,'12'],[18,'12'],[19,'reject']];if(items.some(([a])=>!N.state.answers['plan-'+a])){announce('Choose an output for all six ages first.');const host=$('feedback-plan');host.innerHTML='<p class="feedback revisit" role="status">Choose an output for all six ages, then check.</p>';return;}const correct=items.filter(([a,k])=>N.state.answers['plan-'+a]===k),revisit=items.filter(([a,k])=>N.state.answers['plan-'+a]!==k).map(([a])=>a);recordCheck(id,correct.length===6,correct.length===6?'All six predictions match the rules. Next, write the conditions and explain their order.':`${correct.length}/6 predictions match. Revisit ages ${revisit.join(', ')}. Check acceptance first, then use 12 as the final cheaper age.`,items.map(([a])=>`Age ${a}: ${N.state.answers['plan-'+a]==='reject'?'Age not accepted':'Ticket price: RM'+N.state.answers['plan-'+a]}`).join('\n'));return;}
    const c=L.CHECKS[id],value=N.state.answers[c.key];if(!value){$('feedback-'+id).innerHTML='<p class="feedback revisit" role="status">Choose an answer before checking.</p>';return;}const ok=value===c.correct,question=L.questions.find(q=>q.id===c.key),label=question.options.find(([key])=>key===value)?.[1]||value;recordCheck(id,ok,(ok?'That matches. ':'Revisit this answer. ')+c.message,label);
  }
  function showModel(id){
    if(id.startsWith('test-')){const t=L.TESTS.find(t=>'test-'+t.id===id),pred=N.state.answers[id+'-expected'];if(!pred?.trim()){$('feedback-'+id).innerHTML='<p class="feedback revisit" role="status">Record your prediction first. Then compare it with the rule.</p>';return;}recordCheck(id,null,`Rule-based expected output: ${t.expected}. ${t.why} This does not check your IDE output.`,pred);return;}
    const ids=id==='plenary'?['exit-condition','exit-tests','exit-validation']:[id];if(ids.some(k=>!N.state.answers[k]?.trim())){$('feedback-'+id).innerHTML='<p class="feedback revisit" role="status">Write your response first, then compare with the explanation.</p>';return;}recordCheck(id,null,'Suggested explanation: '+L.models[id]+' Compare your reasoning and revise if needed; this is not an automatic mark.',ids.map(k=>N.state.answers[k]).join('\n'));
  }
  function renderPhotos(){document.querySelectorAll('[data-photos]').forEach(host=>{const group=host.dataset.photos;host.innerHTML=(N.state.photos[group]||[]).map(p=>`<figure class="photo-item"><img src="${p.data}" alt="${esc(p.caption||p.filename)}"><figcaption>${esc(p.filename)}</figcaption><label for="caption-${p.id}">Optional screenshot caption</label><input id="caption-${p.id}" data-caption="${p.id}" data-group="${group}" value="${esc(p.caption)}"><button data-remove-image="${p.id}" data-group="${group}">Remove this screenshot</button></figure>`).join('');});}
  function loadImage(file){return new Promise((resolve,reject)=>{if(!['image/png','image/jpeg','image/webp'].includes(file.type))return reject(Error('Use a PNG, JPEG or WebP screenshot.'));if(file.size>10*1024*1024)return reject(Error('This image is over 10 MB. Save a smaller screenshot before attaching.'));const reader=new FileReader();reader.onerror=()=>reject(Error('This screenshot could not be read.'));reader.onload=()=>{const img=new Image();img.onerror=()=>reject(Error('This file is not a readable image.'));img.onload=()=>{let data=reader.result;if(file.type==='image/webp'){const canvas=document.createElement('canvas');canvas.width=img.naturalWidth;canvas.height=img.naturalHeight;canvas.getContext('2d').drawImage(img,0,0);data=canvas.toDataURL('image/png');}resolve({id:crypto.randomUUID?.()||'img-'+Date.now()+'-'+Math.random().toString(36).slice(2),filename:file.name,caption:'',data});};img.src=reader.result;};reader.readAsDataURL(file);});}
  function filename(ext){const safe=x=>String(x||'').replace(/[^\p{L}\p{N}_-]+/gu,'_').slice(0,70)||'Student';return 'Y10_Validation_Ticket_'+safe(N.state.name)+'_'+safe(N.state.className||'Preview')+'.'+ext;}
  function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
  async function backup(){clearTimeout(saveTimer);await persist();download(new Blob([JSON.stringify(N.state,null,2)],{type:'application/json'}),filename('backup.json'));announce('Editable notebook backup downloaded. It includes your answers and screenshots.');}
  function displayAnswer(q,state){const val=state.answers[q.id];if(q.kind==='checkbox')return val==='yes'?'Yes — self-reported':'Not confirmed';if(!val?.trim())return 'Not answered';if(q.options)return q.options.find(([k])=>k===val)?.[1]||val;return val;}
  function buildPdf(state){
    if(!window.jspdf?.jsPDF)throw Error('The offline PDF library did not load. Export a backup and tell your teacher.');
    const doc=new window.jspdf.jsPDF({unit:'pt',format:'a4',compress:true});doc.addFileToVFS('Raleway.ttf',PDF_FONTS.regular);doc.addFont('Raleway.ttf','Raleway','normal');
    const W=doc.internal.pageSize.getWidth(),H=doc.internal.pageSize.getHeight(),margin=43,width=W-2*margin;let y=48,number=1;
    const normal=()=>doc.setFont('Raleway','normal');normal();
    const footer=()=>{normal();doc.setTextColor(90);doc.setFontSize(8);doc.text('Year 10 · Validation and decisions',margin,H-25);doc.text(String(number),W-margin,H-25,{align:'right'});doc.setTextColor(20);};
    const newPage=()=>{footer();doc.addPage();number++;y=48;};
    const room=h=>{if(y+h>H-48)newPage();};
    function textHeight(str,size,mono=false){doc.setFont(mono?'courier':'Raleway','normal');doc.setFontSize(size);return String(str??'').replace(/\t/g,'    ').split('\n').reduce((h,p)=>h+doc.splitTextToSize(p||' ',width).length*size*1.55,0);}
    function text(str,size=11,gap=8,mono=false){doc.setFont(mono?'courier':'Raleway','normal');doc.setFontSize(size);const paragraphs=String(str??'').replace(/\t/g,'    ').split('\n');for(const paragraph of paragraphs){const lines=doc.splitTextToSize(paragraph||' ',width),blockHeight=lines.length*size*1.55;if(blockHeight<H-100)room(blockHeight+gap);for(const line of lines){room(size*1.55);doc.setFont(mono?'courier':'Raleway','normal');doc.setFontSize(size);doc.text(line,margin,y);y+=size*1.55;}}y+=gap;normal();}
    function heading(title){room(125);y+=8;doc.setDrawColor(175);doc.setLineWidth(.5);doc.line(margin,y-7,W-margin,y-7);doc.setTextColor(0,105,48);text(title,15,9);doc.setTextColor(20);}
    function addPhotos(group){for(const image of state.photos[group]||[]){room(100);text('Screenshot: '+image.filename,10,4);if(image.caption)text('Caption: '+image.caption,10,7);const properties=doc.getImageProperties(image.data);let scale=Math.min(width/properties.width,(H-110)/properties.height);if(y+properties.height*scale>H-50){newPage();text('Screenshot continued: '+image.filename,10,8);}scale=Math.min(width/properties.width,(H-y-52)/properties.height);doc.addImage(image.data,image.data.startsWith('data:image/png')?'PNG':'JPEG',margin,y,properties.width*scale,properties.height*scale);y+=properties.height*scale+15;}}
    text('YEAR 10 COMPUTER SCIENCE',17,8);text('Validate, decide, test',22,17);text('OxfordAQA International GCSE 9210',12,14);text('Name: '+state.name,12,7);text('Class: '+(state.className||'Teacher preview'),12,7);text('Evidence exported: '+new Date().toLocaleString(),10,20);heading('Lesson purpose');text('WAGBA: using validation rules and purposeful tests to make reliable program decisions.');text('Knowledge: validation, selection, normal, boundary and erroneous test data.');text('Skills: plan a decision, write Python, and record results from the IDE.');text('Understanding: validate before deciding and justify tests beyond one successful run.');heading('Evidence notes');text('This is a saved student notebook, not an automatically marked examination. Unanswered items are shown. Comparisons, reflection levels and submission confirmations are self-reported. Python runs on the student device; the website does not execute it.');text('Ticket rules: accept ages 5–18 inclusive. Ages 5–12 pay RM8; ages 13–18 pay RM12. Reject any other age without displaying a price.');text('Scope: range validation of whole-number input. Words, decimals and repeated prompting are not handled in this lesson.');newPage();
    const sections=[...new Set(L.questions.map(q=>q.section))];
    for(const section of sections){heading(section);if(section.startsWith('Extension ')){const i=Number(section.match(/^Extension (\d+)/)[1])-1;text('Task: '+L.EXTENSIONS[i].task,10,9);text('Test to try: '+L.EXTENSIONS[i].test.replace(/→/g,'produces'),10,9);}
      for(const q of L.questions.filter(x=>x.section===section)){const response=displayAnswer(q,state),blockHeight=textHeight(q.label,10)+textHeight(response,11,!!q.code)+13;room(blockHeight<H-100?blockHeight:45);text(q.label,10,3);text(response,11,10,!!q.code);}
      if(section==='Main Activity 1')addPhotos('plan');if(section==='Main Activity 2')addPhotos('program');if(section.startsWith('Extension '))addPhotos('ext-'+(Number(section.match(/^Extension (\d+)/)[1])-1));
      if(section==='Learning Pit Stop'){const profile=prefix=>{const vals=L.TARGETS.map(([id])=>state.answers[prefix+id]);return `${vals.filter(x=>x==='independent').length}/6 independently; ${vals.filter(x=>x==='support').length}/6 with support; ${vals.filter(x=>x==='not-yet').length}/6 not yet; ${vals.filter(x=>!x).length}/6 unanswered.`;};text('Starting evidence profile: '+profile('before-'),10,7);text('Final evidence profile: '+profile('after-'),10,7);text('These are self-reported evidence levels, not grades. Learning phases are recorded separately for each target.',10,10);}
    }
    const checkLabel=id=>id==='plan'?'Main Activity 1 predictions':id==='plenary'?'Plenary explanations':id.startsWith('test-')?'Prediction for age '+id.slice(5):L.questions.find(q=>q.id===id)?.label||id;
    heading('Self-check feedback and model comparisons');if(!Object.keys(state.checks).length)text('No checks or model comparisons recorded.');for(const [id,f] of Object.entries(state.checks)){text(checkLabel(id)+' · '+f.attempts+' check(s)'+(f.stale?' · response changed since this check':''),10,3);text('Answer at the latest check: '+(f.answer||'Not recorded'),10,4);text(f.message,10,10);}
    heading('Guided code walkthrough');if(!state.tutor.seen.length)text('No walkthrough inputs explored.');for(const t of state.tutor.seen)text(`Input ${t.age}: viewed lines ${t.steps.map(i=>i+1).join(', ')}.`,10,7);
    if(state.checkHistory?.length){heading('Check history — learning through corrections');for(const [i,attempt] of state.checkHistory.entries()){text(`${i+1}. ${checkLabel(attempt.id)} — ${attempt.correct===null?'model comparison':attempt.correct?'matched':'revisit'}`,10,3);text('Response at this check: '+attempt.answer,10,5);}}
    heading('Help / pause requests — local only');if(!state.supportLog.length)text('No support-card requests recorded.');for(const s of state.supportLog)text(`${s.request} · ${s.page}${s.note?' · '+s.note:''}`,10,7);
    heading('Notebook activity');text('Pages visited: '+(state.visited.map(id=>L.pages.find(p=>p.id===id)?.label||id).join('; ')||'None'),10,8);for(const event of state.activity)text(event.action+': '+event.detail,9,5);
    heading('Save and submit in Microsoft Teams');text('Open this PDF and check all answers, code and complete screenshots. Open the correct assignment in your Year 10 Computer Science class. Attach the PDF using Add work / upload, then select Turn in. Check the submission status in Teams. This website does not upload or confirm submission.');footer();return doc;
  }
  async function exportPdf(){if(exportBusy)return;exportBusy=true;$('export-pdf').disabled=true;$('export-message').textContent='Preparing the complete notebook. Please wait.';$('export-dialog').showModal();try{clearTimeout(saveTimer);await persist();log('PDF export','Downloaded notebook evidence; this is not a Teams submission.');const snapshot=structuredClone(N.state);const doc=buildPdf(snapshot);doc.save(filename('pdf'));$('export-message').textContent='PDF downloaded. Unfinished items are included and labelled. Check the file before submitting.';}catch(error){$('export-message').textContent='PDF could not be completed: '+error.message+'. Use Backup to preserve all work, and tell your teacher.';}finally{exportBusy=false;$('export-pdf').disabled=false;}}
  function recordInput(el){const id=el.dataset.answer;if(!id)return;const value=el.type==='checkbox'?(el.checked?'yes':'no'):el.value,changed=N.state.answers[id]!==value;N.state.answers[id]=value;const checkId=id.startsWith('plan-')&&/^plan-\d+$/.test(id)?'plan':id.startsWith('exit-')?'plenary':id.endsWith('-expected')?id.replace(/-expected$/,''):id;const feedback=$('feedback-'+checkId);if(changed&&N.state.checks[checkId]){N.state.checks[checkId].stale=true;if(feedback)feedback.innerHTML='<p class="feedback revisit" role="status">Response changed since your last check. Check or compare it again.</p>';}save();route();if(id.startsWith('before-')||id.startsWith('after-')||id.startsWith('phase-'))updateKsu();if(L.pages[N.state.page].id==='testing')updateTestCount();}
  document.addEventListener('input',event=>{const el=event.target;if(el.dataset.answer)recordInput(el);if(el.dataset.caption){const image=N.state.photos[el.dataset.group]?.find(x=>x.id===el.dataset.caption);if(image){image.caption=el.value;save();}}});
  document.addEventListener('change',async event=>{const el=event.target;if(el.dataset.answer){recordInput(el);if(el.id==='tutor-case'){N.state.tutor.step=0;drawTutor();}}
    if(el.id==='extension-choice'){N.state.ui.extension=Number(el.value);drawExtension();save();}
    if(el.dataset.upload){const group=el.dataset.upload,err=$('upload-error-'+group);err.textContent='';el.disabled=true;try{for(const file of Array.from(el.files||[])){const photo=await loadImage(file);(N.state.photos[group]??=[]).push(photo);}renderPhotos();save();await persist();}catch(e){err.textContent=e.message;renderPhotos();save();}finally{el.disabled=false;el.value='';}}
  });
  document.addEventListener('click',async event=>{const el=event.target.closest('button');if(!el)return;
    if(el.dataset.page!==undefined){go(Number(el.dataset.page));return;}
    if(el.dataset.check){checkAnswer(el.dataset.check);return;}if(el.dataset.model){showModel(el.dataset.model);return;}
    if(el.dataset.copy){const text=L.codeSnippets[el.dataset.copy];try{await navigator.clipboard.writeText(text);$('copy-'+el.dataset.copy).textContent=' Copied. Paste it into your own IDE.';log('Code copied',el.dataset.copy);}catch{$('copy-'+el.dataset.copy).textContent=' Select the code above and copy it with your keyboard.';}return;}
    if(el.dataset.tutor){const path=tutorPath(Number(N.state.answers['tutor-case']));N.state.tutor.step=el.dataset.tutor==='restart'?0:Math.max(0,Math.min(path.length-1,(N.state.tutor.step||0)+(el.dataset.tutor==='next'?1:-1)));drawTutor();return;}
    if(el.dataset.test){N.state.ui.test=Math.max(0,Math.min(8,N.state.ui.test+(el.dataset.test==='next'?1:-1)));drawTest();save();$('test-host').scrollIntoView({block:'start'});return;}
    if(el.dataset.removeImage){if(!confirm('Remove this screenshot from your notebook?'))return;N.state.photos[el.dataset.group]=N.state.photos[el.dataset.group].filter(p=>p.id!==el.dataset.removeImage);renderPhotos();save();return;}
    if(el.dataset.support){const request=el.dataset.support;$('support-card').textContent=request;$('support-card').hidden=false;N.state.supportLog.push({request,page:L.pages[N.state.page].label,note:'',time:new Date().toISOString()});save();return;}
    if(el.id==='projector-toggle'){document.body.classList.toggle('projector');el.textContent=document.body.classList.contains('projector')?'Return to standard view':'Larger projector view';}
  });
  $('login-form').addEventListener('submit',async event=>{event.preventDefault();$('login-error').textContent='';$('start-button').disabled=true;try{await start($('student-name').value,$('student-class').value);}catch(e){$('login-error').textContent=e.message;}finally{$('start-button').disabled=false;}});
  $('student-name').addEventListener('input',()=>{$('student-class').required=$('student-name').value.trim().toLowerCase()!=='teacher';});
  $('restore-file').addEventListener('change',async event=>{const file=event.target.files?.[0];if(!file)return;try{if(file.size>100*1024*1024)throw Error('This backup is over 100 MB. Ask your teacher for help restoring it.');const restored=validated(JSON.parse(await file.text()));storageKey=storageId(restored.name,restored.className);const existing=await readSaved(storageKey);if(existing&&!confirm('Replace the saved notebook for this name and class with this backup? Export the existing notebook first if needed.'))return;N.state=restored;N.teacher=restored.name.toLowerCase()==='teacher';$('landing').hidden=true;$('lesson-shell').hidden=false;['export-backup','export-pdf','support-open'].forEach(id=>$(id).disabled=false);render();await persist();$('restore-error').textContent='';}catch(e){$('restore-error').textContent='Could not restore: '+e.message;}finally{event.target.value='';}});
  $('route-toggle').onclick=()=>{const expanded=$('route-toggle').getAttribute('aria-expanded')==='true';$('route-toggle').setAttribute('aria-expanded',String(!expanded));$('route').hidden=expanded;};
  $('previous-page').onclick=()=>go(N.state.page-1);$('next-page').onclick=()=>go(N.state.page+1);$('export-backup').onclick=backup;$('export-pdf').onclick=exportPdf;
  async function home(){if(!N.state.name)return;if(!confirm('Return to the name page? Your notebook will stay saved on this browser.'))return;clearTimeout(saveTimer);await persist();$('landing').hidden=false;$('lesson-shell').hidden=true;['export-backup','export-pdf','support-open'].forEach(id=>$(id).disabled=true);document.body.classList.remove('projector');storageKey='';$('student-name').focus();$('save-status').textContent='Your own lesson notebook';}
  $('change-student').onclick=home;$('home-link').onclick=event=>{event.preventDefault();home();};
  $('support-open').onclick=()=>{$('support-card').hidden=true;$('support-note').value='';$('support-dialog').showModal();};
  $('support-close').onclick=()=>{const last=N.state.supportLog.at(-1);if(last&&!$('support-card').hidden){last.note=$('support-note').value.slice(0,300);save();}$('support-dialog').close();};
  $('support-dialog').addEventListener('cancel',()=>{const last=N.state.supportLog.at(-1);if(last&&!$('support-card').hidden){last.note=$('support-note').value.slice(0,300);save();}});
  $('export-close').onclick=()=>{if(!exportBusy)$('export-dialog').close();};
  document.addEventListener('visibilitychange',()=>{if(document.hidden){clearTimeout(saveTimer);persist();}});
  document.addEventListener('toggle',event=>{if(event.target.tagName==='DETAILS'&&event.target.open&&N.state.name&&!N.teacher){log('Reading / support opened',L.pages[N.state.page].label+' · '+(event.target.querySelector('summary')?.textContent||''));}},true);
  window.addEventListener('beforeunload',event=>{if(saving||dirty||storeFailed){event.preventDefault();event.returnValue='';}});
  Object.assign(N,{go,persist,buildPdf,backup,exportPdf,validated,tutorPath});
  $('sidebar').insertBefore(document.querySelector('.sidebar-intent'),$('route-toggle'));
  if(matchMedia('(max-width:760px)').matches){$('route').hidden=true;$('route-toggle').setAttribute('aria-expanded','false');}
  if(new URLSearchParams(location.search).get('teacher')==='1'){start('teacher','').catch(e=>$('login-error').textContent=e.message);}
})();
