'use strict';
(() => {
  const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const answer = id => window.Notebook?.state?.answers?.[id] ?? '';
  const questions = [];
  const define = (section, id, label, options = {}) => { questions.push({section,id,label,...options}); return id; };
  const q = (section, entries) => entries.forEach(([id,label,opts]) => define(section,id,label,opts));
  const choices = opts => ({options:opts});
  const LEVELS = [['not-yet','Not yet — I cannot show this yet'],['support','With support — an example or prompt helps'],['independent','Independently — I can show this without a model']];
  const PHASES = [['new','New learning — unfamiliar, but I am making progress'],['consolidating','Consolidating — practice is making this more secure'],['treading','Treading water — this is easy; I need more challenge'],['help','Drowning / needing help — I need support to move forward']];
  const TARGETS = [
    ['K1','Knowledge','Explain validation and selection.','Identify a rule and the decision that checks it.'],
    ['K2','Knowledge','Distinguish normal, boundary and erroneous test data.','Identify an example of each and its purpose.'],
    ['S1','Skills','Write a condition that rejects ages outside the accepted range.','Show a condition that rejects both 4 and 19, but accepts 5 and 18.'],
    ['S2','Skills','Build the ticket decision and record actual test results.','Show working code, IDE output and completed test records.'],
    ['U1','Understanding','Explain why validation must happen before a price decision.','Explain why an invalid age must not receive a price.'],
    ['U2','Understanding','Justify tests around both acceptance limits and the price change.','Explain what the tests at 4/5, 18/19 and 12/13 investigate.']
  ];
  q('Prepare', [['prepare-job','What must the program check before deciding a price?',{rows:2}]]);
  q('Do Now', [
    ['starter1','What data type does age store after age = int(input("Age: "))?',choices([['integer','Integer — a whole number'],['string','String — text'],['boolean','Boolean — True or False']])],
    ['starter2','The accepted range is 5–18 inclusive. What should happen for age 19?',choices([['reject','Display Age not accepted; no price'],['price8','Display Ticket price: RM8'],['price12','Display Ticket price: RM12']])],
    ['starter3','Which condition identifies an age outside 5–18?',choices([['or','age < 5 or age > 18'],['and','age < 5 and age > 18'],['inside','age >= 5 and age <= 18']])],
    ['starter4','Why must a rejected age not be used to choose a ticket price?',{rows:2,placeholder:'The age breaks… so the program should…'}]
  ]);
  TARGETS.forEach(([id,area,text]) => define('Types of Learning','before-'+id,area+' · '+text,choices(LEVELS)));
  q('Types of Learning', [['focus-target','Which target will you get better at first?',choices(TARGETS.map(([id,a,t])=>[id,`${id} · ${a}: ${t}`]))],['focus-action','What will you do to get better at this target?',{rows:2,placeholder:'For S1, I will trace the two conditions with ages 4 and 19.'}]]);
  q('Fact 1: validate before deciding', [['fact1','Does an accepted age prove that the person entered their true age? Explain.',{rows:2}]]);
  for (const age of [4,5,12,13,18,19]) define('Main Activity 1','plan-'+age,`Predict the output for age ${age}`,choices([['reject','Age not accepted'],['8','Ticket price: RM8'],['12','Ticket price: RM12']]));
  q('Main Activity 1', [['plan-reject','Write a Python condition for an age outside 5–18.',{rows:2,code:true}],['plan-price','After validation has accepted the age, write a condition for the RM8 category.',{rows:2,code:true}],['plan-algorithm','Write the steps of your algorithm, in order.',{rows:5,placeholder:'1. Obtain the age.\n2. …'}],['plan-order','Why must the rejection decision protect the price decision?',{rows:2}]]);
  q('Fact 2: read and trace the code', [['tutor-case','Input selected for the guided validation example',choices([['4','4 — rejected'],['5','5 — accepted minimum'],['12','12 — accepted'],['13','13 — accepted'],['18','18 — accepted maximum'],['19','19 — rejected']])],['fact2','When age is 19, can line 5 display Age accepted?',choices([['no','No — the rejection branch runs instead'],['yes','Yes — all print statements always run']])]]);
  q('Main Activity 2', [['main2-code','Paste your completed Python ticket program.',{rows:11,code:true}],['main2-output','Paste one accepted run and one rejected run from your IDE.',{rows:6,code:true}],['main2-explain','Explain which path your program follows for age 13.',{rows:3}],['main2-help','Which support did you use?',choices([['none','No model or hint — procedural help only, if needed'],['syntax','Syntax reference or one reminder'],['scaffold','Starting code or a structural hint'],['model','Worked through the example with teacher support']])]]);
  const TESTS = [
    {id:'4',age:4,purpose:'Just below the minimum',expected:'Age not accepted',why:'4 is immediately below 5. It must be rejected and must not receive a price.'},
    {id:'5',age:5,purpose:'At the minimum',expected:'Ticket price: RM8',why:'5 is the first accepted age. It must be accepted, not rejected by a <= 5 mistake.'},
    {id:'18',age:18,purpose:'At the maximum',expected:'Ticket price: RM12',why:'18 is the last accepted age. It must be accepted, not rejected by a >= 18 mistake.'},
    {id:'19',age:19,purpose:'Just above the maximum',expected:'Age not accepted',why:'19 is immediately above 18. It must be rejected before any price is displayed.'},
    {id:'12',age:12,purpose:'Last age in the cheaper category',expected:'Ticket price: RM8',why:'12 tests the final age in the RM8 price category.'},
    {id:'13',age:13,purpose:'First age in the other price category',expected:'Ticket price: RM12',why:'13 tests the first age in the RM12 price category. Together, 12 and 13 test the price transition.'},
    {id:'8',age:8,purpose:'Normal valid input in the cheaper category',expected:'Ticket price: RM8',why:'8 is a typical valid value away from an acceptance limit or price transition.'},
    {id:'15',age:15,purpose:'Normal valid input in the other category',expected:'Ticket price: RM12',why:'15 is typical valid input in the other price category.'}
  ];
  const MATCH = choices([['matched','Actual output matched my prediction'],['different','Actual output differed — correction needed'],['not-run','I have not run this test yet']]);
  TESTS.forEach(t=>q('Test evidence',[['test-'+t.id+'-expected',`Age ${t.age} — predicted output`,{rows:2,code:true}],['test-'+t.id+'-actual',`Age ${t.age} — actual output from my IDE`,{rows:2,code:true}],['test-'+t.id+'-result',`Age ${t.age} — comparison`,MATCH]]));
  q('Test evidence', [['own-test-value','My additional test input',{rows:1,placeholder:'Choose another whole-number age.'}],['own-test-type','My additional test category',choices([['normal','Normal — typical valid input'],['boundary','Boundary — at or just beside a limit'],['erroneous','Erroneous — breaks the acceptance rule']])],['own-test-why','Why did you choose this additional input?',{rows:2}],['own-test-expected','My additional test — predicted output',{rows:2,code:true}],['own-test-actual','My additional test — actual output',{rows:2,code:true}],['own-test-result','My additional test — comparison',MATCH],['test-correction','Describe a failed test and your correction, or state that all the tests you ran matched.',{rows:3}],['test-justify','Why would testing only age 8 be insufficient?',{rows:3}]]);
  const EXTENSIONS = [
    {title:'A more informative ticket',level:'Build confidence',task:'Keep the original rules. Include the accepted age in the price output so a fair organiser can check the result. Rejected ages must still show only the rejection message.',steps:['Keep the age check and both price categories.','Use print with comma-separated values to include the accepted age.','Check both one accepted input and one rejected input.'],run:'Age: 8\nAge 8 — Ticket price: RM8',test:'Age 19 must display Age not accepted, with no ticket price.',hint:'You have used print("Age:", age). You can use the same comma-separated output pattern here.'},
    {title:'Name the rules once',level:'Build confidence',task:'The organiser wants to maintain the program easily. Store 5, 18 and 12 in meaningfully named constants, then use those names in the conditions. The ticket rules must not change.',steps:['Define MIN_AGE, MAX_AGE and CHEAPER_MAX before the input.','Replace the corresponding numbers in your conditions with their names.','Run your existing boundary tests again.'],run:'Age: 5\nTicket price: RM8',test:'Check ages 4, 5, 18 and 19. The results must be unchanged.',hint:'In Python, uppercase names communicate the intention that a value is a constant; Python does not prevent reassignment.'},
    {title:'The price changes one year earlier',level:'Apply and test',task:'The organiser changes the cheaper category to ages 5–11. Ages 12–18 now pay RM12. The accepted age range stays 5–18. Update only the price decision and justify the most useful new tests.',steps:['Identify the condition that controls the cheaper category.','Change its limit, without changing validation.','Test the new price transition and a rejected age.'],run:'Age: 12\nTicket price: RM12',test:'Age 11 → RM8; age 12 → RM12; age 19 → Age not accepted.',hint:'The last cheaper age has moved from 12 to 11. Which comparison uses that number?'},
    {title:'Three ticket categories',level:'Apply and test',task:'Return to the original accepted range of 5–18. This version has three prices: ages 5–8 pay RM5, ages 9–12 pay RM8, and ages 13–18 pay RM12. Invalid ages must never receive a price.',steps:['Validate the age first.','Use if / elif / else inside the accepted path, or an equivalent protected selection chain.','Choose tests on both sides of each price transition.'],run:'Age: 9\nTicket price: RM8',test:'Age 8 → RM5; 9 → RM8; 12 → RM8; 13 → RM12.',hint:'After invalid ages are excluded, compare the accepted age with 8, then with 12.'},
    {title:'A small group booking',level:'Stretch: two inputs',task:'Use the original age and price rules. One booking buys 1–4 tickets for people in the same age category. Ask for the age and ticket quantity. Reject an invalid age or a quantity outside 1–4. Otherwise display the total price.',steps:['Use two whole-number inputs.','Validate both inputs before calculating a total.','Multiply the valid quantity by the appropriate ticket price.'],run:'Age: 13\nTickets: 3\nTotal price: RM36',test:'Age 8 with 4 tickets → RM32. A quantity of 0 or 5 must be rejected.',hint:'A quantity check follows the same pattern as the age check. You do not need a loop or a list.'},
    {title:'A member discount',level:'Stretch: nested decisions',task:'Use the original ticket rules. Ask whether the visitor is a member. For this exercise accept only the exact lowercase strings yes or no; reject any other response. A member receives RM2 off the accepted ticket price.',steps:['Validate the age and the membership response.','Choose the original price for a valid age.','Use selection to apply the discount only for yes.'],run:'Age: 13\nMember (yes/no): yes\nTicket price: RM10',test:'Age 8 with no → RM8; age 8 with yes → RM6. An invalid age must still receive no price.',hint:'For this exercise there is no automatic case conversion. Validate membership with comparisons to "yes" and "no".'},
    {title:'Check the booking code too',level:'Stretch: combine known checks',task:'Use the original age and price rules. A booking also needs a code of exactly six characters. Both the age and the code length must be valid before a ticket price is displayed.',steps:['Read the code as text.','Use len(code) to check its length.','Check a valid code, a five-character code and a seven-character code.'],run:'Age: 8\nBooking code: FAIR26\nTicket price: RM8',test:'Age 8 with FAIR2 must be rejected; age 19 with FAIR26 must also be rejected.',hint:'This is a length check, not authentication. A six-character code is not proof that a real booking exists.'},
    {title:'Transfer: a grade checker',level:'Transfer the same reasoning',task:'A teacher enters a whole-number mark from 0 to 100 inclusive. Reject values outside this range. For accepted marks, display Pass for 50 or above and Not yet passed below 50. Use the same validate-then-decide approach.',steps:['Write the acceptance and outcome rules first.','Build selection using one integer input.','Choose tests around 0, 100 and the pass threshold.'],run:'Mark: 50\nPass',test:'Mark -1 → Mark not accepted; 49 → Not yet passed; 50 → Pass; 101 → Mark not accepted.',hint:'Acceptance boundaries and the outcome threshold are different limits. Test both.'},
    {title:'Transfer: a username request',level:'Transfer to text',task:'A school app accepts a username of 5–8 characters inclusive. Reject a shorter or longer username. If its length is valid, display Username format accepted. Explain why that does not prove the username is unique or belongs to that person.',steps:['Use input without int because a username is text.','Store or use len(username).','Choose normal, boundary and an empty-string test.'],run:'Username: Maya7\nUsername format accepted',test:'Abcd → rejected; Maya7 → accepted; Student8 → accepted; Student99 → rejected.',hint:'The earlier string lesson used len. This exercise needs no password, list, database or loop.'},
    {title:'Find the unsafe path',level:'Analyse and repair',task:'A developer wrote the faulty program below. Explain what it prints for age 4 and for age 19. Repair the structure so neither invalid age receives a price. Show a failing run before the repair and the corrected run afterwards.',steps:['Predict the output without running first.','Run the faulty version in your IDE and check the prediction.','Repair it and retest both invalid ages plus one valid age.'],faulty:'age = int(input("Age: "))\nif age < 5 or age > 18:\n    print("Age not accepted")\nif age <= 12:\n    print("Ticket price: RM8")\nelse:\n    print("Ticket price: RM12")',run:'Required after repair, for age 19:\nAge not accepted',test:'Age 4 and age 19 must each show only Age not accepted. Age 13 must show Ticket price: RM12.',hint:'The second if starts a separate decision. It is not protected by the earlier rejection.'}
  ];
  EXTENSIONS.forEach((e,i)=>q('Extension '+(i+1)+': '+e.title,[['ext-'+i+'-code','My Python code',{rows:9,code:true}],['ext-'+i+'-output','My IDE output and test evidence',{rows:5,code:true}],['ext-'+i+'-explain','My explanation, correction or test justification',{rows:3}],['ext-'+i+'-status','My extension status',choices([['started','Started — not yet tested'],['tested','Tested — I have recorded results'],['help','I need help to finish this challenge']])]]));
  TARGETS.forEach(([id,area,text])=>{
    define('Learning Pit Stop','after-'+id,area+' · '+text,choices(LEVELS));
    define('Learning Pit Stop','phase-'+id,'Learning phase for '+id,choices(PHASES));
  });
  q('Learning Pit Stop',[['pit-evidence','Which target has improved? Quote a specific piece of your work.',{rows:3,placeholder:'For S1, my program rejected ages 4 and 19 and accepted 5 and 18.'}],['pit-action','What is your next action, or which exact step needs help?',{rows:2}]]);
  q('Plenary',[['exit-condition','The cheaper age range changes to 5–11. What price condition should change?',{rows:2,code:true}],['exit-tests','Which two ages best test the new price transition? Explain.',{rows:2}],['exit-validation','Should the age acceptance limits change too? Explain.',{rows:2}]]);
  q('Save and submit',[['submit-checked','I opened my PDF and checked the answers and screenshots',{kind:'checkbox'}],['submit-teams','I attached the PDF to the correct Teams assignment and selected Turn in',{kind:'checkbox'}]]);
  const field = id => {
    const item = questions.find(x=>x.id===id), value = answer(id);
    if (!item) throw Error('Unknown question '+id);
    const {label,options,rows=3,placeholder='',code=false,kind} = item;
    if (kind==='checkbox') return `<label class="submission-check" for="${id}"><input type="checkbox" id="${id}" data-answer="${id}" ${value==='yes'?'checked':''}>${esc(label)}</label>`;
    const labelHtml=`<label for="${id}">${esc(label)}</label>`;
    if(options)return labelHtml+`<select id="${id}" data-answer="${id}"><option value="">Choose an answer…</option>${options.map(([k,t])=>`<option value="${esc(k)}" ${value===k?'selected':''}>${esc(t)}</option>`).join('')}</select>`;
    if(rows===1)return labelHtml+`<input id="${id}" data-answer="${id}" value="${esc(value)}" placeholder="${esc(placeholder)}">`;
    return labelHtml+`<textarea id="${id}" data-answer="${id}" rows="${rows}" ${code?'class="code-answer" spellcheck="false"':''} placeholder="${esc(placeholder)}">${esc(value)}</textarea>`;
  };
  const codeBlock=(text,id)=>{const block=`<div class="code-block"><pre><code>${esc(text)}</code></pre><button class="copy-code" data-copy="${id}">Copy this code (no line numbers)</button><span id="copy-${id}" class="hint" role="status"></span></div>`;return id==='validation-start'?`<details><summary>Copy the un-numbered example into your IDE</summary>${block}</details>`:block;};
  const savedFeedback=id=>{const f=window.Notebook?.state?.checks?.[id];return f?`<div class="feedback ${f.correct===false||f.stale?'revisit':''}" role="status">${esc(f.stale?'Response changed since your last check. Check or compare it again.':f.message)}</div>`:'';};
  const check=id=>`<button class="check-button" data-check="${id}">Check my answer</button><div id="feedback-${id}">${savedFeedback(id)}</div>`;
  const head=(title,time,tag)=>`<div class="stage-meta"><span class="tag">${tag}</span><span>${time} · suggested classroom time, not a countdown</span></div><h1 tabindex="-1">${title}</h1>`;
  const screenshot=(id,title)=>`<section class="evidence-section"><h3>${title}</h3><label for="upload-${id}">Add one or more screenshots (PNG, JPEG or WebP)</label><input id="upload-${id}" type="file" data-upload="${id}" accept="image/png,image/jpeg,image/webp" multiple><p class="hint">Capture the complete relevant code/output. Check that other students’ details are not visible. Images are saved and exported without cropping.</p><div class="photo-list" data-photos="${id}"></div><p class="error" id="upload-error-${id}" role="alert"></p></section>`;
  const rules=()=>`<ul class="rule-list"><li><strong>Accept ages</strong> 5–18 inclusive (both 5 and 18 are allowed).</li><li><strong>Ages 5–12</strong> Ticket price: RM8</li><li><strong>Ages 13–18</strong> Ticket price: RM12</li><li><strong>Other ages</strong> Age not accepted — do not display any price.</li></ul>`;
  const hint=(title,text)=>`<details><summary>${title}</summary><p>${text}</p></details>`;
  const READ_CODE='age = int(input("Age: "))\nif age < 5 or age > 18:\n    print("Age not accepted")\nelse:\n    print("Age accepted")';
  const MODEL_CODE='age = int(input("Age: "))\nif age < 5 or age > 18:\n    print("Age not accepted")\nelse:\n    if age <= 12:\n        print("Ticket price: RM8")\n    else:\n        print("Ticket price: RM12")';
  const ksu=after=>TARGETS.map(([id,area,text,evidence])=>`<section class="ksu-target"><h2>${id} · ${area}</h2><p>${text}</p><p class="target-evidence"><strong>Evidence to look for:</strong> ${evidence}</p>${field((after?'after-':'before-')+id)}${after?field('phase-'+id):''}</section>`).join('')+`<div id="ksu-summary" class="summary" role="status"></div>`;
  const pages = [
    {id:'prepare',label:'Prepare and recap',time:'3 min',section:'Prepare',tag:'READ FIRST',render:()=>`${head('One age. Two decisions.','3 min','READ FIRST')}<div class="scenario"><h2>The school-fair ticket desk</h2><p>A school fair is selling an activity ticket for children and teenagers aged 5–18. A volunteer enters each visitor’s age. Your program must check that the age meets the rule <strong>before</strong> it chooses a price.</p><p>If the age is outside the accepted range, the program must show a rejection message. It must not sell a cheaper ticket just because an invalid age is a small number.</p>${rules()}</div><div class="reading"><h2>Quick recap before Do Now</h2><p>A <strong>variable</strong> stores a value. <code>input()</code> collects text typed by a user; <code>int()</code> converts suitable whole-number text to an integer. A <strong>condition</strong> produces True or False. Selection uses that result to choose a path.</p><p><strong>Validation</strong> checks whether input follows a stated rule. Today the rule is an accepted age range. Validation is not proof that someone has entered their true age.</p></div><div class="callout"><strong>Today’s scope:</strong> enter whole numbers only. This program makes one decision for one entry. Text such as <code>hello</code>, decimal input and repeated prompting need further techniques; they are not required today.</div><h2>What you will produce</h2><ol class="step-list"><li>A short algorithm or flowchart.</li><li>A Python program you run in your own IDE.</li><li>Test predictions, actual outputs and explanations.</li><li>A notebook PDF to submit in Teams.</li></ol>${field('prepare-job')}<details><summary>Textbook and syllabus connections</summary><p>Read the textbook’s printed pp. 32–35 for selection, pp. 92–93 for validation and pp. 96–97 for testing. In the supplied PDF these are pages 36–39, 96–97 and 100–101. The short readings here are original explanations, not copied textbook extracts. On pp. 92–93, focus on selection; the repetition examples are for a later lesson.</p><p><a href="https://www.oxfordaqa.com/wp-content/uploads/2025/02/oxfordaqa-gcse-computer-science-specification.pdf" target="_blank" rel="noopener">OxfordAQA 9210 specification</a>: 3.1.1 algorithms; 3.2.2 selection; 3.2.4–3.2.5 comparisons and Boolean operations; 3.2.7 input/output; 3.2.12 validation and justified test data.</p></details>`},
    {id:'starter',label:'Do Now',time:'6 min',section:'Do Now',tag:'RETRIEVE · AO1 / AO2',render:()=>`${head('Do Now: check what you remember','6 min','RETRIEVE · AO1 / AO2')}<p>Use the recap if you need it. Answer first, then use the checks. A correction helps you choose today’s learning target.</p><section class="question"><h2>1. From text to a number</h2>${codeBlock('age = int(input("Age: "))','starter-code')}${field('starter1')}${check('starter1')}</section><section class="question"><h2>2. Follow the stated rule</h2><p>Ages 5–18 inclusive are accepted. Age 19 is entered.</p>${field('starter2')}${check('starter2')}</section><section class="question"><h2>3. Either rejection is enough</h2><p>Reject an age if it is below 5 <strong>or</strong> above 18. You do not need logic-gate notation.</p>${field('starter3')}${check('starter3')}</section><section class="question"><h2>4. Explain the order</h2>${field('starter4')}<button class="check-button" data-model="starter4">Compare with an explanation</button><div id="feedback-starter4">${savedFeedback('starter4')}</div></section>`},
    {id:'types',label:'Types of Learning',time:'3 min',section:'Types of Learning',tag:'K / S / U · CHOOSE YOUR TARGET',render:()=>`${head('What are you getting better at?','3 min','TYPES OF LEARNING')}<p>Use your Do Now answers to identify what you already know and what needs work. Knowing the definition of a variable does not mean you can yet write or explain a validation program.</p><p><strong>Knowledge:</strong> remember and explain ideas. <strong>Skills:</strong> practise performing a task. <strong>Understanding:</strong> explain why it works and apply it when a rule changes. These can overlap.</p>${ksu(false)}${field('focus-target')}${field('focus-action')}<div class="callout">The profile counts your selected evidence levels. It is <strong>not an exam score</strong> or a judgement about your ability. Your teacher will also look at your work.</div>`},
    {id:'fact1',label:'Fact 1: validation',time:'4 min',section:'Fact 1: validate before deciding',tag:'READ / STUDY · AO1',render:()=>`${head('Fact 1: validate before deciding','4 min','READ / STUDY · AO1')}<div class="reading"><p>The program has two different jobs. First, <strong>validation</strong> asks whether the age is allowed. Only after that, the <strong>price decision</strong> asks which category applies.</p><p>A range check can reject an age below the minimum or above the maximum. “Inclusive” means the two limit values themselves are accepted.</p></div><div class="range-visual" role="img" aria-label="Ages below 5 rejected. Ages 5 through 18 accepted. Ages above 18 rejected."><div><b>Below 5</b>Rejected<br>e.g. 4</div><div class="accepted"><b>5 through 18</b>Accepted<br>both endpoints included</div><div><b>Above 18</b>Rejected<br>e.g. 19</div></div><div class="decision-flow"><p><strong>Input:</strong> obtain the age.</p><p><strong>Decision 1:</strong> outside 5–18?</p><p class="nested">Yes → reject, with no price.</p><p class="nested">No → continue to the price decision.</p><p><strong>Decision 2:</strong> accepted age at most 12?</p><p class="nested">Yes → RM8. No → RM12.</p></div><div class="callout"><strong>A common mistake:</strong> <code>age &lt;= 12</code> is also True for age 4. A price check by itself does not validate the age.</div>${field('fact1')}<button class="check-button" data-model="fact1">Compare my explanation</button><div id="feedback-fact1">${savedFeedback('fact1')}</div><p class="small">Textbook: printed pp. 92–93, selection-based validation. The school-fair rules are our lesson example, not an examination question.</p>`},
    {id:'main1',label:'Main Activity 1: plan',time:'10 min',section:'Main Activity 1',tag:'DESIGN · AO2 / AO3',render:()=>`${head('Main Activity 1: design the safe decision','10 min','DESIGN · AO2 / AO3')}<div class="scenario"><h2>Your role: plan for the ticket volunteer</h2><p>The volunteer must receive one clear result for each visitor. Design the decision so an invalid age cannot accidentally be charged. Use the same four rules throughout.</p>${rules()}</div><h2>A. Predict the result</h2><p>Choose the complete output for each input. These values investigate both age limits and the price change.</p>${[4,5,12,13,18,19].map(age=>`<section class="question"><h3>Age ${age}</h3>${field('plan-'+age)}</section>`).join('')}<button class="check-button" data-check="plan">Check my six predictions</button><div id="feedback-plan">${savedFeedback('plan')}</div><section class="question"><h2>B. Turn the rules into conditions</h2>${field('plan-reject')}${field('plan-price')}${hint('A hint about the two decisions','The rejection condition checks below 5 <strong>or</strong> above 18. Inside the accepted path, the cheaper category ends at 12. The validation has already excluded ages below 5.')}</section><section class="question"><h2>C. Write your algorithm</h2><p>Write numbered steps or clear pseudocode. Alternatively, upload a flowchart and use the text box to describe its two decisions. Include the input, both decisions, all three possible outputs and their order.</p>${field('plan-algorithm')}${screenshot('plan','Optional flowchart evidence')}${field('plan-order')}${hint('An algorithm starting point','1. Obtain the age.<br>2. Decide whether it is outside the accepted range.<br>3. If invalid, reject it.<br>4. Otherwise, choose the correct price category.<br>Now add the exact conditions and outputs yourself.')}</section>`},
    {id:'fact2',label:'Fact 2: code tutor',time:'4 min',section:'Fact 2: read and trace the code',tag:'READ / TRACE · AO2',render:()=>`${head('Fact 2: follow one line at a time','4 min','READ / TRACE · AO2')}<p>This example implements <strong>only the first decision</strong>: is the age accepted? In Main Activity 2 you will replace its accepted message with your own price decision.</p><div class="tutor"><h2>Guided validation example</h2>${field('tutor-case')}<p class="hint">This is a walkthrough of fixed example code, not a Python runner. Select the next step yourself. Line numbers are reading aids, not part of the code.</p><div id="tutor-lines" class="tutor-lines" aria-label="Numbered example code"></div><div class="tutor-controls"><button data-tutor="previous">Previous step</button><button data-tutor="next">Next step</button><button data-tutor="restart">Restart this input</button></div><div id="tutor-explanation" class="tutor-explanation" role="status"></div></div>${codeBlock(READ_CODE,'validation-start')}<details><summary>Syntax reference: what the symbols do</summary><div class="syntax-list"><div><code>=</code> assigns a value to a variable.</div><div><code>&lt; / &gt;</code> means less than / greater than.</div><div><code>&lt;= / &gt;=</code> includes the limit in a comparison.</div><div><code>or</code> makes the rejection True if either comparison is True.</div><div><code>:</code> introduces the block of instructions for a branch.</div><div><strong>Indentation</strong> shows which instructions belong to the branch.</div><div><code>" "</code> encloses text. Brackets in <code>print(...)</code> enclose what is displayed.</div></div><p>Use straight quotation marks and matching brackets. Copying the example is allowed; you still need to study what each line does.</p></details>${field('fact2')}${check('fact2')}<p class="small">Textbook: printed pp. 32–35 for Python comparisons, selection and indentation.</p>`},
    {id:'main2',label:'Main Activity 2: build',time:'16 min',section:'Main Activity 2',tag:'DEVELOP / TEST · AO3',render:()=>`${head('Main Activity 2: build your ticket program','16 min','DEVELOP / TEST · AO3')}<div class="scenario"><h2>From your algorithm to Python</h2><p>You have designed the ticket decision. Now implement it in your own IDE. Start from your algorithm, or adapt the five-line validation example. Your task is to add the price decision <strong>only inside the accepted path</strong>.</p>${rules()}</div><h2>Your coding checklist</h2><ol class="step-list"><li>Create and save <code>fair_ticket.py</code> in your IDE.</li><li>Obtain the age as a whole number.</li><li>Reject ages outside 5–18 with <code>Age not accepted</code>.</li><li>For accepted ages only, choose RM8 or RM12 using selection.</li><li>Run it once with age 8 and once with age 19. Compare each result with your prediction.</li><li>Paste your code and output below. Then complete the test page.</li></ol><h3>Example run — accepted input</h3><pre class="example-run">Age: 13\nTicket price: RM12</pre><h3>Example run — rejected input</h3><pre class="example-run">Age: 19\nAge not accepted</pre><div class="callout"><strong>Completion evidence:</strong> your code, at least one accepted and one rejected run, and test records. Writing code in this notebook does not execute it.</div>${hint('Hint 1 — where does the price decision belong?','Keep the invalid-age branch separate. The accepted <code>else</code> branch is the safe place to choose the price.')}${hint('Hint 2 — what should I add?','Inside the accepted branch, add an <code>if</code> condition for the cheaper category. Its <code>else</code> handles the other accepted category. Keep the nested lines indented.')}${hint('Hint 3 — begin the accepted branch','Inside the outer <code>else:</code>, begin with <code>if age &lt;= 12:</code>. Add its output and the other price branch yourself. An equivalent protected <code>if / elif / else</code> chain is also valid.')}<section class="question">${field('main2-code')}${field('main2-output')}${screenshot('program','Code and output screenshots')}${field('main2-explain')}${field('main2-help')}</section><details><summary>If my program stops with an error</summary><ol class="step-list"><li>Check that the input is a whole number, such as 8, not eight or 8.5.</li><li>Read the reported line number. An error can also begin on the line before it.</li><li>Check matching quotation marks and brackets.</li><li>Check the colon and indentation for the branch.</li><li>Change one thing, then run again. Use Help / pause if you need support.</li></ol><p>An error is information about the program, not a judgement about you.</p></details>`},
    {id:'testing',label:'Fact 3 and test evidence',time:'6 min',section:'Test evidence',tag:'TEST / JUSTIFY · AO3',render:()=>`${head('Fact 3: test the limits, not just the middle','6 min','TEST / JUSTIFY · AO3')}<div class="reading"><p><strong>Normal data</strong> is typical valid input. <strong>Boundary data</strong> is at or immediately beside a limit. <strong>Erroneous data</strong> breaks a rule.</p><p>An invalid value can also be a boundary test: age 4 is immediately below the accepted minimum. A rejected input is a <strong>successful test</strong> when rejection is what you predicted.</p><p>Test both kinds of limit: the acceptance range (5 and 18) and the price transition (12 and 13). A program can pass one test and still have an error in another branch.</p></div><h2>Work through one test at a time</h2><ol class="step-list"><li>Predict the output before running.</li><li>Run your program in your IDE with the shown age.</li><li>Paste the actual output and select whether it matched.</li><li>If it differed, repair your code and rerun the affected tests.</li></ol><div class="test-controls"><button data-test="previous">← Previous test</button><span id="test-position"></span><button data-test="next">Next test →</button></div><div id="test-host"></div><p id="test-summary" class="summary"></p><section class="question">${field('test-correction')}${field('test-justify')}</section><p class="small">Textbook: printed pp. 96–97. Today’s erroneous tests use invalid whole-number ages; handling words, empty numeric input and decimals is a later programming step.</p>`},
    {id:'extensions',label:'Extension studio',time:'Optional',section:'Extensions',tag:'CHOOSE A CHALLENGE · AO2 / AO3',render:()=>`${head('Extension studio','Early finish / follow-up','OPTIONAL CHALLENGES')}<p>There are ten original, short scenario-based challenges. You are <strong>not expected to complete all ten today</strong>. Choose one at the right level, run it in your own IDE and keep its evidence here. Each challenge has its own saved code and output.</p><label for="extension-choice">Choose a challenge</label><select id="extension-choice">${EXTENSIONS.map((e,i)=>`<option value="${i}" ${window.Notebook?.state?.ui?.extension===i?'selected':''}>${i+1}. ${esc(e.title)} — ${esc(e.level)}</option>`).join('')}</select><div id="extension-host" class="extension-browser"></div>`},
    {id:'pit',label:'Learning Pit Stop',time:'3 min',section:'Learning Pit Stop',tag:'K / S / U · EVIDENCE AND NEXT STEP',render:()=>`${head('Learning Pit Stop','3 min','REFLECT AFTER THE EXTENSION WINDOW')}<p>Return to the same six targets. Look at your algorithm, code and test results. Rate each target separately: you may feel secure about validation but need help explaining boundary tests.</p><p>Your evidence level describes what you can show. Your learning phase describes how this work feels <strong>right now</strong>. They are different measures. You can share these privately rather than announce them to the class.</p>${ksu(true)}${field('pit-evidence')}${field('pit-action')}<div class="callout"><strong>Needing help is a useful signal.</strong> You do not need to keep struggling until you become distressed. Choose the exact step and use your agreed support or pause routine.</div>`},
    {id:'plenary',label:'Plenary',time:'3 min',section:'Plenary',tag:'TRANSFER · AO2 / AO3',render:()=>`${head('Plenary: change one rule safely','3 min','TRANSFER · AO2 / AO3')}<div class="scenario"><p>The organiser changes the cheaper ticket category to <strong>ages 5–11</strong>. Ages 12–18 now pay RM12. The overall accepted age range stays 5–18.</p><p>You do not need to rebuild the whole program. Identify the change and the tests that would check it.</p></div>${field('exit-condition')}${field('exit-tests')}${field('exit-validation')}<button class="check-button" data-model="plenary">Compare with a suggested explanation</button><div id="feedback-plenary">${savedFeedback('plenary')}</div>`},
    {id:'submit',label:'Save and submit',time:'2 min',section:'Save and submit',tag:'EVIDENCE · MICROSOFT TEAMS',render:()=>`${head('Save, check and submit','2 min','EVIDENCE · MICROSOFT TEAMS')}<p>You can export at any point, even if some work is unfinished. The PDF includes every question, your saved responses, code, test records, reflections, feedback checks and all attached screenshots. Unanswered items are clearly labelled.</p><div id="completion-summary"></div><ol class="step-list"><li>Select <strong>Export PDF</strong> at the top right. Wait for the download.</li><li>Open the PDF. Check your name, class, code, outputs and complete screenshots.</li><li>Keep the filename clear: <code>Y10_Validation_Ticket_Name_Class.pdf</code>.</li><li>Open <strong>Microsoft Teams → your Year 10 Computer Science class → Assignments</strong>, or open the assignment linked in the lesson’s Classwork module.</li><li>Open the correct assignment. Select <strong>Add work</strong> (or the attach/upload option shown), choose the PDF, then select <strong>Turn in</strong>.</li><li>Check that Teams shows it as turned in. If no assignment is available, follow your teacher’s stated submission destination.</li></ol><p class="small">These are submission instructions, not an automatic upload. The app cannot confirm your Teams submission.</p>${field('submit-checked')}${field('submit-teams')}<p class="hint">After ticking these, export again if you want the PDF to include the final self-reported checklist. A JSON backup preserves editable work and screenshots for this lesson.</p><details><summary>Course connections and teacher information</summary><p>The independent programming and testing build Paper 1 skills. Explaining validation and selecting test data also support Paper 2. This lesson is not a full skeleton-program examination.</p><ul class="resource-list"><li><a href="https://www.oxfordaqa.com/qualification/international-gcse-computer-science-9210/" target="_blank" rel="noopener">OxfordAQA 9210 course and assessment information</a></li><li><a href="https://www.oxfordaqa.com/wp-content/uploads/2025/02/oxfordaqa-gcse-computer-science-specification.pdf" target="_blank" rel="noopener">Specification: 3.1.1, 3.2.2, 3.2.4–3.2.5, 3.2.7 and 3.2.12</a></li></ul><p>Extension exercises are original lesson tasks inspired by short, clear programming-practice formats. They are not reproduced Helsinki MOOC or OxfordAQA examination questions.</p></details>`}
  ];
  const notes = {
    prepare:'Introduce the fair scenario and the four rules. Confirm that students will use their own IDE. Review the agreed quiet-help and break signals. Keep all numerical input as whole numbers.',
    starter:'Suggested answers: integer; reject age 19 with no price; outside-range condition uses or. A rejected value does not meet the rules and must not be used to sell a ticket. A student who consults the recap has used support; this is not a graded diagnostic.',
    types:'Use Do Now evidence to identify a priority K/S/U target. Do not equate self-confidence or the 0–2 evidence ladder with attainment grades. Remind students that targets can overlap.',
    fact1:'Accepted range does not establish truth. Use age 4 to expose the difference between validating eligibility and selecting a cheap price. Keep these decisions visually and verbally separate.',
    main1:'Prediction answers: 4 rejected; 5 RM8; 12 RM8; 13 RM12; 18 RM12; 19 rejected. Reject with age < 5 or age > 18. In the accepted path, age <= 12 selects RM8. Equivalent clear algorithms and protected selection chains are acceptable.',
    fact2:'The tutor traces only the five-line range checker. No arbitrary Python executes here. Watch whether the student can identify a skipped branch. For age 19, line 5 is not executed. Invite independent prediction before stepping.',
    main2:'Assess rule implementation, not exact code matching. A protected if/elif/else chain is also correct. For age 13, validation is False, the cheaper comparison is False, and RM12 is displayed. Record content help separately from procedural access support. Model solution:\n'+MODEL_CODE,
    testing:'Prioritise four acceptance-edge tests, then the price transition and normal branches. The additional input should be selected and justified by the student; -2 is a useful erroneous value away from the boundaries. Self-reported comparisons are not automatic verification of the student program. Words and decimals are outside the practical scope, not fully handled.',
    extensions:'Offer one appropriate challenge, not a race to finish ten. Challenges 1–2 consolidate; 3–4 investigate changed boundaries; 5–7 combine familiar operations; 8–9 transfer; 10 repairs unsafe independent selection. Require evidence from the IDE, not pasted code alone.',
    pit:'Revisit each K/S/U target with artefacts. Support or a high completion count does not by itself show conceptual mastery. Keep support choices private. If distress rises, pause the demand and follow the agreed pupil plan; do not force a spoken explanation.',
    plenary:'Change the cheaper comparison to age <= 11 (inside the accepted path). Test 11 and 12 for RM8/RM12. The validation limits remain 5 and 18. No need to code a whole new application.',
    submit:'Students open and inspect the PDF before attaching it to the actual Teams assignment and selecting Turn in. The website has no Teams upload, live teacher alerts or central tracking. Collect the PDFs and review evidence against K/S/U.'
  };
  const models = {
    starter4:'The age breaks the accepted range rule. Reject it before the price decision; otherwise an invalid small age could be given a cheaper ticket.',
    fact1:'No. Validation checks the permitted range, not whether the entered age is true. A person can enter a permitted age that is not their real age.',
    plenary:'Inside the accepted path, change the cheaper comparison to age <= 11. Test ages 11 and 12 for RM8 and RM12. Keep the accepted age range at 5–18.'
  };
  function testHtml(index) {
    if(index<TESTS.length){const t=TESTS[index];return `<section class="test-card"><p class="eyebrow">TEST ${index+1} · ${esc(t.purpose)}</p><h2>Enter age ${t.age} in your IDE</h2>${field('test-'+t.id+'-expected')}${field('test-'+t.id+'-actual')}${field('test-'+t.id+'-result')}<button class="check-button" data-model="test-${t.id}">Compare my prediction with the rule</button><div id="feedback-test-${t.id}">${savedFeedback('test-'+t.id)}</div></section>`;}
    return `<section class="test-card"><p class="eyebrow">TEST 9 · CHOOSE AND JUSTIFY YOUR OWN INPUT</p><h2>Add an independent test</h2><p>Choose a whole-number input not already in the supplied tests. Select its category and explain what it investigates. An invalid age well away from the limits is a useful additional erroneous test.</p>${['own-test-value','own-test-type','own-test-why','own-test-expected','own-test-actual','own-test-result'].map(field).join('')}${hint('If I need a starting point','Consider a negative age such as -2. It is a whole number, but it breaks the accepted range. Explain what the program must do before running it.')}</section>`;
  }
  function extensionHtml(index){const e=EXTENSIONS[index];return `<p class="extension-badge">CHALLENGE ${index+1} · ${esc(e.level)}</p><h2>${esc(e.title)}</h2><p>${esc(e.task)}</p><h3>What to do</h3><ol class="step-list">${e.steps.map(t=>`<li>${esc(t)}</li>`).join('')}</ol>${e.faulty?codeBlock(e.faulty,'extension-fault'):''}<h3>Example run</h3><pre class="example-run">${esc(e.run)}</pre><p><strong>Test to try:</strong> ${esc(e.test)}</p>${hint('A focused hint',esc(e.hint))}${['code','output','explain','status'].map(k=>field('ext-'+index+'-'+k)).join('')}${screenshot('ext-'+index,'Optional evidence for this challenge')}`;}
  const CHECKS={starter1:{key:'starter1',correct:'integer',message:'int() converts suitable whole-number input text to an integer. The variable age stores that result.'},starter2:{key:'starter2',correct:'reject',message:'19 is above the maximum accepted age, 18. Reject it and do not display a price.'},starter3:{key:'starter3',correct:'or',message:'Either invalid side is enough: below 5 OR above 18. No age can be both below 5 and above 18 at once.'},fact2:{key:'fact2',correct:'no',message:'For age 19, the rejection condition is True. Line 3 runs; the else branch and line 5 are skipped.'}};
  window.Lesson={id:'y10-validation-decisions-v1',title:'Validate, decide, test',questions,TARGETS,LEVELS,PHASES,TESTS,EXTENSIONS,pages,notes,models,CHECKS,READ_CODE,MODEL_CODE,esc,field,testHtml,extensionHtml,codeSnippets:{'starter-code':'age = int(input("Age: "))','validation-start':READ_CODE,'extension-fault':EXTENSIONS[9].faulty}};
})();
