(() => {
'use strict';
const L=window.LESSON,$=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=null,db=null,queue=Promise.resolve(),memoryOnly=false;
const meta=new Map();
function blank(name,cls){return {version:1,name,cls,date:new Date().toLocaleDateString('en-GB'),step:0,answers:{},photos:{},feedback:[]};}
const profile=()=>[state.name.trim().toLowerCase(),state.cls.trim().toLowerCase()].join('|');
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('mrdave-w4s1-security',1);r.onupgradeneeded=()=>r.result.createObjectStore('profiles');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
function get(key){return new Promise((resolve,reject)=>{const r=db.transaction('profiles').objectStore('profiles').get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
function save(){if(!state)return;const snapshot=structuredClone(state),key=profile();$('saveStatus').textContent='Saving…';queue=queue.catch(()=>{}).then(()=>new Promise((resolve,reject)=>{if(!db){reject(new Error('Storage unavailable'));return;}const tx=db.transaction('profiles','readwrite');tx.objectStore('profiles').put(snapshot,key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);})).then(()=>{$('saveStatus').textContent='Saved on this device';memoryOnly=false;}).catch(()=>{memoryOnly=true;$('saveStatus').textContent='Not saved: export PDF or backup now.';});return queue;}
function field(key,label,stage,rows=3){meta.set(key,{label,stage});return `<div class="question"><label for="${key}">${label}</label><textarea id="${key}" data-answer="${key}" rows="${rows}">${esc(state.answers[key]||'')}</textarea></div>`;}
function select(key,label,options,stage){const c=L.checks.find(c=>key==='before_'+c.id||key==='after_'+c.id);meta.set(key,{label:c?`${c.type}: ${c.statement} — ${label}`:label,stage});return `<label for="${key}">${esc(label)}</label><select id="${key}" data-answer="${key}"><option value="">Choose…</option>${options.map(o=>`<option ${state.answers[key]===o?'selected':''}>${esc(o)}</option>`).join('')}</select>`;}
const card=(title,body)=>`<article class="card"><h2>${title}</h2>${body}</article>`;
const flow=(a,b,c)=>`<div class="diagram" aria-label="${esc(a+' then '+b+' then '+c)}"><span>${a}</span><b>→</b><span>${b}</span><b>→</b><span>${c}</span></div>`;
function photoZone(stage){return `<div class="card upload"><h3>Working on paper?</h3><p>Write the task title and question numbers. Add clear photographs of every page instead of typing the same answers again. Keep your original work and corrections visible.</p><label>Add photographs <input type="file" data-upload="${stage}" accept="image/png,image/jpeg,image/webp" multiple></label><p class="hint">PNG, JPG or WebP; up to 15 MB per image. Photos are resized for the report. Check that the writing is readable. You can also paste a copied image while on this page.</p><div class="photo-grid">${(state.photos[stage]||[]).map((p,i)=>`<div class="photo"><img src="${p.data}" alt="${esc(p.name)}"><label>What does this show?<input data-caption="${stage}:${i}" value="${esc(p.caption)}"></label><button data-remove="${stage}:${i}">Remove photo ${i+1}</button></div>`).join('')}</div></div>`;}
function suggested(c){const phase=state.answers['after_'+c.id],i=L.phases.indexOf(phase);return i===4?c.start:(c.actions[i]||'Choose a current phase to see a suggested next step.');}
function checks(after){const prefix=after?'after_':'before_',stage=after?'pit':'before';return L.checks.map(c=>`<div class="check"><span class="badge">${c.type}</span><h3>${c.statement}</h3><p class="hint">${after?esc(c.evidence):'Use your starter or discussion where relevant. These checks include ideas we have not taught yet.'}</p>${after?`<p class="before">Starting point: ${esc(state.answers['before_'+c.id]||'Not recorded')}</p>`:''}${select(prefix+c.id,after?'Where am I now?':'My starting point',after?L.phases:L.before,stage)}${after?`<p class="action">${esc(suggested(c))}</p>`:''}</div>`).join('');}
function focus(after){const stage=after?'pit':'before',key=after?'next_focus':'focus',choices=L.checks.map(c=>c.type+': '+c.title),c=L.checks.find(c=>c.type+': '+c.title===state.answers[key]);return card(after?'Choose one next step':'Choose one focus',select(key,after?'What should I practise, extend or discuss?':'What will I work on today?',choices,stage)+`<p class="action">${c?esc(after?suggested(c):c.start):'Choose a focus using your work or a discussion with your teacher.'}</p>`+field(after?'pit_evidence':'focus_reason',after?'Give one piece of evidence and your next action.':'What in your starter or discussion helped you choose?',stage,2));}
function content(id){switch(id){
case 'start':return `<p class="lead">A working connection is not automatically a secure connection.</p>`+card('Read first',`<p>Our school network connects laptops, servers and wireless devices. Protocols are agreed rules that let devices communicate. Last lesson, you explored how protocols support communication.</p><p><strong>HTTP</strong> supports requests and responses for web resources. <strong>HTTPS</strong> adds protection for the communication, including encryption. Reaching the correct computer does not by itself show who may use the information or whether it stayed private on the way.</p><p>Today you will learn four ways to protect a network. We will distinguish checking a person, checking a device, filtering traffic and protecting information.</p>`)+`<p>Answer first on your own. Then compare one explanation with a partner. If you used the reading, say so in your learning check.</p>`+field('s1','1. What additional protection does HTTPS provide compared with HTTP?','start')+field('s2','2. A visitor’s device connects to the school network. Does that mean the visitor should be able to open staff records? Explain.','start')+field('s3','3. A message reaches the correct computer. Does that prove nobody else could read it during transmission? Explain.','start')+photoZone('start');
case 'before':return `<p>Look back at your starter answers. Choose a starting point for each statement, then one focus for today.</p><div class="card accent"><p><strong>Knowledge:</strong> facts I can recall. <strong>Skills:</strong> things I can practise and do. <strong>Understanding:</strong> reasons I can explain and apply.</p><p>We work on all three; they are not fixed types of learner.</p><p>Our starter did not check all four security measures. Choose <strong>“Not sure / not checked yet”</strong> when you have no evidence. These are starting points, not grades.</p></div>`+checks(false)+focus(false);
case 'learn':return `<p>Read the four panels (6 minutes). Study one explanation (3 minutes). Practise with your partner (6 minutes), then show your teacher the checkpoint (3 minutes).</p><div class="grid">`+
card('1. Who are you?',`<span class="badge">AUTHENTICATION</span><p>Authentication checks that a user or system is who it claims to be. A login system can compare the credentials supplied with the credentials associated with the account. If the check succeeds, access can be allowed.</p>${flow('Claim an identity','Check credentials','Accept or reject login')}<p><strong>School example:</strong> a teacher enters an individual username and password to sign in.</p><p><strong>Important distinction:</strong> authentication checks identity. Access permissions determine which records that account may use. An approved device does not identify the person using it.</p>`)+
card('2. Can someone read it?',`<span class="badge">ENCRYPTION</span><p>Encryption uses an algorithm and a key to transform readable <strong>plaintext</strong> into <strong>ciphertext</strong>. The appropriate decryption key is needed to turn it back into intelligible information.</p>${flow('Plaintext','Algorithm + key','Ciphertext')}<p><strong>School example:</strong> encrypting assessment information sent between a laptop and server protects its confidentiality if it is intercepted.</p><p><strong>Limit:</strong> encryption does not prevent interception itself or decide who should be allowed to log in.</p>`)+
card('3. Which traffic is allowed?',`<span class="badge">FIREWALL</span><p>A firewall examines network traffic and compares it with configured rules. It allows traffic that meets the rules and blocks traffic that does not. Rules can concern addresses, ports or types of communication.</p>${flow('Network traffic','Compare with rules','Allow or block')}<p><strong>School example:</strong> the administrator blocks incoming connections that do not match permitted-traffic rules.</p><p><strong>Limit:</strong> a firewall does not guarantee that all permitted traffic is harmless. It does not replace user authentication.</p>`)+
card('4. Which device?',`<span class="badge">MAC ADDRESS FILTERING</span><p>A MAC address identifies a network interface. MAC address filtering compares the connecting device’s MAC address with a configured allowed or blocked list to decide whether the device can access the network.</p>${flow('Device MAC address','Compare with list','Allow or deny device')}<p><strong>School example:</strong> only the network-adapter addresses of approved assessment laptops are on the allowed list.</p><p><strong>Limit:</strong> this does not check who is using an approved device or encrypt its traffic. For a deeper challenge, consider that a MAC address can be imitated.</p>`)+`</div><p class="small">Reading support: OxfordAQA International GCSE Computer Science Student Book, printed pp. 248–251. Explanations above are lesson guidance, not verbatim textbook quotations. The examination scope is <a href="https://www.oxfordaqa.com/wp-content/uploads/2022/08/oxfordaqa-international-gcse-computer-science-specification.pdf" target="_blank" rel="noopener">9210 specification 3.5, printed p. 28</a>. You do not need to learn encryption algorithms or certificate-handshake details for this task.</p>`+
card('Study the model: explain, not just name',`<p><strong>Situation:</strong> a teacher sends confidential assessment information across a network. Someone intercepts it.</p><p><strong>Measure:</strong> use encryption.</p><p><strong>Mechanism:</strong> it converts the information into ciphertext using an algorithm and key.</p><p><strong>Benefit here:</strong> someone without the appropriate decryption key should not be able to understand the intercepted assessment information.</p><p>“It makes the network safer” does not explain how the measure addresses this situation.</p>`)+
card('Partner practice: choose, explain, challenge',`<ol><li>Partner A reads the first scenario. Partner B names a suitable measure and explains how it works without copying the reading.</li><li>Partner A asks: “What does this measure not protect against?”</li><li>Open the check, correct your explanation, then swap roles for the next scenario.</li><li>Each of you records one explanation below. In a group of three, rotate speaker, questioner and checker.</li></ol>${L.scenarios.map((s,i)=>`<div class="check"><h3>Scenario ${i+1}</h3><p>${s[0]}</p><details><summary>Check after explaining</summary><p>${s[1]}</p></details></div>`).join('')}`)+field('partner','My explanation: name the scenario, the measure, how it works and one limitation.','learn')+card('Stop and show your teacher',`<p>“This laptop is on the approved MAC address list, so anyone using it should be allowed to open staff records.”</p>`+field('hinge','Is that conclusion correct? Explain the difference between device approval and user identity.','learn'))+photoZone('learn');
case 'apply':return card('Your brief: the school assessment network',`<p>The school is introducing a networked assessment system. Teachers share school laptops but sign in to individual accounts. Only approved school devices should join the assessment wireless network. Confidential assessment information travels between the laptops and a server. The administrator needs to block incoming connections that do not meet the school’s permitted-traffic rules.</p><p><strong>Your job:</strong> explain which of the four measures addresses each requirement. State the measure and explain its operation in this situation. Each of questions 1–4 is worth 2 marks: 1 for the suitable measure and 1 for the explanation. Question 5 is worth 2 marks. <strong>Total: 10 marks.</strong></p><p>Work independently for your first attempt. You may use the reading while learning; record any support below. If you work on paper, number answers 1–5 and upload all pages.</p>`)+
field('a1','1. Check the identity of someone signing in. Name the measure and explain how it works here. [2 marks]','apply')+field('a2','2. Restrict which devices can join the assessment wireless network using their network-adapter addresses. Name and explain the measure. [2 marks]','apply')+
card('Quick teacher check',`<p>After questions 1 and 2, show your teacher one explanation. Ask: “Have I explained what the measure checks, rather than only saying it is secure?” If your teacher is helping someone else, continue to question 3.</p>`)+field('a3','3. Protect confidential information if it is intercepted in transit. Name and explain the measure. [2 marks]','apply')+field('a4','4. Block connections that fail the administrator’s permitted-traffic rules. Name and explain the measure. [2 marks]','apply')+field('a5','5. An approved laptop is connected. Explain why authentication and encryption are both still needed. [2 marks]','apply')+select('support','What support did I use for this first attempt?',['Independent without reading','Used reading or model','Discussed with a partner','Worked with teacher support'],'apply')+
card('Use your feedback',`<p>Keep your first answers above. Record one piece of feedback and a better explanation below. Save the feedback step to keep a snapshot of your first answers.</p>`+field('feedback_note','What should I improve?','apply',2)+field('improved','My improved answer (include the question number).','apply')+`<button id="snapshot">Save feedback and both attempts</button><div class="feedback-log">${state.feedback.map((f,i)=>`<p>Feedback step ${i+1} saved · ${esc(f.time)}<br>${esc(f.note)}<br>Improvement: ${esc(f.improved)}</p>`).join('')}</div>`)+photoZone('apply');
case 'pit':return `<p>Return to the same six statements. Use your answers, partner explanation and teacher feedback. You may be secure with one idea and need help with another.</p><div class="card accent"><p><strong>New learning:</strong> this takes effort, but I am making progress with examples or support.</p><p><strong>Consolidating:</strong> I am practising what I know and becoming more secure.</p><p><strong>Treading water:</strong> this is not stretching me; I need a deeper explanation or new situation.</p><p><strong>Drowning:</strong> I am stuck and need a smaller guided step.</p><p><strong>Not attempted yet:</strong> I do not have evidence for this check yet.</p><p>These phases are not ordered scores. If you need help, tell your teacher or show your screen now. Saving a response here does not send an alert.</p></div><p class="before">Your starting focus: ${esc(state.answers.focus||'Not recorded')}</p>`+checks(true)+focus(true);
case 'extension':return `<p>Optional work within independent practice time, or finish later if your teacher asks. Complete the original exam practice, then deepen your explanation. <strong>10 marks available: 4 original exam marks + 6 classroom challenge marks.</strong></p>`+card('Original exam practice · November 2024',`<p>OxfordAQA 9210/2, Question 06.1–06.2, original page 12. The page below is unchanged. Read it at full size if needed.</p><a href="assets/nov24-q06.png" target="_blank" rel="noopener">Open the original question page</a><img class="exam" src="assets/nov24-q06.png" alt="Original November 2024 Paper 2 page 12. Question 06.1 asks how a firewall keeps a network secure, for 2 marks. Question 06.2 asks how MAC address filtering keeps a network secure, for 2 marks.">`)+field('e061','06.1 — Your answer [2 marks]','extension')+field('e062','06.2 — Your answer [2 marks]','extension')+card('Go further: is one measure enough?',`<p>A school permits only approved devices on its wireless network. A member of staff says: “This means passwords and encryption are no longer necessary.”</p><p>For each response below, explain the risk as well as the measure. These are separate classroom questions, not additions to the original exam question.</p>`)+field('e1','1. Explain why an approved device does not make user authentication unnecessary. [2 marks]','extension')+field('e2','2. Explain why approved devices still need encryption when sending confidential information. [2 marks]','extension')+field('e3','3. A person knows a valid account password. Explain one risk that can remain and recommend one further precaution that addresses it. [2 marks]','extension')+photoZone('extension');
case 'exit':return card('A new situation · Close your notes',`<p>A medical centre encrypts information sent between its computers. A manager claims: “Because the information is encrypted, we no longer need to check who signs in.”</p><p>Answer independently without the reading. Show that you can transfer today’s learning to this new situation.</p>`)+field('p1','1. Explain why the manager’s claim is incorrect.','exit')+field('p2','2. Name the missing measure and explain how it addresses a different risk.','exit')+photoZone('exit');
case 'submit':return card('Your evidence of learning',`<p>Your PDF includes your name and class, all typed answers, photographs, the before-and-after learning checks, next actions and saved feedback snapshots. An unanswered question is recorded as “Not recorded”; it is not assigned a zero mark.</p><ol><li>Select <strong>Export PDF</strong>.</li><li>Open the downloaded PDF. Check every photograph is readable and your answers are present.</li><li>Submit it to the assignment your teacher identifies in Teams. The app does not submit automatically.</li><li>Keep a backup if you need to continue on another device.</li></ol><div class="toolbar"><button id="export" class="primary">Export PDF</button><button id="backupEnd">Save lesson backup</button></div><p>Keep your PDF and backup private: both include your name and work. Work saved in this browser is not shared with your teacher until you submit it.</p>`)+`<p class="small">Network security · OxfordAQA 9210, section 3.5 · Reading: Student Book printed pp. 248–251. Main task and challenge marks are classroom allocations; the November 2024 question keeps its original four marks.</p>`;
}}
function render(){const [id,title,time]=L.stages[state.step];$('content').innerHTML=`<div class="stage-head"><p class="eyebrow">${time} · PAPER 2 · 3.5</p><h1 tabindex="-1">${title}</h1></div>`+content(id);$('identity').textContent=state.name.toLowerCase()==='teacher'?'Teacher preview · all stages open':state.name+' · '+state.cls;$('nav').innerHTML=L.stages.map((s,i)=>`<button data-step="${i}" ${i===state.step?'aria-current="step"':''}>${i+1}. ${s[1]}</button>`).join('');$('position').textContent=`${state.step+1} of ${L.stages.length} · ${title}`;$('prev').disabled=state.step===0;$('next').disabled=state.step===L.stages.length-1;}
function go(n){state.step=Math.max(0,Math.min(L.stages.length-1,n));render();save();window.scrollTo(0,0);$('content').querySelector('h1').focus({preventScroll:true});}
async function enter(name,cls){state=blank(name,cls);try{db=db||await openDB();const prior=await get(profile());if(prior)state=prior;}catch{memoryOnly=true;}$('landing').hidden=true;$('lesson').hidden=false;render();save();}
$('login').addEventListener('submit',async e=>{e.preventDefault();const name=$('name').value.trim(),cls=$('class').value.trim();if(!name||(!cls&&name.toLowerCase()!=='teacher')){$('loginError').textContent='Please enter your name and class.';return;}await enter(name,cls);});
document.addEventListener('input',e=>{if(!state)return;const k=e.target.dataset.answer;if(k){state.answers[k]=e.target.value;save();}if(e.target.dataset.caption){const[s,i]=e.target.dataset.caption.split(':');state.photos[s][i].caption=e.target.value;save();}});
document.addEventListener('change',e=>{if(e.target.matches('select[data-answer]')){state.answers[e.target.dataset.answer]=e.target.value;save();const key=e.target.dataset.answer;render();const el=document.querySelector(`[data-answer="${key}"]`);if(el)el.focus();}if(e.target.dataset.upload)upload(e.target.files,e.target.dataset.upload);});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||!state)return;if(b.dataset.step!==undefined)go(Number(b.dataset.step));if(b.id==='next')go(state.step+1);if(b.id==='prev')go(state.step-1);if(['export','exportTop'].includes(b.id))exportPDF();if(['backup','backupEnd'].includes(b.id))backup();if(b.id==='switch'){$('lesson').hidden=true;$('landing').hidden=false;$('name').value='';$('class').value='';state=null;}
if(b.id==='snapshot'){if(!state.answers.feedback_note?.trim()||!state.answers.improved?.trim()){alert('Add your feedback and improved answer first.');return;}state.feedback.push({time:new Date().toLocaleString('en-GB'),original:Object.fromEntries(['a1','a2','a3','a4','a5'].map(k=>[k,state.answers[k]||''])),note:state.answers.feedback_note,improved:state.answers.improved});save();render();}
if(b.dataset.remove&&confirm('Remove this photograph from your saved work?')){const[s,i]=b.dataset.remove.split(':');state.photos[s].splice(Number(i),1);save();render();}});
function readData(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});}
async function resize(file){if(!/^image\/(png|jpeg|webp)$/.test(file.type)||file.size>15*1024*1024)throw Error('Please choose a PNG, JPG or WebP image smaller than 15 MB.');const src=await readData(file),im=new Image();await new Promise((resolve,reject)=>{im.onload=resolve;im.onerror=reject;im.src=src;});const scale=Math.min(1,2000/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*scale);c.height=Math.round(im.height*scale);const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(im,0,0,c.width,c.height);return {name:file.name||'Pasted image',caption:'',data:c.toDataURL('image/jpeg',.9)};}
async function upload(files,stage){const owner=state;try{for(const f of files){const p=await resize(f);if(state!==owner)return;(state.photos[stage]??=[]).push(p);}await save();render();}catch(e){alert(e.message||'This image could not be read. Try a JPG or PNG.');}}
document.addEventListener('paste',e=>{if(!state)return;const stage=L.stages[state.step][0];if(!['start','learn','apply','extension','exit'].includes(stage))return;const files=[...(e.clipboardData?.items||[])].filter(x=>x.type.startsWith('image/')).map(x=>x.getAsFile());if(files.length){e.preventDefault();upload(files,stage);}});
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
const filename=()=>('Year11_W4S1_'+state.name).replace(/[^a-z0-9_-]/gi,'_');
function backup(){download(new Blob([JSON.stringify({app:'w4s1-security',state})],{type:'application/json'}),filename()+'.json');}
let pendingRestore=null;
const restorePanel=document.createElement('div');restorePanel.id='restorePanel';restorePanel.hidden=true;restorePanel.className='card';
restorePanel.innerHTML='<p id="restoreSummary"></p><button id="confirmRestore" type="button" class="primary">Restore this work</button> <button id="cancelRestore" type="button">Cancel</button>';
$('landing').append(restorePanel);
$('restore').addEventListener('change',async e=>{
 try{
  pendingRestore=null;restorePanel.hidden=true;$('loginError').textContent='';
  const f=e.target.files[0];if(!f)return;if(f.size>60*1024*1024)throw Error('Backup is too large.');
  const raw=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('Could not read this backup.'));r.readAsText(f);});
  const data=JSON.parse(raw),s=data.state;
  if(data.app!=='w4s1-security'||s?.version!==1||typeof s.name!=='string'||typeof s.cls!=='string'||!s.answers||!s.photos||!Array.isArray(s.feedback)||!Number.isInteger(s.step)||s.step<0||s.step>=L.stages.length)throw Error('Choose a backup from this lesson.');
  for(const v of Object.values(s.answers))if(typeof v!=='string')throw Error('Invalid answer data.');
  for(const arr of Object.values(s.photos)){if(!Array.isArray(arr))throw Error('Invalid photos.');for(const p of arr)if(typeof p.data!=='string'||!/^data:image\/(jpeg|png|webp);base64,[a-z0-9+/=]+$/i.test(p.data))throw Error('Invalid image in backup.');}
  for(const f of s.feedback)if(!f||typeof f.note!=='string'||typeof f.improved!=='string'||!f.original)throw Error('Invalid feedback in backup.');
  pendingRestore=s;$('restoreSummary').textContent='Restore work for '+s.name+' · '+s.cls+'? This will replace the saved work for that name and class in this browser.';
  restorePanel.hidden=false;$('confirmRestore').focus();
 }catch(err){$('loginError').textContent=err.message||'Could not restore this backup.';}
});
$('cancelRestore').addEventListener('click',()=>{pendingRestore=null;restorePanel.hidden=true;$('restore').value='';});
$('confirmRestore').addEventListener('click',async()=>{if(!pendingRestore)return;state=pendingRestore;pendingRestore=null;restorePanel.hidden=true;try{db=db||await openDB();}catch{}$('landing').hidden=true;$('lesson').hidden=false;render();await save();});
async function exportPDF(){const b=$('exportTop');b.disabled=true;$('saveStatus').textContent='Preparing PDF…';try{L.stages.forEach(([id])=>content(id));const {jsPDF}=window.jspdf,doc=new jsPDF({unit:'mm',format:'a4',compress:true});doc.addFileToVFS('Raleway.ttf',PDF_FONTS.regular);doc.addFont('Raleway.ttf','Raleway','normal');doc.addFileToVFS('RalewayBold.ttf',PDF_FONTS.bold);doc.addFont('RalewayBold.ttf','Raleway','bold');let y=22;const page=()=>{doc.addPage();y=22;};function text(t,size=11,bold=false){doc.setFont('Raleway',bold?'bold':'normal');doc.setFontSize(size);for(const line of doc.splitTextToSize(String(t||'Not recorded'),174)){if(y>272)page();doc.text(line,18,y);y+=size*.5;}y+=3;}function heading(t){if(y>240)page();text(t,16,true);}text('YEAR 11 · COMPUTER SCIENCE',12,true);text(L.title,24,true);text('Term 1 · Week 4 · Session 1 · Paper 2 · 3.5');text(state.name+' · '+state.cls+' · '+state.date);text('WAGBA: '+L.wagba);text('Learning phases are self-reports, not grades. Blank responses have not been scored.');
for(const [id,title] of L.stages.filter(s=>s[0]!=='submit')){page();heading(title);if(id==='apply')text('Classroom task: 10 marks available. Original answers and improvements are recorded separately.');if(id==='extension')text('Optional: November 2024 9210/2 Q06.1–06.2 (4 marks), plus separate classroom challenge (6 marks).');for(const [key,m] of meta){if(m.stage!==id)continue;text(m.label,10,true);text(state.answers[key]);}if(id==='before'){const c=L.checks.find(c=>c.type+': '+c.title===state.answers.focus);if(c){text('Suggested starting action',10,true);text(c.start);}}if(id==='pit'){for(const c of L.checks){text(c.type+': '+c.statement,10,true);text('Starting point: '+(state.answers['before_'+c.id]||'Not recorded'));text('Current phase: '+(state.answers['after_'+c.id]||'Not recorded'));text('Suggested action: '+suggested(c));}}if(id==='apply')for(const f of state.feedback){heading('Saved feedback · '+f.time);for(const[k,v]of Object.entries(f.original)){text(meta.get(k)?.label||k,10,true);text(v);}text('Feedback: '+f.note);text('Improved answer: '+f.improved);}for(const p of state.photos[id]||[]){const props=doc.getImageProperties(p.data),scale=Math.min(174/props.width,215/props.height),w=props.width*scale,h=props.height*scale;if(y+h+18>272)page();text(p.caption||p.name,10,true);doc.addImage(p.data,'JPEG',18,y,w,h);y+=h+8;}}
const pages=doc.getNumberOfPages();for(let i=1;i<=pages;i++){doc.setPage(i);doc.setDrawColor(150);doc.line(18,282,192,282);doc.setFont('Raleway','normal');doc.setFontSize(8);doc.text('Network security · '+state.name,18,288);doc.text(`${i} / ${pages}`,192,288,{align:'right'});}doc.save(filename()+'.pdf');$('saveStatus').textContent=memoryOnly?'PDF downloaded. Device save unavailable.':'PDF downloaded · check it, then submit to Teams.';}catch(err){alert('PDF export failed. Save a lesson backup now and try again. '+err.message);$('saveStatus').textContent='Export failed — save a backup.';}finally{b.disabled=false;}}
window.addEventListener('beforeunload',e=>{if(state&&memoryOnly){e.preventDefault();e.returnValue='';}});
})();
