window.LESSON = {
 title:'Securing a school network', wagba:'Choosing suitable network-security measures and explaining how they protect a network.',
 stages:[['start','Do Now','5 min'],['before','Types of Learning','3 min'],['learn','Main Activity 1','18 min'],['apply','Main Activity 2','22 min'],['pit','Learning Pitstop','4 min'],['extension','Extension','Optional'],['exit','Plenary','5 min'],['submit','Save & submit','3 min']],
 before:['Already knew / could do independently','With reading or a prompt','New to me','Not sure / not checked yet'],
 phases:['New learning — a good struggle','Consolidating','Treading water — I need more challenge','Drowning — I need help','Not attempted yet'],
 checks:[
 {id:'identity',type:'Knowledge',title:'User and device checks',statement:'I can describe what authentication and MAC address filtering check.',evidence:'Use your shared-laptop response and the first two rows of your school-network plan.',start:'Read “Who are you?” and “Which device?” in Main Activity 1. Say what each check compares.',actions:['Use the reading to complete: authentication checks …; MAC filtering checks …','Recall both checks without the panels. Give a school example of each.','Explain why a stolen approved laptop still needs user authentication.','Ask your teacher to compare one person’s login with one device’s MAC address. Point to what each check verifies.']},
 {id:'traffic',type:'Knowledge',title:'Data and traffic protection',statement:'I can describe how encryption and a firewall work.',evidence:'Point to your explanations of ciphertext and traffic rules in Main Activity 2.',start:'Compare “Can someone read it?” and “Which traffic is allowed?” in Main Activity 1.',actions:['Follow the encryption arrows, then say what a firewall checks instead.','Explain both mechanisms without reading. Check that you mention a key and filtering rules.','Explain why encrypted traffic can still be blocked by a firewall rule.','Ask your teacher to show one readable message and one traffic rule. Explain which measure changes data and which filters traffic.']},
 {id:'choose',type:'Skills',title:'Choosing a suitable measure',statement:'I can identify a security requirement and select a suitable measure.',evidence:'Use the four requirements in your Main Activity 2 plan.',start:'Underline what must be protected in each scenario before choosing a measure.',actions:['Work through one scenario with a partner. Identify whether it concerns a user, a device, traffic or readable information.','Try another scenario without notes and justify your selection.','Recommend two measures for the extension and show that they address different risks.','Show your teacher one scenario. Together, identify what the school needs to check or protect before naming a measure.']},
 {id:'explain',type:'Skills',title:'Writing a precise explanation',statement:'I can connect a measure, its operation and its benefit in the situation.',evidence:'Compare one original answer with your saved improvement after feedback.',start:'Study the encryption model. Write your own answer using measure → mechanism → benefit.',actions:['Use the model structure for a different measure. Explain the mechanism, not just “it is safer”.','Rewrite one explanation without the sentence starter and check its scenario link.','Improve a technically correct but generic answer so that every sentence addresses the requirement.','Show your teacher your chosen measure. Explain aloud what it does, then write that sentence before adding the benefit.']},
 {id:'device',type:'Understanding',title:'Device approval is not user identity',statement:'I can explain why approving a device does not prove who is using it.',evidence:'Use the shared-laptop checkpoint and your explanation of why a login remains necessary.',start:'Imagine two different people using the same approved school laptop. Which check would distinguish them?',actions:['Use the shared-laptop example to explain what stays the same when another person uses it.','Explain without notes why an approved MAC address does not prove the user’s identity.','Consider a borrowed approved laptop. Distinguish device access, user authentication and permission to view staff records.','Ask your teacher to separate “Which device?” from “Who is using it?” using one laptop and two people.']},
 {id:'layers',type:'Understanding',title:'Using measures together',statement:'I can explain why one security measure cannot replace all the others.',evidence:'Use your final Main Activity 2 answer about authentication and encryption.',start:'For each measure, identify a different problem it does not solve.',actions:['Explain one reason why an approved device still needs a user login.','Without the reading, explain why encryption does not replace authentication.','Explain why someone with a valid password may still act unsafely and why other controls matter.','Ask your teacher to compare “Who may sign in?” with “Can an intercepted message be read?” Choose a different measure for each.']}
 ],
 fields:[],
 scenarios:[
 ['A person tries to sign in to a teacher’s account. The system must check that the person can provide the correct credentials.','Authentication checks the supplied credentials against the account’s expected credentials before allowing access. A valid login is not a guarantee that the person will act safely.'],
 ['The assessment wireless network should accept only school-approved devices, using their network-adapter addresses.','MAC address filtering compares a device’s MAC address with an allowed list. It does not prove the identity of the person using the device.'],
 ['An incoming connection does not meet the network administrator’s permitted-traffic rules.','A firewall checks traffic against configured rules and blocks traffic that fails them. It is not a guarantee that every allowed file or connection is safe.'],
 ['Confidential assessment information might be intercepted as it travels to the server.','Encryption converts plaintext to ciphertext using an algorithm and key. Someone without the appropriate decryption key should not be able to understand the intercepted information. It does not stop interception itself.']
 ]
};
