const STAGES=[
  {id:'preparation',title:'Prepare',optional:false},{id:'starter',title:'Starter',optional:false},{id:'plan',title:'Plan',optional:false},{id:'build',title:'Build & test',optional:false},{id:'extension',title:'Extension',optional:true},{id:'plenary',title:'Plenary',optional:false},{id:'review',title:'Review',optional:false}
];
const REQUIRED={
  preparation:['deviceNumber','projectName','editor','equipmentReady'],
  starter:['orderDisplayInitials','orderStart','orderIcon','orderWait','orderEnd','starterInput','starterProcess','starterOutput','starterHinge'],
  plan:['purpose','user','startupOutput','inputPlan','buttonOutput','testingPlan','ipoInput','ipoProcess','ipoOutput','algorithm','planChecked'],
  build:['chosenIcon','chosenMessage','predictStartup','predictButton','test1Expected','test1Actual','test1Result','test2Expected','test2Actual','test2Result','test3Expected','test3Actual','test3Result','debugNote','simulatorDone','transferDone','physicalDone','screenshotDone'],
  plenary:['plenaryInput','plenaryProcess','plenaryOutput','plenaryAlgorithm','plenaryTest','plenaryReflection','fullyTested','fullyTestedExplain']
};
const DEFAULT_STATE={studentName:'',studentClass:'',current:'preparation',completed:{},responses:{},checks:{},image:null,updated:null};
let teacher=new URLSearchParams(location.search).get('teacher')==='1';
let storageKey=teacher?'y8-w2-project-teacher':'y8-w2-project-student';
let state=load();let saveTimer;let imageData=null;
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function load(){try{return {...DEFAULT_STATE,...JSON.parse(localStorage.getItem(storageKey)||'{}')}}catch{return structuredClone(DEFAULT_STATE)}}
function save(){state.updated=new Date().toISOString();localStorage.setItem(storageKey,JSON.stringify(state));$('#saveStatus').textContent='Saved';renderProgress();}
function queueSave(){$('#saveStatus').textContent='Saving…';clearTimeout(saveTimer);saveTimer=setTimeout(save,350)}
function clean(v){return typeof v==='string'?v.trim():v}
function slug(v){return v.replace(/[^a-z0-9]+/gi,'_').replace(/^_|_$/g,'')}
function start(){
  $('#entry').hidden=true;$('#app').hidden=false;$('#studentHeader').textContent=`${state.studentName} · ${state.studentClass}`;renderJourney();showStage(state.current||'preparation');
}
$('#entryForm').addEventListener('submit',e=>{e.preventDefault();const name=$('#studentName').value.trim(),cl=$('#studentClass').value.trim();if(name.toLowerCase()==='teacher'){teacher=true;storageKey='y8-w2-project-teacher';state=load();state.studentName='Teacher Preview';state.studentClass=cl||'Year 8';save();start();return}if(!name||!cl){$('#entryError').textContent='Enter your full name and class before beginning.';return}state.studentName=name;state.studentClass=cl;save();start()});
if(teacher&&!state.studentName){state.studentName='Test Student';state.studentClass='8T';state.responses={deviceNumber:'01',projectName:'Y8_8T_Test_Student_W2_SmartBadge',editor:'MakeCode Blocks'};save()}
if(state.studentName&&state.studentClass)start();
function renderJourney(){const host=$('#journey');host.innerHTML='';STAGES.forEach((s,i)=>{const b=document.createElement('button');b.type='button';b.dataset.stage=s.id;b.innerHTML=`<strong>${String(i).padStart(2,'0')} · ${s.title}</strong><small>${s.optional?'Optional':'Core'}</small>`;b.addEventListener('click',()=>showStage(s.id));host.append(b)});renderProgress()}
function unlocked(id){if(teacher)return true;const i=STAGES.findIndex(s=>s.id===id);if(i===0)return true;if(id==='extension')return !!state.completed.build;if(id==='plenary')return !!state.completed.build;if(id==='review')return !!state.completed.plenary;const prev=STAGES[i-1];return prev.optional?!!state.completed[STAGES[i-2].id]:!!state.completed[prev.id]}
function renderProgress(){const core=STAGES.filter(s=>!s.optional&&s.id!=='review');const done=core.filter(s=>state.completed[s.id]).length;$('#progressBar').style.width=`${done/core.length*100}%`;$$('#journey button').forEach(b=>{b.disabled=!unlocked(b.dataset.stage);b.classList.toggle('current',b.dataset.stage===state.current);b.classList.toggle('complete',!!state.completed[b.dataset.stage])})}
function showStage(id,force=false){if(!force&&!unlocked(id))return;state.current=id;queueSave();const t=$(`#stage-${id}`);$('#stageHost').replaceChildren(t.content.cloneNode(true));bindInputs();bindChecks();restoreInputs();if(id==='build')setEditorLink();if(id==='review')renderReport();const i=STAGES.findIndex(s=>s.id===id);$('#backButton').disabled=i===0;$('#backButton').onclick=()=>showStage(STAGES[Math.max(0,i-1)].id);$('#nextButton').textContent=id==='review'?'Return to start':id==='extension'?'Skip / continue':'Check and continue';$('#nextButton').onclick=()=>advance(id,i);renderProgress();const lesson=$('.lesson');if(lesson)lesson.scrollIntoView({block:'start',behavior:'auto'})}
function bindInputs(){$$('[data-save]').forEach(el=>{el.addEventListener('input',capture);el.addEventListener('change',capture)});$$('[data-image]').forEach(el=>el.addEventListener('change',handleImage));$$('[data-paste]').forEach(el=>el.addEventListener('paste',handlePaste))}
function capture(e){const el=e.currentTarget,key=el.dataset.save;state.responses[key]=el.type==='checkbox'?el.checked:el.value;queueSave()}
function restoreInputs(){$$('[data-save]').forEach(el=>{const v=state.responses[el.dataset.save];if(v===undefined)return;if(el.type==='checkbox')el.checked=!!v;else if(el.type==='radio')el.checked=el.value===v;else el.value=v});if(imageData)showImage(imageData)}
function bindChecks(){$$('[data-check]').forEach(b=>b.addEventListener('click',()=>checkTask(b.dataset.check)))}
function checkTask(id){let ok=false,msg='';if(id==='starterOrder'){const r=state.responses;ok=+r.orderStart===1&&+r.orderIcon===2&&+r.orderWait===3&&+r.orderDisplayInitials===4&&+r.orderEnd===5;msg=ok?'Correct. The event must happen before the button output.':'Recheck the cause and effect: the program starts and shows the icon before it waits for Button A.'}else{const r=state.responses;ok=r.starterInput==='Button A is pressed'&&r.starterProcess==='The program detects the event and runs its instructions'&&r.starterOutput==='Initials or a message appear on the LEDs';msg=ok?'Correct. You separated the trigger, internal action and visible result.':'Check each role: input is the trigger, process is what the program does, and output is what the user observes.'}state.checks[id]=ok;const p=$(`[data-feedback="${id}"]`);p.textContent=msg;p.className=`feedback ${ok?'success':'improve'}`;queueSave()}
function completed(id){if(teacher)return true;if(id==='extension'||id==='review')return true;const missing=(REQUIRED[id]||[]).filter(k=>{const v=state.responses[k];return v===undefined||v===false||clean(v)==='' });if(id==='starter'&&(!state.checks.starterOrder||!state.checks.starterIPO))missing.push('checked starter tasks');if(id==='plan'){const steps=(state.responses.algorithm||'').split(/\n/).filter(x=>x.trim()).length;if(steps<5)missing.push('5–7 algorithm steps')}if(id==='build'&&!imageData)missing.push('uploaded screenshot or device photo');return missing}
function advance(id,i){if(id==='review'){showStage('preparation');return}const missing=completed(id);if(Array.isArray(missing)&&missing.length){alert(`Complete these before continuing:\n• ${missing.join('\n• ')}`);return}if(id!=='extension')state.completed[id]=true;save();let next=i+1;if(id==='build')next=STAGES.findIndex(s=>s.id==='extension');showStage(STAGES[Math.min(next,STAGES.length-1)].id)}
function setEditorLink(){const choice=state.responses.editor||'MakeCode Blocks';$('#chosenEditor').textContent=choice;const a=$('#chosenEditorLink');a.href=choice.includes('Python')?'https://python.microbit.org/v/3':'https://makecode.microbit.org/';a.textContent=`Open ${choice} ↗`}
function handleImage(e){const f=e.target.files[0];if(f)storeImage(f,f.name,e.target)}
function handlePaste(e){const item=[...(e.clipboardData?.items||[])].find(x=>x.type.startsWith('image/'));if(!item){alert('No image was found on the clipboard. Copy a screenshot, then paste again.');return}e.preventDefault();storeImage(item.getAsFile(),'pasted-smart-badge-evidence.png')}
function storeImage(f,name,input){if(!f)return;if(f.size>6*1024*1024){alert('Choose an image smaller than 6 MB.');if(input)input.value='';return}const reader=new FileReader();reader.onload=()=>{imageData=reader.result;try{localStorage.setItem(`${storageKey}-image`,imageData)}catch{alert('The image is too large to save in this browser. Keep the original file and choose a smaller screenshot.')}showImage(imageData);state.responses.buildEvidenceName=name;queueSave()};reader.readAsDataURL(f)}
function showImage(src){const p=$('[data-preview="buildEvidence"]');if(p){p.innerHTML=`<img src="${src}" alt="Uploaded Smart Badge evidence preview"><button class="secondary" type="button" data-remove-image>Remove evidence</button>`;p.querySelector('[data-remove-image]').addEventListener('click',()=>{imageData=null;localStorage.removeItem(`${storageKey}-image`);delete state.responses.buildEvidenceName;p.innerHTML='';queueSave()})}}
try{imageData=localStorage.getItem(`${storageKey}-image`)}catch{}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function ans(k){const v=state.responses[k];return v===undefined||v===false||clean(v)===''?'<span class="not-complete">Not completed</span>':`<div class="report-answer">${esc(v===true?'Completed':v)}</div>`}
function renderReport(){const sections=[['Student and setup',[['Name',state.studentName],['Class',state.studentClass],['Device','deviceNumber'],['Editor','editor'],['Project name','projectName']]],['Starter',[['Algorithm explanation','starterHinge'],['Input','starterInput'],['Process','starterProcess'],['Output','starterOutput']]],['Planning',[['Purpose','purpose'],['User','user'],['Startup output','startupOutput'],['Button input','inputPlan'],['Button output','buttonOutput'],['IPO process','ipoProcess'],['Algorithm','algorithm']]],['Testing',[['Prediction: startup','predictStartup'],['Prediction: Button A','predictButton'],['Test 1 result','test1Result'],['Test 2 result','test2Result'],['Test 3 result','test3Result'],['Correction / success / limitation','debugNote']]],['Plenary',[['Input explanation','plenaryInput'],['Processing explanation','plenaryProcess'],['Output explanation','plenaryOutput'],['How the algorithm helped','plenaryAlgorithm'],['Test completed','plenaryTest'],['Reflection','plenaryReflection'],['Fully tested?','fullyTested'],['Reason','fullyTestedExplain']]]];if(Object.keys(state.responses).some(k=>k.startsWith('extension')&&clean(state.responses[k])!==''))sections.splice(4,0,['Optional extension',[['Button B purpose','extensionIntent'],['Change','extensionChange'],['Prediction','extensionPrediction'],['Result','extensionResult'],['Explanation','extensionExplain']]]);$('#report').innerHTML=`<div class="print-only"><h1>Year 8 Week 2 Project — Smart Badge Mission 1</h1><p>${esc(state.studentName)} · ${esc(state.studentClass)} · ${new Date().toLocaleDateString()}</p><p><strong>WAGBA:</strong> We are getting better at representing a precise algorithm and applying input–process–output to a Smart Badge.</p></div>`+sections.map(([title,items])=>`<section class="report-card"><h3>${title}</h3>${items.map(([label,key])=>`<strong>${label}</strong>${typeof key==='string'&&key in state.responses?ans(key):`<div class="report-answer">${esc(key)}</div>`}`).join('')}</section>`).join('')+(imageData?`<section class="report-card"><h3>Uploaded evidence</h3><img src="${imageData}" alt="Student uploaded project evidence" style="max-width:100%;max-height:440px"></section>`:'<section class="report-card"><h3>Uploaded evidence</h3><span class="not-complete">Not completed</span></section>')}
$('#learningToggle').addEventListener('click',()=>{const p=$('#learningPanel');p.classList.toggle('open');$('#learningToggle').setAttribute('aria-expanded',p.classList.contains('open'))});$('#learningClose').addEventListener('click',()=>$('#learningPanel').classList.remove('open'));
function printReport(){showStage('review',true);const oldTitle=document.title;document.title=`Year8_${slug(state.studentClass)}_${slug(state.studentName)}_Week2_Project`;setTimeout(()=>{window.print();document.title=oldTitle},120)}$('#printButton').addEventListener('click',printReport);$('#resetButton').addEventListener('click',()=>{if(confirm('Delete all saved answers and evidence for this lesson?')){localStorage.removeItem(storageKey);localStorage.removeItem(`${storageKey}-image`);location.reload()}});document.addEventListener('click',e=>{if(e.target?.id==='printFinal')printReport();if(e.target?.id==='downloadJson'){const payload={lesson:'Year8-T1-W2-SmartBadge',version:1,...state};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Year8_${slug(state.studentClass)}_${slug(state.studentName)}_W2_Project_Backup.json`;a.click();URL.revokeObjectURL(a.href)}});
