(function (root) {
  'use strict';
  const L = root.Lesson;
  const e = v => String(v ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
  const button = (action, text, extra = '', primary = false) => `<button type="button" data-action="${action}" ${extra} class="${primary ? 'primary' : 'secondary'}">${text}</button>`;
  const link = (url, text) => `<a href="${e(url)}" target="_blank" rel="noopener noreferrer">${text} ↗</a>`;
  const note = (html, kind = '') => `<div class="note ${kind}">${html}</div>`;
  const text = (s, key, label, prompt = '', rows = 2) => `<div class="field"><label for="f-${key}">${label}</label>${prompt ? `<p id="h-${key}" class="small">${prompt}</p>` : ''}<textarea id="f-${key}" data-field="${key}" rows="${rows}" maxlength="6000" ${prompt ? `aria-describedby="h-${key}"` : ''}>${e(s.responses[key] || '')}</textarea></div>`;
  const input = (s, key, label, max = 100) => `<div class="field"><label for="f-${key}">${label}</label><input id="f-${key}" data-field="${key}" value="${e(s.responses[key] || '')}" maxlength="${max}"></div>`;
  function choices(s, key, title, values = L.VALUES[key]) {
    return `<fieldset class="field"><legend>${title}</legend><div class="choices">${Object.entries(values).map(([val, label]) => `<label class="choice"><input type="radio" name="${key}" data-field="${key}" value="${e(val)}" ${s.responses[key] === val ? 'checked' : ''}><span>${e(label)}</span></label>`).join('')}</div></fieldset>`;
  }
  const image = (name, alt) => `<button type="button" class="figure-link" data-action="image" data-image="${e(name)}" data-alt="${e(alt)}" aria-label="Enlarge: ${e(alt)}"><img src="assets/images/${e(name)}" alt="${e(alt)}" loading="lazy"><span class="small">Tap to enlarge</span></button>`;
  const guide = (name, alt, caption = '') => `<details class="small-guide"><summary>Optional picture guide</summary>${image(name, alt)}${caption ? `<p class="small">${caption}</p>` : ''}</details>`;
  function where(s, task) {
    const micro = s.responses.editor === 'micropython';
    const ipad=s.responses.device==='ipad';
    return `<div class="place"><span>${ipad?'RETURN TO YOUR MAKECODE PROJECT':'RETURN TO YOUR EDITOR TAB'}</span><strong>${e(L.label('editor', s.responses.editor || 'blocks'))}</strong></div><p class="small">${ipad?'Switch back to the micro:bit app and the project you already opened. If you are using the browser alternative, return to that existing editor tab.':'Use the editor tab you already opened.'} <strong>Do not create another project for this card.</strong> ${link(micro ? L.LINKS.micropython : L.LINKS.makecode, 'Browser editor, if not already open')}</p><p>${task}</p>`;
  }
  function support(s, id) {
    const d = L.SUPPORT[s.language];
    if (!d) return '';
    return `<details open class="language-support"><summary>${d.label} · Task instructions</summary><p lang="${s.language === 'zh' ? 'zh-Hans' : s.language === 'bm' ? 'ms' : 'ko'}">${e(d[id])}</p><button type="button" class="text-button" data-action="glossary">English + ${d.label} vocabulary</button></details>`;
  }
  function code(s, withButton, withB = false) {
    const r = s.responses, initial = !withButton;
    const sample = L.sample(r.editor, initial ? 'HEART' : r.icon, initial ? 'AB' : r.message, withButton, withB);
    return `<div class="code-wrap"><label for="exampleCode"><strong>${e(L.label('editor', r.editor))} · ${withB ? 'example with B' : initial ? 'first working example' : 'your two choices applied to the example'}</strong></label><textarea id="exampleCode" readonly spellcheck="false" rows="${Math.min(12, sample.split('\n').length + 1)}">${e(sample)}</textarea><div class="buttons">${button('copy-code', 'Copy example code')}<span class="small">Paste into the editor’s Python code area—not into a block or this lesson.</span></div></div>`;
  }
  function model(s, withButton = false) {
    const r = s.responses;
    if (r.editor !== 'blocks') return code(s, withButton);
    return `<div class="two"><div class="block-example"><strong>on start</strong><div class="nested">show icon: ${e(withButton ? L.label('icon',r.icon || 'HEART') : 'Heart')}</div></div>${withButton ? `<div class="block-example"><strong>on button A pressed</strong><div class="nested">show string: “${e(r.message || 'AB')}”</div></div>` : ''}</div>`;
  }
  function inlineGrade(s, key) {
    const check = s.checks[key];
    return `<div id="feedback-${key}" aria-live="polite">${check && check.answer === s.responses[key] ? feedback(s,key,check) : ''}</div>`;
  }
  function feedback(s,key,check){return note(`<p>${e(check.message)}</p>${L.FEEDBACK_SUPPORT[s.language]?.[key]?`<p>${e(L.FEEDBACK_SUPPORT[s.language][key])}</p>`:''}`,check.correct?'good':'warn');}
  function setupGuide(s) {
    const r = s.responses;
    if (!r.device || !r.editor) return note('Choose a device and an editor. Your instructions will appear here.');
    if (r.device === 'ipad') return note(`<strong>iPad route: MakeCode + the micro:bit app.</strong><ol><li>Use the school-installed <strong>micro:bit app</strong>. Choose <strong>Create Code</strong> to open MakeCode.</li><li>Start a project called <strong>Y8_${e(s.student.className)}_SmartBadge_W2</strong>.</li><li>${r.editor === 'makepython' ? 'At the top of MakeCode, open the menu beside JavaScript and choose Python. This is <strong>MakeCode Python</strong>, not MicroPython.' : 'Stay in <strong>Blocks</strong>. Use the toolbox and drag blocks into the workspace.'}</li></ol><p>If the app is not available, ${link(L.LINKS.makecode,'open MakeCode in your browser')} to build and test. Ask your teacher to help with the app before physical transfer.</p><p class="small">${link(L.LINKS.ipad,'Official iPad connection guide')} · Keep this lesson open in its own tab. Return here after each editor task.</p>`);
    return note(`<ol><li>${link(r.editor === 'micropython' ? L.LINKS.micropython : L.LINKS.makecode,'Open your editor')} in a new tab.</li><li>Create/name a project <strong>Y8_${e(s.student.className)}_SmartBadge_W2</strong>.</li><li>${r.editor === 'blocks' ? 'Stay in <strong>Blocks</strong>. The toolbox is on the left of the workspace.' : r.editor === 'makepython' ? 'Open the menu beside <strong>JavaScript</strong> and choose <strong>Python</strong> in MakeCode.' : 'Use the large Python code area in the <strong>micro:bit Python Editor</strong>. This uses MicroPython, not MakeCode Python.'}</li></ol><p class="small">Leave this lesson open. Switch back to this tab to record results. Save an existing project before replacing its code.</p>`);
  }
  function routeChoices(s) {
    const r=s.responses;
    const options=`<div class="two">${choices(s,'device','1. My device')}${choices(s,'editor','2. My editor',r.device === 'ipad' ? { blocks: 'MakeCode Blocks — easiest starting route', makepython: 'MakeCode Python — in the same MakeCode editor' } : { blocks: 'MakeCode Blocks — recommended for first-time users', makepython: 'MakeCode Python — same editor, text code', micropython: 'MicroPython — optional separate laptop editor' })}</div>`;
    return r.device && r.editor ? `<details><summary>${e(L.label('device',r.device))} · ${e(L.label('editor',r.editor))} — change choices</summary>${options}</details>` : options;
  }
  function transferGuide(s) {
    if (s.responses.device === 'ipad') return `<p><strong>Use the micro:bit iOS app and Bluetooth—not a USB file-copy instruction.</strong></p><ol class="instruction-list"><li>Power your micro:bit using the teacher-approved battery pack. Keep it beside the iPad.</li><li>Open the <strong>micro:bit app</strong>, return to your MakeCode project, and choose <strong>Download</strong>. Follow the app’s pairing/send prompts.</li><li>When prompted, enter pairing mode. Normally, hold <strong>A + B</strong>, press and release <strong>reset</strong>, then release A + B when the pairing pattern appears. Match <strong>your own device’s pattern</strong> in the app.</li><li>Wait until the app confirms transfer is finished. Restart the micro:bit and press A. Compare both outputs with your two choices.</li></ol><details><summary>My project is in a browser / pairing does not work</summary><p>Do not start a new project and lose your work. Save/download the project first. If using Chrome’s MakeCode download handoff, choose <strong>Open app</strong> when offered. Otherwise ask your teacher to open/import your saved project in the app.</p><p>A micro:bit last used with MicroPython may need a MakeCode program loaded from a computer first. Your teacher should handle this. Do not keep resetting a device that will not pair.</p>${link(L.LINKS.ipad,'Official current iPad instructions')}</details>`;
    return `<ol class="instruction-list"><li>Hold the board by its edges. Insert the <strong>micro USB plug into the top port</strong>, straight and gently. Connect the other end to the computer using a data cable.</li><li>In your editor, choose <strong>Download</strong> / <strong>Send to micro:bit</strong>. If browser pairing is offered, follow it. Otherwise download the <strong>.hex</strong> file.</li><li>For a downloaded file, open your file manager and copy the <strong>.hex file to the MICROBIT drive</strong>. Do not copy this lesson’s HTML or a screenshot.</li><li>Wait for transfer to finish. Restart the micro:bit, observe the icon, then press A and observe the text.</li></ol><details><summary>The MICROBIT drive does not appear</summary><p>Try another USB port or a teacher-provided data cable. Some cables only charge. Ask for help before changing devices. You may record simulator evidence and mark physical transfer as needing help.</p>${link(L.LINKS.transfer,'Official transfer guide')}</details>`;
  }
  function evidenceSlot(s, images, slot, title) {
    const im = images[slot];
    return `<section class="evidence-slot"><h3>${title}</h3>${im ? `<img src="${e(im.data)}" alt="${e(im.caption || title)}"><div class="field"><label for="cap-${slot}">Optional caption</label><textarea id="cap-${slot}" data-caption="${slot}" rows="2" maxlength="2000">${e(im.caption)}</textarea></div>` : '<p class="small">No image saved yet.</p>'}<label class="file-label" for="upload-${slot}">${im ? 'Replace image' : 'Choose screenshot / photo'}</label><input id="upload-${slot}" type="file" accept="image/png,image/jpeg,image/webp" data-upload="${slot}"><div class="buttons">${button('paste', 'Paste screenshot', `data-slot="${slot}"`)}${im ? button('remove-image','Delete image',`data-slot="${slot}"`) : ''}</div><div class="paste-zone" tabindex="0" data-paste="${slot}" role="group" aria-label="Paste ${title.toLowerCase()} here">Or focus here and press Ctrl+V / ⌘V.</div><p id="upload-status-${slot}" class="small" role="status"></p></section>`;
  }
  function body(s, images, id) {
    const r = s.responses;
    if(['try','button','test','transfer'].includes(id) && (!r.device || !r.editor || (r.device==='ipad' && r.editor==='micropython'))){
      return note('<strong>Choose your device and editor first.</strong><p>That choice gives you the right code and connection instructions. No code or hardware success has been assumed.</p>') + button('go','Choose my device and editor','data-card="setup"',true) + '<p class="small">If you cannot choose yet, you may still continue with a needs-review record.</p>';
    }
    switch(id) {
      case 'starter': return `<p class="lead">At a school welcome desk, a helper’s badge shows an icon when it starts. The helper presses A to introduce themselves.</p><div class="two"><div class="block-example"><strong>When the badge starts</strong><div class="nested">Display a heart icon</div></div><div class="block-example"><strong>When Button A is pressed</strong><div class="nested">Display “AB”</div></div></div>${choices(s,'prediction','The badge is showing the heart. What will happen when A is pressed?')}${button('check','Show feedback','data-key="prediction"')}${inlineGrade(s,'prediction')}<p class="small">This is a starting-point check, not a grade. An incorrect answer will not lock the lesson.</p>`;
      case 'learning': return `<p>Today’s WAGBA is about <strong>creating, testing and explaining</strong> a button-controlled badge. Different learning moves help with different parts.</p><div class="three"><section><h3>Knowledge</h3><p>Remember: a button sends an <strong>input</strong>; the LEDs show an <strong>output</strong>.</p></section><section><h3>Skills</h3><p>Practise placing one instruction in the right place. Run it and observe.</p></section><section><h3>Understanding</h3><p>Predict what will happen. Explain why the code responds at that time.</p></section></div>${choices(s,'strategy','Which move will help you most today?')}${guide('types-of-learning.png','School guidance: knowledge, skills and understanding')}<p class="small">Discuss with your partner for 30 seconds. These are kinds of learning—not fixed types of learner.</p>`;
      case 'setup': return `<p>You will make the <strong>same badge outcome</strong> with different tools. Choose the device you are using now.</p>${routeChoices(s)}${setupGuide(s)}<p class="small"><strong>Before touching equipment:</strong> dry table, hold board edges, never force a connector. Ask your teacher about batteries.</p><details><summary>Equipment and pair routines</summary><p>Use a numbered micro:bit, a tested data cable (laptop) or teacher-approved battery pack (iPad). Do not wear a bare board against your skin.</p><p>If sharing, one person operates while the other reads and predicts. Swap after the first successful run. Both should be able to explain Button A.</p>${input(s,'deviceNumber','Device number (optional)',30)}</details>`;
      case 'try': return where(s,`First, try a <strong>working heart example</strong>. Do not add a button yet. We are checking that you can run a small program.`) + (r.editor === 'blocks' ? `<ol class="instruction-list"><li>Find <strong>Basic → show icon</strong> in the toolbox.</li><li>Drag it <strong>inside on start</strong>. Choose the heart.</li><li>Use the simulator’s run/restart control. Look for the heart on its LED display.</li></ol>` : `<ol class="instruction-list"><li>In your new test project, select the code in the <strong>${e(L.label('editor',r.editor))}</strong> code area.</li><li>Replace it with the small example below. Keep spelling and punctuation unchanged.</li><li>Use the simulator’s run/restart control. Look for a heart.</li></ol>`) + model(s) + choices(s,'firstRun','Come back here: what happened?') + note('If you need help, show your editor screen to your teacher. You can continue with a “needs review” record.','');
      case 'design': return `<p class="lead">You are a student helper at the school welcome desk. Your badge should look welcoming on startup and identify you when A is pressed.</p><p>Make just <strong>two decisions</strong>. You will use them in the next card—no separate planning sheet is needed.</p><div class="two">${choices(s,'icon','Welcome icon')}${input(s,'message','Initials or short welcome word',12)}</div><p class="small">Use a short word such as your initials, not a full name. For reliable LED text, choose A–Z letters/numbers. Your spoken or written explanations may use your support language.</p>${note(`Your design: <strong>${e(L.label('icon',r.icon) || 'choose an icon')}</strong> at startup; <strong>${e(r.message || 'choose your text')}</strong> when A is pressed.`)}`;
      case 'button': return where(s,'Keep your welcome icon. Now make the badge display your chosen text <strong>only when A is pressed</strong>.') + (r.editor === 'blocks' ? `<ol class="instruction-list"><li>Change the icon inside <strong>on start</strong> to your chosen icon.</li><li>From <strong>Input</strong>, drag <strong>on button A pressed</strong> into an empty part of the workspace.</li><li>From <strong>Basic</strong>, drag <strong>show string</strong> <strong>inside the A event</strong>. Replace “Hello!” with your chosen text.</li></ol>${model(s,true)}` : `<p>Replace the small heart-only test with this complete two-behaviour example in the <strong>same Python editor</strong>. It now uses your choices. <strong>Do not paste it below the previous program.</strong></p>${code(s,true)}<details><summary>What do these lines do?</summary><p>${r.editor === 'micropython' ? '<code>display.show</code> sets the startup icon. The supplied <code>while True</code> loop keeps listening; <code>button_a.was_pressed()</code> detects A. The indented <code>display.scroll</code> line runs when that test is true. You are not expected to invent this loop today.' : '<code>basic.show_icon</code> sets the startup icon. The function groups the instructions for A. Its indented <code>basic.show_string</code> line displays the text. <code>input.on_button_pressed</code> connects the function to Button A.'}</p><p>Keep the indentation. MakeCode Python and MicroPython are different: do not mix their commands.</p></details>`) + choices(s,'buttonBuild','Return here after working in the editor') + `<p class="small">You may use the example. To show your understanding, test it and explain your own result on the next cards.</p>`;
      case 'test': return where(s,'Run <strong>two tests</strong>. Do not just check that the code looks right.') + `<div class="two"><section><h3>1. Restart the simulator</h3><p>Expected from your design: <strong>${e(L.label('icon',r.icon) || 'your welcome icon')}</strong>, before pressing any button.</p>${choices(s,'startTest','What happened on restart?')}${r.startTest === 'retry' ? text(s,'startActual','What did you actually see?','“I expected … but I saw …”') : ''}</section><section><h3>2. Press simulator Button A</h3><p>Expected from your design: <strong>${e(r.message || 'your chosen text')}</strong>.</p>${choices(s,'pressTest','What happened when you pressed A?')}${r.pressTest === 'retry' ? text(s,'pressActual','What did you actually see?','“When I pressed A, …”') : ''}</section></div>${text(s,'improvement','One change or successful check','Use one short sentence: “I moved … into …, then … happened.” Or: “Both tests matched because I saw … on restart and … after A.”')}<details><summary>One test failed—what should I look at?</summary><p>Text appears immediately? Check whether the text instruction is in startup instead of the A event. A does nothing? Check that the string instruction is inside/indented in the A response. Python error? Check the editor dialect, spelling and indentation. Make one change, then run both tests again.</p></details>${guide('6-build-test-simulator.png','Concept picture: build, restart the simulator, then press A','The picture illustrates the test actions. Your expected icon and text are the choices shown above—not the symbols in the picture.')}`;
      case 'transfer': return `<div class="place"><span>WORK WITH YOUR DEVICE</span><strong>${e(L.label('device',r.device) || 'Choose a route in Main Task 1')}</strong></div>${transferGuide(s)}${note('Keep liquids away. Do not unplug or turn off the micro:bit during transfer. Hold the connector—not the wire—when disconnecting. Stop and tell your teacher if the board, port or battery is damaged or becomes hot.','warn')}${choices(s,'physical','Record your actual position—not what you hoped would happen')}${text(s,'physicalNote','What did the device show, or where did you get stuck?','“On restart I saw …; after A I saw …” Or: “I reached … but could not …”')}`;
      case 'evidence': return `<p>Keep <strong>one code screenshot</strong> and <strong>one device-output photo</strong>. This is evidence for your teacher, not another writing task.</p><p class="small">Show both startup and A-event code in the screenshot. Photograph only the micro:bit—not people, messages or passwords. Images are compressed and saved in this browser.</p><div class="two">${evidenceSlot(s,images,'code','Code screenshot')}${evidenceSlot(s,images,'device','Physical output photo')}</div><details ${r.evidenceAlternative ? 'open' : ''}><summary>No camera, no device or upload not working?</summary>${text(s,'evidenceAlternative','Tell your teacher what can be checked','“I can show my simulator/code on screen. The physical test is not done because …” Your teacher will review this; the app does not verify a live demonstration.')}</details><div class="buttons">${button('go','Finished early? Choose an extension','data-card="extend1"')}<span class="small">Otherwise continue to the Learning Pitstop.</span></div>`;
      case 'pitstop': return `<p>Pause with your teacher. Think about the <strong>test you just performed</strong>, not how much of the page you filled in.</p>${choices(s,'phase','Which describes your learning right now?')}${text(s,'nextMove','Use one piece of evidence and choose your next move','“I am … because my … test showed … . Next I will … .” If it feels too hard, write where you need help and raise your hand.')}<p class="small">New learning → try one smaller step. Consolidating → repeat independently. Treading water → choose an extension. Drowning → ask for a demonstration of the exact step.</p>${guide('learning-pitstop.png','School Learning Pitstop: new learning, consolidating, treading water and drowning')}`;
      case 'plenary': return `<p>Use <strong>your own badge</strong> to explain one important idea. Short answers are enough; you may use your support language.</p>${text(s,'explain','Why does your badge show the right thing when A is pressed?',r.editor==='micropython'?'Sentence frame: “When I press A, … appears because the button check runs … .” Your supplied loop checks the button repeatedly; MakeCode uses a registered event handler instead. Explain the response, not the whole loop.':'Sentence frame: “When I press A, … appears because … is inside the button event.” Words you might use: input, event, instruction, output. They are support—not a password to pass.')}${choices(s,'eventCheck','Imagine moving the text instruction from the Button A response into startup. What changes?')}${button('check','Show feedback','data-key="eventCheck"')}${inlineGrade(s,'eventCheck')}<p class="small">Your explanation is saved for your teacher. The app does not pretend to grade your writing.</p>`;
      case 'review': return `<p>Check what is recorded before you submit. “Needs review” is honest evidence of your next learning step—not a failed login or a locked page.</p><div class="buttons">${button('pdf','Print / save report as PDF','',true)}${button('backup','Download progress backup')}${button('menu','Return to a lesson card')}</div>${teams()}<details><summary>See the complete report, including attempts and corrections</summary>${report(s,images)}</details><p class="small">Your PDF uses the browser’s print window. Choose <strong>Save as PDF</strong> (on iPad use the print preview/share options). A backup JSON restores the lesson; it is not the PDF to submit.</p>`;
      case 'extend1': return `<p><strong>Choose this if your A response works.</strong> A visitor wants an easy “ready to help” signal as well as your initials. Give Button B a different useful output.</p><ol><li>Decide what B should communicate. Say your idea to a partner.</li><li>In the editor, add B’s response without removing startup or A.</li><li>Test startup, A and B. Make sure the two buttons have different jobs.</li></ol><details><summary>I need a starting hint</summary>${r.editor === 'blocks' ? '<p>Add another <strong>on button … pressed</strong> block, select <strong>B</strong> and put a different output inside it. Do not put the B event inside the A event.</p>' : code(s,true,true)}<p>The tick is just an example. Choose what is useful for your badge.</p></details>${text(s,'extend1Result','What job did you give B, and how did your test prove it works?','“B should … . I added … . My three tests showed … .”')}<p>When you finish, try Level 2 or Level 3. Extensions do not block the plenary.</p><div class="buttons">${button('go','Choose Level 2','data-card="extend2"')}${button('go','Choose Level 3','data-card="extend3"')}</div>`;
      case 'extend2': return `<p>A trainee’s badge shows their name <strong>immediately on restart</strong>. Pressing A only shows a heart. They wanted the opposite.</p><div class="two"><div class="block-example"><strong>Faulty startup</strong><div class="nested">Display “AB”</div></div><div class="block-example"><strong>Faulty Button A response</strong><div class="nested">Display heart</div></div></div><p>On A4 paper, draw two boxes labelled <strong>Startup</strong> and <strong>Button A</strong>. Put the corrected instruction in each. Then use the idea to explain or test a fix in a copy of your editor project.</p>${text(s,'extend2Result','Explain the bug and the correction','“The message appears too soon because … . I would move … to … . After the fix, restarting should … and pressing A should … .”')}<p class="small">No new syntax is needed. Your explanation must connect code location to when it runs.</p>`;
      case 'extend3': return `<p>Ask a partner to use your badge <strong>without you explaining the buttons first</strong>. Notice one thing that makes it easy or confusing.</p><ol><li>On A4 paper, sketch the badge and add a clear user instruction or label.</li><li>Choose one improvement: clearer text, a more meaningful icon, or a better pause/timing.</li><li>Make one change and ask the partner to test it again. Keep startup and A working.</li></ol>${text(s,'extend3Result','What did you observe, change and learn from the retest?','“My partner … . I changed … because … . In the second test … .”')}<p class="small">Evidence may be your observation and paper sketch shown to your teacher. Do not photograph the partner.</p>`;
      default: return '<p>This card is unavailable. Open the lesson menu.</p>';
    }
  }
  function card(s, images = {}, id = s.current) {
    const c = L.CARDS.find(c => c.id === id) || L.CORE[0];
    return `<h1>${e(c.title)}</h1>${support(s,c.id)}${body(s,images,c.id)}`;
  }
  function teams() { return `<section class="note good"><h3>Submit to Microsoft Teams</h3><p>Upload your completed PDF to the Microsoft Teams Assignment named <strong>Week 2 Project</strong>.</p><p>Before uploading: check your <strong>name and class</strong>, the lesson sections and evidence. Confirm the PDF saved successfully. Upload the <strong>PDF</strong>—not a screenshot or the JSON backup.</p></section>`; }
  function status(s,id) {
    const card = s.cards[id];
    if (!card || card.status === 'started') return 'Not completed';
    return card.status === 'review' ? 'Recorded — needs review' : 'Recorded — ready for teacher review';
  }
  function report(s, images = {}) {
    const r = s.responses;
    const objectives = Object.entries(L.OBJECTIVES).map(([k,v]) => `<dt>${e(k)}</dt><dd>${e(v)}</dd>`).join('');
    const sections = L.CARDS.filter(c => c.id !== 'review' && (!c.optional || Object.entries(L.FIELDS).some(([k,[id]]) => id === c.id && r[k]) || s.cards[c.id])).map(c => {
      const fields = Object.entries(L.FIELDS).filter(([, [id]]) => id === c.id).map(([k,[,label]]) => `<dt>${e(label)}</dt><dd>${r[k] ? e(L.label(k,r[k])).replace(/\n/g,'<br>') : 'Not answered'}</dd>`).join('');
      const checks = ['prediction','eventCheck'].filter(k => L.FIELDS[k][0] === c.id && r[k]).map(k => {
        const g = L.grade(k,r[k]); return `<p><strong>Automatic concept check:</strong> ${g.correct ? 'Correct' : 'Review needed'} — ${e(g.message)}</p>`;
      }).join('');
      const pics = c.id === 'evidence' ? ['code','device'].map(slot => images[slot] ? `<figure><img src="${e(images[slot].data)}" alt="${e(slot+' evidence')}"><figcaption>${e(slot === 'code' ? 'Code screenshot' : 'Device output photo')}: ${e(images[slot].caption || 'No caption')} · ${e(images[slot].at)}</figcaption></figure>` : `<p>${slot === 'code' ? 'Code image' : 'Device image'}: not supplied.</p>`).join('') : '';
      const expected = c.id === 'test' ? `<p><strong>Expected from the student’s choices:</strong> on restart: ${e(L.label('icon',r.icon) || 'not chosen')}; after A: ${e(r.message || 'not chosen')}.</p>` : '';
      return `<section class="report-section"><h2>${e(c.stage)} — ${e(c.title)}</h2><p><strong>${status(s,c.id)}</strong></p>${expected}<dl>${fields}</dl>${checks}${pics}</section>`;
    }).join('');
    const history = s.history.filter(h => h.type !== 'navigation').map(h => {
      const data = h.data && typeof h.data === 'object' ? Object.entries(h.data).map(([k,v]) => `${L.FIELDS[k]?.[1] || k}: ${typeof v === 'object' ? JSON.stringify(v) : L.label(k,v)}`).join(' | ') : String(h.data || '');
      return `<li><strong>${e(h.at)} · ${e(h.type)} · ${e(h.card)}</strong><br>${e(data)}</li>`;
    }).join('');
    return `<header><h1>Year 8 Computing · Week 2 Project</h1><h2>Smart Badge — Mission 1</h2><p><strong>${e(s.student.name)} · ${e(s.student.className)}</strong><br>Term 1, Week 2 · Export date: ${e(new Date().toLocaleDateString('en-GB'))}<br>Started: ${e(s.created)} · Last saved: ${e(s.updated)}<br>Route: ${e(L.label('device',r.device) || 'not chosen')} / ${e(L.label('editor',r.editor) || 'not chosen')} · Language support: ${e(s.language)}</p></header><section class="report-section report-objectives"><h2>Learning intentions</h2><dl>${objectives}</dl></section><section class="report-section"><h2>Completion summary</h2><ul>${L.CORE.filter(c=>c.id!=='review').map(c=>`<li>${e(c.title)}: ${status(s,c.id)}</li>`).join('')}</ul><p>Practical outcomes and explanations require teacher review. A “recorded” card is not proof of mastery. Hardware not demonstrated: ${r.physical === 'worked' ? 'student reports a successful test; verify evidence' : 'yes'}.</p></section>${sections}<section class="report-section"><h2>Attempts, submissions and improvements</h2><p>Latest answers are above. Earlier answers and submitted snapshots are retained below. Routine opening of a card is not counted as completed work.</p>${history ? `<ul>${history}</ul>` : '<p>No submitted attempts yet.</p>'}</section>${s.legacy ? `<section class="report-section"><h2>Work preserved from the previous app</h2><p>This older work is not automatically counted as completion of the new activities.</p><p>${e(JSON.stringify(s.legacy,null,2)).replace(/\n/g,'<br>')}</p></section>` : ''}`;
  }
  root.Views = { e, button, link, note, card, report, teams, status, support, feedback, setupGuide, transferGuide };
  if (typeof module !== 'undefined') module.exports = root.Views;
})(typeof globalThis !== 'undefined' ? globalThis : this);
