const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path');const base=path.resolve(__dirname,'..')+'/';
const nodes=new Map(),events={},intervals=[];const el=id=>{if(!nodes.has(id))nodes.set(id,{innerHTML:'',textContent:'',value:'',checked:true,hidden:false,dataset:{},classList:{add(){},toggle(){}},addEventListener(t,f){this[t]=f},querySelector(){return {focus(){}}},closest(){return null},focus(){}});return nodes.get(id)};
const c={window:{addEventListener(){},dispatchEvent(){}},document:{getElementById:el,querySelectorAll:()=>[],querySelector:()=>null,createElement:()=>el('created'),addEventListener(t,f,cap){(events[t]??=[]).push({f,cap})},body:{append(){}}},location:{search:''},URLSearchParams,Event,structuredClone,console,Date,Intl,indexedDB:{open(){throw Error('test')}},scrollTo(){},localStorage:{getItem:()=>null,setItem(){}},setInterval:f=>{intervals.push(f);return 1},clearInterval(){}};vm.createContext(c);for(const f of ['lesson.js','sql.js','app.js','session-plan.js'])vm.runInContext(fs.readFileSync(base+f,'utf8'),c);
(async()=>{const b=c.window.LessonClassroom;let locked=false;c.window.ClassroomMode={locked:()=>locked};assert.equal(b.info().entry,true);b.move('main2');el('name').value='Example Student';el('class').value='11T';await el('login').submit({preventDefault(){}});assert.equal(b.info().page,'main2');assert(!JSON.stringify(b.info()).includes('Example'));
locked=true;b.navigate('start');assert.equal(b.info().page,'main2');b.move('sql');assert.equal(b.info().page,'sql');locked=false;b.navigate('start');assert.equal(b.info().page,'start');b.move('fact-key');assert.equal(b.info().page,'start');assert(b.pages().every(id=>!id.startsWith('fact')));
const plan=c.window.SESSION_PLAN,clock=c.window.LessonClock;assert.equal(plan.stages.reduce((n,s)=>n+s.end-s.start,0),60);
assert.equal(clock.at(679*60).phase,'before');assert.equal(clock.at(680*60).stage.id,'read');assert.equal(clock.at(740*60).phase,'after');
for(const s of plan.stages){assert.equal(clock.at(s.start*60).stage.id,s.id);assert.equal(clock.at(s.end*60-1).remaining,1);assert.equal(clock.at(s.end*60-1).stage.id,s.id)}
assert.equal(clock.seconds(new Date('2026-09-23T03:20:00Z')),680*60);
let sec=680*60,moves=0;c.window.LessonClock={...clock,seconds:()=>sec};const old=b;c.window.LessonClassroom={...b,navigate(){moves++}};vm.runInContext(fs.readFileSync(base+'lesson-clock.js','utf8'),c);sec=730*60;intervals.at(-1)();assert.equal(moves,0);el('clock-open').onclick();assert.equal(moves,1);el('clock-follow').checked=false;el('clock-follow').onchange();el('clock-open').onclick();assert.equal(moves,1);assert.equal(el('clock-guidance').hidden,true);
for(const task of c.window.LESSON.tasks){const r=c.window.runClubSQL(task[2]);assert(r.rows.length>0)}
assert(!fs.readFileSync(base+'index.html','utf8').includes('src="teacher-presentation'));
c.window.LessonClassroom=old;vm.runInContext(fs.readFileSync(base+'teacher-presentation.js','utf8'),c);assert.equal(c.window.TeacherPresentation,undefined);
console.log('PASS: 60-minute plan, every time boundary, Malaysia time, optional clock without automatic navigation, lock/remote routing, teacher-only script gate and five SQL queries.');})();
