'use strict';
const B=(en,ms,zh)=>({en,ms,zh});
const L={
 title:B('Build a helpdesk adviser','Bina penasihat meja bantuan','编写服务台建议程序'),
 wagba:B('Build and test a Python program that takes input, calculates time and gives two different pieces of advice.','Bina dan uji atur cara Python yang menerima input, mengira masa dan memberi dua nasihat berbeza.','编写并测试 Python 程序：获取输入、计算时间，并给出两种不同的建议。'),
 knowledge:B('Recognise input(), int(), variables, constants and conditions.','Kenali input(), int(), pemboleh ubah, pemalar dan syarat.','认识 input()、int()、变量、常量和条件。'),
 skills:B('Arrange code, edit Python and run both decision paths.','Susun kod, sunting Python dan jalankan kedua-dua laluan keputusan.','排列代码、修改 Python，并运行两条判断路径。'),
 understanding:B('Explain a calculation and why a condition chooses an output.','Jelaskan pengiraan dan sebab syarat memilih sesuatu output.','解释计算，以及条件为什么选择某个输出。'),
 K:B('Knowledge','Pengetahuan','知识'),S:B('Skills','Kemahiran','技能'),U:B('Understanding','Pemahaman','理解'),
 next:B('Next page','Halaman seterusnya','下一页'),back:B('Back','Kembali','返回'),choose:B('Choose…','Pilih…','请选择…'),run:B('Run','Jalankan','运行'),stop:B('Stop','Hentikan','停止'),download:B('Download .py','Muat turun .py','下载 .py'),check:B('Check my answer','Semak jawapan saya','检查答案'),
 console:B('Console','Konsol','控制台'),ready:B('Press Run to start. Answer each question here when it appears.','Tekan Jalankan. Jawab setiap soalan di sini apabila muncul.','点击运行。问题出现时，直接在这里回答。'),
 saved:B('Saved on this browser','Disimpan dalam pelayar ini','已保存在此浏览器'),saveError:B('Saving is unavailable. Download a backup before leaving.','Tidak dapat menyimpan. Muat turun sandaran sebelum keluar.','无法保存。离开前请下载备份。'),
 independent:B('I can do this on my own','Saya boleh buat sendiri','我能独立完成'),support:B('I can do this with help','Saya boleh buat dengan bantuan','我能借助帮助完成'),need:B('I need help to start','Saya perlukan bantuan untuk mula','我需要帮助才能开始'),untried:B('I have not tried yet','Saya belum mencuba','我还没尝试'),
 new:B('New learning','Pembelajaran baharu','新学习'),consolidating:B('Consolidating','Mengukuhkan','巩固'),treading:B('Treading water','Terlalu mudah','原地踏步'),drowning:B('Drowning / need help','Buntu / perlukan bantuan','遇到困难／需要帮助'),
 pdf:B('Save as PDF','Simpan sebagai PDF','保存为 PDF'),backup:B('Save full backup','Simpan sandaran penuh','保存完整备份'),restore:B('Load backup','Muatkan sandaran','加载备份'),report:B('Readable report','Laporan boleh dibaca','可阅读报告'),
 sample:B('Worked example','Contoh lengkap','完整示例'),try:B('Your turn','Giliran anda','轮到你了'),parsons:B('Arrange the code','Susun kod','排列代码'),practice:B('Programming practice','Latihan pengaturcaraan','编程练习'),
 noEvidence:B('Not attempted yet','Belum dicuba','尚未尝试'),teacher:B('Teacher preview','Pratonton guru','教师预览'),
};
const PAGES=[
 ['read',B('Read first','Baca dahulu','先阅读'),B('What should a helpdesk solve?','Apakah yang perlu diselesaikan oleh meja bantuan?','服务台应该解决什么问题？'),'START'],
 ['starter',B('Do Now','Mula sekarang','课前练习'),B('Read. Recall. Try six checks.','Baca. Ingat. Cuba enam semakan.','先读，再回忆，尝试六个小题。'),'START'],
 ['types',B('Types of Learning','Jenis Pembelajaran','学习类型'),B('What will I get better at?','Apakah yang akan saya perbaiki?','今天我要在哪方面进步？'),'START'],
 ['reference',B('Examples & reading','Contoh & bacaan','示例与阅读'),B('Meet the building blocks.','Kenali bahagian asas.','认识程序的基本组成。'),'MAIN 1'],
 ['inputs',B('Input & variables','Input & pemboleh ubah','输入与变量'),B('Ask. Store. Use a number.','Tanya. Simpan. Gunakan nombor.','提问、存储、使用数字。'),'MAIN 1'],
 ['constants',B('Constants & variables','Pemalar & pemboleh ubah','常量与变量'),B('What stays fixed? What changes?','Apa yang tetap? Apa yang berubah?','什么保持固定？什么会改变？'),'MAIN 1'],
 ['conditions',B('Conditions','Syarat','条件'),B('Ask Python a True / False question.','Tanya Python soalan True / False.','向 Python 提一个真假问题。'),'MAIN 1'],
 ['calculations-read',B('Calculations: read first','Pengiraan: baca dahulu','计算：先阅读'),B('Follow the numbers, one line at a time.','Ikuti nombor, satu baris pada satu masa.','逐行跟随数字变化。'),'MAIN 2'],
 ['calculations',B('Calculate time','Kira masa','计算时间'),B('Turn the inputs into useful results.','Tukar input menjadi hasil berguna.','用输入计算有用的结果。'),'MAIN 2'],
 ['decisions',B('Build the full program','Bina atur cara lengkap','组成完整程序'),B('Two paths. One working adviser.','Dua laluan. Satu penasihat berfungsi.','两条路径，一个可运行的建议程序。'),'MAIN 2'],
 ['pit',B('Learning Pit Stop','Hentian Pembelajaran','学习停靠站'),B('How confident do I feel?','Sejauh manakah keyakinan saya?','我现在有多大信心？'),'REFLECT'],
 ['plenary',B('Plenary & save','Rumusan & simpan','总结与保存'),B('Recall the code. Keep your work.','Ingat semula kod. Simpan kerja.','回顾代码，保存作品。'),'REFLECT'],
 ['extension',B('Further challenge','Cabaran lanjutan','进阶挑战'),B('Can your adviser handle a busy day?','Bolehkah penasihat anda mengendalikan hari sibuk?','你的程序能处理忙碌的一天吗？'),'EXTEND']
];
const GROUPS={'START':B('Get ready','Bersedia','准备开始'),'MAIN 1':B('Main Task 1 · Building blocks','Tugasan Utama 1 · Asas','主要任务 1 · 基本组成'),'MAIN 2':B('Main Task 2 · Build & test','Tugasan Utama 2 · Bina & uji','主要任务 2 · 编写与测试'),'REFLECT':B('Reflect & save','Refleksi & simpan','反思与保存'),'EXTEND':B('Use extra time','Gunakan masa tambahan','利用剩余时间')};
const VOCAB=[
 ['input()',B('Ask the user a question. The answer is text.','Tanya pengguna soalan. Jawapannya teks.','向用户提问。回答是文本。'),'name = input("Your name: ")'],
 ['int()',B('Convert suitable text to a whole number.','Tukar teks yang sesuai kepada nombor bulat.','把合适的文本转换为整数。'),'people = int(input("People: "))'],
 ['variable',B('A name stores a value that can change.','Nama menyimpan nilai yang boleh berubah.','名称保存一个可以改变的值。'),'people_ahead = 2'],
 ['constant',B('A value we intend to keep fixed. Use CAPITALS; Python does not lock it.','Nilai yang ingin dikekalkan. Gunakan HURUF BESAR; Python tidak menguncinya.','我们打算保持固定的值。用大写名称表示，但 Python 不会锁定它。'),'MINUTES_PER_PERSON = 4'],
 ['condition',B('A comparison gives True or False.','Perbandingan menghasilkan True atau False.','比较的结果为 True 或 False。'),'print(12 <= 15)'],
 ['output',B('Show a result or advice to the user.','Papar hasil atau nasihat kepada pengguna.','向用户显示结果或建议。'),'print("Ask the helpdesk.")']
];
const CHECKS=[
 ['k1','K',B('I know input() returns text and int() makes an integer.','Saya tahu input() memberi teks dan int() menghasilkan integer.','我知道 input() 返回文本，int() 转换为整数。'),'s1','input_number'],
 ['k2','K',B('I can spot a variable and an intended constant.','Saya boleh mengenal pasti pemboleh ubah dan pemalar.','我能辨认变量和预定的常量。'),'s2','constant_edit'],
 ['s1','S',B('I can collect a number and calculate with it.','Saya boleh menerima nombor dan menggunakannya untuk mengira.','我能获取数字并用它计算。'),'s3','calculate_total'],
 ['s2','S',B('I can arrange an if/else and run both paths.','Saya boleh menyusun if/else dan menjalankan kedua-dua laluan.','我能排列 if/else，并运行两条路径。'),'s4','core'],
 ['u1','U',B('I know why the total includes Sam’s own time.','Saya tahu sebab jumlah termasuk masa Sam sendiri.','我知道总时间为什么要包括 Sam 本人的时间。'),'s5','calculate_total'],
 ['u2','U',B('I know why <= includes exactly enough time.','Saya tahu sebab <= termasuk masa yang cukup tepat.','我知道 <= 为什么包含时间刚好够用的情况。'),'s6','core']
];
const PHASES=[
 ['new',B('It is new and takes effort. I am making progress.','Ini baharu dan memerlukan usaha. Saya semakin maju.','内容是新的，需要努力，但我正在进步。')],
 ['consolidating',B('I know the idea. Practice is making me more secure.','Saya tahu idea ini. Latihan mengukuhkan saya.','我已知道这个概念，练习让我更熟练。')],
 ['treading',B('This is already easy. I need a harder version.','Ini sudah mudah. Saya perlukan versi lebih sukar.','这已经很容易，我需要更有挑战的版本。')],
 ['drowning',B('I am stuck. I need someone to show one small step.','Saya buntu. Saya perlukan tunjuk ajar satu langkah kecil.','我卡住了，需要有人示范一个小步骤。')]
];
const Q=(id,area,prompt,code,options,answer,why)=>({id,area,prompt,code,options,answer,why});
const STARTER=[
 Q('s1','K',B('Sam types 3 into input(). What does Python receive?','Sam menaip 3 dalam input(). Apakah yang diterima Python?','Sam 在 input() 中输入 3。Python 收到什么？'),'', ['"3" (str)','3 (int)','True (bool)'],0,B('input() returns text. int("3") converts that text to the integer 3.','input() memberi teks. int("3") menukar teks itu kepada integer 3.','input() 返回文本。int("3") 将它转换为整数 3。')),
 Q('s2','K',B('Which name shows the intended constant?','Nama manakah menunjukkan pemalar?','哪个名称表示预定的常量？'),'MINUTES_PER_PERSON = 4\npeople_ahead = 2',['people_ahead','MINUTES_PER_PERSON'],1,B('The model keeps 4 minutes per person. The queue length can change.','Model mengekalkan 4 minit setiap orang. Panjang baris gilir boleh berubah.','模型设定每人固定 4 分钟，排队人数可以改变。')),
 Q('s3','S',B('Which line can collect a whole number for arithmetic?','Baris manakah menerima nombor bulat untuk pengiraan?','哪一行能获取用于计算的整数？'),'', ['people = input("People: ")','people = int(input("People: "))'],1,B('int() makes the input usable as an integer.','int() menjadikan input boleh digunakan sebagai integer.','int() 把输入转换为可以计算的整数。')),
 Q('s4','S',B('Which order makes an if/else decision?','Susunan manakah membentuk keputusan if/else?','哪个顺序组成 if/else 判断？'),'', [B('if → indented True output → else → indented False output','if → output True berinden → else → output False berinden','if → 缩进的 True 输出 → else → 缩进的 False 输出'),B('else → both outputs → if','else → kedua-dua output → if','else → 两个输出 → if')],0,B('Each output belongs inside its branch. Only one branch runs.','Setiap output berada dalam cabangnya. Hanya satu cabang berjalan.','每条输出放进所属分支。每次只执行一条路径。')),
 Q('s5','U',B('Two people wait ahead of Sam. Each person needs 4 minutes. Why is the total 12, not 8?','Dua orang di hadapan Sam. Setiap orang perlu 4 minit. Mengapa jumlahnya 12, bukan 8?','Sam 前面有两人，每人需要 4 分钟。为什么总时间是 12，而不是 8？'),'', [B('Sam also needs 4 minutes of help.','Sam juga memerlukan 4 minit bantuan.','Sam 本人也需要 4 分钟。'),B('Python always adds 4.','Python sentiasa menambah 4.','Python 总会加 4。')],0,B('8 minutes waiting + 4 minutes for Sam = 12 minutes altogether.','8 minit menunggu + 4 minit untuk Sam = jumlah 12 minit.','等待 8 分钟 + Sam 的 4 分钟 = 总共 12 分钟。')),
 Q('s6','U',B('The total and available time are both 12. What does this condition give?','Jumlah dan masa tersedia kedua-duanya 12. Apakah hasil syarat ini?','总时间和可用时间都是 12。这个条件的结果是什么？'),'print(12 <= 12)',['True','False'],0,B('<= includes equal. Exactly 12 minutes meets this classroom rule; real help may take longer.','<= termasuk sama. Tepat 12 minit memenuhi peraturan kelas ini; bantuan sebenar mungkin lebih lama.','<= 包含等于。12 分钟符合课堂规则，但实际帮助可能需要更久。'))
];
const PARSONS={};
function puzzle(id,page,title,instruction,blocks,hint){PARSONS[id]={id,page,title,instruction,blocks,hint,start:blocks.map((_,i)=>(i+blocks.length-1)%blocks.length)};}
puzzle('p_input1','inputs',B('1 · Ask for a device','1 · Tanya peranti','1 · 询问设备'),B('Ask first. Then print the answer.','Tanya dahulu. Kemudian cetak jawapan.','先提问，再显示回答。'),['device = input("Device: ")','print("Bring your", device)'],B('device must have a value before print uses it.','device mesti mempunyai nilai sebelum print menggunakannya.','print 使用 device 之前，device 必须先有值。'));
puzzle('p_input2','inputs',B('2 · Read a number','2 · Baca nombor','2 · 读取数字'),B('Read text → convert it → print the number.','Baca teks → tukar → cetak nombor.','读取文本 → 转换 → 显示数字。'),['answer = input("People ahead: ")','people_ahead = int(answer)','print(people_ahead)'],B('int(answer) needs answer first. Print the converted number last.','int(answer) memerlukan answer dahulu. Cetak nombor yang ditukar akhir sekali.','先获取 answer，才能使用 int(answer)。最后输出转换后的数字。'));
puzzle('p_constant1','constants',B('1 · Use a fixed value','1 · Guna nilai tetap','1 · 使用固定值'),B('Set the constant → copy it into a variable → print.','Tetapkan pemalar → salin ke pemboleh ubah → cetak.','设置常量 → 复制到变量 → 输出。'),['MINUTES_PER_PERSON = 4','sam_minutes = MINUTES_PER_PERSON','print("Sam needs", sam_minutes, "minutes")'],B('Define MINUTES_PER_PERSON before using it.','Takrifkan MINUTES_PER_PERSON sebelum menggunakannya.','先定义 MINUTES_PER_PERSON，再使用它。'));
puzzle('p_constant2','constants',B('2 · A value changes','2 · Nilai berubah','2 · 数值改变'),B('Start the count at 2. One person joins. Print the new count.','Mulakan kiraan pada 2. Seorang menyertai. Cetak kiraan baharu.','人数从 2 开始。又来一人。输出新人数。'),['people_ahead = 2','people_ahead = people_ahead + 1','print(people_ahead)'],B('Store the starting value before adding 1. The final value is 3.','Simpan nilai awal sebelum menambah 1. Nilai akhir ialah 3.','先存储初始值，再加 1。最终值是 3。'));
puzzle('p_condition1','conditions',B('1 · Compare two times','1 · Banding dua masa','1 · 比较两个时间'),B('Store the total. Then store the available time. Print the comparison last.','Simpan jumlah, kemudian masa tersedia. Cetak perbandingan akhir sekali.','先存储总时间，再存储可用时间，最后输出比较结果。'),['total_minutes = 12','minutes_available = 15','print(total_minutes <= minutes_available)'],B('Both values must exist before the comparison. 12 <= 15 is True.','Kedua-dua nilai mesti wujud sebelum perbandingan. 12 <= 15 ialah True.','比较前需要两个值。12 <= 15 为 True。'));
puzzle('p_condition2','conditions',B('2 · Store a Boolean','2 · Simpan Boolean','2 · 保存布尔值'),B('Store the number. Compare it with 0. Print the Boolean.','Simpan nombor. Bandingkan dengan 0. Cetak Boolean.','存储数字，与 0 比较，输出布尔值。'),['people_ahead = 0','queue_empty = people_ahead == 0','print(queue_empty)'],B('== compares two values. The result True is stored in queue_empty.','== membandingkan dua nilai. Hasil True disimpan dalam queue_empty.','== 比较两个值。结果 True 保存在 queue_empty 中。'));
puzzle('p_calc1','calculations',B('1 · Calculate waiting time','1 · Kira masa menunggu','1 · 计算等待时间'),B('Set the constant and read the queue size. Then calculate and print.','Tetapkan pemalar dan baca saiz baris gilir. Kemudian kira dan cetak.','设置常量并读取人数，然后计算并输出。'),['MINUTES_PER_PERSON = 4\npeople_ahead = int(input("People ahead: "))','waiting_minutes = people_ahead * MINUTES_PER_PERSON','print("Estimated wait:", waiting_minutes)'],B('Use * to multiply the number of people by the time for each person.','Gunakan * untuk mendarab bilangan orang dengan masa setiap orang.','用 * 将人数乘以每人的时间。'));
puzzle('p_calc2','calculations',B('2 · Include Sam’s time','2 · Sertakan masa Sam','2 · 加上 Sam 的时间'),B('Set the starting values → calculate the wait → add Sam’s time → print.','Tetapkan nilai → kira masa menunggu → tambah masa Sam → cetak.','设置数值 → 计算等待 → 加上 Sam 的时间 → 输出。'),['MINUTES_PER_PERSON = 4\npeople_ahead = 3','waiting_minutes = people_ahead * MINUTES_PER_PERSON','total_minutes = waiting_minutes + MINUTES_PER_PERSON','print("Estimated total:", total_minutes)'],B('3 × 4 = 12 minutes waiting. Add Sam’s 4 minutes: total 16.','3 × 4 = 12 minit menunggu. Tambah 4 minit Sam: jumlah 16.','3 × 4 = 等待 12 分钟，再加上 Sam 的 4 分钟，总共 16。'));
puzzle('p_if1','decisions',B('1 · Choose one advice path','1 · Pilih satu laluan nasihat','1 · 选择一条建议路径'),B('Arrange if → True advice → else → False advice. The times already exist.','Susun if → nasihat True → else → nasihat False. Masa sudah diberi.','排列 if → True 建议 → else → False 建议。时间变量已有值。'),['if total_minutes <= minutes_available:','    print("Ask the helpdesk if they can help now.")','else:','    print("Arrange another time.")'],B('Keep four spaces before each print. if and else start at the same edge.','Kekalkan empat ruang sebelum print. if dan else bermula di tepi yang sama.','每个 print 前保留四个空格。if 和 else 左侧对齐。'));
puzzle('p_if2','decisions',B('2 · Ask for a useful detail','2 · Tanya butiran berguna','2 · 询问有用的信息'),B('Check the stored device name. Give one instruction for a laptop and another for other devices.','Semak nama peranti disimpan. Beri arahan untuk komputer riba dan arahan lain untuk peranti lain.','检查已保存的设备名称。给笔记本电脑一种指示，给其他设备另一种指示。'),['if device == "laptop":','    print("Bring the laptop and its charger.")','else:','    print("Tell the helpdesk which device you use.")'],B('== tests whether the text matches exactly. This example expects lowercase laptop.','== menyemak padanan teks tepat. Contoh ini menjangka laptop dalam huruf kecil.','== 检查文本是否完全相同。此例要求输入小写 laptop。'));
const PROGRAMS={};
function program(id,page,title,task,starter,guided,solution,tests){PROGRAMS[id]={id,page,title,task,starter,guided,solution,tests};}
program('input_text','inputs',B('1 · Welcome a user','1 · Sambut pengguna','1 · 欢迎用户'),B('Ask for a first name. Print Hello followed by the name. Use a fictional name.','Minta nama pertama. Cetak Hello diikuti nama. Gunakan nama rekaan.','询问名字，再输出 Hello 和名字。请使用虚构名字。'),'# Ask for a name, then print a greeting.\n','name = input("First name: ")\nprint("Hello", ___)\n','name = input("First name: ")\nprint("Hello", name)\n',[[['Sam'],'Hello Sam']]);
program('input_number','inputs',B('2 · Read a queue number','2 · Baca nombor baris gilir','2 · 读取排队人数'),B('Ask how many people are ahead. Convert the answer with int(). Print the number plus 1 to include Sam.','Tanya bilangan orang di hadapan. Tukar dengan int(). Cetak nombor tambah 1 untuk menyertakan Sam.','询问前面有多少人，用 int() 转换，再输出人数加 1，包括 Sam。'),'people_ahead = int(input("People ahead: "))\n# Print the number including Sam.\n','people_ahead = int(input("People ahead: "))\nprint(people_ahead + ___)\n','people_ahead = int(input("People ahead: "))\nprint(people_ahead + 1)\n',[[['2'],'3'],[['0'],'1']]);
program('input_pair','inputs',B('3 · Collect both inputs','3 · Terima kedua-dua input','3 · 获取两个输入'),B('Ask for people_ahead, then minutes_available. Convert both to integers. Print each value with a label.','Tanya people_ahead, kemudian minutes_available. Tukar kedua-duanya kepada integer. Cetak setiap nilai dengan label.','先询问 people_ahead，再询问 minutes_available。都转换成整数，分别加标签输出。'),'# Ask for two whole numbers.\n# Print both with clear labels.\n','people_ahead = int(input("People ahead: "))\nminutes_available = int(input("Minutes available: "))\nprint("People:", people_ahead)\nprint("Available:", ___)\n','people_ahead = int(input("People ahead: "))\nminutes_available = int(input("Minutes available: "))\nprint("People:", people_ahead)\nprint("Available:", minutes_available)\n',[[['3','20'],'People: 3\nAvailable: 20']]);
program('constant_edit','constants',B('1 · One fixed value, one changing count','1 · Satu nilai tetap, satu kiraan berubah','1 · 一个固定值，一个变化的计数'),B('Keep MINUTES_PER_PERSON at 4. Ask for people_ahead. Increase people_ahead by 1. Print the new count and the unchanged constant.','Kekalkan MINUTES_PER_PERSON pada 4. Tanya people_ahead. Tambah 1 kepada people_ahead. Cetak kiraan baharu dan pemalar yang tidak berubah.','保持 MINUTES_PER_PERSON 为 4。询问 people_ahead，然后加 1。输出新人数和未改变的常量。'),'MINUTES_PER_PERSON = 4\n# Read and increase people_ahead.\n# Print the count, then the constant.\n','MINUTES_PER_PERSON = 4\npeople_ahead = int(input("People ahead: "))\npeople_ahead = people_ahead + ___\nprint(people_ahead)\nprint(MINUTES_PER_PERSON)\n','MINUTES_PER_PERSON = 4\npeople_ahead = int(input("People ahead: "))\npeople_ahead = people_ahead + 1\nprint(people_ahead)\nprint(MINUTES_PER_PERSON)\n',[[['2'],'3\n4'],[['5'],'6\n4']]);
program('condition_check','conditions',B('1 · Print the condition’s result','1 · Cetak hasil syarat','1 · 输出条件结果'),B('Read total_minutes and minutes_available. Print whether the total is less than or equal to the available time. Use <=.','Baca total_minutes dan minutes_available. Cetak sama ada jumlah kurang daripada atau sama dengan masa tersedia. Gunakan <=.','读取 total_minutes 和 minutes_available。输出总时间是否小于或等于可用时间。使用 <=。'),'total_minutes = int(input("Total minutes: "))\nminutes_available = int(input("Minutes available: "))\n# Print the comparison.\n','total_minutes = int(input("Total minutes: "))\nminutes_available = int(input("Minutes available: "))\nprint(total_minutes ___ minutes_available)\n','total_minutes = int(input("Total minutes: "))\nminutes_available = int(input("Minutes available: "))\nprint(total_minutes <= minutes_available)\n',[[['12','15'],'True'],[['20','15'],'False'],[['12','12'],'True']]);
program('calculate_wait','calculations',B('1 · Calculate the wait','1 · Kira masa menunggu','1 · 计算等待'),B('Read people_ahead. Multiply it by MINUTES_PER_PERSON. Print Estimated wait: followed by the number and minutes.','Baca people_ahead. Darab dengan MINUTES_PER_PERSON. Cetak Estimated wait: diikuti nombor dan minutes.','读取 people_ahead，乘以 MINUTES_PER_PERSON。输出 Estimated wait:、数字和 minutes。'),'MINUTES_PER_PERSON = 4\npeople_ahead = int(input("People ahead: "))\n# Calculate and print waiting_minutes.\n','MINUTES_PER_PERSON = 4\npeople_ahead = int(input("People ahead: "))\nwaiting_minutes = people_ahead ___ MINUTES_PER_PERSON\nprint("Estimated wait:", waiting_minutes, "minutes")\n','MINUTES_PER_PERSON = 4\npeople_ahead = int(input("People ahead: "))\nwaiting_minutes = people_ahead * MINUTES_PER_PERSON\nprint("Estimated wait:", waiting_minutes, "minutes")\n',[[['3'],'Estimated wait: 12 minutes'],[['0'],'Estimated wait: 0 minutes']]);
program('calculate_total','calculations',B('2 · Add Sam’s help time','2 · Tambah masa bantuan Sam','2 · 加上 Sam 的服务时间'),B('Calculate the wait, then add 4 minutes for Sam. Print the total with a label and minutes.','Kira masa menunggu, kemudian tambah 4 minit untuk Sam. Cetak jumlah dengan label dan minutes.','计算等待时间，再加上 Sam 的 4 分钟。输出总时间，带标签和 minutes。'),'MINUTES_PER_PERSON = 4\npeople_ahead = int(input("People ahead: "))\nwaiting_minutes = people_ahead * MINUTES_PER_PERSON\n# Calculate and print total_minutes.\n','MINUTES_PER_PERSON = 4\npeople_ahead = int(input("People ahead: "))\nwaiting_minutes = people_ahead * MINUTES_PER_PERSON\ntotal_minutes = waiting_minutes ___ MINUTES_PER_PERSON\nprint("Estimated total:", total_minutes, "minutes")\n','MINUTES_PER_PERSON = 4\npeople_ahead = int(input("People ahead: "))\nwaiting_minutes = people_ahead * MINUTES_PER_PERSON\ntotal_minutes = waiting_minutes + MINUTES_PER_PERSON\nprint("Estimated total:", total_minutes, "minutes")\n',[[['3'],'Estimated total: 16 minutes'],[['0'],'Estimated total: 4 minutes']]);
program('calculate_spare','calculations',B('3 · Find the minutes left','3 · Cari baki minit','3 · 求剩余分钟'),B('Read the total time, then the available time. Subtract total from available. A negative result means there is not enough time. Print Minutes left: and the result.','Baca jumlah masa, kemudian masa tersedia. Tolak jumlah daripada masa tersedia. Hasil negatif bermakna masa tidak cukup. Cetak Minutes left: dan hasil.','读取总时间，再读取可用时间。用可用时间减总时间。负数表示时间不足。输出 Minutes left: 和结果。'),'total_minutes = int(input("Total minutes: "))\nminutes_available = int(input("Minutes available: "))\n# Calculate and print spare_minutes.\n','total_minutes = int(input("Total minutes: "))\nminutes_available = int(input("Minutes available: "))\nspare_minutes = minutes_available ___ total_minutes\nprint("Minutes left:", spare_minutes)\n','total_minutes = int(input("Total minutes: "))\nminutes_available = int(input("Minutes available: "))\nspare_minutes = minutes_available - total_minutes\nprint("Minutes left:", spare_minutes)\n',[[['12','15'],'Minutes left: 3'],[['20','15'],'Minutes left: -5']]);
const FULL='MINUTES_PER_PERSON = 4\npeople_ahead = int(input("People ahead: "))\nminutes_available = int(input("Minutes available: "))\nwaiting_minutes = people_ahead * MINUTES_PER_PERSON\ntotal_minutes = waiting_minutes + MINUTES_PER_PERSON\nprint("Estimated wait:", waiting_minutes, "minutes")\nprint("Estimated total:", total_minutes, "minutes")\nif total_minutes <= minutes_available:\n    print("Ask the helpdesk if they can help now.")\nelse:\n    print("Arrange another time.")\n';
program('core','decisions',B('Your complete helpdesk adviser','Penasihat meja bantuan lengkap anda','你的完整服务台建议程序'),B('Join the ideas: ask for two numbers, calculate waiting and total time, then use if/else to choose advice. Test all three cases.','Gabungkan idea: tanya dua nombor, kira masa menunggu dan jumlah, kemudian guna if/else untuk memilih nasihat. Uji ketiga-tiga kes.','结合所学：获取两个数字，计算等待与总时间，然后用 if/else 选择建议。测试三种情况。'),'MINUTES_PER_PERSON = 4\n# Read people_ahead and minutes_available as integers.\n# Calculate and print waiting_minutes and total_minutes.\n# Add if/else and the two advice outputs.\n',FULL.replace('people_ahead * MINUTES_PER_PERSON','people_ahead ___ MINUTES_PER_PERSON').replace('waiting_minutes + MINUTES_PER_PERSON','waiting_minutes ___ MINUTES_PER_PERSON').replace('total_minutes <= minutes_available','total_minutes ___ minutes_available'),FULL,[[['2','15'],'Estimated wait: 8 minutes\nEstimated total: 12 minutes\nAsk the helpdesk if they can help now.'],[['4','15'],'Estimated wait: 16 minutes\nEstimated total: 20 minutes\nArrange another time.'],[['2','12'],'Estimated wait: 8 minutes\nEstimated total: 12 minutes\nAsk the helpdesk if they can help now.']]);
program('extension','extension',B('Busy-day challenge','Cabaran hari sibuk','忙碌日挑战'),B('Add a 2-minute buffer to the total. Reject a negative queue length or a negative available time with “Enter zero or a positive number.” Otherwise calculate and choose advice.','Tambah penimbal 2 minit kepada jumlah. Tolak bilangan orang atau masa tersedia yang negatif dengan “Enter zero or a positive number.” Jika tidak, kira dan pilih nasihat.','给总时间加 2 分钟缓冲。人数或可用时间为负时输出“Enter zero or a positive number.”。否则计算并给出建议。'),'# Start with your full program using the copy button.\n', 'MINUTES_PER_PERSON = 4\nBUFFER_MINUTES = 2\npeople_ahead = int(input("People ahead: "))\nminutes_available = int(input("Minutes available: "))\nif people_ahead < 0 or minutes_available < 0:\n    print("Enter zero or a positive number.")\nelse:\n    total_minutes = (people_ahead + 1) * MINUTES_PER_PERSON + ___\n    print("Estimated total:", total_minutes, "minutes")\n    if total_minutes <= minutes_available:\n        print("Ask the helpdesk if they can help now.")\n    else:\n        print("Arrange another time.")\n', 'MINUTES_PER_PERSON = 4\nBUFFER_MINUTES = 2\npeople_ahead = int(input("People ahead: "))\nminutes_available = int(input("Minutes available: "))\nif people_ahead < 0 or minutes_available < 0:\n    print("Enter zero or a positive number.")\nelse:\n    total_minutes = (people_ahead + 1) * MINUTES_PER_PERSON + BUFFER_MINUTES\n    print("Estimated total:", total_minutes, "minutes")\n    if total_minutes <= minutes_available:\n        print("Ask the helpdesk if they can help now.")\n    else:\n        print("Arrange another time.")\n',[[['2','12'],'Estimated total: 14 minutes\nArrange another time.'],[['2','15'],'Estimated total: 14 minutes\nAsk the helpdesk if they can help now.'],[['-1','15'],'Enter zero or a positive number.'],[['2','-1'],'Enter zero or a positive number.']]);
const PLENARY=[
 Q('e1','K',B('What does input() return before conversion?','Apakah yang dikembalikan input() sebelum penukaran?','input() 转换前返回什么？'),'', ['str','int','bool'],0,STARTER[0].why),
 Q('e2','K',B('What does int("5") produce?','Apakah hasil int("5")?','int("5") 得到什么？'),'', ['"5"','5','True'],1,B('It converts suitable text to the integer 5.','Ia menukar teks sesuai kepada integer 5.','它把合适的文本转换为整数 5。')),
 Q('e3','U',B('Use the full code on the left. What happens for 1 person ahead and 8 minutes available?','Gunakan kod lengkap di kiri. Apakah berlaku bagi 1 orang di hadapan dan 8 minit tersedia?','看左侧完整代码。前面 1 人，可用 8 分钟，会怎样？'),'', [B('Total 8; ask the helpdesk about help now.','Jumlah 8; tanya meja bantuan untuk bantuan sekarang.','总时间 8；询问现在能否帮忙。'),B('Total 4; arrange another time.','Jumlah 4; aturkan masa lain.','总时间 4；另约时间。')],0,B('(1 × 4) + 4 = 8. 8 <= 8 is True.','(1 × 4) + 4 = 8. 8 <= 8 ialah True.','(1 × 4) + 4 = 8。8 <= 8 为 True。')),
 Q('e4','K',B('Which statement describes MINUTES_PER_PERSON and people_ahead?','Pernyataan manakah menerangkan MINUTES_PER_PERSON dan people_ahead?','哪句话描述 MINUTES_PER_PERSON 和 people_ahead？'),'', [B('Both must stay fixed.','Kedua-duanya mesti tetap.','两者都必须固定。'),B('The first is an intended constant; the second can change with input.','Yang pertama pemalar; yang kedua boleh berubah mengikut input.','前者是预定常量，后者随输入改变。')],1,STARTER[1].why)
];
const GUIDED_TASKS={
 input_text:B('Replace ___. Click Run. Type Sam when asked. Look for Hello Sam.','Ganti ___. Klik Jalankan. Taip Sam apabila ditanya. Cari Hello Sam.','替换 ___，点击运行。提问时输入 Sam，查看 Hello Sam。'),
 input_number:B('Fill one gap. Run. Type 2. The program should print 3: two people and Sam.','Isi satu tempat kosong. Jalankan. Taip 2. Atur cara patut mencetak 3: dua orang dan Sam.','填一个空，运行，输入 2。程序应显示 3：前面两人加上 Sam。'),
 input_pair:B('Fill the name gap. Run. Answer the two questions: 3, then 20.','Isi nama yang hilang. Jalankan. Jawab dua soalan: 3, kemudian 20.','填入缺少的名称，运行。依次回答两个问题：3，然后 20。'),
 constant_edit:B('Add one person. Run with 2. Look for 3 people and the fixed time 4.','Tambah seorang. Jalankan dengan 2. Cari 3 orang dan masa tetap 4.','加一个人。运行并输入 2，查看人数 3 和固定时间 4。'),
 condition_check:B('Put <= in the gap. Run with 12 and 15. Look for True. Then try the other cases.','Letak <= dalam ruang kosong. Jalankan dengan 12 dan 15. Cari True. Kemudian cuba kes lain.','空白处填 <=。运行并输入 12 和 15，查看 True，再尝试其他情况。'),
 calculate_wait:B('Choose the multiply symbol. Run with 3 people. Look for 12 minutes waiting.','Pilih simbol darab. Jalankan dengan 3 orang. Cari masa menunggu 12 minit.','选择乘号。运行并输入 3 人，查看等待 12 分钟。'),
 calculate_total:B('Choose the add symbol. Add Sam’s 4 minutes. Run with 3 people. Look for total 16.','Pilih simbol tambah. Tambah 4 minit Sam. Jalankan dengan 3 orang. Cari jumlah 16.','选择加号，加上 Sam 的 4 分钟。运行并输入 3 人，查看总时间 16。'),
 calculate_spare:B('Choose the subtract symbol. Run with 12, then 15. Look for 3 minutes left.','Pilih simbol tolak. Jalankan dengan 12, kemudian 15. Cari baki 3 minit.','选择减号。运行并先输入 12，再输入 15。查看剩余 3 分钟。'),
 core:B('Fill three gaps: multiply, add, compare. Run with 2, then 15. Read the advice. Try B and C next.','Isi tiga ruang: darab, tambah, banding. Jalankan dengan 2, kemudian 15. Baca nasihat. Cuba B dan C seterusnya.','填三个空：乘、加、比较。运行并先输入 2，再输入 15，阅读建议。接着尝试 B 和 C。'),
 extension:B('Add the buffer name in the gap. Run with 2 and 12. Look for total 14. Then try a negative number.','Tambah nama penimbal dalam ruang kosong. Jalankan dengan 2 dan 12. Cari jumlah 14. Kemudian cuba nombor negatif.','空白处填缓冲常量名称。输入 2 和 12 运行，查看总时间 14。再试一个负数。')
};

const PIT_TOPICS={
 k1:B('input() and whole numbers','input() dan nombor bulat','input() 与整数'),
 k2:B('Variables and constants','Pemboleh ubah dan pemalar','变量与常量'),
 s1:B('Reading numbers and calculating time','Membaca nombor dan mengira masa','读取数字与计算时间'),
 s2:B('Writing and testing both if/else paths','Menulis dan menguji kedua-dua laluan if/else','编写并测试两条 if/else 路径'),
 u1:B('Why the total includes Sam’s help time','Sebab jumlah termasuk masa bantuan Sam','总时间为什么包括 Sam 的服务时间'),
 u2:B('Why <= includes exactly enough time','Sebab <= termasuk masa yang cukup tepat','<= 为什么包括时间刚好够用的情况')
};
