'use strict';
const B=(en,ms,zh)=>({en,ms,zh});
const C={
 title:B('Build a helpdesk adviser','Bina penasihat meja bantuan','编写服务台建议程序'),
 subtitle:B('Your first working prototype','Prototaip pertama yang berfungsi','你的第一个可运行原型'),
 wagba:B('Turn a helpdesk plan into Python: collect input, calculate useful values, choose advice, then test and explain both paths.','Tukarkan rancangan meja bantuan kepada Python: kumpul input, kira nilai berguna, pilih nasihat, kemudian uji dan jelaskan kedua-dua laluan.','将服务台计划变成 Python 程序：获取输入、计算有用的数值、选择建议，然后测试并解释两条路径。'),
 knowledge:B('Know what input(), int(), variables, constants and conditions mean.','Ketahui maksud input(), int(), pemboleh ubah, pemalar dan syarat.','知道 input()、int()、变量、常量和条件的含义。'),
 skills:B('Collect two numbers, calculate time, write if/else and test both advice paths.','Kumpul dua nombor, kira masa, tulis if/else dan uji kedua-dua laluan nasihat.','获取两个数字、计算时间、编写 if/else，并测试两条建议路径。'),
 understanding:B('Explain why the type, calculation and decision fit Sam’s problem—and why the time is only an estimate.','Jelaskan mengapa jenis data, pengiraan dan keputusan sesuai dengan masalah Sam, serta mengapa masa itu hanya anggaran.','解释数据类型、计算和判断为什么适合 Sam 的问题，以及为什么时间只是估计。'),
 brief:B('Sam needs help signing in before the next lesson. There are people ahead at the school IT helpdesk. Your program will estimate the time and help Sam choose what to do next.','Sam memerlukan bantuan log masuk sebelum pelajaran seterusnya. Ada orang di hadapannya di meja bantuan IT sekolah. Atur cara anda akan menganggarkan masa dan membantu Sam memilih tindakan seterusnya.','Sam 需要在下一节课前获得登录帮助。学校 IT 服务台前有人排队。你的程序将估算时间，帮助 Sam 决定下一步。'),
 assumption:B('Our classroom model allows 4 minutes for each person, including Sam. This is an invented estimate, not a school rule. Real help may take longer. Never ask for a password.','Model kelas memperuntukkan 4 minit bagi setiap orang, termasuk Sam. Ini anggaran rekaan, bukan peraturan sekolah. Bantuan sebenar mungkin mengambil masa lebih lama. Jangan minta kata laluan.','课堂模型假设每人需要 4 分钟，包括 Sam。这是练习用的估计，并非学校规定。实际帮助可能需要更久。不要索取密码。'),
 finish:B('A working program, three recorded tests and an explanation of your choices.','Atur cara yang berfungsi, tiga ujian direkodkan dan penjelasan pilihan anda.','一个可运行的程序、三次测试记录，以及对设计选择的解释。'),
 names:B('Name your values clearly','Namakan nilai dengan jelas','为数值取清晰的名称'),
 estimate:B('Estimate first. Explain the advice.','Anggar dahulu. Jelaskan nasihat.','先估算，再解释建议。'),
 nav:[B('Read first','Baca dahulu','先阅读'),B('Do Now','Mula sekarang','课前练习'),B('Types of Learning','Jenis Pembelajaran','学习类型'),B('Main Task 1','Tugasan Utama 1','主要任务 1'),B('Main Task 2','Tugasan Utama 2','主要任务 2'),B('Further Challenges','Cabaran Lanjutan','进阶挑战'),B('Learning Pit Stop','Hentian Pembelajaran','学习停靠站'),B('Plenary & hand in','Rumusan & hantar','总结与提交')],
 minutes:['5','5','3','13','22','5','3','4'],
 pageTitles:[B('Meet Sam. See what you will build.','Kenali Sam. Lihat hasil yang akan dibina.','认识 Sam，了解你将制作什么。'),B('What can you already explain?','Apakah yang sudah boleh anda jelaskan?','你已经能解释什么？'),B('Choose a useful focus for today.','Pilih fokus berguna untuk hari ini.','选择今天值得改进的重点。'),B('Collect input. Calculate the time.','Kumpul input. Kira masa.','获取输入，计算时间。'),B('Choose advice. Test both paths.','Pilih nasihat. Uji kedua-dua laluan.','选择建议，测试两条路径。'),B('Make your program more useful.','Jadikan atur cara lebih berguna.','让你的程序更实用。'),B('What does your work show now?','Apakah yang ditunjukkan oleh kerja anda kini?','现在的作品说明了什么？'),B('Explain your learning. Save your work.','Jelaskan pembelajaran. Simpan kerja anda.','解释所学，保存作品。')]
};
const UI={
 name:B('Full name','Nama penuh','姓名'),className:B('Class','Kelas','班级'),language:B('Reading language','Bahasa bacaan','阅读语言'),
 begin:B('Start the lesson','Mulakan pelajaran','开始学习'),resume:B('Resume my work','Sambung kerja saya','继续学习'),welcome:B('Welcome page','Halaman alu-aluan','欢迎页'),
 previous:B('Previous','Sebelumnya','上一步'),next:B('Next','Seterusnya','下一步'),choose:B('Choose…','Pilih…','请选择…'),
 knowledge:B('Knowledge','Pengetahuan','知识'),skills:B('Skills','Kemahiran','技能'),understanding:B('Understanding','Pemahaman','理解'),
 saved:B('Saved on this browser','Disimpan dalam pelayar ini','已保存在此浏览器'),saveError:B('Browser storage unavailable. Download a backup before leaving.','Storan pelayar tidak tersedia. Muat turun sandaran sebelum keluar.','浏览器存储不可用。离开前请下载备份。'),
 run:B('Run Python','Jalankan Python','运行 Python'),stop:B('Stop','Hentikan','停止'),download:B('Download .py','Muat turun .py','下载 .py'),
 editor:B('Python editor','Editor Python','Python 编辑器'),console:B('Console & input','Konsol & input','控制台与输入'),send:B('Send input','Hantar input','提交输入'),
 ready:B('Ready to run','Sedia dijalankan','可以运行'),running:B('Running','Sedang berjalan','正在运行'),waiting:B('Waiting for your input','Menunggu input anda','等待你的输入'),done:B('Finished','Selesai','运行完成'),error:B('Needs a correction','Perlu pembetulan','需要修改'),stopped:B('Stopped','Dihentikan','已停止'),timeout:B('Time limit reached','Had masa dicapai','达到时间限制'),
 emptyConsole:B('Run your code. Each input() question will appear here. Type a response and press Enter.','Jalankan kod. Setiap soalan input() akan muncul di sini. Taip jawapan dan tekan Enter.','运行代码。每个 input() 问题会出现在这里。输入回答并按 Enter。'),
 stale:B('Code changed since this run. Run again to test this version.','Kod berubah selepas larian ini. Jalankan semula untuk menguji versi ini.','代码在此次运行后已更改。请重新运行以测试当前版本。'),
 history:B('Recent runs and code used','Larian terkini dan kod yang digunakan','最近的运行及所用代码'),
 check:B('Check my answer','Semak jawapan saya','检查答案'),model:B('Compare with an explanation','Bandingkan dengan penjelasan','对照解释'),
 prior:B('Demonstrated independently','Ditunjukkan secara berdikari','已独立展示'),support:B('Demonstrated with an example or reminder','Ditunjukkan dengan contoh atau peringatan','借助示例或提示展示'),gap:B('Not yet demonstrated','Belum dapat ditunjukkan','尚不能展示'),unattempted:B('Not attempted','Belum dicuba','尚未尝试'),
 new:B('New learning','Pembelajaran baharu','新学习'),consolidating:B('Consolidating','Mengukuhkan','巩固'),treading:B('Treading water','Terlalu mudah','原地踏步'),drowning:B('Drowning / need help','Buntu / perlukan bantuan','遇到困难／需要帮助'),
 current:B('What can I demonstrate now?','Apakah yang boleh saya tunjukkan sekarang?','现在我能展示什么？'),phase:B('How am I experiencing this learning?','Bagaimanakah pengalaman pembelajaran ini?','我在这个方面的学习体验如何？'),
 evidence:B('Point to an answer, code line or test that supports your judgement.','Nyatakan jawapan, baris kod atau ujian yang menyokong pertimbangan anda.','指出支持判断的答案、代码行或测试。'),
 focus:B('My focus','Fokus saya','我的重点'),action:B('My next action and the evidence behind it','Tindakan seterusnya dan bukti yang menyokongnya','我的下一步行动及依据'),
 prediction:B('My prediction before running','Ramalan sebelum menjalankan','运行前的预测'),actual:B('Recorded run','Larian direkodkan','已记录的运行'),attach:B('Record matching run','Rekod larian sepadan','记录匹配的运行'),
 noRun:B('No matching completed run yet. Run the core program with these inputs.','Belum ada larian selesai yang sepadan. Jalankan atur cara utama dengan input ini.','尚无匹配的完整运行。请使用这些输入运行主程序。'),
 testExplain:B('Do the results match? Explain a correction or why your code meets the rule.','Adakah hasil sepadan? Jelaskan pembetulan atau mengapa kod memenuhi peraturan.','结果是否符合预测？解释修改内容，或说明代码为什么符合规则。'),
 savePDF:B('Save my work as PDF','Simpan kerja sebagai PDF','将作品保存为 PDF'),backup:B('Full backup (.json)','Sandaran penuh (.json)','完整备份（.json）'),readable:B('Readable report (.html)','Laporan boleh dibaca (.html)','可阅读报告（.html）'),restore:B('Restore a backup','Pulihkan sandaran','恢复备份'),
 input:B('Input','Input','输入'),output:B('Output','Output','输出'),process:B('Process','Proses','处理'),step:B('Step','Langkah','步骤'),line:B('Line','Baris','行'),value:B('Value','Nilai','数值'),meaning:B('What it means','Maksudnya','含义'),
 noEvidence:B('Not recorded yet','Belum direkodkan','尚未记录'),codeUsed:B('Code used for this run','Kod yang digunakan untuk larian ini','此次运行使用的代码'),copyCore:B('Copy my core program here','Salin atur cara utama saya ke sini','将我的主程序复制到这里')
};
const TOPICS=[
 {id:'k1',area:'knowledge',title:B('Input and integer conversion','Input dan penukaran integer','输入与整数转换'),check:B('I can identify the text returned by input() and the integer produced by int().','Saya boleh mengenal pasti teks daripada input() dan integer yang dihasilkan oleh int().','我能辨认 input() 返回的文本和 int() 转换后的整数。'),evidence:B('Starter 1; my two input lines.','Permulaan 1; dua baris input saya.','练习 1；我的两行输入代码。')},
 {id:'k2',area:'knowledge',title:B('Variables and a constant','Pemboleh ubah dan pemalar','变量与常量'),check:B('I can identify an input variable, a calculated variable and our intended constant.','Saya boleh mengenal pasti pemboleh ubah input, pemboleh ubah dikira dan pemalar yang dimaksudkan.','我能辨认输入变量、计算得到的变量和预定的常量。'),evidence:B('Starter 2; MINUTES_PER_PERSON, people_ahead and total_minutes.','Permulaan 2; MINUTES_PER_PERSON, people_ahead dan total_minutes.','练习 2；MINUTES_PER_PERSON、people_ahead 和 total_minutes。')},
 {id:'s1',area:'skills',title:B('Collect and calculate','Kumpul dan kira','获取与计算'),check:B('I can write two numerical inputs and calculate both waiting time and total time.','Saya boleh menulis dua input berangka dan mengira masa menunggu serta jumlah masa.','我能编写两次数值输入，并计算等待时间和总时间。'),evidence:B('Starter 3 is a clue; my own runnable Main Task 1 code is stronger evidence.','Permulaan 3 ialah petunjuk; kod Tugasan Utama 1 yang boleh dijalankan ialah bukti lebih kukuh.','练习 3 提供线索；我自己编写的可运行代码是更有力的证据。')},
 {id:'s2',area:'skills',title:B('Write and test two paths','Tulis dan uji dua laluan','编写并测试两条路径'),check:B('I can write if/else with indentation and make both advice paths run.','Saya boleh menulis if/else dengan inden dan menjalankan kedua-dua laluan nasihat.','我能正确缩进 if/else，并让两条建议路径分别运行。'),evidence:B('Starter 4 is a clue; Main Task 2 code and tests A–C show what I can do.','Permulaan 4 ialah petunjuk; kod Tugasan Utama 2 dan ujian A–C menunjukkan kebolehan saya.','练习 4 提供线索；主要任务 2 的代码及测试 A–C 展示我的能力。')},
 {id:'u1',area:'understanding',title:B('Explain the calculation','Jelaskan pengiraan','解释计算'),check:B('I can explain why we use whole numbers and include Sam’s own help time.','Saya boleh menjelaskan sebab menggunakan nombor bulat dan memasukkan masa bantuan Sam sendiri.','我能解释为什么使用整数，以及为什么要计入 Sam 本人的服务时间。'),evidence:B('Starter 5; my explanation after Main Task 1.','Permulaan 5; penjelasan selepas Tugasan Utama 1.','练习 5；主要任务 1 后的解释。')},
 {id:'u2',area:'understanding',title:B('Explain the decision and its limits','Jelaskan keputusan dan batasannya','解释判断及其局限'),check:B('I can explain equality in <= and why the advice is based on an estimate.','Saya boleh menjelaskan kesamaan dalam <= dan sebab nasihat berdasarkan anggaran.','我能解释 <= 中的相等情况，以及建议为什么基于估计。'),evidence:B('Starter 6; test C and my advice explanation.','Permulaan 6; ujian C dan penjelasan nasihat saya.','练习 6；测试 C 和我的建议解释。')}
];
const STARTER=[
 {id:'q1',topic:'k1',prompt:B('The user types 3. What does input() store before int() is used?','Pengguna menaip 3. Apakah yang disimpan oleh input() sebelum int() digunakan?','用户输入 3。在使用 int() 前，input() 返回什么？'),options:[B('The integer 3','Integer 3','整数 3'),B('The string "3"','Rentetan "3"','字符串 "3"'),B('The Boolean True','Boolean True','布尔值 True')],answer:1,why:B('input() returns text: "3" is a string. int("3") produces integer 3 so the program can do arithmetic.','input() mengembalikan teks: "3" ialah rentetan. int("3") menghasilkan integer 3 untuk pengiraan.','input() 返回文本："3" 是字符串。int("3") 将其转换为整数 3，以便进行算术计算。')},
 {id:'q2',topic:'k2',prompt:B('Which name shows the intended constant in this classroom model?','Nama manakah menunjukkan pemalar yang dimaksudkan dalam model kelas ini?','哪个名称表示课堂模型中预定的常量？'),code:'MINUTES_PER_PERSON = 5\npeople_ahead = 2\nwaiting_minutes = people_ahead * MINUTES_PER_PERSON',options:['people_ahead','waiting_minutes','MINUTES_PER_PERSON'],answer:2,why:B('MINUTES_PER_PERSON is intended to stay fixed during the run. people_ahead can differ between users; waiting_minutes is calculated. Uppercase names are a convention, not a Python lock.','MINUTES_PER_PERSON dimaksudkan kekal semasa larian. people_ahead boleh berbeza antara pengguna; waiting_minutes dikira. Huruf besar ialah konvensyen, bukan kunci Python.','MINUTES_PER_PERSON 在运行过程中按设计保持固定。people_ahead 可因用户而异；waiting_minutes 由计算得到。大写名称是一种约定，Python 不会强制锁定它。')},
 {id:'q3',topic:'s1',prompt:B('Choose the pair of lines that receives a number and calculates waiting time.','Pilih pasangan baris yang menerima nombor dan mengira masa menunggu.','选择能获取数字并计算等待时间的两行代码。'),options:['people_ahead = input("People ahead: ")\nwaiting_minutes = people_ahead * 5','people_ahead = int(input("People ahead: "))\nwaiting_minutes = people_ahead * 5','people_ahead = int(input("People ahead: "))\nwaiting_minutes = "people_ahead" * 5'],answer:1,why:B('Convert the input to an integer, then multiply the variable. Multiplying text repeats text. Choosing the right lines is a starting point; writing and running your own code will demonstrate the skill.','Tukar input kepada integer, kemudian darabkan pemboleh ubah. Mendarab teks mengulang teks. Memilih baris betul ialah permulaan; menulis dan menjalankan kod sendiri menunjukkan kemahiran.','先将输入转换为整数，再对变量进行乘法运算。文本乘法会重复文本。选对代码是起点；亲自编写并运行代码才能展示技能。')},
 {id:'q4',topic:'s2',prompt:B('This program has two missing pieces. What does it need?','Atur cara ini mempunyai dua bahagian yang hilang. Apakah yang diperlukan?','这段程序缺少两处内容。需要补上什么？'),code:'total_minutes = 10\nminutes_available = 15\nif total_minutes <= minutes_available\nprint("The estimate fits.")\nelse:\n    print("Arrange another time.")',options:[B('A colon after the if condition, and indentation before its print.','Titik bertindih selepas syarat if dan inden sebelum print itu.','在 if 条件后加冒号，并缩进其 print。'),B('Quotation marks around both numbers.','Tanda petik pada kedua-dua nombor.','给两个数字加引号。'),B('Replace <= with =.','Gantikan <= dengan =.','将 <= 改为 =。')],answer:0,why:B('The colon starts a branch, and indentation shows which statement belongs to it. Test both outcomes after repairing the structure.','Titik bertindih memulakan cabang, dan inden menunjukkan pernyataan yang tergolong di dalamnya. Uji kedua-dua hasil selepas membaiki struktur.','冒号开始一个分支，缩进表明哪条语句属于该分支。修复结构后需要测试两种结果。')},
 {id:'q5',topic:'u1',prompt:B('The waiting time is 10 minutes. Why does that not tell us whether Sam can finish receiving help in 10 minutes? What must be added?','Masa menunggu ialah 10 minit. Mengapakah ini tidak menunjukkan Sam boleh selesai menerima bantuan dalam 10 minit? Apakah yang perlu ditambah?','等待时间是 10 分钟。为什么这不能说明 Sam 能在 10 分钟内完成求助？还需要加上什么？'),why:B('Waiting time ends when Sam’s turn begins. Add the time needed to help Sam. We use whole numbers because this first model records complete minutes and counts people.','Masa menunggu tamat apabila giliran Sam bermula. Tambahkan masa untuk membantu Sam. Kita menggunakan nombor bulat kerana model pertama ini merekod minit penuh dan bilangan orang.','等待时间在轮到 Sam 时结束。还要加上帮助 Sam 本人所需的时间。此模型记录整分钟并统计人数，所以使用整数。')},
 {id:'q6',topic:'u2',prompt:B('Explain the result when both values are 15. What would change if <= became <, and why is the time still only an estimate?','Jelaskan hasil apabila kedua-dua nilai ialah 15. Apakah perubahan jika <= menjadi <, dan mengapakah masa itu masih anggaran?','当两个值都为 15 时，解释判断结果。若把 <= 改为 <，会发生什么变化？为什么时间仍只是估计？'),code:'total_minutes <= minutes_available',why:B('15 <= 15 is True, but 15 < 15 is False. The chosen rule decides what happens at equality. The assumed time per person may differ from reality, so the program cannot promise completion.','15 <= 15 ialah True, tetapi 15 < 15 ialah False. Peraturan dipilih menentukan hasil apabila sama. Masa anggaran seorang mungkin berbeza daripada keadaan sebenar, jadi atur cara tidak boleh menjamin siap.','15 <= 15 为 True，15 < 15 为 False。所选规则决定相等时的结果。每人的实际服务时间可能不同，因此程序不能保证完成。')}
];
const CORE_START='# School IT helpdesk adviser\nMINUTES_PER_PERSON = 4\n\n# 1. Ask for people_ahead. Convert the input to int.\n\n# 2. Ask for minutes_available. Convert the input to int.\n\n# 3. Calculate waiting_minutes, then total_minutes.\n\n# 4. Print both estimates with labels and units.\n\n# Main Task 2: add if/else and advice for both paths.\n';
const MODEL_INPUT='MINUTES_PER_PERSON = 3\npeople_text = input("People ahead: ")\npeople_ahead = int(people_text)\nminutes_available = int(input("Minutes available: "))\nwaiting_minutes = people_ahead * MINUTES_PER_PERSON\ntotal_minutes = waiting_minutes + MINUTES_PER_PERSON\nprint("Estimated wait:", waiting_minutes, "minutes")\nprint("Estimated total:", total_minutes, "minutes")';
const MODEL_DECISION='total_minutes = 9\nminutes_available = 12\nif total_minutes <= minutes_available:\n    print("The estimate fits.")\nelse:\n    print("Arrange another time.")';
const TUTOR_CODE='MINUTES_PER_PERSON = 4\npeople_ahead = 2\nminutes_available = 15\nwaiting_minutes = people_ahead * MINUTES_PER_PERSON\ntotal_minutes = waiting_minutes + MINUTES_PER_PERSON\nif total_minutes <= minutes_available:\n    print("Ask the helpdesk about being seen now.")\nelse:\n    print("Arrange another time.")';
const TUTOR_STEPS=[
 [1,{MINUTES_PER_PERSON:'4'},B('Store our four-minute estimate. Its uppercase name shows that we intend to keep it fixed.','Simpan anggaran empat minit. Nama huruf besar menunjukkan niat untuk mengekalkannya.','存储四分钟的估计。大写名称表示我们打算保持它不变。')],
 [2,{people_ahead:'2'},B('Store 2 people ahead. These given values let us study the sequence; your own program will ask the user.','Simpan 2 orang di hadapan. Nilai diberi membantu kita mengkaji urutan; atur cara anda akan bertanya kepada pengguna.','存储排在前面的 2 人。示例先给定数值以便观察执行顺序；你的程序会向用户提问。')],
 [3,{minutes_available:'15'},B('Store 15 minutes available. This is the value we will compare with the total.','Simpan 15 minit tersedia. Nilai ini akan dibandingkan dengan jumlah masa.','存储可用的 15 分钟。稍后将把它与总时间进行比较。')],
 [4,{waiting_minutes:'8'},B('Read people_ahead and MINUTES_PER_PERSON. Calculate 2 × 4 = 8 and store the waiting time.','Baca people_ahead dan MINUTES_PER_PERSON. Kira 2 × 4 = 8 dan simpan masa menunggu.','读取 people_ahead 和 MINUTES_PER_PERSON。计算 2 × 4 = 8，并存储等待时间。')],
 [5,{total_minutes:'12'},B('Add Sam’s own four minutes: 8 + 4 = 12. Waiting and receiving help are different parts of the total.','Tambah empat minit untuk Sam sendiri: 8 + 4 = 12. Menunggu dan menerima bantuan ialah dua bahagian jumlah masa.','加上 Sam 本人的四分钟：8 + 4 = 12。等待和接受帮助是总时间的两个部分。')],
 [6,{},B('Compare 12 <= 15. This is True, so Python chooses the indented if branch.','Bandingkan 12 <= 15. Ini True, jadi Python memilih cabang if yang berinden.','比较 12 <= 15。结果为 True，因此 Python 选择缩进的 if 分支。')],
 [7,{},B('Print the first advice. The else branch is skipped; it does not print a second, conflicting instruction.','Cetak nasihat pertama. Cabang else dilangkau; ia tidak mencetak arahan kedua yang bercanggah.','显示第一条建议。else 分支被跳过，不会同时显示另一条相反的指令。')]
];
const PHASES=[['new',B('A good struggle, with progress. Try another case with a little less support.','Cabaran yang baik, dengan kemajuan. Cuba kes lain dengan kurang sokongan.','有挑战，也在进步。减少一点支持，再尝试一个例子。')],['consolidating',B('You are getting more accurate or fluent. Practise a fresh case and explain it.','Anda semakin tepat atau lancar. Latih kes baharu dan jelaskannya.','你越来越准确或熟练。练习一个新例子并解释。')],['treading',B('The work is already easy. Add the buffer or input guard and justify the change.','Kerja sudah mudah. Tambah penimbal atau semakan input dan jelaskan perubahan.','任务已经很容易。添加缓冲时间或输入检查，并说明理由。')],['drowning',B('You need help with a particular step. Point to the line or idea and ask for a worked explanation.','Anda memerlukan bantuan pada langkah tertentu. Nyatakan baris atau idea dan minta penjelasan bercontoh.','你在某一步需要帮助。指出具体代码行或概念，并请老师或同伴示范。')]];
const TESTS=[['A',2,15,B('Enough time','Masa mencukupi','时间充足')],['B',4,15,B('Not enough time','Masa tidak mencukupi','时间不足')],['C',2,12,B('Exactly equal','Sama tepat','恰好相等')]];

const CORE_SCAFFOLD=B(CORE_START, '# Penasihat meja bantuan IT sekolah\nMINUTES_PER_PERSON = 4\n\n# 1. Minta people_ahead. Tukar input kepada int.\n\n# 2. Minta minutes_available. Tukar input kepada int.\n\n# 3. Kira waiting_minutes, kemudian total_minutes.\n\n# 4. Cetak kedua-dua anggaran dengan label dan unit.\n\n# Tugasan Utama 2: tambah if/else dan nasihat kedua-dua laluan.\n', '# 学校 IT 服务台建议程序\nMINUTES_PER_PERSON = 4\n\n# 1. 获取 people_ahead，将输入转换为 int。\n\n# 2. 获取 minutes_available，将输入转换为 int。\n\n# 3. 计算 waiting_minutes，再计算 total_minutes。\n\n# 4. 输出两项估计，写明标签和单位。\n\n# 主要任务 2：添加 if/else 及两条路径的建议。\n');
const AREA_ACTIONS={knowledge:B('Clarify input() and int(), then label an input variable, a calculated value and the constant in the example.','Jelaskan input() dan int(), kemudian label pemboleh ubah input, nilai dikira dan pemalar dalam contoh.','弄清 input() 和 int()，再标出示例中的输入变量、计算值和常量。'),skills:B('Practise writing the two input lines and the if/else block. Then try without the example and run a different case.','Latih dua baris input dan blok if/else. Kemudian cuba tanpa contoh dan jalankan kes berbeza.','练习编写两行输入和 if/else 结构，再不看示例尝试，并运行不同情况。'),understanding:B('Explain why Sam’s own time must be added. Trace an equality case and explain why the chosen advice is only an estimate.','Jelaskan sebab masa Sam perlu ditambah. Jejak kes sama tepat dan jelaskan sebab nasihat dipilih hanya anggaran.','解释为什么要加上 Sam 本人的时间。追踪相等情况，并解释建议为什么只基于估计。')};
