(() => {
'use strict';
const L=window.LESSON, APP='w5s2-database', $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
let state=null,db=null,queue=Promise.resolve(),unsaved=false,pendingRestore=null;
const meta=new Map();
function blank(name,cls){return {version:1,name,cls,date:new Date().toLocaleDateString('en-GB'),step:0,answers:{},photos:{},design:{fields:[],records:[],tests:[]}};}
function profile(s=state){return [s.name.trim().toLowerCase(),s.cls.trim().toLowerCase()].join('|');}
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('mrdave-'+APP,1);r.onupgradeneeded=()=>r.result.createObjectStore('profiles');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
function get(key){return new Promise((resolve,reject)=>{const r=db.transaction('profiles').objectStore('profiles').get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
function save(){if(!state)return Promise.resolve();const snapshot=structuredClone(state),key=profile();unsaved=true;$('saveStatus').textContent='Saving…';queue=queue.catch(()=>{}).then(()=>new Promise((resolve,reject)=>{if(!db){reject(Error('Storage unavailable'));return;}const tx=db.transaction('profiles','readwrite');tx.objectStore('profiles').put(snapshot,key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);})).then(()=>{unsaved=false;$('saveStatus').textContent='Saved on this device';}).catch(()=>{unsaved=true;$('saveStatus').textContent='Device save unavailable — download a backup.';});return queue;}
function field(key,label,stage,rows=3){meta.set(key,{label,stage});return `<div class="question"><label for="${key}">${esc(label)}</label><textarea id="${key}" data-answer="${key}" rows="${rows}">${esc(state.answers[key]||'')}</textarea></div>`;}
function table(caption,heads,rows){return `<div class="table-wrap"><table><caption>${esc(caption)}</caption><thead><tr>${heads.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
const card=(title,body)=>`<section class="card"><h2>${title}</h2>${body}</section>`;
function mcq(key,title,options){meta.set(key,{label:title,stage:'read'});return `<fieldset class="card options"><legend>${esc(title)}</legend>${options.map((o,i)=>`<label><input type="radio" name="${key}" data-answer="${key}" value="${esc(o)}" ${state.answers[key]===o?'checked':''}>${esc(o)}</label>`).join('')}</fieldset>`;}
function checks(after){const stage=after?'pit':'before',choices=after?L.phases:L.starting;return L.checks.map(([id,type,statement,evidence])=>{const key=(after?'after_':'before_')+id;meta.set(key,{label:type+': '+statement,stage});const v=state.answers[key];const next={knowledge:'Explain one term using a row or column in your own table.',skills:'Check one field with a suitable value and an unsuitable value.',understanding:'Explain why a value can fit the type but fail the brief.'};const action=v==='Drowning'?'Ask your teacher to work through one field with you before continuing.':v==='Treading water'?'Try the extension: explain how the table should change when a requirement changes.':v==='Not checked yet'?'Attempt one relevant question, then return to this target.':next[id];return card(type,`<h3>${esc(statement)}</h3><p>${esc(evidence)}</p>${after?`<p class="small">Starting point: ${esc(state.answers['before_'+id]||'Not recorded')}</p>`:''}<label for="${key}">${after?'My phase now':'My starting point'}</label><select id="${key}" data-answer="${key}"><option value="">Choose…</option>${choices.map(o=>`<option ${v===o?'selected':''}>${esc(o)}</option>`).join('')}</select>${after&&v?`<p class="action">${action}</p>`:''}`);}).join('');}
function photo(stage){return `<section class="card upload"><h2>Working on paper?</h2><p>Number your answers and add a clear photo of each page. Keep corrections visible. You do not need to type the same answers again.</p><label>Add photographs<input type="file" data-upload="${stage}" accept="image/png,image/jpeg,image/webp" multiple></label><p class="small">JPG, PNG or WebP; maximum 15 MB per image. You can also paste a copied image here. Check every image is readable before submitting.</p><div class="photo-grid">${(state.photos[stage]||[]).map((p,i)=>`<div class="photo"><img src="${p.data}" alt="${esc(p.caption||p.name)}"><label>Questions or evidence shown<input data-caption="${stage}:${i}" value="${esc(p.caption||'')}"></label><button data-removephoto="${stage}:${i}">Remove photo ${i+1}</button></div>`).join('')}</div></section>`;}
function builder(){const d=state.design;return card('1. Design your fields',`<p>Use the six field names in the brief. Set a maximum character length for Text. Character means one character; other types do not need a text-length setting here.</p><div class="table-wrap"><table><caption>Club — table structure</caption><thead><tr><th>Field name</th><th>Data type</th><th>Text length</th><th>Action</th></tr></thead><tbody>${d.fields.map((f,i)=>`<tr><td><input aria-label="Field ${i+1} name" data-schema="${f.id}" data-prop="name" value="${esc(f.name)}" maxlength="40"></td><td><select aria-label="Field ${i+1} type" data-schema="${f.id}" data-prop="type"><option value="">Choose…</option>${L.types.map(t=>`<option ${f.type===t?'selected':''}>${t}</option>`).join('')}</select></td><td>${f.type==='Text'?`<input aria-label="Field ${i+1} maximum length" type="number" min="1" max="200" data-schema="${f.id}" data-prop="length" value="${esc(f.length)}">`:f.type==='Character'?'1 character':'Not applicable'}</td><td><button data-deletefield="${f.id}">Remove</button></td></tr>`).join('')}</tbody></table></div><button id="addField">+ Add a field</button>`)+card('2. Enter records',`<p>Each row must describe a different fictional club. Dates: YYYY-MM-DD. Boolean values: True or False. Values remain exactly as you type them so you can inspect errors.</p>${d.fields.length?`<div class="table-wrap"><table class="record-table"><caption>Club — your records</caption><thead><tr><th>#</th>${d.fields.map((f,i)=>`<th scope="col">${esc(f.name||'Field '+(i+1))}</th>`).join('')}<th>Action</th></tr></thead><tbody>${d.records.map((r,i)=>`<tr><th scope="row">${i+1}</th>${d.fields.map(f=>`<td><input aria-label="Record ${i+1}, ${esc(f.name||'unnamed field')}" data-record="${r.id}" data-col="${f.id}" value="${esc(r.values[f.id]||'')}"></td>`).join('')}<td><button data-deleterecord="${r.id}">Remove</button></td></tr>`).join('')}</tbody></table></div><button id="addRecord">+ Add a record</button>`:'<p class="action">Add your fields first, then enter records here.</p>'}`)+card('3. Test, explain and improve',field('prediction','Before checking: which value or design choice are you testing, and what should happen?','main2',2)+'<button id="testDesign" class="primary">Check and save this test</button><p class="small">Checks cover this brief, not every possible database rule. A passing result does not mark your written explanations.</p>'+d.tests.map((t,i)=>`<details ${i===d.tests.length-1?'open':''}><summary>Test ${i+1} · ${esc(t.time)} · ${t.issues.length?t.issues.length+' points to review':'Checks passed'}</summary><p><strong>Your prediction:</strong> ${esc(t.prediction||'Not recorded')}</p>${t.issues.length?'<ul>'+t.issues.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>':'<p class="ok">Your fields and records meet the checks in this brief. Explain why your choices work below.</p>'}</details>`).join(''))}
function validate(d){const issues=[],add=s=>issues.push(s),names=new Set();
 if(d.fields.length!==6)add('The brief asks for six fields. Check you have included each required fact once.');
 const expected={ClubCode:'Text',ClubName:'Text',Places:'Integer',SessionHours:'Real',StartDate:'Date',OpenToBeginners:'Boolean'};
 for(const f of d.fields){if(!f.name.trim())add('Give every field a meaningful name.');if(names.has(f.name.toLowerCase()))add('Repeated field name: '+f.name);names.add(f.name.toLowerCase());if(!L.types.includes(f.type))add((f.name||'Unnamed field')+': choose a data type.');if(f.type==='Text'&&(!Number.isInteger(Number(f.length))||Number(f.length)<1||Number(f.length)>200))add((f.name||'Text field')+': set a whole-number maximum length from 1 to 200.');}
 for(const [name,type] of Object.entries(expected)){const f=d.fields.find(f=>f.name===name);if(!f){add('Include the field '+name+' using the spelling in the brief.');continue;}if(f.type!==type)add(name+': reconsider what kind of value must be preserved. Your selected type does not fit this brief.');if(name==='ClubCode'&&f.type==='Text'&&Number(f.length)!==6)add('ClubCode: use the six-character code requirement to choose the maximum length.');if(name==='ClubName'&&f.type==='Text'&&Number(f.length)!==40)add('ClubName: the directory must allow names up to 40 characters. Set the maximum to match the brief.');}
 if(d.records.length<3)add('Enter at least three fictional club records.');
 const types={Text:()=>true,Character:v=>[...v].length===1,Integer:v=>/^[+-]?\d+$/.test(v),Real:v=>/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(v),Boolean:v=>/^(True|False)$/.test(v),Date:v=>/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v,Time:v=>/^([01]\d|2[0-3]):[0-5]\d$/.test(v)};
 for(const [i,r] of d.records.entries())for(const f of d.fields){const v=String(r.values[f.id]??'');const label='Record '+(i+1)+', '+(f.name||'unnamed field');if(!v.trim()){add(label+': enter a value.');continue;}if(types[f.type]&&!types[f.type](v))add(label+': “'+v+'” is not valid for '+f.type+'.');if(f.type==='Text'&&[...v].length>Number(f.length))add(label+': '+[...v].length+' characters exceeds your maximum of '+f.length+'.');if(f.name==='ClubCode'&&!/^[A-Z]{2}\d{4}$/.test(v))add(label+': use two uppercase letters followed by four digits.');if(f.name==='Places'&&(!/^\d+$/.test(v)||Number(v)<1||Number(v)>30))add(label+': the school allows 1 to 30 whole-number places.');if(f.name==='SessionHours'&&(!types.Real(v)||Number(v)<.5||Number(v)>3))add(label+': the allowed duration is 0.5 to 3 hours.');}
 const vals=name=>{const f=d.fields.find(f=>f.name===name);return f?d.records.map(r=>r.values[f.id]||''):[];};
 if(!vals('Places').includes('30'))add('Include one record at the 30-place limit.');if(!vals('SessionHours').some(v=>types.Real(v)&&!Number.isInteger(Number(v))))add('Include at least one fractional duration.');if(!['True','False'].every(v=>vals('OpenToBeginners').includes(v)))add('Include both True and False across your records.');
 return issues;
}
function content(id){return L.render({card,field,table,photo,checks,mcq,builder,state,esc},id);}
function render(){const [id,title,time]=L.stages[state.step];$('content').innerHTML=`<div class="stage-head"><p class="eyebrow">${time} · DATABASE CONCEPTS</p><h1 tabindex="-1">${title}</h1></div>`+content(id);$('identity').textContent=state.name.toLowerCase()==='teacher'?'Teacher preview · all pages open':state.name+' · '+state.cls;$('nav').innerHTML=L.stages.map((s,i)=>`<button data-step="${i}" ${i===state.step?'aria-current="step"':''}>${String(i+1).padStart(2,'0')} · ${s[1]}</button>`).join('');$('position').textContent=`${state.step+1} / ${L.stages.length} · ${title}`;$('prev').disabled=state.step===0;$('next').disabled=state.step===L.stages.length-1;}
function go(n){state.step=Math.max(0,Math.min(L.stages.length-1,n));render();save();scrollTo(0,0);$('content').querySelector('h1').focus({preventScroll:true});}
async function enter(name,cls){state=blank(name,cls);try{db=db||await openDB();const prior=await get(profile());if(prior)state=prior;}catch{}$('landing').hidden=true;$('lesson').hidden=false;render();await save();}
$('login').addEventListener('submit',async e=>{e.preventDefault();const name=$('name').value.trim(),cls=$('class').value.trim();if(!name||(!cls&&name.toLowerCase()!=='teacher')){$('loginError').textContent='Enter your name and class to start.';return;}await enter(name,cls);});
document.addEventListener('input',e=>{if(!state)return;const t=e.target;if(t.dataset.answer){state.answers[t.dataset.answer]=t.value;save();}if(t.dataset.caption){const[s,i]=t.dataset.caption.split(':');state.photos[s][i].caption=t.value;save();}if(t.dataset.schema){const f=state.design.fields.find(f=>f.id===t.dataset.schema);f[t.dataset.prop]=t.value;save();}if(t.dataset.record){const r=state.design.records.find(r=>r.id===t.dataset.record);r.values[t.dataset.col]=t.value;save();}});
document.addEventListener('change',e=>{if(!state)return;const t=e.target;if(t.dataset.upload)upload(t.files,t.dataset.upload);if(t.dataset.schema){const f=state.design.fields.find(f=>f.id===t.dataset.schema);f[t.dataset.prop]=t.value;save();render();}if(t.matches('select[data-answer]')){state.answers[t.dataset.answer]=t.value;save();render();$(t.dataset.answer)?.focus();}});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||!state)return;
 if(b.dataset.step!==undefined)go(Number(b.dataset.step));
 if(b.id==='next')go(state.step+1);if(b.id==='prev')go(state.step-1);
 if(['export','exportTop'].includes(b.id))exportPDF();if(['backup','backupEnd'].includes(b.id))backup();
 if(b.id==='switch'){await queue;$('lesson').hidden=true;$('landing').hidden=false;$('name').value='';$('class').value='';state=null;}
 if(b.dataset.check){const keys=b.dataset.check==='starter'?Array.from({length:10},(_,i)=>'s'+(i+1)):['m1','m2','m3'];const hasPhotos=(state.photos.start||[]).length>0;if(keys.some(k=>!state.answers[k]?.trim())&&!(b.dataset.check==='starter'&&hasPhotos)&&!confirm('Some answers are blank. Have you attempted them on paper and are you ready to check?'))return;state.answers[b.dataset.check+'Checked']='Yes';save();render();}
 if(b.id==='addField'){if(state.design.fields.length>=12){alert('This table is limited to 12 fields; the brief needs six.');return;}state.design.fields.push({id:uid(),name:'',type:'',length:''});save();render();$('content').querySelector('input[data-schema]:last-of-type')?.focus();}
 if(b.id==='addRecord'){if(state.design.records.length>=20){alert('You can add up to 20 records. Three are enough for this task.');return;}state.design.records.push({id:uid(),values:{}});save();render();}
 if(b.dataset.deletefield&&confirm('Remove this field and its values from the current table? Saved test snapshots will remain.')){state.design.fields=state.design.fields.filter(f=>f.id!==b.dataset.deletefield);for(const r of state.design.records)delete r.values[b.dataset.deletefield];save();render();}
 if(b.dataset.deleterecord&&confirm('Remove this record? Saved test snapshots will remain.')){state.design.records=state.design.records.filter(r=>r.id!==b.dataset.deleterecord);save();render();}
 if(b.id==='testDesign'){if(!state.answers.prediction?.trim()){alert('Write a short prediction before testing.');$('prediction').focus();return;}state.design.tests.push({time:new Date().toLocaleString('en-GB'),prediction:state.answers.prediction,fields:structuredClone(state.design.fields),records:structuredClone(state.design.records),issues:validate(state.design)});save();render();$('testDesign').scrollIntoView({block:'center'});}
 if(b.dataset.removephoto&&confirm('Remove this photograph?')){const[s,i]=b.dataset.removephoto.split(':');state.photos[s].splice(Number(i),1);save();render();}
});
async function resize(file){if(!/^image\/(png|jpeg|webp)$/.test(file.type)||file.size>15*1024*1024)throw Error('Choose a JPG, PNG or WebP image smaller than 15 MB.');const src=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);}),im=new Image();await new Promise((resolve,reject)=>{im.onload=resolve;im.onerror=reject;im.src=src;});const scale=Math.min(1,2200/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*scale);c.height=Math.round(im.height*scale);const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(im,0,0,c.width,c.height);return {name:file.name||'Pasted image',caption:'',data:c.toDataURL('image/jpeg',.92)};}
async function upload(files,stage){const owner=state;try{for(const f of files){const p=await resize(f);if(state!==owner)return;(state.photos[stage]??=[]).push(p);}await save();render();}catch(e){alert(e.message||'This image could not be read.');}}
document.addEventListener('paste',e=>{if(!state)return;const stage=L.stages[state.step][0];if(!['start','main1','main2','exit','extension'].includes(stage))return;const files=[...(e.clipboardData?.items||[])].filter(x=>x.type.startsWith('image/')).map(x=>x.getAsFile());if(files.length){e.preventDefault();upload(files,stage);}});
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
const filename=()=>('Year11_W5S2_'+state.name).replace(/[^a-z0-9_-]/gi,'_');
function backup(){download(new Blob([JSON.stringify({app:APP,state})],{type:'application/json'}),filename()+'.json');}
function validateBackup(s){if(!s||s.version!==1||typeof s.name!=='string'||!s.name.trim()||typeof s.cls!=='string'||typeof s.date!=='string'||!Number.isInteger(s.step)||s.step<0||s.step>=L.stages.length||!s.answers||!s.photos||!s.design)throw Error('Choose a backup from this lesson.');for(const v of Object.values(s.answers))if(typeof v!=='string')throw Error('Invalid answer in backup.');for(const [stage,arr] of Object.entries(s.photos)){if(!L.stages.some(x=>x[0]===stage)||!Array.isArray(arr))throw Error('Invalid photo data.');for(const p of arr)if(typeof p.data!=='string'||!/^data:image\/(jpeg|png|webp);base64,[a-z0-9+/=]+$/i.test(p.data)||typeof p.name!=='string'||typeof p.caption!=='string')throw Error('Invalid photograph.');}
 const checkTable=d=>{if(!Array.isArray(d.fields)||d.fields.length>12||!Array.isArray(d.records)||d.records.length>20)throw Error('Invalid table.');const ids=new Set();for(const f of d.fields){if(typeof f.id!=='string'||!/^[a-zA-Z0-9-]+$/.test(f.id)||ids.has(f.id)||typeof f.name!=='string'||typeof f.type!=='string'||typeof f.length!=='string')throw Error('Invalid field.');ids.add(f.id);}const rids=new Set();for(const r of d.records){if(typeof r.id!=='string'||!/^[a-zA-Z0-9-]+$/.test(r.id)||rids.has(r.id)||!r.values)throw Error('Invalid record.');rids.add(r.id);for(const v of Object.values(r.values))if(typeof v!=='string')throw Error('Invalid value.');}};checkTable(s.design);if(!Array.isArray(s.design.tests))throw Error('Invalid tests.');for(const t of s.design.tests){checkTable(t);if(typeof t.time!=='string'||typeof t.prediction!=='string'||!Array.isArray(t.issues)||t.issues.some(x=>typeof x!=='string'))throw Error('Invalid test.');}return s;}
$('restore').addEventListener('change',async e=>{try{pendingRestore=null;$('restorePanel').hidden=true;$('loginError').textContent='';const f=e.target.files[0];if(!f)return;if(f.size>80*1024*1024)throw Error('This backup is too large.');const data=JSON.parse(await f.text());if(data.app!==APP)throw Error('Use a Week 5 Session 2 database lesson backup.');pendingRestore=validateBackup(data.state);$('restoreSummary').textContent='Restore '+pendingRestore.name+' · '+pendingRestore.cls+'? This replaces the saved work for this name and class.';$('restorePanel').hidden=false;}catch(err){$('loginError').textContent=err.message||'Could not read this backup.';}});
$('cancelRestore').addEventListener('click',()=>{pendingRestore=null;$('restorePanel').hidden=true;$('restore').value='';});
$('confirmRestore').addEventListener('click',async()=>{if(!pendingRestore)return;state=pendingRestore;pendingRestore=null;$('restorePanel').hidden=true;try{db=db||await openDB();}catch{}$('landing').hidden=true;$('lesson').hidden=false;render();await save();});
async function exportPDF(){const button=$('exportTop');button.disabled=true;try{L.stages.forEach(([id])=>content(id));const {jsPDF}=window.jspdf,doc=new jsPDF({unit:'mm',format:'a4',compress:true});doc.addFileToVFS('Raleway.ttf',PDF_FONTS.regular);doc.addFont('Raleway.ttf','Raleway','normal');doc.addFileToVFS('RalewayBold.ttf',PDF_FONTS.bold);doc.addFont('RalewayBold.ttf','Raleway','bold');let y=23;const page=()=>{doc.addPage();y=23;};function text(t,size=11,bold=false){doc.setFont('Raleway',bold?'bold':'normal');doc.setFontSize(size);for(const line of doc.splitTextToSize(String(t||'Not recorded'),174)){if(y>271)page();doc.text(line,18,y);y+=size*.5;}y+=3;}function head(t){if(y>243)page();text(t,16,true);}function design(d){text('Table: Club',12,true);for(const f of d.fields)text((f.name||'Unnamed field')+' | '+(f.type||'Type not selected')+(f.type==='Text'?' | maximum '+(f.length||'?')+' characters':''));if(!d.fields.length)text('No fields created.');for(const [i,r] of d.records.entries()){text('Record '+(i+1),11,true);for(const f of d.fields)text((f.name||'Unnamed field')+': '+(r.values[f.id]||'Not recorded'));}if(!d.records.length)text('No records entered.');}
 text('YEAR 11 · COMPUTER SCIENCE',12,true);text(L.title,23,true);text('Term 1 · Week 5 · Session 2 · Paper 2');text(state.name+' · '+state.cls+' · '+state.date);text('WAGBA: '+L.wagba);text('This report includes responses, uploaded paper work, table design and saved test attempts. Blank answers are not assigned a mark. Learning phases are self-reports, not grades.');
 for(const [id,title] of L.stages.filter(s=>!['intro','creation','submit'].includes(s[0]))){page();head(title);if(id==='main1')text('18 marks available across eight classroom questions.');if(id==='extension')text('Original exam practice: Nov 2024 Q05.1 (1 mark), Jun 2025 Q09.2 (1 mark). The final challenge is a separate classroom task.');for(const[k,m]of meta){if(m.stage!==id)continue;if(y>251)page();text(m.label,10,true);text(state.answers[k]);}if(id==='main2'){head('My current table');design(state.design);for(const [i,t] of state.design.tests.entries()){head('Saved test '+(i+1)+' · '+t.time);text('Prediction: '+t.prediction);text(t.issues.length?'Points to review:':'All checks passed.');for(const issue of t.issues)text('- '+issue);text('Table at the time of this test',12,true);design(t);}}
 for(const p of state.photos[id]||[]){const props=doc.getImageProperties(p.data),scale=Math.min(174/props.width,205/props.height),w=props.width*scale,h=props.height*scale;if(y+h+24>271)page();text(p.caption||p.name,10,true);if(y+h>271)page();doc.addImage(p.data,'JPEG',18,y,w,h);y+=h+8;}}
 const pages=doc.getNumberOfPages();for(let i=1;i<=pages;i++){doc.setPage(i);doc.setDrawColor(150);doc.line(18,282,192,282);doc.setFont('Raleway','normal');doc.setFontSize(8);doc.text('Database concepts · '+state.name.slice(0,50),18,288);doc.text(`${i} / ${pages}`,192,288,{align:'right'});}doc.save(filename()+'.pdf');$('saveStatus').textContent='PDF downloaded — check it, then submit to Teams.';
 }catch(e){alert('PDF export failed. Save a backup now. '+e.message);}finally{button.disabled=false;}}
 window.addEventListener('beforeunload',e=>{if(state&&unsaved){e.preventDefault();e.returnValue='';}});
 // Pure checker exposed for automated verification; contains no pupil data or answer key.
 window.DatabaseChecks={validate};
})();
