window.LESSON_PAGES=[
  ['Prepare','6 min',pagePrepare],['Do now','5 min',pageStarter],['Types of learning','3 min',pageTypes],
  ['Main task 1','14 min',pageRelations],['Read: SQL changes','7 min',pageSqlRead],['Main task 2','16 min',pageSql],
  ['Learning pit stop','3 min',pagePit],['Plenary','4 min',pagePlenary],['Extension A','After lesson / early finish',pageExtensionA],
  ['Mark & improve','After Extension A',pageMark],['Extension B','After marking',pageExtensionB],['Submit','2 min',pageSubmit]
];
window.BASE_DB={
  Student:[{StudentID:'S014',Name:'Aisha Karim',Email:'aisha@school.edu'},{StudentID:'S027',Name:'Daniel Lim',Email:'daniel@school.edu'}],
  Book:[{BookID:'B031',Title:'Python Basics'},{BookID:'B044',Title:'Network Essentials'}],
  Loan:[{LoanID:'L101',StudentID:'S014',BookID:'B031',LoanDate:'2026-10-12',Returned:'FALSE'},{LoanID:'L102',StudentID:'S014',BookID:'B044',LoanDate:'2026-10-14',Returned:'FALSE'},{LoanID:'L103',StudentID:'S027',BookID:'B031',LoanDate:'2026-10-15',Returned:'TRUE'}]
};
window.DB_KEYS={Student:{pk:'StudentID'},Book:{pk:'BookID'},Loan:{pk:'LoanID',fk:['StudentID','BookID']}};
window.SQL_TASKS=[
 {id:'sql1',label:'A · Add a student',prompt:'Mina Rahman joins the library. Her StudentID is S039 and her email is mina@school.edu. Write one INSERT INTO statement that adds her complete record to Student. Then preview it and explain which row should be added.',expected:'Student'},
 {id:'sql2',label:'B · Correct one email address',prompt:'Aisha Karim has changed her email to aisha.new@school.edu. Write one UPDATE statement that changes only her Student record. Use StudentID, not her name, to identify the row.',expected:'Student'},
 {id:'sql3',label:'C · Record a return',prompt:'Loan L102 has been returned. Write one UPDATE statement that changes its Returned value to TRUE without changing the other loans.',expected:'Loan'},
 {id:'sql4',label:'D · Remove one loan record',prompt:'Loan L103 was entered by mistake and should be removed. Write one DELETE FROM statement that removes only that Loan record. Explain why the Student and Book records must remain.',expected:'Loan'}
];
window.esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function field(key,label,rows=3,hint=''){return `<label for="${key}">${label}</label>${rows===1?`<input id="${key}" data-key="${key}" value="${esc(appState.answers[key]||'')}" placeholder="${esc(hint)}">`:`<textarea id="${key}" data-key="${key}" rows="${rows}" placeholder="${esc(hint)}">${esc(appState.answers[key]||'')}</textarea>`}`}
function head(n,title,tag){return `<span class="badge">${n} · ${tag}</span><h1>${title}</h1>`}
function makeTables(db=BASE_DB,marks={}){return `<div class="tables">${Object.entries(db).map(([table,rows])=>`<div class="table-wrap"><table><caption>${table}</caption><thead><tr>${Object.keys(BASE_DB[table][0]).map(k=>`<th>${DB_KEYS[table].pk===k?`<span class="key">${k}</span>`:DB_KEYS[table].fk?.includes(k)?`<span class="fk">${k}</span>`:k}</th>`).join('')}</tr></thead><tbody>${rows.map((row,i)=>`<tr class="${marks[table]?.[i]||''}">${Object.keys(BASE_DB[table][0]).map(k=>`<td>${esc(row[k])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`).join('')}</div><p class="small"><span class="key">Underlined</span> = primary key · <span class="fk">Dotted underline</span> = foreign key. StudentID in Loan links to Student; BookID in Loan links to Book.</p>`}
function sideTable(inner=makeTables()){return `<section class="card db-side"><p class="eyebrow">DATABASE BESIDE YOUR WORK</p>${inner}</section>`}
function pagePrepare(){return `${head('00','Start with the library story','READ FIRST')}<div class="split"><div><div class="card accent"><h2>What the school needs</h2><p>The library records which students borrow which books. A student may borrow several books. A book may appear in several loan records over time. Each loan must identify its student and book.</p><p>If a student's email is copied into every loan record, changing that email means finding and correcting many records. One missed copy creates inconsistent data. Instead, store each student's details once in <strong>Student</strong>, each book once in <strong>Book</strong>, and each borrowing event in <strong>Loan</strong>.</p></div><div class="card"><h2>How to read the tables</h2><p>A <strong>primary key</strong> uniquely identifies a record in its own table. A <strong>foreign key</strong> is a field in one table that refers to a primary key in another. Follow Loan.StudentID → Student.StudentID to find who borrowed the book.</p><p>Read the three small tables beside this explanation. Find Loan L102. Who borrowed which book? Check the IDs first; do not guess from row position.</p>${field('readL102','Loan L102 belongs to which student and book? Explain the links.',2,'Follow each foreign key to its matching primary key.')}</div></div>${sideTable()}</div>`}
function pageStarter(){return `${head('01','Do now','RETRIEVE')}<p>Answer from memory first. Then use the tables beside you to check your reasoning.</p><div class="split"><div class="card"><ol class="plain-list"><li>What makes a primary key suitable for a table?</li><li>Loan L102 has StudentID S014 and BookID B044. Name the student and book.</li><li>Why would copying Aisha's email into every Loan record cause a problem when she changes it?</li><li>Which single keyword in an UPDATE or DELETE command limits the affected records?</li></ol>${field('starter','Write four numbered answers.',7,'1. ...  2. ...')}</div>${sideTable()}</div>`}
function pageTypes(){return `${head('02','What kind of learning is this?','DISCUSS')}<div class="card"><p><strong>Knowledge:</strong> remember what primary key, foreign key, redundancy and the SQL keywords mean.</p><p><strong>Skill:</strong> practise following keys and writing a command that affects exactly one intended row.</p><p><strong>Understanding:</strong> explain why separate linked tables prevent inconsistent copies, and predict how a command changes the data.</p><p>Talk to your partner for 30 seconds: which part will stretch you most today? Choose one and give a reason tied to this library database.</p>${field('learningType','My choice and reason',2,'For me, writing WHERE is a skill because ...')}</div>`}
function pageRelations(){return `${head('03','Main task 1: design the links','AO1 → AO2')}<div class="split"><div><div class="card accent"><h2>Worked example</h2><p>In Loan L101, StudentID <strong>S014</strong> matches Student.StudentID <strong>S014</strong>. So that loan belongs to Aisha. The same loan's BookID <strong>B031</strong> matches Book.BookID <strong>B031</strong>, so it is for <em>Python Basics</em>.</p><p>Notice that Aisha's email and the book title are not copied into Loan. This avoids repeated details. Loan stores only the IDs needed to make the links.</p></div><div class="card"><h2>Your design challenge</h2><p>A new requirement says the library will record many loans for the same student and many loans for the same book. Use the visible tables and write a short design explanation. You may sketch the relationships on paper and add a photograph.</p>${field('relKeys','1. Identify the primary key of Student, Book and Loan. Identify both foreign keys in Loan.',3)}${field('relLinks','2. State each one-to-many relationship and explain why it is one-to-many.',3)}${field('relRedundancy','3. Explain one specific redundancy or inconsistency that these linked tables avoid.',3)}${field('relChallenge','4. Challenge: if Student S014 changed email, which table and record should be changed? What should stay unchanged?',3)}<label for="relPhoto">Optional paper diagram or handwritten explanation</label><input type="file" id="relPhoto" data-photo="relPhoto" accept="image/*" capture="environment"><div id="relPhotoPreview"></div><div class="preview"><strong>Teacher check:</strong> show your keys, links and explanation before moving on. Note one correction after feedback.</div>${field('relFeedback','Feedback and my correction',2)}</div></div>${sideTable()}</div>`}
function pageSqlRead(){return `${head('04','Read before you change data','GUIDED PRACTICE')}<div class="split"><div><div class="card accent"><h2>Three different jobs</h2><p><strong>INSERT INTO</strong> adds a new record. In this specification, use VALUES for the whole record in field order.</p><div class="code">INSERT INTO Book VALUES ('B055', 'Database Design');</div><p><strong>UPDATE</strong> changes existing values. <strong>SET</strong> names the field and new value; <strong>WHERE</strong> chooses the record.</p><div class="code">UPDATE Book SET Title = 'Database Basics' WHERE BookID = 'B055';</div><p><strong>DELETE FROM</strong> removes a record. A precise WHERE condition is essential.</p><div class="code">DELETE FROM Book WHERE BookID = 'B055';</div><p>Text values have quotes. Look at the table headings for exact field names. Without WHERE, UPDATE or DELETE could affect every row in a table.</p></div><div class="card"><h2>Thirty-second skill check</h2><p>Which command changes only Loan L102 to returned?</p><div class="code">UPDATE Loan SET Returned = TRUE WHERE LoanID = 'L102';</div><p>Point to the table, field, new value and record selector. Then answer:</p>${field('sqlReadCheck','What would happen if WHERE LoanID = ... were removed?',2)}</div></div>${sideTable()}</div>`}
function pageSql(){return `${head('05','Main task 2: change the right rows','AO2')}<p>Keep the database visible as you work. Write each SQL statement, then select <strong>Preview change</strong>. The preview shows which row your command would affect. It does not change the starting database for the next question.</p><div class="split"><div><div class="card">${SQL_TASKS.map(t=>`<section class="question"><h2>${t.label}</h2><p>${t.prompt}</p>${field(t.id,'Write your SQL statement',3,'Use the exact table and field names shown beside you.')}<button type="button" data-preview="${t.id}">Preview change</button><div class="preview" id="feedback-${t.id}" aria-live="polite">Your preview will appear here.</div>${field(t.id+'Reason','What should change? What must stay unchanged?',2)}</section>`).join('')}<div class="preview"><strong>Teacher check:</strong> show one statement and its preview. Correct the first syntax or row-selection error you find.</div>${field('sqlFeedback','The correction I made after feedback',2)}</div></div><section class="card db-side"><p class="eyebrow">LIVE DATABASE · SAME VIEW</p><p class="small">The selected preview appears below. Each task starts from the original database shown here.</p><div id="liveTables">${makeTables()}</div></section></div>`}
function pagePit(){return `${head('06','Learning pit stop','REFLECT')}<div class="card"><h2>What happened when you tested your SQL?</h2><p>Choose the phrase that best describes your learning <em>right now</em> and give evidence from your work.</p><div class="two"><div><label class="choice"><input type="radio" name="pit" value="New learning"> New learning: I am learning an unfamiliar idea and working through it.</label><label class="choice"><input type="radio" name="pit" value="Consolidating"> Consolidating: I am using prior knowledge more accurately.</label><label class="choice"><input type="radio" name="pit" value="Treading water"> Treading water: the work is too easy and I need a tougher comparison.</label><label class="choice"><input type="radio" name="pit" value="Drowning"> Drowning: I need help with one specific point before I can continue.</label></div><div><p>Use a precise example: following Loan.StudentID, choosing WHERE, or spotting repeated data. If you need help, name the exact line or keyword.</p>${field('pitEvidence','My evidence and next action',4,'I selected … because task … showed …; next I will …')}</div></div></div>`}
function pagePlenary(){return `${head('07','Prove what changed','EXIT TICKET')}<div class="card"><p>Answer without copying from the reading. Your response should show both a database idea and a safe SQL habit.</p>${field('plenary1','1. Explain how Loan connects Student and Book without storing repeated names or titles.',3)}${field('plenary2','2. Write a DELETE FROM command for Loan L102, then explain what could happen if you omitted WHERE.',4)}${field('plenary3','3. Which part of today’s work still needs practice? Name a specific question or keyword.',2)}</div>`}
function pageExtensionA(){return `${head('08','Extension A: original exam questions','10 MARKS')}<div class="card accent"><h2>Collect the printed paper from me</h2><p>Ask for <strong>Extension A: Databases and SQL</strong>. These are unaltered extracts from OxfordAQA 9210/2 question papers. Work on the paper, not on this website. You will see the original tables and question layout.</p><ol class="plain-list"><li>Complete the 10 marks independently.</li><li>Bring the paper to me for marking or mark it when I release the scheme.</li><li>Correct one answer in a different colour and explain the change.</li><li>Then continue to Extension B to revisit earlier topics.</li></ol><p class="small">Selected: November 2024 Q05.3–05.4; June 2024 Q08.1 and Q08.3; November 2023 Q06.1 and Q06.4.</p></div>`}
function pageMark(){return `${head('09','Mark and improve','AFTER EXTENSION A')}<div class="card"><p>Once I have checked your Extension A paper, record your score and one precise improvement. I will give the passcode when it is time to view the original mark schemes. The PDFs also ask for the same password when opened.</p>${field('extAScore','Extension A score out of 10',1,'e.g. 7')}${field('extACorrection','One mark I reclaimed: what I wrote, what the mark scheme requires, and my correction',4)}<label for="pass">Passcode for original mark-scheme PDFs</label><input id="pass" type="password" autocomplete="off" placeholder="Ask your teacher"><button id="unlock" type="button">Unlock mark schemes</button><p id="unlockStatus" role="status"></p><div id="teacherLinks" hidden><p><a href="teacher/Extension_A_Original_Mark_Scheme.pdf" target="_blank" rel="noopener">Open Extension A original mark scheme (PDF)</a></p><p><a href="teacher/Extension_B_Original_Mark_Scheme.pdf" target="_blank" rel="noopener">Open Extension B original mark scheme (PDF)</a></p><div class="preview"><h3>Main task answer guide</h3><p>Student and Book each have a unique primary key; Loan has LoanID as its primary key and StudentID/BookID as foreign keys. One Student or Book can occur in many Loan records. The matching values in SQL tasks are: add S039/Mina Rahman; update Student S014 email; update Loan L102 Returned to TRUE; delete only Loan L103. Every UPDATE and DELETE must select the intended row using WHERE.</p></div></div></div>`}
function pageExtensionB(){return `${head('10','Extension B: return to earlier topics','10 MARKS')}<div class="card accent"><h2>Collect the second paper from me</h2><p>After you have marked and improved Extension A, ask for <strong>Extension B: Retrieval Practice</strong>. Complete this second paper by hand. It revisits Year 10 number representation and this term’s networks, protocols and cyber security.</p><p>Do not expect to know every answer immediately: retrieve what you can, then check and correct it using the original scheme when I release it.</p><p class="small">Selected: June 2025 Q01.1–01.3 and Q08.1; November 2024 Q01.4–01.6.</p>${field('extBScore','After marking: Extension B score out of 10',1,'e.g. 8')}${field('extBCorrection','One answer I improved and why',3)}</div>`}
function pageSubmit(){return `${head('11','Save and submit','FINAL STEP')}<div class="card"><ol class="plain-list"><li>Read through your answers and teacher-feedback correction.</li><li>Use <strong>Save PDF</strong> in the top-right corner. Open the PDF and check that your name and answers appear.</li><li>Upload the PDF to the Teams assignment. If you drew a relationship diagram on paper, its photo will be included if you added it here.</li><li>Keep a <strong>Full backup</strong> if you want to resume or retain the editable work.</li></ol><p class="small">Your printed extension papers are handed to me separately. They are not copied into the student PDF.</p></div>`}
