'use strict';
const TUTOR_STATE={};
const TITLES={desk:B('Example 1 · Is the helpdesk open?','Contoh 1 · Adakah meja dibuka?','示例 1 · 服务台开放吗？'),time:B('Example 2 · Is there enough time?','Contoh 2 · Adakah masa cukup?','示例 2 · 时间够用吗？')};
function tutorial(id){const s=TUTOR_STATE[id]||{choice:0,step:0},desk=id!=='time',closed=s.choice===2;
 const code=desk?nestedCode.replace('desk_open = True','desk_open = '+(closed?'False':'True')).replace('people_ahead = 2','people_ahead = '+(s.choice===1?0:2)):timeCode.replace('minutes_available = 12','minutes_available = '+[12,11,-1][s.choice]);
 const route=closed?[0,1,2,8]:[0,1,2,3,desk?(s.choice===1?4:6):(s.choice===0?4:6)];const step=Math.min(s.step,route.length-1),line=route[step],innerTrue=desk?s.choice===1:s.choice===0;
 const notes=[B('Store the first value. No decision has run yet.','Simpan nilai pertama. Belum ada keputusan.','保存第一个值，尚未进行判断。'),B('Store the second value. These values decide which route runs.','Simpan nilai kedua. Nilai ini menentukan laluan.','保存第二个值，这些值决定执行路径。'),closed?B('The outer condition is False. Skip the inner decision and move to the outer else.','Syarat luar False. Langkau keputusan dalaman dan pergi ke else luar.','外层条件为 False。跳过内层判断，前往外层 else。'):B('The outer condition is True. Enter its indented block.','Syarat luar True. Masuk blok berinden.','外层条件为 True，进入其缩进代码块。'),B('Evaluate the inner condition: '+(innerTrue?'True':'False')+'. Follow only its matching branch.','Nilai syarat dalaman: '+(innerTrue?'True':'False')+'. Ikuti cabang yang sepadan sahaja.','计算内层条件：'+(innerTrue?'True':'False')+'。只执行对应分支。'),B('Print this message. The other output lines are skipped.','Cetak mesej ini. Baris output lain dilangkau.','输出这条消息，跳过其他输出行。')];
 const note=closed&&step===3?notes[4]:notes[step];const labels=desk?[B('Open · queue','Buka · beratur','开放 · 有人排队'),B('Open · no queue','Buka · tiada barisan','开放 · 无人排队'),B('Closed','Tutup','关闭')]:[B('12 minutes','12 minit','12 分钟'),B('11 minutes','11 minit','11 分钟'),B('−1 minute','−1 minit','−1 分钟')];
 return `<div class="line-tutor" id="walk-${id}"><div class="actions">${labels.map((l,i)=>`<button data-walk-case="${id}" data-choice="${i}" aria-pressed="${i===s.choice}">${bi(l)}</button>`).join('')}</div><div class="tutor-grid"><ol class="trace-code">${code.split('\n').map((l,i)=>`<li class="${route.includes(i)?'':'skipped'}" ${i===line?'aria-current="step"':''}>${codeMarkup(l)}</li>`).join('')}</ol><div class="tutor-note" aria-live="polite"><span class="tag">${t('Line','Baris','行')} ${line+1} · ${step+1}/${route.length}</span>${para(note)}<p class="small">${t('Faded lines are not executed in this case.','Baris pudar tidak dilaksanakan dalam kes ini.','浅色行在此案例中不执行。')}</p><div class="actions"><button data-walk="${id}" data-step="${step-1}" ${step===0?'disabled':''}>← ${bi(L.back)}</button><button class="primary" data-walk="${id}" data-step="${step===route.length-1?0:step+1}">${step===route.length-1?t('Replay','Ulang','重播'):t('Next line','Baris seterusnya','下一行')} →</button></div></div></div></div>`;
}
function questionsFor(page){return (QUESTION_SETS[page]||[]).map(mcq).join('');}
function validationTable(){return `<div class="tablewrap"><table><thead><tr><th>${t('Check','Semakan','验证')}</th><th>${t('What it checks','Apa yang disemak','检查什么')}</th><th>${t('Accepted example','Contoh diterima','接受的例子')}</th><th>${t('Rejected example','Contoh ditolak','拒绝的例子')}</th></tr></thead><tbody>${[
 [0,B('An answer was supplied. Trim spaces before checking.','Jawapan diberi. Buang ruang tepi sebelum menyemak.','是否填写答案，检查前去除两侧空格。'),'Sam','(blank)'],
 [1,B('A whole number can be used for a count.','Nombor bulat boleh digunakan untuk bilangan.','计数是否可用整数表示。'),'4','four / 2.5'],
 [2,B('A number is within limits: 1–10 inclusive.','Nombor dalam had: 1–10 termasuk hujung.','数值是否在 1–10 范围内（含端点）。'),'1, 5, 10','0, 11'],
 [3,B('Exactly six characters were entered.','Tepat enam aksara dimasukkan.','是否恰好六个字符。'),'ABC123','ABC12'],
 [4,B('A code follows HD- then three digits.','Kod mengikut HD- dan tiga digit.','代码是否为 HD- 后跟三位数字。'),'HD-204','204-HD']
 ].map(([i,m,a,r])=>`<tr><td><b>${bi(checksNames[i])}</b></td><td>${bi(m)}</td><td><code>${a}</code></td><td><code>${r==='(blank)'?t('blank','kosong','空白'):r}</code></td></tr>`).join('')}</tbody></table></div>`;}
function dataCards(){return `<div class="three-grid">${[
 [testNames[0],B('Typical allowed data. For 1–10 tickets, try 5.','Data biasa yang dibenarkan. Untuk 1–10 tiket, cuba 5.','典型有效数据。允许 1–10 张工单时，测试 5。'),'5'],
 [testNames[1],B('At and around a limit. For the upper limit 10, try 9, 10 and 11.','Pada dan sekitar had. Untuk had atas 10, cuba 9, 10 dan 11.','在边界上及附近。上限 10 时，测试 9、10、11。'),'9 · 10 · 11'],
 [testNames[2],B('Data that should be rejected. Try text, a blank answer or an out-of-range number.','Data yang patut ditolak. Cuba teks, kosong atau nombor luar julat.','应该拒绝的数据，例如文本、空白或超范围数字。'),'hello · −3']
 ].map(([h,p,v])=>card(h,`<div class="number-example">${v}</div>${para(p)}`)).join('')}</div>${para(B('A value can check a boundary and be erroneous: 11 is just above the limit of 10 and must be rejected.','Nilai boleh menguji sempadan dan juga salah: 11 melebihi had 10 dan mesti ditolak.','一个值可同时测试边界并属于错误数据：11 略高于上限 10，应被拒绝。'))}`;}
readPage=function(){return `${card(B('A decision inside a decision','Keputusan dalam keputusan','判断中的判断'),para(B('Sam needs help with a laptop. First check whether the helpdesk is open. Only when it is open, check whether anyone is waiting. This is nested selection.','Sam perlukan bantuan laptop. Semak sama ada meja dibuka. Hanya apabila dibuka, semak sama ada orang menunggu. Ini pilihan bersarang.','Sam 需要电脑帮助。先检查服务台是否开放；只有开放时，才检查是否有人排队。这就是嵌套选择。'))+tutorial('intro'))}${card(B('Validation: check the input rules','Pengesahan: semak peraturan input','数据验证：检查输入规则'),para(B('A program should check whether data is suitable before using it. A ticket count of 1–10 must be a whole number in that range. Validation does not prove that the answer is true.','Atur cara patut menyemak data sesuai sebelum menggunakannya. Bilangan tiket 1–10 mesti nombor bulat dalam julat itu. Pengesahan tidak membuktikan jawapan benar.','程序使用数据前应检查它是否符合规则。1–10 张工单必须是该范围内的整数。验证不能证明答案真实。'))+`<div class="two-grid"><div class="mini-rule">${t('No answer → presence check','Tiada jawapan → semakan kehadiran','无答案 → 非空验证')}</div><div class="mini-rule">${t('Outside the limits → range check','Di luar had → semakan julat','超出上下限 → 范围验证')}</div></div>`)}${dataCards()}${card(B('Five reading checks','Lima semakan bacaan','五个阅读检查'),questionsFor('read'))}`;};
starterPage=function(){return `<p class="instruction">${t('Arrange both short programs. Then choose the validation answers. Use the reading page if you need a reminder.','Susun kedua-dua atur cara pendek. Kemudian pilih jawapan pengesahan. Rujuk bacaan jika perlu.','排列两个短程序，再选择验证答案。需要时可返回阅读页。')}</p>${puzzleHTML('do1')}${puzzleHTML('do2')}${card(B('Recognise the terms and rules','Kenali istilah dan peraturan','识别术语和规则'),questionsFor('starter'))}`;};
reflection=function(end){if(end)return pitStop();return `<p class="intro">${t('Think about the starter. Choose one response for each check. No written explanation needed.','Fikirkan latihan permulaan. Pilih satu respons bagi setiap semakan. Tidak perlu penjelasan bertulis.','回顾课前练习，为每项选择一个回答，不需要写解释。')}</p><div class="reflection-grid">${['K','S','U'].map(area=>card(L[area],CHECKS.filter(c=>c[1]===area).map(([id,,label,qid])=>{const q=STARTER.find(q=>q.id===qid);let evidence=id==='s1'?`${t('Code orders checked','Susunan kod disemak','已检查的代码顺序')}: ${['do1','do2'].filter(p=>state.orderChecked[p]&&ordered(p)).length}/2`:val(qid)&&state.checked[qid]?`${t('Starter check','Semakan permulaan','课前检查')}: ${Number(val(qid))===q.answer?t('correct','betul','正确'):t('try again','cuba lagi','再试一次')}`:txt(L.noEvidence);return `<div class="reflection-check"><h3>${bi(label)}</h3><p class="small">${evidence}</p>${select('start_'+id,B('My starting point','Titik mula saya','我的起点'),[['independent',B('I can do this confidently','Saya boleh buat dengan yakin','我能自信地完成')],['support',B('I can do this with a reminder','Saya boleh buat dengan peringatan','借助提示我能完成')],['need',B('I need to learn this','Saya perlu belajar ini','我需要学习这一项')],['untried',L.untried]])}</div>`;}).join(''))).join('')}</div>${card(B('My practice focus','Fokus latihan saya','我的练习重点'),`<div id="focus-summary">${focusSummary('start')}</div>`)}`;};
const baseFocus=focusSummary;
focusSummary=function(prefix){const counts=['K','S','U'].map(a=>[a,CHECKS.filter(c=>c[1]===a&&['support','need'].includes(val(prefix+'_'+c[0]))).length]),max=Math.max(...counts.map(c=>c[1])),leaders=counts.filter(c=>c[1]===max).map(c=>c[0]);const next={K:B('Use the example and validation table to clarify meanings.','Guna contoh dan jadual pengesahan untuk memahami maksud.','用示例和验证表弄清概念。'),S:B('Practise arranging, repairing and running the code.','Latih menyusun, membaiki dan menjalankan kod.','练习排列、修复并运行代码。'),U:B('Follow why one branch runs and another is skipped.','Ikuti sebab satu cabang berjalan dan satu lagi dilangkau.','跟随讲解，理解为何执行某分支、跳过另一分支。')};return baseFocus(prefix)+(max?`<p>${leaders.map(a=>bi(next[a])).join(' ')}</p>`:'');};
exercise=function(id){const p=PROGRAMS[id];return `<div class="task-brief"><span class="tag">${bi(L.try)}</span><h3>${bi(p.title)}</h3>${para(state.guided?GUIDED_TASKS[id]:id==='core'?B('Write your code here. Run the three cases below and compare the outputs.','Tulis kod di sini. Jalankan tiga kes di bawah dan bandingkan output.','在这里编写代码，运行下面三个案例，并比较输出。'):p.task)}${state.guided?`<div class="word-bank">${t('Try these symbols','Cuba simbol ini','尝试这些符号')}: <code>== &gt; : 5 10</code></div>`:''}</div>${ide(id)}${testCards(id)}${teacher?`<details class="teacher-model"><summary>${t('Teacher: worked solution','Guru: penyelesaian','教师：参考答案')}</summary>${codeBox(p.solution)}</details>`:''}`;};
function nestedReading(){return `${card(B('Read from the outside in','Baca dari luar ke dalam','从外到内阅读'),para(B('1. Check the outer condition. 2. Enter its matching branch. 3. Read an inner decision only if that branch contains it. Indentation shows which lines belong together.','1. Semak syarat luar. 2. Masuk cabang sepadan. 3. Baca keputusan dalaman hanya jika cabang itu mengandunginya. Inden menunjukkan baris yang bersama.','1. 检查外层条件。2. 进入对应分支。3. 只有分支内包含内层判断时才执行它。缩进说明哪些行属于同一块。')))}${card(TITLES.desk,tutorial('desk'))}${card(TITLES.time,tutorial('time'))}${questionsFor('nested-read')}`;}
function debugPage(){return `${card(B('Before you repair','Sebelum membaiki','修复前先看'),`<div class="example-grid">${codeBox('if permission:\n    if stock > 0:\n        print("Borrow a laptop")\n    else:\n        print("Join the waiting list")\nelse:\n    print("Ask a teacher")')}<div>${para(B('Each if and else line ends with a colon. The inner if uses four spaces. Its print uses eight. The outer else starts at the left edge.','Setiap baris if dan else berakhir dengan titik bertindih. if dalaman guna empat ruang. print-nya guna lapan. else luar bermula di kiri.','每个 if 和 else 行以冒号结尾。内层 if 缩进四格，其 print 缩进八格。外层 else 从最左侧开始。'))}</div></div>`)}${['gap','syntax','indent'].map(id=>card(PROGRAMS[id].title,exercise(id))).join('')}`;}
function programPage(){return `<div class="program-layout"><div class="program-reference">${card(L.sample,codeBox(nestedCode)+para(B('This sample checks opening first, then the queue. Your task checks permission first, then stock.','Contoh ini menyemak pembukaan, kemudian baris gilir. Tugasan anda menyemak kebenaran, kemudian stok.','示例先检查是否开放，再检查队伍。你的任务先检查许可，再检查库存。')))}${card(B('Your scenario','Situasi anda','你的情景'),para(PROGRAMS.core.task)+`<ul><li><code>yes → 2 → Borrow a laptop</code></li><li><code>yes → 0 → Join the waiting list</code></li><li><code>no → Ask a teacher</code></li></ul>`+para(B('For this task, use yes/no and whole-number stock of zero or more. The extension adds checks for unsuitable input.','Untuk tugas ini, guna yes/no dan stok nombor bulat sifar atau lebih. Cabaran menambah semakan input tidak sesuai.','本题使用 yes/no，库存输入零或正整数。进阶任务会增加不合适输入的验证。')))}</div><div>${exercise('core')}</div></div>`;}
function validationReading(){return `${card(B('Five useful validation checks','Lima semakan pengesahan berguna','五种常用数据验证'),validationTable())}${card(B('A validation routine is a sequence of checks','Rutin pengesahan ialah urutan semakan','验证过程是一系列检查'),para(B('This small routine already has an integer. It checks the allowed range before choosing a desk. Presence and type checks are needed as well when collecting arbitrary user input.','Rutin kecil ini sudah mempunyai integer. Ia menyemak julat sebelum memilih meja. Semakan kehadiran dan jenis juga diperlukan untuk input pengguna umum.','这个小程序已获得整数。它在选择服务台前检查范围。接收任意用户输入时，还需要非空和类型验证。'))+codeBox('tickets = 7\nif 1 <= tickets <= 10:\n    if tickets <= 5:\n        print("Quick desk")\n    else:\n        print("Group desk")\nelse:\n    print("Enter 1 to 10")')+para(B('7 passes the range check. 7 <= 5 is False, so the output is Group desk. Try tracing 0: no desk advice is printed.','7 lulus julat. 7 <= 5 ialah False, maka output Group desk. Jejak 0: tiada nasihat meja dicetak.','7 通过范围验证。7 <= 5 为 False，所以输出 Group desk。跟踪 0：不应输出服务台建议。')))}${card(B('Plan tests around the rules','Rancang ujian sekitar peraturan','根据规则设计测试'),dataCards())}${questionsFor('validation-read')}`;}
function validationPractice(){return `${card(B('Keep this reference beside you','Simpan rujukan ini','参考表'),validationTable())}${card(B('1 · Match each definition','1 · Padankan definisi','1 · 匹配定义'),(QUESTION_SETS.validation||[]).filter(q=>q.id.startsWith('m')).map(mcq).join(''))}${card(B('2 · Choose checks and test data','2 · Pilih semakan dan data ujian','2 · 选择验证方法和测试数据'),para(B('Read the rule in each card. Choose the check that addresses that rule; a full form may need several checks.','Baca peraturan setiap kad. Pilih semakan untuk peraturan itu; borang penuh mungkin memerlukan beberapa semakan.','阅读每张卡的规则，选择对应验证。完整表单可能需要多个验证。'))+(QUESTION_SETS.validation||[]).filter(q=>q.id.startsWith('a')).map(mcq).join(''))}`;}
extensionPage=function(){return `${card(B('Use your extra time: the ticket desk','Gunakan masa tambahan: meja tiket','利用剩余时间：工单服务台'),para(B('Build a working solution, then compare how many cases it passes. Accuracy matters more than typing speed. Use fictional data.','Bina penyelesaian, kemudian bandingkan bilangan kes lulus. Ketepatan lebih penting daripada kelajuan menaip. Guna data rekaan.','编写可运行的程序，再比较通过的测试数。正确比打字快更重要，请使用虚构数据。')))}<div class="two-grid">${card(B('Scenario and requirements','Situasi dan keperluan','情景与要求'),para(PROGRAMS.extension.task)+`<ol><li>${t('Bronze: both valid desk routes work.','Gangsa: kedua-dua laluan meja sah berfungsi.','铜级：两个有效的服务台分支可运行。')}</li><li>${t('Silver: reject 0 and 11; accept 1 and 10.','Perak: tolak 0 dan 11; terima 1 dan 10.','银级：拒绝 0 和 11，接受 1 和 10。')}</li><li>${t('Gold: reject blank, words and decimals without crashing.','Emas: tolak kosong, perkataan dan perpuluhan tanpa ranap.','金级：拒绝空白、文字和小数，程序不崩溃。')}</li></ol>`)}${card(B('Sample output and supplied support','Contoh output dan sokongan','示例输出与辅助代码'),codeBox('Tickets (1-10): 7\nUse the group desk')+para(B('The starter supplies try/except: try attempts int(answer); except ValueError shows a helpful message when conversion fails. Complete the range and inner decision.','Kod permulaan menyediakan try/except: try mencuba int(answer); except ValueError memaparkan mesej jika penukaran gagal. Lengkapkan julat dan keputusan dalaman.','起始代码提供 try/except：try 尝试 int(answer)，转换失败时 except ValueError 显示提示。补全范围与内层条件。')))}</div>${exercise('extension')}`;};
plenary=function(){return `${puzzleHTML('exit')}${card(B('Validation and testing recall','Ingat pengesahan dan ujian','回顾验证与测试'),questionsFor('plenary'))}`;};
renderPage=function(){switch(state.page){case'read':return readPage();case'starter':return starterPage();case'types':return reflection(false);case'nested-read':return nestedReading();case'parsons':return puzzleHTML('main1')+puzzleHTML('main2');case'debug':return debugPage();case'program':return programPage();case'validation-read':return validationReading();case'validation':return validationPractice();case'pit':return pitStop();case'plenary':return plenary();case'extension':return extensionPage();case'submit':return saveCard()+`<a class="teams-link" href="https://teams.microsoft.com/" target="_blank" rel="noopener">${t('Open Microsoft Teams','Buka Microsoft Teams','打开 Microsoft Teams')} ↗</a>`;default:return '';}};
// Use the existing landing form without importing an unrelated project notebook.
welcome=originalWelcome;
const baseWelcome=welcome;
welcome=function(){return baseWelcome().replace('<p class="small">',`<p class="small">${t('Your name and class are saved only in this browser and included in your PDF. They are not sent to the live classroom.','Nama dan kelas hanya disimpan dalam pelayar ini untuk PDF. Maklumat ini tidak dihantar ke kelas langsung.','姓名和班级仅保存在此浏览器并用于 PDF，不发送到实时课堂。')} </p><p class="small">`).replace('<button class="primary wide" type="submit">',langControl()+'<button class="primary wide" type="submit">');};
report=function(){let out=`<article class="report-content"><h1>${bi(L.title)}</h1><p>Year 9 · Week 5 · ${esc(state.name)} · ${esc(state.className)}</p><p>WAGBA: ${bi(L.wagba)}</p>`;
 for(const p of PAGES){let body='';for(const q of questions.filter(q=>q.page===p[0]))if(val(q.id)!=='')body+=`<h3>${bi(q.prompt)}</h3>${q.code?codeBox(q.code):''}<p>${bi(q.options[Number(val(q.id))])}</p>${state.checked[q.id]?para(Number(val(q.id))===q.answer?B('Correct','Betul','正确'):B('Needs another attempt','Perlu cuba lagi','需要再尝试')):para(B('Not checked','Belum disemak','未检查'))}`;
 for(const puzzle of Object.values(PARSONS).filter(q=>q.page===p[0]))if(state.orders[puzzle.id])body+=`<h3>${bi(puzzle.title)}</h3>${codeBox(order(puzzle.id).map(n=>puzzle.blocks[n]).join('\n'))}${para(state.orderChecked[puzzle.id]?(ordered(puzzle.id)?B('Correct order','Susunan betul','顺序正确'):B('Keep practising','Terus berlatih','继续练习')):L.noEvidence)}`;
 for(const prog of Object.values(PROGRAMS).filter(q=>q.page===p[0]))if(state.code[prog.id]!==undefined||state.runs[prog.id]?.length){body+=`<h3>${bi(prog.title)}</h3>${codeBox(starterCode(prog.id))}`;for(const r of state.runs[prog.id]||[])body+=`<p>${esc(r.at)} · ${esc(r.status)}</p><pre>${esc(r.transcript+'\n'+r.error)}</pre>`;}
 if(p[0]==='types')body=CHECKS.map(([id,,label])=>val('start_'+id)?`<p>${bi(label)}: ${bi(L[val('start_'+id)])}</p>`:'').join('')+focusSummary('start');
 if(p[0]==='pit')body=CHECKS.map(([id])=>val('phase_'+id)?`<p>${bi(PIT_TOPICS[id])}: ${bi(L[val('phase_'+id)])}</p>`:'').join('')+phaseSummary();
 if(body)out+=`<h2>${bi(p[1])}</h2>${body}`;
 }return out+'</article>';};
importNotebook=function(raw){return validate(raw);};
backup=function(){save();download('Year9-Week5-notebook.json',JSON.stringify(state,null,2),'application/json');};
document.addEventListener('click',ev=>{const b=ev.target.closest('button');if(!b)return;if(b.dataset.walkCase){TUTOR_STATE[b.dataset.walkCase]={choice:Number(b.dataset.choice),step:0};document.getElementById('walk-'+b.dataset.walkCase).outerHTML=tutorial(b.dataset.walkCase);}else if(b.dataset.walk){const s=TUTOR_STATE[b.dataset.walk]||{choice:0,step:0};s.step=Number(b.dataset.step);TUTOR_STATE[b.dataset.walk]=s;document.getElementById('walk-'+b.dataset.walk).outerHTML=tutorial(b.dataset.walk);}});
const basicMCQ=mcq;
mcq=function(q){return basicMCQ(state.guided?{...q,prompt:q.short||q.prompt}:q).replace('</article>',(teacher?`<details class="teacher-model"><summary>${t('Teacher: answer','Guru: jawapan','教师：答案')}</summary>${para(q.options[q.answer])}${para(q.why)}</details>`:'')+'</article>');};
const basicPuzzle=puzzleHTML;
puzzleHTML=function(id){const p=PARSONS[id];return basicPuzzle(id).replace('</article>',(teacher?`<details class="teacher-model"><summary>${t('Teacher: correct order','Guru: susunan betul','教师：正确顺序')}</summary>${codeBox(p.blocks.join('\n'))}</details>`:'')+'</article>');};
render();
