'use strict';
// Week 5 content uses the saved-notebook and Python components from the project lesson.
Object.assign(L,{
 title:B('Decisions inside decisions','Keputusan dalam keputusan','判断中的判断'),
 wagba:B('Use nested selection and choose suitable validation checks and test data.','Gunakan pilihan bersarang dan pilih semakan pengesahan serta data ujian yang sesuai.','使用嵌套选择，并选择合适的数据验证和测试数据。'),
 knowledge:B('Recognise nested selection, validation checks and three types of test data.','Kenali pilihan bersarang, semakan pengesahan dan tiga jenis data ujian.','认识嵌套选择、数据验证和三类测试数据。'),
 skills:B('Arrange, debug and run nested Python. Match checks to data.','Susun, nyahpepijat dan jalankan Python bersarang. Padankan semakan dengan data.','排列、调试并运行嵌套 Python。为数据选择验证方法。'),
 understanding:B('Know when an inner decision runs and why different tests matter.','Fahami bila keputusan dalaman berjalan dan sebab ujian berbeza penting.','理解内层判断何时执行，以及不同测试的作用。')});
PAGES.splice(0,PAGES.length,
 ['read',B('Read first','Baca dahulu','先阅读'),B('One decision can lead to another','Satu keputusan membawa kepada keputusan lain','一个判断引出另一个判断'),'START'],
 ['starter',B('Do Now','Mula sekarang','课前练习'),B('Arrange it. Recognise it.','Susun. Kenal pasti.','排列代码，识别概念。'),'START'],
 ['types',B('Types of Learning','Jenis Pembelajaran','学习类型'),B('What will I practise today?','Apakah yang akan saya latih?','今天我要练习什么？'),'START'],
 ['nested-read',B('Read nested code','Baca kod bersarang','阅读嵌套代码'),B('Follow the route, line by line','Ikuti laluan, baris demi baris','逐行跟随程序路径'),'MAIN 1'],
 ['parsons',B('Arrange two programs','Susun dua atur cara','排列两个程序'),B('Turn each scenario into code','Tukar setiap situasi kepada kod','把情景变成代码'),'MAIN 1'],
 ['debug',B('Syntax & indentation','Sintaks & inden','语法与缩进'),B('Three small repairs','Tiga pembaikan kecil','修复三个小问题'),'MAIN 1'],
 ['program',B('Program it','Atur carakannya','动手编程'),B('Build your own nested decision','Bina keputusan bersarang anda','编写自己的嵌套判断'),'MAIN 1'],
 ['validation-read',B('Read: validation','Baca: pengesahan','阅读：数据验证'),B('What makes an input acceptable?','Apakah input yang boleh diterima?','什么输入符合规则？'),'MAIN 2'],
 ['validation',B('Choose the right check','Pilih semakan yang betul','选择正确的验证'),B('Match the check to the rule','Padankan semakan dengan peraturan','根据规则选择验证方法'),'MAIN 2'],
 ['pit',B('Learning Pit Stop','Hentian Pembelajaran','学习停靠站'),B('How confident do I feel?','Sejauh mana keyakinan saya?','我现在有多大信心？'),'REFLECT'],
 ['plenary',B('Plenary','Rumusan','总结'),B('Put today’s ideas together','Gabungkan idea hari ini','整合今天的学习'),'REFLECT'],
 ['extension',B('Competitive coding','Cabaran pengekodan','编程挑战'),B('Make the helpdesk more reliable','Jadikan meja bantuan lebih boleh dipercayai','让服务台程序更可靠'),'EXTEND'],
 ['submit',B('PDF submission','Hantar PDF','提交 PDF'),B('Save your learning. Submit to Teams.','Simpan pembelajaran. Hantar ke Teams.','保存学习成果，提交到 Teams。'),'SAVE']);
Object.assign(GROUPS,{'START':B('Get ready','Bersedia','准备开始'),'MAIN 1':B('Main Task 1 · Nested selection','Tugasan Utama 1 · Pilihan bersarang','主要任务 1 · 嵌套选择'),'MAIN 2':B('Main Task 2 · Validation','Tugasan Utama 2 · Pengesahan','主要任务 2 · 数据验证'),'REFLECT':B('Reflect & recall','Refleksi & ingat','反思与回顾'),'EXTEND':B('Use extra time','Gunakan masa tambahan','利用剩余时间'),'SAVE':B('Save & submit','Simpan & hantar','保存与提交')});
const nestedCode='desk_open = True\npeople_ahead = 2\nif desk_open:\n    if people_ahead == 0:\n        print("Ask now")\n    else:\n        print("Join the queue")\nelse:\n    print("Come back later")';
const timeCode='total_minutes = 12\nminutes_available = 12\nif minutes_available >= 0:\n    if total_minutes <= minutes_available:\n        print("Ask about help now")\n    else:\n        print("Arrange another time")\nelse:\n    print("Enter zero or more")';
const shortHint=B('Read the outer if first. Keep each else aligned with its matching if.','Baca if luar dahulu. Jajarkan setiap else dengan if pasangannya.','先读外层 if。每个 else 与对应的 if 对齐。');
for(const k of Object.keys(PARSONS))delete PARSONS[k];
function addPuzzle(id,page,title,scenario,blocks){puzzle(id,page,title,scenario,blocks,shortHint);}
addPuzzle('do1','starter',B('1 · Is help available?','1 · Adakah bantuan tersedia?','1 · 可以获得帮助吗？'),B('The desk is open. Nobody is waiting. Arrange the code to print Ask now. The values are supplied.','Meja dibuka. Tiada orang menunggu. Susun kod untuk mencetak Ask now. Nilai disediakan.','服务台开放，无人排队。排列代码，输出 Ask now。数值已给出。'),['desk_open = True\npeople_ahead = 0','if desk_open:','    if people_ahead == 0:\n        print("Ask now")','    else:\n        print("Join the queue")','else:\n    print("Come back later")']);
addPuzzle('do2','starter',B('2 · Bring the right equipment','2 · Bawa peralatan yang betul','2 · 带上正确的设备'),B('If the device is a laptop, check the charger. Otherwise ask for the device name. Here the charger is missing.','Jika peranti ialah laptop, semak pengecas. Jika tidak, tanya nama peranti. Di sini pengecas tiada.','如果是笔记本电脑，检查充电器；否则询问设备名称。这里没有充电器。'),['device = "laptop"\ncharger = False','if device == "laptop":','    if charger:\n        print("Bring both")','    else:\n        print("Find your charger")','else:\n    print("Tell us your device")']);
addPuzzle('main1','parsons',B('Scenario 1 · Booking','Situasi 1 · Tempahan','情景 1 · 预约'),B('A booked visitor is directed to Room A if it is open, or reception if it is closed. A visitor without a booking must book first. Predict the output for these values.','Pelawat bertempah pergi ke Room A jika dibuka, atau reception jika ditutup. Tanpa tempahan, tempah dahulu. Ramalkan output.','已预约的访客：Room A 开放则前往，否则去 reception。未预约则先预约。预测这些数值的输出。'),['booked = True\nroom_open = False','if booked:','    if room_open:\n        print("Room A")','    else:\n        print("Reception")','else:\n    print("Book first")']);
addPuzzle('main2','parsons',B('Scenario 2 · Loan a laptop','Situasi 2 · Pinjam laptop','情景 2 · 借笔记本电脑'),B('A pupil with permission may borrow a laptop if stock is above zero. Otherwise join the waiting list. Without permission, ask a teacher.','Murid dengan kebenaran boleh meminjam jika stok melebihi sifar. Jika tiada stok, sertai senarai menunggu. Tanpa kebenaran, tanya guru.','有许可且库存大于零时可以借用；无库存则加入等候名单。无许可时询问老师。'),['permission = True\nstock = 3','if permission:','    if stock > 0:\n        print("Borrow a laptop")','    else:\n        print("Join the waiting list")','else:\n    print("Ask a teacher")']);
addPuzzle('exit','plenary',B('Final code check','Semakan kod akhir','最后的代码检查'),B('If a ticket is valid, check whether it is urgent. Otherwise ask for a new ticket. Arrange all three routes.','Jika tiket sah, semak sama ada mendesak. Jika tidak sah, minta tiket baharu. Susun ketiga-tiga laluan.','工单有效时检查是否紧急；无效时申请新工单。排列三条路径。'),['valid_ticket = True\nurgent = False','if valid_ticket:','    if urgent:\n        print("Priority desk")','    else:\n        print("Normal queue")','else:\n    print("Request a new ticket")']);
STARTER.splice(0);PLENARY.splice(0);
const QUESTION_SETS={};
function ask(page,id,area,prompt,code,options,answer,why){const q=Q(id,area,prompt,code,options,answer,why);q.page=page;(page==='plenary'?PLENARY:STARTER).push(q);(QUESTION_SETS[page]??=[]).push(q);}
const yesno=[B('Yes','Ya','是'),B('No','Tidak','否')];
const checksNames=[B('Presence','Kehadiran','非空验证'),B('Type','Jenis','类型验证'),B('Range','Julat','范围验证'),B('Length','Panjang','长度验证'),B('Format','Format','格式验证')];
const testNames=[B('Normal','Normal','正常数据'),B('Boundary','Sempadan','边界数据'),B('Erroneous','Salah','错误数据')];
ask('read','r1','K',B('What is nested selection?','Apakah pilihan bersarang?','什么是嵌套选择？'),'', [B('A decision inside another decision','Keputusan dalam keputusan lain','判断中包含另一个判断'),B('Printing twice','Mencetak dua kali','输出两次'),B('Two unrelated variables','Dua pemboleh ubah tidak berkaitan','两个不相关的变量')],0,shortHint);
ask('read','r2','U',B('If desk_open is False, is the inner queue check reached?','Jika desk_open ialah False, adakah semakan baris gilir dicapai?','desk_open 为 False 时，会执行内层排队判断吗？'),'',yesno,1,B('The outer else runs. The inner if is skipped.','else luar berjalan. if dalaman dilangkau.','执行外层 else，跳过内层 if。'));
ask('read','r3','K',B('Validation checks whether data…','Pengesahan menyemak sama ada data…','数据验证检查数据是否……'),'', [B('Follows the rules','Mematuhi peraturan','符合规则'),B('Is definitely true','Pasti benar','一定真实')],0,B('An allowed value can still be an inaccurate answer.','Nilai dibenarkan masih boleh tidak tepat.','符合规则的数值仍可能不真实。'));
ask('read','r4','K',B('Tickets must be 1–10. Which value is normal data?','Tiket mesti 1–10. Nilai manakah data normal?','工单数必须为 1–10，哪个是正常数据？'),'', ['5','0','hello'],0,B('5 is a typical valid value inside the range.','5 ialah nilai sah biasa dalam julat.','5 是范围内的典型有效值。'));
ask('read','r5','U',B('Which set checks around the upper limit of 10?','Set manakah menguji sekitar had atas 10?','哪组数据检查上限 10 附近的情况？'),'', ['3, 4, 5','9, 10, 11','20, 30, 40'],1,B('Try just below, at and just above the limit. 11 should be rejected.','Cuba di bawah, pada dan di atas had. 11 mesti ditolak.','测试稍低于、等于和稍高于上限的值。11 应被拒绝。'));
ask('starter','s1','K',B('Which term means a decision inside another decision?','Istilah manakah bermaksud keputusan dalam keputusan lain?','哪个术语表示判断中的判断？'),'', [B('Nested selection','Pilihan bersarang','嵌套选择'),B('Assignment','Umpukan','赋值'),B('Output','Output','输出')],0,shortHint);
ask('starter','s2','K',B('Which check makes sure an answer is not blank?','Semakan manakah memastikan jawapan tidak kosong?','哪种验证确保答案不为空？'),'',checksNames,0,B('A presence check looks for a supplied value.','Semakan kehadiran memastikan nilai diberi.','非空验证检查是否提供了值。'));
ask('starter','s3','S',B('Minutes must be 0–60. Choose the check.','Minit mesti 0–60. Pilih semakan.','分钟数必须为 0–60。选择验证方法。'),'',checksNames,2,B('A range check compares a number with allowed limits.','Semakan julat membandingkan nombor dengan had dibenarkan.','范围验证比较数值与允许的上下限。'));
ask('starter','s4','S',B('Choose a condition that allows 0 to 60 inclusive.','Pilih syarat yang membenarkan 0 hingga 60 termasuk had.','选择允许 0 到 60（含端点）的条件。'),'', ['0 <= minutes <= 60','0 < minutes < 60','minutes > 60'],0,B('<= includes both endpoints.','<= termasuk kedua-dua hujung.','<= 包含两个端点。'));
ask('starter','s5','U',B('Why is the inner decision indented?','Mengapakah keputusan dalaman berinden?','为什么内层判断需要缩进？'),'', [B('It belongs to the outer branch','Ia milik cabang luar','它属于外层分支'),B('It makes the text shorter','Ia memendekkan teks','为了让文本更短')],0,shortHint);
ask('starter','s6','U',B('An allowed ticket count is 1–10. Does passing validation prove the count is true?','Bilangan tiket dibenarkan ialah 1–10. Adakah lulus pengesahan membuktikan bilangannya benar?','工单数允许 1–10。通过验证能证明人数真实准确吗？'),'',yesno,1,B('The check proves only that the value follows this rule.','Semakan hanya membuktikan nilai mematuhi peraturan ini.','验证只能说明数值符合这条规则。'));
ask('nested-read','n1','U',B('When is an inner if reached?','Bilakah if dalaman dicapai?','什么时候执行内层 if？'),'', [B('When its containing branch runs','Apabila cabang yang mengandunginya berjalan','当包含它的分支被执行时'),B('Every time the program runs','Setiap kali atur cara berjalan','每次程序运行时')],0,shortHint);
ask('nested-read','n2','S',B('Total is 12 and available time is 11. Which output?','Jumlah 12 dan masa tersedia 11. Apakah output?','总时间 12，可用时间 11。输出是什么？'),'', ['Ask about help now','Arrange another time','Enter zero or more'],1,B('The number is allowed, but 12 <= 11 is False.','Nombor dibenarkan, tetapi 12 <= 11 ialah False.','输入有效，但 12 <= 11 为 False。'));
ask('nested-read','n3','K',B('Which else belongs to an if?','else manakah berpasangan dengan if?','哪个 else 与 if 对应？'),'', [B('The one at the same indentation level','Yang pada aras inden sama','同一缩进层级的 else'),B('Always the last else','Sentiasa else terakhir','总是最后一个 else')],0,shortHint);
ask('validation-read','v1','K',B('A ticket code must have exactly 6 characters. Which check?','Kod tiket mesti tepat 6 aksara. Semakan mana?','工单代码必须恰好 6 个字符。用哪种验证？'),'',checksNames,3,B('Length counts characters. It does not check the pattern.','Panjang mengira aksara, bukan coraknya.','长度验证计算字符数，不检查字符排列模式。'));
ask('validation-read','v2','K',B('A code must start with HD- followed by three digits. Which check?','Kod mesti bermula HD- diikuti tiga digit. Semakan mana?','代码必须为 HD- 后跟三位数字。用哪种验证？'),'',checksNames,4,B('Format checks the required pattern, such as HD-204.','Format menyemak corak seperti HD-204.','格式验证检查规定模式，例如 HD-204。'));
ask('validation-read','v3','U',B('Why check the type before doing arithmetic?','Mengapa semak jenis sebelum mengira?','为什么计算前要检查类型？'),'', [B('Text such as two cannot be used as an integer','Teks seperti two tidak boleh digunakan sebagai integer','two 这样的文本不能直接当整数使用'),B('All text is unsafe','Semua teks tidak selamat','所有文本都不安全')],0,B('The check depends on the job. Names need text; counts need integers.','Semakan bergantung pada tugas. Nama memerlukan teks; bilangan memerlukan integer.','验证取决于用途：名字需要文本，计数需要整数。'));
for(const [i,name,meaning] of [
 [0,'Presence',B('An answer must be supplied.','Jawapan mesti diberi.','必须填写答案。')],
 [1,'Type',B('The value must be a whole number.','Nilai mesti nombor bulat.','数值必须为整数。')],
 [2,'Range',B('The number must be between stated limits.','Nombor mesti dalam had dinyatakan.','数值必须在规定上下限之间。')],
 [3,'Length',B('The text must have a stated number of characters.','Teks mesti mempunyai bilangan aksara ditetapkan.','文本必须具有规定的字符数。')],
 [4,'Format',B('The text must follow a stated pattern.','Teks mesti mengikut corak ditetapkan.','文本必须符合规定模式。')]]) ask('validation','m'+i,'K',meaning,'',checksNames,i,B('Match the meaning to the check in the table above.','Padankan maksud dengan semakan dalam jadual di atas.','对照上方表格，匹配含义和验证方法。'));
ask('validation','a1','S',B('A help request cannot have an empty description. Choose the check.','Permintaan bantuan tidak boleh mempunyai penerangan kosong. Pilih semakan.','求助描述不能为空。选择验证。'),'',checksNames,0,B('Presence rejects an empty answer.','Kehadiran menolak jawapan kosong.','非空验证拒绝空答案。'));
ask('validation','a2','S',B('The queue count is already an integer. It must be 0–20. What additional check is needed?','Bilangan sudah integer. Ia mesti 0–20. Apakah semakan tambahan?','人数已是整数，还必须在 0–20 之间。需要增加什么验证？'),'',checksNames,2,B('The type is already checked. Now check its range.','Jenis sudah disemak. Kini semak julat.','类型已检查，现在检查范围。'));
ask('validation','a3','S',B('An ID has six characters, but AB204X does not match HD- plus three digits. What check finds this?','ID ada enam aksara, tetapi AB204X tidak sepadan HD- dan tiga digit. Semakan mana?','AB204X 有六个字符，但不符合 HD- 加三位数字。哪种验证能发现？'),'',checksNames,4,B('Correct length does not guarantee correct format.','Panjang betul tidak menjamin format betul.','长度正确并不代表格式正确。'));
ask('validation','a4','U',B('For integers 0–20, why test 19, 20 and 21?','Bagi integer 0–20, mengapa uji 19, 20 dan 21?','对于 0–20 的整数，为什么测试 19、20、21？'),'', [B('They check around the upper boundary','Ia menguji sekitar sempadan atas','它们检查上边界附近'),B('They should all be accepted','Semua mesti diterima','它们都应被接受')],0,B('19 and 20 are accepted. 21 is rejected; it is also erroneous.','19 dan 20 diterima. 21 ditolak; ia juga data salah.','19 和 20 被接受；21 被拒绝，它也是错误数据。'));
ask('validation','a5','K',B('For a count of 0–20, classify hello.','Untuk bilangan 0–20, kelaskan hello.','对于 0–20 的人数，hello 属于哪类数据？'),'',testNames,2,B('It cannot be used as the required integer.','Ia tidak boleh digunakan sebagai integer diperlukan.','它不能作为所需整数使用。'));
ask('validation','a6','K',B('For a count of 0–20, classify 8 as a typical valid value.','Untuk bilangan 0–20, kelaskan 8 sebagai nilai sah biasa.','对于 0–20 的人数，8 是典型有效值，属于哪类数据？'),'',testNames,0,B('It is comfortably inside the allowed range.','Ia berada dalam julat dibenarkan.','它在允许范围内部。'));
ask('plenary','e1','S',B('A user leaves their name blank. Which check is needed?','Pengguna membiarkan nama kosong. Semakan mana?','用户没有填写姓名。需要哪种验证？'),'',checksNames,0,B('Presence checks that something was entered.','Kehadiran menyemak sesuatu telah dimasukkan.','非空验证检查是否有输入。'));
ask('plenary','e2','U',B('Allowed minutes are 0–60. Which set tests the lower boundary?','Minit dibenarkan 0–60. Set mana menguji sempadan bawah?','分钟数允许 0–60。哪组测试下边界？'),'', ['-1, 0, 1','20, 30, 40','58, 59, 60'],0,B('-1 is rejected. 0 and 1 are accepted.','-1 ditolak. 0 dan 1 diterima.','拒绝 -1，接受 0 和 1。'));
ask('plenary','e3','U',B('Passing a format check proves that a ticket is real.','Lulus semakan format membuktikan tiket benar.','通过格式验证能证明工单真实存在。'),'',yesno,1,B('It only proves that the text matches the required pattern.','Ia hanya membuktikan teks mengikut corak diperlukan.','它只能说明文本符合规定模式。'));
CHECKS.splice(0,CHECKS.length,
 ['k1','K',B('Recognise nested selection','Kenali pilihan bersarang','识别嵌套选择'),'s1','core'],
 ['k2','K',B('Recognise validation checks','Kenali semakan pengesahan','识别验证方法'),'s2','extension'],
 ['s1','S',B('Arrange nested code','Susun kod bersarang','排列嵌套代码'),'s3','gap'],
 ['s2','S',B('Choose a suitable validation check','Pilih semakan pengesahan sesuai','选择适当验证'),'s4','extension'],
 ['u1','U',B('Know when an inner decision runs','Fahami bila keputusan dalaman berjalan','理解内层判断何时执行'),'s5','core'],
 ['u2','U',B('Know what validation can and cannot show','Fahami had pengesahan','理解验证的作用与局限'),'s6','extension']);
for(const [id,,label] of CHECKS)PIT_TOPICS[id]=label;
PIT_TOPICS.u2=B('Why boundary and erroneous tests matter','Mengapa ujian sempadan dan salah penting','为什么边界和错误测试很重要');
for(const k of Object.keys(PROGRAMS))delete PROGRAMS[k];
const repair='desk_open = True\npeople_ahead = 0\nif desk_open:\n    if people_ahead == 0:\n        print("Ask now")\n    else:\n        print("Join the queue")\nelse:\n    print("Come back later")\n';
program('gap','debug',B('1 · Complete the missing condition','1 · Lengkapkan syarat','1 · 补全条件'),B('The desk is open. Nobody is ahead. Replace ___ so Ask now is printed only when people_ahead equals zero.','Meja dibuka. Tiada orang di hadapan. Ganti ___ supaya Ask now dicetak hanya apabila people_ahead sama dengan sifar.','服务台开放，无人排队。替换 ___，仅当 people_ahead 等于零时输出 Ask now。'),repair.replace('people_ahead == 0','people_ahead ___ 0'),repair.replace('people_ahead == 0','people_ahead ___ 0'),repair,[[[],'Ask now']]);
program('syntax','debug',B('2 · Repair the syntax','2 · Baiki sintaks','2 · 修复语法'),B('Python cannot start: a decision line is missing punctuation. Repair it, then run. Expected: Ask now.','Python tidak dapat bermula: baris keputusan kurang tanda baca. Baiki dan jalankan. Dijangka: Ask now.','程序无法开始：判断行缺少标点。修复并运行，应输出 Ask now。'),repair.replace('if desk_open:','if desk_open'),repair.replace('if desk_open:','if desk_open'),repair,[[[],'Ask now']]);
program('indent','debug',B('3 · Repair the indentation','3 · Baiki inden','3 · 修复缩进'),B('The Ask now print belongs inside the inner if. Add the correct spaces, then run. Use eight spaces on that print line.','print Ask now berada dalam if dalaman. Tambah ruang yang betul dan jalankan. Guna lapan ruang pada baris print itu.','Ask now 的 print 属于内层 if。添加正确缩进并运行。该 print 前需要八个空格。'),repair.replace('        print("Ask now")','    print("Ask now")'),repair.replace('        print("Ask now")','    print("Ask now")'),repair,[[[],'Ask now']]);
const core='permission = input("Permission (yes/no): ").strip().lower()\nif permission == "yes":\n    stock = int(input("Laptops available: "))\n    if stock > 0:\n        print("Borrow a laptop")\n    else:\n        print("Join the waiting list")\nelse:\n    print("Ask a teacher")\n';
program('core','program',B('Your laptop loan adviser','Penasihat pinjaman laptop anda','你的电脑借用建议程序'),B('Ask for permission. Only if the answer is yes, ask for stock. If stock is above zero, allow a loan. Otherwise show the waiting-list message. Without permission, print Ask a teacher. Use whole numbers zero or more for this task.','Tanya kebenaran. Hanya jika yes, tanya stok. Jika stok melebihi sifar, benarkan pinjaman. Jika tidak, papar senarai menunggu. Tanpa kebenaran, cetak Ask a teacher. Guna nombor bulat sifar atau lebih.','先询问许可。仅当回答 yes 时询问库存。库存大于零则允许借用，否则加入等候名单。没有许可则输出 Ask a teacher。本题输入零或正整数。'), 'permission = input("Permission (yes/no): ").strip().lower()\n# Add the outer decision.\n# Ask for stock inside the yes branch.\n# Add the inner decision and all three outputs.\n',core.replace('permission == "yes"','permission ___ "yes"').replace('stock > 0','stock ___ 0'),core,[[['yes','2'],'Borrow a laptop'],[['yes','0'],'Join the waiting list'],[['no'],'Ask a teacher']]);
const ext='answer = input("Tickets (1-10): ").strip()\nif answer == "":\n    print("Enter a ticket count")\nelse:\n    try:\n        tickets = int(answer)\n        if 1 <= tickets <= 10:\n            if tickets <= 5:\n                print("Use the quick desk")\n            else:\n                print("Use the group desk")\n        else:\n            print("Enter 1 to 10")\n    except ValueError:\n        print("Enter a whole number")\n';
program('extension','extension',B('Ticket desk challenge','Cabaran meja tiket','工单服务台挑战'),B('Accept 1–10 whole tickets. Send 1–5 to the quick desk and 6–10 to the group desk. Reject blank, text, decimals and out-of-range values. Complete the two conditions in the starter, then test every route.','Terima 1–10 tiket bulat. Hantar 1–5 ke quick desk dan 6–10 ke group desk. Tolak kosong, teks, perpuluhan dan nilai luar julat. Lengkapkan dua syarat dan uji setiap laluan.','接受 1–10 的整数工单数。1–5 去 quick desk，6–10 去 group desk。拒绝空白、文本、小数和超范围值。补全两个条件并测试所有路径。'),ext.replace('1 <= tickets <= 10','___').replace('tickets <= 5','___'),ext.replace('1 <= tickets <= 10','1 <= tickets <= ___').replace('tickets <= 5','tickets <= ___'),ext,[[['3'],'Use the quick desk'],[['5'],'Use the quick desk'],[['6'],'Use the group desk'],[['10'],'Use the group desk'],[['0'],'Enter 1 to 10'],[['11'],'Enter 1 to 10'],[['two'],'Enter a whole number'],[['2.5'],'Enter a whole number'],[[''],'Enter a ticket count']]);
for(const [id,p]of Object.entries(PROGRAMS))GUIDED_TASKS[id]=p.task;

Object.assign(GUIDED_TASKS,{
 gap:B('Choose ==. Replace ___. Run. Look for Ask now.','Pilih ==. Ganti ___. Jalankan. Cari Ask now.','选择 ==，替换 ___，运行。查看 Ask now。'),
 syntax:B('Find if desk_open. Add : at the end. Run.','Cari if desk_open. Tambah : di hujung. Jalankan.','找到 if desk_open，在末尾添加冒号 :，运行。'),
 indent:B('Find print("Ask now"). Put eight spaces before print. Run.','Cari print("Ask now"). Letak lapan ruang sebelum print. Jalankan.','找到 print("Ask now")，在 print 前加八格，运行。'),
 core:B('Fill the first gap with ==. Fill the second with >. Run. Type yes, then 2. Next run: type yes, then 0. Last run: type no.','Isi tempat pertama dengan ==. Isi kedua dengan >. Jalankan. Taip yes, kemudian 2. Larian seterusnya: yes, kemudian 0. Akhir: no.','第一个空填 ==，第二个空填 >。运行，输入 yes，再输入 2。下次运行输入 yes、0。最后运行输入 no。'),
 extension:B('First gap: 10. Second gap: 5. Run with 3. Run again with 11. Which answer is rejected?','Tempat pertama: 10. Kedua: 5. Jalankan dengan 3. Jalankan lagi dengan 11. Jawapan mana ditolak?','第一空填 10，第二空填 5。输入 3 运行，再输入 11 运行。哪个输入被拒绝？')});
const SHORT_PROMPTS={
 r2:B('Desk closed: does Python check the queue?','Meja tutup: adakah Python semak barisan?','服务台关闭时，Python 会检查队伍吗？'),
 r4:B('Allowed: 1–10. Choose a normal value.','Dibenarkan: 1–10. Pilih nilai normal.','允许 1–10，选一个正常值。'),
 r5:B('The limit is 10. Which values test near 10?','Had ialah 10. Nilai mana menguji dekat 10?','上限为 10，哪些值测试 10 附近？'),
 s3:B('Allowed minutes: 0–60. Which check?','Minit dibenarkan: 0–60. Semakan mana?','分钟数允许 0–60，用哪种验证？'),
 s4:B('Allow 0 and 60 too. Which condition?','Benarkan 0 dan 60 juga. Syarat mana?','也要允许 0 和 60，选哪个条件？'),
 s6:B('The number is allowed. Must it be true?','Nombor dibenarkan. Mestikah ia benar?','数字符合规则，就一定真实吗？'),
 n2:B('Need 12 minutes. Have 11. Which message?','Perlu 12 minit. Ada 11. Mesej mana?','需要 12 分钟，只有 11 分钟。输出哪条消息？'),
 v1:B('Exactly 6 characters. Which check?','Tepat 6 aksara. Semakan mana?','恰好 6 个字符，用哪种验证？'),
 v2:B('Must look like HD-123. Which check?','Mesti seperti HD-123. Semakan mana?','必须像 HD-123 这样，用哪种验证？'),
 v3:B('Why check for a whole number before maths?','Mengapa semak nombor bulat sebelum mengira?','为什么计算前要检查是不是整数？'),
 a1:B('The description is blank. Which check?','Penerangan kosong. Semakan mana?','描述为空，用哪种验证？'),
 a2:B('Already an integer. Must be 0–20. Which check next?','Sudah integer. Mesti 0–20. Semakan seterusnya?','已经是整数，还必须在 0–20 内。接着用哪种验证？'),
 a3:B('Need HD-123. Got AB204X. Both have 6 characters. Which check finds the error?','Perlu HD-123. Dapat AB204X. Kedua-duanya 6 aksara. Semakan mana mengesan ralat?','需要 HD-123 这样的代码，却收到 AB204X。都有六个字符。哪种验证能找出错误？'),
 a4:B('Allowed: 0–20. Why try 19, 20, 21?','Dibenarkan: 0–20. Mengapa cuba 19, 20, 21?','允许 0–20，为什么测试 19、20、21？'),
 a5:B('Need a count. User types hello. What test data is this?','Perlu bilangan. Pengguna menaip hello. Jenis data ujian apa?','需要人数，却输入 hello。这是哪类测试数据？'),
 a6:B('Allowed: 0–20. A typical value is 8. What type of test?','Dibenarkan: 0–20. Nilai biasa ialah 8. Jenis ujian apa?','允许 0–20，典型值为 8。这是哪类测试？'),
 e2:B('Allowed: 0–60. Test near zero. Which set?','Dibenarkan: 0–60. Uji dekat sifar. Set mana?','允许 0–60，要测试零附近。选哪组？')};
for(const q of [...STARTER,...PLENARY])q.short=SHORT_PROMPTS[q.id]||q.prompt;
PROGRAMS.extension.tests.push([['1'],'Use the quick desk'],[['9'],'Use the group desk'],[['-1'],'Enter 1 to 10']);
