(function(){
  'use strict';
  const element=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=String(text);if(cls)e.className=cls;return e;};
  const node=(tag,text,cls)=>element(tag,text,cls);
  function download(blob,name){const url=URL.createObjectURL(blob),a=element('a');a.href=url;a.download=name;a.rel='noopener';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
  function chunks(value){const text=String(value??'');if(text.length<=1000)return [text];const parts=[];let remaining=text;while(remaining.length>1000){let cut=remaining.lastIndexOf(' ',1000);if(cut<500)cut=1000;parts.push(remaining.slice(0,cut));remaining=remaining.slice(cut);}parts.push(remaining);return parts;}
  function blocks(state,photos){const all=[];const title=t=>all.push(node('h2',t));
    function answer(label,value){for(const [i,part] of chunks(value).entries()){const b=node('div',undefined,'report-block');b.append(node('h3',label+(i?' (continued)':'')),node('p',part));all.push(b);}}
    title('Week 2 Theory — Plan a school journey');answer('Student',state.name+' | '+state.className);answer('WAGBA',Lesson.goals.wagba);['knowledge','skills','understanding'].forEach(k=>answer(k[0].toUpperCase()+k.slice(1),Lesson.goals[k]));
    answer('Lesson evidence','This report contains attempted work, not a formal grade. Model steps and supported responses are identified. Submit this PDF to Teams → Week 2 Theory.');
    const map=node('img',undefined,'report-map');map.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(schoolMap());map.alt='Practice route map';all.push(map);
    title('Understanding checks');for(const [id,result]of Object.entries(state.quizzes)){const q=Lesson.questions[id];if(!q)continue;const attempt=result.choice!==undefined?q.choices[result.choice]:'Not selected';answer(q.title,'Latest answer: '+attempt+'\n'+(result.accepted?(result.supported?'Completed with explanation support.':'Latest check correct independently.'):'Not yet completed.')+'\nAttempts: '+(result.attempts||[]).map((a,i)=>(i+1)+'. '+q.choices[a.choice]+' — '+(a.correct?'correct':'try again')).join(' | '));}
    title('Planning and reflection');for(const [id,value]of Object.entries(state.answers)){if(!String(value||'').trim()||/^step[3-8]$/.test(id)||id.startsWith('extension')||id==='deviceChoice')continue;answer(Lesson.labels[id]||id,value);}
    title('My final pseudocode');answer('START','At the Main Entrance, facing Reception.');Lesson.route(state).forEach((s,i)=>answer('Step '+(i+1)+(i<2?' — supplied model':''),s));answer('END','Outside CS Room C1.');
    title('My flowchart');all.push(node('div','START','report-flow end'));Lesson.route(state).forEach((s,i)=>{const b=node('div',undefined,'report-block');b.append(node('p','↓','report-note'),node('div',(i+1)+'. '+s,'report-flow'));all.push(b);});all.push(node('div','↓ END','report-flow end'));
    if(state.revisions.length){title('Changes after testing');for(const r of state.revisions)answer('Step '+r.step.replace('step',''),'Before: '+r.before+'\nAfter: '+r.after+'\nReason: '+(r.reason||'Not recorded'));}
    const extensions=Object.entries(state.answers).filter(([k,v])=>k.startsWith('extension')&&String(v).trim());if(extensions.length||state.extensionVisits.length){title('Optional extension');answer('Participation',state.extensionVisits.length+' challenge visit(s). Opening a challenge does not mean it was completed.');extensions.forEach(([k,v])=>answer(Lesson.labels[k],v));}
    if(photos.length){title('Optional paper evidence');for(const photo of photos){const b=node('div',undefined,'report-block'),img=node('img',undefined,'report-photo');img.src=photo.data;img.alt='Student paper evidence';b.append(img);all.push(b);}}
    if(state.legacy){title('Preserved work from the earlier lesson version');answer('About this section','These answers were saved before the redesign. The previous question identifiers are retained where the full wording is unavailable. They are not answers to the redesigned tasks.');for(const [k,v]of Object.entries(state.legacy.answers||{}))if(String(v??'').trim())answer(k,String(v));(state.legacy.algorithmSteps||[]).forEach((v,i)=>{if(v)answer('Previous route step '+(i+1),v);});}
    title('Completion and support');const core=Lesson.cards.filter(c=>!['extension','submit'].includes(c.id));answer('Lesson progress',core.filter(c=>state.completed.includes(c.id)).length+' of '+core.length+' core cards marked complete. Progress is not a grade.');answer('Questions completed with support',Object.entries(state.quizzes).filter(([,q])=>q.supported).map(([id])=>Lesson.questions[id]?.title||id).join('\n')||'None recorded.');answer('Remaining work',core.flatMap(c=>Lesson.missing(state,c.id).map(k=>Lesson.answerLabel(k))).join('\n')||'All required responses attempted.');answer('Submission','After saving, attach this PDF to Teams → Assignments → Week 2 Theory and tap Turn in. The app cannot verify Teams submission. You do not need another PDF after confirming submission.');
    return all;
  }
  async function build(state,photos,preparing=false){
    const host=document.getElementById('report-root');host.replaceChildren();document.body.classList.toggle('report-preparing',preparing);document.body.classList.toggle('report-open',!preparing);
    if(document.fonts)await document.fonts.ready;
    const pages=[];let area;
    function page(){const p=node('section',undefined,'report-page');p.append(node('div','YEAR 7 · WEEK 2 THEORY · '+state.name+' · '+state.className,'report-header'));area=node('div',undefined,'report-content');p.append(area);const footer=node('div',undefined,'report-footer');footer.append(node('span','Created '+new Date().toLocaleString()),node('span','Page '+(pages.length+1)));p.append(footer);host.append(p);pages.push(p);}
    page();
    for(const block of blocks(state,photos)){area.append(block);for(const img of block.matches('img')?[block]:Array.from(block.querySelectorAll('img'))){if(!img.complete)await new Promise(resolve=>{img.onload=resolve;img.onerror=resolve;});}
      if(area.scrollHeight>area.clientHeight){block.remove();page();area.append(block);}
      if(area.scrollHeight>area.clientHeight)throw Error('Report block exceeds a page');
    }
    pages.forEach((p,i)=>p.querySelector('.report-footer').lastChild.textContent=`Page ${i+1} of ${pages.length}`);
    return pages;
  }
  function close(){document.body.classList.remove('report-open','report-preparing');document.getElementById('report-root').replaceChildren();document.getElementById('card-title')?.focus();}
  async function preview(state,photos){try{await build(state,photos);const bar=node('div',undefined,'report-toolbar');const back=node('button','Back to my lesson');back.onclick=close;const print=node('button','Print / save fallback');print.onclick=()=>window.print();bar.append(back,print);document.getElementById('report-root').prepend(bar);window.scrollTo(0,0);back.focus();}catch{close();alert('The report preview could not open. Your answers are unchanged. Try again or save a lesson backup.');}}
  async function make(state,photos){try{if(!window.jspdf?.jsPDF||!window.html2canvas)throw Error('PDF library unavailable');const pages=await build(state,photos,true),pdf=new jspdf.jsPDF({unit:'mm',format:'a4',compress:true});for(let i=0;i<pages.length;i++){const canvas=await html2canvas(pages[i],{scale:1.5,backgroundColor:'#ffffff',logging:false,windowWidth:1000,scrollX:0,scrollY:0});if(i)pdf.addPage();pdf.addImage(canvas.toDataURL('image/jpeg',.94),'JPEG',0,0,210,297,undefined,'FAST');canvas.width=1;canvas.height=1;}
      pdf.setProperties({title:'Year 7 Week 2 Theory',subject:'Student lesson evidence'});return new File([pdf.output('arraybuffer')],Lesson.filename(state),{type:'application/pdf'});
    }finally{close();}}
  async function print(state,photos){await preview(state,photos);if(document.body.classList.contains('report-open'))window.print();}
  function db(){return new Promise((resolve,reject)=>{const r=indexedDB.open('y7-w2-theory-evidence-v4',1);r.onupgradeneeded=()=>r.result.createObjectStore('profiles');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
  async function load(key){const database=await db();return new Promise((resolve,reject)=>{const tx=database.transaction('profiles','readonly'),r=tx.objectStore('profiles').get(key);r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error);tx.oncomplete=()=>database.close();});}
  async function save(key,photos){const database=await db();return new Promise((resolve,reject)=>{const tx=database.transaction('profiles','readwrite');tx.objectStore('profiles').put(photos,key);tx.oncomplete=()=>{database.close();resolve();};tx.onerror=()=>{database.close();reject(tx.error);};});}
  async function compress(file){const url=URL.createObjectURL(file);try{const img=await new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=reject;image.src=url;});const scale=Math.min(1,1400/img.width,1400/img.height),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',.82);}finally{URL.revokeObjectURL(url);}}
  window.Evidence={load,save,compress};window.Report={download,preview,print,make,blocks,close};
})();
