window.Lesson={
 id:'year8-t1w3-theory-v1',title:'Smart Badge: Remembering and Changing Information',
 topic:'Variables, data types and meaningful identifiers',
 wagba:'We are getting better at storing and tracing values using suitable data types and meaningful identifiers.',
 knowledge:['A variable has a name and refers to a value.','Assignment uses = to give a variable a value.','A string represents text; an integer represents a whole number.'],
 skills:['Identify a variable’s name, value and data type.','Trace how values change as a program runs.','Modify a short program using meaningful variable names.'],
 understanding:['A variable’s value can change during a program.','Assignment uses the value on the right to update the variable on the left.','Quotation marks affect how Python interprets text and numbers.'],
 challenge:'Explain what changes—and what stays the same—when a program updates or copies a value.',
 keywords:['variable','value','assignment','identifier','string','integer','trace table'],
 stages:['Do Now','Types of Learning','Main Task 1','Main Task 2','Extension','Learning Pitstop','Plenary','Review & export'],
 languages:{en:'English only',zh:'English + 中文',ko:'English + 한국어',ms:'English + Bahasa Melayu'},
 glossary:[
 ['variable','A name that refers to a value.','变量','변수','pemboleh ubah'],
 ['value','The information a variable currently refers to.','值','값','nilai'],
 ['assignment','Use = to give a variable the value on the right.','赋值','대입','umpukan nilai'],
 ['identifier','A name used in code, such as badge_name.','标识符（名称）','식별자（이름）','pengecam (nama)'],
 ['string','Text inside quotation marks, including text such as "2".','字符串','문자열','rentetan'],
 ['integer','A whole number, such as -2, 0 or 5.','整数','정수','integer / nombor bulat'],
 ['trace table','A record of values after each instruction runs.','跟踪表','추적표','jadual surihan']
 ],
 support:{
 entry:{zh:'选择你需要的语言支持。英语内容会保留，并在每张学习卡旁显示中文提示。你的姓名、班级和学习记录只保存在这台设备的浏览器中。',ko:'필요한 언어 지원을 선택하세요. 영어 내용 옆에 한국어 안내가 표시됩니다. 이름, 반, 학습 기록은 이 기기의 브라우저에만 저장됩니다.',ms:'Pilih sokongan bahasa. Kandungan bahasa Inggeris dikekalkan dengan panduan ringkas di setiap kad. Nama, kelas dan kemajuan disimpan dalam pelayar peranti ini sahaja.'},
 starter:{zh:'先独立作答。这个徽章需要记住昵称和分数。预测代码显示什么，然后判断昵称应是文字还是数字。不需要连接 micro:bit。',ko:'먼저 혼자 답하세요. 배지는 별명과 점수를 기억해야 합니다. 코드의 출력 결과를 예상하고 별명이 글자인지 숫자인지 생각해 보세요. micro:bit 연결은 필요 없습니다.',ms:'Jawab sendiri dahulu. Lencana perlu menyimpan nama panggilan dan skor. Ramalkan output, kemudian tentukan sama ada nama panggilan ialah teks atau nombor. Tidak perlu menyambung micro:bit.'},
 types:{zh:'知识：记住术语。技能：逐行跟踪数值。理解：解释数值为什么变化。请选择一种今天要使用的学习策略。',ko:'지식: 용어 기억하기. 기능: 한 줄씩 값 추적하기. 이해: 값이 변하는 이유 설명하기. 오늘 사용할 학습 전략 하나를 선택하세요.',ms:'Pengetahuan: ingat istilah. Kemahiran: jejak nilai baris demi baris. Kefahaman: jelaskan sebab nilai berubah. Pilih satu strategi untuk hari ini.'},
 concepts:{zh:'变量是引用一个值的名称。= 表示赋值：先计算右边，再把结果赋给左边的名称。"2" 是文字，2 是整数。变量名拼写和大小写必须一致。',ko:'변수는 값을 가리키는 이름입니다. =는 대입입니다. 오른쪽 값을 먼저 구한 뒤 왼쪽 이름에 대입합니다. "2"는 문자열이고 2는 정수입니다. 변수 이름의 철자와 대소문자를 일치시키세요.',ms:'Pemboleh ubah ialah nama yang merujuk kepada nilai. = memberikan nilai di sebelah kanan kepada nama di sebelah kiri. "2" ialah teks; 2 ialah integer. Ejaan dan huruf besar/kecil nama mesti konsisten.'},
 trace:{zh:'先预测两行输出。然后逐行阅读，记录每行执行后的值。没有变化的值照写，输出单独记录。第 4 行用旧分数加 1，再保存新分数。',ko:'먼저 두 줄의 출력을 예상하세요. 각 줄이 실행된 뒤의 값을 기록하세요. 바뀌지 않은 값은 그대로 쓰고 출력은 따로 기록하세요. 4번째 줄은 이전 점수에 1을 더해 새 점수를 저장합니다.',ms:'Ramalkan dua baris output dahulu. Catat nilai selepas setiap baris dilaksanakan. Salin nilai yang tidak berubah dan catat output secara berasingan. Baris 4 menambah 1 kepada skor lama dan menyimpan skor baharu.'},
 fix:{zh:'修改第二行，让它显示变量中保存的昵称。保留第一行。不要直接打印 NOVA。请在右边代码框中修改，再运行和测试。需要帮助时可查看提示并继续。',ko:'저장된 별명이 출력되도록 두 번째 줄을 고치세요. 첫 줄은 그대로 두세요. NOVA를 직접 출력하지 말고 변수를 사용하세요. 코드 상자에서 수정한 뒤 실행하고 테스트하세요. 막히면 힌트를 보거나 지원을 받으며 계속할 수 있습니다.',ms:'Baiki baris kedua supaya nilai nama panggilan dipaparkan. Kekalkan baris pertama. Gunakan pemboleh ubah, bukan cetakan NOVA secara terus. Sunting dalam kotak kod, kemudian jalankan dan uji. Petunjuk tersedia jika perlu.'},
 award:{zh:'欢迎活动的初始分数是 2，完成后加 3。先更新 score，再分别显示昵称和新分数。不要直接打印 5。测试会把初始分数改为 5 和 0，检查程序是否仍正确。',ko:'시작 점수는 2이고 활동을 마치면 3점을 받습니다. score를 갱신한 뒤 별명과 새 점수를 각각 출력하세요. 5를 직접 출력하지 마세요. 테스트는 시작 점수를 5와 0으로 바꾸어 확인합니다.',ms:'Skor awal ialah 2 dan aktiviti memberi 3 mata tambahan. Kemas kini score, kemudian paparkan nama panggilan dan skor baharu pada baris berasingan. Jangan terus mencetak 5. Ujian juga menggunakan skor awal 5 dan 0.'},
 extension:{zh:'这是可选挑战，位于总结之前。选择一个难度，完成后可继续另一个。你也可以在 A4 纸上写代码并拍照上传。需要继续全班活动时，点击“前往学习检查站”。',ko:'정리 활동 전의 선택 도전입니다. 난이도를 하나 고르고 마치면 다른 도전도 해 보세요. A4 용지에 코드를 쓰고 사진을 올려도 됩니다. 학급 활동으로 돌아갈 때 학습 점검으로 이동하세요.',ms:'Cabaran pilihan ini sebelum penutup. Pilih satu tahap dan teruskan ke tahap lain jika selesai. Anda juga boleh menulis kod pada kertas A4 dan memuat naik foto. Teruskan ke Learning Pitstop apabila kelas bersedia.'},
 pitstop:{zh:'选择你目前的学习状态，不是能力等级。用今天的一个例子说明原因，再选择下一步：多练习、检查变量、挑战更难任务，或请求老师示范。',ko:'지금의 학습 상태를 고르세요. 능력 등급이 아닙니다. 오늘 작업의 예를 들어 이유를 설명하고 다음 행동을 고르세요: 연습, 변수 확인, 더 어려운 도전, 선생님께 시범 요청.',ms:'Pilih keadaan pembelajaran anda sekarang, bukan tahap kebolehan kekal. Beri satu contoh daripada kerja hari ini dan pilih tindakan seterusnya: berlatih, menyemak nilai, mencuba cabaran atau meminta tunjuk ajar.'},
 plenary:{zh:'请独立作答。预测最终输出，判断数据类型，并解释分数从多少变成多少、为什么。简短回答即可。',ko:'혼자 답하세요. 최종 출력과 자료형을 찾고 점수가 얼마에서 얼마로, 왜 바뀌었는지 설명하세요. 짧게 답해도 됩니다.',ms:'Jawab secara individu. Ramalkan output akhir, kenal pasti jenis data dan jelaskan perubahan skor serta sebabnya. Jawapan ringkas memadai.'},
 review:{zh:'检查姓名、班级和作答记录。未完成的部分会标明。导出 PDF 后，请上传到 Teams 的“02 Submit your Week 3 Theory assignment here”作业；JSON 备份用于下次继续学习。',ko:'이름, 반, 답변을 확인하세요. 미완료 부분은 표시됩니다. PDF를 내보낸 뒤 Teams의 “02 Submit your Week 3 Theory assignment here” 과제에 업로드하세요. JSON 백업은 나중에 이어서 학습할 때 사용합니다.',ms:'Semak nama, kelas dan jawapan. Bahagian belum siap akan ditandakan. Eksport PDF dan muat naik ke tugasan Teams “02 Submit your Week 3 Theory assignment here”. Sandaran JSON digunakan untuk menyambung kerja kemudian.'}
 },
 example:'badge_name = "NOVA"\nscore = 0\nprint(badge_name)\nscore = score + 1\nprint(score)',
 tasks:{
 fix:{title:'Fix the badge display',level:'Core challenge 1',code:'badge_name = "NOVA"\nprint("badge_name")',mission:'The badge should display its stored nickname. Instead, it displays the variable’s name. Repair it.',requirements:['Keep the first line unchanged.','Change the second line to display the stored value.','Use the variable rather than printing NOVA directly.'],expected:'NOVA',hints:['Quotation marks tell Python to treat something as text.','Compare print("score") with print(score). Which one looks up a value?'],fields:[['fix_explain','If the stored nickname became ECHO, what would your repaired program display?','It would display…']]},
 award:{title:'Award the welcome points',level:'Core challenge 2',code:'badge_name = "NOVA"\nscore = 2\n\n# Add your instructions below.',mission:'A participant starts with 2 points. Completing the welcome activity earns 3 more. Finish this program so the badge remembers the updated score.',requirements:['Keep score = 2 as the starting assignment; choose a short nickname.','Increase the existing score by 3. Do not just print 5.','Display the nickname, then the updated score on the next line.'],expected:'NOVA\n5',hints:['You need one assignment to update the score, then two print instructions.','Read the current value on the right, add 3, and assign the result to score on the left.','A different example: lives = lives + 1 updates lives. Adapt the idea for your score.'],fields:[['award_string','Why is your nickname stored as a string?','I used a string because…'],['award_explain','Why does your program still work when the starting score changes?','It uses the current score to…']]},
 message:{title:'Add a welcome message',level:'Extension 1 · 4–6 min',code:'# Store a short string in welcome_message.\n# Display the stored value.',mission:'Your badge needs a useful greeting. Store it once so you can change it easily.',requirements:['Create a string variable called welcome_message.','Display its stored value using print().','Change the message and check that the output changes too.'],expected:'Your chosen message',hints:['A string is text inside quotes. Give that string a meaningful name.','Use print() with the variable name to display its value.'],fields:[['message_note','Where would this message appear in your badge sequence?','Before / after… because…']]},
 bonus:{title:'Make the reward adjustable',level:'Extension 2 · 5–7 min',code:'badge_name = "NOVA"\nscore = 2\nbonus = 3\n\n# Update score using bonus, then display the results.',mission:'Different welcome activities award different points. Use a bonus variable so the reward can change without rewriting the update instruction.',requirements:['Keep the three starting assignments.','Update score using the value of bonus.','Display the nickname and updated score on separate lines.'],expected:'NOVA\n5',hints:['The amount you add now has a name: bonus.','Both sides of an arithmetic expression can use variable names.'],fields:[['bonus_note','What happens if bonus changes from 3 to 5?','The final score becomes… because…']]}
 }
};
