// Browser checks run with Node and Playwright. The lesson itself needs neither.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'/Users/tenbywork/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..');
const out=process.env.TEST_OUTPUT||path.resolve(root,'../../..','tmp/validation-app-check');
const python=process.env.PYTHON_PATH||'/Users/tenbywork/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/bin/python3';
fs.mkdirSync(out,{recursive:true});
const {spawnSync}=require('node:child_process');
(async()=>{
  const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_PATH||'/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge'});
  const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
  const page=await context.newPage(),errors=[],remote=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))remote.push(r.url());});
  await page.goto('file://'+path.join(root,'index.html'));await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(out,'01-landing.png'),fullPage:true});
  await page.fill('#student-name','Evidence Check');await page.fill('#student-class','10T');await page.click('#start-button');await page.waitForSelector('#lesson-shell:not([hidden])');
  assert.equal(await page.evaluate(()=>Lesson.pages.length),12);assert.equal(await page.evaluate(()=>Lesson.EXTENSIONS.length),10);
  const ids=await page.evaluate(()=>Lesson.questions.map(q=>q.id));assert.equal(ids.length,new Set(ids).size,'Question IDs must be unique');
  const registered=new Set(ids);let observed=[];
  for(let i=0;i<12;i++){
    await page.evaluate(i=>Notebook.go(i),i);
    assert.equal(await page.locator('main h1').count(),1);
    observed.push(...await page.locator('[data-answer]').evaluateAll(nodes=>nodes.map(n=>n.dataset.answer)));
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false,'Desktop viewport overflow at '+i);
    if([2,3,4,5,6,7,8,9,10,11].includes(i))await page.screenshot({path:path.join(out,`page-${i}.png`),fullPage:true});
  }
  assert(observed.every(id=>registered.has(id)),'Every input must be in the export registry');
  await page.evaluate(()=>Notebook.go(1));await page.selectOption('#starter1','string');await page.click('[data-check="starter1"]');assert.match(await page.locator('#feedback-starter1').innerText(),/Revisit/);
  await page.selectOption('#starter1','integer');assert.match(await page.locator('#feedback-starter1').innerText(),/changed/);await page.click('[data-check="starter1"]');assert.match(await page.locator('#feedback-starter1').innerText(),/matches/);
  await page.selectOption('#starter2','reject');await page.selectOption('#starter3','or');await page.fill('#starter4','Reject the invalid age before choosing a price.');await page.click('[data-model="starter4"]');
  await page.evaluate(()=>Notebook.go(2));for(const id of ['K1','K2','S1','S2','U1','U2'])await page.selectOption('#before-'+id,id==='K1'?'independent':'support');await page.selectOption('#focus-target','S1');await page.fill('#focus-action','Trace both invalid sides.');assert.match(await page.locator('#ksu-summary').innerText(),/1\/6 independently; 5\/6 with support/);
  await page.evaluate(()=>Notebook.go(4));for(const [age,output] of [[4,'8'],[5,'8'],[12,'8'],[13,'12'],[18,'12'],[19,'reject']])await page.selectOption('#plan-'+age,output);await page.click('[data-check="plan"]');assert.match(await page.locator('#feedback-plan').innerText(),/5\/6.*4/);await page.selectOption('#plan-4','reject');await page.click('[data-check="plan"]');assert.match(await page.locator('#feedback-plan').innerText(),/All six/);await page.fill('#plan-reject','age < 5 or age > 18');await page.fill('#plan-price','age <= 12');await page.fill('#plan-algorithm','Input age\nReject if outside 5–18\nOtherwise choose RM8 at most 12, else RM12.');
  await page.evaluate(()=>Notebook.go(5));for(const value of ['4','5','12','13','18','19']){await page.selectOption('#tutor-case',value);let safety=0;while(!(await page.locator('[data-tutor="next"]').isDisabled())&&safety++<10)await page.click('[data-tutor="next"]');assert.match(await page.locator('#tutor-explanation').innerText(),['4','19'].includes(value)?/Age not accepted/:/Age accepted/);}await page.screenshot({path:path.join(out,'tutor.png'),fullPage:true});
  const fixture=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=1400;c.height=740;const x=c.getContext('2d');x.fillStyle='white';x.fillRect(0,0,c.width,c.height);x.fillStyle='#17221c';x.font='32px monospace';['Evidence test — full screenshot','age = 13','Ticket price: RM12','Bottom edge: this must remain visible'].forEach((t,i)=>x.fillText(t,40,90+i*190));return c.toDataURL('image/png');});
  const imagePath=path.join(out,'fixture.png');fs.writeFileSync(imagePath,Buffer.from(fixture.split(',')[1],'base64'));
  await page.evaluate(()=>Notebook.go(6));const model=await page.evaluate(()=>Lesson.MODEL_CODE);await page.fill('#main2-code',model);await page.fill('#main2-output','Age: 13\nTicket price: RM12\nAge: 19\nAge not accepted');await page.fill('#main2-explain','13 is valid; it is above 12, so the price is RM12.');await page.selectOption('#main2-help','scaffold');await page.setInputFiles('#upload-program',[imagePath,imagePath]);await page.waitForFunction(()=>Notebook.state.photos.program?.length===2);assert.equal(await page.locator('[data-photos="program"] img').count(),2);await page.fill('[data-photos="program"] input >> nth=0','Code and output: first evidence image');await page.screenshot({path:path.join(out,'main2-evidence.png'),fullPage:true});
  const run=spawnSync(python,['-c',`import subprocess,sys\ncode=${JSON.stringify(model)}\nfor age, expected in [(-2,"Age not accepted"),(4,"Age not accepted"),(5,"Ticket price: RM8"),(8,"Ticket price: RM8"),(12,"Ticket price: RM8"),(13,"Ticket price: RM12"),(15,"Ticket price: RM12"),(18,"Ticket price: RM12"),(19,"Age not accepted")]:\n p=subprocess.run([sys.executable,"-c",code],input=str(age)+"\\n",text=True,capture_output=True)\n assert p.returncode==0,(age,p.stderr)\n assert p.stdout.strip()=="Age: "+expected,(age,p.stdout)\nprint("Python model verified for 9 inputs")`],{encoding:'utf8'});assert.equal(run.status,0,run.stderr);console.log(run.stdout.trim());
  await page.click('#support-open');await page.click('[data-support="Help me with this line"]');await page.fill('#support-note','I need help on the price condition.');assert.match(await page.locator('#support-card').innerText(),/Help me/);await page.click('#support-close');assert.equal(await page.evaluate(()=>Notebook.state.supportLog.at(-1).note),'I need help on the price condition.');
  await page.evaluate(()=>Notebook.go(7));for(let i=0;i<9;i++){
    if(i<8){const t=await page.evaluate(i=>Lesson.TESTS[i],i);await page.fill('#test-'+t.id+'-expected',t.expected);await page.fill('#test-'+t.id+'-actual','Age: '+t.age+'\n'+t.expected);await page.selectOption('#test-'+t.id+'-result','matched');if(i===0)await page.click('[data-model="test-4"]');}
    else {await page.fill('#own-test-value','-2');await page.selectOption('#own-test-type','erroneous');await page.fill('#own-test-why','A negative age is invalid away from the boundary.');await page.fill('#own-test-expected','Age not accepted');await page.fill('#own-test-actual','Age: -2\nAge not accepted');await page.selectOption('#own-test-result','matched');}
    observed.push(...await page.locator('#test-host [data-answer]').evaluateAll(n=>n.map(x=>x.dataset.answer)));
    if(i<8)await page.click('[data-test="next"]');
  }
  assert.match(await page.locator('#test-summary').innerText(),/8\/8.*recorded/);await page.fill('#test-correction','All recorded runs matched.');await page.fill('#test-justify','Age 8 does not check either acceptance edge or the price transition.');
  await page.evaluate(()=>Notebook.go(8));for(let i=0;i<10;i++){await page.selectOption('#extension-choice',String(i));observed.push(...await page.locator('#extension-host [data-answer]').evaluateAll(n=>n.map(x=>x.dataset.answer)));assert.match(await page.locator('#extension-host').innerText(),/Example run/);assert.match(await page.locator('#extension-host').innerText(),/Test to try/);if(i===0||i===9){await page.fill('#ext-'+i+'-code',i===0?model+'\n# Extension one evidence':model+'\n# Extension ten repaired');await page.fill('#ext-'+i+'-output',i===0?'EXTENSION ONE EVIDENCE — age 8 RM8':'EXTENSION TEN EVIDENCE — invalid ages rejected');await page.selectOption('#ext-'+i+'-status','tested');}if(i===9){await page.setInputFiles('#upload-ext-9',imagePath);await page.waitForFunction(()=>Notebook.state.photos['ext-9']?.length===1);}}
  await page.evaluate(()=>Notebook.go(9));for(const id of ['K1','K2','S1','S2','U1','U2']){await page.selectOption('#after-'+id,'independent');await page.selectOption('#phase-'+id,id==='U2'?'help':'consolidating');}await page.fill('#pit-evidence','S1: my code rejects 4 and 19, accepts 5 and 18.');await page.fill('#pit-action','Explain the price-transition tests without a hint.');assert.match(await page.locator('#ksu-summary').innerText(),/6\/6 independently/);assert.match(await page.locator('#ksu-summary').innerText(),/1 needing help/);
  await page.evaluate(()=>Notebook.go(10));await page.fill('#exit-condition','age <= 11');await page.fill('#exit-tests','11 and 12 check the changed price transition.');await page.fill('#exit-validation','No: ages 5–18 are still accepted.');await page.click('[data-model="plenary"]');
  await page.evaluate(()=>Notebook.go(11));assert.equal(new Set(observed).size,ids.length,'All registered prompts must be reachable in the UI');await page.evaluate(()=>Notebook.persist());
  await page.reload();await page.fill('#student-name','Evidence Check');await page.fill('#student-class','10T');await page.click('#start-button');await page.waitForSelector('#lesson-shell:not([hidden])');assert.equal(await page.evaluate(()=>Notebook.state.photos.program.length),2);assert.equal(await page.evaluate(()=>Notebook.state.answers['ext-9-output']),'EXTENSION TEN EVIDENCE — invalid ages rejected');
  const bd=page.waitForEvent('download');await page.click('#export-backup');const backup=await bd;const backupPath=path.join(out,'sample.backup.json');await backup.saveAs(backupPath);assert.equal(JSON.parse(fs.readFileSync(backupPath,'utf8')).photos['ext-9'].length,1);
  const pd=page.waitForEvent('download');await page.click('#export-pdf');const pdf=await pd;await pdf.saveAs(path.join(out,'sample-evidence.pdf'));assert.match(await page.locator('#export-message').innerText(),/downloaded/);await page.click('#export-close');
  await page.setViewportSize({width:390,height:844});for(let i=0;i<12;i++){await page.evaluate(i=>Notebook.go(i),i);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false,'Mobile overflow at '+i);}await page.evaluate(()=>Notebook.go(5));await page.screenshot({path:path.join(out,'mobile-tutor.png'),fullPage:true});
  const teacher=await context.newPage();teacher.on('pageerror',e=>errors.push(e.message));await teacher.goto('file://'+path.join(root,'index.html'));await teacher.fill('#student-name','teacher');await teacher.click('#start-button');await teacher.waitForSelector('#lesson-shell:not([hidden])');assert.equal(await teacher.evaluate(()=>Notebook.teacher),true);await teacher.evaluate(()=>Notebook.go(6));await teacher.click('.teacher-guide summary');assert.match(await teacher.locator('.teacher-guide').innerText(),/Model solution/);await teacher.click('#projector-toggle');assert.equal(await teacher.locator('body.projector').count(),1);await teacher.screenshot({path:path.join(out,'teacher-preview.png'),fullPage:true});
  const restore=await context.newPage();await restore.goto('file://'+path.join(root,'index.html'));restore.on('dialog',d=>d.accept());await restore.setInputFiles('#restore-file',backupPath);await restore.waitForSelector('#lesson-shell:not([hidden])');assert.equal(await restore.evaluate(()=>Notebook.state.photos.program.length),2);assert.match(await restore.evaluate(()=>Notebook.state.answers['ext-0-output']),/EXTENSION ONE/);
  assert.deepEqual(errors,[],'No browser errors');assert.deepEqual(remote,[],'No network is needed to load/use/export');
  await browser.close();console.log('PASS: all 12 pages, 10 extensions, 6 KSU targets, tutor branches, feedback, images, saving/resume/restore, support cards, full PDF, teacher preview and mobile layout.');console.log('QA output: '+out);
})().catch(e=>{console.error(e);process.exitCode=1;});
