(() => {
  'use strict';
  const L=window.LOOP_LESSON, P=window.LessonProgress, $=s=>document.querySelector(s);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let s=null, worker=null, timer=null, workerURL=null, playback=null, pdf=null, banner='';
  const entryPages=['overview','starter','types','loop-guide','body-guide','task1','task2','feedback','extension','pitstop','plenary','export'];
  const pageNames={overview:'Your learning journey',starter:'Starter · Remember the commands',types:'Types of learning','loop-guide':'Read the loop heading','body-guide':'Which lines repeat?',task1:'Main task 1 · Build loop patterns',task2:'Main task 2 · Test and repair',feedback:'Partner check · Explain your code',extension:'Extra challenges',pitstop:'Learning pitstop',plenary:'Plenary · Remember and explain',export:'Review · Save · Submit'};
  const key=()=>`${L.id}:${s.teacher?'teacher':s.name.trim().toLowerCase()+':'+s.klass.trim().toLowerCase()}`;
  const zh=(text)=>s?.lang==='zh'?`<p class="zh" lang="zh">${esc(text)}</p>`:'';
  const current=()=>L.challenges.find(c=>c.id===s.cid);
  const model=()=>L.models[s.mi];
  function log(type,detail=''){s.events.push({at:new Date().toISOString(),type,detail});if(s.events.length>600)s.events.shift();}
  function save(){if(!s)return;try{localStorage.setItem(key(),JSON.stringify(s));localStorage.setItem(L.id+':last',key());if($('#save'))$('#save').textContent='Saved on this device';}catch{if($('#save'))$('#save').textContent='Storage full — export a backup now';}}
  function work(c){return s.work[c.id]??= {order:[2,0,1],answers:{},checks:{},history:[],codes:{modify:c.sample,make:c.starter},runs:{run:[],modify:[],make:[]},visited:[],hints:[],notes:{}};}
  function last(c,m){return work(c).runs[m].at(-1);}
  function answered(v){return v!==undefined&&v!==null&&String(v).trim()!=='';}
  function complete(c,m){return P.done(s,P.node('challenge',c.id,L.models.indexOf(m)));}
  function challengeProgress(c){const nodes=P.path.filter(n=>n.cid===c.id);return nodes.length?nodes.filter(n=>P.done(s,n)).length+' / '+nodes.length+' core cards attempted':score(c)+' / 6 extra challenge cards attempted';}
  function started(c){const w=s.work[c.id];return !!w&&(w.visited.length>0||Object.values(w.runs).some(x=>x.length));}
  function score(c){return L.models.filter(m=>complete(c,m)).length;}
  function filename(suffix){const clean=v=>String(v).replace(/[^\p{L}\p{N}_-]/gu,'_').slice(0,45)||'Class';return `Year7_${clean(s.klass)}_${clean(s.name)}_${suffix}`;}
  function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),60000);}
  function launch(name,klass,lang){const teacher=name.toLowerCase()==='teacher';s={version:3,name,klass:teacher?'':klass,lang,teacher,page:'overview',cid:'square',mi:0,work:{},answers:{},events:[],speed:'normal'};try{const previous=JSON.parse(localStorage.getItem(key()));if(previous?.version===3)s=previous;}catch{}log('session-start');save();render();}
  function landing(){const canResume=!!localStorage.getItem(L.id+':last');$('#app').innerHTML=`<main class="welcome"><div><span class="eyebrow">Year 7 · Python Turtle</span><h1>Small steps.<br>Clear patterns.<br>Better code.</h1><p class="lead">Draw with loops, then become a code detective. Put code in order, predict it, run it, investigate, modify and make your own drawing.</p><div class="read-card"><strong>WAGBA</strong><p>${L.wagba}</p></div><p>Follow three core challenges in order. Continue with three extra challenges when you are ready. Your progress saves if you need another lesson.</p></div><form id="entry" class="entry-card"><h2>Start or continue</h2><label for="name">Full name</label><input id="name" autocomplete="name" required><label for="class">Class</label><input id="class" placeholder="For example, 7T"><label for="lang">Language support</label><select id="lang"><option value="en">English</option><option value="zh">English + 中文 support</option></select><p class="small">Your answers and code save on this device. At the end, save your PDF and Python files for Teams.</p><button class="primary">Start learning</button>${canResume?'<button type="button" data-action="resume">Resume saved work</button>':''}<p id="entry-error" role="alert"></p><label class="small" for="restore">Restore a lesson backup (.json)</label><input id="restore" type="file" accept=".json"></form></main>`;
    $('#entry').onsubmit=e=>{e.preventDefault();const name=$('#name').value.trim(),klass=$('#class').value.trim();if(!name||(!klass&&name.toLowerCase()!=='teacher')){$('#entry-error').textContent='Enter your name and class to begin.';return;}launch(name,klass,$('#lang').value);};
    $('[data-action="resume"]')?.addEventListener('click',()=>{try{s=JSON.parse(localStorage.getItem(localStorage.getItem(L.id+':last')));if(s?.version!==3)throw Error();render();}catch{$('#entry-error').textContent='Saved work was not found. Enter your name and class.';}});
    $('#restore').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>8000000)throw Error('Choose a backup smaller than 8 MB.');const b=JSON.parse(await file.text());if(b.lesson!==L.id||b.state?.version!==3||!b.state.work||!Array.isArray(b.state.events))throw Error('Choose a backup from this lesson.');s=b.state;save();render();}catch(err){$('#entry-error').textContent=err.message;}};
  }
  function objectives(){return `<h3>WAGBA</h3><p>${L.wagba}</p><h3>Knowledge</h3><p>${L.k}</p><h3>Skills</h3><p>${L.s}</p><h3>Understanding</h3><p>${L.u}</p><h3>Keywords · tap for help</h3><div class="words">${Object.entries(L.keywords).map(([k,v])=>`<details><summary>${k}</summary><p>${v[0]}</p>${zh(v[1])}</details>`).join('')}</div>`;}
  function move(page,cid,mi=0){if(!P.allowed(s,P.node(page,cid,mi))){banner='Finish the next card in My progress first. Your saved answers are safe.';render();return;}stop();s.page=page;if(cid)s.cid=cid;s.mi=mi;if(page==='challenge'){const w=work(current());if(!w.visited.includes(model()))w.visited.push(model());}log('visit',page==='challenge'?`${cid}:${model()}`:page);save();banner='';render();$('#title')?.focus({preventScroll:true});window.scrollTo({top:0,behavior:'auto'});}
  function render(){if(!s){landing();return;}migrateLesson();const active=P.node(s.page,s.cid,s.mi);if(!P.allowed(s,active)){const n=P.path[Math.max(0,P.first(s))];s.page=n.page;s.cid=n.cid||s.cid;s.mi=n.mi;banner='Your saved answers are kept. Continue from the next unfinished card.';}const oldScroll=window.scrollY,c=current(),m=model(),isChallenge=s.page==='challenge',title=isChallenge?({parsons:'Put the code in order',predict:'Predict the drawing',run:'Run and watch',investigate:'Find what repeats',modify:'Change one thing',make:'Write your own loop'}[m]):pageNames[s.page];
  $('#app').innerHTML=`<div class="focus-shell"><header class="focus-header"><div class="focus-toolbar"><span>Year 7 · ${esc(s.name)}</span><button data-action="journey">My progress</button><button data-action="language">${s.lang==='zh'?'English + 中文':'Language help'}</button><details class="learning-help"><summary>Learning goals</summary>${objectives()}</details></div><p class="persistent-wagba"><strong>WAGBA</strong> ${L.wagba}</p><div class="focus-keywords"><strong>Keywords</strong>${Object.entries(L.keywords).map(([k,v])=>`<details><summary>${k}</summary><div>${esc(v[0])}${zh(v[1])}</div></details>`).join('')}</div></header><main id="main"><section id="progress-checker" aria-label="My progress"></section><div class="crumb">${isChallenge?'Task '+c.task+' · '+esc(c.title):'Your lesson'}</div><h1 id="title" tabindex="-1">${esc(title)}</h1>${banner?`<p class="notice" role="status">${esc(banner)}</p>`:''}<div class="single-task">${isChallenge?challengeCard(c,m):pageBody()}</div><nav class="bottom-nav"><button data-action="back">← Back</button><span id="save">Saved on this device</span><button class="primary" data-action="next">${s.page==='export'?'My progress':s.page==='extension'?'Continue to pitstop →':'Continue →'}</button></nav></main></div>`;bind();updateProgress();paint();save();window.scrollTo({top:oldScroll,behavior:'auto'});}
  function nodeLabel(n){if(n.page!=='challenge')return pageNames[n.page];const c=L.challenges.find(c=>c.id===n.cid);return 'Task '+c.task+' · '+c.title+' · '+L.names[L.models[n.mi]];}
  function focusRequirement(selector){document.querySelectorAll('.needs-attention').forEach(e=>e.classList.remove('needs-attention'));const e=$(selector);if(!e){if(s.page==='challenge'&&$('[data-action="run"]')){focusRequirement('[data-action="run"]');return;}if(s.page==='plenary'){const match=selector.match(/exit([123])/);if(match){s.exitIndex=+match[1]-1;render();focusRequirement(selector);}}return;}for(let parent=e.parentElement;parent;parent=parent.parentElement)if(parent.tagName==='DETAILS')parent.open=true;const box=e.closest('.question-card,.editor-pane')||e;box.classList.add('needs-attention');e.scrollIntoView({block:'center',behavior:'smooth'});e.focus({preventScroll:true});}
  function updateProgress(){const panel=$('#progress-checker');if(!panel)return;const n=P.node(s.page,s.cid,s.mi),r=P.requirements(s,n),f=P.first(s),count=P.path.filter(x=>P.done(s,x)).length;
    panel.innerHTML=`<div class="quiet-progress"><span>${s.page==='challenge'?'Step '+(s.mi+1)+' · '+L.names[model()].split(' · ')[0]:count+' of '+P.path.length+' cards attempted'}</span><span>${s.page==='challenge'?learningStatus():'Your work saves automatically'}</span></div>${banner.startsWith('Almost there')?`<ul class="missing-actions">${r.filter(x=>!x.done).map(x=>`<li><button data-requirement="${r.indexOf(x)}">${esc(x.label)} →</button></li>`).join('')}</ul>`:''}${s.page==='challenge'&&!P.core.includes(s.cid)?'<button id="leave-extra">Pause extra challenges</button>':''}`;
    refreshActionChecklist();panel.querySelectorAll('[data-requirement]').forEach(b=>b.onclick=()=>focusRequirement(r[+b.dataset.requirement].selector));if($('#leave-extra'))$('#leave-extra').onclick=()=>move('extension');
    for(const item of r.filter(x=>x.done)){const e=$(item.selector);(e?.closest('.question-card,.editor-pane')||e)?.classList.remove('needs-attention');}if(r.length&&r.every(x=>x.done)&&banner.startsWith('Almost there')){banner='';$('.notice')?.remove();}
    $('#show-progress')?.addEventListener('click',menu);panel.querySelectorAll('[data-requirement]').forEach(b=>b.onclick=()=>focusRequirement(r[+b.dataset.requirement].selector));if($('#leave-extra'))$('#leave-extra').onclick=()=>move('extension');
    document.querySelectorAll('[data-page],[data-model],[data-challenge],[data-make],[data-gap]').forEach(b=>{let dest;if(b.dataset.page)dest=P.node(b.dataset.page);else if(b.dataset.model!==undefined)dest=P.node('challenge',s.cid,+b.dataset.model);else if(b.dataset.challenge)dest=P.node('challenge',b.dataset.challenge,startModel(b.dataset.challenge));else if(b.dataset.make)dest=P.node('challenge',b.dataset.make,5);else{const [id,i]=b.dataset.gap.split(',');dest=P.node('challenge',id,+i);}const ok=P.allowed(s,dest);b.disabled=!ok;b.classList.toggle('locked-step',!ok);if(!ok)b.title='Locked — finish the next card shown in My progress first.';else b.removeAttribute('title');});
  }


  function migrateLesson(){if(s.lessonRevision===4)return;s.lessonRevision=4;s.answerHistory??={};const w=s.work?.square;if(w){s.previousLessonEvidence??={};s.previousLessonEvidence.square=JSON.parse(JSON.stringify(w));delete w.answers.predict;delete w.answers.investigate;delete w.checks.predict;delete w.checks.investigate;w.codes.modify=currentSquare().sample;w.codes.make=currentSquare().starter;w.runs.modify=[];w.runs.make=[];w.notes.modify='';w.notes.make='';delete w.answers.targetCheck;delete w.answers.selfcheck;}save();}
  function learningStatus(){const w=work(current()),m=model(),r=w.runs?.[m]?.at(-1);if((r&&!r.ok)||(m==='make'&&w.answers.selfcheck===2)||(m==='modify'&&w.answers.targetCheck===2)||(m==='run'&&w.answers.compare===2))return 'Help requested / review needed';if((m==='make'&&w.answers.selfcheck===0)||(m==='modify'&&w.answers.targetCheck===0))return 'Checked against target · student judgement';return complete(current(),m)?'Attempt recorded':'Not finished yet';}
  function currentSquare(){return L.challenges.find(c=>c.id==='square');}
  function startModel(cid){return P.path.find(n=>n.cid===cid)?.mi??0;}
  function exitCard(){const i=Math.max(0,Math.min(2,s.exitIndex||0)),q=L.exitQuestions[i],value=s.answers[q.id],checked=s.exitChecked?.[q.id];return read('Independent check · '+(i+1)+' of 3','Try this new example before checking. This is not a race. Your first answer and any changes are saved.','先独立尝试这个新例子，再检查。首次答案和修改都会保存。')+'<h2>'+esc(q.title)+'</h2>'+codeView(q.code)+choices(q.id,q.q,q.options,value)+zh(q.zh)+'<button data-action="check-exit">Check this answer</button>'+(checked?'<div class="feedback">'+esc(q.why)+zh('比较解释后，你可以修改答案。')+'</div>':'')+'<div class="tools">'+L.exitQuestions.map((x,j)=>'<button data-exit="'+j+'" '+(!s.teacher&&L.exitQuestions.slice(0,j).some(p=>!answered(s.answers[p.id]))?'disabled':'')+'>'+(j+1)+'. '+esc(x.title)+(answered(s.answers[x.id])?' ✓':'')+'</button>').join('')+'</div>';}
  function visualPrediction(c,w){return '<fieldset class="visual-prediction"><legend>Choose one picture.</legend><div class="picture-options">'+[['←',160,110],['↓',160,110],['→',60,30]].map(([arrow,x,y],i)=>'<label><input type="radio" name="predict" data-choice="predict" value="'+i+'" '+(String(w.answers.predict)===String(i)?'checked':'')+'><svg viewBox="0 0 220 145" aria-hidden="true"><circle cx="60" cy="30" r="5" fill="#116b40"/><path d="M60 30H160V110" stroke="#116b40" stroke-width="4" fill="none"/><text x="'+x+'" y="'+y+'" font-size="30">'+arrow+'</text><text x="10" y="20" font-size="12">Start</text></svg><span>'+esc(c.prediction.options[i])+'</span></label>').join('')+'</div></fieldset>';}
  function predictionPictures(){return '<div class="prediction-pictures">'+[['A','←','160','110'],['B','↓','160','110'],['C','→','60','30']].map(([label,arrow,x,y])=>'<figure><svg viewBox="0 0 220 150" role="img" aria-label="Option '+label+': '+(label==='C'?'back at start facing right':'right and down facing '+(label==='A'?'left':'down'))+'"><circle cx="60" cy="30" r="5" fill="#116b40"/><path d="M60 30H160V110" stroke="#116b40" stroke-width="4" fill="none"/><text x="'+x+'" y="'+y+'" font-size="30" fill="#17221d">'+arrow+'</text><text x="10" y="20" font-size="12">Start</text></svg><figcaption>Option '+label+'</figcaption></figure>').join('')+'</div>';}
  function hintLadder(c,m){if(c.id==='stairs'||c.id==='turnbug')return '<details class="hint" data-hint="modify"><summary>Show the staircase hint</summary><p>'+esc(c.modify)+'</p><p>The upward step uses left(90), then right(90). Two left turns make the Turtle face backwards.</p></details>';const exact=c.id==='square'?'Change the distance in t.forward(...) to 120. Keep the repeat count and angle.':c.id==='countbug'?'Change range(3) to range(4).':c.id==='indentbug'?'Add four spaces before t.right(90), so it lines up with t.forward(60).':c.hint;return '<details class="hint" data-hint="'+m+'"><summary>Hint 1 · What should I inspect?</summary><p>'+(c.id==='square'?'Find the number controlling distance.':'Compare how many moves and turns happen with the intended square.')+'</p>'+zh('先比较目标和实际结果，一次检查一处。')+'<details><summary>Hint 2 · Where should I look?</summary><p>'+esc(c.id==='square'?'Look at t.forward(...) inside the loop.':c.id==='countbug'?'Inspect the number inside range(...).':'Inspect the spaces before the turn command.')+'</p><details><summary>Hint 3 · Show the edit</summary><p>'+esc(exact)+'</p></details></details></details>';}

  function read(title,text,chinese=''){return `<section class="read-card"><span class="tag">READ</span><h2>${title}</h2><p>${text}</p>${chinese?zh(chinese):''}</section>`;}
  function codeView(code){return `<pre class="code-view" translate="no"><code>${esc(code)}</code></pre>`;}
  function note(id,label,prompt,value){return `<div class="question-card"><label for="${id}">${label}</label><p class="sentence">${esc(prompt)}</p><textarea id="${id}" data-note="${id}" rows="2" placeholder="A short phrase or sentence is enough.">${esc(value||'')}</textarea></div>`;}
  function choices(id,q,opts,value){return `<fieldset class="question-card"><legend>${q}</legend>${opts.map((v,i)=>`<label class="option"><input type="radio" name="${id}" data-choice="${id}" value="${i}" ${String(value)===String(i)?'checked':''}><span>${esc(v)}</span></label>`).join('')}</fieldset>`;}
  function feedbackBox(c,id){const w=work(c),a=w.checks[id];if(!a?.length)return '';const latest=a.at(-1);return `<div class="feedback ${latest.correct?'correct':'retry'}" role="status"><strong>${latest.correct?'Your reasoning matches.':'Compare and try again.'}</strong><p>${esc(c[id==='predict'?'prediction':'investigate'].why)}</p></div>`;}

  function codingSupport(c,m){
    if(c.id==='stairs'||c.id==='turnbug'){
      const example=(m==='make'?c.solution:c.modified).split('\n\n')[1];
      return '<section class="coding-support"><div><h2>Correct staircase loop</h2>'+codeView(example)+'<p>Loop section only: keep the prepared setup and <code>t.done()</code> in your editor. The Turtle starts facing right. Each repeat draws one horizontal line and one vertical line. The final turn makes it face right again.</p>'+zh('每次循环画一条横线和一条竖线。最后一次转弯让海龟重新面向右边。')+'</div><div><h2>What to do now</h2><p>'+esc(m==='make'?c.make:c.modify)+'</p><button type="button" id="go-code">Take me to the code ↓</button><div id="action-checklist" aria-label="Task checklist"></div></div></section>';
    }
    const example='for i in range(4):\n    t.forward(80)\n    t.right(90)';
    const instruction=m==='make'?(c.id==='square'?'In Your Python, replace the eight repeated move/turn lines with one loop. Keep the setup above and t.done() below. Use 60 for the side length, not the example’s 80.':'In Your Python, write your loop where the comment says to start. Keep the setup and t.done(). Use the distances and turns in your goal.'):'In Your Python, find the loop beginning with for. Change only the part named in your goal. Leave the setup and t.done() alone.';
    return '<section class="coding-support"><div><h2>Use this Python pattern</h2>'+codeView(example)+'<p><code>for</code> starts the loop. <code>i</code> is the counter. <code>range(4)</code> repeats four times. Keep the <strong>colon :</strong> and <strong>four spaces</strong> before both commands.</p>'+zh('for 开始循环；range(4) 重复四次。保留冒号，并在循环里的每条指令前加四个空格。')+'</div><div><h2>What to do now</h2><p>'+esc(instruction)+'</p><button type="button" id="go-code">Take me to the code ↓</button><p class="support-hint"><strong>Hint:</strong> '+esc(m==='make'?c.hint:c.id==='square'?'The distance is inside t.forward(...).':c.id==='countbug'?'Check how many sides the repeat count produces.':'Check which commands have spaces before them.')+'</p><div id="action-checklist" aria-label="Task checklist"></div></div></section>';
  }
  function refreshActionChecklist(){const box=$('#action-checklist');if(!box)return;const req=P.requirements(s,P.node(s.page,s.cid,s.mi));box.innerHTML='<h3>Your task checklist</h3><ul>'+req.map((x,i)=>'<li>'+(x.done?'✓ '+esc(x.label):'<button data-todo="'+i+'">'+esc(x.label)+' →</button>')+'</li>').join('')+'</ul><p class="small">Ticks show recorded attempts, not a teacher grade.</p>';box.querySelectorAll('[data-todo]').forEach(b=>b.onclick=()=>focusRequirement(req[+b.dataset.todo].selector));if($('#go-code'))$('#go-code').onclick=()=>focusRequirement('#python');}

  function editor(c,m){const w=work(c),r=last(c,m);return `<div class="editor-grid"><section class="editor-pane"><label for="python">${m==='run'?'Prepared Python · run this version':'Your Python · type here'}</label><textarea id="python" spellcheck="false" autocorrect="off" autocapitalize="off" translate="no" ${m==='run'?'readonly':''}>${esc(m==='run'?c.sample:w.codes[m])}</textarea><details class="editor-options"><summary>Typing help and tools</summary>${m!=='run'?`<div class="tokens"><button data-insert="    ">4 spaces</button><button data-insert="t.forward()">forward</button><button data-insert="t.right()">right</button><button data-insert="t.left()">left</button></div>`:''}<div class="tools"><label class="small">Drawing speed <select id="speed"><option value="normal" ${s.speed==='normal'?'selected':''}>Watch drawing</option><option value="slow" ${s.speed==='slow'?'selected':''}>Slow</option><option value="instant" ${s.speed==='instant'?'selected':''}>Instant</option></select></label>${m!=='run'?'<button data-action="reset-code">Reset this editor</button><button data-action="py">Download this .py</button>':''}</div></details><div class="tools"><button class="primary" data-action="run" ${worker?'disabled':''}>${m==='run'?'Run prepared code':'Run my code'}</button><button data-action="stop" ${worker||playback?'':'disabled'}>Stop</button></div><p class="console" role="status">${worker?'Running Python…':esc(r?.error||r?.output||(r?'Run finished. Compare your drawing with the requirement.':'Ready. Run the code to see the drawing.'))}</p></section><section class="drawing"><h2>Actual output</h2><canvas id="output" width="800" height="600" aria-label="Actual Turtle output with x and y coordinates" role="img"></canvas><details class="context-help"><summary>Grid and replay help</summary><p class="small">Each grid step is 50 units. x: left/right. y: up/down.</p>${r?`<label class="small" for="replay">Test in sections · reveal drawn lines</label><input id="replay" type="range" min="0" max="${r.draws.filter(d=>d.pen&&d.from&&d.to).length}" value="${r.draws.filter(d=>d.pen&&d.from&&d.to).length}"><output id="line-count"></output><p class="small">These are drawn lines, not Python line numbers.</p>`:''}</details></section></div>`;}
  function target(c){return `<div class="target"><canvas id="target" width="800" height="600" role="img" aria-label="Target drawing for ${esc(c.title)}"></canvas><p>Target to aim for · start is marked with a dot</p></div>`;}
  function challengeCard(c,m){const w=work(c),r=['run','modify','make'].includes(m)?last(c,m):null;
    const goal=(text,chinese='')=>(c.id==='turnbug'&&m!=='make'?'<section class="explicit-goal"><strong>Debugging task — this starting program is deliberately wrong</strong><p>It does NOT draw three staircase steps. First inspect the broken version. On Modify, repair its final turn so each step continues right and up.</p>'+zh('这是故意写错的程序，不是正确示范。先观察，再在 Modify 页面修复最后一次转弯。')+'</section>':'')+'<section class="explicit-goal"><strong>Your goal</strong><p class="task-instruction">'+text+'</p>'+zh(chinese)+'</section>';
    const loopCode=(c.sample.split('\n\n')[1]||c.sample)+(m==='investigate'?'\nt.done()':'');
    if(m==='parsons')return goal(c.arrange,'用上移或下移排列代码，再检查。')+'<details class="context-help"><summary>Why are we drawing this?</summary><p>'+esc(c.scenario)+'</p></details><div class="parsons">'+w.order.map((n,i)=>`<div class="strip"><span class="strip-number">${i+1}</span><pre translate="no">${esc(c.blocks[n])}</pre><div><button data-shift="${i},-1" ${i===0?'disabled':''} aria-label="Move strip ${i+1} up">↑ Up</button><button data-shift="${i},1" ${i===2?'disabled':''} aria-label="Move strip ${i+1} down">↓ Down</button></div></div>`).join('')+'</div><button data-action="check-order">Check my order</button>'+(w.checks.parsons?.length?'<p class="feedback">'+(w.checks.parsons.at(-1).correct?'Order checked. Continue to predict the drawing.':'Start with the loop heading. Keep the repeating commands underneath. You may try again or continue with your attempt.')+'</p>':'');
    if(m==='predict')return goal(c.task===2?c.scenario:(c.id==='square'?'Read the loop. Choose where Turtle will be after two repeats. It starts facing right.':'Read the loop, then choose the answer below. Imagine one repeat at a time.'),c.task===2?c.scenarioZH:'读循环，预测两次重复后的位置和方向。开始时面向右。')+codeView(loopCode)+(c.id==='square'?visualPrediction(c,w):choices('predict',c.prediction.q,c.prediction.options,w.answers.predict));
    if(m==='run')return goal('Press Run prepared code. Watch the drawing, then compare it with your prediction.','运行代码，观察画线，再与你的预测比较。')+editor(c,m)+(r?choices('compare','Did it match your prediction?',['It matched my prediction','I changed my mind','I need help following the drawing'],w.answers.compare):'');
    if(m==='investigate')return goal('Look at the indented lines. Choose the explanation that fits the code.','看缩进的指令，选择正确的解释。')+codeView(loopCode)+choices('investigate',c.investigate.q,c.investigate.options,w.answers.investigate)+'<button data-action="check-investigate">Check my explanation</button>'+feedbackBox(c,'investigate')+'<details class="context-help"><summary>Help me follow one repeat</summary><p>'+esc(c.concept)+'</p><table><tr><th>Repeat</th><th>i</th><th>What happens</th></tr>'+c.trace.map(row=>'<tr>'+row.map(v=>'<td>'+esc(v)+'</td>').join('')+'</tr>').join('')+'</table></details>';
    if(m==='modify')return goal(c.modify,c.modifyZH)+codingSupport(c,m)+editor(c,m)+hintLadder(c,m)+(r?'<div class="after-run"><h2>Check your result</h2><p>'+esc(c.modifyCheck)+'</p>'+choices('targetCheck','How does your drawing compare?',['It matches the target','It partly matches; I know what to improve','I need help checking it'],w.answers.targetCheck)+(c.task===2?'<details class="context-help"><summary>Compare before and after</summary><div class="comparison"><section><h3>Before</h3><canvas id="before" width="800" height="600"></canvas></section><section><h3>After</h3><canvas id="after" width="800" height="600"></canvas></section></div></details>'+note('modify','What did you fix?',c.note,w.notes.modify):'')+'</div>':'');
    return goal(c.make,c.makeZH)+codingSupport(c,m)+'<details class="context-help"><summary>Show the target and checklist</summary>'+target(c)+'<ul>'+c.criteria.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul></details>'+editor(c,m)+'<details class="hint" data-hint="make"><summary>I need help starting</summary><p>'+esc(c.hint)+'</p></details>'+(r?choices('selfcheck','Check your drawing against the target',['My drawing meets the requirements','I have a partial drawing and know what to improve','I need help with one part'],w.answers.selfcheck)+note('make','Explain your loop',c.note,w.notes.make):'');
  }
  function pageBody(){switch(s.page){
    case 'overview':return read('Draw a pattern. Repair two bugs.','Today you will turn repeated Turtle commands into one loop. Then you will repair two programs. Follow Continue at the bottom of each card. Your code and drawings save automatically.','今天把重复的指令改成循环，再修复两个程序。每次完成一张卡，按下方的继续。代码和图形会自动保存。')+'<p><strong>First:</strong> compare two short programs in the starter.</p>';
    case 'starter':return read('Your job: replace repeated commands','Both programs below draw the same square. In Program A, the move and turn appear four times. In Program B, Python repeats the indented group. Point to the group before answering.','两个程序画相同的正方形。A 重复写四组指令，B 用循环重复缩进的指令。先指出重复的一组。')+'<div class="focus-grid"><section><h2>A · Written four times</h2>'+codeView(Array(4).fill('t.forward(80)\nt.right(90)').join('\n'))+'</section><section><h2>B · One loop</h2>'+codeView('for i in range(4):\n    t.forward(80)\n    t.right(90)')+'</section></div>'+choices('start','Which group in A does the loop repeat?',['forward(80) then right(90)','forward(80) then forward(80)','right(90) then right(90)'],s.answers.start)+'<button data-action="starter-check">Check my thinking</button>'+(s.answers.startChecked?'<p class="feedback">The indented move and turn form one group. Four repeats replace the four written groups.</p>':'');
    case 'types':return `${read('What does learning mean today?','Learning means getting better at what you know, can do and can explain through practice, feedback and useful challenge. Choose your starting point for each statement. These are not grades.','通过练习和反馈，提高知识、技能和理解。请选择你现在的起点。')}${[['k','Knowledge',L.k],['s','Skills',L.s],['u','Understanding',L.u]].map(([id,label,text])=>`<div class="question-card"><label for="rating-${id}">${label} · ${text}</label><select id="rating-${id}" data-global="rating-${id}"><option value="">Choose…</option>${['I can do this on my own','I can do this with an example','I need help to start','I have not tried this yet'].map(v=>`<option ${s.answers['rating-'+id]===v?'selected':''}>${v}</option>`).join('')}</select></div>`).join('')}`;
    case 'loop-guide':return `${read('Read it as: repeat this group four times','A loop lets Python repeat a group of commands. You write the group once. This heading tells Python how many times to run it. Look at each labelled part before using it in a challenge.','循环把一组指令重复执行。这个标题表示重复四次。')}<div class="loop-anatomy">${[['for','Start a loop','开始循环'],['i','The counter name; it stores 0, then 1, 2, 3','计数变量名'],['in','Take each value from the following range','依次取值'],['range(4)','Four values: 0, 1, 2, 3 → four repeats','四个值，重复四次'],[':','The repeated group comes next','后面是循环内容']].map(([word,meaning,chinese])=>`<div><code>${word}</code><span aria-hidden="true">↓</span><p>${meaning}</p>${zh(chinese)}</div>`).join('')}</div><div class="question-card"><h2>Say it before you type it</h2><p>“For each of four counter values, do the commands underneath.” You do not need to change <code>i</code> yourself. Python moves to its next value automatically.</p><button data-action="next">Show me the commands underneath →</button></div>`;
    case 'body-guide':return `${read('Spaces show what belongs inside','Both movement and turning need to repeat for a square. Put four spaces before EACH command. These spaces are called indentation. A line at the left edge after the loop runs only after the repeats finish.','四个空格表示缩进。方形需要前进和转弯都在循环内重复。')}<div class="body-example"><pre>for i in range(4):</pre><div><span class="body-label">INSIDE THE LOOP · both repeat</span><pre>    t.forward(80)\n    t.right(90)</pre></div><pre>t.done()</pre><p><code>t.done()</code> is outside the loop. It keeps a desktop Turtle window open; in this app it safely finishes the drawing program.</p></div><div class="question-card"><h2>Your editor can help</h2><p>After a line ending with <code>:</code>, press Return and the editor adds four spaces. On a tablet, the <strong>4 spaces</strong> button also inserts indentation. Keep the move and turn lined up.</p><button data-action="next">I am ready for the challenges →</button></div>`;
    case 'task1':case 'task2':return read(s.page==='task1'?'Your square challenge':'Your two detective cases',s.page==='task1'?'Draw a square using a loop instead of writing the same commands four times. First, put three code strips in order. Press Continue to begin.':'Two classmates want to draw squares. Their programs run, but something is wrong. For each case, predict, run, inspect and repair one thing. Press Continue to open Case A.',s.page==='task1'?'用循环代替重复写四次的指令。先排列三条代码。按继续开始。':'两个同学的程序能运行，但图形不对。先预测、运行、检查，再修改一处。按继续打开案例 A。');
    case 'feedback':return `${read('Check your drawing with a partner','Show your square or a repaired drawing. Point to the starting point and the repeated commands. Explain one repair. Ask your partner what is clear and what still needs help. Working alone? Explain it aloud to yourself.','给同伴解释一个循环，请同伴提出一条具体改进。')}<div class="challenge-grid">${L.challenges.filter(c=>started(c)&&complete(c,'make')).map(c=>`<button data-make="${c.id}">${c.title} · return to Make</button>`).join('')}</div>${globalNote('partner','What did your partner notice?','My partner noticed ___. Working alone? Write “I checked…” instead.')}${globalNote('improvement','What will you do with the feedback?','I will change ___ / check ___ / keep ___ because it matches the target.')}`;
    case 'extension':return read('Choose an extra challenge','Choose one if you have time. You can pause it and return here. Otherwise press Continue for your learning pitstop.','有时间可以选一个额外挑战。也可以按继续进入学习反思。')+'<div class="challenge-grid">'+L.challenges.filter(c=>!P.core.includes(c.id)).map(c=>'<button data-challenge="'+c.id+'">'+esc(c.title)+' →</button>').join('')+'</div>';
    case 'pitstop':return `${read('Where is your learning now?','Think about loops and debugging today. Choose the phase that fits. Your answer helps you decide what to do next. It does not change your score.','想一想今天的循环和调试学习。选择适合你的阶段，再决定下一步。')}${choices('phase','My current phase of learning…',['New learning · a useful challenge; I am learning something new','Consolidating · I am improving what I already know','Treading water · I need a harder challenge','Drowning · I need help to move forward'],s.answers.phase)}${globalNote('nextStep','What will help you improve?','I will ask for an example / trace one repeat / explain my code / try another challenge.')}<p class="small">If you need help now, tell your teacher. This choice is saved for your report; it does not send a live alert.</p>`;
    case 'plenary':return exitCard();
    case 'export':return exportPage();
    default:return '';
  }}
  function globalNote(id,label,prompt){return note(id,label,prompt,s.answers[id]);}
  function missing(){return P.path.filter(n=>n.page!=='export'&&!P.done(s,n)).map(n=>({text:nodeLabel(n),page:n.page,cid:n.cid,mi:n.mi}));}
  function exportPage(){const gaps=missing();return `${read('Your evidence is already collected','Each program run saved its code and output automatically. Your PDF includes your Parsons attempts, predictions, investigations, before/after drawings and explanations. You do not need to take device screenshots.')}<section class="question-card"><h2>${gaps.length?'Some evidence still needs attention':'Your core evidence is recorded'}</h2>${gaps.length?`<p>Tap a named card below to return to it. You can save a draft PDF at any time.</p><div class="gap-list">${gaps.map(g=>`<button ${g.cid?`data-gap="${g.cid},${g.mi}"`:`data-page="${g.page}"`}>${esc(g.text)} →</button>`).join('')}</div>`:'<p>Read your report before submitting. Recorded attempts are not a teacher grade.</p>'}</section><div class="tools"><button class="primary" data-action="pdf">Create my PDF</button><button data-action="review">Review all answers</button><button data-action="backup">Save progress backup</button></div><div id="pdf-links"></div><div id="review"></div><h2>Save your Python files</h2><p>Download the Make programs you completed. Keep the PDF and these files together.</p><div class="tools">${L.challenges.filter(c=>last(c,'make')).map(c=>`<button data-download="${c.id}">${c.title} · .py</button>`).join('')||'<p>No Make program has been run yet.</p>'}</div>${read('Upload to Teams','Open the project assignment your teacher names in <strong>Y7T Computer Science 2026–2027</strong>. Choose <strong>Add work</strong>, attach your PDF and required Python files, then select <strong>Turn in</strong>.')}<details class="device-help" open><summary>iPad / tablet · Save and upload</summary><ol><li>Tap <strong>Share / Save to Files</strong> after creating your PDF.</li><li>Choose <strong>Save to Files</strong>, choose your folder, then Save. If a PDF preview opens, use its Share button.</li><li>In Teams, choose <strong>Add work → Upload from this device / Files</strong>, then select the saved file.</li><li>Check the attachments and tap <strong>Turn in</strong>.</li></ol><p>A website cannot choose your iPad folder or verify your Teams submission.</p></details><label class="option"><input type="checkbox" id="submitted" ${s.answers.submitted?'checked':''}>I checked my attachments and selected Turn in in Teams.</label>`;}
  function bind(){document.querySelectorAll('[data-exit]').forEach(b=>b.onclick=()=>{s.exitIndex=+b.dataset.exit;save();render();});document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>move(b.dataset.page));document.querySelectorAll('[data-challenge]').forEach(b=>b.onclick=()=>move('challenge',b.dataset.challenge,startModel(b.dataset.challenge)));document.querySelectorAll('[data-make]').forEach(b=>b.onclick=()=>move('challenge',b.dataset.make,5));document.querySelectorAll('[data-gap]').forEach(b=>b.onclick=()=>{const [id,i]=b.dataset.gap.split(',');move('challenge',id,+i);});document.querySelectorAll('[data-model]').forEach(b=>b.onclick=()=>move('challenge',s.cid,+b.dataset.model));document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));
    document.querySelectorAll('[data-choice]').forEach(el=>el.onchange=()=>{const id=el.dataset.choice,where=s.page==='challenge'?work(current()).answers:s.answers;where[id]=+el.value;if(s.page!=='challenge'){(s.answerHistory??={})[id]??=[];s.answerHistory[id].push({value:+el.value,at:new Date().toISOString()});}log('answer',`${s.page}:${s.cid}:${id}=${el.value}`);if(s.page==='challenge')work(current()).history.push({at:new Date().toISOString(),field:id,value:+el.value});save();updateProgress();});
    document.querySelectorAll('[data-note]').forEach(el=>el.oninput=()=>{(s.page==='challenge'?work(current()).notes:s.answers)[el.dataset.note]=el.value;save();updateProgress();});document.querySelectorAll('[data-global]').forEach(el=>el.onchange=()=>{s.answers[el.dataset.global]=el.value;log('self-rating',el.dataset.global+': '+el.value);save();updateProgress();});
    document.querySelectorAll('[data-shift]').forEach(b=>b.onclick=()=>{const [i,d]=b.dataset.shift.split(',').map(Number),a=work(current()).order;[a[i],a[i+d]]=[a[i+d],a[i]];log('parsons-move',s.cid);save();render();});
    const py=$('#python');if(py&&!py.readOnly){py.oninput=()=>{work(current()).codes[model()]=py.value;save();updateProgress();};py.onkeydown=e=>{if(e.key==='Tab'){e.preventDefault();insert('    ');}if(e.key==='Enter'&&!e.ctrlKey&&!e.metaKey){e.preventDefault();const before=py.value.slice(0,py.selectionStart).split('\n').at(-1);insert('\n'+(before.match(/^ */)?.[0]||'')+(before.trimEnd().endsWith(':')?'    ':''));}if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();run();}};}
    document.querySelectorAll('[data-insert]').forEach(b=>b.onclick=()=>insert(b.dataset.insert));document.querySelectorAll('[data-hint]').forEach(d=>d.ontoggle=()=>{if(d.open){work(current()).hints.push({stage:model(),at:new Date().toISOString()});save();}});if($('#speed'))$('#speed').onchange=e=>{s.speed=e.target.value;save();};if($('#replay'))$('#replay').oninput=e=>{if(playback){playback.cancel();playback=null;}const r=last(current(),model());drawPartial($('#output'),r.draws,+e.target.value);$('#line-count').textContent=`${e.target.value} drawn lines shown`;};if($('#submitted'))$('#submitted').onchange=e=>{s.answers.submitted=e.target.checked;log('teams-confirmation',e.target.checked);save();updateProgress();};document.querySelectorAll('[data-download]').forEach(b=>b.onclick=()=>savePy(L.challenges.find(c=>c.id===b.dataset.download),'make'));}
  function insert(text){const e=$('#python');if(!e||e.readOnly)return;e.setRangeText(text,e.selectionStart,e.selectionEnd,'end');e.dispatchEvent(new Event('input'));e.focus();}
  function stop(){if(worker)worker.terminate();worker=null;if(timer)clearTimeout(timer);timer=null;if(workerURL)URL.revokeObjectURL(workerURL);workerURL=null;if(playback)playback.cancel();playback=null;}
  function run(){stop();const c=current(),m=model(),w=work(c),code=m==='run'?c.sample:w.codes[m];if(!code?.trim()){banner='Add a command in the code box, then run.';render();return;}const start=Date.now();let finished=false;const finish=r=>{if(finished)return;finished=true;stop();const record={at:new Date().toISOString(),code,ok:!!r.ok,draws:r.draws||[],error:r.error||'',output:r.output||'',ms:Date.now()-start};w.runs[m].push(record);if(w.runs[m].length>15)w.runs[m].splice(1,1);log('python-run',`${c.id}:${m}:${record.ok?'finished':'error'}`);save();render();if(record.ok&&record.draws.length&&s.speed!=='instant'){playback=TurtlePlayback.start(record.draws,{speed:()=>s.speed,paint:draws=>{const cv=$('#output');if(cv)RouteMap.paint(cv,draws,{map:false});},done:()=>{playback=null;const b=$('[data-action="stop"]');if(b)b.disabled=true;}});const b=$('[data-action="stop"]');if(b)b.disabled=false;}};
    try{workerURL=URL.createObjectURL(new Blob([window.PYTHON_RUNNER_SOURCE],{type:'text/javascript'}));worker=new Worker(workerURL);worker.onmessage=e=>{if(e.data.type==='ready'){clearTimeout(timer);timer=setTimeout(()=>finish({error:'This run took too long. Use a smaller repeat count and try again.'}),8000);worker.postMessage({type:'run',code});}else if(e.data.type==='result')finish(e.data);};worker.onerror=()=>finish({error:'Python could not start. Reload the hosted lesson and try again.'});timer=setTimeout(()=>finish({error:'Python did not load. Keep your work, reload the app and try again.'}),15000);render();}catch(e){finish({error:e.message});}}
  function drawPartial(cv,draws,n){let i=0;const out=[];for(const d of draws){if(d.pen&&d.from&&d.to){if(i>=n)break;i++;}out.push(d);}RouteMap.paint(cv,out,{map:false});}
  function paint(){if(s.page!=='challenge')return;const c=current(),m=model(),r=['run','modify','make'].includes(m)?last(c,m):null;if($('#output'))RouteMap.paint($('#output'),r?.draws||[],{map:false});if($('#before'))RouteMap.paint($('#before'),last(c,'run')?.draws||[],{map:false});if($('#after'))RouteMap.paint($('#after'),last(c,'modify')?.draws||[],{map:false});if($('#target')){const draws=[];let prev=null;for(const p of c.target){if(prev&&p)draws.push({from:prev,to:p,pen:true,color:'#708d7c',width:3});prev=p;}RouteMap.paint($('#target'),draws,{map:false});const cv=$('#target'),ctx=cv.getContext('2d'),start=c.target[0];ctx.beginPath();ctx.arc(400+start[0],300-start[1],7,0,Math.PI*2);ctx.fillStyle='#08783a';ctx.fill();}}
  function menu(){const d=document.createElement('dialog');d.className='journey-dialog';const f=P.first(s);d.innerHTML=`<h2>My progress</h2><p>✓ Recorded · Next = ready to do · Locked = finish earlier cards first. Answers do not have to be perfect.</p><div class="menu-list">${P.path.map((n,i)=>`<button data-step="${i}" ${P.allowed(s,n)?'':'disabled'}>${P.done(s,n)?'✓':i===f?'Next →':P.allowed(s,n)?'Revisit':'Locked'} · ${esc(nodeLabel(n))}</button>`).join('')}</div><h3>Extra challenges</h3><p>Available at the extension. Each challenge follows its own six steps.</p><div class="menu-list">${L.challenges.filter(c=>!P.core.includes(c.id)).map(c=>`<button data-extra="${c.id}" ${P.allowed(s,P.node('challenge',c.id,0))?'':'disabled'}>${esc(c.title)} · ${score(c)}/6</button>`).join('')}</div><button id="draft">Save a draft report</button> <button id="backup-now">Save progress backup</button> <button id="close-menu">Close</button> <button id="change-learner">Change learner</button>`;document.body.append(d);d.showModal();const close=()=>{d.close();d.remove();};d.querySelector('#close-menu').onclick=close;d.querySelector('#draft').onclick=()=>{close();move('export');};d.querySelector('#backup-now').onclick=()=>action('backup');d.querySelector('#change-learner').onclick=()=>{close();action('leave');};d.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{const n=P.path[+b.dataset.step];close();move(n.page,n.cid,n.mi);});d.querySelectorAll('[data-extra]').forEach(b=>b.onclick=()=>{const c=L.challenges.find(c=>c.id===b.dataset.extra),mi=L.models.findIndex(m=>!complete(c,m));close();move('challenge',c.id,mi<0?0:mi);});d.oncancel=()=>d.remove();}
  function next(){if(s.page==='plenary'&&(s.exitIndex||0)<2){const q=L.exitQuestions[s.exitIndex||0];if(!answered(s.answers[q.id])&&!s.teacher){banner='Choose an answer before moving to the next question.';render();focusRequirement('[name="'+q.id+'"]');return;}s.exitIndex=(s.exitIndex||0)+1;save();render();return;}if(s.page==='export'){menu();return;}const n=P.node(s.page,s.cid,s.mi),gaps=P.requirements(s,n).filter(r=>!r.done);if(gaps.length&&!s.teacher){banner='Almost there — complete the highlighted item, then press Save and continue.';render();focusRequirement(gaps[0].selector);return;}if(!P.requirements(s,n).length){(s.read??={})[P.id(n)]=true;save();}const i=P.path.findIndex(p=>P.id(p)===P.id(n));if(i>=0){const target=P.path[i+1];if(target)move(target.page,target.cid,target.mi);}else if(s.page==='challenge'){if(s.mi<5)move('challenge',s.cid,s.mi+1);else move('extension');}}
  function back(){const i=P.path.findIndex(n=>P.id(n)===P.id(P.node(s.page,s.cid,s.mi)));if(s.page==='export'){menu();return;}if(i>=0){const n=P.path[Math.max(0,i-1)];move(n.page,n.cid,n.mi);}else if(s.mi>0)move('challenge',s.cid,s.mi-1);else move('extension');}
  async function action(a){switch(a){case 'check-exit':{const q=L.exitQuestions[s.exitIndex||0];if(!answered(s.answers[q.id])){banner='Choose an answer first. A guess is OK.';render();return;}(s.exitChecked??={})[q.id]=true;save();render();break;}case 'next':next();break;case 'back':back();break;case 'journey':menu();break;case 'language':s.lang=s.lang==='zh'?'en':'zh';save();render();break;case 'leave':stop();save();s=null;landing();break;case 'starter-check':s.answers.startChecked=true;save();render();break;
    case 'check-order':{const w=work(current());(w.checks.parsons??=[]).push({at:new Date().toISOString(),order:[...w.order],correct:w.order.every((v,i)=>v===i)});log('parsons-check',s.cid);save();render();break;}
    case 'check-predict':case 'check-investigate':{const id=a==='check-predict'?'predict':'investigate',c=current(),w=work(c);if(!answered(w.answers[id])){banner='Choose an answer first. You can change it after checking.';render();break;}(w.checks[id]??=[]).push({at:new Date().toISOString(),value:w.answers[id],correct:w.answers[id]===c[id==='predict'?'prediction':'investigate'].answer});log('check',s.cid+':'+id);save();render();break;}
    case 'run':run();break;case 'stop':stop();banner='Stopped. Your code is saved. Reduce the repeats or change one thing, then run again.';render();break;case 'reset-code':if(confirm('Reset this editor? Your earlier run evidence stays saved.')){work(current()).codes[model()]=model()==='modify'?current().sample:current().starter;save();render();}break;
    case 'py':savePy(current(),model());break;case 'backup':download(new Blob([JSON.stringify({lesson:L.id,state:s})],{type:'application/json'}),filename('Loop_Practice_Backup.json'));break;case 'pdf':makePDF();break;case 'review':$('#review').innerHTML=reportHTML();$('#review').scrollIntoView({block:'start'});break;case 'download-pdf':if(pdf)download(pdf,filename('Loops_Debugging_Evidence.pdf'));break;
    case 'share-pdf':if(pdf){try{const file=new File([pdf],filename('Loops_Debugging_Evidence.pdf'),{type:'application/pdf'});if(navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:'My Year 7 evidence'});else{download(pdf,file.name);$('#pdf-status').textContent='If a PDF preview opens, use Share → Save to Files.';}}catch{$('#pdf-status').textContent='Sharing closed. Your PDF is still ready below.';}}break;
    case 'print':$('#print-report')?.remove();{const report=document.createElement('div');report.id='print-report';report.innerHTML=reportHTML();document.body.append(report);window.print();}break;
  }}
  function savePy(c,m){const code=work(c).codes[m]||c.sample;download(new Blob([code+'\n'],{type:'text/x-python'}),filename(`${c.id}_${m}_v02.py`));log('python-export',c.id+':'+m);save();}
  function reportParts(){const parts=[{title:L.title,text:`${s.name} · ${s.klass||'Teacher preview'}\n${new Date().toLocaleString()}\nWAGBA: ${L.wagba}\nKnowledge: ${L.k}\nSkills: ${L.s}\nUnderstanding: ${L.u}`},{title:'Starting point',text:`Starter: ${['Move then turn','Move then move','Turn then turn'][s.answers.start]||'Not answered'}\nKnowledge: ${s.answers['rating-k']||'Not answered'}\nSkills: ${s.answers['rating-s']||'Not answered'}\nUnderstanding: ${s.answers['rating-u']||'Not answered'}`}];
    for(const c of L.challenges.filter(started)){const w=work(c);parts.push({title:`Main task ${c.task} · ${c.title}`,text:`${c.scenario}\nProgress: ${challengeProgress(c)}\nParsons checks: ${w.checks.parsons?.length||0}; latest: ${w.checks.parsons?.at(-1)?.correct?'ordered as requested':'not yet correct / not checked'}`},{title:'My arranged code strips',code:w.order.map(i=>c.blocks[i]).join('\n')},{title:'Predict and investigate',text:`Prediction: ${c.prediction.options[w.answers.predict]||'No response'}\nPrediction attempts: ${w.history.filter(x=>x.field==='predict').map(x=>c.prediction.options[x.value]).join(' → ')||'None'}\nRun comparison: ${['Matched prediction','Changed prediction','Needed help'][w.answers.compare]||'No response'}\nInvestigation: ${c.investigate.options[w.answers.investigate]||'No response'}\nChecks: ${w.checks.investigate?.length||0}; hints opened: ${w.hints.length}`});
      for(const [m,title] of [['run','Run · original / before'],['modify','Modify · latest attempt / after'],['make','Make · my own version']]){if(m==='make'&&!work(c).visited.includes('make')&&!last(c,m))continue;const r=last(c,m);parts.push({title:`${c.title} · ${title}`,text:`${m==='modify'?c.modify:m==='make'?c.make:'Prepared sample'}\nRuns: ${w.runs[m].length}\n${r?(r.ok?'Executed successfully — target still needs checking.':r.error):'Not run yet'}\n${m==='modify'?'Target check: '+(['Matches target','Partly matches','Needs help'][w.answers.targetCheck]||'Not selected')+'\n':''}${w.notes[m]||''}`,code:r?.code||(m==='run'?undefined:w.codes[m]),draws:r?.draws});if(m!=='run'&&r&&w.codes[m]!==r.code)parts.push({title:`${c.title} · ${m} draft edited since last run`,text:'This is the current editor code. The drawing above belongs to the earlier run. Run this revised code before claiming its output.',code:w.codes[m]});}
      parts.push({title:'Self-check',text:['My drawing meets the requirements','Partial drawing — I know what to improve','I need help'][w.answers.selfcheck]||'Not selected'});
    }
    for(const q of L.exitQuestions){const h=s.answerHistory?.[q.id]||[],first=h[0]?.value,current=s.answers[q.id];parts.push({title:'Independent check · '+q.title,code:q.code,text:q.q+'\nFirst answer: '+(q.options[first]||'Not recorded')+'\nLatest answer: '+(q.options[current]||'Not answered')+(s.exitChecked?.[q.id]?'\nFeedback: '+q.why:'')+'\nFeedback opened: '+(s.exitChecked?.[q.id]?'Yes':'No')});}if(s.previousLessonEvidence?.square)parts.push({title:'Earlier lesson version · preserved square evidence',text:'Saved before the revised questions. Not counted as a new attempt.',code:s.previousLessonEvidence.square.codes?.make});
    const archive=s.previousLessonEvidence?.square;if(archive){for(const m of ['run','modify','make'])for(const r of archive.runs?.[m]||[])parts.push({title:'Preserved earlier square · '+m,text:(r.error||r.output||'Earlier program run')+'\n'+(archive.notes?.[m]||''),code:r.code,draws:r.draws});}
    parts.push({title:'Challenges not yet started',text:L.challenges.filter(c=>!started(c)).map(c=>`Task ${c.task}: ${c.title}`).join('\n')||'All started'},{title:'Partner check and improvement',text:`Noticed: ${s.answers.partner||'Not answered'}\nImproved: ${s.answers.improvement||'Not answered'}`},{title:'Learning pitstop',text:`Phase: ${['New learning','Consolidating','Treading water','Drowning'][s.answers.phase]||'Not selected'}\nNext step: ${s.answers.nextStep||'Not answered'}`},{title:'Earlier written reflections (if attempted)',text:`Loop: ${s.answers.pLoop||'Not answered'}\nBug: ${s.answers.pBug||'Not answered'}\nSection test: ${s.answers.pTest||'Not answered'}`},{title:'Evidence still to complete',text:missing().map(g=>g.text).join('\n')||'No required attempts missing. Correctness needs teacher review.'},{title:'Submission',text:s.answers.submitted?'Student confirmed attachments and Turn in. This is not a verified Teams status.':'Upload the PDF and your required Python files to the project assignment in Teams and select Turn in.'});return parts.filter(p=>p.title!=='Earlier written reflections (if attempted)'||['pLoop','pBug','pTest'].some(k=>answered(s.answers[k])));}
  function reportHTML(){return reportParts().map(p=>{let image='';if(p.draws?.length){const c=document.createElement('canvas');RouteMap.paint(c,p.draws,{map:false});image=`<img src="${c.toDataURL()}" alt="Recorded Turtle output">`;}return `<section class="report-section"><h2>${esc(p.title)}</h2>${p.text?`<p>${esc(p.text).replace(/\n/g,'<br>')}</p>`:''}${p.code?codeView(p.code):''}${image}</section>`;}).join('');}
  function makePDF(){try{const doc=new window.jspdf.jsPDF({unit:'mm',format:'a4'});let y=18;const newPage=()=>{doc.addPage();y=18;};const text=(value,mono=false)=>{doc.setFont(mono?'courier':'helvetica','normal');doc.setFontSize(mono?9:10);for(const raw of String(value||'').split('\n')){if(/[^\x20-\x7e]/.test(raw)){const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');canvas.width=1100;canvas.height=40;ctx.font='20px sans-serif';let row='';const rows=[];for(const ch of raw){if(ctx.measureText(row+ch).width>1050){rows.push(row);row='';}row+=ch;}rows.push(row);for(const r of rows){if(y>277)newPage();ctx.fillStyle='#fff';ctx.fillRect(0,0,1100,40);ctx.fillStyle='#14271b';ctx.fillText(r,0,27);doc.addImage(canvas.toDataURL(),'PNG',17,y-4,176,6.4);y+=6.2;}}else for(const row of doc.splitTextToSize(raw||' ',176)){if(y>277)newPage();doc.text(row,17,y);y+=5;}}y+=3;};
      for(const p of reportParts()){if(y>245)newPage();doc.setTextColor('#086a35');doc.setFont('helvetica','bold');doc.setFontSize(13);const title=p.title.replace(/[·→]/g,'-');for(const row of doc.splitTextToSize(title,176)){doc.text(row,17,y);y+=6;}doc.setTextColor('#14271b');y+=3;if(p.text)text(p.text);if(p.code)text(p.code,true);if(p.draws?.length){if(y+132>279)newPage();const canvas=document.createElement('canvas');RouteMap.paint(canvas,p.draws,{map:false});doc.addImage(canvas.toDataURL(),'PNG',17,y,176,132);y+=140;}}
      pdf=doc.output('blob');$('#pdf-links').innerHTML=`<div class="feedback"><strong>PDF ready</strong><p id="pdf-status">Save your report, check it, then upload it to Teams.</p><div class="tools"><button data-action="download-pdf">Download PDF</button><button data-action="share-pdf">Share / Save to Files</button><button data-action="print">Print / Save as PDF fallback</button></div></div>`;$('#pdf-links').querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));log('pdf-created');save();$('#pdf-links').scrollIntoView({block:'nearest'});
    }catch(e){$('#pdf-links').innerHTML='<p role="alert">PDF creation was interrupted. Use Review all answers, then Print / Save as PDF.</p><button id="print-fallback">Print / Save as PDF</button>';$('#print-fallback').onclick=()=>action('print');}}
  landing();
})();
