'use strict';
(() => {
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const questions=[];
  const define=(section,id,label,options={})=>{questions.push({section,id,label,kind:'text',...options});return id;};
  const opts=(values)=>({kind:'select',options:values});
  const levels=[['not-yet','Not yet demonstrated'],['support','Demonstrated with support'],['independent','Demonstrated independently']];
  const phases=[['new','New learning — this is new and I am making progress'],['consolidating','Consolidating — practice is making this more reliable'],['treading','Treading water — this is secure and I need a stretch'],['help','Drowning / I need help — identify one step to support']];
  const targets=[
    ['K1','Knowledge','Explain definite iteration','I can state that the number of repetitions is determined before this loop runs.'],
    ['K2','Knowledge','Recognise the start and stop values','I can distinguish Python’s excluded stop value from OxfordAQA’s included TO value.'],
    ['S1','Skills','Trace the counter and output','I can list ticket values and identify the message printed after the loop.'],
    ['S2','Skills','Modify and test the program','I can use an entered count to issue every ticket from 1 to that count.'],
    ['U1','Understanding','Explain why a definite loop fits','I can connect the known booking count to a fixed number of repetitions.'],
    ['U2','Understanding','Explain the bounds and indentation','I can explain + 1 and why the confirmation is outside the repeated block.']
  ];
  const routes={
    build:{name:'Build the missing idea',label:'Route 1 · Build',description:'Choose this when a key idea is missing, a comparison is confusing, or you need a model before you can explain your answer.',paper:'Two pages: identify one missing idea, practise a small check, prepare and show an explanation.'},
    strengthen:{name:'Make the answer precise',label:'Route 2 · Strengthen',description:'Choose this when you earned some credit but need a more precise explanation, a complete comparison or clearer evidence.',paper:'Two pages: map each marking point, improve the missing detail, rehearse your explanation and check it.'},
    transfer:{name:'Explain and transfer',label:'Route 3 · Transfer',description:'Choose this when your answer earned full credit and you can explain why. Use a teacher-approved new example to show that the idea transfers.',paper:'Two pages: explain why the answer earns credit, transfer the idea and test an alternative or boundary case.'}
  };
  define('Do Now','starter-int','What type does int(input(...)) produce?',opts([['integer','Integer'],['string','String'],['boolean','Boolean']]));
  define('Do Now','starter-boundary','The rule is “age is at least 14”. Choose its Python comparison.',opts([['ge','age >= 14'],['gt','age > 14'],['eq','age == 14']]));
  define('Do Now','starter-indent','Why are instructions indented below an if statement?',opts([['branch','They belong to the branch that runs when its condition is True.'],['decoration','Indentation only makes the code look tidy.'],['always','Indented instructions always run, regardless of the condition.']]));
  define('Types of Learning','review-focus','Which part of your checkpoint learning needs attention?',opts([['knowledge','Knowledge — recall a meaning, rule or computing term'],['skills','Skills — apply a rule, trace code or construct an answer'],['understanding','Understanding — explain why a rule or solution works'],['transfer','I can explain it; I need a new example to apply it to']]));
  define('Types of Learning','review-area','Which topic will you look for in your paper feedback?',opts([['comparisons','Comparisons and their meaning'],['selection','Selection and choosing the correct branch'],['input-types','Input, values and integer conversion'],['tracing','Tracing and exact output'],['wording','Precise written explanations / command words'],['evidence','Code or screenshot evidence'],['teacher','I need my teacher to help choose']]));
  define('Types of Learning','prior-experience','Have you used a FOR loop before?',opts([['new','Not yet / I am not sure'],['seen','I have seen one but need practice'],['used','I have used and explained one before']]));
  targets.forEach(([id,,title])=>define('Types of Learning','before-'+id,'Before learning: '+title,opts(levels)));
  define('Main Task 1: paper review','review-total','Optional: your teacher-marked checkpoint total / 40',{kind:'number',min:0,max:40});
  define('Main Task 1: paper review','review-question','Question number to discuss on paper',{placeholder:'e.g. 1.3 or 04.3.1',max:30});
  define('Main Task 1: paper review','review-earned','Marks awarded for this question',{kind:'number',min:0,max:40});
  define('Main Task 1: paper review','review-available','Marks available for this question',{kind:'number',min:1,max:40});
  define('Main Task 1: paper review','review-route','My review route',opts(Object.entries(routes).map(([id,r])=>[id,r.label+' — '+r.name])));
  define('Main Task 1: paper review','review-choice','Why does this route fit?',opts([['missing','A key idea is missing or I need a model'],['partial','I have some credit; my answer needs precision'],['secure','I can explain the credited answer; I need transfer'],['teacher','My teacher helped me choose / override the suggestion']]));
  define('Main Task 1: paper review','review-talk','How will you prepare to explain to your teacher?',opts([['frame','Write using a sentence frame, then explain privately'],['write','Write first; show or read my explanation to my teacher'],['point','Point to the relevant words or code, then explain one step'],['speak','Explain privately using my paper as a reference']]));
  ['sheet','points','improved','checked','explained'].forEach((id,i)=>define('Main Task 1: paper review','review-'+id,[
    'I collected my paper review sheet and the relevant marked question / marking points.',
    'On paper, I identified what earned credit and what was missing, or why full credit was earned.',
    'On paper, I wrote a corrected answer or a teacher-approved transfer response.',
    'I checked my response using the marking points and a suitable example or test.',
    'I showed or explained my reasoning to my teacher using my agreed support.'
  ][i],{kind:'checkbox'}));
  define('Read and model','fact-count','How many ticket numbers does range(1, 6) supply?',opts([['5','Five'],['6','Six'],['4','Four']]));
  define('Main Task 2: predict and trace','predict-output','Before using the walkthrough: predict the complete output.',{rows:7,code:true});
  for(let i=1;i<=5;i++)define('Main Task 2: predict and trace','trace-'+i,'Iteration '+i+' — ticket value',{kind:'number',min:0,max:100});
  define('Main Task 2: predict and trace','trace-message','How many times is “All tickets issued.” displayed?',opts([['once','Once, after the loop'],['five','Five times, inside the loop'],['never','It is not displayed']]));
  define('Main Task 2: predict and trace','trace-reason','Why is a definite loop suitable for the five-ticket task?',{rows:3,placeholder:'The organiser knows…'});
  define('Main Task 2: modify and test','program-code','Paste your own completed Python program.',{rows:11,code:true});
  define('Main Task 2: modify and test','program-output','Paste one complete run from your own IDE.',{rows:6,code:true});
  for(const n of [1,3,5]){
    define('Main Task 2: modify and test','test-'+n+'-actual','Input '+n+' — actual output from my IDE',{rows:4,code:true});
    define('Main Task 2: modify and test','test-'+n+'-status','Input '+n+' — comparison with the requirement',opts([['matched','Matched: tickets 1 to '+n+'; final message once'],['different','Different: I need to correct and retest'],['not-run','Not run yet']]));
  }
  define('Main Task 2: modify and test','program-pseudo','Write the equivalent OxfordAQA pseudocode.',{rows:7,code:true});
  define('Main Task 2: modify and test','program-explain','Explain why your Python stop value uses + 1.',{rows:3,placeholder:'I used… because… With an input of 3…'});
  define('Main Task 2: modify and test','program-support','What support did you use?',opts([['independent','No content hint / procedural access support only'],['reminder','A syntax reminder or one example'],['scaffold','Starting code or sentence frame'],['together','Worked through the model with my teacher']]));
  const extensions=[
    {title:'Repair the missing final ticket',level:'Consolidate',task:'A workshop program asks for the booking count but uses range(1, number_of_tickets). The final ticket is missing. Change the bounds without changing the input.',run:'Input: 4\nTickets: 1, 2, 3, 4\nConfirmation: once',test:'Also try 1: ticket 1 must appear once.',hint:'Python excludes the stop value. What stop comes immediately after the final ticket?'},
    {title:'Choose the first and last ticket',level:'Apply',task:'A second workshop continues the numbering from an earlier event. Ask for the first and last ticket numbers, then display every number in that inclusive range. Assume first <= last.',run:'First: 7\nLast: 10\nTickets: 7, 8, 9, 10',test:'First 12, last 12 must issue exactly one ticket.',hint:'Keep the starting number. Set the Python stop immediately after the last number.'},
    {title:'A multiplication practice card',level:'Apply',task:'A pupil chooses a whole-number times table. Ask for the number and display its products with 1 through 12. Use multiplication inside one definite loop.',run:'Table: 4\nFirst product: 4\nLast product: 48\nProducts displayed: 12',test:'Table 3 must start at 3 and finish at 36.',hint:'The counter runs from 1 to 12. Multiply the entered number by the counter.'},
    {title:'Personalised rehearsal messages',level:'Consolidate',task:'A presenter wants to rehearse a welcome message. Ask for their name and a repetition count. Print a numbered welcome that many times, then one closing message.',run:'Name: Maya\nRepetitions: 2\n1 Welcome Maya\n2 Welcome Maya\nRehearsal complete.',test:'A count of 1 must give one welcome and one closing message.',hint:'Use print with comma-separated values. Put the closing message outside the loop.'},
    {title:'Print five desk labels',level:'Apply',task:'A club has consecutive desk numbers beginning at a number chosen by the organiser. Ask for that starting number and display exactly five labels.',run:'Start: 21\nLabels: 21, 22, 23, 24, 25',test:'Start 1 must display labels 1 to 5.',hint:'The included numbers begin at start. Count five positions before choosing the excluded stop.'},
    {title:'A numbered revision checklist',level:'Consolidate',task:'A learner chooses how many revision slots to plan. Ask for a positive count. Display a numbered “Review one example” instruction for each slot, followed by “Plan ready” once.',run:'Slots: 3\n1 Review one example\n2 Review one example\n3 Review one example\nPlan ready',test:'Count 5 must produce five numbered instructions, not six.',hint:'The repeated instruction belongs inside the loop; the final message does not.'},
    {title:'Sponsor-rate table',level:'Apply',task:'A sponsor pays RM2 per completed lap. Display the sponsorship amounts for 1 through 6 laps. Use a named rate constant and multiplication; no running total is needed.',run:'1 lap: RM2\n2 laps: RM4\n…\n6 laps: RM12',test:'Change the named rate to 3. Six laps should then show RM18.',hint:'For each counter value, calculate laps * RATE and display that amount.'},
    {title:'Find the misplaced confirmation',level:'Explain',task:'A program puts “All tickets issued.” inside the loop. Explain the visible problem, then move that instruction to the correct indentation level.',run:'Input: 3\nTicket numbers: 1, 2, 3\nAll tickets issued. [once]',test:'Use counts 1 and 3. Explain why count 1 alone could hide this mistake.',hint:'A line indented under for repeats every iteration. An unindented line follows the completed loop.'},
    {title:'Show both languages agree',level:'Transfer',task:'Choose two positive endpoint numbers. Write OxfordAQA pseudocode and Python to display the same inclusive range. Explain the different stop notation and check the Python output.',run:'Endpoints: 4 and 8\nBoth designs: 4, 5, 6, 7, 8',test:'Also use equal endpoints: 4 and 4. Both should display 4 once.',hint:'OxfordAQA TO includes the endpoint. Python range excludes its stop.'},
    {title:'A workshop attendance register',level:'Transfer',task:'The organiser knows that three students have booked. Use a definite loop to ask for each student’s name and immediately display their registration number and name. Print a closing message after all three entries.',run:'Names entered: Ali, Maya, Zara\n1 Ali\n2 Maya\n3 Zara\nRegistration complete.',test:'Confirm there are three input prompts and one closing message.',hint:'Here the name input belongs inside the loop. Each iteration processes one booking; no list is needed.'}
  ];
  extensions.forEach((e,i)=>{
    define('Extension '+(i+1)+': '+e.title,'ext-'+i+'-code','My Python code',{rows:8,code:true});
    define('Extension '+(i+1)+': '+e.title,'ext-'+i+'-output','Actual output / test evidence',{rows:5,code:true});
    define('Extension '+(i+1)+': '+e.title,'ext-'+i+'-explain','What did I change, and how did I check it?',{rows:3});
    define('Extension '+(i+1)+': '+e.title,'ext-'+i+'-status','Challenge status',opts([['started','Started'],['tested','Run and checked in my IDE'],['support','I need support / a correction']]));
  });
  targets.forEach(([id,,title])=>{
    define('Learning Pit Stop','after-'+id,'After learning: '+title,opts(levels));
    define('Learning Pit Stop','phase-'+id,'My current learning phase: '+title,opts(phases));
  });
  define('Learning Pit Stop','pit-evidence','Name the evidence for one target.',{rows:3,placeholder:'S2: my runs for 1, 3 and 5…'});
  define('Learning Pit Stop','pit-action','What is your next specific action?',{rows:3,placeholder:'I will trace the counter for… / ask for help with…'});
  define('Plenary','exit-values','List the values produced by range(2, 5).',{rows:2,code:true});
  define('Plenary','exit-header','Write the Python header for FOR ticket ← 1 TO 4.',{rows:2,code:true});
  define('Plenary','exit-message','Why is the final confirmation outside the loop?',{rows:3});
  define('Save and submit','submit-check','I opened the exported PDF and checked my evidence.',{kind:'checkbox'});
  define('Save and submit','submit-teams','I attached my PDF to the correct Teams assignment and selected Turn in.',{kind:'checkbox'});
  const val=id=>window.Notebook?.state.answers[id]??'';
  function field(id){const q=questions.find(x=>x.id===id);if(!q)throw Error('Unknown field '+id);const v=val(id);let input;
    if(q.kind==='select')input=`<select id="${id}" data-answer="${id}"><option value="">Choose when ready</option>${q.options.map(([k,t])=>`<option value="${esc(k)}" ${k===v?'selected':''}>${esc(t)}</option>`).join('')}</select>`;
    else if(q.kind==='checkbox')return `<div class="field"><label class="check-label" for="${id}"><input type="checkbox" id="${id}" data-answer="${id}" ${v==='yes'?'checked':''}><span>${esc(q.label)}</span></label></div>`;
    else if(q.kind==='number')input=`<input type="number" id="${id}" data-answer="${id}" step="1" min="${q.min}" max="${q.max}" value="${esc(v)}" inputmode="numeric">`;
    else if(q.rows)input=`<textarea id="${id}" data-answer="${id}" rows="${q.rows}" ${q.code?'class="code-answer" spellcheck="false"':''} placeholder="${esc(q.placeholder||'')}">${esc(v)}</textarea>`;
    else input=`<input id="${id}" data-answer="${id}" value="${esc(v)}" maxlength="${q.max||100}" placeholder="${esc(q.placeholder||'')}">`;
    return `<div class="field"><label for="${id}">${esc(q.label)}</label>${input}</div>`;
  }
  const head=(title,time,tag)=>`<p class="eyebrow">${tag}</p><h1 tabindex="-1">${title}</h1><p class="stage-time">${time} · Work at your pace. You can return to any page.</p>`;
  const hint=(title,content)=>`<details><summary>${title}</summary><div>${content}</div></details>`;
  const snippets={
    worked:'for ticket in range(1, 6):\n    print(ticket)\n\nprint("All tickets issued.")',
    pseudo:'FOR ticket ← 1 TO 5\n    OUTPUT ticket\nENDFOR\nOUTPUT "All tickets issued."',
    start:'number_of_tickets = int(input("How many tickets? "))\n\n# Add your definite loop here.\n\nprint("All tickets issued.")',
    scaffold:'number_of_tickets = int(input("How many tickets? "))\n\nfor ticket in range(1, ____):\n    print(ticket)\n\nprint("All tickets issued.")'
  };
  const model='number_of_tickets = int(input("How many tickets? "))\n\nfor ticket in range(1, number_of_tickets + 1):\n    print(ticket)\n\nprint("All tickets issued.")';
  const pseudoModel='number_of_tickets ← USERINPUT\nFOR ticket ← 1 TO number_of_tickets\n    OUTPUT ticket\nENDFOR\nOUTPUT "All tickets issued."';
  const code=id=>`<div class="codebox"><pre>${esc(snippets[id])}</pre><div class="copy-row"><button data-copy="${id}">Copy ${id==='pseudo'?'pseudocode':'Python code'}</button><span id="copy-${id}" role="status"></span></div></div>`;
  const feedback=id=>`<div id="feedback-${id}">${window.Notebook?.state.checks[id]?`<p class="feedback ${window.Notebook.state.checks[id].stale?'revisit':''}">${esc(window.Notebook.state.checks[id].stale?'Your response changed. Check it again.':window.Notebook.state.checks[id].message)}</p>`:''}</div>`;
  const check=(id,label='Check my response')=>`<button data-check="${id}">${label}</button>${feedback(id)}`;
  function upload(group,title){return `<details><summary>${title}</summary><p class="small">Attach complete PNG, JPEG or WebP images, up to 10 MB each. You can also paste a copied screenshot on this page. Images are included uncropped in your PDF. Multiple images are allowed.</p><label for="upload-${group}">Choose evidence images</label><input id="upload-${group}" type="file" data-upload="${group}" accept="image/png,image/jpeg,image/webp" multiple><p class="error" id="upload-error-${group}" role="alert"></p><div data-photos="${group}"></div></details>`;}
  function ksu(after){return targets.map(([id,type,title,evidence])=>`<fieldset class="target"><legend>${type} · ${title}</legend><p class="small">Evidence: ${esc(evidence)}</p>${field((after?'after-':'before-')+id)}${after?field('phase-'+id):''}</fieldset>`).join('')+'<p id="ksu-summary" class="callout" role="status"></p>';}
  const paperSteps='<ol class="steps"><li><strong>Collect your paper sheet.</strong> Show your chosen route to your teacher. Collect your marked answer and only the relevant marking points.</li><li><strong>Identify the evidence.</strong> On paper, show what earned credit and what was missing. Full-credit answers need a reason, not an invented mistake.</li><li><strong>Improve one response.</strong> Use your route sheet. Write in your own words, not a copied model.</li><li><strong>Check it.</strong> Use a specific value, boundary case, trace or the relevant marking points.</li><li><strong>Prepare, then explain.</strong> Use your paper to rehearse one explanation. Ask your teacher for a private check when ready. You can point, write or read your prepared words first.</li></ol>';
  const pages=[
    {id:'ready',label:'Get ready',section:'Get ready',render:()=>`${head('Two connected goals','Before the lesson','YOUR LESSON ROUTE')}<p>First, use your checkpoint feedback to improve and explain one response <strong>on paper</strong>. Then learn a new structure that repeats instructions: a definite loop.</p><ol class="steps"><li>Have your marked checkpoint, a pen and your teacher’s paper review sheet ready.</li><li>Keep your Python IDE open. The website does not run your code.</li><li>Use the Help / pause card if you need a written instruction, one example or time to prepare.</li></ol><div class="callout"><strong>Success today:</strong> one meaningful paper review, one accurate loop trace, and one tested loop modification. The extensions are optional.</div><div class="table-scroll"><table><caption class="sr-only">60-minute lesson timing</caption><thead><tr><th>Minutes</th><th>Stage</th></tr></thead><tbody>${[['0–5','Do Now'],['5–8','Types of Learning'],['8–23','Main Task 1: paper checkpoint review'],['23–30','Read and model FOR loops'],['30–49','Main Task 2: trace, run, modify and test'],['49–54','Optional extension'],['54–57','Learning Pit Stop'],['57–60','Plenary and save']].map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td></tr>`).join('')}</tbody></table></div>`},
    {id:'starter',label:'Do Now',section:'Do Now',render:()=>`${head('Recall before you review','5 minutes','DO NOW · INPUT, COMPARISONS, INDENTATION')}<p>These three checks help you choose what to revisit in your marked paper. Try first; use the short recap if you need it. Using support is useful information, not a failure.</p>${hint('Quick recap if I need it','<p><code>input()</code> receives text. <code>int()</code> converts suitable whole-number text into an integer. “At least 14” includes 14, so it means <code>&gt;= 14</code>. Indentation shows which instructions belong to an <code>if</code> branch.</p>')}${field('starter-int')}${check('starter-int')}${field('starter-boundary')}${check('starter-boundary')}${field('starter-indent')}${check('starter-indent')}`},
    {id:'types',label:'Types of Learning',section:'Types of Learning',render:()=>`${head('Choose a meaningful learning target','3 minutes','KNOWLEDGE · SKILLS · UNDERSTANDING')}<p>Use your Do Now responses and your paper feedback. You may know a rule but need practice applying it—or apply it correctly but need help explaining why.</p>${field('review-focus')}${field('review-area')}<div class="callout"><strong>Prepare an explanation on paper:</strong> “I used ___ because the rule says ___. With the value ___, the result is ___.” You may write, point or read your prepared words before speaking independently.</div>${field('prior-experience')}${hint('Optional: my starting evidence for FOR loops','<p>These are new targets. If you have not studied loops, choose “Not yet” where appropriate. This is a baseline, not a test or grade. Leave a target blank if you cannot judge it yet.</p>'+ksu(false))}`},
    {id:'review',label:'Main Task 1 · Review',section:'Main Task 1: paper review',render:()=>`${head('Review on paper. Explain one improvement.','15 minutes','MAIN TASK 1 · FEEDBACK INTO ACTION')}<p>Your teacher will first model how a response earns credit using a paper question and its marking points. Then work on <strong>one</strong> question of your own. The test questions, test answers and your written reflection are not entered here.</p><h2>1. Choose a starting point</h2><p>A total mark is optional context. The marks and difficulty of your chosen question are more useful for deciding the support you need.</p>${field('review-total')}${field('review-question')}${field('review-earned')}${field('review-available')}<button id="suggest-route">Suggest a review route</button><p id="route-suggestion" class="callout" role="status"></p><p class="small">This is a suggestion, not an attainment band. Choose a different route with your teacher if the question marks do not reflect what you need.</p>${field('review-route')}<div id="route-description"></div>${field('review-choice')}<h2>2. Collect the paper and follow its steps</h2>${paperSteps}${field('review-talk')}<p class="small">Your teacher can give you an instruction in writing and wait while you prepare. You do not have to answer an unexpected question immediately.</p><h2>3. Record progress only</h2><p>The detailed answer, marking-point analysis, reflection and next-step plan belong on your paper sheet. These checks are self-reported; they are not extra test marks.</p>${['sheet','points','improved','checked','explained'].map(id=>field('review-'+id)).join('')}<div class="callout">If you still need help, keep your unfinished paper and choose the support card. Your teacher may give you supported loop work next rather than rush your review.</div>`},
    {id:'learn',label:'Read & model · FOR',section:'Read and model',render:()=>`${head('One instruction. Five tickets.','7 minutes','NEW LEARNING · OXFORDAQA 3.2.2')}<p>The school computing workshop has five bookings. The organiser needs ticket numbers <strong>1 to 5</strong>, followed by one confirmation message. We can repeat one output instruction rather than write five separate instructions.</p><h2>Read this first</h2><p>A <strong>loop</strong> repeats instructions. <strong>Definite iteration</strong> repeats a number of times determined before this loop begins. A <strong>counter</strong> takes each value in turn. Here, each counter value becomes one ticket number.</p><p class="small">Textbook: printed pages <strong>44–45, “Counter loops”</strong> (PDF pages 48–49). Read “Definite iteration”, “Counter variable”, “Start the for loop”, “Indented lines are repeated” and the first worked example. This lesson explanation is an original summary, not a reproduced textbook extract. Step sizes and nested loops are not required today.</p>${code('worked')}<ol class="steps"><li><code>ticket</code> is the counter variable.</li><li><code>range(1, 6)</code> supplies 1, 2, 3, 4 and 5. The stop value, 6, is excluded.</li><li>The indented <code>print(ticket)</code> repeats once for each ticket.</li><li>The unindented final message happens once after the loop.</li></ol><div class="range-visual" aria-label="Included counter values 1 to 5; stop value 6 is excluded"><span>1</span><span>2</span><span>3</span><span>4</span><span>5</span><span class="excluded">6 · excluded stop</span></div><h2>The same algorithm in OxfordAQA pseudocode</h2>${code('pseudo')}<p><strong>OxfordAQA TO 5 includes 5. Python range(1, 6) stops before 6.</strong> These examples both issue five tickets. Pseudocode is for expressing an algorithm; paste Python, not pseudocode, into your IDE.</p>${field('fact-count')}${check('fact-count')}`},
    {id:'trace',label:'Main Task 2 · Trace',section:'Main Task 2: predict and trace',render:()=>`${head('Predict, then follow the counter','First 7 minutes of Main Task 2','MAIN TASK 2 · READ BEFORE WRITING')}<p>Use the five-ticket example. First predict its complete output, including the final message. Then enter the ticket value for each iteration. The walkthrough below is a fixed visual model, not a Python interpreter.</p>${code('worked')}${field('predict-output')}<div class="table-scroll"><table class="trace-table"><thead><tr><th>Iteration</th><th>Ticket value</th></tr></thead><tbody>${[1,2,3,4,5].map(i=>`<tr><td>${i}</td><td><label class="sr-only" for="trace-${i}">Ticket value in iteration ${i}</label><input type="number" id="trace-${i}" data-answer="trace-${i}" min="0" max="100" step="1" value="${esc(val('trace-'+i))}"></td></tr>`).join('')}</tbody></table></div>${field('trace-message')}${check('trace','Check my trace')}<details><summary>Guided line-by-line walkthrough</summary><div class="tutor"><p class="small">Use Next step when ready. Line numbers are reading guides, not Python code. There is no automatic animation.</p><div id="tutor-lines" class="tutor-scroll"></div><div class="tutor-nav"><button data-tutor="back">Previous step</button><button data-tutor="next">Next step</button><button data-tutor="restart">Restart</button></div><p id="tutor-description" class="tutor-description" role="status"></p><pre id="tutor-values" class="example"></pre><p id="tutor-position" class="small"></p></div></details>${field('trace-reason')}${hint('An explanation frame','<p>“A definite loop is suitable because the organiser knows ___ before the loop starts. Each iteration ___.”</p>')}`},
    {id:'build',label:'Main Task 2 · Build',section:'Main Task 2: modify and test',render:()=>`${head('Let the organiser choose the count','Next 12 minutes of Main Task 2','MODIFY · RUN IN YOUR OWN IDE · TEST')}<p>You have followed a program that issues five tickets. The organiser now needs it for workshops with different booking counts. Ask for the number of tickets, then issue every ticket from <strong>1 up to that number</strong>. Display the confirmation once after all tickets.</p><p>Assume the organiser enters a <strong>positive whole number</strong>. Validation, lists, nested loops and accumulators are not required today. A count chosen by input still gives a definite loop: the count is known when that loop begins.</p><h2>What to do</h2><ol class="steps"><li>Copy the starting code into your own IDE and save it as <code>workshop_tickets.py</code>.</li><li>Add a FOR loop using the entered count. Use the previous example to choose its bounds.</li><li>Put the ticket-number output inside the loop. Keep the confirmation outside it.</li><li>Predict an input of 3, then run the program.</li><li>Test 1, 3 and 5. Compare the actual ticket numbers and confirmation count with the requirements.</li><li>Paste your code and evidence below. Write the equivalent OxfordAQA pseudocode and explain your stop value.</li></ol>${code('start')}${hint('A structural scaffold if I need one','<p>Replace the blank before running this. It is deliberately incomplete. Do not copy the underscores as your answer.</p>'+code('scaffold'))}${hint('A hint about the final ticket','<p>If the last required ticket is 3, Python needs the excluded stop value 4. Express this using the entered count rather than a fixed 4.</p>')}<h3>Example run for input 3</h3><pre class="example">How many tickets? 3\n1\n2\n3\nAll tickets issued.</pre>${field('program-code')}${field('program-output')}${upload('program','Attach code / output screenshots')}<h2>Check all three runs</h2>${[1,3,5].map(n=>hint('Test input '+n+' — record actual evidence',`<p>Expected: ticket numbers 1 through ${n}, each once; the confirmation once after them.</p>${field('test-'+n+'-actual')}${field('test-'+n+'-status')}`)).join('')}${field('program-pseudo')}${field('program-explain')}${field('program-support')}<button data-model="program">Compare with a model after attempting</button>${feedback('program')}<p class="small">The model helps you compare your reasoning; it does not automatically mark or execute your program.</p>`},
    {id:'extensions',label:'Extension',section:'Extensions',render:()=>`${head('Choose one purposeful challenge','5 minutes / follow-up','OPTIONAL · APPLY THE SAME LOOP IDEAS')}<p>Choose one task, not all ten. Each uses input, output, simple arithmetic and definite iteration. A tested explanation is more useful than racing through copied code.</p><label for="extension-choice">Challenge</label><select id="extension-choice">${extensions.map((e,i)=>`<option value="${i}" ${i===(window.Notebook?.state.ui.extension||0)?'selected':''}>${i+1}. ${esc(e.title)} · ${e.level}</option>`).join('')}</select><div id="extension-host"></div>`},
    {id:'pit',label:'Learning Pit Stop',section:'Learning Pit Stop',render:()=>`${head('What can you now show?','3 minutes','REFLECT · EVIDENCE AND LEARNING PHASE')}<p>Look at your trace, code, test runs and explanations. For each target, choose what you can demonstrate, then how that learning feels right now. These are separate measures and neither is a grade.</p><p class="small">“With support” can include a content model or scaffold. Procedural access support is not automatically a lack of subject understanding. Discuss your evidence privately with your teacher.</p>${ksu(true)}${field('pit-evidence')}${field('pit-action')}<div class="callout">Keep the detailed checkpoint next-step plan on your paper sheet. Here, reflect on the new FOR-loop targets. If you need help, identify one line or idea rather than having to explain everything at once.</div>`},
    {id:'plenary',label:'Plenary',section:'Plenary',render:()=>`${head('Show the key ideas','3 minutes, including saving','EXIT CHECK · BOUNDS AND INDENTATION')}<p>Try these without reopening the model. You may prepare your explanation in writing, then share it privately with your teacher.</p>${field('exit-values')}${field('exit-header')}${field('exit-message')}${check('plenary','Compare my exit responses')}<p class="small">These are teacher-authored formative questions, not reproduced past-paper questions.</p>`},
    {id:'submit',label:'Save & submit',section:'Save and submit',render:()=>`${head('Keep both kinds of evidence','At the end, or whenever you stop','PAPER REVIEW + DIGITAL LOOP NOTEBOOK')}<p>Your paper review stays on paper. Hand it in as your teacher directs. If your teacher asks for digital evidence, you may attach clear photos of the sheet below; no typed checkpoint answers are required.</p>${upload('paper','Optional: attach complete photos of your paper review')}<div id="completion"></div><ol class="steps"><li>Select <strong>Export PDF</strong> at the top right. This works even if your work is unfinished.</li><li>Open the PDF. Check your name, class, text, code and complete images. Unanswered items are labelled.</li><li>Open <strong>Microsoft Teams → Year 10 Computer Science → the correct assignment</strong>. You can reach it from the lesson’s Classwork module.</li><li>Select <strong>Add work</strong> or the attachment option shown, upload your PDF and select <strong>Turn in</strong>.</li><li>Check the status in Teams. If there is no assignment, follow your teacher’s stated destination.</li><li>Keep or hand in your paper review as directed. Export a JSON backup if you need to resume on another device.</li></ol>${field('submit-check')}${field('submit-teams')}<p class="small">These confirmations are self-reported. The app has no Teams connection. Export again if you want your final checklist included.</p>${hint('Sources and course connections','<p>OxfordAQA 9210, section 3.2.2: interpreting and using definite iteration. Pseudocode reading and tracing support written assessment; coding, modification and run evidence support practical assessment.</p><ul><li>Textbook: printed pages 44–45, Counter loops (PDF pages 48–49).</li><li><a href="https://www.oxfordaqa.com/qualification/international-gcse-computer-science-9210/" target="_blank" rel="noopener">OxfordAQA 9210 course resources</a></li><li><a href="https://docs.python.org/3/tutorial/controlflow.html#the-range-function" target="_blank" rel="noopener">Python: the range function</a></li><li><a href="https://teachcomputing.org/pedagogy" target="_blank" rel="noopener">NCCE computing pedagogy: models, tracing and PRIMM</a></li><li><a href="https://www.autism.org.uk/learn/knowledge-hub/professional-practice/communication-pupils" target="_blank" rel="noopener">Communication support and processing time</a></li></ul><p>The extension tasks are original short scenario-based practice, not reproduced Helsinki MOOC or OxfordAQA questions.</p>')}`}
  ];
  function extensionHtml(i){const e=extensions[i];return `<p class="eyebrow">${e.level.toUpperCase()} · CHALLENGE ${i+1}</p><h2>${esc(e.title)}</h2><p>${esc(e.task)}</p><h3>Example / required result</h3><pre class="example">${esc(e.run)}</pre><p><strong>Test to try:</strong> ${esc(e.test)}</p>${hint('One focused hint',`<p>${esc(e.hint)}</p>`)}${['code','output','explain','status'].map(k=>field('ext-'+i+'-'+k)).join('')}${upload('ext-'+i,'Optional screenshot evidence for this challenge')}`;}
  const notes={
    ready:'Prepare marked papers and the relevant marking points. Print the six-page review pack: routes 1, 2 and 3 each occupy two pages. Students need one pair, not the whole pack. No total-score bands or fixed ability labels. Protect review time; reduce independent loop demand if correction reveals substantial gaps.',
    starter:'Integer; age >= 14; indentation identifies the selected branch. Allow written responses, processing time and a single comparison guide. The starter checks prior learning, not new FOR-loop knowledge.',
    types:'Distinguish recalling a rule, applying it and explaining it. Do not confuse an answer-expression gap with a knowledge gap. FOR baselines are optional because this is new content. Evidence levels and feelings are different, not attainment grades.',
    review:'Model one marking point from a paper question for 3 minutes; students map their answer for 4; prepare/explain for 3; improve/check for 4; set a next step for 1. Use routes flexibly: missing idea -> Build; partial credit -> Strengthen; full credit with explainable reasoning -> Transfer. A question score is a starting signal, not an automatic judgement. Keep the review and test content on paper. Accept valid alternative wording where the actual scheme allows it. 04.2 did not require extra printed results in the issued version; do not add that requirement. 04.3 still requires the specified results and evidence. Missing OR alone is not decisive: check logically equivalent cancellation handling.',
    learn:'Textbook printed pp. 44–45. Definite count is set before loop execution, even if entered at runtime. Python stop excluded vs OxfordAQA TO included. Use meaningful ticket rather than an unexplained i. Do not teach WHILE, steps or nesting here. The five-ticket model has six output lines: five numbers plus the closing message.',
    trace:'Expected ticket values 1,2,3,4,5. Confirmation once, after the loop. Students predict before opening the fixed walkthrough. The pointer changes only when they click. Observe the distinction between the iteration count and counter values.',
    build:'Require the count input, int conversion, bounds 1 to entered count inclusive, number output inside, confirmation outside. Tests 1,3,5. No validation requirement or accumulator. Accept logically equivalent code and pseudocode. Practical support can be gradually faded. Model:\n'+model+'\n\nPseudocode uses numeric input by assumption:\n'+pseudoModel,
    extensions:'One challenge in the five-minute window. Ten available for follow-up. These remain within known input, output, multiplication and FOR-loop ideas. New numbering ranges are transfer, not compulsory. No score for speed.',
    pit:'Assess six K/S/U indicators using actual work. Six independent ticks do not establish an exam grade. Phases are private, per target and separate from evidence. A prepared explanation read aloud can be a legitimate supported step toward confidence. Agree the next prompt and format with the pupil when calm.',
    plenary:'range(2,5) -> 2,3,4. Header -> for ticket in range(1,5):. Closing message is outside so it runs once after all tickets. Self-check suggestions are formative, not official marks.',
    submit:'No automatic Teams submission, remote teacher alerts or central storage. Collect the paper sheets alongside PDFs. Optional sheet photos must be complete and readable. Review route/marks/checks are self-reported; teacher moderation is on paper.'
  };
  window.Lesson={id:'y10-checkpoint-review-for-loops-v1',title:'Review, explain, repeat',questions,targets,routes,pages,extensions,snippets,model,pseudoModel,notes,esc,field,extensionHtml,levels,phases};
})();
