'use strict';
(() => {
  // Transcribed from the revised, issued checkpoint schemes. No new marking criteria.
  const written='resources/Checkpoint_1_Written_Theory_Mark_Scheme.pdf';
  const practical='resources/Checkpoint_1_Practical_Mark_Scheme.pdf';
  const entries=[
    {id:'01.1',title:'Abstraction',marks:1,page:2,points:['The process of removing unnecessary details from a problem.'],guidance:'Accept “information” for “details”. Reject “data” for “details”.',official:true},
    {id:'01.2',title:'Decomposition',marks:2,page:2,points:['1 mark: breaking a problem down into sub-problems.','1 mark: so that each sub-problem accomplishes an identifiable task, or each sub-problem might be further subdivided.'],guidance:'Accept “task” for “problem”. Accept “program” or “algorithm” for “problem” as benefit of doubt.',official:true},
    {id:'01.3',title:'Camera-kit booking: sub-problems',marks:2,page:2,points:['Award 1 mark for each of two distinct sub-problems described in terms of its task.'],guidance:'Accept other sensible subdivisions of the stated problem. Isolated labels such as “input” or “processing” without saying what they do are not enough. Do not credit the same sub-problem twice.',example:'Examples: obtain/store the student identifier and quantity requested; compare the quantity requested with kits available to decide whether the booking can proceed; display the appropriate confirmation/refusal to the student.'},
    {id:'01.4',title:'Algorithm and program',marks:1,page:2,points:['Award 1 mark for a valid distinction: an algorithm describes steps for solving a problem, whereas a program implements those steps in a programming language; or an algorithm does not have to be executable code, whereas a program is code intended for a computer to execute.'],guidance:'Reject: an algorithm must be written in Python; a program and an algorithm are always the same thing.'},
    {id:'02.1',title:'Student identifier: data type',marks:2,page:3,points:['1 mark: string.','1 mark: explains that it preserves the identifier exactly, including leading zeros, or represents a label/text rather than a quantity used in arithmetic.'],guidance:'Accept str. “It is a number” or “it contains digits” is not enough as a justification for string. A contradictory justification earns no reason mark. The two points are independent, but both must describe a suitable representation.'},
    {id:'02.2',title:'Advantages of a named constant',marks:2,page:3,points:['1 mark: a descriptive constant name makes the purpose of the value easier to understand.','1 mark: the maximum can be updated in one definition, and every use refers to that updated value, avoiding missed or inconsistent updates.'],guidance:'Changing in one place and avoiding inconsistent updates count as one maintenance point, not two marks. “Better”, “easier” or “faster” without explaining how is not enough. Reject: uppercase names automatically prevent reassignment in Python.'},
    {id:'02.3',title:'Meaningful variable name',marks:2,page:3,points:['1 mark: a meaningful, valid identifier such as kits_requested, number_of_kits or requested_quantity.','1 mark: explains that the name tells the other programmer what the stored value represents, so they can understand or change the relevant calculation/decision without guessing what n means.'],guidance:'Accept other naming conventions with a clear meaning. “It is meaningful” or “it is better” alone is not enough. The explanation must apply to the suggested name.'},
    {id:'03.1',title:'Camera-kit trace table',marks:3,page:4,points:['1 mark: Available records 12 then 10 in that order.','1 mark: Requested is 5, Approved is Y, and Available subsequently becomes 5.','1 mark: outputs Booked then 5 in that order, with no additional output.'],guidance:'Ignore unnecessary repeats of unchanged values, blank cells, quotation marks around text and row choice, provided the event sequence remains clear. An incorrect additional value in an assessed variable sequence loses that point. Mark each point independently.',trace:true},
    {id:'03.2',title:'Why AND, not OR?',marks:2,page:4,points:['1 mark: AND requires both enough kits and teacher approval for the booking to proceed.','1 mark: OR would allow a booking when only one requirement holds, such as enough kits but no approval, or approval but too few kits.'],guidance:'Accept an equivalent correct counterexample with values. Only reciting “AND means both; OR means either” without relating the rule to the booking conditions is not enough.'},
    {id:'03.3',title:'Collection-message selection',marks:3,page:5,points:['1 mark: zero and negative quantities produce Invalid quantity.','1 mark: values 1, 2 and 3 produce Collect from office.','1 mark: values greater than 3 produce Ask technician, and the selection produces exactly one appropriate message for every integer input.'],guidance:'For points 1 and 2, credit the correctly implemented path even if another path is incorrect. Point 3 requires the complete mutually exclusive decision. No further mark for the supplied input statement. Accept equivalent IF/ELSE IF/ELSE, nested IF or separate non-overlapping conditions. Ignore minor message punctuation/case differences and harmless minor pseudocode syntax errors where the intended logic is unambiguous. Reject incorrect inclusion/exclusion of boundary values.',code:'Requested ← USERINPUT\nIF Requested ≤ 0 THEN\n    OUTPUT "Invalid quantity"\nELSE IF Requested ≤ 3 THEN\n    OUTPUT "Collect from office"\nELSE\n    OUTPUT "Ask technician"\nENDIF',example:'Boundary check: -1 or 0 → Invalid quantity; 1, 2 or 3 → Collect from office; 4 or greater → Ask technician.'},
    {id:'04.1',title:'Practical: trace the given program',marks:5,page:1,points:['1 mark: points = 15.','1 mark: permission != "Y" is False.','1 mark: age >= 16 is False.','1 mark: age >= 14 is True.','1 mark: output is Aisha Intermediate 15.'],guidance:'Accept equivalent representations of Boolean values and spacing in the output. Reject values obtained by changing or skipping given lines.',practical:true},
    {id:'04.2.1',title:'First-version source code',marks:6,page:1,points:['1 mark: a meaningful identifier stores the name input.','1 mark: age input is converted to integer.','1 mark: permission and cancellation inputs are both stored.','1 mark: activity input is converted to integer.','1 mark: a named constant with value 5 is created.','1 mark: total points use activities and the named constant.'],guidance:'Accept int(input(...)) or input followed by int conversion; any meaningful identifiers. Reject a literal 5 used only in the calculation when no named constant is created and used.',practical:true,first:true},
    {id:'04.2.2',title:'First-version run screenshot',marks:1,page:1,points:['1 mark: a readable first-version run with the requested inputs, consistent with 04.2.1. Accept input prompts and typed responses.'],guidance:'Extra printed results, including a displayed points total, are not required. No debugger display or extra print statement is required. The capture must show the first version, not a different program.',practical:true,run:'Enter student name: Aisha\nEnter age: 14\nParental permission given? Y/N: Y\nBooking cancelled? Y/N: N\nNumber of activities: 3',example:'This is an illustrative transcript, not a student screenshot. The program may finish without printing anything else. The calculated points are assessed in the source code.'},
    {id:'04.3.1',title:'Completed source code: selection',marks:6,page:1,points:['1 mark: permission and cancellation are correctly compared and joined by or.','1 mark: rejected bookings output Booking cannot proceed.','1 mark: age >= 16 selects Senior.','1 mark: age >= 14 selects Intermediate after the Senior check.','1 mark: the final else selects Junior.','1 mark: accepted output contains name, selected group and calculated points, while rejected bookings are not assigned a group.'],guidance:'Accept logically equivalent Python selection. Reject use of = where comparison is required. Missing the literal word or is not, by itself, a reason to reject logically equivalent selection; both rejection conditions must still be handled correctly.',practical:true,complete:true},
    {id:'04.3.2',title:'Test A output screenshot',marks:1,page:1,points:['1 mark: visible output showing Aisha, Intermediate and 15 points. It must match the completed code in 04.3.1.'],guidance:'Source code and screenshot marks are separate. Required results must be visible; a crop that omits a required result does not earn the screenshot mark.',practical:true,example:'Test A inputs: Aisha; age 14; permission Y; cancelled N; activities 3.'},
    {id:'04.3.3',title:'Test B output screenshot',marks:1,page:1,points:['1 mark: visible output showing Booking cannot proceed and no age group for Zara. It must match the completed code in 04.3.1.'],guidance:'Source code and screenshot marks are separate. Required results must be visible; a crop that omits a required result does not earn the screenshot mark.',practical:true,example:'Test B inputs: Zara; age 13; permission Y; cancelled Y; activities 2.'}
  ];
  const first='POINTS_PER_ACTIVITY = 5\nname = input("Enter student name: ")\nage = int(input("Enter age: "))\npermission = input("Parental permission given? Y/N: ")\ncancelled = input("Booking cancelled? Y/N: ")\nactivities = int(input("Number of activities: "))\npoints = activities * POINTS_PER_ACTIVITY';
  const complete=first+'\n\nif permission != "Y" or cancelled == "Y":\n    print("Booking cannot proceed")\nelif age >= 16:\n    print("Student:", name, "Group: Senior", "Points:", points)\nelif age >= 14:\n    print("Student:", name, "Group: Intermediate", "Points:", points)\nelse:\n    print("Student:", name, "Group: Junior", "Points:", points)';
  const esc=s=>window.Lesson.esc(s);
  const model=e=>{
    let html='';
    if(e.official)html+='<p class="small">Original OxfordAQA guidance: June 2025, 9210/2, Q02.1–02.2, mark scheme page 6. Classroom numbering: 01.1–01.2.</p><img class="scheme-original" src="resources/Official_01_1_01_2_Marking_Extract.png" alt="Original official marking extract. Abstraction: remove unnecessary details, 1 mark. Decomposition: break a problem into sub-problems, 1 mark; identifiable tasks or further subdivision, 1 mark. Both original questions are shown; use only your selected one.">';
    if(e.trace)html+='<div class="table-scroll"><table><caption>Example trace: values when first assigned or changed</caption><thead><tr><th>Available</th><th>Requested</th><th>Approved</th><th>OUTPUT</th></tr></thead><tbody><tr><td>12</td><td></td><td></td><td></td></tr><tr><td>10</td><td></td><td></td><td></td></tr><tr><td></td><td>5</td><td></td><td></td></tr><tr><td></td><td></td><td>Y</td><td></td></tr><tr><td>5</td><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td><td>Booked</td></tr><tr><td></td><td></td><td></td><td>5</td></tr></tbody></table></div>';
    if(e.first||e.complete||e.code)html+='<pre class="example scheme-code">'+esc(e.first?first:e.complete?complete:e.code)+'</pre>';
    if(e.run)html+='<pre class="example">'+esc(e.run)+'</pre>';
    if(e.example)html+='<p>'+esc(e.example)+'</p>';
    return html?'<details><summary>Show the example / original extract</summary><div>'+html+'</div></details>':'';
  };
  function panel(){const selected=window.Notebook?.state.ui.markQuestion||'';return '<section class="scheme-panel" aria-labelledby="scheme-title"><h2 id="scheme-title">Find your question’s marking points</h2><p>Choose <strong>one question</strong> from your marked paper. Compare your answer with its marking points, then make the correction and set your target <strong>on paper</strong>. You do not need to read every answer.</p><label for="scheme-question">Question to review</label><select id="scheme-question"><option value="">Choose your question number</option>'+[['Written theory · Sections A–C · 20 marks',false],['Python practical · Section D · 20 marks',true]].map(([label,p])=>'<optgroup label="'+label+'">'+entries.filter(e=>!!e.practical===p).map(e=>'<option value="'+e.id+'" '+(selected===e.id?'selected':'')+'>'+e.id+' · '+e.title+' · '+e.marks+' '+(e.marks===1?'mark':'marks')+'</option>').join('')+'</optgroup>').join('')+'</select><div id="scheme-content" aria-live="polite"></div><details><summary>Full mark schemes and marking guidance</summary><div><p><a href="'+written+'" target="_blank" rel="noopener">Open written theory mark scheme (20 marks)</a> · <a href="'+written+'" download>Download PDF</a></p><p><a href="'+practical+'" target="_blank" rel="noopener">Open practical mark scheme — corrected Q04.2 (20 marks)</a> · <a href="'+practical+'" download>Download PDF</a></p><p>These are the revised checkpoint documents, released here for post-test review. They retain their original teacher-copy labels. Only 01.1–01.2 use official OxfordAQA guidance; the other questions and marking points are school-authored.</p><p>Accept equivalent wording or logically equivalent solutions where the scheme allows. A model answer is not the only possible answer. Your teacher confirms marks; this page does not re-mark your test.</p><p>Written: award whole marks; do not credit the same idea twice. An incorrect or contradictory explanation does not earn an explanation mark. Minor spelling or punctuation errors do not lose marks unless meaning changes. Clear, unambiguous pseudocode alternatives, including correctly structured Python, are accepted for school-written questions.</p><p>Practical: mark positively, credit logically equivalent Python 3 and do not penalise the same error twice. Code and screenshot marks are assessed separately. A correct listing can earn code marks even when a screenshot is missing; a screenshot cannot replace missing source code.</p></div></details></section>';}
  function draw(){const host=document.getElementById('scheme-content');if(!host)return;const e=entries.find(x=>x.id===window.Notebook.state.ui.markQuestion);if(!e){host.innerHTML='<p class="small">The marking points for your selected question will appear here.</p>';return;}host.innerHTML='<h3>'+esc(e.id+' · '+e.title+' · '+e.marks+' '+(e.marks===1?'mark':'marks'))+'</h3><p class="small">'+(e.practical?'School-authored practical marking':e.official?'Official OxfordAQA marking guidance':'School-authored written marking')+'</p><ul class="scheme-points">'+e.points.map(p=>'<li>'+esc(p)+'</li>').join('')+'</ul><p><strong>Accepted alternatives / marking notes:</strong> '+esc(e.guidance)+'</p>'+model(e)+'<p class="small"><a href="'+(e.practical?practical:written)+'#page='+e.page+'" target="_blank" rel="noopener">Open this question in the original checkpoint scheme (page '+e.page+')</a></p><div class="callout"><strong>Now use your paper sheet:</strong><br>Find what is missing → correct it → check a similar example → set one target. Showing or writing your explanation is fine; you do not have to answer aloud immediately.</div>';}
  window.CheckpointScheme={entries,panel,draw};
})();
