'use strict';
(() => {
  const clean=s=>String(s??'').replace(/←/g,'<-').replace(/→/g,'->').replace(/[–—]/g,'-').replace(/[“”]/g,'"').replace(/[‘’]/g,"'").replace(/≥/g,'>=').replace(/…/g,'...');
  function base(){if(!window.jspdf?.jsPDF)throw Error('The offline PDF library is unavailable. Save a backup and tell your teacher.');const d=new window.jspdf.jsPDF({unit:'pt',format:'a4',compress:true});d.addFileToVFS('Raleway.ttf',window.PDF_FONTS.regular);d.addFont('Raleway.ttf','Raleway','normal');d.setFont('Raleway','normal');d.setProperties({title:'Year 10 - Checkpoint review and definite iteration',author:'Computer Science'});return d;}
  function notebook(state){
    const L=window.Lesson,d=base(),W=d.internal.pageSize.getWidth(),H=d.internal.pageSize.getHeight(),m=43,w=W-2*m;let y=48,page=1;
    const footer=()=>{d.setFont('Raleway','normal');d.setTextColor(95);d.setFontSize(8);d.text('Year 10 - Review, explain, repeat',m,H-25);d.text(String(page),W-m,H-25,{align:'right'});d.setTextColor(25);};
    const next=()=>{footer();d.addPage();page++;y=48;};
    const room=h=>{if(y+h>H-50)next();};
    function text(s,size=11,gap=8,mono=false){d.setFont(mono?'courier':'Raleway','normal');d.setFontSize(size);for(const p of clean(s).replace(/\t/g,'    ').split('\n')){const lines=d.splitTextToSize(p||' ',w);if(lines.length*size*1.5<H-110)room(lines.length*size*1.5+gap);for(const line of lines){room(size*1.5);d.setFont(mono?'courier':'Raleway','normal');d.setFontSize(size);d.text(line,m,y);y+=size*1.5;}}y+=gap;d.setFont('Raleway','normal');}
    const heading=s=>{room(100);y+=6;d.setDrawColor(190);d.setLineWidth(.4);d.line(m,y,W-m,y);y+=25;d.setTextColor(0,105,48);text(s,15,10);d.setTextColor(25);};
    function photos(group){for(const p of state.photos[group]||[]){const prop=d.getImageProperties(p.data);next();text('Evidence image: '+p.filename,11,8);if(p.caption)text('Caption: '+p.caption,10,8);const scale=Math.min(w/prop.width,(H-y-65)/prop.height);d.addImage(p.data,p.data.startsWith('data:image/png')?'PNG':'JPEG',m,y,prop.width*scale,prop.height*scale);y+=prop.height*scale+12;}}
    text('YEAR 10 COMPUTER SCIENCE',16,9);text('Review, explain, repeat',23,16);text('OxfordAQA 9210 - Checkpoint review and definite iteration',11,14);text('Name: '+state.name,12);text('Class: '+(state.className||'Teacher preview'),12);text('Exported: '+new Date().toLocaleString(),10,17);heading('WAGBA and learning intent');text('WAGBA: use evidence and feedback to improve explanations, and control how many times instructions repeat.');text('Knowledge: marking points, definite iteration, counter and bounds.');text('Skills: improve a written response; trace, modify and test a FOR loop.');text('Understanding: explain a correction, loop bounds and indentation.');heading('Evidence boundaries');text('Checkpoint responses and detailed reflections are written on a paper sheet, not typed into this website. Only the chosen route, question reference, optional marks and progress checks are recorded here. Attachments may include optional complete photos of the paper sheet.');text('Responses, marks, evidence levels and checklist confirmations are self-reported. This is not an automatically marked assessment or a record of verified Teams submission. Python is run in the student’s own IDE. Unanswered core items are labelled.');next();
    const display=q=>{const v=state.answers[q.id];if(q.kind==='checkbox')return v==='yes'?'Confirmed by student':'Not confirmed';if(!v?.trim())return 'Not answered';return q.options?.find(([k])=>k===v)?.[1]||v;};
    const sections=[...new Set(L.questions.map(q=>q.section))];
    for(const section of sections){const qs=L.questions.filter(q=>q.section===section);if(section.startsWith('Extension ')&&!qs.some(q=>state.answers[q.id]?.trim())&&!(state.photos['ext-'+(Number(section.match(/^Extension (\d+)/)[1])-1)]||[]).length)continue;heading(section);
      if(section==='Main Task 1: paper review')text('Detailed checkpoint analysis, corrected answer, explanation and next-step plan: on the student’s paper review sheet. The checks below do not verify accuracy.',10);
      if(section.startsWith('Extension ')){const i=Number(section.match(/^Extension (\d+)/)[1])-1;text('Task: '+L.extensions[i].task,10);text('Test: '+L.extensions[i].test,10);}
      for(const q of qs){room(70);text(q.label,10,3);text(display(q),q.code?10:11,11,!!q.code);}
      if(section==='Main Task 2: modify and test')photos('program');if(section==='Save and submit')photos('paper');if(section.startsWith('Extension '))photos('ext-'+(Number(section.match(/^Extension (\d+)/)[1])-1));
      if(section==='Learning Pit Stop'){const count=prefix=>{const v=L.targets.map(([id])=>state.answers[prefix+id]);return `${v.filter(x=>x==='independent').length}/6 independent; ${v.filter(x=>x==='support').length}/6 with support; ${v.filter(x=>x==='not-yet').length}/6 not yet; ${v.filter(x=>!x).length}/6 unanswered.`;};text('Starting profile (optional baseline): '+count('before-'),10);text('Final self-reported evidence profile: '+count('after-'),10);text('Learning phase and demonstrated evidence are separate. Neither is an exam grade.',10);}
    }
    heading('Optional extension record');L.extensions.forEach((e,i)=>text(`${i+1}. ${e.title}: ${['code','output','explain','status'].some(k=>state.answers['ext-'+i+'-'+k]?.trim())||(state.photos['ext-'+i]||[]).length?'evidence included above':'not attempted / no recorded evidence'}.`,10,5));
    heading('Self-check feedback');if(!state.checkHistory.length)text('No self-checks recorded.');for(const c of state.checkHistory){const q=L.questions.find(q=>q.id===c.id),label=q?.label||({trace:'Counter trace and confirmation count',program:'Compare my program with the model',plenary:'Plenary response comparison'}[c.id]||c.id),answer=q?.options?.find(([k])=>k===c.answer)?.[1]||c.answer;room(90);text(label,10,3);text('Checked: '+new Date(c.time).toLocaleString(),9,3);text('Response at this check: '+answer,10,4,c.id==='program');text(c.message,10,9);}
    heading('Support and walkthrough record');text('Fixed walkthrough steps opened: '+(state.tutorSeen.length?state.tutorSeen.map(i=>i+1).join(', '):'none'),10);if(!state.supportLog.length)text('No support-card requests recorded.',10);for(const s of state.supportLog)text(s.request+' - '+s.page+(s.note?' - '+s.note:''),10,6);
    text('Pages visited: '+state.visited.map(id=>L.pages.find(p=>p.id===id)?.label||id).join('; '),10);room(230);heading('Submit in Microsoft Teams');text('Open this PDF and check all evidence. In the correct Year 10 Computer Science assignment, attach it using Add work / upload and select Turn in. Check the status in Teams. Hand in the paper review sheet as your teacher directs. This website does not upload or confirm submission.');footer();return d;
  }
  // Exactly two A4 pages per route: roomy handwriting areas, no test content or answers.
  function reviewSheets(routeId=null){
    const d=base(),W=595.28,H=841.89,m=42,w=W-2*m;const selected=routeId?[routeId]:['build','strengthen','transfer'];let index=0;
    function write(s,x,y,size=10.5,width=w){d.setFont('Raleway','normal');d.setFontSize(size);d.setTextColor(25);const lines=d.splitTextToSize(clean(s),width);d.text(lines,x,y,{lineHeightFactor:1.35});return y+lines.length*size*1.35;}
    function lines(y,h){d.setDrawColor(200);d.setLineWidth(.35);for(let yy=y+18;yy<y+h;yy+=22)d.line(m,yy,W-m,yy);}
    function block(title,prompt,y,h){d.setTextColor(0,105,48);d.setFontSize(12);d.text(clean(title),m,y);const end=write(prompt,m,y+19,10);lines(end+3,h-(end-y)-3);return y+h;}
    function start(route,pageNumber){if(index++)d.addPage();const r=window.Lesson.routes[route];d.setDrawColor(190);d.setLineWidth(.5);d.line(m,73,W-m,73);d.setTextColor(0,105,48);d.setFontSize(18);d.text('Year 10 - Learning Checkpoint 1',m,39);write(r.label+' | '+r.name,m,60,12);write('Name: _______________________  Class: ______  Date: __________',m,95,11);write('Topic: checkpoint review and definite iteration',m,120,10);write('WAGBA: use evidence and feedback to improve an explanation.',m,139,10);write('K: recognise the credited idea. S: improve and check a response.',m,158,10);write('U: explain why the correction or transfer works.',m,176,10);write('Challenge: justify your answer with a value, example or marking point.',m,195,10);d.setDrawColor(190);d.line(m,209,W-m,209);write('Paper review - '+r.label+' - page '+pageNumber+' of 2',m,H-24,8);}
    for(const route of selected){
      start(route,1);write('Collect your marked question and its relevant marking points from your teacher.',m,231,10);write('Question: ________  Awarded: ____ / ____   Whole-test total (optional): ____ / 40',m,252,10);
      let y=282;
      y=block('1. Locate the evidence',route==='transfer'?'Copy the part of your original answer that earned credit. Identify the relevant marking points.':'Copy the important part of your original answer. Show what earned credit and what was missing or inaccurate.',y,116);
      y=block('2. Identify the learning need',route==='build'?'Choose one missing meaning, rule or step. Is the need knowledge, skill or understanding? Ask for one model if needed.':route==='strengthen'?'Match your answer to the marking points. Which detail needs clearer wording, a fuller reason or more accurate application?':'Explain why your response meets the marking points. Choose a new example with your teacher; do not invent a mistake.',y+10,113);
      y=block('3. Write a better response',route==='transfer'?'Write an answer for the teacher-approved new example. Preserve the correct idea while adapting the values or context.':'Write the improved answer in your own words. Include the missing idea and make the reasoning clear.',y+10,145);
      block('4. Check using evidence','Use an appropriate value, boundary case, trace or marking point. Record what you expected and what your check shows.',y+10,112);
      start(route,2);let z=239;
      z=block('5. Prepare an explanation','Use if helpful: I used ___ because the rule says ___. With the value ___, the result is ___. Write first, then show or read this privately to your teacher.',z,115);
      z=block('6. Show understanding, not just a copied answer',route==='transfer'?'Compare the original and new examples. Explain what stays the same, what changes, and why the approach still works.':'Explain why the change fixes the problem. If comparisons are your focus, write the wording, symbol and one substituted value separately.',z+10,100);
      z=block('7. Plan one specific next step','Name the question or skill; choose an action (trace three values / practise the boundary / rewrite an explanation / discuss one marking point); state what evidence will show improvement.',z+10,98);
      write('8. Reflect on this paper review',m,z+26,12);write('K = recalling the idea; S = applying it; U = explaining why it works.',m,z+46,10);write('Evidence: 0 not yet | 1 with content support | 2 independently. Not a grade.',m,z+64,10);
      write('Knowledge: ____   Skills: ____   Understanding: ____',m,z+87,11);write('Current phase (choose one): new learning / consolidating / treading water /',m,z+109,10);write('drowning - I need help. Which exact step? ___________________________',m,z+127,10);
      write('Private explanation: prepared / shared with support / shared independently',m,z+155,10);write('Teacher check / agreed next step: ___________________________________',m,z+176,10);write('Return this paper as directed. The website records progress checks, not this answer.',m,z+198,9);
    }
    return d;
  }
  window.LessonPDF={notebook,reviewSheets};
})();
