/* Lesson content and guides. Each card has a single practical subgoal. */
window.LESSON = (() => {
  const links = { model:'https://makecode.com/_R5tA5xE2JJJE', student:'https://makecode.com/_ioxHMeYpd4Wg', reactor:'https://makecode.com/_2sPdRM1ejWfR', editor:'https://arcade.makecode.com/' };
  const stages = ['Mission briefing','Do Now','Types of Learning','Main Task 1','Main Task 2','Learning Pit Stop','Go Further','Plenary','Save & submit'];
  const guide = (src,alt,notes,marks=[]) => ({src:'assets/guides/'+src,alt,notes,marks});
  const guides = {
    open:guide('open-template.jpg','Shared Countdown Crew game. The Edit Code icon is in the top bar.',['Select the pencil-in-a-square icon: Edit Code.','You will be editing your own local copy, not the teacher’s published example.'],[{x:85.5,y:1,w:4.1,h:7,n:1}]),
    editor:guide('editor-blocks.jpg','MakeCode Arcade editor with simulator on the left, toolbox in the middle and Blocks workspace on the right.',['1 Simulator: run and observe your game.','2 Toolbox: find blocks. You do not need to add artwork today.','3 Workspace: change the countdown code.'],[{x:1,y:9,w:29,h:46,n:1},{x:33,y:8,w:16,h:64,n:2},{x:50,y:25,w:33,h:42,n:3}]),
    language:guide('language-menu.jpg','Arcade editor language menu with a Python choice.',['Choose Blocks at the top for the beginner route.','For Python, open the code-language arrow and select Python.','This is Arcade Python, not micro:bit MicroPython.']),
    name:guide('name-save.jpg','Project name field beside the floppy-disk Save button.',['1 Replace the existing project name with your class and first name.','2 At the end, this Save button downloads an editable project PNG.'],[{x:2,y:14,w:65,h:77,n:1},{x:67,y:14,w:14,h:77,n:2}]),
    controls:guide('game-controls.jpg','Countdown game simulator with A, B and the simulator toolbar.',['1 A starts this template’s countdown.','2 B resets this game so you can test again.','3 The toolbar’s restart button also restarts the simulator.'],[{x:77,y:59,w:18,h:13,n:1},{x:63,y:72,w:18,h:13,n:2},{x:18,y:91,w:13,h:9,n:3}]),
    loop:guide('countdown-blocks.jpg','The student’s actual Blocks countdown: set countdown to 5, while countdown is greater than 0, show count, pause 1000 milliseconds, change by minus 1, then launch.',['The four jobs are: start, check, wait and change.','show_count displays the number. launch_pod runs after the loop stops.']),
    start:guide('countdown-blocks.jpg','Starting-value field in the set countdown block.',['Select the white 5 in set countdown to 5. Replace it with 7.','Keep the condition, pause and counter change unchanged for this test.'],[{x:57,y:4,w:14,h:12,n:1}]),
    speed:guide('countdown-blocks.jpg','Pause value in the countdown while loop.',['Select the 1000 field in pause. Type 500.','If a preset menu opens, use its editable value field.'],[{x:28,y:47,w:25,h:13,n:1}]),
    step:guide('countdown-blocks.jpg','Minus-one counter-change value near the bottom of the loop.',['The counter change is inside the while block.','Change this value only when a challenge tells you to.'],[{x:74,y:60,w:16,h:14,n:1}]),
    condition:guide('countdown-blocks.jpg','The countdown loop’s greater-than-zero condition.',['The loop checks countdown > 0 before each repetition.','At 0 the condition is false. The loop ends before displaying 0.'],[{x:62,y:17,w:28,h:15,n:1}]),
    pythonLoop:guide('countdown-python.jpg','Actual Arcade Python student loop at the bottom of the template.',['Scroll to STUDENT MISSION near the bottom of the Python editor.','Keep the indented display, pause and change lines inside while.','launch_pod() is not indented: it runs after the loop.']),
    pythonStart:guide('countdown-python.jpg','Arcade Python countdown assignment highlighted.',['Change only countdown = 5 to countdown = 7.'],[{x:9,y:11,w:36,h:15,n:1}]),
    pythonSpeed:guide('countdown-python.jpg','Arcade Python pause statement highlighted.',['Change pause(1000) to pause(500). Keep its indentation.'],[{x:17,y:53,w:31,h:15,n:1}]),
    pythonStep:guide('countdown-python.jpg','Arcade Python counter change highlighted.',['countdown += -1 subtracts one. Edit the negative number for the challenge.'],[{x:17,y:67,w:43,h:15,n:1}]),
    reactor:guide('reactor-blocks.jpg','Actual reactor Blocks loop: charge starts at zero, repeats while below six, adds one, displays charge and pauses.',['The charge starts at 0. This loop adds before it displays.','For the challenge, change the +1 step to +2. Keep charge < 6.'],[{x:68,y:31,w:19,h:13,n:1}]),
    pythonReactor:guide('reactor-python.jpg','Actual Arcade Python recharge loop with charge = 0, while charge < 6 and charge += 1.',['Find this short loop at the bottom of the reactor project.','Change charge += 1 to charge += 2, keeping the indentation.'],[{x:8,y:43,w:39,h:15,n:1}]),
    reactorResult:guide('reactor-result.jpg','Completed reactor showing READY, charge 6 and a green filled meter.',['This is the original +1 example after completion.','Use the number display, not just the green meter, to trace your changed code.'])
  };
  const choice = (id,label,options,correct,explanation) => ({id,label,type:'choice',options,correct,explanation,required:true});
  const select = (id,label,options,required=true) => ({id,label,type:'select',options,required});
  const text = (id,label,prompt,required=true) => ({id,label,type:'text',prompt,required});
  const check = (id,label,required=true) => ({id,label,type:'check',required});
  const confidence = ['Already confident','Need a reminder','Need help to start'];
  const cards = [
    {id:'brief',stage:0,title:'Your crew needs a safe launch',tag:'Welcome aboard · 3 minutes',intro:'Today you are the countdown engineer. You will turn a working space scene into your own launch sequence.',body:'Your crew is preparing a launch pod. The countdown gives everyone time to get ready before the pod leaves. A variable stores the current number, and a while loop repeats the countdown while its condition is true. Today, you will test the existing launch sequence, change its starting number and speed, and check that it still reaches a safe ending.',demo:true,fields:[check('read-brief','I understand the mission: change and test a countdown, not build the artwork.')],help:'No micro:bit, cables or Bluetooth are needed. The game runs in your browser. You will use two tabs: this lesson for guidance, and MakeCode for coding.'},
    {id:'starter',stage:1,title:'Predict before you press A',tag:'Do Now · 5 minutes',intro:'A countdown starts at 5, shows the number, pauses, then subtracts 1. It repeats while countdown > 0.',guide:'loop',fields:[choice('starter-sequence','1. Which numbers appear first?',['5, 4, 3','0, 1, 2','5, 5, 5'],0,'The number begins at 5 and decreases by one after each display: 5, 4, 3.'),choice('starter-condition','2. What does countdown > 0 check?',['Whether the current number is greater than zero','Whether the pause lasts zero seconds','Whether the player pressed A'],0,'The condition checks the current number. The A input starts the mission; it is not this while condition.'),choice('starter-change','3. If the counter never changes, what could happen?',['The loop could keep repeating without ending','The game would always launch after one repetition','The pause would become faster'],0,'If countdown stays at 5, then 5 > 0 stays true. A counter change can help the condition eventually become false.')],help:'Choose your best answer. Feedback explains the idea; a wrong answer does not lock the next card.'},
    {id:'types',stage:2,title:'What will you get better at?',tag:'Types of Learning · 3 minutes',intro:'Think about today’s actual knowledge, skills and understanding. This is a starting point, not a grade.',ksu:true,fields:[select('before-k','Knowledge: explain what a counter and a condition do.',confidence),select('before-s','Skills: find a value, change it and test the game.',confidence),select('before-u','Understanding: explain why a loop eventually stops.',confidence)],help:'Knowledge: point to a counter and say what it stores. Skills: practise one edit and test it. Understanding: trace the last number and check the condition. Ask a partner to explain, but make your own changes.'},
    {id:'open',stage:3,title:'Open your launch mission',tag:'Main Task 1 · Open',intro:'Your scene and artwork are already prepared. Open the student template, not a blank project.',where:'MakeCode editor tab',guide:'open',link:'student',linkLabel:'Open My Launch Sequence ↗',steps:['Select the large editor button below. A separate tab opens.','On the shared game page, select <strong>Edit Code</strong>—the pencil-in-a-square icon.','Keep this lesson tab open. Come back here for the next instruction.'],fields:[check('opened','I can see my editable copy in MakeCode.')],help:'If pop-ups are blocked, use the link again. If the link is unavailable, download the local template below, then Arcade Home → Import → Import File. No sign-in is required.',backup:2},
    {id:'name',stage:3,title:'Give your mission a name',tag:'Main Task 1 · Name',intro:'A recognisable project name helps you find your game again. You are still working in your own editable copy.',where:'MakeCode editor tab',guide:'name',steps:['Find the project-name box beside the floppy-disk Save button.','Replace the template title with <strong>Y8_Class_FirstName_Countdown</strong>.','Return to this lesson tab and record the name below.'],fields:[{id:'project-name',label:'The project name I used',type:'input',prompt:'For example: Y8_8T_Aisha_Countdown',required:true}],help:'Changing the name does not change the game. Do not click hardware Download: we will use Save to back up the project near the end.'},
    {id:'orient',stage:3,title:'Choose your route. Find your way.',tag:'Main Task 1 · Navigate',intro:'Choose one coding language and match it in your MakeCode tab. You do not need to switch repeatedly.',where:'MakeCode editor tab',guide:'editor',pythonGuide:'language',steps:['For <strong>Blocks</strong>, select Blocks at the top of the editor. For <strong>Arcade Python</strong>, open the code-language arrow and select Python.','Find the <strong>simulator</strong>: it tests the game. Find the <strong>workspace</strong>: it is where you edit. The toolbox holds blocks and code snippets.','Leave the prepared artwork and functions alone. Your next cards will point to the short countdown section.'],fields:[check('route-match','My selected route here matches the language in my MakeCode editor.')],help:'On a tablet, use landscape if you can. If the simulator is hidden, use the Show simulator control. The editor layout may move on smaller screens; use the control names shown here.'},
    {id:'try',stage:3,title:'Give your game a test flight',tag:'Main Task 1 · Run',intro:'Do not change the code yet. First find out what the original game does.',where:'MakeCode simulator',guide:'controls',steps:['Press the on-screen <strong>A</strong> button in the simulator.','Watch: <strong>5, 4, 3, 2, 1</strong>, then <strong>GO!</strong> and the launch.','Press <strong>B</strong> to reset. Press A again to prove you can replay it.'],fields:[select('baseline-result','What did your original game do?',['Counted down and launched','The game opened, but I need help running it','The game did not load; I need technical help'])],help:'After editing, wait for MakeCode to rebuild the game. Use its restart control if needed, then press A. Use the simulator’s keyboard-shortcut button to see controls for your device.'},
    {id:'find',stage:3,title:'Meet the four countdown jobs',tag:'Main Task 1 · Investigate',intro:'This is the short section you will edit. You do not need to understand all the prepared scene code.',guide:'loop',pythonGuide:'pythonLoop',body:'Start: countdown = 5 gives the counter a value. Check: countdown > 0 decides whether another repetition runs. Wait: pause(1000) spaces out the displays. Change: countdown += -1 moves the counter towards stopping.',fields:[choice('find-change','Which instruction moves the counter towards zero?',['Change countdown by -1','Call show_count','Pause 1000 milliseconds'],0,'Subtracting one changes the counter. show_count displays it; pause changes the waiting time.')],help:'Blocks: find the on start stack. Python: scroll to STUDENT MISSION at the bottom. Leave show_count and launch_pod in place; they are prepared display helpers.'},
    {id:'longer',stage:4,title:'Give the crew a seven-count warning',tag:'Main Task 2 · Modify one value',intro:'Mission Control needs more warning before launch. Change the starting number, not the speed.',where:'MakeCode editor tab',guide:'start',pythonGuide:'pythonStart',steps:['Find <strong>set countdown to 5</strong>. In Python, find <strong>countdown = 5</strong>.','Replace <strong>5</strong> with <strong>7</strong>. Leave the other values unchanged.','Restart if needed, then press <strong>A</strong>. Compare the game with your prediction.'],code:'countdown = 7',expected:'7, 6, 5, 4, 3, 2, 1 → GO!',fields:[choice('longer-predict','Before testing: what should appear first?',['7','5','0'],0,'The starting value is now 7. This change adds two repetitions; it does not change the pause.'),select('longer-result','After testing: what happened?',['It started at 7 and launched','It still started at 5','I need help testing this change'])],help:'Click or tap the number itself, not the variable-name arrow. If your game still starts at 5, check the value, wait for the editor to rebuild and restart the simulator.'},
    {id:'faster',stage:4,title:'Same warning. Faster rhythm.',tag:'Main Task 2 · Change the wait',intro:'Keep the seven-count warning, but make the pause between numbers shorter.',where:'MakeCode editor tab',guide:'speed',pythonGuide:'pythonSpeed',steps:['Inside the while loop, find <strong>pause 1000 ms</strong> or <strong>pause(1000)</strong>.','Replace <strong>1000</strong> with <strong>500</strong>. Keep the start at 7 and the change at -1.','Restart, press <strong>A</strong> and watch the same sequence run faster.'],code:'pause(500)',expected:'The same seven numbers, with about half a second between displays.',fields:[choice('speed-effect','What changes when pause changes from 1000 to 500?',['The waiting time, not the numbers or repetition count','The countdown now starts at 500','The loop has 500 repetitions'],0,'The pause affects waiting time. The start, condition and counter change still determine the displayed numbers.'),select('faster-result','After testing: did your game keep the numbers but run faster?',['Yes—same numbers, shorter wait','No—I need to check my edit','I need help running the test'])],help:'500 ms is half a second. Keep a pause in the loop. This classroom countdown is not a precision clock: simulator performance also affects timing.'},
    {id:'prove',stage:4,title:'Show your launch works',tag:'Main Task 2 · Demonstrate',intro:'Run your game again. Use these criteria to check the result, then capture one useful screenshot.',where:'MakeCode simulator, then this lesson tab',guide:'condition',pythonGuide:'pythonLoop',fields:[check('proof-start','My countdown starts at 7.'),check('proof-step','It decreases by 1 and waits 500 ms between numbers.'),check('proof-launch','It reaches GO!, launches and can be reset.'),text('stop-explain','Why does your loop stop?','Sentence frame: My loop stops when countdown is ___ because ___ > ___ is false. You may explain in your support language or show your teacher.'),check('spoken-proof','I explained this aloud to my teacher instead of writing.',false)],evidence:'code',help:'Take a screenshot of the relevant countdown code. Upload it or paste it here. If taking a screenshot is difficult, show your running game and code to your teacher; choose the teacher-check option below. A tick is your report, not an automatic code check.'},
    {id:'pit',stage:5,title:'Where is your learning now?',tag:'Learning Pit Stop · 3 minutes',intro:'Use what you actually did today. This is about your next useful step, not a label for you as a person.',fields:[check('pit-k','Knowledge: I can name the counter and the condition.',false),check('pit-s','Skills: I changed one value at a time and tested it.',false),check('pit-u','Understanding: I can explain why 0 is not displayed.',false),select('pit-feeling','How did this learning feel?',['New learning: a good struggle with new ideas','Consolidating: I am getting more confident','Treading water: I can do this and need more challenge','Drowning: I feel stuck and need help']),text('pit-help','A specific thing I want help with or want to challenge next','For example: Find the pause value / explain the last repetition / try a larger counter step.',false)],pit:true,help:'If you are stuck, point to the exact card or value and ask for help. If you are confident, try a Go Further mission. Your feelings and the evidence may differ—talk them through with your teacher.'},
    {id:'fast',stage:6,title:'Mission 1: Fast launch',tag:'Go Further · Apply',intro:'If you have time, make a countdown that shows three numbers before launch. Keep your existing countdown project.',where:'Your current MakeCode countdown project',guide:'step',pythonGuide:'pythonStep',steps:['Set the starting value to <strong>6</strong>.','Change the counter step from <strong>-1 to -2</strong>. Keep <strong>countdown > 0</strong> and the pause.','Predict the numbers. Run the game and check whether it launches.'],fields:[text('fast-predict','Predict the displayed numbers','Write the numbers in order, separated by commas.'),select('fast-result','What did your game do?',['It showed 6, 4, 2 then launched','It showed a different sequence','I need help testing'])],help:'Trace each repetition: show the current value, wait, then subtract 2. The counter becomes 0 after displaying 2. Do not run a version with no counter change or no pause.'},
    {id:'reactor',stage:6,title:'Mission 2: Recharge the reactor',tag:'Go Further · Transfer',intro:'Use the new reactor project to investigate counting up. Keep your countdown project saved so you can return to it.',where:'New MakeCode reactor editor tab',guide:'reactor',pythonGuide:'pythonReactor',link:'reactor',linkLabel:'Open Reactor Recharge ↗',backup:3,steps:['Open the reactor template and select <strong>Edit Code</strong>. Choose your same coding language.','Run the original: A starts; B replays. It begins at 0 and charges to 6.','Change <strong>change charge by 1</strong> to <strong>2</strong>, or <strong>charge += 1</strong> to <strong>charge += 2</strong>. Run it again.'],fields:[choice('reactor-predict','With +2, which new charge values should appear after A?',['2, 4, 6','1, 2, 3','6, 4, 2'],0,'The prepared display shows 0 before A. Each loop repetition then adds 2 before displaying, so the new values are 2, 4, 6.'),select('reactor-result','After changing the step, what happened?',['It reached 6 and READY','It did something else','I need help testing']),text('reactor-extra','Stretch: change the condition to charge < 5. With +2, does it finish at exactly 5? Why?','Trace: 0 → 2 → 4 → ___. Does that final value make the condition false?',false)],help:'The meter is capped at six units. Use the number display to trace values. With a target of 5 and +2, the value passes 5; less than 5 can still become false safely.'},
    {id:'designer',stage:6,title:'Mission 3: You are the flight engineer',tag:'Go Further · Design',intro:'Return to your countdown game. Design a launch that shows exactly 9, 6, 3, then GO! Leave the prepared artwork unchanged.',where:'Your MakeCode countdown project',guide:'loop',pythonGuide:'pythonLoop',body:'Choose the starting value, counter step and a readable pause. Keep the condition countdown > 0. You have the required output, but not a full solution. Make and test your own choices.',fields:[{id:'design-start',label:'My starting value',type:'input',prompt:'Enter your choice',required:true},{id:'design-step',label:'My counter change',type:'input',prompt:'Include + or -',required:true},{id:'design-pause',label:'My pause in milliseconds',type:'input',prompt:'For example: 750',required:true},select('design-result','Did it show 9, 6, 3 and launch?',['Yes, I tested the required sequence','Not yet; I am debugging','I need help']),text('design-explain','Explain why your design stops safely','The counter changes by ___ until it reaches ___. Then the condition ___ is false.',false)],help:'If you get stuck, subtract the difference between two required numbers. Test one change at a time. Do not replace the safe > 0 condition with a condition you have not traced.'},
    {id:'plenary',stage:7,title:'Your final flight check',tag:'Plenary · 4 minutes',intro:'These checks use the main mission: start at 7, change by -1, while countdown > 0. Answer without reopening the example first.',fields:[choice('exit-zero','1. Why is 0 not displayed?',['The condition becomes false before the next display','Zero cannot be displayed in Arcade','A pause prevents zero'],0,'After displaying 1, the counter becomes 0. The next condition check is false, so launch_pod runs instead of showing 0.'),choice('exit-pause','2. To keep the same numbers but slow the warning, what should you change?',['Increase the pause','Increase the counter step','Replace > with <'],0,'A larger pause means a longer wait between displays. It does not change the number sequence.'),text('exit-transfer','3. What would you check if a countdown never reached GO!?','I would check ___ because ___. Short phrases, your support language or a teacher-recorded spoken answer are welcome.')],help:'Look for a counter change that moves towards making the condition false. If a test runs endlessly, stop the simulator and restore your last working version.'},
    {id:'save',stage:8,title:'Keep your game. Keep your evidence.',tag:'Save & submit · Back up',intro:'There are two different things to save: your editable MakeCode game and your lesson report.',where:'MakeCode editor, then this lesson tab',guide:'name',steps:['In your countdown project, check its name. Select the <strong>Save</strong> button beside the name—not the hardware Download button.','Keep the downloaded <strong>project PNG</strong>. It contains your code and artwork. Do not resize or edit it as a photo.','Here, export your PDF report. Use Work tools → Download lesson backup if you need to continue on another device.'],fields:[check('saved-game','I saved the editable project PNG, or my teacher helped me back it up.'),check('checked-evidence','I checked that my name, class and evidence are ready for my report.')],help:'To restore a project PNG: Arcade Home → Import → Import File. MakeCode browser storage and this lesson’s storage are separate. Clearing browser data can remove both; a downloaded backup protects you.'},
    {id:'review',stage:8,title:'Your mission report',tag:'Save & submit · Review',intro:'Review what you have completed. You can export your current progress even when some sections are unfinished.',review:true,fields:[]}
  ];
  const languageHelp = {
    en:[],
    zh:[
      '你的任务是修改并测试倒计时。场景已经准备好，不需要 micro:bit 或蓝牙。',
      '先预测数字，再选择答案。答错后阅读反馈；你仍然可以继续。',
      '知识：解释计数器和条件。技能：修改一个数值并测试。理解：解释循环为什么停止。',
      '点击打开项目按钮，然后在新页面点击 Edit Code（编辑代码）。保留本课程标签页。',
      '修改项目名称。初学者选 Blocks；如用 Python，请选择 Arcade Python，不是 MicroPython。',
      '在模拟器按 A 开始，按 B 重置。观察 5、4、3、2、1，然后发射。',
      '找到起始值、条件、暂停和计数器变化。只修改学生的循环，不修改预设场景。',
      '把起始值 5 改为 7。其他数值不变。按 A 测试并比较你的预测。',
      '把 pause 的 1000 改为 500 毫秒。数字相同，等待时间变短。保留缩进。',
      '运行游戏并检查要求。粘贴或上传代码截图；也可以请老师检查。句型：循环在 ___ 时停止，因为条件 ___ 为假。',
      '根据今天实际完成的任务评价学习。勾选你能解释的项目，再说明是新学习、巩固、太容易或需要帮助。',
      '把起始值设为 6，每次减 2。先预测，再测试。条件仍然是 countdown > 0。',
      '打开反应堆项目。把每次增加 1 改为增加 2。观察数字，不只是绿色仪表。',
      '设计显示 9、6、3 后发射的倒计时。自己选择起始值、每次变化和暂停。',
      '用本节课的概念回答。可以写短语或用中文解释：我会检查 ___，因为 ___。',
      '在 MakeCode 点击项目名旁的 Save，保存含代码的 PNG。这里保存课程回答和 PDF，是不同的文件。',
      '检查姓名、班级和证据。未完成部分会标明。把 PDF 附加到 Teams 作业，再点击 Turn in。'
    ],
    ko:[
      '오늘의 임무는 카운트다운을 수정하고 테스트하는 것입니다. 장면은 준비되어 있습니다. micro:bit나 블루투스가 필요하지 않습니다.',
      '먼저 숫자를 예측한 뒤 답을 고르세요. 틀리면 설명을 읽으세요. 다음 카드로 계속 갈 수 있습니다.',
      '지식: 카운터와 조건을 설명하기. 기능: 값 하나를 바꾸고 테스트하기. 이해: 반복이 끝나는 이유 설명하기.',
      '프로젝트 열기 버튼을 누른 뒤 새 페이지에서 Edit Code를 선택하세요. 수업 탭은 닫지 마세요.',
      '프로젝트 이름을 바꾸세요. 처음이면 Blocks를 선택하세요. Python은 Arcade Python이며 MicroPython이 아닙니다.',
      '시뮬레이터에서 A를 누르면 시작하고 B를 누르면 초기화됩니다. 5, 4, 3, 2, 1 다음에 발사됩니다.',
      '시작 값, 조건, 대기 시간, 카운터 변화를 찾으세요. 준비된 장면 코드는 그대로 두세요.',
      '시작 값을 5에서 7로 바꾸세요. 다른 값은 그대로 두고 A를 눌러 예측과 비교하세요.',
      'pause의 1000을 500밀리초로 바꾸세요. 숫자는 같고 기다리는 시간은 줄어듭니다. 들여쓰기를 유지하세요.',
      '게임을 실행해 요구 사항을 확인하세요. 코드 화면을 붙여넣거나 업로드하세요. 선생님에게 보여 주어도 됩니다. 문장 틀: ___일 때 조건 ___가 거짓이 되어 반복이 끝납니다.',
      '오늘 실제로 한 일을 바탕으로 생각하세요. 설명할 수 있는 항목을 체크하고 현재 느낌을 선택하세요.',
      '시작은 6, 변화는 -2로 설정하세요. 먼저 예측하고 테스트하세요. 조건은 countdown > 0을 유지하세요.',
      '원자로 프로젝트를 여세요. 증가 값을 1에서 2로 바꾸세요. 녹색 표시뿐 아니라 숫자를 확인하세요.',
      '9, 6, 3을 표시한 뒤 발사되도록 설계하세요. 시작 값, 변화 값, 대기 시간을 직접 선택하세요.',
      '오늘 배운 개념으로 답하세요. 짧은 문구나 한국어로 설명해도 됩니다. 문장 틀: ___ 때문에 ___를 확인하겠습니다.',
      'MakeCode에서 프로젝트 이름 옆 Save를 눌러 코드가 담긴 PNG를 저장하세요. 수업 답변과 PDF는 별도로 저장됩니다.',
      '이름, 반, 증거를 확인하세요. 미완료 부분도 표시됩니다. Teams 과제에 PDF를 첨부한 뒤 Turn in을 누르세요.'
    ],
    ms:[
      'Misi anda ialah mengubah dan menguji kiraan detik. Adegan sudah disediakan. Tidak perlu micro:bit atau Bluetooth.',
      'Ramalkan nombor dahulu, kemudian pilih jawapan. Baca maklum balas jika tersilap; anda masih boleh meneruskan.',
      'Pengetahuan: terangkan pembilang dan syarat. Kemahiran: ubah satu nilai dan uji. Kefahaman: terangkan sebab gelung berhenti.',
      'Tekan butang untuk membuka projek, kemudian pilih Edit Code. Jangan tutup tab pelajaran ini.',
      'Namakan projek. Pilih Blocks jika baharu. Python di sini ialah Arcade Python, bukan MicroPython.',
      'Tekan A dalam simulator untuk mula dan B untuk mula semula. Perhatikan 5, 4, 3, 2, 1, kemudian pelancaran.',
      'Cari nilai awal, syarat, jeda dan perubahan pembilang. Jangan ubah kod adegan yang telah disediakan.',
      'Tukar nilai awal daripada 5 kepada 7. Biarkan nilai lain. Tekan A dan bandingkan dengan ramalan.',
      'Tukar pause daripada 1000 kepada 500 milisaat. Nombor sama, masa menunggu lebih pendek. Kekalkan inden.',
      'Uji permainan dan semak kriteria. Tampal atau muat naik tangkap layar kod, atau tunjukkan kepada guru. Ayat: Gelung berhenti apabila ___ kerana syarat ___ menjadi palsu.',
      'Nilai berdasarkan kerja sebenar hari ini. Tandakan perkara yang boleh anda terangkan dan pilih perasaan anda.',
      'Mulakan pada 6 dan tolak 2 setiap kali. Ramalkan, kemudian uji. Kekalkan countdown > 0.',
      'Buka projek reaktor. Tukar penambahan 1 kepada 2. Perhatikan nombor, bukan meter hijau sahaja.',
      'Reka kiraan yang memaparkan 9, 6, 3 sebelum pelancaran. Pilih nilai awal, perubahan dan jeda sendiri.',
      'Jawab menggunakan konsep hari ini. Frasa pendek atau Bahasa Melayu diterima. Ayat: Saya akan semak ___ kerana ___.',
      'Di MakeCode, pilih Save di sebelah nama projek untuk menyimpan PNG yang mengandungi kod. Jawapan pelajaran dan PDF disimpan berasingan.',
      'Semak nama, kelas dan bukti. Bahagian belum siap ditunjukkan. Lampirkan PDF dalam tugasan Teams, kemudian pilih Turn in.'
    ]
  };
  const vocab = {
    counter:['a variable storing the current number','计数器：存储当前数字的变量','카운터: 현재 숫자를 저장하는 변수','pembilang: pemboleh ubah yang menyimpan nombor semasa'],
    condition:['a check that is true or false','条件：结果为真或假的判断','조건: 참 또는 거짓인 확인','syarat: semakan benar atau palsu'],
    while:['repeat while a condition is true','while：条件为真时重复','while: 조건이 참인 동안 반복','while: ulang selagi syarat benar'],
    pause:['wait for a number of milliseconds','暂停：等待指定的毫秒数','pause: 정해진 밀리초 동안 기다리기','jeda: tunggu selama beberapa milisaat'],
    test:['run and compare with a prediction','测试：运行并比较预测与结果','테스트: 실행하고 예측과 비교하기','uji: jalankan dan banding dengan ramalan']
  };
  const starter=cards.find(c=>c.id==='starter'),starterFields=starter.fields;
  starter.title='Predict the first three numbers';starter.fields=[starterFields[0]];
  cards.splice(2,0,
    {id:'starter-condition',stage:1,title:'Read the condition',tag:'Do Now · Check',intro:'The countdown repeats while countdown > 0. A condition is a check whose result is true or false.',guide:'condition',pythonGuide:'pythonLoop',fields:[starterFields[1]],help:'Read > as greater than. Imagine the counter currently holds 5: 5 > 0 is true. At 0, 0 > 0 is false.'},
    {id:'starter-update',stage:1,title:'Will the mission ever finish?',tag:'Do Now · Think',intro:'The counter normally decreases after each display. Imagine that the change instruction was missing. Do not delete it or run that faulty version.',guide:'step',pythonGuide:'pythonStep',fields:[starterFields[2]],help:'If the counter stays at 5, the same condition stays true. Explain your prediction to a partner; a wrong answer is a useful starting point.'}
  );
  languageHelp.zh.splice(5,0,'选择与课程一致的编程方式。Blocks 是积木；Arcade Python 通过顶部语言菜单打开。找到模拟器和编辑区。');
  languageHelp.ko.splice(5,0,'수업에서 고른 언어와 편집기의 언어를 맞추세요. Blocks 또는 위쪽 메뉴의 Arcade Python을 선택하세요. 시뮬레이터와 작업 공간을 찾으세요.');
  languageHelp.ms.splice(5,0,'Pilih bahasa yang sama dengan pilihan pelajaran. Gunakan Blocks atau pilih Arcade Python melalui menu bahasa. Cari simulator dan ruang kerja.');
  languageHelp.zh.splice(2,0,'条件是结果为真或假的判断。把 countdown > 0 读作“倒计时数字大于零”。','想象计数器没有变化。如果数字一直是 5，条件还会为真吗？不要运行故障版本。');
  languageHelp.ko.splice(2,0,'조건은 참 또는 거짓인 확인입니다. countdown > 0은 카운터가 0보다 큰지 확인합니다.','카운터가 바뀌지 않는다고 상상하세요. 값이 계속 5라면 조건은 계속 참일까요? 잘못된 코드는 실행하지 마세요.');
  languageHelp.ms.splice(2,0,'Syarat ialah semakan benar atau palsu. countdown > 0 menyemak sama ada nilai pembilang lebih besar daripada sifar.','Bayangkan nilai pembilang tidak berubah. Jika kekal pada 5, adakah syarat masih benar? Jangan jalankan versi yang salah.');
  cards.find(c=>c.id==='starter').pythonGuide='pythonLoop';
  // Keep the old card order so saved work and earlier backups resume correctly.
  const legacyCardIds=cards.map(c=>c.id);
  const reactorIndex=cards.findIndex(c=>c.stage===4);
  stages.splice(4,0,'Reactor Rush');
  cards.forEach(c=>{if(c.stage>=4)c.stage++;});
  const prediction=choice('rush-predict','Before the faster round: start stays 5, but pause changes from 1000 ms to 500 ms. What changes?',[
    'Still 5 repetitions, but less time to charge.',
    '10 repetitions because the pause is shorter.',
    'The counter now starts at 500.'
  ],0,'The counter still goes 5, 4, 3, 2, 1. The loop repeats 5 times. A 500 ms pause halves the intended round time; it does not change the starting counter.');
  prediction.required=false;
  cards.splice(reactorIndex,0,{
    id:'reactor-rush',stage:4,game:true,title:'Reactor Rush: charge before launch',tag:'Crew break · 3–4 minutes',
    intro:'Try the 5-second round, make a prediction, then try the faster round. Each tap is an input; the while loop controls how long charging stays open.',
    fields:[prediction],help:'Tap Charge, or focus it and press Space or Enter. Holding a key does not earn extra presses. Your speed is not a grade. You may go straight to Main Task 2.'
  });
  const support={
    zh:'先玩 5 秒回合，再预测并尝试快回合。两轮都重复 5 次；等待从 1000 毫秒变为 500 毫秒。点击是输入，不是循环重复次数。速度不计入成绩；你可以直接继续主任务 2。',
    ko:'먼저 5초 라운드를 하고, 예측한 뒤 빠른 라운드를 해 보세요. 두 라운드 모두 5번 반복합니다. 대기 시간만 1000ms에서 500ms로 바뀝니다. 누르기는 입력이지 반복 횟수가 아닙니다. 속도는 성적이 아니며 바로 주요 과제 2로 가도 됩니다.',
    ms:'Cuba pusingan 5 saat, buat ramalan, kemudian cuba pusingan lebih pantas. Kedua-duanya mengulang 5 kali; jeda berubah daripada 1000 ms kepada 500 ms. Ketikan ialah input, bukan ulangan gelung. Kelajuan bukan markah; anda boleh terus ke Tugasan Utama 2.'
  };
  Object.entries(support).forEach(([language,words])=>languageHelp[language].splice(reactorIndex,0,words));
  return {id:'year8-arcade-countdown-v1',contentRevision:2,legacyCardIds,reactorIndex,title:'Countdown Crew',topic:'Countdown games using while loops',wagba:'We are getting better at modifying and testing a while loop to control a game countdown.',ksu:['I know the purpose of a counter, a condition and a pause.','I can open an Arcade project, change one value at a time and test the result.','I can explain how the counter changes and why the loop eventually stops.'],challenge:'Adapt a loop to meet a new mission requirement and explain why it stops safely.',links,stages,guides,cards,languageHelp,vocab};
})();
