const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {JSDOM}=require('/tmp/year9-live-test/node_modules/jsdom');const root=path.join(__dirname,'..'),classId='c429701c-21c3-4e99-b84d-c2faadca7afb',lessonId='Year11_week6_relational_sql_merged';
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
async function boot(teacher=false){
 const html=read('index.html').replace(/<script[\s\S]*?<\/script>/g,'');const dom=new JSDOM(html,{url:`https://school.test/lesson/${teacher?'?teacher=1':''}`,runScripts:'dangerously',pretendToBeVisual:true});const w=dom.window,d=w.document;
 w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.CSS.escape=w.CSS.escape||String;w.confirm=()=>true;w.AbortSignal=AbortSignal;
 let timer=0;const jobs=new Map();w.setTimeout=(fn,delay=0)=>{jobs.set(++timer,{fn,delay});return timer};w.clearTimeout=id=>jobs.delete(id);w.setInterval=()=>++timer;w.clearInterval=()=>{};
 let state={version:1,lesson:lessonId,class_id:classId,session_id:'00000000-0000-4000-8000-000000000002',stage:'page-0',locked:false,mode:'self',revision:0,bring_revision:0,return_revision:0,demo:{open:false,demo_revision:0},expires_at:new Date(Date.now()+3600000).toISOString(),server_now:new Date().toISOString(),ended:false};const channels=[],sent=[],tracked=[];
 const client={auth:{getSession:async()=>({data:{session:teacher?{}:null}}),onAuthStateChange:()=>({}),signOut:async()=>{},signInWithPassword:async()=>({})},rpc:(name,args)=>({abortSignal:async()=>{if(name==='classroom_is_teacher')return{data:true};if(name==='classroom_class_current'||name==='classroom_class_snapshot'||name==='classroom_class_start')return{data:{...state}};if(name==='classroom_teach_control'){state={...state,revision:state.revision+1};if(args.p_stage){state.stage=args.p_stage;state.bring_revision++}if(['attention','view','answer'].includes(args.p_action)){state.locked=true;state.mode=args.p_action}if(['self','return','end'].includes(args.p_action)){state.locked=false;state.mode='self';state.demo={open:false,demo_revision:state.demo.demo_revision+1}}if(args.p_action==='return')state.return_revision++;return{data:{...state,ended:args.p_action==='end'}}}if(name==='classroom_demo_save'){state.demo={...args.p_demo,demo_revision:(state.demo.demo_revision||0)+1};return{data:{...state.demo}}}throw Error(name)}}),channel:name=>{const callbacks={};const ch={name,on(type,filter,fn){callbacks[filter.event]=fn;return this},subscribe(fn){w.setTimeout(()=>fn('SUBSCRIBED'),0);return this},send:async msg=>{sent.push(msg);return'ok'},track:async value=>{tracked.push(value);return'ok'},presenceState:()=>teacher?{'00000000-0000-4000-8000-000000000003':[{v:2,revision:state.revision,mode:state.mode}]}:{},emit(event,payload){callbacks[event]({payload})}};channels.push(ch);return ch},removeChannel:async()=>{}};w.supabase={createClient:()=>client};
 for(const f of ['lesson.js','app.js','teacher-presentation.js','live-demo.js','classroom-config.js','classroom.js']){const s=d.createElement('script');s.textContent=read(f);d.body.append(s)}
 async function flush(){for(let round=0;round<30;round++){await Promise.resolve();const run=[...jobs.entries()].filter(([,j])=>j.delay<=2000);for(const[id]of run)jobs.delete(id);for(const[,j]of run)await j.fn();await Promise.resolve()}}
 await flush();return{w,d,sent,tracked,flush,control:()=>channels.find(c=>c.name.endsWith(':control')),close:()=>w.close()};
}
(async()=>{
 const s=await boot(false);assert.equal(s.d.querySelectorAll('#classroom-root a').length,1);s.d.getElementById('name').value='Student';s.d.getElementById('class').value='11T';s.d.getElementById('login').dispatchEvent(new s.w.Event('submit',{bubbles:true,cancelable:true}));assert.equal(s.d.getElementById('classroom-root').hidden,true);
 s.w.LessonClassroom.navigate('page-3');s.control().emit('state',{version:1,lesson:lessonId,class_id:classId,session_id:'00000000-0000-4000-8000-000000000002',stage:'slide-fact-where',locked:true,mode:'view',revision:1,bring_revision:1,return_revision:0,demo:{open:false},expires_at:new Date(Date.now()+3600000).toISOString(),server_now:new Date().toISOString(),ended:false});assert.equal(s.w.LessonClassroom.info().page,'slide-fact-where');assert.equal(s.d.querySelector('[data-key="factWhere"]').disabled,true);
 s.control().emit('demo',{open:true,program:'update-email',title:'UPDATE one student safely',code:'UPDATE Student\nSET Email = 1\nWHERE StudentID = 2;',output:'1 row would change',line:2,seq:1});assert.match(s.d.querySelector('#live-demo .current').textContent,/SET Email/);assert(s.tracked.every(x=>!('name'in x)&&!('className'in x)&&!('answers'in x)));s.close();
 const t=await boot(true);assert(t.d.querySelector('[data-cm="attention"]'));t.d.querySelector('#cm-demo-program').value='update-returned';t.d.querySelector('[data-cm="demo-start"]').click();await t.flush();const editor=t.d.getElementById('sql-demo-editor');assert(editor);editor.value="UPDATE Loan\nSET Returned = TRUE\nWHERE LoanID = 'L102';";editor.selectionStart=editor.selectionEnd=15;editor.dispatchEvent(new t.w.Event('input',{bubbles:true}));await t.flush();assert(t.sent.some(m=>m.event==='demo'&&m.payload.program==='update-returned'));t.close();
 console.log('classroom: landing-only sign-in, lock/follow, answer blocking, anonymous presence and live SQL broadcast passed');
})().catch(e=>{console.error(e);process.exitCode=1});
