/* Local evidence rendering. No uploads, third-party requests, or bundled fonts. */
(function(root){
'use strict';
const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const show=v=>v===undefined||v===null||v===''?'Not recorded':String(v);
const p=(label,value)=>'<p><strong>'+E(label)+'</strong> '+E(show(value))+'</p>';
const pre=code=>'<pre>'+E(code)+'</pre>';
function blocks(s){const L=root.Lesson,A=root.App,arr=[],add=(title,html)=>arr.push('<section class="report-block">'+(title?'<h2>'+E(title)+'</h2>':'')+html+'</section>');
add('Python Turtle: Read, Trace and Predict','<h1>Year 7 · Week 3 Theory</h1><div class="report-meta">'+p('Name:',s.name)+p('Class:',s.klass)+p('Device:',s.device+' / '+s.browser)+p('Language:',s.lang==='zh'?'English + 中文':s.lang==='ko'?'English + 한국어':'English')+'</div>'+p('Started:',new Date(s.startedAt).toLocaleString())+'<div class="report-status">Individual learning evidence. First attempts are preserved. Completion is not a grade. Teacher review is required for explanations and the checkpoint.</div>');
add('Learning intentions',p('WAGBA:',L.goals.wagba.en)+['knowledge','skills','understanding'].map(k=>p(k[0].toUpperCase()+k.slice(1)+':',L.goals[k].en)).join('')+p('Challenge:',L.goals.challenge.en));
add('Starting point', ['knowledge','skills','understanding'].map(k=>p(k+':',L.before[s.before[k]]?.en)).join('')+p('My focus:',s.fields.focus));
const groups=[['Read now',['ready']],['Do now',['retrieval1','retrieval2','retrieval3']],['Main task 1',['syntax','move','turn','pen','comment','hinge']]];
for(const [name,ids] of groups)for(const id of ids){const q=L.questions[id],a=s.q[id],first=a?.history?.[0],last=a?.history?.at(-1);let content=p('Question:',q.stem.en);const example=L.examples[id];if(example){content+=p('Start:',`(${example.start.x}, ${example.start.y}); facing ${root.TurtleModel.heading(example.start.h)}; pen ${example.start.pen?'down':'up'}`)+pre(example.code);}
const answer=v=>v===-1?'I am not sure yet':q.options[v]?.en||'No answer checked';content+=p('First checked answer:',first?answer(first.value):'Not attempted');if(first)content+=p('First-answer feedback:',first.value===q.correct?'Correct':'Revisit / not sure');if(last&&a.history.length>1)content+=p('Latest checked answer:',answer(last.value));if(a?.value!==undefined&&a.value!==last?.value)content+=p('Latest selection (not checked):',answer(a.value));content+=p('Attempts:',a?.history?.length||0);add(name+' · '+id,content);}
const routeTable=f=>'<table style="width:100%;border-collapse:collapse;font-size:12px"><thead><tr><th>Instruction</th><th>Position after</th><th>Movement direction</th></tr></thead><tbody><tr><td>t.goto(0, -100)</td><td>(0, -100)</td><td>Up (modelled)</td></tr><tr><td>t.goto(0, 100)</td><td>('+E(show(f.traceX2))+', '+E(show(f.traceY2))+')</td><td>'+E(show(f.traceDir2))+'</td></tr><tr><td>t.goto(200, 100)</td><td>('+E(show(f.traceX3))+', '+E(show(f.traceY3))+')</td><td>'+E(show(f.traceDir3))+'</td></tr></tbody></table>';
add('Main task 2 · First route trace',p('Start:','Main Entrance (0, -200), facing right, pen down')+pre(L.examples.route.code)+(s.traceAttempts.length?routeTable(s.traceAttempts[0].fields)+p('Explanation:',s.traceAttempts[0].fields.traceExplain|| (s.traceAttempts[0].fields.traceSpoken?'Student reports an oral explanation; not recorded.':''))+p('Trace feedback:',s.traceAttempts[0].correct?'Coordinate and direction fields correct':'One or more coordinate / direction fields need revisiting'):'<p>No route trace checked.</p>'));
if(s.traceAttempts.length>1)add('Route trace · Later version',routeTable(s.traceAttempts.at(-1).fields)+p('Latest explanation:',s.traceAttempts.at(-1).fields.traceExplain)+p('Checked versions:',s.traceAttempts.length));
for(const id of ['compareA','compareB']){const q=L.questions[id],a=s.q[id],first=a?.history?.[0],last=a?.history?.at(-1);add('Compare sequences · Program '+id.slice(-1),p('Start:','(0, 0), facing right, pen down')+pre(L.examples[id].code)+p('First endpoint prediction:',first?(first.value===-1?'Not sure':q.options[first.value]?.en):'Not attempted')+(last&&a.history.length>1?p('Latest checked endpoint:',q.options[last.value]?.en||'Not sure'):'')+p('Checked attempts:',a?.history?.length||0));}
add('Why the drawings differ',p('My explanation:',s.fields.compareExplain||(s.fields.compareSpoken?'Student reports an oral explanation; not recorded.':'')));
const cp=s.checkpoint;
add('Independent checkpoint · First submission',p('Start:','(0, 0), facing right, pen down')+pre(L.examples.checkpoint.code)+(cp?p('First submission:',new Date(cp.at).toLocaleString())+p('Support reported:',cp.mode)+'<p>The responses below are the student’s predictions, not a model answer. Mark out of 8 after review.</p>':'<p>No independent checkpoint submitted.</p>'));
if(cp){add('Checkpoint responses · Syntax, position and heading',p('1. Correct t.goto(60 20) [1]:',cp.syntax)+p('2. Final x [1]:',cp.x)+p('Final y [1]:',cp.y)+p('3. Final facing direction [1]:',cp.heading));add('Checkpoint response · Visible drawing [2]', '<p>4. Two visible line segments. This is the student’s predicted plot.</p>'+A.plotHTML(cp.points,false)+p('Selected points:',cp.points.map(v=>'('+v.x+', '+v.y+')').join(' → ')));add('Checkpoint responses · Explanation and comment',p('5. Why is no line drawn on the move to (-40, 20)? [1]:',cp.reason)+p('6. Meaningful Python comment [1]:',cp.comment)+p('Reference / help records during checkpoint:',cp.support?.map(x=>x.text).join('; ')||'None recorded in this app. Absence of a record is not proof of no external help.'));}
for(const c of s.checkpointCorrections)add('Checkpoint · Separate later correction',p('Recorded:',new Date(c.at).toLocaleString())+p('Correction and reason:',c.text));
if(s.fields.extensionChoice||s.extensionResult||s.fields.extensionExplain){
 const code=String(s.extensionCode||''),preview=code.split('\n').slice(0,25).map(line=>line.length>110?line.slice(0,107)+'...':line).join('\n').slice(0,1600);
 add('Optional extension',p('Choice:',s.fields.extensionChoice)+pre(preview)+(preview!==code?'<p>Long code is previewed here. Use the optional .py export for the full program; selected short test evidence appears below.</p>':'')+p('What I noticed:',s.fields.extensionExplain));
}

const labs=s.pythonLabs||{};
const attempted=Object.entries(labs).filter(([id,d])=>d.runCount||d.runs?.length);
if(attempted.length)add('Python practice · Testing record', '<p>These are tests after predictions, not independent assessment answers. The original question responses and checkpoint above stay unchanged. A successful run means the code executed; it does not prove that the intended drawing was correct.</p>'+attempted.map(([id,d])=>p((root.TurtleIDE?.spec(id).title||id)+':',String(d.runCount||d.runs.length)+' run(s); '+(d.kept?'selected test included below.':'no detailed test selected.'))).join(''));
for(const [id,d] of attempted){
 const k=d.kept;if(!k)continue;
 add('Executed Python · '+k.title,p('Evidence type:',k.afterCheckpoint?'Practice after the first checkpoint was saved. NOT the first assessed prediction.':'Practice test after saving a prediction.')+p('Starting state:',`(${k.start.x}, ${k.start.y}); facing ${root.TurtleModel.heading(k.start.h)}; pen ${k.start.pen?'down':'up'}`)+pre(k.code)+p('Kept:',new Date(k.at).toLocaleString()));
 add('Actual output · '+k.title,(typeof k.image==='string'&&/^data:image\/jpeg;base64,/.test(k.image)?'<img src="'+E(k.image)+'" style="display:block;width:336px;height:280px;margin:8px auto" alt="Actual output of the selected Python test">':'')+'<p style="font-size:11px;color:#557076">Grid, Turtle icon and any dashed undrawn travel are teaching aids, not pen strokes.</p>'+p('Final position:',`(${k.final.x}, ${k.final.y})`)+p('Final facing direction:',root.TurtleModel.heading(k.final.h))+p('Pen:',k.final.pen?'Down':'Up')+p('What I noticed:',k.observation||'No observation recorded.'));
 if(k.output)add('Python console · '+k.title,pre(k.output.slice(0,800)));
}
add('Learning pitstop · Same intentions revisited',['knowledge','skills','understanding'].map(k=>'<h3>'+E(k[0].toUpperCase()+k.slice(1))+'</h3>'+p('Statement:',L.goals[k].en)+p('Before:',L.before[s.before[k]]?.en)+p('After:',L.after[s.after[k]]?.en)).join(''));
add('Reflection and next action',p('Evidence of my progress:',s.fields.evidence)+p('Next action:',s.fields.nextAction)+p('Further note:',s.fields.reflectionNote));
const ex=L.questions.exit,firstExit=s.q.exit?.history?.[0],lastExit=s.q.exit?.history?.at(-1);add('Plenary',p('Question:',ex.stem.en)+p('First checked answer:',firstExit?(ex.options[firstExit.value]?.en||'Not sure'):'Not attempted')+(lastExit&&s.q.exit.history.length>1?p('Latest checked answer:',ex.options[lastExit.value]?.en||'Not sure'):'')+p('Explanation:',s.fields.exitExplain||(s.fields.exitSpoken?'Student reports an oral explanation; not recorded.':'')));
add('Support and evidence notes',p('Help recorded:',s.support.length?s.support.map(x=>x.stage+' — '+x.text).join('\n'):'None requested through this app.')+p('Teacher overrides:',s.overrides.length?s.overrides.map(x=>x.reason||JSON.stringify(x)).join('\n'):'None recorded.')+'<p>This report is generated before Teams submission. Saving a PDF, attaching it and turning it in are separate actions. The app does not verify any of those actions. No second report or upload is needed after completing the guide. Optional quiz results are not included in this submission.</p>');
return arr;}
function createPages(state){const s=JSON.parse(JSON.stringify(state)),host=document.createElement('div');host.className='report-offscreen';host.setAttribute('aria-hidden','true');document.body.append(host);let content,pg;const pages=[];function newPage(){pg=document.createElement('article');pg.className='report-sheet';pg.innerHTML='<header class="report-header"><strong>YEAR 7 · WEEK 3 THEORY</strong><span style="float:right">'+E(s.name)+' · '+E(s.klass)+'</span></header><div class="report-content"></div><footer class="report-foot"><span>Turtle Trace · Individual evidence</span><span class="page-number"></span></footer>';host.append(pg);content=pg.querySelector('.report-content');pages.push(pg);}
newPage();for(const html of blocks(s)){const block=document.createElement('div');block.innerHTML=html;let node=block.firstElementChild;content.append(node);if(content.scrollHeight>content.clientHeight+1){node.remove();newPage();content.append(node);if(content.scrollHeight>content.clientHeight+1){node.style.fontSize='12px';node.style.lineHeight='1.3';if(content.scrollHeight>content.clientHeight+1){host.remove();throw new Error('A report section is too long to fit safely. Shorten very long notes before exporting.');}}}}pages.forEach((p,i)=>p.querySelector('.page-number').textContent='Page '+(i+1)+' / '+pages.length);return {host,pages,state:s};}
function preview(s){const r=createPages(s);const html=r.pages.map(p=>p.outerHTML).join('');const count=r.pages.length;r.host.remove();return {html,count};}
async function rasterizePlots(host){
 for(const original of host.querySelectorAll('svg')){
  const svg=original.cloneNode(true);svg.setAttribute('width','480');svg.setAttribute('height','400');svg.removeAttribute('style');
  const source=new XMLSerializer().serializeToString(svg),url='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(source);
  const im=await new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error('A coordinate plot could not be prepared.'));image.src=url;});
  const canvas=document.createElement('canvas');canvas.width=960;canvas.height=800;canvas.getContext('2d').drawImage(im,0,0,960,800);
  const out=document.createElement('img');out.src=canvas.toDataURL('image/png');out.alt='Student-predicted visible line';out.style.cssText='display:block;width:336px;height:280px;margin:auto;';
  original.replaceWith(out);await out.decode();
 }
}
async function prepare(s){if(!root.html2canvas||!root.jspdf)throw new Error('PDF libraries missing');document.body.classList.add('pdf-busy');let r;try{r=createPages(s);await document.fonts.ready;await rasterizePlots(r.host);const pdf=new root.jspdf.jsPDF({orientation:'portrait',unit:'mm',format:'a4',compress:true});for(let i=0;i<r.pages.length;i++){const canvas=await root.html2canvas(r.pages[i],{scale:1.65,backgroundColor:'#ffffff',logging:false,useCORS:false,windowWidth:1200,windowHeight:1300});if(i)pdf.addPage();pdf.addImage(canvas.toDataURL('image/jpeg',.9),'JPEG',0,0,210,297,undefined,'FAST');canvas.width=1;canvas.height=1;}const at=new Date().toISOString();pdf.setProperties({title:'Year 7 Week 3 Theory - '+s.name,subject:'Python Turtle individual learning evidence',creator:'Turtle Trace lesson app'});return {blob:pdf.output('blob'),filename:root.SubmissionGuide.filename(s),pageCount:r.pages.length,version:s.evidenceVersion,at};}finally{r?.host.remove();document.body.classList.remove('pdf-busy');}}
root.EvidenceReport={preview,prepare,createPages};
})(window);
