window.teacherMode=new URLSearchParams(location.search).get('teacher')==='1';
window.appState={name:'',className:'',page:0,answers:{},photos:{}};
let saveKey='',classroomOwn=null,classroomPending=null,activeDemo=null;
window.$=id=>document.getElementById(id);
const safe=s=>String(s).trim().replace(/\s+/g,' ').slice(0,80);
const key=(name,cls)=>'y10-w5-strings-validation-v1:'+name.toLowerCase()+':'+cls.toLowerCase();
function save(){if(!saveKey)return;try{localStorage.setItem(saveKey,JSON.stringify(appState));$('saveStatus').textContent='Saved in this browser · '+new Date().toLocaleTimeString()}catch{$('saveStatus').textContent='Browser storage is full. Download a full backup now.'}}
function start(name,className){
 name=safe(name);className=safe(className);
 if(!name){$('loginError').textContent='Enter your name.';return}
 saveKey=key(name,className);
 try{const old=JSON.parse(localStorage.getItem(saveKey)||'null');appState=old?.name?old:{name,className,page:0,answers:{},photos:{}}}
 catch{appState={name,className,page:0,answers:{},photos:{}}}
 $('landing').hidden=true;$('lesson').hidden=false;$('backup').disabled=false;$('pdf').disabled=false;
 if(classroomPending!==null){appState.page=classroomPending;classroomPending=null}
 render();
}
function render(){const nav=$('nav');nav.innerHTML=LESSON_PAGES.map(([label],i)=>`<button type="button" data-go="${i}" ${i===appState.page?'aria-current="page"':''}>${String(i).padStart(2,'0')} · ${esc(label)}</button>`).join('');$('content').innerHTML=LESSON_PAGES[appState.page][2]();$('position').textContent=`${appState.page+1} of ${LESSON_PAGES.length} · ${LESSON_PAGES[appState.page][1]}`;$('prev').disabled=appState.page===0;$('next').disabled=appState.page===LESSON_PAGES.length-1;restorePhotos();initTutors();updateKsu();save();window.scrollTo(0,0);window.dispatchEvent(new Event('lesson:render'))}
function go(n,remote=false){if(!remote&&!teacherMode&&window.ClassroomMode?.locked?.())return;appState.page=Math.max(0,Math.min(LESSON_PAGES.length-1,n));render()}
function updateKsu(){for(const prefix of ['before','after']){const box=$(prefix+'-summary');if(!box)continue;const counts={'not-yet':0,support:0,independent:0,blank:0};for(const [id] of KSU_TARGETS){const x=appState.answers[prefix+'-'+id];counts[x||'blank']++}box.innerHTML=`<strong>Quantified profile:</strong> ${counts.independent} independently · ${counts.support} with support · ${counts['not-yet']} not yet · ${counts.blank} not answered.`}}
const TUTORS={
 strings:{lines:['username = "Maya7"','print("Hello, " + username)','print(len(username))','print(username[0])','print(username[0:4])'],steps:['Store the five-character string Maya7 in username.','Join the greeting and username. Output: Hello, Maya7','Count every character. Output: 5','Retrieve the character at index 0. Output: M','Retrieve indices 0, 1, 2 and 3. The stop index 4 is excluded. Output: Maya']},
 validation:{lines:['username = input("Enter a username: ")','length = len(username)','if length < 5:','    print("Too short")','elif length > 8:','    print("Too long")','else:','    print("Username accepted")']}
};
const tutorStep={strings:0,validation:0};
function validationPath(input){const n=input.length;if(n<5)return{path:[0,1,2,3],steps:[`Store the entered text ${input||'(empty input)'}.`,`Count the characters. length becomes ${n}.`,`${n} < 5 is True, so enter this branch.`,`Output: Too short. The remaining branches are skipped.`]};if(n>8)return{path:[0,1,2,4,5],steps:[`Store the entered text ${input}.`,`Count the characters. length becomes ${n}.`,`${n} < 5 is False, so skip Too short.`,`${n} > 8 is True, so enter this branch.`,`Output: Too long. The else branch is skipped.`]};return{path:[0,1,2,4,6,7],steps:[`Store the entered text ${input}.`,`Count the characters. length becomes ${n}.`,`${n} < 5 is False.`,`${n} > 8 is False.`,`Both rejection tests were False, so enter else.`,`Output: Username accepted.`]}}
function tutorData(kind){if(kind==='strings')return{path:TUTORS.strings.lines.map((_,i)=>i),steps:TUTORS.strings.steps};return validationPath($('traceInput')?.value||'Maya7')}
function drawTutor(box){const kind=box.dataset.tutor,data=tutorData(kind),step=Math.min(tutorStep[kind],data.path.length-1),active=data.path[step],passed=new Set(data.path.slice(0,step+1));box.querySelector('.tutor-lines').innerHTML=TUTORS[kind].lines.map((line,i)=>`<div class="tutor-line ${i===active?'active':''} ${step>1&&!data.path.includes(i)?'skipped':''}"><span>${i+1}</span><code>${esc(line)}</code></div>`).join('');box.querySelector('.explanation').textContent=data.steps[step]||'Choose Next line to begin.';box.querySelector('[data-tutor-prev]').disabled=step===0;box.querySelector('[data-tutor-next]').disabled=step===data.path.length-1}
function initTutors(){document.querySelectorAll('[data-tutor]').forEach(drawTutor)}
function compress(file){return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{try{const max=1500,s=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*s);c.height=Math.round(img.height*s);c.getContext('2d').drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(url);resolve(c.toDataURL('image/jpeg',.8))}catch(e){reject(e)}};img.onerror=()=>reject(Error('The image could not be read.'));img.src=url})}
function restorePhotos(){for(const k of Object.keys(appState.photos||{})){const box=$('preview-'+k);if(box)box.innerHTML=`<p class="small">Saved evidence:</p><img src="${appState.photos[k]}" alt="Student evidence" style="max-width:100%;max-height:320px;border:1px solid #9aa69d"><p><button type="button" data-remove-photo="${k}">Remove image</button></p>`}}
function filename(ext){return `W5_Merged_Strings_Validation_${(appState.name||'student').replace(/[^a-z0-9_-]+/gi,'_')}_${(appState.className||'class').replace(/[^a-z0-9_-]+/gi,'_')}.${ext}`}
function download(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function backup(){download(new Blob([JSON.stringify({...appState,version:1,created:new Date().toISOString()},null,2)],{type:'application/json'}),filename('backup.json'))}
const PDF_SECTIONS=[
 ['Preparation',[['prepare-check','The two jobs']]],['Do Now',[['starter1','Variable and stored value'],['starter2','Data type'],['starter3','Character count'],['starter4','Exact text comparison']]],
 ['Types of Learning',[...KSU_TARGETS.map(([id,,t])=>['before-'+id,t]),['focusTarget','Priority target'],['focusAction','Improvement action']]],['String reading',[['readExplain','Why the slice stop is excluded']]],
 ['Main Activity 1',[['main1Predict','Predicted outputs'],['main1Compare','Comparison after running'],['main1Code','Adapted Python code'],['main1Output','IDE output']]],['Validation reading',[['validationExplain','Why else represents lengths 5–8']]],
 ['Main Activity 2',[['main2Code','Completed validation code'],['main2Output','Accepted output'],['main2Explain','Branch explanation']]],['Test evidence',[['testNormal','Normal actual output'],['test4','Length 4 actual output'],['test5','Length 5 actual output'],['test8','Length 8 actual output'],['test9','Length 9 actual output'],['testEmpty','Empty input actual output'],['testConclusion','Test conclusion'],['testWhy','Why one normal test is insufficient']]],
 ['Extension',[['extensionCode','Furthest extension code'],['extensionEvidence','Extension output and challenge']]],['Class fact discussions',[['factPositions','Why the slice stop is excluded'],['factValidation','What validation proves'],['factBoundaries','Why a normal test is insufficient']]],['Learning Pit Stop',[...KSU_TARGETS.flatMap(([id,,t])=>[['after-'+id,t+' — evidence level'],['phase-'+id,t+' — learning phase']]),['pitEvidence','Evidence and next action']]],['Plenary',[['plenary1','Length operation'],['plenary2','Six-character condition'],['plenary3','Boundary lengths'],['plenary4','Why one valid test is insufficient']]]
];
function savePdf(){const C=window.jspdf?.jsPDF;if(!C){alert('PDF library did not load. Download a backup and tell your teacher.');return}const doc=new C({unit:'pt',format:'a4'});try{doc.addFileToVFS('Raleway.ttf',PDF_FONTS.regular);doc.addFont('Raleway.ttf','Raleway','normal');doc.setFont('Raleway','normal')}catch{doc.setFont('helvetica')}const H=842,L=42,R=553;let y=47,page=1;const footer=()=>{doc.setFontSize(8);doc.text(`Year 10 · ${appState.name} · ${page}`,L,H-24)};const newPage=()=>{footer();doc.addPage();page++;y=47};function line(text,size=10,gap=4){doc.setFontSize(size);for(const part of doc.splitTextToSize(String(text),R-L)){if(y+size*1.5>H-48)newPage();doc.text(part,L,y);y+=size*1.4}y+=gap}function section(title){if(y>H-130)newPage();y+=8;doc.setDrawColor(10,108,61);doc.line(L,y-4,R,y-4);line(title,14,5)}line('YEAR 10 COMPUTER SCIENCE · STRINGS AND VALIDATION',16,8);line(`Name: ${appState.name}     Class: ${appState.className||'—'}`,10,12);line('WAGBA: examining text and testing validation decisions accurately.',10,10);for(const [title,items] of PDF_SECTIONS){section(title);for(const [k,label] of items){line(label+':',9,1);line(appState.answers[k]||'Not answered',10,7)}}for(const [k,title] of [['main1Image','Main Activity 1 screenshot'],['main2Image','Main Activity 2 screenshot']]){if(!appState.photos?.[k])continue;section(title);if(y>H-340)newPage();try{const p=doc.getImageProperties(appState.photos[k]),s=Math.min((R-L)/p.width,(H-y-55)/p.height);doc.addImage(appState.photos[k],'JPEG',L,y,p.width*s,p.height*s);y+=p.height*s+10}catch{line('Image could not be placed. Keep the full backup.')}}footer();doc.save(filename('pdf'))}

$('login').addEventListener('submit',e=>{e.preventDefault();start($('name').value,$('class').value)});
$('restore').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{const d=JSON.parse(await f.text());if(!d.name||typeof d.answers!=='object')throw Error('This is not a lesson backup.');appState={name:safe(d.name),className:safe(d.className||''),page:Number(d.page)||0,answers:d.answers||{},photos:d.photos||{}};saveKey=key(appState.name,appState.className);$('landing').hidden=true;$('lesson').hidden=false;$('backup').disabled=$('pdf').disabled=false;render()}catch(err){$('loginError').textContent=err.message}});
document.addEventListener('input',e=>{if(e.target.matches('[data-key]')){appState.answers[e.target.dataset.key]=e.target.value;save();updateKsu()}});
document.addEventListener('change',async e=>{if(e.target.matches('[data-photo]')&&e.target.files?.[0]){try{appState.photos[e.target.dataset.photo]=await compress(e.target.files[0]);save();restorePhotos()}catch(err){alert(err.message)}}if(e.target.id==='traceInput'){tutorStep.validation=0;const box=e.target.closest('[data-tutor]');if(box)drawTutor(box)}});
document.addEventListener('click',e=>{const nav=e.target.closest('[data-go]');if(nav)return go(Number(nav.dataset.go));const box=e.target.closest('[data-tutor]');if(box&&e.target.matches('[data-tutor-prev],[data-tutor-next],[data-tutor-reset]')){const k=box.dataset.tutor,data=tutorData(k);if(e.target.hasAttribute('data-tutor-prev'))tutorStep[k]=Math.max(0,tutorStep[k]-1);if(e.target.hasAttribute('data-tutor-next'))tutorStep[k]=Math.min(data.path.length-1,tutorStep[k]+1);if(e.target.hasAttribute('data-tutor-reset'))tutorStep[k]=0;drawTutor(box)}const rm=e.target.closest('[data-remove-photo]');if(rm){delete appState.photos[rm.dataset.removePhoto];save();render()}});
$('prev').onclick=()=>go(appState.page-1);$('next').onclick=()=>go(appState.page+1);$('backup').onclick=backup;$('pdf').onclick=savePdf;$('switch').onclick=()=>{if(confirm('Return to the name screen? Your saved work will remain on this device.')){$('lesson').hidden=true;$('landing').hidden=false;$('backup').disabled=$('pdf').disabled=true;saveKey=''}};

const DEMOS={
 'string-operations':{title:'Trace string operations',page:4,code:'username = "Maya7"\nprint("Hello, " + username)\nprint(len(username))\nprint(username[0])\nprint(username[0:4])',output:'Hello, Maya7\n5\nM\nMaya'},
 'validation-short':{title:'Trace a username that is too short',page:6,code:'username = "Amy"\nlength = len(username)\nif length < 5:\n    print("Too short")\nelif length > 8:\n    print("Too long")\nelse:\n    print("Username accepted")',output:'Too short'},
 'validation-boundary':{title:'Trace the minimum boundary',page:6,code:'username = "Maya7"\nlength = len(username)\nif length < 5:\n    print("Too short")\nelif length > 8:\n    print("Too long")\nelse:\n    print("Username accepted")',output:'Username accepted'}
};
function demoState(){const editor=$('python-demo-editor');if(!activeDemo||!editor)return{open:false};return{open:true,program:activeDemo,title:DEMOS[activeDemo].title,code:editor.value.slice(0,20000),output:($('python-demo-output')?.textContent||DEMOS[activeDemo].output).slice(0,24000),line:editor.value.slice(0,editor.selectionStart).split('\n').length,selectionStart:editor.selectionStart,selectionEnd:editor.selectionEnd,running:false}}
function announce(){window.dispatchEvent(new Event('lesson:demo-change'))}
function openDemo(id){const d=DEMOS[id];if(!teacherMode||!d)return false;activeDemo=id;go(d.page,true);let p=$('sql-demo-teacher');if(!p){p=document.createElement('section');p.id='sql-demo-teacher';document.body.append(p)}p.innerHTML=`<header><div><span>TEACHER LIVE PYTHON WALKTHROUGH</span><h1>${esc(d.title)}</h1></div><button id="python-demo-close">Close workspace</button></header><main><section><label for="python-demo-editor">Python example</label><textarea id="python-demo-editor" spellcheck="false">${esc(d.code)}</textarea><p class="small">Click the line you are explaining. Students see a read-only highlighted copy.</p></section><section><h2>Expected output</h2><pre id="python-demo-output">${esc(d.output)}</pre></section></main>`;const ed=$('python-demo-editor');['input','click','keyup','select'].forEach(x=>ed.addEventListener(x,announce));$('python-demo-close').onclick=()=>{p.remove();activeDemo=null;announce()};ed.focus();announce();return true}
function stopDemo(){activeDemo=null;$('sql-demo-teacher')?.remove()}
window.LessonClassroom=Object.freeze({info:()=>({teacher:teacherMode,entry:!$('landing').hidden,page:'page-'+appState.page,lang:'en'}),pages:()=>LESSON_PAGES.map((_,i)=>'page-'+i),destinations:()=>LESSON_PAGES.map(([title,time],i)=>({id:'page-'+i,title,group:time})),label:()=>LESSON_PAGES[appState.page][0],teacherPages:()=>[],openTeacherPage:()=>{},navigate:id=>{const n=Number(String(id).replace('page-',''));if(Number.isInteger(n))go(n)},move:id=>{const n=Number(String(id).replace('page-',''));if(!Number.isInteger(n))return;if(!$('landing').hidden)classroomPending=n;else go(n,true)},captureOwn:()=>{if(classroomOwn===null&&$('landing').hidden)classroomOwn=appState.page},returnOwn:()=>{if(classroomOwn!==null){const n=classroomOwn;classroomOwn=null;go(n,true)}},setSession:()=>{},clearTarget:()=>{classroomPending=null;classroomOwn=null},demoPrograms:()=>Object.entries(DEMOS).map(([id,d])=>({id,title:d.title,page:'page-'+d.page})),startDemo:openDemo,stopDemo,demoState});
if(teacherMode)start('Teacher preview','Teacher');
