window.esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const v=k=>window.appState?.answers?.[k]||'';
function field(k,label,rows=3,hint=''){return `<label for="${k}">${label}</label>${rows===1?`<input id="${k}" data-key="${k}" value="${esc(v(k))}" placeholder="${esc(hint)}">`:`<textarea id="${k}" data-key="${k}" rows="${rows}" placeholder="${esc(hint)}">${esc(v(k))}</textarea>`}`}
function selectField(k,label,options){return `<label for="${k}">${label}</label><select id="${k}" data-key="${k}"><option value="">Choose…</option>${options.map(([value,text])=>`<option value="${esc(value)}" ${v(k)===value?'selected':''}>${esc(text)}</option>`).join('')}</select>`}
function head(n,title,tag){return `<span class="badge">${n} · ${tag}</span><h1>${title}</h1>`}
function code(text){return `<pre class="code">${esc(text)}</pre>`}
function evidence(key,label){return `<div class="preview"><label for="${key}">${label}</label><input id="${key}" type="file" accept="image/*" data-photo="${key}"><div id="preview-${key}"></div><p class="small">Use a screenshot from your own IDE. Check that another student’s name or work is not visible.</p></div>`}
const LEVELS=[['not-yet','Not yet / new to me'],['support','I can do this with support'],['independent','I can do this independently']];
const PHASES=[['new','New learning — I am making progress with an unfamiliar idea'],['consolidating','Consolidating — practice is making me more secure'],['treading','Treading water — this is easy and I need more challenge'],['help','Drowning / needing help — I cannot yet move forward']];
window.KSU_TARGETS=[
 ['K1','Knowledge','Explain concatenation, length, index and substring.'],['K2','Knowledge','Distinguish normal, boundary and erroneous test data.'],
 ['S1','Skill','Predict and use string operations in Python.'],['S2','Skill','Write a selection-based validation decision and record tests.'],
 ['U1','Understanding','Explain why indexing begins at 0 and a slice stop is excluded.'],['U2','Understanding','Explain why tests at and immediately outside both limits are needed.']
];
function ksuChecks(prefix,includePhase=false){return `<div class="card">${KSU_TARGETS.map(([id,area,target])=>`<section class="ksu-grid"><p><strong>${id} · ${area}</strong><br>${target}</p><div>${selectField(`${prefix}-${id}`,'Current evidence',LEVELS)}${includePhase?selectField(`phase-${id}`,'Learning phase',PHASES):''}</div></section>`).join('')}</div><div id="${prefix}-summary" class="summary" aria-live="polite">Complete the six checks to see your learning profile.</div>`}
function pagePrepare(){return `${head('00','Prepare: one username, two jobs','READ FIRST')}<div class="reading"><h2>The school account problem</h2><p>A school activity app needs a username. Before it can accept the username, the program must first <strong>examine the text</strong> and then <strong>make a decision</strong>.</p><p>Today you will use string operations to join, count and extract characters. You will then build a checker that accepts usernames containing <strong>5–8 characters inclusive</strong>.</p></div><div class="callout"><strong>Lesson boundary:</strong> this checker validates one entry using selection. It does not repeatedly ask again. Validation loops come later.</div><div class="card"><h2>What success looks like</h2><ol><li>Predict and run string expressions in your own Python IDE.</li><li>Write a checker using <code>if</code>, <code>elif</code> and <code>else</code>.</li><li>Test the checker at, inside and outside both limits.</li><li>Explain the result using the stated rule.</li></ol></div>${field('prepare-check','In one sentence, what are the two jobs the program must perform?',2,'First it… Then it…')}`}
function pageStarter(){return `${head('01','Do Now: read the stored text','RETRIEVE')}<p>Answer from memory. Each question has its own response so you can see exactly what is complete.</p><div class="question"><h2>1. Stored value</h2>${code('username = "Maya7"')}${field('starter1','What is the variable name and what value does it store?',2)}</div><div class="question"><h2>2. Data type</h2>${field('starter2','What is the data type of the stored value? Explain how you know.',2)}</div><div class="question"><h2>3. Count carefully</h2>${field('starter3','How many characters are in Maya7? Explain whether the digit counts.',2)}</div><div class="question"><h2>4. Exact text</h2>${field('starter4','Are Maya7 and maya7 exactly the same string? Explain.',2)}</div><div class="callout"><strong>After answering:</strong> compare your character count with <code>len("Maya7")</code> in your IDE. Correct your answer if needed.</div>`}
function pageTypes(){return `${head('02','Types of Learning: choose the right target','REFLECT')}<p>Use evidence from your Do Now. A target you already completed independently is not the best first improvement target.</p>${ksuChecks('before')}${selectField('focusTarget','My priority target',KSU_TARGETS.map(([id,area,t])=>[id,`${id} · ${area}: ${t}`]))}${field('focusAction','What will you do to improve this target today?',2,'For S1, I will predict each expression before I run it.')}`}
function pageStringRead(){return `${head('03','Read: how Python examines a string','FACT 1')}<div class="reading"><h2>A string is a sequence of characters</h2><p>Python can join strings, count characters and retrieve part of a string. A digit inside quotation marks is still a character in the string.</p>${code('username = "Maya7"\nprint("Hello, " + username)\nprint(len(username))\nprint(username[0])\nprint(username[0:4])')}<table class="test-table"><thead><tr><th>Expression</th><th>Result</th><th>Meaning</th></tr></thead><tbody><tr><td><code>"Hello, " + username</code></td><td>Hello, Maya7</td><td>Concatenation joins strings.</td></tr><tr><td><code>len(username)</code></td><td>5</td><td>Length counts every character.</td></tr><tr><td><code>username[0]</code></td><td>M</td><td>Indexing retrieves one character.</td></tr><tr><td><code>username[0:4]</code></td><td>Maya</td><td>A substring/slice retrieves positions 0–3. The stop index is excluded.</td></tr></tbody></table></div><h2>Character-position visual</h2><div class="position-strip"><div><b>0</b>M</div><div><b>1</b>a</div><div><b>2</b>y</div><div><b>3</b>a</div><div><b>4</b>7</div></div><p class="small">People count five characters. Python indexes their positions from 0 to 4.</p>${field('readExplain','Why does username[0:4] return four characters rather than five?',2)}`}
function pageMain1(){return `${head('04','Main Activity 1: investigate a username','AO1 → AO2')}<div class="card"><h2>Your mission</h2><p>You are preparing the greeting shown after a student enters a username. First predict the program, then run it in your own IDE. Finally adapt it to a new username.</p></div><div class="tutor" data-tutor="strings"><h2>Guided line-by-line example</h2><p>Select <strong>Next line</strong>. The highlighted line and explanation show exactly what Python does.</p><div class="tutor-lines"></div><div class="tutor-controls"><button type="button" data-tutor-prev>Previous line</button><button type="button" data-tutor-next>Next line</button><button type="button" data-tutor-reset>Restart</button></div><div class="explanation" aria-live="polite"></div></div><div class="question"><h2>A. Predict before running</h2>${field('main1Predict','Write the four outputs in order.',5,'1. …')}</div><div class="question"><h2>B. Run and compare</h2><ol><li>Copy the example into your Python IDE.</li><li>Run it.</li><li>Compare the output with your prediction.</li><li>Record one correction or state that all four predictions matched.</li></ol>${field('main1Compare','What matched or changed after you ran the program?',3)}</div><div class="question"><h2>C. Adapt the program</h2><p>Change the username to <code>Amir28</code>. Display a greeting, the length, the first character and the first four characters.</p>${field('main1Code','Paste your adapted Python code here.',8)}${field('main1Output','Paste the output from your IDE.',5)}${evidence('main1Image','Optional screenshot of your code and output')}</div>`}
function pageValidationRead(){return `${head('05','Read: validation makes a decision','FACT 2')}<div class="reading"><h2>The rule</h2><p>A username is accepted when its length is <strong>between 5 and 8 characters inclusive</strong>. “Inclusive” means that lengths 5 and 8 are accepted.</p>${code('username = input("Enter a username: ")\nlength = len(username)\n\nif length < 5:\n    print("Too short")\nelif length > 8:\n    print("Too long")\nelse:\n    print("Username accepted")')}<ol><li>Store the entered text.</li><li>Count its characters.</li><li>Reject fewer than 5.</li><li>Otherwise reject more than 8.</li><li>Accept everything remaining: lengths 5–8.</li></ol></div><div class="callout"><strong>Important:</strong> validation checks whether data follows rules. It does not prove that the username is true, belongs to the student or is available.</div>${field('validationExplain','Why does the else branch represent lengths 5–8?',3)}`}
function pageMain2(){return `${head('06','Main Activity 2: build the checker','AO2')}<div class="card"><h2>From algorithm to program</h2><p>You have examined the string. Now transfer that information into a selection decision. Work through the guided trace first, then type and test the program in your IDE.</p></div><div class="tutor" data-tutor="validation"><h2>Guided validation trace</h2><label for="traceInput">Choose an example input</label><select id="traceInput"><option value="Maya7">Maya7 · length 5</option><option value="Amy">Amy · length 3</option><option value="Student99">Student99 · length 9</option></select><div class="tutor-lines"></div><div class="tutor-controls"><button type="button" data-tutor-prev>Previous line</button><button type="button" data-tutor-next>Next line</button><button type="button" data-tutor-reset>Restart</button></div><div class="explanation" aria-live="polite"></div></div><div class="question"><h2>A. Build and run</h2><ol><li>Type the checker in your own IDE.</li><li>Run it with <code>Maya7</code>.</li><li>Change the accepted message so it includes the username using concatenation.</li><li>Run the changed version again.</li></ol>${field('main2Code','Paste your completed Python code.',10)}${field('main2Output','Paste one accepted output.',3)}${evidence('main2Image','Optional screenshot of the working checker')}</div><div class="question"><h2>B. Explain the branches</h2>${field('main2Explain','Explain what must be true for each of the three messages to be displayed.',4)}</div>`}
function pageTesting(){return `${head('07','Test the limits, not just the middle','FACT 3 · AO3')}<div class="reading"><p><strong>Normal data</strong> is a typical valid value away from a limit. <strong>Boundary data</strong> is at or immediately either side of a limit. <strong>Erroneous data</strong> breaks the rule.</p><p>A test can be both boundary data and invalid. For this 5–8 rule, lengths 4 and 9 are invalid boundary tests.</p></div><p>Predict first. Then enter every test into your program and record the actual result.</p><table class="test-table"><thead><tr><th>Input</th><th>Length</th><th>Purpose</th><th>Expected output</th><th>Actual output</th></tr></thead><tbody>
<tr><td>Amir28</td><td>6</td><td>Normal valid</td><td>Username accepted</td><td><input data-key="testNormal" value="${esc(v('testNormal'))}"></td></tr>
<tr><td>Abcd</td><td>4</td><td>Just below minimum</td><td>Too short</td><td><input data-key="test4" value="${esc(v('test4'))}"></td></tr>
<tr><td>Maya7</td><td>5</td><td>At minimum</td><td>Username accepted</td><td><input data-key="test5" value="${esc(v('test5'))}"></td></tr>
<tr><td>Student8</td><td>8</td><td>At maximum</td><td>Username accepted</td><td><input data-key="test8" value="${esc(v('test8'))}"></td></tr>
<tr><td>Student99</td><td>9</td><td>Just above maximum</td><td>Too long</td><td><input data-key="test9" value="${esc(v('test9'))}"></td></tr>
<tr><td>empty input</td><td>0</td><td>Erroneous</td><td>Too short</td><td><input data-key="testEmpty" value="${esc(v('testEmpty'))}"></td></tr></tbody></table>${field('testConclusion','Did every actual result match? If not, identify the failed test and the correction needed.',3)}${field('testWhy','Why would testing only Amir28 be insufficient?',3)}`}
function pageExtensions(){return `${head('08','Extension studio: ten focused challenges','EARLY FINISH / AFTER CORE')}<p>Complete these in order until lesson time ends. Each challenge uses only strings, selection and operations already taught. Run the code in your own IDE and paste evidence for the challenges you complete.</p><div class="extension-list">
${[['Greeting builder','Ask for a first name and family name. Concatenate them into one greeting.'],['Length reporter','Ask for a username and display its length in a clear sentence.'],['First character','Display the first character of a supplied username.'],['Final character','Use <code>len(username) - 1</code> as an index to display the final character.'],['Four-character preview','Display the first four characters as a preview.'],['Initials','Ask for a first name and family name, then display their first characters together.'],['Prefix checker','Accept a code only when <code>code[0:3] == "Y10"</code>.'],['Exact-length checker','Accept an activity code only when its length is exactly 6.'],['Username checker rebuilt','Recreate the 5–8 character checker without looking at the model.'],['Combined challenge','Accept a username only when its length is 5–8 and its first three characters are <code>Y10</code>. Explain one appropriate boundary test.']].map(([t,p])=>`<section class="question extension"><h2>${t}</h2><p>${p}</p></section>`).join('')}</div>${field('extensionCode','Paste code from the furthest challenge you completed.',10)}${field('extensionEvidence','Paste its output and state which challenge it proves.',5)}`}
function pagePit(){return `${head('09','Learning Pit Stop: measure your progress','REFLECT')}<p>Assess each target separately. Use your program, outputs and test table as evidence; do not rate everything from general confidence.</p>${ksuChecks('after',true)}${field('pitEvidence','Choose one target. Quote evidence, identify its learning phase and state your next action.',4,'For S2, my code… This is consolidating because… Next I will…')}`}
function pagePlenary(){return `${head('10','Plenary: transfer the learning','EXIT TICKET')}<div class="card"><p>A different app accepts a code containing <strong>exactly six characters</strong>.</p>${field('plenary1','1. Which Python operation finds the code length?',1)}${field('plenary2','2. Write a Python condition that checks whether the length is six.',2)}${field('plenary3','3. Which three lengths would you test around this boundary?',2)}${field('plenary4','4. Explain why testing only a six-character code is insufficient.',3)}</div>`}
function pageSubmit(){return `${head('11','Save, check and submit','FINAL STEP')}<div class="card"><ol><li>Review every page and complete any unfinished core response.</li><li>Select <strong>Save PDF</strong> at the top right.</li><li>Open the PDF. Check that your name, answers, code, outputs, test evidence and reflections are complete.</li><li>Rename it clearly if needed: <code>W5_Merged_Strings_Validation_Name_Class.pdf</code>.</li><li>Upload the PDF to the correct Microsoft Teams assignment.</li></ol><p>This website saves locally and downloads evidence. It does not upload to Teams automatically.</p></div>`}
window.LESSON_PAGES=[['Prepare','4 min',pagePrepare],['Do Now','5 min',pageStarter],['Types of Learning','3 min',pageTypes],['Read: string operations','5 min',pageStringRead],['Main Activity 1','11 min',pageMain1],['Read: validation','5 min',pageValidationRead],['Main Activity 2','14 min',pageMain2],['Test data','6 min',pageTesting],['Extensions','Early finish',pageExtensions],['Learning Pit Stop','3 min',pagePit],['Plenary','2 min',pagePlenary],['Submit','2 min',pageSubmit]];
