(()=>{'use strict';
const L=window.LESSON,APP='w5s3-primary-sql-v1',$=id=>document.getElementById(id),meta=new Map();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=null,db=null,pending=null,queue=Promise.resolve(),unsaved=false,unlocked=false;
const teacherMode=new URLSearchParams(location.search).get('teacher')==='1';
let classroomTarget=null;
const classroomLocked=()=>!teacherMode&&!!window.ClassroomMode?.locked();
const classroomChanged=()=>window.dispatchEvent(new Event('lesson:render'));
window.LessonClassroom=Object.freeze({
 info:()=>({teacher:teacherMode,lang:'en',page:L.stages[state?.step||0][0],entry:!state}),
 pages:()=>L.stages.map(s=>s[0]),label:()=>L.stages[state?.step||0][1],
 move:id=>{if(teacherMode||!L.stages.some(s=>s[0]===id))return;if(!state){classroomTarget=id;return;}go(L.stages.findIndex(s=>s[0]===id),true);},
 navigate:id=>{if(!state||!L.stages.some(s=>s[0]===id))return;go(L.stages.findIndex(s=>s[0]===id));},
 clearTarget:()=>{classroomTarget=null;}
});
for(const type of ['click','change'])document.addEventListener(type,e=>{if(classroomLocked()&&e.target.closest('[data-step],#prev,#next,#switch,#restore,#confirmRestore')){e.preventDefault();e.stopImmediatePropagation();}},true);
const blank=(name,cls)=>({version:1,name,cls,date:new Date().toLocaleDateString('en-GB'),step:0,answers:{},photos:{},attempts:{},design:L.heads.map(name=>({name,type:'',length:'',reason:''})),records:[['','','','',''],['','','','','']]});
const profile=()=>state.name.trim().toLowerCase()+'|'+state.cls.trim().toLowerCase();
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(APP,1);r.onupgradeneeded=()=>r.result.createObjectStore('profiles');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function save(){if(!state)return;unsaved=true;const s=structuredClone(state),key=profile();$('saveStatus').textContent='Saving…';queue=queue.catch(()=>{}).then(()=>new Promise((resolve,reject)=>{if(!db)return reject(Error('No storage'));const tx=db.transaction('profiles','readwrite');tx.objectStore('profiles').put(s,key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);})).then(()=>{unsaved=false;$('saveStatus').textContent='Saved on this device';}).catch(()=>{$('saveStatus').textContent='Device save unavailable — use Full backup';});return queue;}
function field(key,label,stage,rows=3){meta.set(key,{label,stage});return `<div class="question"><label for="${key}">${esc(label)}</label><textarea id="${key}" data-answer="${key}" rows="${rows}">${esc(state.answers[key]||'')}</textarea></div>`;}
function table(caption,heads,rows){return `<div class="table-wrap"><table><caption>${esc(caption)}</caption><thead><tr>${heads.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table>${rows.length?'':'<p>No matching records.</p>'}</div>`;}
const card=(title,body)=>`<section class="card"><h2>${title}</h2>${body}</section>`;
function mcq(key,label,options,correct,why){meta.set(key,{label,stage:['r4','r5'].includes(key)?'sql':'read'});const answer=state.answers[key];return `<fieldset class="card options"><legend>${esc(label)}</legend>${options.map(o=>`<label><input type="radio" name="${key}" data-answer="${key}" value="${esc(o)}" ${answer===o?'checked':''}>${esc(o)}</label>`).join('')}${answer?`<p class="action" role="status">${answer===correct?'Correct.':'Reconsider your choice.'} ${esc(why)}</p>`:''}</fieldset>`;}
function checks(after){return L.targets.map(([label,target,hint],i)=>{const key=(after?'after':'before')+i,stage=after?'pit':'before';meta.set(key,{label:label+': '+target,stage});const choices=after?['New learning','Consolidating','Treading water','Drowning','Not checked yet']:['I know this confidently','I know this now, with support','I don’t know this yet','Not checked yet'];const actions={'Drowning':'Ask your teacher to model one decision or one query line with you.','Treading water':'Try the two-condition extension and explain why both conditions matter.','Consolidating':'Try one query without looking at the worked example.','New learning':'Explain a corrected answer to your partner.','Not checked yet':'Attempt a relevant question before choosing a phase.'};return card(label,`<p><strong>${esc(target)}</strong></p><p>${esc(hint)}</p>${after?'<p class="small">Starting point: '+esc(state.answers['before'+i]||'Not recorded')+'</p>':''}<label for="${key}">${after?'My phase now':'My starting point'}</label><select id="${key}" data-answer="${key}"><option value="">Choose…</option>${choices.map(v=>`<option ${state.answers[key]===v?'selected':''}>${esc(v)}</option>`).join('')}</select>${after&&state.answers[key]?'<p class="action">'+esc(actions[state.answers[key]])+'</p>':''}`);}).join('');}
function photo(stage){return card('Paper work and evidence',`<p>You may answer on paper instead of typing. Number your answers and add clear photographs. You can add more than one photo or paste a copied image on this page.</p><label>Add photos<input type="file" accept="image/png,image/jpeg,image/webp" multiple data-upload="${stage}"></label><p class="small">JPG, PNG or WebP; up to 15 MB each. Images are resized for the report.</p><div class="photo-grid">${(state.photos[stage]||[]).map((p,i)=>`<div class="photo"><img src="${p.data}" alt="${esc(p.caption||p.name)}"><label>Evidence shown<input data-caption="${stage}:${i}" value="${esc(p.caption)}"></label><button data-remove="${stage}:${i}">Remove photo</button></div>`).join('')}</div>`);}
function design(){return card('Design your table',`<p>Choose a data type for each field. Give maximum lengths for Text only; use the brief, not just the sample values.</p><div class="table-wrap"><table><caption>Club — your data dictionary</caption><thead><tr><th>Field</th><th>Data type</th><th>Text length</th><th>Reason</th></tr></thead><tbody>${state.design.map((f,i)=>`<tr><th scope="row">${f.name}</th><td><select aria-label="${f.name} type" data-design="${i}" data-prop="type"><option value="">Choose…</option>${['Text','Integer','Real','Boolean','Date'].map(t=>`<option ${f.type===t?'selected':''}>${t}</option>`).join('')}</select></td><td><input aria-label="${f.name} text length" data-design="${i}" data-prop="length" value="${esc(f.length)}" placeholder="If Text"></td><td><input aria-label="${f.name} reason" data-design="${i}" data-prop="reason" value="${esc(f.reason)}"></td></tr>`).join('')}</tbody></table></div><p>Create two valid example records. Keep the ClubCode values different.</p><div class="table-wrap"><table><caption>Your example records</caption><thead><tr>${L.heads.map(h=>'<th>'+h+'</th>').join('')}</tr></thead><tbody>${state.records.map((r,i)=>'<tr>'+r.map((v,j)=>`<td><input aria-label="Record ${i+1} ${L.heads[j]}" data-record="${i}:${j}" value="${esc(v)}"></td>`).join('')+'</tr>').join('')}</tbody></table></div>`);}
function query(task,stage){const [key,label]=task;return card(label,field(key+'prediction','Predict the matching ClubCodes.',''+stage,2)+field(key+'sql','Write your complete SQL query.',stage,4)+(key==='q1'?'<details><summary>Need a first step?</summary><p>Start with SELECT ClubCode, ClubName. Add FROM Club, then compare ClubName with a quoted text value.</p></details>':'')+`<button data-run="${key}" class="primary">Run query & save attempt</button>`+((state.attempts[key]||[]).length?'<div aria-live="polite">'+state.attempts[key].map((a,i)=>`<details ${i===state.attempts[key].length-1?'open':''}><summary>Attempt ${i+1} · ${esc(a.time)}</summary><pre><code>${esc(a.sql)}</code></pre><p><strong>Prediction:</strong> ${esc(a.prediction)}</p>${a.error?'<p class="error">'+esc(a.error)+'</p>':table('Actual result',a.result.heads,a.result.rows)+'<p class="action">'+esc(a.feedback)+'</p>'}</details>`).join('')+'</div>':'')+field(key+'reflection','Compare the result with your prediction. Explain any correction.',stage,2));}
function mark(){if(!unlocked)return card('Review after discussion','<p>Ask your teacher when to check your answers. You can continue improving your work while waiting.</p><label for="passcode">Teacher passcode</label><input id="passcode" type="password" autocomplete="off"><button id="unlock">Unlock review</button><p id="unlockError" role="alert"></p>');return card('Review your explanations','<p>Use these points to improve your answer, not replace your original attempt.</p><h3>Do Now</h3><p>3 records; 4 fields. ClubCode: Text to keep letters and digits. SessionHours: Real for fractional hours. Maximum length 40 allows up to 40 characters, not exactly 40. Robotics occurs twice; ClubCode distinguishes the records. FROM names the table; WHERE filters records.</p><h3>Main Task 1</h3><p>ClubCode: Text, length 6. ClubName: Text, length 40. Places: Integer. SessionHours: Real. OpenToBeginners: Boolean. ClubCode is unique and required; ClubName can repeat. A duplicate code must be rejected or replaced by a new unique code. 999 is an Integer but exceeds the permitted capacity of 30.</p><h3>Main Task 2</h3>'+L.tasks.slice(0,4).map(t=>'<p>'+esc(t[1])+'</p><pre><code>'+esc(t[2])+'</code></pre>').join('')+'<p>For “at least 15”, use >= 15. The > operator wrongly excludes Photography.</p><h3>Plenary</h3><p>BookID uniquely identifies a record and is never missing; Title may repeat.</p><pre><code>SELECT Title\nFROM Book\nWHERE Copies &lt; 3;</code></pre><p>Removing WHERE returns all three records but still only the Title field. Repeated title values remain; SELECT alone does not remove duplicates.</p><button id="lock">Lock review</button>')+field('reviewCorrection','Which answer did you improve, and why?','mark');}
function content(id){return L.render({card,field,table,photo,checks,mcq,design,query,state,esc,mark},id);}
function render(){if(classroomTarget){state.step=L.stages.findIndex(s=>s[0]===classroomTarget);classroomTarget=null;}const[id,title,time]=L.stages[state.step];$('identity').textContent=state.name+' · '+(state.cls||'Teacher preview');$('content').innerHTML=`<div class="stage-head"><p class="eyebrow">${esc(time)} · WEEK 5 SESSION 3</p><h1 tabindex="-1">${title}</h1></div>`+content(id);$('nav').innerHTML=L.stages.map((s,i)=>`<button data-step="${i}" ${i===state.step?'aria-current="step"':''}>${String(i+1).padStart(2,'0')} · ${s[1]}</button>`).join('');$('prev').disabled=state.step===0;$('next').disabled=state.step===L.stages.length-1;$('position').textContent=`${state.step+1} / ${L.stages.length} · ${title}`;document.querySelectorAll('textarea[id$="sql"]').forEach(t=>{t.classList.add('sql-editor');t.spellcheck=false;});classroomChanged();}
function show(){ $('landing').hidden=true;$('lesson').hidden=false;$('backup').disabled=false;$('pdf').disabled=false;render();}
function go(n,remote=false){if(!state||(!remote&&classroomLocked()))return;state.step=Math.max(0,Math.min(n,L.stages.length-1));render();save();scrollTo(0,0);$('content').querySelector('h1').focus({preventScroll:true});}
$('login').addEventListener('submit',async e=>{e.preventDefault();const name=$('name').value.trim(),cls=$('class').value.trim();if(!name||(!cls&&name.toLowerCase()!=='teacher'))return $('loginError').textContent='Enter your name and class.';state=blank(name,cls);try{db=db||await openDB();const prior=await new Promise((resolve,reject)=>{const r=db.transaction('profiles').objectStore('profiles').get(profile());r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});if(prior)state=validate(prior);}catch{}unlocked=false;show();save();});
document.addEventListener('input',e=>{if(!state)return;const t=e.target;if(t.dataset.answer)state.answers[t.dataset.answer]=t.value;if(t.dataset.design!==undefined)state.design[Number(t.dataset.design)][t.dataset.prop]=t.value;if(t.dataset.record){const[i,j]=t.dataset.record.split(':').map(Number);state.records[i][j]=t.value;}if(t.dataset.caption){const[s,i]=t.dataset.caption.split(':');state.photos[s][i].caption=t.value;}save();});
document.addEventListener('change',e=>{if(!state)return;const t=e.target;if(t.dataset.upload)upload(t.files,t.dataset.upload);if(t.matches('select[data-answer], input[type=radio][data-answer]')){state.answers[t.dataset.answer]=t.value;save();const id=t.id;render();if(id)$(id)?.focus();}});
document.addEventListener('keydown',e=>{if(e.key==='Tab'&&e.target.matches('.sql-editor')){e.preventDefault();const t=e.target;t.setRangeText('    ',t.selectionStart,t.selectionEnd,'end');t.dispatchEvent(new Event('input',{bubbles:true}));}});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.id==='confirmRestore'){state=pending;pending=null;unlocked=false;try{db=db||await openDB();}catch{}show();save();$('restorePanel').hidden=true;return;}if(b.id==='cancelRestore'){$('restorePanel').hidden=true;pending=null;return;}if(!state)return;
 if(b.dataset.step!==undefined)go(Number(b.dataset.step));if(b.id==='prev')go(state.step-1);if(b.id==='next')go(state.step+1);
 if(b.id==='backup')backup();if(b.id==='pdf')exportPDF();
 if(b.id==='switch'){await queue;state=null;unlocked=false;$('landing').hidden=false;$('lesson').hidden=true;$('backup').disabled=true;$('pdf').disabled=true;$('identity').textContent='YEAR 11 · WEEK 5 · SESSION 3';$('saveStatus').textContent='Start or restore your lesson to save work.';classroomChanged();}
 if(b.id==='unlock'){if($('passcode').value==='Y11isawesome'){unlocked=true;render();}else $('unlockError').textContent='That passcode was not recognised.';}if(b.id==='lock'){unlocked=false;render();}
 if(b.dataset.run){const key=b.dataset.run,prediction=state.answers[key+'prediction']?.trim(),sql=state.answers[key+'sql']?.trim();if(!prediction||!sql){alert('Add your prediction and SQL before running.');return;}const a={time:new Date().toLocaleTimeString('en-GB'),sql,prediction};try{a.result=runClubSQL(sql);const expected=runClubSQL(L.tasks.find(t=>t[0]===key)[2]);const rows=r=>r.rows.map(v=>JSON.stringify(v)).sort().join('|');a.feedback=JSON.stringify(a.result.heads.map(h=>h.toLowerCase()))===JSON.stringify(expected.heads.map(h=>h.toLowerCase()))&&rows(a.result)===rows(expected)?'This result matches the requested fields and records. Explain why it is correct.':'The query ran, but its result does not yet match the request. Check the selected fields and the boundary in the condition.';}catch(err){a.error=err.message;}(state.attempts[key]??=[]).push(a);save();render();document.querySelector(`[data-run="${key}"]`)?.scrollIntoView({block:'center'});}
 if(b.dataset.remove&&confirm('Remove this photograph?')){const[s,i]=b.dataset.remove.split(':');state.photos[s].splice(Number(i),1);save();render();}
});
async function upload(files,stage){const owner=state;try{for(const file of files){if(!/^image\/(png|jpeg|webp)$/.test(file.type)||file.size>15*1024*1024)throw Error('Use JPG, PNG or WebP images up to 15 MB each.');const raw=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);}),im=new Image();await new Promise((resolve,reject)=>{im.onload=resolve;im.onerror=reject;im.src=raw;});const scale=Math.min(1,2200/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*scale);c.height=Math.round(im.height*scale);const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(im,0,0,c.width,c.height);if(state!==owner)return;(state.photos[stage]??=[]).push({name:file.name||'Pasted image',caption:'',data:c.toDataURL('image/jpeg',.92)});}await save();render();}catch(err){alert(err.message||'Could not load the image.');}}
document.addEventListener('paste',e=>{if(!state)return;const stage=L.stages[state.step][0];if(!['start','main1','main2','extension','exit'].includes(stage))return;const files=[...(e.clipboardData?.items||[])].filter(x=>x.type.startsWith('image/')).map(x=>x.getAsFile());if(files.length){e.preventDefault();upload(files,stage);}});
const filename=()=>('Year11_W5S3_'+state.name).replace(/[^a-z0-9_-]/gi,'_');
function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),30000);}
function backup(){download(new Blob([JSON.stringify({app:APP,state})],{type:'application/json'}),filename()+'.json');}
function validate(s){const obj=x=>x&&typeof x==='object'&&!Array.isArray(x);if(!obj(s)||s.version!==1||typeof s.name!=='string'||!s.name.trim()||typeof s.cls!=='string'||typeof s.date!=='string'||!Number.isInteger(s.step)||s.step<0||s.step>=L.stages.length||!obj(s.answers)||!obj(s.photos)||!obj(s.attempts)||!Array.isArray(s.design)||s.design.length!==5||!Array.isArray(s.records)||s.records.length!==2)throw Error('Invalid lesson backup.');for(const v of Object.values(s.answers))if(typeof v!=='string')throw Error('Invalid answer.');s.design.forEach((f,i)=>{if(!obj(f)||f.name!==L.heads[i]||['type','length','reason'].some(k=>typeof f[k]!=='string'))throw Error('Invalid design.');});for(const r of s.records)if(!Array.isArray(r)||r.length!==5||r.some(v=>typeof v!=='string'))throw Error('Invalid record.');for(const[k,arr]of Object.entries(s.photos)){if(!L.stages.some(x=>x[0]===k)||!Array.isArray(arr))throw Error('Invalid photo page.');for(const p of arr)if(!obj(p)||typeof p.name!=='string'||typeof p.caption!=='string'||!/^data:image\/jpeg;base64,[A-Za-z0-9+/=]+$/.test(p.data))throw Error('Invalid photo.');}for(const[k,arr]of Object.entries(s.attempts)){if(!L.tasks.some(t=>t[0]===k)||!Array.isArray(arr))throw Error('Invalid SQL history.');for(const a of arr){if(!obj(a)||['time','sql','prediction'].some(k=>typeof a[k]!=='string'))throw Error('Invalid attempt.');if(a.error){if(typeof a.error!=='string')throw Error('Invalid error.');}else if(!obj(a.result)||!Array.isArray(a.result.heads)||!Array.isArray(a.result.rows)||a.result.heads.some(h=>!L.heads.includes(h))||a.result.rows.some(r=>!Array.isArray(r)||r.length!==a.result.heads.length||r.some(v=>!['string','number'].includes(typeof v)))||typeof a.feedback!=='string')throw Error('Invalid result.');}}return s;}
$('restore').addEventListener('change',async e=>{pending=null;$('restorePanel').hidden=true;try{const f=e.target.files[0];if(!f)return;if(f.size>80*1024*1024)throw Error('Backup exceeds 80 MB.');const data=JSON.parse(await f.text());if(data.app!==APP)throw Error('Choose a Week 5 Session 3 backup.');pending=validate(data.state);$('restoreSummary').textContent=`Restore ${pending.name} (${pending.cls})? This replaces this student’s saved work for this lesson.`;$('restorePanel').hidden=false;$('loginError').textContent='';}catch(err){$('loginError').textContent=err.message;}});
async function exportPDF(){const b=$('pdf');b.disabled=true;try{L.stages.forEach(([id])=>content(id));const {jsPDF}=window.jspdf,d=new jsPDF({unit:'mm',format:'a4',compress:true});d.addFileToVFS('Raleway.ttf',PDF_FONTS.regular);d.addFont('Raleway.ttf','Raleway','normal');d.addFileToVFS('RalewayBold.ttf',PDF_FONTS.bold);d.addFont('RalewayBold.ttf','Raleway','bold');let y=22;const page=()=>{d.addPage();y=22;};const text=(v,size=11,bold=false,mono=false)=>{d.setFont(mono?'courier':'Raleway',bold?'bold':'normal');d.setFontSize(size);const lines=d.splitTextToSize(String(v||'Not recorded'),174);for(const line of lines){if(y>270)page();d.text(line,18,y);y+=size*.5;}y+=3;};
text('YEAR 11 · WEEK 5 · SESSION 3',12,true);text(L.title,22,true);text(state.name+' · '+state.cls+' · '+state.date);text('WAGBA: Choosing how to organise data and retrieving exactly the information we need.');text('Lesson evidence: responses, design decisions, query attempts and paper work.');
for(const[id,title]of L.stages.filter(s=>!['submit','mark'].includes(s[0]))){page();text(title,18,true);for(const[k,m]of meta){if(m.stage===id){text(m.label,10,true);text(state.answers[k],11,false,k.endsWith('sql'));}}
if(id==='main1'){text('My Club data dictionary',13,true);for(const f of state.design){text(f.name,11,true);text('Type: '+(f.type||'Not recorded')+' | Text length: '+(f.length||'Not recorded'));text('Reason: '+(f.reason||'Not recorded'));}state.records.forEach((r,i)=>{text('My record '+(i+1),12,true);r.forEach((v,j)=>text(L.heads[j]+': '+(v||'Not recorded')));});}
if(id==='extension')text('Paper extension: collect the June 2023 handout (07.1 and 07.4, 5 marks) from your teacher. Complete and return it on paper.'); if(id==='main2'){for(const t of L.tasks.filter(t=>id==='extension'?t[0]==='qx':t[0]!=='qx')){text(t[1],12,true);for(const[aIndex,a]of(state.attempts[t[0]]||[]).entries()){text('Attempt '+(aIndex+1)+' · '+a.time,11,true);text('Prediction: '+a.prediction);text(a.sql,10,false,true);if(a.error)text('Error: '+a.error);else{text('Result fields: '+a.result.heads.join(' | '));if(!a.result.rows.length)text('No matching records.');for(const r of a.result.rows)text(r.join(' | '));text(a.feedback);}}}}
for(const p of state.photos[id]||[]){const props=d.getImageProperties(p.data),scale=Math.min(174/props.width,210/props.height),w=props.width*scale,h=props.height*scale;if(y+h+20>270)page();text(p.caption||p.name,10,true);if(y+h>270)page();d.addImage(p.data,'JPEG',18,y,w,h);y+=h+8;}}
if(state.answers.reviewCorrection){page();text('My correction after review',16,true);text(state.answers.reviewCorrection);}
const total=d.getNumberOfPages();for(let i=1;i<=total;i++){d.setPage(i);d.setFont('Raleway','normal');d.setFontSize(8);d.line(18,282,192,282);d.text('Primary keys & SQL · '+state.name.slice(0,45),18,288);d.text(i+' / '+total,192,288,{align:'right'});}d.save(filename()+'.pdf');$('saveStatus').textContent='PDF downloaded — check it before submitting.';}catch(err){alert('PDF could not be saved. Keep a Full backup. '+err.message);}finally{b.disabled=false;}}
window.addEventListener('beforeunload',e=>{if(state&&unsaved){e.preventDefault();e.returnValue='';}});
})();
