window.LESSON={
 title:'Primary keys and SQL retrieval',
 stages:[['read','Read first','5 min'],['start','Do Now','4 min'],['before','Types of Learning','3 min'],['main1','Main Task 1','15 min'],['sql','Read SQL','5 min'],['main2','Main Task 2','18 min'],['pit','Learning Pitstop','3 min'],['exit','Plenary','5 min'],['extension','Extension','Within task time'],['mark','Review answers','After teacher discussion'],['submit','PDF submission','2 min']],
 targets:[['Knowledge','I can explain a primary key and the purpose of SELECT, FROM and WHERE.','Use a definition or one line of a query.'],['Skills','I can choose types and lengths, identify a key and write a query that runs.','Use your design and a saved SQL attempt.'],['Understanding','I can justify a key and explain which records and fields a query returns.','Use your key explanation and a predicted result.']],
 heads:['ClubCode','ClubName','Places','SessionHours','OpenToBeginners'],
 rows:[['RB0014','Robotics',18,1.5,'True'],['AR0021','Art',12,1,'True'],['RB0018','Robotics',10,1,'False'],['DR0032','Drama',30,2,'True'],['CH0040','Chess',16,0.5,'True'],['PH0051','Photography',15,1.5,'False']],
 tasks:[
 ['q1','Display ClubCode and ClubName for groups named Robotics.',"SELECT ClubCode, ClubName\nFROM Club\nWHERE ClubName = 'Robotics';"],
 ['q2','Display ClubName and SessionHours for every group.','SELECT ClubName, SessionHours FROM Club;'],
 ['q3','Display ClubCode and ClubName for sessions lasting no more than one hour.','SELECT ClubCode, ClubName FROM Club WHERE SessionHours <= 1;'],
 ['q4','Display ClubCode, ClubName and Places for groups with at least 15 places.','SELECT ClubCode, ClubName, Places FROM Club WHERE Places >= 15;'],
 ['qx','Display ClubCode, ClubName and SessionHours for Robotics groups lasting no more than one hour.',"SELECT ClubCode, ClubName, SessionHours FROM Club WHERE ClubName = 'Robotics' AND SessionHours <= 1;"]
 ],
 render(H,id){const {card,field,table,photo,checks,mcq,design,query,state,esc}=H;
 const club=()=>table('Club — each record describes one club group',this.heads,this.rows);
 const code=t=>'<pre><code>'+esc(t)+'</code></pre>';
 const source='<p class="small">Aligned to OxfordAQA 9210, sections 3.7.2–3.7.3. <a href="https://www.oxfordaqa.com/wp-content/uploads/2025/02/oxfordaqa-gcse-computer-science-specification.pdf" target="_blank" rel="noopener">Open the specification</a>. The explanations and practice here are lesson materials, not quotations from an exam paper.</p>';
 switch(id){
 case 'read':return card('One record. One reliable identifier.','<p>A <strong>table</strong> stores data about one kind of thing. A <strong>record</strong> contains the related values for one item; a <strong>field</strong> describes one attribute. Here, a record describes one club group.</p><p>A <strong>primary key</strong> is a field, or combination of fields, that uniquely identifies every record. Its value must not be missing, and two records cannot have the same key value. Today we use a single field as the key.</p>'+table('Two groups can share a name',['ClubCode','ClubName','Places'],this.rows.filter(r=>r[1]==='Robotics').map(r=>r.slice(0,3)))+'<p>The school gives each group a unique ClubCode and never reuses it. <strong>ClubName is not suitable:</strong> Robotics describes two different groups. Even if names happened to be different today, that would not guarantee unique names in future. A key does not have to be a number or the first column.</p>')+card('Ask the database a question','<p>A <strong>query</strong> retrieves information. In SQL, <strong>SELECT</strong> chooses the fields to display, <strong>FROM</strong> names the table, and <strong>WHERE</strong> filters records using a condition.</p>'+code('SELECT ClubCode, ClubName\nFROM Club\nWHERE Places > 15;')+'<p>This asks for two fields from Club, but only for groups with more than 15 places. It does not change or delete the other records. The order is SELECT → FROM → WHERE. Without WHERE, all records are returned.</p>')+mcq('r1','Which rule must a primary key meet?',['Every value is unique and not missing.','Every value is an integer.','Every value is a person’s name.'],'Every value is unique and not missing.','A primary key must identify exactly one record.')+mcq('r2','Which keyword chooses the fields to display?',['WHERE','SELECT','FROM'],'SELECT','SELECT lists the fields; FROM names the table.')+mcq('r3','What does WHERE Places > 15 do?',['Changes all places to 15.','Selects records with more than 15 places.','Shows only the Places field.'],'Selects records with more than 15 places.','WHERE filters records. A value of exactly 15 does not meet > 15.')+source;
 case 'start':return card('Recall, then apply','<p>Work independently. Use Read first if you need support, then explain one answer to a partner.</p>'+table('Club — starter sample',this.heads.slice(0,4),this.rows.slice(0,3).map(r=>r.slice(0,4))))+field('s1','1. How many records and fields are shown?','start',2)+field('s2','2. Give suitable data types for ClubCode and SessionHours. Explain why each fits.','start')+field('s3','3. ClubName allows up to 40 characters. Does every name need 40 characters? Explain.','start',2)+field('s4','4. Why can “Robotics” not identify just one record? Which field can?','start',2)+field('s5','5. Which SQL keyword chooses the table? Which filters records?','start',2)+photo('start');
 case 'before':return card('What are we getting better at?','<p><strong>Amazing Learning happens when we practice, try hard and use good struggle to get better.</strong></p><p>We get better by building Knowledge, Skills and Understanding.</p><p><strong>Knowledge:</strong> recall a term and give an example. <strong>Skills:</strong> practise a query and compare the result with your prediction. <strong>Understanding:</strong> explain why a design works, not just whether it runs.</p><p>Choose your starting point for each target. These are not grades or fixed types of learner.</p>')+checks(false)+field('focus','Which target will you focus on, and what will you do to improve?','before',2);
 case 'main1':return card('Your brief: a searchable club directory','<p>The activities coordinator needs a table called <strong>Club</strong>. Each record describes one club group. Different groups may share a club name.</p><ul><li>ClubCode is a unique code of two uppercase letters followed by four digits. Codes are never reused.</li><li>ClubName may contain up to 40 characters, including spaces.</li><li>Places is a whole-number capacity from 1 to 30.</li><li>SessionHours can range from 0.5 to 3, including fractional hours.</li><li>OpenToBeginners records True or False.</li></ul><p>Use the five field names below. Choose their types and text lengths yourself. Name your primary key, then add two different example records. You can complete this on paper and upload a photograph instead.</p>'+club())+design()+field('key','Which field is the primary key? Explain both why it works and why ClubName does not.','main1')+field('duplicate','A new group tries to use RB0014, which already exists. What should happen, and why?','main1')+field('range','Could 999 have the correct data type for Places but still be unsuitable? Explain.','main1')+card('Show me your reasoning','<p>Show your teacher your primary key and one type/length decision. While waiting, check your two records against every requirement.</p>')+field('feedback1','What feedback did you receive? Record one improvement you made.','main1')+photo('main1');
 case 'sql':return card('Read a query from top to bottom',club()+code('SELECT ClubCode, ClubName\nFROM Club\nWHERE Places > 15;')+table('Read each line',['Part','Meaning'],[['SELECT ClubCode, ClubName','Display these two fields. Separate field names with commas.'],['FROM Club','Use the table called Club.'],['WHERE Places > 15','Keep only records whose Places value is greater than 15.']])+'<p>The result contains RB0014, DR0032 and CH0040, with their club names. Photography has exactly 15 places, so it does not appear. The Places field can be used in the condition without appearing in the output.</p>')+card('Text, numbers and comparison operators',code("SELECT ClubCode, Places\nFROM Club\nWHERE ClubName = 'Art';")+'<p>Put text values in single quotes. Do not put field names in quotes. Numeric values such as 15 do not need quotes. Capitalising keywords helps readability; SQL keywords are not case-sensitive.</p>'+table('Choose the condition carefully',['Meaning','Operator'],[['Equal to','='],['More than','>'],['At least','>='],['Less than','<'],['No more than','<='],['Not equal to','<>']])+'<p>SELECT * displays all fields. For these tasks, list only the fields requested. End a query with a semicolon. Indentation and line breaks make SQL easier to read.</p>')+mcq('r4','Which condition means “no more than one hour”?',['SessionHours < 1','SessionHours <= 1','SessionHours >= 1'],'SessionHours <= 1','No more than includes exactly one hour.')+mcq('r5','What changes if WHERE is removed?',['All records are returned; the selected fields stay the same.','All fields are returned.','The table is deleted.'],'All records are returned; the selected fields stay the same.','SELECT still determines the output fields.');
 case 'main2':return card('Help the coordinator find the right groups','<p>Use the fixed Club table below for every query. This lets you check SQL even if you are still improving your own table design.</p><ol><li>Predict the matching ClubCodes before running.</li><li>Type the complete query in the SQL editor.</li><li>Run it, compare the result, and explain any correction.</li></ol><p>The practice runner supports one Club table, SELECT, FROM, WHERE, comparison operators and AND. It is a small learning simulator, not a full database system.</p>'+club())+this.tasks.slice(0,4).map(t=>query(t,'main2')).join('')+field('debug','A query for “at least 15 places” uses WHERE Places > 15. Explain the error and write the corrected condition.','main2')+field('feedback2','Show your teacher a predicted and actual result. What did you check or improve?','main2')+photo('main2');
 case 'pit':return card('Where am I now?','<p><strong>New learning:</strong> I am making progress through a useful struggle.<br><strong>Consolidating:</strong> I am making existing knowledge more secure.<br><strong>Treading water:</strong> I need more challenge.<br><strong>Drowning:</strong> I need a smaller guided step and help.</p><p>Choose a phase for each target, using evidence from your work. This is not a grade and does not send your teacher an alert. If you need support, ask now.</p>')+checks(true)+field('pitEvidence','Name one answer or SQL attempt that shows your progress. What will you do next?','pit');
 case 'exit':return card('A new situation: the library','<p>Work independently, without the reading or SQL runner. Each record describes a book title held by the library. BookID is unique and never missing. Different records may have the same Title, such as different editions.</p>'+table('Book',['BookID','Title','Copies'],[['BK001','Python basics',2],['BK002','Networks',3],['BK003','Python basics',1]]))+field('p1','1. Explain why BookID is a more suitable primary key than Title.','exit')+field('p2','2. Write SQL to display Title for books with fewer than three copies.','exit')+field('p3','3. What would change if you removed the WHERE line? Refer to records and fields.','exit')+photo('exit');
 case 'extension':return card('Collect your paper extension','<p><strong>Come to me and collect the printed Paper 2 extension.</strong> You will answer it on paper in class, not on this website.</p><ol><li>Write your name and class on the handout.</li><li>Read the original scenario and Figure 2.</li><li>Answer June 2023 questions <strong>07.1 and 07.4</strong> in the spaces provided (5 marks altogether).</li><li>Bring your completed paper to me for feedback.</li></ol><p>Question 07.4 uses AND: both conditions must be true for a record to match. Refer to the field names in the printed table.</p><p>Keep this page open as your reminder, then work on the handout. There is nothing to type or upload here.</p>');
 case 'mark':return H.mark();
 case 'submit':return card('Submit your learning','<ol><li>Select <strong>Full backup</strong> at the top right. Keep this file so you can restore your work.</li><li>Select <strong>Save PDF</strong>. The report includes all pages’ responses, table design, SQL attempts and photos.</li><li>Open the PDF and check that your work is readable.</li><li>Attach the PDF to your teacher’s Teams assignment and select <strong>Turn in</strong>.</li></ol><p>This app does not upload anything to Teams. A backup contains your work and photos: keep it private.</p><a href="https://teams.microsoft.com/" target="_blank" rel="noopener">Open Teams</a>')+source;
 }}};
