/* Daily lesson clock uses Malaysia time on the device; it never changes lesson pages. */
window.SESSION_PLAN=Object.freeze({zone:'Asia/Kuala_Lumpur',start:680,end:740,topic:'Primary keys and single-table SQL',wagba:'Choosing how to organise data and retrieving exactly the information we need.',keywords:'Primary key · record · field · data type · field length · query · SELECT · FROM · WHERE',challenge:'Prove that your key and query still work when new records are added.',stages:[
 {id:'read',start:680,end:685,title:'Read first',steps:['Read the Club example. Identify what each record represents.','Explain why ClubCode identifies one group but ClubName may repeat.','Read SELECT, FROM and WHERE. Try the reading checks.']},
 {id:'start',start:685,end:689,title:'Do Now',steps:['Answer the five starter questions using the example table.','Count records and fields. Choose suitable types and explain the repeated name.','Recall which SQL keyword chooses a table and which filters records.']},
 {id:'before',start:689,end:692,title:'Types of Learning',steps:['Use your starter answers to judge Knowledge, Skills and Understanding separately.','Identify something you already know and one thing to improve.','Choose an action: clarify a term, practise a query, or explain a reason.']},
 {id:'main1',start:692,end:707,title:'Main Task 1 · Design a table',steps:['Read all five field requirements. Choose a type and any text length for each field.','Choose the primary key and add two different example records.','Explain a duplicate code and why 999 is unsuitable for Places. Show one decision to your teacher.']},
 {id:'sql',start:707,end:712,title:'Read SQL',steps:['Read the example query one line at a time: SELECT → FROM → WHERE.','Predict which ClubCodes match Places > 15. Explain why exactly 15 is excluded.','Check text quotes and the difference between > and >=.']},
 {id:'main2',start:712,end:730,title:'Main Task 2 · Query, test, improve',steps:['Use the fixed Club table. Predict the matching ClubCodes before each run.','Write and run the four queries. Compare the actual fields and records with your prediction.','Correct the “at least 15” condition. Show your teacher a result and explain a change.']},
 {id:'pit',start:730,end:733,title:'Learning Pitstop',steps:['Consider Knowledge, Skills and Understanding separately.','Choose your learning phase using one answer, design decision or saved SQL attempt.','Explain your evidence and next action. Ask directly if you need help.']},
 {id:'exit',start:733,end:738,title:'Plenary · Apply it to books',steps:['Work independently, without the SQL runner.','Explain why BookID is a better key than Title.','Write a query for titles with fewer than three copies; explain removing WHERE.']},
 {id:'submit',start:738,end:740,title:'Save and submit',steps:['Save a full backup, then save your PDF.','Open the PDF and check your name, work and results.','Attach the PDF to the correct Teams assignment and select Turn in.']}
]});
window.LessonClock=Object.freeze({
 at(seconds){const p=window.SESSION_PLAN,stage=p.stages.find(s=>seconds>=s.start*60&&seconds<s.end*60);return seconds<p.start*60?{phase:'before',stage:p.stages[0],remaining:p.start*60-seconds}:seconds>=p.end*60?{phase:'after',stage:p.stages.at(-1),remaining:0}:{phase:'active',stage,remaining:stage.end*60-seconds};},
 seconds(date=new Date()){const a=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:window.SESSION_PLAN.zone,hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(date).map(x=>[x.type,x.value]));return +a.hour*3600 + +a.minute*60 + +a.second;},
 time(minutes){return `${String(Math.floor(minutes/60)).padStart(2,'0')}:${String(minutes%60).padStart(2,'0')}`;}
});
