'use strict';
const $=id=>document.getElementById(id),editor=$('editor'),STORE='year9-practical-creation-v2';
const labels={
 en:{subtitle:'Practical checkpoint · read and answer on your paper',intro:'Use your paper for the scenario, sample code, predictions and answers. Type your Python here. Discuss with your partner and swap who uses the editor.',purpose:'WAGBA: Complete, test and improve a helpdesk program.',practiceTab:'Main Task 1 · Explore',createTab:'Main Task 2 · Create',practiceHint:'Paper page 2 · type the sample, run it, then predict and make the changes.',createHint:'Paper pages 3–7 · use the code bank to build, test and improve your adviser.',scaffold:'Load guided scaffold',indent:'Indent →',dedent:'← Dedent',run:'▶ Run',stop:'■ Stop',open:'Open .py',download:'Download .py',clear:'Clear',send:'Send',ready:'Ready. Type your code, then press Run.',running:'Running…',waiting:'Answer the program question below.',done:'Program finished.',stopped:'Stopped. You can edit and run again.',empty:'Type some Python before pressing Run.',saved:'Saved in this browser',failedSave:'Browser saving unavailable — download your code.',error:'Python reported an error. Read the last line and check the stated code line.',footer:'Record results on paper. Download your final program and submit it in Teams.',helpButton:'Editor help',codeTitle:'Code',consoleTitle:'Console',inputLabel:'Program input',fileLabel:'File name',undo:'Undo',redo:'Redo',indentHint:'4 spaces · no code suggestions'},
 zh:{subtitle:'Practical checkpoint · 纸上阅读与作答',intro:'情境、示例代码、预测与答案都在试卷上。在这里输入 Python。与同伴讨论，并轮流操作编辑器。',purpose:'WAGBA: 完成、测试并改进服务台程序。',practiceTab:'Main Task 1 · 运行与修改',createTab:'Main Task 2 · 创建',practiceHint:'试卷第2页：输入示例并运行，再预测和修改。',createHint:'试卷第3–7页：使用代码示例创建、测试和改进程序。',scaffold:'Load guided scaffold · 加载框架',indent:'Indent → 缩进',dedent:'← Dedent 取消缩进',run:'▶ Run 运行',stop:'■ Stop 停止',open:'Open .py 打开',download:'Download .py 下载',clear:'Clear 清空',send:'Send 发送',ready:'准备好后输入 Python，并按 Run。',running:'正在运行…',waiting:'请在下面回答程序的问题。',done:'程序运行结束。',stopped:'已停止。可以修改并再次运行。',empty:'请先输入 Python 代码。',saved:'已保存在此浏览器',failedSave:'无法在浏览器保存，请下载代码。',error:'Python 报错了。阅读最后一行，并检查指出的代码行。',footer:'在试卷上记录结果。下载最终程序，并提交到 Teams。',helpButton:'Editor help 使用说明',codeTitle:'Code 代码',consoleTitle:'Console 控制台',inputLabel:'Program input 程序输入',fileLabel:'File name 文件名',undo:'Undo 撤销',redo:'Redo 重做',indentHint:'4个空格 · 无代码预测'},
 ms:{subtitle:'Practical checkpoint · baca dan jawab pada kertas',intro:'Gunakan kertas untuk situasi, contoh kod, ramalan dan jawapan. Taip Python di sini. Bincang dan bergilir menggunakan editor.',purpose:'WAGBA: Lengkapkan, uji dan tambah baik program meja bantuan.',practiceTab:'Main Task 1 · Teroka',createTab:'Main Task 2 · Cipta',practiceHint:'Kertas halaman 2 · taip contoh, jalankan, kemudian ramal dan ubah.',createHint:'Kertas halaman 3–7 · guna contoh kod untuk membina, menguji dan menambah baik.',scaffold:'Muat rangka kod',indent:'Indent →',dedent:'← Dedent',run:'▶ Run',stop:'■ Stop',open:'Buka .py',download:'Muat turun .py',clear:'Kosongkan',send:'Hantar',ready:'Taip kod, kemudian tekan Run.',running:'Sedang berjalan…',waiting:'Jawab soalan program di bawah.',done:'Program selesai.',stopped:'Dihentikan. Ubah dan jalankan semula.',empty:'Taip Python sebelum menekan Run.',saved:'Disimpan dalam pelayar ini',failedSave:'Simpanan tidak tersedia — muat turun kod.',error:'Python melaporkan ralat. Baca baris terakhir dan semak baris kod yang dinyatakan.',footer:'Catat hasil pada kertas. Muat turun program akhir dan hantar dalam Teams.',helpButton:'Bantuan editor',codeTitle:'Kod',consoleTitle:'Konsol',inputLabel:'Input program',fileLabel:'Nama fail',undo:'Undo',redo:'Redo',indentHint:'4 ruang · tiada cadangan kod'}
};
Object.assign(labels.en,{languageLabel:'Language',helpTitle:'Using the editor',helpRuntime:'This browser runs a local Python 3 subset for this checkpoint. It has no code suggestions or generated answers.',replaceTitle:'Replace this program?',replaceText:'Download your current work first if you want to keep a separate copy. You can also Undo immediately after replacing it.',cancelReplace:'Cancel',confirmReplace:'Replace'});
Object.assign(labels.zh,{languageLabel:'Language 语言',helpTitle:'Using the editor 使用说明',helpRuntime:'此浏览器运行适用于本次任务的 Python 3 子集。没有代码预测或自动生成答案。',replaceTitle:'Replace this program? 替换代码？',replaceText:'如需保留当前代码，请先下载。替换后也可立即按 Undo 撤销。',cancelReplace:'Cancel 取消',confirmReplace:'Replace 替换'});
Object.assign(labels.ms,{languageLabel:'Bahasa',helpTitle:'Menggunakan editor',helpRuntime:'Pelayar ini menjalankan subset Python 3 untuk tugasan ini. Tiada cadangan kod atau jawapan automatik.',replaceTitle:'Gantikan program ini?',replaceText:'Muat turun kod semasa untuk menyimpan salinan lain. Anda juga boleh Undo sejurus selepas menggantikannya.',cancelReplace:'Batal',confirmReplace:'Gantikan'});

const words={
 en:{heading:'Create your helpdesk adviser',subtitle:'Two Main Tasks · one program · 60 minutes · 40 marks',purpose:'WAGBA: Create a useful helpdesk adviser using inputs, a calculation and two advice paths.',intro:'Sam needs help before his next lesson. Each person takes 4 minutes, including Sam. Build a calculator, then turn the same program into an adviser. Use the references and make the messages yours.',exampleTitle:'What you are creating · example console',practiceTab:'Main Task 1 · Make a calculator',createTab:'Main Task 2 · Create an adviser',chooseCard:'Current build card',useCode:'Code you can use · do not type line numbers',upgradeLabel:'Choose one upgrade',previousCard:'← Previous card',nextCard:'Next card →',keepProgram:'Keep one program. Changing cards never replaces your code.',taskHint:'Your program · add each step to the same code',scaffold:'Load starter code',startHelpTitle:'Help me start',startHelpText:'Which line should go first? Put the fixed service time before asking the question.',startHelpAnswer:'Compare with the two-line reference above. Type those lines or use Load starter code. You can use this help without losing marks.',finishTitle:'Show your creation',finishChecks:'Paper page 5: run (2, 15) and (4, 15). Tick the advice you actually saw. Also check (2, 12): exactly enough time must be accepted. No prediction table.',individualTitle:'Your own turn · paper page 6',individualText:'Your partner pauses. Change only MINUTES_PER_PERSON from 4 to 3. Run with 1 person ahead and 7 minutes available. Record your changed line and result; complete the short explanation boxes. Set it back to 4 before your partner’s turn or final download. No extra written retest.',submitTitle:'Save and submit',submitSave:'Use a file name with your class and group names. Restore the service-time constant to 4, then Download .py.',submitOwn:'Own device: attach your downloaded .py to the practical submission in Teams and submit.',submitShared:'Shared device: one person uploads the team .py with all names. Each partner confirms submission with the teacher.',submitIPad:'iPad: look in Files → Downloads. Attach from Files in Teams. Open the editor in Safari if the Teams browser restricts typing or downloads.',submitPaper:'Everyone hands in their own named booklet. Short phrases are enough.',footer:'Build → run → make it yours. Keep your code saved before closing.',migrationNote:'Your earlier work has been kept. If both old tasks had code, the Create program was chosen; the original browser backup remains untouched.'},
 zh:{heading:'Create your helpdesk adviser · 创建建议工具',subtitle:'两个主任务 · 一个程序 · 60分钟 · 40分',purpose:'WAGBA: 使用输入、计算和两条建议分支创建有用的服务台工具。',intro:'Sam 想在上课前获得帮助。每人需要4分钟，包括 Sam。先创建计算器，再把同一个程序改成建议工具。可以使用示例，并写自己的信息。',exampleTitle:'你的作品会这样运行 · 控制台示例',practiceTab:'Main Task 1 · 创建计算器',createTab:'Main Task 2 · 创建建议工具',chooseCard:'当前创建步骤',useCode:'可以使用的代码 · 不要输入行号',upgradeLabel:'选择一项改进',previousCard:'← 上一张卡',nextCard:'下一张卡 →',keepProgram:'保留同一个程序。切换卡片不会替换代码。',taskHint:'你的程序 · 在同一份代码里逐步添加',scaffold:'Load starter code · 加载起始代码',startHelpTitle:'Help me start · 帮我开始',startHelpText:'哪一行应先出现？先设置固定服务时间，再询问人数。',startHelpAnswer:'对照上面的两行示例输入代码，或按 Load starter code。使用帮助不会扣分。',finishTitle:'展示你的作品',finishChecks:'试卷第5页：输入 (2, 15) 和 (4, 15)，勾选实际看到的建议。也检查 (2, 12)：时间刚好足够应被接受。不用填写预测表。',individualTitle:'自己操作 · 试卷第6页',individualText:'同伴暂停帮助。只把 MINUTES_PER_PERSON 从4改为3。人数输入1，可用时间输入7。记录修改行和结果，完成简短说明框。同伴操作前或最终下载前恢复为4。不必再写一次重测记录。',submitTitle:'保存并提交',submitSave:'文件名包含班级和小组姓名。服务时间常量恢复为4，再按 Download .py。',submitOwn:'自己的设备：在 Teams 的实践提交任务附上下载的 .py 并提交。',submitShared:'共享设备：一人上传含全部姓名的小组 .py，每位同伴向老师确认提交。',submitIPad:'iPad：在 Files → Downloads 找文件，再从 Teams 附上。Teams 浏览器限制输入或下载时，用 Safari 打开编辑器。',submitPaper:'每人交写有自己姓名的试卷。简短词句即可。',footer:'创建 → 运行 → 写出自己的作品。关闭前保存代码。',migrationNote:'之前的代码已保留。如果两个旧任务都有代码，优先保留 Create 程序；浏览器中的原备份未删除。'},
 ms:{heading:'Cipta penasihat meja bantuan',subtitle:'Dua Tugasan Utama · satu program · 60 minit · 40 markah',purpose:'WAGBA: Cipta penasihat berguna dengan input, pengiraan dan dua laluan nasihat.',intro:'Sam perlukan bantuan sebelum kelas. Setiap orang mengambil 4 minit, termasuk Sam. Bina kalkulator, kemudian jadikan program yang sama sebagai penasihat. Guna contoh dan tulis mesej sendiri.',exampleTitle:'Ciptaan anda · contoh konsol',practiceTab:'Tugasan 1 · Bina kalkulator',createTab:'Tugasan 2 · Cipta penasihat',chooseCard:'Kad binaan semasa',useCode:'Kod contoh · jangan taip nombor baris',upgradeLabel:'Pilih satu peningkatan',previousCard:'← Kad sebelumnya',nextCard:'Kad seterusnya →',keepProgram:'Kekalkan satu program. Menukar kad tidak menggantikan kod.',taskHint:'Program anda · tambah langkah pada kod yang sama',scaffold:'Muat kod permulaan',startHelpTitle:'Bantu saya mula',startHelpText:'Baris mana perlu dahulu? Tetapkan masa tetap sebelum bertanya soalan.',startHelpAnswer:'Bandingkan dengan contoh dua baris di atas. Taip atau guna Muat kod permulaan. Bantuan ini tidak mengurangkan markah.',finishTitle:'Tunjukkan ciptaan anda',finishChecks:'Halaman 5: Run (2, 15) dan (4, 15). Tandakan nasihat sebenar. Semak juga (2, 12): masa tepat cukup mesti diterima. Tiada jadual ramalan.',individualTitle:'Giliran sendiri · halaman 6',individualText:'Rakan berhenti membantu. Ubah MINUTES_PER_PERSON daripada 4 kepada 3 sahaja. Run dengan 1 orang dan 7 minit. Catat baris dan hasil; lengkapkan kotak penjelasan ringkas. Pulihkan kepada 4 sebelum giliran rakan atau muat turun akhir. Tiada catatan ujian tambahan.',submitTitle:'Simpan dan hantar',submitSave:'Gunakan nama fail dengan kelas dan ahli kumpulan. Pulihkan masa kepada 4, kemudian Muat turun .py.',submitOwn:'Peranti sendiri: lampirkan .py kepada tugasan praktikal dalam Teams dan hantar.',submitShared:'Peranti dikongsi: seorang menghantar .py pasukan dengan semua nama. Setiap ahli mengesahkan dengan guru.',submitIPad:'iPad: cari Files → Downloads, kemudian lampirkan melalui Teams. Guna Safari jika pelayar Teams menghadkan input atau muat turun.',submitPaper:'Setiap pelajar menyerahkan buku jawapan sendiri. Frasa ringkas memadai.',footer:'Bina → Run → jadikan milik anda. Simpan sebelum menutup.',migrationNote:'Kerja lama dikekalkan. Jika kedua-dua tugasan lama mempunyai kod, program Create dipilih; sandaran asal dalam pelayar tidak dipadam.'}
};
Object.assign(words.en,{inputHint:'Type a whole number, such as 2. Use digits only.',learningTitle:'Today’s learning',learningText:'Knowledge: input, integer, variable, constant and comparison. Skills: build, run and adapt Python. Understanding: explain why the calculation gives this advice.'});
Object.assign(words.zh,{inputHint:'只输入整数，例如2，不要输入单位。',learningTitle:'今天的学习',learningText:'知识：输入、整数、变量、常量和比较。技能：创建、运行和修改 Python。理解：说明计算为何产生这条建议。'});
Object.assign(words.ms,{inputHint:'Taip nombor bulat seperti 2. Digit sahaja.',learningTitle:'Pembelajaran hari ini',learningText:'Pengetahuan: input, integer, pemboleh ubah, pemalar dan perbandingan. Kemahiran: bina, Run dan ubah Python. Pemahaman: jelaskan mengapa pengiraan menghasilkan nasihat ini.'});
for(const lang of Object.keys(words))Object.assign(labels[lang],words[lang]);
const blank={tab:'create',stage:0,language:'en',upgrade:0,files:{create:{code:'',name:'year9_helpdesk'}}};
let state=blank,migrated=false;
try{const x=JSON.parse(localStorage.getItem(STORE));if(x&&labels[x.language]&&typeof x.files?.create?.code==='string'&&x.files.create.code.length<=20000&&typeof x.files.create.name==='string')state={...blank,...x,tab:'create',stage:Number.isInteger(x.stage)?Math.max(0,Math.min(5,x.stage)):0,upgrade:Number.isInteger(x.upgrade)?Math.max(0,Math.min(2,x.upgrade)):0};else{const old=JSON.parse(localStorage.getItem('year9-practical-editor-v1'));if(old){const m=LessonData.migrate(old);if(m.code.length<=20000){state={...blank,language:m.language,files:{create:{code:m.code,name:m.name}}};migrated=!!m.code;}}}}catch{}
let worker=null,pendingInput=null,replaceAction=null;let history={practice:[],create:[]},histIndex={practice:-1,create:-1};let saveTimer=null;
const t=k=>labels[state.language][k]||labels.en[k]||k;
function persist(){state.files[state.tab]={code:editor.value,name:$('filename').value};try{localStorage.setItem(STORE,JSON.stringify(state));$('saveState').textContent=t('saved');}catch{$('saveState').textContent=t('failedSave');}}
function escapeHTML(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function paint(){const text=editor.value;const tokens=/(#[^\n]*|"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'|\b(?:if|elif|else|for|while|in|not|and|or|True|False|None|try|except|def|return|import|from|break|continue|pass|class|raise)\b|\b\d+(?:\.\d+)?\b)/g;let html='',last=0;for(const m of text.matchAll(tokens)){html+=escapeHTML(text.slice(last,m.index));const v=m[0],cls=v.startsWith('#')?'comment':/^['"]/.test(v)?'str':/^\d/.test(v)?'num':'kw';html+=`<span class="${cls}">${escapeHTML(v)}</span>`;last=m.index+v.length;}html+=escapeHTML(text.slice(last));$('highlight').innerHTML=html+'\n';$('numbers').textContent=Array.from({length:text.split('\n').length},(_,i)=>i+1).join('\n');syncScroll();position();}
function syncScroll(){$('highlight').scrollTop=editor.scrollTop;$('highlight').scrollLeft=editor.scrollLeft;$('numbers').scrollTop=editor.scrollTop;}
function position(){const before=editor.value.slice(0,editor.selectionStart);$('cursor').textContent=`Line ${before.split('\n').length}, column ${before.length-before.lastIndexOf('\n')}`;}
function snapshot(){return {text:editor.value,start:editor.selectionStart,end:editor.selectionEnd};}
function remember(){const tab=state.tab,h=history[tab],s=snapshot();if(h[histIndex[tab]]?.text===s.text)return;h.splice(histIndex[tab]+1);h.push(s);if(h.length>150)h.shift();histIndex[tab]=h.length-1;}
function change(result){editor.value=result.text;editor.setSelectionRange(result.start,result.end);remember();paint();persist();}
function undo(delta){const k=state.tab,i=histIndex[k]+delta;if(i<0||i>=history[k].length)return;histIndex[k]=i;const s=history[k][i];editor.value=s.text;editor.setSelectionRange(s.start,s.end);paint();persist();}
function stop(message=true){worker?.terminate();worker=null;pendingInput=null;$('inputForm').hidden=true;$('run').disabled=false;$('stop').disabled=true;if(message)$('runState').textContent=t('stopped');}

function language(){document.documentElement.lang=state.language==='zh'?'zh-Hans':state.language;for(const id of Object.keys(labels.en))if($(id)&&id!=='runState')$(id).textContent=t(id);$('language').value=state.language;$('runState').textContent=t(worker?(pendingInput?'waiting':'running'):'ready');$('migrationNote').hidden=!migrated;
const help={en:['One program stays in the editor as you move through both Main Tasks.','Run asks input() questions in the console. Answer with Enter or Send.','After a colon, Enter adds four spaces. After the first indented print, press Enter and Dedent once before else:.','Open .py imports a file; Download .py saves your code. Download before changing devices.'],zh:['两个主任务使用同一个程序，切换步骤不会清空代码。','Run 后在控制台回答 input() 的问题，按 Enter 或 Send。','冒号后 Enter 自动添加4个空格。第一条缩进 print 后，Enter 再 Dedent 一次，然后输入 else:。','Open .py 打开文件；Download .py 保存代码。换设备前先下载。'],ms:['Satu program dikekalkan bagi kedua-dua tugasan.','Jawab input() dalam konsol dengan Enter atau Hantar.','Enter selepas titik bertindih menambah empat ruang. Selepas print berinden, Enter kemudian Dedent sekali sebelum else:.','Buka .py mengimport; Muat turun .py menyimpan. Simpan sebelum menukar peranti.']};$('helpSteps').replaceChildren(...help[state.language].map(s=>{const li=document.createElement('li');li.textContent=s;return li;}));renderGuide();}
function renderReference(el,code){el.replaceChildren(...code.trimEnd().split('\n').map((line,i)=>{const row=document.createElement('span');row.className='reference-line';const n=document.createElement('span');n.className='reference-number';n.textContent=i+1;const text=document.createElement('span');text.textContent=line;row.append(n,text);return row;}));}
function renderGuide(){const i=LessonData.index(state.language),s=LessonData.stages[state.stage];$('stageSelect').replaceChildren(...LessonData.stages.map((c,n)=>{const o=document.createElement('option');o.value=n;o.textContent=c.title[i];return o;}));$('stageSelect').value=state.stage;$('stageCount').textContent=`${state.stage+1} / 6`;$('stageTitle').textContent=s.title[i];$('stageGoal').textContent=s.goal[i];renderReference($('stageCode'),s.code);$('stageCode').parentElement.hidden=state.stage===5;$('useCode').hidden=state.stage===5;$('stageSteps').replaceChildren(...s.steps.map(v=>{const li=document.createElement('li');li.textContent=v[i];return li;}));$('stageChoice').textContent=s.choice[i];$('stageSuccess').textContent=s.success[i];$('startHelp').hidden=state.stage!==0;$('scaffold').hidden=state.stage!==0;$('upgradeControls').hidden=state.stage!==5;$('upgradeSelect').replaceChildren(...LessonData.upgrades.map((u,n)=>{const o=document.createElement('option');o.value=n;o.textContent=u.name[i];return o;}));$('upgradeSelect').value=state.upgrade;const u=LessonData.upgrades[state.upgrade];$('upgradeInstruction').textContent=u.instruction[i];renderReference($('upgradeCode'),u.code);$('upgradeTry').textContent=u.try[i];$('previousCard').disabled=state.stage===0;$('nextCard').disabled=state.stage===5;for(const [id,task] of [['practiceTab',1],['createTab',2]])$(id).setAttribute('aria-selected',String(s.task===task));$('workpanel').setAttribute('aria-labelledby',s.task===1?'practiceTab':'createTab');}
function selectStage(n){persist();state.stage=n;renderGuide();persist();}
function show(){editor.value=state.files.create.code;$('filename').value=state.files.create.name;language();remember();paint();}
function append(text){$('console').textContent+=text;$('console').scrollTop=$('console').scrollHeight;}
function run(){persist();if(!editor.value.trim()){$('runState').textContent=t('empty');return;}stop(false);$('console').textContent='';$('runState').textContent=t('running');$('run').disabled=true;$('stop').disabled=false;worker=createPythonWorker();const active=worker;active.onmessage=({data:d})=>{if(worker!==active)return;if(d.type==='output')append(d.text);else if(d.type==='input'){pendingInput=d.id;append(d.prompt);$('inputForm').hidden=false;$('inputLabel').textContent=d.prompt||t('inputLabel');$('answer').value='';$('runState').textContent=t('waiting');$('answer').focus({preventScroll:true});$('inputForm').scrollIntoView({block:'nearest',behavior:'smooth'});}else if(d.type==='done'||d.type==='error'){if(d.error)append('\n'+d.error+'\n');stop(false);$('runState').textContent=t(d.error?'error':'done');}};active.onerror=()=>{if(worker!==active)return;append('\nPython could not start. Keep the complete app folder together, or ask your teacher to reload the editor.\n');stop(false);$('runState').textContent=t('error');};active.postMessage({type:'run',code:editor.value});}
function requestReplace(action){replaceAction=action;if(!editor.value.trim()){action();return;}$('replaceDialog').showModal();}
editor.addEventListener('input',()=>{remember();paint();clearTimeout(saveTimer);saveTimer=setTimeout(persist,200);});
editor.addEventListener('keydown',e=>{if(e.isComposing)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo(e.shiftKey?1:-1);return;}if(e.key==='F5'){e.preventDefault();run();return;}if(e.key==='Enter'&&!e.ctrlKey&&!e.metaKey){e.preventDefault();change(EditorCore.newline(editor.value,editor.selectionStart,editor.selectionEnd));}else if(e.key==='Tab'){e.preventDefault();change(EditorCore.indent(editor.value,editor.selectionStart,editor.selectionEnd,e.shiftKey));}else if(e.key==='Backspace'){const r=EditorCore.backspace(editor.value,editor.selectionStart,editor.selectionEnd);if(r){e.preventDefault();change(r);}}});
// Touch keyboards often deliver beforeinput without a usable keydown.
editor.addEventListener('beforeinput',e=>{if(e.isComposing)return;if(e.inputType==='insertLineBreak'||e.inputType==='insertParagraph'){e.preventDefault();change(EditorCore.newline(editor.value,editor.selectionStart,editor.selectionEnd));}});
editor.addEventListener('scroll',syncScroll);editor.addEventListener('click',position);editor.addEventListener('keyup',position);editor.addEventListener('blur',persist);
for(const [id,dedent] of [['indent',false],['dedent',true]]){$(id).addEventListener('pointerdown',e=>e.preventDefault());$(id).onclick=()=>{change(EditorCore.indent(editor.value,editor.selectionStart,editor.selectionEnd,dedent));editor.focus({preventScroll:true});};}
$('undo').onclick=()=>undo(-1);$('redo').onclick=()=>undo(1);$('run').onclick=run;$('stop').onclick=()=>stop();$('practiceTab').onclick=()=>selectStage(0);$('createTab').onclick=()=>selectStage(3);$('stageSelect').onchange=()=>selectStage(Number($('stageSelect').value));$('previousCard').onclick=()=>selectStage(Math.max(0,state.stage-1));$('nextCard').onclick=()=>selectStage(Math.min(5,state.stage+1));$('upgradeSelect').onchange=()=>{state.upgrade=Number($('upgradeSelect').value);renderGuide();persist();};$('language').onchange=()=>{state.language=$('language').value;language();persist();};$('filename').oninput=persist;
$('inputForm').onsubmit=e=>{e.preventDefault();if(!worker||pendingInput===null)return;const value=$('answer').value;append(value+'\n');worker.postMessage({type:'input',id:pendingInput,value});pendingInput=null;$('inputForm').hidden=true;$('runState').textContent=t('running');};
$('clear').onclick=()=>{if(!worker){$('console').textContent='';$('runState').textContent=t('ready');}};$('scaffold').onclick=()=>requestReplace(()=>{stop(false);change({text:LessonData.first,start:LessonData.first.length,end:LessonData.first.length});editor.focus({preventScroll:true});});
$('cancelReplace').onclick=()=>{$('replaceDialog').close();replaceAction=null;};$('confirmReplace').onclick=()=>{$('replaceDialog').close();const action=replaceAction;replaceAction=null;action?.();};
$('open').onclick=()=>$('fileInput').click();$('fileInput').onchange=async()=>{const f=$('fileInput').files[0];if(!f)return;if(!/\.py$/i.test(f.name)||f.size>80000){$('runState').textContent='Choose a .py file smaller than 80 KB.';$('fileInput').value='';return;}const code=await f.text();if(code.length>20000){$('runState').textContent='This file is too long for the checkpoint editor.';return;}requestReplace(()=>{stop(false);$('filename').value=f.name.replace(/\.py$/i,'');change({text:code,start:0,end:0});});$('fileInput').value='';};
$('download').onclick=()=>{persist();const name=($('filename').value||'year9_helpdesk').replace(/\.py$/i,'').replace(/[^a-zA-Z0-9_-]/g,'_').slice(0,80);const url=URL.createObjectURL(new Blob([editor.value],{type:'text/x-python;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name+'.py';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);};
$('helpButton').onclick=()=>{$('help').hidden=!$('help').hidden;$('helpButton').setAttribute('aria-expanded',String(!$('help').hidden));};window.addEventListener('pagehide',persist);document.addEventListener('visibilitychange',()=>{if(document.hidden)persist();});
show();persist();
