'use strict';
const $=id=>document.getElementById(id),editor=$('editor'),STORE='year9-practical-editor-v1';
const scaffold='MINUTES_PER_PERSON = 4\npeople_ahead = int(input("People ahead: "))\nminutes_available = int(input("Minutes available: "))\n';
const labels={
 en:{subtitle:'Practical checkpoint · read and answer on your paper',intro:'Use your paper for the scenario, sample code, predictions and answers. Type your Python here. Discuss with your partner and swap who uses the editor.',purpose:'WAGBA: Complete, test and improve a helpdesk program.',practiceTab:'Main Task 1 · Explore',createTab:'Main Task 2 · Create',practiceHint:'Paper page 2 · type the sample, run it, then predict and make the changes.',createHint:'Paper pages 3–7 · use the code bank to build, test and improve your adviser.',scaffold:'Load guided scaffold',indent:'Indent →',dedent:'← Dedent',run:'▶ Run',stop:'■ Stop',open:'Open .py',download:'Download .py',clear:'Clear',send:'Send',ready:'Ready. Type your code, then press Run.',running:'Running…',waiting:'Answer the program question below.',done:'Program finished.',stopped:'Stopped. You can edit and run again.',empty:'Type some Python before pressing Run.',saved:'Saved in this browser',failedSave:'Browser saving unavailable — download your code.',error:'Python reported an error. Read the last line and check the stated code line.',footer:'Record results on paper. Download your final program and submit it in Teams.',helpButton:'Editor help',codeTitle:'Code',consoleTitle:'Console',inputLabel:'Program input',fileLabel:'File name',undo:'Undo',redo:'Redo',indentHint:'4 spaces · no code suggestions'},
 zh:{subtitle:'Practical checkpoint · 纸上阅读与作答',intro:'情境、示例代码、预测与答案都在试卷上。在这里输入 Python。与同伴讨论，并轮流操作编辑器。',purpose:'WAGBA: 完成、测试并改进服务台程序。',practiceTab:'Main Task 1 · 运行与修改',createTab:'Main Task 2 · 创建',practiceHint:'试卷第2页：输入示例并运行，再预测和修改。',createHint:'试卷第3–7页：使用代码示例创建、测试和改进程序。',scaffold:'Load guided scaffold · 加载框架',indent:'Indent → 缩进',dedent:'← Dedent 取消缩进',run:'▶ Run 运行',stop:'■ Stop 停止',open:'Open .py 打开',download:'Download .py 下载',clear:'Clear 清空',send:'Send 发送',ready:'准备好后输入 Python，并按 Run。',running:'正在运行…',waiting:'请在下面回答程序的问题。',done:'程序运行结束。',stopped:'已停止。可以修改并再次运行。',empty:'请先输入 Python 代码。',saved:'已保存在此浏览器',failedSave:'无法在浏览器保存，请下载代码。',error:'Python 报错了。阅读最后一行，并检查指出的代码行。',footer:'在试卷上记录结果。下载最终程序，并提交到 Teams。',helpButton:'Editor help 使用说明',codeTitle:'Code 代码',consoleTitle:'Console 控制台',inputLabel:'Program input 程序输入',fileLabel:'File name 文件名',undo:'Undo 撤销',redo:'Redo 重做',indentHint:'4个空格 · 无代码预测'},
 ms:{subtitle:'Practical checkpoint · baca dan jawab pada kertas',intro:'Gunakan kertas untuk situasi, contoh kod, ramalan dan jawapan. Taip Python di sini. Bincang dan bergilir menggunakan editor.',purpose:'WAGBA: Lengkapkan, uji dan tambah baik program meja bantuan.',practiceTab:'Main Task 1 · Teroka',createTab:'Main Task 2 · Cipta',practiceHint:'Kertas halaman 2 · taip contoh, jalankan, kemudian ramal dan ubah.',createHint:'Kertas halaman 3–7 · guna contoh kod untuk membina, menguji dan menambah baik.',scaffold:'Muat rangka kod',indent:'Indent →',dedent:'← Dedent',run:'▶ Run',stop:'■ Stop',open:'Buka .py',download:'Muat turun .py',clear:'Kosongkan',send:'Hantar',ready:'Taip kod, kemudian tekan Run.',running:'Sedang berjalan…',waiting:'Jawab soalan program di bawah.',done:'Program selesai.',stopped:'Dihentikan. Ubah dan jalankan semula.',empty:'Taip Python sebelum menekan Run.',saved:'Disimpan dalam pelayar ini',failedSave:'Simpanan tidak tersedia — muat turun kod.',error:'Python melaporkan ralat. Baca baris terakhir dan semak baris kod yang dinyatakan.',footer:'Catat hasil pada kertas. Muat turun program akhir dan hantar dalam Teams.',helpButton:'Bantuan editor',codeTitle:'Kod',consoleTitle:'Konsol',inputLabel:'Input program',fileLabel:'Nama fail',undo:'Undo',redo:'Redo',indentHint:'4 ruang · tiada cadangan kod'}
};
Object.assign(labels.en,{languageLabel:'Language',helpTitle:'Using the editor',helpRuntime:'This browser runs a local Python 3 subset for this checkpoint. It has no code suggestions or generated answers.',replaceTitle:'Replace this program?',replaceText:'Download your current work first if you want to keep a separate copy. You can also Undo immediately after replacing it.',cancelReplace:'Cancel',confirmReplace:'Replace'});
Object.assign(labels.zh,{languageLabel:'Language 语言',helpTitle:'Using the editor 使用说明',helpRuntime:'此浏览器运行适用于本次任务的 Python 3 子集。没有代码预测或自动生成答案。',replaceTitle:'Replace this program? 替换代码？',replaceText:'如需保留当前代码，请先下载。替换后也可立即按 Undo 撤销。',cancelReplace:'Cancel 取消',confirmReplace:'Replace 替换'});
Object.assign(labels.ms,{languageLabel:'Bahasa',helpTitle:'Menggunakan editor',helpRuntime:'Pelayar ini menjalankan subset Python 3 untuk tugasan ini. Tiada cadangan kod atau jawapan automatik.',replaceTitle:'Gantikan program ini?',replaceText:'Muat turun kod semasa untuk menyimpan salinan lain. Anda juga boleh Undo sejurus selepas menggantikannya.',cancelReplace:'Batal',confirmReplace:'Gantikan'});
// Small build reminders mirror the paper; they do not supply the decision or advice.
Object.assign(labels.en,{scaffold:'Load starter code',createHint:'Paper pages 4-5: build in three steps. Pages 6-7: test and improve.',buildInputTitle:'1 · Inputs',buildInputText:'Load starter code (page 4). Run; enter digits only. This step asks questions but gives no advice yet.',buildTotalTitle:'2 · Total',buildTotalText:'Click the blank line below your inputs. Add the two lines from page 4. Run with 2 and 15.',buildAdviceTitle:'3 · Advice',buildAdviceText:'Choose the comparison and write both messages (page 5). After the first print: Enter → Dedent once → type else: → Enter.',buildReminder:'Keep one program: add each step below your existing code. Do not reload the starter after adding your work.',inputHint:'Core task: type a whole number 0 or more, such as 2. Do not type “2 people”.',footer:'Before the next student or final download: restore MINUTES_PER_PERSON to 4 and run again. Name the file with your class/group; each student submits the .py in Teams.'});
Object.assign(labels.zh,{scaffold:'Load starter code 加载起始代码',createHint:'第4-5页：分三步创建。第6-7页：测试与改进。',buildInputTitle:'1 · Inputs 输入',buildInputText:'加载起始代码（第4页），运行并只输入数字。这一步只提问，暂时没有建议。',buildTotalTitle:'2 · Total 总时间',buildTotalText:'点击输入行下方的空白行，添加第4页的两行代码。输入2和15运行。',buildAdviceTitle:'3 · Advice 建议',buildAdviceText:'选择比较符号并写两条建议（第5页）。第一条 print 后：Enter → Dedent 一次 → 输入 else: → Enter。',buildReminder:'保留同一个程序，在已有代码下添加步骤。添加自己的代码后，不要重新加载起始代码。',inputHint:'基本任务：输入0或以上的整数，例如2，不要输入“2 people”。',footer:'下一位同学开始前和最终下载前：常量恢复为4并运行检查。文件名包含班级和小组姓名；每人将 .py 提交到 Teams。'});
Object.assign(labels.ms,{scaffold:'Muat kod permulaan',createHint:'Halaman 4-5: bina dalam tiga langkah. Halaman 6-7: uji dan tambah baik.',buildInputTitle:'1 · Input',buildInputText:'Muat kod permulaan (halaman 4). Run; taip digit sahaja. Langkah ini bertanya tanpa memberi nasihat lagi.',buildTotalTitle:'2 · Jumlah',buildTotalText:'Klik baris kosong di bawah input. Tambah dua baris dari halaman 4. Run dengan 2 dan 15.',buildAdviceTitle:'3 · Nasihat',buildAdviceText:'Pilih perbandingan dan tulis dua mesej (halaman 5). Selepas print pertama: Enter → Dedent sekali → taip else: → Enter.',buildReminder:'Kekalkan satu program: tambah setiap langkah di bawah kod sedia ada. Jangan muat semula kod permulaan selepas menambah kerja.',inputHint:'Tugasan asas: taip nombor bulat 0 atau lebih, seperti 2. Jangan taip “2 people”.',footer:'Sebelum pelajar seterusnya atau muat turun akhir: pulihkan MINUTES_PER_PERSON kepada 4 dan Run. Nama fail mengandungi kelas/kumpulan; setiap pelajar hantar .py dalam Teams.'});

Object.assign(labels.en,{checkInputs:'Stop and check: I answered both questions, in order.',checkTotal:'Stop and check: 2 people + Sam = 3. Does the total match 3 × 4?',checkAdvice:'Stop and check: page 6 tests show both messages and accept exactly enough time.',submitTitle:'Submission help',submitSave:'1. Select Main Task 2. Restore MINUTES_PER_PERSON to 4 and run again. Use a file name such as 9T_Alex_Lin, then Download .py.',submitOwn:'2. Own device: open the practical submission in Teams, attach the downloaded .py and submit.',submitShared:'2. Shared device: choose one uploader. Submit the team .py with all group names. Each partner confirms with the teacher; you do not need to sign in on your partner’s device.',submitIPad:'iPad: check Files → Downloads, or the folder you chose. In Teams, attach from Files. Ask your teacher if you cannot find the .py.',submitPaper:'3. Everyone hands in their own named booklet. The paper contains your individual answers.',footer:'Before the next student: restore MINUTES_PER_PERSON to 4 and run again. Use Submission help for the final team file.'});
Object.assign(labels.zh,{checkInputs:'停下检查：我已依次回答两个问题。',checkTotal:'停下检查：前面2人加 Sam，共3人。总时间是否等于3 × 4？',checkAdvice:'停下检查：第6页测试显示两条建议，也接受时间刚好足够。',submitTitle:'Submission help 提交帮助',submitSave:'1. 选择 Main Task 2。MINUTES_PER_PERSON 恢复为4并运行。文件名可用 9T_Alex_Lin，然后点 Download .py。',submitOwn:'2. 自己的设备：打开 Teams 实践提交任务，附上下载的 .py 并提交。',submitShared:'2. 共享设备：选一人上传含全部成员姓名的小组 .py。每位同伴向老师确认提交。不必在同伴设备上登录自己的账号。',submitIPad:'iPad：检查 Files → Downloads 或所选文件夹。在 Teams 中从 Files 附上 .py。找不到文件时请问老师。',submitPaper:'3. 每人交写有自己姓名的试卷，保留个人答案。',footer:'下一位同学开始前：MINUTES_PER_PERSON 恢复为4并运行。最终小组文件按 Submission help 提交。'});
Object.assign(labels.ms,{checkInputs:'Berhenti dan semak: saya menjawab kedua-dua soalan mengikut urutan.',checkTotal:'Berhenti dan semak: 2 orang + Sam = 3. Adakah jumlah sama dengan 3 × 4?',checkAdvice:'Berhenti dan semak: ujian halaman 6 menunjukkan dua mesej dan menerima masa yang tepat cukup.',submitTitle:'Bantuan penghantaran',submitSave:'1. Pilih Main Task 2. Pulihkan MINUTES_PER_PERSON kepada 4 dan Run. Gunakan nama seperti 9T_Alex_Lin, kemudian Muat turun .py.',submitOwn:'2. Peranti sendiri: buka tugasan praktikal dalam Teams, lampirkan .py yang dimuat turun dan hantar.',submitShared:'2. Peranti dikongsi: pilih seorang penghantar. Hantar .py pasukan dengan semua nama ahli. Setiap ahli mengesahkan dengan guru; tidak perlu log masuk pada peranti rakan.',submitIPad:'iPad: semak Files → Downloads atau folder pilihan. Lampirkan fail daripada Files dalam Teams. Tanya guru jika .py tidak dijumpai.',submitPaper:'3. Setiap pelajar menyerahkan buku jawapan sendiri yang bernama.',footer:'Sebelum pelajar seterusnya: pulihkan MINUTES_PER_PERSON kepada 4 dan Run. Ikuti Bantuan penghantaran untuk fail akhir.'});

let state={tab:'practice',language:'en',files:{practice:{code:'',name:'year9_practice'},create:{code:'',name:'year9_helpdesk'}}};
try{const x=JSON.parse(localStorage.getItem(STORE));if(x&&['practice','create'].includes(x.tab)&&labels[x.language]&&['practice','create'].every(k=>typeof x.files?.[k]?.code==='string'&&x.files[k].code.length<=20000&&typeof x.files[k].name==='string'))state=x;}catch{}
let worker=null,pendingInput=null,replaceAction=null;let history={practice:[],create:[]},histIndex={practice:-1,create:-1};let saveTimer=null;
const t=k=>labels[state.language][k]||labels.en[k]||k;
function persist(){state.files[state.tab]={code:editor.value,name:$('filename').value};try{localStorage.setItem(STORE,JSON.stringify(state));$('saveState').textContent=t('saved');}catch{$('saveState').textContent=t('failedSave');}}
function escapeHTML(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function paint(){const text=editor.value;const tokens=/(#[^\n]*|"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'|\b(?:if|elif|else|for|while|in|not|and|or|True|False|None|try|except|def|return|import|from|break|continue|pass|class|raise)\b|\b\d+(?:\.\d+)?\b)/g;let html='',last=0;for(const m of text.matchAll(tokens)){html+=escapeHTML(text.slice(last,m.index));const v=m[0],cls=v.startsWith('#')?'comment':/^['"]/.test(v)?'str':/^\d/.test(v)?'num':'kw';html+=`<span class="${cls}">${escapeHTML(v)}</span>`;last=m.index+v.length;}html+=escapeHTML(text.slice(last));$('highlight').innerHTML=html+'\n';$('numbers').textContent=Array.from({length:text.split('\n').length},(_,i)=>i+1).join('\n');syncScroll();position();}
function syncScroll(){$('highlight').scrollTop=editor.scrollTop;$('highlight').scrollLeft=editor.scrollLeft;$('numbers').scrollTop=editor.scrollTop;}
function position(){const before=editor.value.slice(0,editor.selectionStart);$('cursor').textContent=`Line ${before.split('\n').length}, column ${before.length-before.lastIndexOf('\n')}`;}
function snapshot(){return {text:editor.value,start:editor.selectionStart,end:editor.selectionEnd};}
function remember(){const tab=state.tab,h=history[tab],s=snapshot();if(h[histIndex[tab]]?.text===s.text)return;h.splice(histIndex[tab]+1);h.push(s);if(h.length>150)h.shift();histIndex[tab]=h.length-1;}
function change(result){editor.value=result.text;editor.setSelectionRange(result.start,result.end);remember();paint();persist();}
function undo(delta){const k=state.tab,i=histIndex[k]+delta;if(i<0||i>=history[k].length)return;histIndex[k]=i;const s=history[k][i];editor.value=s.text;editor.setSelectionRange(s.start,s.end);paint();persist();}
function stop(message=true){worker?.terminate();worker=null;pendingInput=null;$('inputForm').hidden=true;$('run').disabled=false;$('stop').disabled=true;if(message)$('runState').textContent=t('stopped');}
function language(){document.documentElement.lang=state.language;for(const id of Object.keys(labels.en))if($(id)&&!['runState'].includes(id))$(id).textContent=t(id);$('language').value=state.language;$('taskHint').textContent=t(state.tab==='practice'?'practiceHint':'createHint');$('runState').textContent=t(worker?(pendingInput?'waiting':'running'):'ready');$('helpSteps').innerHTML=state.language==='zh'?'<li>选择 Main Task 1 或 Main Task 2；两者分别保存代码。</li><li>按 Run。在控制台回答 input()，按 Enter 或 Send。</li><li>冒号后按 Enter 增加4个空格。第一条 print 后先按 Enter，再按 Dedent 一次，然后输入 else: 并按 Enter。不要输入试卷行号。</li><li>Download .py 下载当前程序；Open .py 打开已保存文件。</li><li>关闭或更换设备前，请下载代码。</li>':state.language==='ms'?'<li>Pilih Main Task 1 atau Main Task 2; kod disimpan berasingan.</li><li>Tekan Run. Jawab input() dalam konsol, kemudian Enter atau Hantar.</li><li>Enter selepas titik bertindih menambah empat ruang. Selepas print pertama, tekan Enter, kemudian Dedent sekali, taip else: dan Enter. Jangan taip nombor baris kertas.</li><li>Muat turun .py menyimpan fail; Buka .py mengimport fail.</li><li>Muat turun kod sebelum menutup atau menukar peranti.</li>': '<li>Choose Main Task 1 or Main Task 2. Each has its own saved code.</li><li>Press Run. When input() asks a question, answer in the console and press Enter or Send.</li><li>After a colon, Enter adds four spaces. After the first print, press Enter, then Dedent once. Type else: and press Enter. Do not type the paper’s line numbers.</li><li>Download .py saves the selected program. Open .py imports a saved file.</li><li>Download your code before closing or changing devices.</li>';}
function switchTab(tab){if(tab===state.tab)return;persist();stop(false);state.tab=tab;show();persist();}
function show(){editor.value=state.files[state.tab].code;$('filename').value=state.files[state.tab].name;for(const k of ['practice','create'])$(k+'Tab').setAttribute('aria-selected',String(k===state.tab));$('workpanel').setAttribute('aria-labelledby',state.tab+'Tab');$('scaffold').hidden=state.tab!=='create';$('buildGuide').hidden=state.tab!=='create';$('submissionGuide').hidden=state.tab!=='create';$('console').textContent='';language();remember();paint();}
function append(text){$('console').textContent+=text;$('console').scrollTop=$('console').scrollHeight;}
function run(){persist();if(!editor.value.trim()){$('runState').textContent=t('empty');return;}stop(false);$('console').textContent='';$('runState').textContent=t('running');$('run').disabled=true;$('stop').disabled=false;worker=createPythonWorker();const active=worker;active.onmessage=({data:d})=>{if(worker!==active)return;if(d.type==='output')append(d.text);else if(d.type==='input'){pendingInput=d.id;append(d.prompt);$('inputForm').hidden=false;$('inputLabel').textContent=d.prompt||t('inputLabel');$('answer').value='';$('runState').textContent=t('waiting');$('answer').focus({preventScroll:true});$('inputForm').scrollIntoView({block:'nearest',behavior:'smooth'});}else if(d.type==='done'||d.type==='error'){if(d.error)append('\n'+d.error+'\n');stop(false);$('runState').textContent=t(d.error?'error':'done');}};active.onerror=()=>{if(worker!==active)return;append('\nPython could not start. Keep the complete app folder together, or ask your teacher to reload the editor.\n');stop(false);$('runState').textContent=t('error');};active.postMessage({type:'run',code:editor.value});}
function requestReplace(action){replaceAction=action;if(!editor.value.trim()){action();return;}$('replaceDialog').showModal();}
editor.addEventListener('input',()=>{remember();paint();clearTimeout(saveTimer);saveTimer=setTimeout(persist,200);});
editor.addEventListener('keydown',e=>{if(e.isComposing)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo(e.shiftKey?1:-1);return;}if(e.key==='F5'){e.preventDefault();run();return;}if(e.key==='Enter'&&!e.ctrlKey&&!e.metaKey){e.preventDefault();change(EditorCore.newline(editor.value,editor.selectionStart,editor.selectionEnd));}else if(e.key==='Tab'){e.preventDefault();change(EditorCore.indent(editor.value,editor.selectionStart,editor.selectionEnd,e.shiftKey));}else if(e.key==='Backspace'){const r=EditorCore.backspace(editor.value,editor.selectionStart,editor.selectionEnd);if(r){e.preventDefault();change(r);}}});
// Touch keyboards often deliver beforeinput without a usable keydown.
editor.addEventListener('beforeinput',e=>{if(e.isComposing)return;if(e.inputType==='insertLineBreak'||e.inputType==='insertParagraph'){e.preventDefault();change(EditorCore.newline(editor.value,editor.selectionStart,editor.selectionEnd));}});
editor.addEventListener('scroll',syncScroll);editor.addEventListener('click',position);editor.addEventListener('keyup',position);editor.addEventListener('blur',persist);
for(const [id,dedent] of [['indent',false],['dedent',true]]){$(id).addEventListener('pointerdown',e=>e.preventDefault());$(id).onclick=()=>{change(EditorCore.indent(editor.value,editor.selectionStart,editor.selectionEnd,dedent));editor.focus({preventScroll:true});};}
$('undo').onclick=()=>undo(-1);$('redo').onclick=()=>undo(1);$('run').onclick=run;$('stop').onclick=()=>stop();$('practiceTab').onclick=()=>switchTab('practice');$('createTab').onclick=()=>switchTab('create');$('language').onchange=()=>{state.language=$('language').value;language();persist();};$('filename').oninput=persist;
$('inputForm').onsubmit=e=>{e.preventDefault();if(!worker||pendingInput===null)return;const value=$('answer').value;append(value+'\n');worker.postMessage({type:'input',id:pendingInput,value});pendingInput=null;$('inputForm').hidden=true;$('runState').textContent=t('running');};
$('clear').onclick=()=>{if(!worker){$('console').textContent='';$('runState').textContent=t('ready');}};$('scaffold').onclick=()=>requestReplace(()=>{stop(false);change({text:scaffold,start:scaffold.length,end:scaffold.length});editor.focus({preventScroll:true});});
$('cancelReplace').onclick=()=>{$('replaceDialog').close();replaceAction=null;};$('confirmReplace').onclick=()=>{$('replaceDialog').close();const action=replaceAction;replaceAction=null;action?.();};
$('open').onclick=()=>$('fileInput').click();$('fileInput').onchange=async()=>{const f=$('fileInput').files[0];if(!f)return;if(!/\.py$/i.test(f.name)||f.size>80000){$('runState').textContent='Choose a .py file smaller than 80 KB.';$('fileInput').value='';return;}const code=await f.text();if(code.length>20000){$('runState').textContent='This file is too long for the checkpoint editor.';return;}requestReplace(()=>{stop(false);$('filename').value=f.name.replace(/\.py$/i,'');change({text:code,start:0,end:0});});$('fileInput').value='';};
$('download').onclick=()=>{persist();const name=($('filename').value||'year9_helpdesk').replace(/\.py$/i,'').replace(/[^a-zA-Z0-9_-]/g,'_').slice(0,80);const url=URL.createObjectURL(new Blob([editor.value],{type:'text/x-python;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name+'.py';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);};
$('helpButton').onclick=()=>{$('help').hidden=!$('help').hidden;$('helpButton').setAttribute('aria-expanded',String(!$('help').hidden));};window.addEventListener('pagehide',persist);document.addEventListener('visibilitychange',()=>{if(document.hidden)persist();});
show();persist();
