'use strict';
(() => {
const L=window.LESSON,$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const PREFIX=L.id, LAST=PREFIX+'-last';let state=null,key='',teacher=false,editor=null,engine=null,cleanupGame=null,saveTimer=null,currentRun=null,composition=false;
const blank=(name,cls,language,crew)=>({schema:1,lessonId:L.id,student:{name,className:cls},language,crew,current:0,furthest:0,records:{},evidence:[],created:new Date().toISOString(),saved:null,teamsSubmitted:false});
const storageKey=(name,cls,isTeacher)=>PREFIX+(isTeacher?'-teacher':'-student-'+encodeURIComponent((name.trim()+'|'+cls.trim()).toLowerCase()));
const record=c=>state.records[c.id]??=( {answers:{},history:[],runs:[],tests:[],done:false,attempted:false} );
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;setTimeout(()=>$('#toast').hidden=true,4500);}
function save(immediate=false){
 $('#save-state').textContent='Saving…';clearTimeout(saveTimer);
 const persist=()=>{try{state.saved=new Date().toISOString();localStorage.setItem(key,JSON.stringify(state));if(!teacher)localStorage.setItem(LAST,key);$('#save-state').textContent='Saved locally · '+new Date(state.saved).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});}catch(e){$('#save-state').textContent='Save failed · make a backup';}};
 immediate?persist():saveTimer=setTimeout(persist,250);
}
function attempt(c,submitted=true){const r=record(c);r.attempted=true;r.updated=new Date().toISOString();if(submitted){r.history.push({at:r.updated,answers:structuredClone(r.answers)});r.done=true;}save();progress();}
function answer(c,field,value){const r=record(c);r.answers[field]=value;r.attempted=true;r.updated=new Date().toISOString();save();}
function support(c){const lang=state.language;if(lang==='en')return '';const v=L.support[lang];return `<aside class="support-box" aria-label="${esc(v.label)}"><b>${esc(v.label)}</b><p>${esc(c[lang]||v.general)}</p><p>${esc(v.frame)}</p><small>${esc(v.words)}</small></aside>`;}
function cardHeader(c){const title=L.stages.find(x=>x[0]===c.stage)?.[1]||'Crew Lounge';return `<div class="card-heading"><div><span class="tag">${esc(title.toUpperCase())}</span><h2 id="card-title">${esc(c.title)}</h2></div><img class="crew" src="assets/crew.svg" alt="Crew engineer" width="64" height="76"></div><p class="body-copy">${esc(c.body||'')}</p>${support(c)}`;}
function feedbackHtml(ok,text){return `<div class="feedback ${ok?'good':''}" role="status"><b>${ok?'Good thinking':'Try an improvement'}</b><p>${esc(text)}</p><small>Your attempt is saved. You can revise it; you are not locked here.</small></div>`;}
function setFeedback(c,ok,text){record(c).feedback={ok,text};$('#feedback').innerHTML=feedbackHtml(ok,text);attempt(c);}
function fieldsBind(c){const r=record(c);$('#card').querySelectorAll('[data-field]').forEach(el=>{const f=el.dataset.field;if(el.type==='checkbox')el.checked=!!r.answers[f];else if(r.answers[f]!==undefined)el.value=r.answers[f];el.addEventListener(el.type==='checkbox'||el.tagName==='SELECT'?'change':'input',()=>answer(c,f,el.type==='checkbox'?el.checked:el.value));});}
function quiz(c){const r=record(c);return `${c.code?`<pre><code>${esc(c.code)}</code></pre>`:''}<fieldset class="answers"><legend>${esc(c.question||'Choose your prediction, then check it.')}</legend>${c.options.map((o,i)=>`<label class="answer"><input type="radio" name="quiz" value="${i}" ${String(r.answers.choice)===String(i)?'checked':''}> ${esc(o)}</label>`).join('')}</fieldset><button id="check" type="button" class="primary">Check prediction</button><div id="feedback">${r.feedback?feedbackHtml(r.feedback.ok,r.feedback.text):''}</div>`;}
function progress(){
 const core=L.cards.filter(c=>c.core!==false&&!['review','lounge','break'].includes(c.stage));const done=core.filter(c=>state.records[c.id]?.done).length;
 $('#progress-count').textContent=`${done}/${core.length}`;$('#progress').value=100*done/core.length;
 $('#journey').innerHTML=L.stages.map(([id,title],i)=>{const cards=L.cards.filter(c=>c.stage===id),first=L.cards.indexOf(cards[0]),count=cards.filter(c=>state.records[c.id]?.done).length;const locked=!teacher&&first>state.furthest;return `<button type="button" class="journey-button ${L.cards[state.current].stage===id?'current':''}" data-stage="${id}" ${locked?'disabled':''} ${L.cards[state.current].stage===id?'aria-current="step"':''}><span class="stage-dot">${count===cards.length?'✓':i+1}</span>${esc(title)}<span class="stage-detail">${id==='extension'?'If time':`${count}/${cards.length}`}</span></button>`;}).join('');
 $('#journey').querySelectorAll('button').forEach(b=>b.onclick=()=>move(L.cards.findIndex(c=>c.stage===b.dataset.stage)));
}
function permitNext(c){if(teacher||c.core===false||['break','review','lounge'].includes(c.stage))return true;return !!record(c).done;}
function move(index){
 if(index<0||index>=L.cards.length)return;if(L.cards[index].stage==='lounge'&&!state.teamsSubmitted&&!teacher)return;
 if(engine&&$('#stop')&&!$('#stop').disabled){toast('Select Stop before changing cards. Your code will be kept.');return;}
 if(!teacher&&index>state.furthest){toast('Finish or submit an attempt on the current card first.');return;}
 engine?.stop(false);engine=null;editor?.toTextArea();editor=null;cleanupGame?.();cleanupGame=null;
 state.current=index;save();render();$('#card').focus({preventScroll:true});if(innerWidth<761)$('#card').scrollIntoView({block:'start',behavior:'instant'});else window.scrollTo({top:0,behavior:'instant'});
}
function continueCard(){const c=L.cards[state.current];if(!permitNext(c)){$('#nav-message').textContent=c.type==='code'?'Run or test your code once. An error is an attempt too—use its feedback to improve.':'Make and submit an attempt on this card. Short answers are fine.';return;}state.furthest=Math.max(state.furthest,state.current+1);move(state.current+1);}
function startSession(name,cls,lang,crew){
 teacher=new URLSearchParams(location.search).get('teacher')==='1'||name.trim().toLowerCase()==='teacher';if(teacher){name='Test Student';cls=cls||'8T';}
 key=storageKey(name,cls,teacher);let previous;try{previous=JSON.parse(localStorage.getItem(key)||'null');}catch{}
 state=previous?.lessonId===L.id?previous:blank(name,cls,lang,crew);state.language=lang;state.crew=crew;
 $('#landing').hidden=true;$('#lesson').hidden=false;document.body.className='crew-'+state.crew;$('#student').textContent=state.student.name+' · '+state.student.className;$('#support').value=state.language;$('#wagba').textContent=L.wagba;save(true);render();window.scrollTo(0,0);
}
function render(){
 const c=L.cards[state.current],r=record(c);let body='';$('#nav-message').textContent='';
 $('#stage-title').textContent=L.stages.find(s=>s[0]===c.stage)?.[1]||'Crew Lounge';const group=L.cards.filter(x=>x.stage===c.stage);$('#card-position').textContent=`Card ${group.indexOf(c)+1} of ${group.length}`;
 if(c.type==='read')body=`${c.visual?`<div class="split"><div>${c.html||''}</div><div class="scene"><img src="assets/ship.svg" alt="Spacecraft launch panel showing the countdown 3, 2, 1"><div class="display">CREW READY</div></div></div>`:c.html||''}${c.code?`<pre><code>${esc(c.code)}</code></pre>`:''}<label class="checkline"><input type="checkbox" id="read-done" ${r.done?'checked':''}> I have read this card and know what to try next.</label>`;
 if(c.type==='quiz')body=quiz(c);
 if(c.type==='readiness')body=c.html+'<button id="ready-submit" class="primary" type="button">Save my starting point</button><div id="feedback"></div>';
 if(c.type==='trace')body=`<pre><code>${esc(c.code)}</code></pre><div class="fields mini-trace">${c.fields.map(([f,label])=>`<label>${esc(label)}<input type="text" inputmode="numeric" data-field="${f}" aria-label="${esc(label)}"></label>`).join('')}</div>${quiz({...c,code:null})}`;
 if(c.type==='code')body=codeHtml(c,r);
 if(c.type==='break')body=`<div id="game-host"></div><p class="small">Your own best only—no class ranking or assessment marks. This break does not affect lesson progress.</p>`;
 if(c.type==='pit')body=pitHtml(c,r);
 if(c.type==='plenary')body=`<div class="fields"><label>1. How is while different from if?<textarea data-field="difference" placeholder="if chooses… while repeats…"></textarea></label><label>2. What changes so your console loop can stop?<textarea data-field="stop" placeholder="The value of ___ changes. The condition becomes False when ___."></textarea></label><label>3. Without the update, what happens here?<pre>seconds = 3\nwhile seconds &gt; 0:\n    print(seconds)</pre><select data-field="missing"><option value="">Choose…</option><option>It repeatedly displays 3 until interrupted.</option><option>It counts down and stops.</option><option>It displays nothing.</option></select></label></div><button id="exit-submit" type="button" class="primary">Save my debrief</button><div id="feedback"></div>`;
 if(c.type==='review')body=reviewHtml()+`<div class="action-row"><button id="export-final" class="primary big" type="button">Export mission PDF</button><button id="review-print" type="button">Print / Save as PDF</button></div><p class="note">Upload your completed PDF to the Microsoft Teams Assignment named <b>Week 7 Theory</b>. If your teacher uses another week/module title, follow that title.</p><div class="evidence" id="evidence-area" tabindex="0"><h3>Screenshot evidence, if useful</h3><p class="small">Code and tests are already included. You may attach a screenshot by choosing a file or pasting an image here (Ctrl/⌘+V). Avoid faces and other students’ personal details.</p><label>Choose image<input id="evidence-file" type="file" accept="image/png,image/jpeg,image/webp"></label><div id="evidence-preview"></div></div>`;
 if(c.type==='lounge')body='<div class="action-row"><button data-game="reactor" type="button">Reactor Overdrive</button><button data-game="memory" type="button">Remember the Signal</button><button data-game="wires" type="button">Connect the Wires</button></div><div id="game-host"></div><button id="return-review" type="button" class="text-button">Return to my report</button>';
 $('#card').classList.toggle('coding-card',c.type==='code');
 $('#card').innerHTML=cardHeader(c)+body+(c.stage==='extension'?'<div class="action-row"><button id="to-plenary" type="button">Go to Plenary →</button><small>If you have time, keep challenging yourself. You can return later.</small></div>':'');
 fieldsBind(c);$('#back').disabled=state.current===0;$('#next').hidden=['review','lounge'].includes(c.stage);$('#next').textContent=c.stage==='break'?'Return to mission →':'Next card →';progress();
 if(c.type==='read')$('#read-done').onchange=e=>{r.done=e.target.checked;r.answers.read=e.target.checked;r.attempted=true;r.updated=new Date().toISOString();save();progress();};
 if(c.type==='quiz'||c.type==='trace'){
  $('#card').querySelectorAll('input[name=quiz]').forEach(el=>el.onchange=()=>answer(c,'choice',Number(el.value)));
  $('#check').onclick=()=>{if(r.answers.choice===undefined){toast('Choose a prediction first.');return;}if(c.type==='trace'&&c.fields.some(([f])=>!String(r.answers[f]||'').trim())){toast('Enter your three predicted values first.');return;}const good=Number(r.answers.choice)===c.correct&&(c.type!=='trace'||c.fields.every(([f],i)=>String(r.answers[f]).trim()===String(3-i)));setFeedback(c,good,c.feedback);};
 }
 if(c.type==='readiness')$('#ready-submit').onclick=()=>{if(['readyK','readyS','readyU'].some(f=>!r.answers[f])){toast('Choose a starting point for each area.');return;}attempt(c);$('#feedback').innerHTML=feedbackHtml(true,'Your starting point is saved. Use the worked example and reference snippets where you need them.');};
 if(c.type==='code')bindEditor(c,r);
 if(c.type==='break'){game('reactor');r.done=true;save();}
 if(c.type==='pit')$('#pit-submit').onclick=()=>{if(!r.answers.phase){toast('Choose the learning experience that best fits you.');return;}attempt(c);$('#feedback').innerHTML=feedbackHtml(true,'Your reflection is saved. Choose the challenge ladder if you feel ready, or return to your console for another test.');};
 if(c.type==='plenary')$('#exit-submit').onclick=()=>{if(!String(r.answers.difference||'').trim()||!String(r.answers.stop||'').trim()||!r.answers.missing){toast('Give a short response to each question. Keywords or your home language are fine.');return;}attempt(c);$('#feedback').innerHTML=feedbackHtml(r.answers.missing.startsWith('It repeatedly'),'The update is missing, so seconds stays at 3 and the condition stays True. Your explanations are saved for teacher review, not automatically graded.');};
 if(c.stage==='extension')$('#to-plenary').onclick=()=>{const i=L.cards.findIndex(x=>x.stage==='plenary');state.furthest=Math.max(state.furthest,i);move(i);};
 if(c.type==='review'){ $('#export-final').onclick=exportPDF;$('#review-print').onclick=printReport;$('#evidence-file').onchange=e=>uploadEvidence(e.target.files[0]);$('#evidence-area').onpaste=e=>{const f=[...e.clipboardData.items].find(x=>x.type.startsWith('image/'))?.getAsFile();if(f){e.preventDefault();uploadEvidence(f);}};showEvidence(); }
 if(c.type==='lounge'){game('reactor');$('#card').querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>game(b.dataset.game));$('#return-review').onclick=()=>move(L.cards.findIndex(x=>x.stage==='review'));}
}
function pitHtml(){return `<div class="ability"><section><h3>Knowledge</h3><label><input type="checkbox" data-field="pitK"> I can identify the loop condition.</label></section><section><h3>Skills</h3><label><input type="checkbox" data-field="pitS"> My program repeats, counts and stops.</label></section><section><h3>Understanding</h3><label><input type="checkbox" data-field="pitU"> I can explain why the condition becomes False.</label></section></div><p id="pit-count" class="small">Use these checks as evidence, not as a grade.</p><fieldset class="phase-grid"><legend>How does the learning feel?</legend>${[['New learning','Something new; I am making progress.'],['Consolidating','I am becoming more secure.'],['Treading water','This is too easy to stretch me.'],['Drowning / need help','I cannot progress without support.']].map(([label,text])=>`<label><input type="radio" name="phase" value="${esc(label)}"> <span><b>${esc(label)}</b><br>${esc(text)}</span></label>`).join('')}</fieldset><div class="fields"><label>One piece of evidence or one thing you need help with<textarea data-field="evidence" placeholder="My third-entry test… / I repaired… / I need help with…"></textarea></label></div><button id="pit-submit" class="primary" type="button">Save my pit stop</button><div id="feedback"></div>`;}
function codeHtml(c,r){return `<div class="success-chips" aria-label="Success criteria">${c.success.map(x=>`<span>☑ ${esc(x)}</span>`).join('')}</div>
<div class="editor-wrap"><div class="editor-top"><b>mission.py</b><span>Python lab · <span id="python-version">ready to load</span></span></div>
<div class="editor-actions"><button class="run" id="run" type="button"><span class="icon" aria-hidden="true">🚀</span>Run</button><button class="stop" id="stop" type="button" disabled><span class="icon" aria-hidden="true">■</span>Stop</button><button class="test" id="test-code" type="button"><span class="icon" aria-hidden="true">☑</span>Test</button><button id="save-code" type="button">Save .py</button><button id="expand" type="button">Expand</button><button id="editor-tools-toggle" type="button" aria-expanded="false">Editor tools</button></div>
<div class="editor-panels"><section class="editor-panel"><div class="panel-label">PYTHON EDITOR — WRITE YOUR CODE HERE</div><textarea id="code" aria-label="Python code editor"></textarea></section><section class="console-panel"><div class="panel-label">PYTHON SHELL — OUTPUT AND INPUT HERE</div><div id="console" class="console" aria-label="Python console" role="log" aria-live="off"></div><form id="shell-form" class="shell-entry"><span aria-hidden="true">&gt;&gt;&gt;</span><textarea id="shell-command" aria-label="Interactive Python command" placeholder="After running: inspect a variable" rows="1"></textarea><button type="submit">Enter</button></form></section></div>
<div class="editor-bottom"><span id="python-status" role="status">Run your code. Enter answers after its shell prompt.</span><span id="cursor-position">Ln 1, Col 0</span></div>
<div id="editor-tools" class="editor-help" hidden><div class="action-row"><button id="undo" type="button">Undo</button><button id="redo" type="button">Redo</button><button id="indent" type="button">Indent</button><button id="dedent" type="button">Unindent</button><button id="comment" type="button">Comment / uncomment</button><button id="complete" type="button">Complete word</button><button id="syntax-check" type="button">Check syntax</button><button id="trace-replay" type="button">Replay last trace</button><button id="restart" type="button">Restart shell</button><button id="clear-console" type="button">Clear display</button><button id="restore" type="button">Restore starter</button><label class="small">Open .py file<input id="open-py" type="file" accept=".py,text/plain"></label><button id="font-minus" type="button" aria-label="Decrease code font size">A−</button><button id="font-plus" type="button" aria-label="Increase code font size">A+</button></div><label class="small">Find<input id="find-text" type="text"></label><label class="small">Replace with<input id="replace-text" type="text"></label><button id="find" type="button">Find next</button><button id="replace" type="button">Replace selection</button><p class="small">Tab: four spaces · Shift+Tab: unindent · Ctrl/⌘+Enter: Run · F5: Run · Escape: leave editor / close expanded view. Shell Enter executes; Shift+Enter adds a line.</p><div id="completions"></div></div></div>
<div class="character-tip"><img class="crew" src="assets/crew.svg" alt=""><span id="byte-tip">Run → enter in the shell → Test. An error is an attempt, not a locked door.</span><div id="test-feedback">${testSummary(c,r)}</div></div>
<div id="trace-host"></div><div class="code-extras"><details><summary>Reference and a small hint</summary>${c.reference?`<pre>${esc(c.reference)}</pre>`:''}<p class="hint">${esc(c.hint)}</p></details><details><summary>Add a brief stopping-rule explanation</summary><label class="fields">Short phrases are fine; not auto-marked.<textarea data-field="explanation" placeholder="${esc(c.explain)}"></textarea></label></details></div>`;}
function testSummary(c,r){if(!r.tests?.length)return '';const t=r.tests.at(-1),passed=t.results.filter(x=>x.pass).length,all=passed===c.tests.length&&t.results.length===c.tests.length;return `<button type="button" data-tests="${esc(c.id)}" class="test-summary ${all&&t.code===r.code?'passed':''}">${t.code===r.code?'':'Earlier: '}${passed}/${c.tests.length} tests passed · View</button>`;}
function testHtml(r){if(!r.tests?.length)return '';const latest=r.tests.at(-1);return `<div class="feedback"><b>${latest.code===r.code?'Test results':'Earlier test results — code has changed'}</b>${latest.results.map(x=>`<div class="test-result"><h3>${x.pass?'✓ Passed':'↻ Improve'}: ${esc(x.name)}</h3><p>${esc(x.pass?'Expected behaviour matched.':x.error||'Compare the expected output with your result.')}</p><pre>Expected:\n${esc(x.expect)}\nActual:\n${esc(x.output||'(no printed output)')}</pre></div>`).join('')}</div><p class="small">Tests check these cases, not every possible program. A stopped test may leave remaining cases untested.</p>`;}
function bindEditor(c,r){
 if(r.code===undefined)r.code=c.starter||state.records[c.inherit]?.code||L.consoleStarter;
 editor=CodeMirror.fromTextArea($('#code'),{value:r.code,mode:'python',lineNumbers:true,indentUnit:4,tabSize:4,indentWithTabs:false,matchBrackets:true,autoCloseBrackets:true,styleActiveLine:true,viewportMargin:10,extraKeys:{Tab:cm=>cm.somethingSelected()?cm.indentSelection('add'):cm.replaceSelection('    '),'Shift-Tab':cm=>cm.indentSelection('subtract'),'Ctrl-Enter':()=>runCode(),'Cmd-Enter':()=>runCode(),F5:()=>runCode(),Esc:()=>{if($('.editor-wrap').classList.contains('expanded'))toggleExpand();else $('#run').focus();},'Ctrl-Space':()=>completion()}});editor.setValue(r.code);
 editor.on('change',()=>{r.code=editor.getValue();r.attempted=true;r.updated=new Date().toISOString();$('#test-feedback').innerHTML=testSummary(c,r);save();});
 editor.on('cursorActivity',()=>{const pos=editor.getCursor();$('#cursor-position').textContent=`Ln ${pos.line+1}, Col ${pos.ch}`;const line=editor.getLine(pos.line).slice(0,pos.ch);if(/\binput\([^)]*$/.test(line))$('#byte-tip').textContent='input(prompt) asks in the shell and returns text.';else if(/\bprint\([^)]*$/.test(line))$('#byte-tip').textContent='print(value, ...) displays values in the shell.';});
 engine=new PythonEngine({ready:v=>$('#python-version')&&($('#python-version').textContent=v),output:(s,error)=>appendConsole(s,error?'error':''),input:askInput,stopped:msg=>{removeInput();appendConsole('\n'+msg+'\n','system');}});
 appendConsole('Python shell. Select Run to start your program.\n','system');
 $('#run').onclick=()=>runCode();$('#stop').onclick=()=>engine.stop();$('#test-code').onclick=()=>testCode();$('#save-code').onclick=()=>download(new Blob([editor.getValue()],{type:'text/x-python'}),filename(c.id,'py'));$('#expand').onclick=toggleExpand;
 $('#editor-tools-toggle').onclick=()=>{const tools=$('#editor-tools');tools.hidden=!tools.hidden;$('#editor-tools-toggle').setAttribute('aria-expanded',String(!tools.hidden));};
 $('#undo').onclick=()=>editor.undo();$('#redo').onclick=()=>editor.redo();$('#indent').onclick=()=>editor.indentSelection('add');$('#dedent').onclick=()=>editor.indentSelection('subtract');$('#comment').onclick=()=>{const a=editor.getCursor('from').line,b=editor.getCursor('to').line;editor.operation(()=>{for(let i=a;i<=b;i++){const line=editor.getLine(i),m=line.match(/^(\s*)# ?(.*)$/);editor.replaceRange(m?m[1]+m[2]:'# '+line,{line:i,ch:0},{line:i,ch:line.length});}});};
 $('#complete').onclick=completion;$('#syntax-check').onclick=()=>runCode({check:true});$('#trace-replay').onclick=()=>traceReplay(r);
 $('#restart').onclick=()=>{engine.stop();$('#python-version').textContent='ready to reload';$('#python-status').textContent='Shell restarted; variables cleared. Your code is kept.';};$('#clear-console').onclick=()=>{$('#console').replaceChildren();};
 $('#restore').onclick=()=>{if(confirm('Replace your current code with the starter? You can Undo afterwards.'))editor.setValue(c.starter||state.records[c.inherit]?.code||L.consoleStarter);};
 $('#open-py').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.size>100000){toast('Choose a Python file below 100 KB.');return;}if(confirm('Replace the editor code with this file?'))editor.setValue(await f.text());};
 let font=15;const resize=n=>{font=Math.max(13,Math.min(24,font+n));editor.getWrapperElement().style.fontSize=font+'px';editor.refresh();};$('#font-minus').onclick=()=>resize(-1);$('#font-plus').onclick=()=>resize(1);
 $('#find').onclick=()=>{const query=$('#find-text').value;if(!query)return;const source=editor.getValue(),from=editor.indexFromPos(editor.getCursor('to'));let i=source.indexOf(query,from);if(i<0)i=source.indexOf(query);if(i<0){toast('Text not found.');return;}editor.setSelection(editor.posFromIndex(i),editor.posFromIndex(i+query.length));editor.focus();};$('#replace').onclick=()=>{if(editor.getSelection()===$('#find-text').value&&$('#find-text').value)editor.replaceSelection($('#replace-text').value);else toast('Find and select the matching text first.');};
 $('#shell-form').onsubmit=e=>{e.preventDefault();runShell();};$('#shell-command').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();runShell();}};
 fieldsBind(c);
 if(c.type==='pit')bindPit(c,r);
}
function completion(){const pos=editor.getCursor(),line=editor.getLine(pos.line).slice(0,pos.ch),prefix=line.match(/[A-Za-z_]\w*$/)?.[0]||'';const words=[...new Set(['while','if','else','elif','break','print','input','True','False','and','or','int',...editor.getValue().match(/[A-Za-z_]\w*/g)||[]])].filter(w=>w.startsWith(prefix)&&w!==prefix).slice(0,16);const host=$('#completions');host.innerHTML='<p class="small">Choose a name or keyword:</p>'+words.map(w=>`<button type="button" data-word="${esc(w)}">${esc(w)}</button>`).join('');host.querySelectorAll('button').forEach(b=>b.onclick=()=>{editor.replaceRange(b.dataset.word,{line:pos.line,ch:pos.ch-prefix.length},pos);host.replaceChildren();editor.focus();});if(!words.length)host.textContent='No matching completion.';$('#editor-tools').hidden=false;}
function toggleExpand(){const wrap=$('.editor-wrap');wrap.classList.toggle('expanded');$('#expand').textContent=wrap.classList.contains('expanded')?'Close expanded view':'Expand';editor.refresh();}
function appendConsole(text,cls=''){const node=document.createElement('span');node.className=cls;node.textContent=text;$('#console')?.append(node);if(currentRun)currentRun.transcript+=text;const box=$('#console');if(box)box.scrollTop=box.scrollHeight;}
function removeInput(){document.querySelector('.inline-input')?.remove();}
function askInput(prompt){appendConsole(prompt);const form=document.createElement('form');form.className='inline-input';const input=document.createElement('input');input.type='text';input.autocomplete='off';input.setAttribute('aria-label',prompt||'Program input');const submit=document.createElement('button');submit.type='submit';submit.textContent='Enter';form.append(input,submit);$('#console').append(form);input.oncompositionstart=()=>composition=true;input.oncompositionend=()=>composition=false;form.onsubmit=e=>{e.preventDefault();if(composition)return;const value=input.value;form.remove();appendConsole(value+'\n','user-input');currentRun?.inputs.push({prompt,value,at:new Date().toISOString()});save();$('#python-status').textContent='Running…';engine.sendInput(value);};$('#python-status').textContent='Waiting for input — type after the prompt, then Enter.';$('#byte-tip').textContent='Type your entry in the shell, not in the code editor.';input.focus();input.scrollIntoView({block:'nearest'});}
function busy(value){['run','test-code','syntax-check','restart','restore','open-py'].forEach(id=>{const el=$('#'+id);if(el)el.disabled=value;});$('#stop').disabled=!value;$('#shell-command').disabled=value;}
async function runCode(options={}){
 if(!engine||engine.pending)return;const c=L.cards[state.current],r=record(c),code=editor.getValue();busy(true);$('#python-status').textContent='Loading / running Python…';editor.eachLine(h=>editor.removeLineClass(h,'background','error-line'));removeInput();$('#console').replaceChildren();appendConsole(`=== RESTART: mission.py ===\n`,'system');currentRun={at:new Date().toISOString(),code,inputs:[],transcript:'',kind:options.check?'syntax check':'run'};
 try{const result=await engine.execute(code,{fresh:true,tracing:!options.check,check:!!options.check});removeInput();if(!result.ok){appendConsole('\n'+result.error+'\n','error');if(result.line)editor.addLineClass(result.line-1,'background','error-line');$('#byte-tip').textContent='Read the error and inspect its line. Change one thing, then run again.';}else if(options.check){appendConsole('Syntax check passed. Behaviour still needs testing.\n','system');}else{appendConsole('\nProgram finished.\n','system');$('#byte-tip').textContent='Run complete. Test whether the result matches the mission.';}
  currentRun.result={...result,trace:undefined};r.runs.push(currentRun);r.lastTrace=result.trace||[];r.lastValues=result.values||{};if(!options.check){attempt(c);r.codeRun=code;}$('#python-status').textContent=result.ok?(options.check?'Syntax is valid.':'Finished. Use >>> to inspect a variable.'):'Run ended — inspect the feedback.';
 }catch(error){appendConsole(String(error.message)+'\n','error');currentRun.result={ok:false,error:error.message};r.runs.push(currentRun);attempt(c);$('#python-status').textContent='Python unavailable — see console instructions.';}
 finally{currentRun=null;busy(false);save();}
}
async function runShell(){if(engine?.pending)return;const command=$('#shell-command').value;if(!command.trim())return;$('#shell-command').value='';busy(true);appendConsole('>>> '+command+'\n','user-input');const c=L.cards[state.current],r=record(c);currentRun={at:new Date().toISOString(),code:command,inputs:[],transcript:'',kind:'shell'};try{const result=await engine.execute(command,{fresh:false,shell:true});if(!result.ok)appendConsole(result.error+'\n','error');currentRun.result=result;r.runs.push(currentRun);save();}catch(e){appendConsole(e.message+'\n','error');}finally{currentRun=null;removeInput();busy(false);}}
async function testCode(){
 if(engine?.pending)return;const c=L.cards[state.current],r=record(c),code=editor.getValue();busy(true);currentRun=null;$('#python-status').textContent='Testing cases separately…';const results=[];
 try{for(const t of c.tests){const result=await engine.execute(code,{inputs:t.inputs,silent:true,fresh:true,override:t.override||{}});const normal=s=>String(s||'').replace(/\r/g,'').trimEnd();const loopProblem=c.requireWhile&&!result.hasWhile?'Use a while loop; printed answers alone do not demonstrate repetition.':c.minWhile&&result.whileCount<c.minWhile?'Use a second while loop for the countdown, not copied print lines.':'';const pass=result.ok&&normal(result.output)===normal(t.expect)&&!loopProblem;results.push({...t,pass,output:result.output||'',error:result.error||loopProblem});if(result.stopped)break;}
  r.tests.push({at:new Date().toISOString(),code,results});r.code=code;attempt(c);$('#test-feedback').innerHTML=testSummary(c,r);$('#byte-tip').textContent=results.length===c.tests.length&&results.every(x=>x.pass)?'Required cases matched. Explain your stopping rule.':'Inspect the failed case, change one thing and test again. You can continue.';$('#python-status').textContent='Tests finished. Run starts a fresh interactive session.';
 }catch(error){toast(error.message);}
 finally{busy(false);save();}
}
function traceReplay(r){const trace=r.lastTrace||[];if(!trace.length){toast('Run your program first to record a trace.');return;}let i=0;const host=$('#trace-host');host.innerHTML='<section class="trace-controls"><h3>Replay the actual recorded trace</h3><p class="small">Snapshots show variables <b>before</b> each executed line. This is a replay, not a live debugger. Up to 400 steps are recorded.</p><div class="action-row"><button id="trace-prev" type="button">Previous step</button><button id="trace-next" type="button">Next step</button><span id="trace-position"></span></div><pre id="trace-values"></pre></section>';const show=()=>{editor.eachLine(h=>editor.removeLineClass(h,'background','trace-line'));editor.addLineClass(trace[i].line-1,'background','trace-line');$('#trace-position').textContent=`Before line ${trace[i].line} · step ${i+1}/${trace.length}`;$('#trace-values').textContent=Object.entries(trace[i].values).map(([k,v])=>k+' = '+v).join('\n')||'(No student variables yet)';$('#trace-prev').disabled=i===0;$('#trace-next').disabled=i===trace.length-1;};$('#trace-prev').onclick=()=>{i--;show();};$('#trace-next').onclick=()=>{i++;show();};show();}
function bindPit(c,r){$('#card').querySelectorAll('input[name=phase]').forEach(el=>{el.checked=r.answers.phase===el.value;el.onchange=()=>answer(c,'phase',el.value);});}
function reviewHtml(){return L.stages.filter(([id])=>!['review','break'].includes(id)).map(([stage,title])=>{const cards=L.cards.filter(c=>c.stage===stage&&(c.core!==false||state.records[c.id]?.attempted));if(!cards.length)return '';return `<section class="review-section"><h3>${esc(title)}</h3>${cards.map(c=>{const r=state.records[c.id];return `<div class="review-item"><b>${esc(c.title)} <span class="badge">${r?.done?'Attempt submitted':r?.attempted?'In progress':'Not completed'}</span></b>${r?Object.entries(r.answers||{}).map(([k,v])=>`<p>${esc(fieldLabel(k))}: ${esc(k==='choice'?c.options?.[Number(v)]??v:typeof v==='boolean'?(v?'Yes':'No'):v)}</p>`).join(''):''}${r?.feedback?`<p>${esc(r.feedback.text)}</p>`:''}${r?.history?.length>1?`<details><summary>${r.history.length} submitted attempts / improvements</summary>${r.history.map(h=>`<p>${esc(new Date(h.at).toLocaleTimeString())}: ${esc(Object.entries(h.answers).map(([k,v])=>fieldLabel(k)+': '+(k==='choice'?c.options?.[Number(v)]??v:v)).join(' · '))}</p>`).join('')}</details>`:''}${r?.code&&r.attempted?`<details><summary>Code and results</summary><pre>${esc(r.code)}</pre>${testHtml(r)}</details>`:''}<button type="button" class="text-button" data-return="${c.id}">Return to this card</button></div>`;}).join('')}</section>`;}).join('');}
function fieldLabel(k){return ({read:'Read acknowledgement',choice:'Selected answer',first:'First number',second:'Second number',third:'Third number',readyK:'Knowledge starting point',readyS:'Skills starting point',readyU:'Understanding starting point',pitK:'Knowledge check',pitS:'Skills check',pitU:'Understanding check',phase:'Learning experience',evidence:'Reflection evidence',explanation:'Stopping-rule explanation',difference:'while compared with if',stop:'What makes my loop stop',missing:'Missing-update prediction'})[k]||k;}
function filename(part,ext){const clean=s=>String(s).normalize('NFKC').replace(/[^\p{L}\p{N}_-]+/gu,'_').slice(0,75);return `Year8_${clean(state.student.className)}_${clean(state.student.name)}_Week7_Theory_${clean(part)}.${ext}`;}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
async function exportPDF(){save(true);toast('Preparing your report…');try{const images=await allEvidence();const blob=await MissionReport.pdf(state,L,images);download(blob,filename('Mission_Loop','pdf'));state.lastExport=new Date().toISOString();save();showGuide(false);}catch(e){toast('Direct PDF export failed. Use Print report / Save as PDF. '+e.message);}}
async function printReport(){const images=await allEvidence();$('#print-report').innerHTML=MissionReport.html(state,L,images);window.print();showGuide(true);}
function showGuide(print){
 const ios=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);const mobile=ios||/Android/.test(navigator.userAgent);
 $('#device-guide').innerHTML=mobile?`<p>${print?'In the print preview, save a PDF.':'Your browser may download the PDF or open a preview.'}</p><ol><li>On iPad/iPhone, look for <b>Downloads ↓</b> near the Safari address bar, or open the PDF preview.</li><li>Choose <b>Share</b> → <b>Save to Files</b>, then select a folder you can find again. On Android, check your browser’s Downloads.</li><li>Open <b>Files</b> and confirm the PDF is there before opening Teams.</li></ol><p class="small">Button positions vary by browser and iOS version. This is a labelled guide, not a screenshot of your device.</p>`:`<div class="download-arrow"><p><b>Look near the top-right of your browser.</b><br>Select the Downloads ↓ icon, or open your Downloads folder. Browser layouts may differ.</p><span aria-hidden="true">↗</span></div><p>${print?'In your print dialog choose Save as PDF, then save the file.':'Open the downloaded PDF and check the report.'}</p>`;
 $('#teams-confirm').checked=false;$('#submitted').disabled=true;$('#guide').showModal();
}
let dbPromise;
function evidenceDB(){return dbPromise??=new Promise((resolve,reject)=>{const req=indexedDB.open(PREFIX+'-evidence',1);req.onupgradeneeded=()=>req.result.createObjectStore('images',{keyPath:'id'});req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
async function dbAction(mode,action){const db=await evidenceDB();return new Promise((resolve,reject)=>{const tx=db.transaction('images',mode),store=tx.objectStore('images'),request=action(store);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function allEvidence(){const images=[];for(const meta of state.evidence){const data=await dbAction('readonly',s=>s.get(meta.id));if(data)images.push({...meta,data:data.data});}return images;}
async function uploadEvidence(file){if(!file)return;if(!/^image\/(png|jpeg|webp)$/.test(file.type)||file.size>12e6){toast('Choose a PNG, JPEG or WebP below 12 MB.');return;}if(state.evidence.length>=3){toast('Keep up to three evidence images. Remove one before adding another.');return;}try{const url=URL.createObjectURL(file),img=new Image();img.src=url;await img.decode();const ratio=Math.min(1,1600/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*ratio);canvas.height=Math.round(img.height*ratio);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);URL.revokeObjectURL(url);const id=key+'-'+crypto.randomUUID();await dbAction('readwrite',s=>s.put({id,data:canvas.toDataURL('image/jpeg',.87)}));state.evidence.push({id,name:file.name||'Pasted screenshot',caption:'',at:new Date().toISOString()});save();showEvidence();toast('Image saved in this browser. Include it in your backup.');}catch(e){toast('Image could not be saved: '+e.message);}}
async function showEvidence(){const host=$('#evidence-preview');if(!host)return;const images=await allEvidence();host.innerHTML=images.map(x=>`<div><img src="${x.data}" alt="${esc(x.caption||x.name)}"><label>Caption<input data-caption="${esc(x.id)}" value="${esc(x.caption)}"></label><button type="button" data-delete="${esc(x.id)}">Remove image</button></div>`).join('');host.querySelectorAll('[data-caption]').forEach(el=>el.oninput=()=>{state.evidence.find(x=>x.id===el.dataset.caption).caption=el.value;save();});host.querySelectorAll('[data-delete]').forEach(el=>el.onclick=async()=>{if(!confirm('Remove this evidence image?'))return;await dbAction('readwrite',s=>s.delete(el.dataset.delete));state.evidence=state.evidence.filter(x=>x.id!==el.dataset.delete);save();showEvidence();});}
async function backup(){try{save(true);const data={...state,images:await allEvidence()};download(new Blob([JSON.stringify(data)],{type:'application/json'}),filename('Backup','json'));toast('Backup downloaded. Keep it with your school files.');}catch(e){toast('Backup failed: '+e.message);}}
async function importBackup(file){if(!file)return;try{if(engine&&$('#stop')&&!$('#stop').disabled)throw Error('Select Stop before importing a backup.');if(file.size>20e6)throw Error('Backup is too large (maximum 20 MB).');const b=JSON.parse(await file.text());if(b.lessonId!==L.id||b.schema!==1||typeof b.student?.name!=='string'||!b.student.name.trim()||typeof b.student?.className!=='string'||!b.student.className.trim()||!b.records||typeof b.records!=='object'||Array.isArray(b.records)||!Number.isInteger(b.current)||b.current<0||b.current>=L.cards.length)throw Error('This is not a valid Mission Loop backup.');for(const [id,r] of Object.entries(b.records)){if(!L.cards.some(c=>c.id===id)||!r||typeof r.answers!=='object'||Array.isArray(r.answers)||!Array.isArray(r.history)||!Array.isArray(r.runs)||!Array.isArray(r.tests))throw Error('The backup contains invalid lesson records.');}if(!Array.isArray(b.images||[])||(b.images||[]).length>3||(b.images||[]).some(x=>!/^data:image\/(jpeg|png|webp);base64,/.test(x.data||'')))throw Error('Invalid image evidence in backup.');if(!confirm('Restore this backup and replace the active saved lesson?'))return;engine?.stop(false);editor?.toTextArea();editor=null;engine=null;cleanupGame?.();teacher=new URLSearchParams(location.search).get('teacher')==='1';key=storageKey(b.student.name,b.student.className,teacher);const metas=[];for(const x of b.images||[]){const id=key+'-'+crypto.randomUUID();await dbAction('readwrite',s=>s.put({id,data:x.data}));metas.push({id,name:String(x.name||'Evidence'),caption:String(x.caption||''),at:x.at});}delete b.images;b.evidence=metas;b.language=['en','zh','ko'].includes(b.language)?b.language:'en';b.crew=['teal','coral','purple'].includes(b.crew)?b.crew:'teal';b.furthest=Math.min(L.cards.length-1,Math.max(b.current,Number(b.furthest)||0));state=b;$('#landing').hidden=true;$('#lesson').hidden=false;$('#student').textContent=b.student.name+' · '+b.student.className;$('#support').value=b.language;$('#wagba').textContent=L.wagba;document.body.className='crew-'+b.crew;save(true);render();toast('Progress and evidence restored.');}catch(e){toast('Import failed: '+e.message);}}
$('#entry').onsubmit=e=>{e.preventDefault();const name=$('#fullName').value.trim(),cls=$('#className').value.trim();if(!name){$('#entry-error').textContent='Enter your full name.';$('#fullName').focus();return;}if(!cls&&name.toLowerCase()!=='teacher'){ $('#entry-error').textContent='Enter your class.';$('#className').focus();return;}startSession(name,cls,$('#language').value,$('input[name=crew]:checked').value);};
$('#next').onclick=continueCard;$('#back').onclick=()=>move(state.current-1);$('#support').onchange=e=>{state.language=e.target.value;save();move(state.current);};$('#export-top').onclick=exportPDF;$('#backup').onclick=backup;$('#import').onclick=()=>$('#import-file').click();$('#landing-import').onclick=()=>$('#import-file').click();$('#import-file').onchange=e=>{importBackup(e.target.files[0]);e.target.value='';};$('#print').onclick=printReport;
$('#reset').onclick=async()=>{if(engine&&$('#stop')&&!$('#stop').disabled){toast('Select Stop before resetting your work.');return;}if(!confirm('Reset this student’s saved Mission Loop work and evidence? Download a backup first if you need to keep it.'))return;clearTimeout(saveTimer);engine?.stop(false);for(const m of state.evidence)try{await dbAction('readwrite',s=>s.delete(m.id));}catch{}const activeKey=key;state=null;localStorage.removeItem(activeKey);if(!teacher)localStorage.removeItem(LAST);location.href=location.pathname+(teacher?'?teacher=1':'');};
$('#guide [data-close]').onclick=()=>$('#guide').close();$('#teams-confirm').onchange=e=>$('#submitted').disabled=!e.target.checked;$('#submitted').onclick=()=>{if(!$('#teams-confirm').checked)return;state.teamsSubmitted=true;state.teamsSubmittedAt=new Date().toISOString();const i=L.cards.findIndex(c=>c.stage==='lounge');state.furthest=i;save();$('#guide').close();move(i);};
$('#test-close').onclick=()=>$('#test-dialog').close();
$('#card').addEventListener('click',e=>{const id=e.target.closest('[data-return]')?.dataset.return;if(id)move(L.cards.findIndex(c=>c.id===id));const test=e.target.closest('[data-tests]')?.dataset.tests;if(test){$('#test-dialog-body').innerHTML=testHtml(state.records[test]);$('#test-dialog').showModal();}});
const observer=new MutationObserver(()=>{const c=state&&L.cards[state.current];if(c?.type==='pit')bindPit(c,record(c));});observer.observe($('#card'),{childList:true});
window.addEventListener('beforeunload',()=>{if(state)save(true);});
document.addEventListener('error',e=>{if(e.target instanceof HTMLImageElement&&!e.target.dataset.fallback){const img=e.target;img.dataset.fallback='true';const note=document.createElement('span');note.className='small';note.textContent=img.alt?img.alt+' (image unavailable)':'Visual unavailable';img.replaceWith(note);}},true);
document.querySelectorAll('img').forEach(img=>{if(img.complete&&!img.naturalWidth)img.dispatchEvent(new Event('error'));});
try{const last=JSON.parse(localStorage.getItem(localStorage.getItem(LAST)||'')||'null');if(last?.student){$('#resume').hidden=false;$('#resume').innerHTML=`<b>Saved work found:</b> ${esc(last.student.name)} · ${esc(last.student.className)}<br><button id="resume-button" type="button">Resume my work</button><small>Different student? Enter your own details below.</small>`;$('#resume-button').onclick=()=>startSession(last.student.name,last.student.className,last.language,last.crew);}}catch{}
if(new URLSearchParams(location.search).get('teacher')==='1')startSession('teacher','8T','en','teal');
// Games are local, ungraded and do not set learning completion.
function game(kind){
 cleanupGame?.();const host=$('#game-host');let active=true;cleanupGame=()=>active=false;
 if(kind==='reactor'){
  cleanupGame=window.ReactorGame.mount(host,{
   best:state.gameStats?.reactorBest,
   language:state.language,
   onBest:best=>{state.gameStats??={};state.gameStats.reactorBest=best;save();},
   onReturn:()=>L.cards[state.current].stage==='break'?continueCard():move(L.cards.findIndex(c=>c.stage==='review'))
  });
 }
 if(kind==='memory'){const symbols=['★','☾','◆','☀'];const seq=Array.from({length:3},()=>Math.floor(Math.random()*4));let index=0,playing=false;host.innerHTML=`<div class="game"><h3>Remember the Signal</h3><p>Study these three symbols: <b id="pattern">${seq.map(x=>symbols[x]).join(' · ')}</b></p><button id="memory-start" type="button">I'm ready — hide the pattern</button><div class="memory-grid">${symbols.map((s,i)=>`<button type="button" data-symbol="${i}" aria-label="${['Star','Moon','Diamond','Sun'][i]}" disabled>${s}</button>`).join('')}</div><p id="game-status" class="game-status" role="status">No timer. Take your time.</p><button id="game-reset" type="button">New pattern</button></div>`;$('#memory-start').onclick=()=>{$('#pattern').textContent='? · ? · ?';playing=true;host.querySelectorAll('[data-symbol]').forEach(b=>b.disabled=false);$('#memory-start').disabled=true;};host.querySelectorAll('[data-symbol]').forEach(b=>b.onclick=()=>{if(!playing)return;if(Number(b.dataset.symbol)!==seq[index]){$('#game-status').textContent='Try again. The pattern is shown for another look.';$('#pattern').textContent=seq.map(x=>symbols[x]).join(' · ');index=0;playing=false;$('#memory-start').disabled=false;host.querySelectorAll('[data-symbol]').forEach(x=>x.disabled=true);return;}index++;$('#game-status').textContent=index===3?'Signal restored! Nice sequence.':`${index} / 3 correct`;if(index===3){playing=false;host.querySelectorAll('[data-symbol]').forEach(x=>x.disabled=true);}});$('#game-reset').onclick=()=>game(kind);}
 if(kind==='wires'){const left=['★ Star','◆ Diamond','☾ Moon','☀ Sun'],right=[...left].sort(()=>Math.random()-.5);let selected=null,matched=0;host.innerHTML=`<div class="game"><h3>Connect the Wires</h3><p>Tap a left connector, then its matching right connector. Match symbols, not just colour.</p><div class="wire-grid">${left.map((s,i)=>`<button type="button" data-side="left" data-value="${esc(s)}">${esc(s)}</button><button type="button" data-side="right" data-value="${esc(right[i])}">${esc(right[i])}</button>`).join('')}</div><p id="game-status" class="game-status" role="status">0 / 4 connections</p><button id="game-reset" type="button">Reconnect</button></div>`;host.querySelectorAll('[data-side]').forEach(b=>b.onclick=()=>{if(b.dataset.side==='left'){host.querySelectorAll('.selected').forEach(x=>x.classList.remove('selected'));selected=b;b.classList.add('selected');return;}if(!selected){$('#game-status').textContent='Choose a left connector first.';return;}if(b.dataset.value===selected.dataset.value){b.disabled=true;selected.disabled=true;b.classList.add('matched');selected.classList.add('matched');selected.classList.remove('selected');selected=null;matched++;$('#game-status').textContent=matched===4?'All wires connected. Systems online!':`${matched} / 4 connections`;}else $('#game-status').textContent='Different symbols. Choose the matching connector.';});$('#game-reset').onclick=()=>game(kind);}
}
window.MissionApp={get state(){return state;},get editor(){return editor;},get engine(){return engine;},move,exportPDF,printReport,fieldLabel};
})();
