const STEPS=[
{n:1,p:9,c:0,title:'Give the controller a home',kit:'Top chassis plate · 4 × M3 10 mm PCB stands',do:'Find the four mounting holes shown in the picture. Insert one 10 mm stand into each hole. Compare the whole plate with the diagram before tightening.',check:'All four stands are in the matching holes, on the same side of the plate.'},
{n:2,p:9,c:1,title:'Secure the four stands',kit:'4 × M3 nuts · cross wrench',do:'Turn the plate over while holding the stands. Fit a nut to each stand. Use the cross wrench to make them snug, not forced.',check:'Each stand is secured underneath and does not wobble.'},
{n:3,p:9,c:2,title:'Mount REKA:BIT',kit:'REKA:BIT board · 4 × M3 6 mm bolts · Phillips screwdriver',do:'Match the board orientation to the photo. Rest it on the four stands, align the holes, then fit the four bolts. Tighten gently in turn.',check:'The board is supported by all four stands, with no bending.',note:'Your chassis labels may look different from the booklet. Use the hole pattern and board orientation, not just the printed labels.'},
{n:4,p:10,c:0,title:'Add the ultrasonic bracket',kit:'Ultrasonic bracket · 2 × M3 6 mm bolts · 2 × M3 nuts',do:'Place the bracket at the front of the top plate as shown. Secure both fixing holes with the bolts and nuts.',check:'The bracket faces forwards and stays still when touched gently.'},
{n:5,p:10,c:1,title:'Seat the micro:bit',kit:'micro:bit · assembled REKA:BIT board',do:'Keep all power disconnected. Hold the micro:bit by its edges. Match its orientation to the picture and slide its edge connector evenly into the slot.',check:'The micro:bit sits straight and is fully seated.',note:'Do not push at an angle. Stop and ask your teacher if it does not slide into the connector.'},
{n:6,p:10,c:2,title:'Fit the “eyes”',kit:'Ultrasonic sensor · fitted bracket',do:'Place the ultrasonic sensor in the bracket as shown, with its two round transducers facing forwards. Keep the connecting pins clear.',check:'The sensor is secure, faces forwards and is not bent.'},
{n:7,p:11,c:3,title:'Prepare the battery base',kit:'Lower chassis plate · 4 hook-side Velcro dots',do:'Find the battery-holder position on the lower plate. Use the first two pictures to place the four hook-side Velcro dots.',check:'The dots match the battery-holder position and do not cover fixing holes.'},
{n:8,p:11,c:2,title:'Match the battery holder',kit:'Battery holder · 4 loop-side Velcro dots',do:'Place the matching loop-side dots on the back of the battery holder. Line them up with the dots on the chassis.',check:'The two sets of dots line up. The battery holder is still disconnected.'},
{n:9,p:12,c:0,title:'Prepare both motors',kit:'2 DC motors · 2 motor brackets · supplied motor bolts · screwdriver',do:'Place each motor in its bracket. Fit the supplied motor bolts as shown. Check which way the shafts will face before tightening.',check:'Both motors are secured in their brackets, with shafts facing outwards when mounted.'},
{n:10,p:12,c:1,title:'Position the motors',kit:'Lower chassis plate · both motor assemblies',do:'Match the motor brackets to the slots in the chassis. Put one motor on each side, following the photo.',check:'The two wheel shafts point out from opposite sides of the chassis.'},
{n:11,p:12,c:2,title:'Secure the motors',kit:'4 × M3 6 mm bolts · screwdriver',do:'Use two bolts for each motor bracket. Tighten each pair gradually while keeping the motor aligned.',check:'Neither motor rocks and both wheel shafts remain clear.'},
{n:12,p:13,c:0,title:'Prepare the line-sensor supports',kit:'2 × M3 5 mm stands · 2 × M3 nuts · cross wrench',do:'Turn the lower plate over. Use the picture to find the two line-sensor mounting holes. Fit the stands and secure them with nuts.',check:'Both short stands are in the pictured holes on the underside.'},
{n:13,p:13,c:1,title:'Position Maker Line',kit:'Maker Line sensor board',do:'Place the line-sensor board on its stands. Match the orientation and fixing holes to the diagram. Its sensing side must face the floor when the robot is upright.',check:'The sensor is aligned and will face the floor, not the inside of the robot.'},
{n:14,p:13,c:2,title:'Secure the line sensor',kit:'2 × M3 4 mm bolts specified by assembly step 14 · screwdriver',do:'Ask your teacher to check the supplied fixings, then secure the board to the stands gently.',check:'The board is supported without bending, and its fixings have been checked.',note:'Booklet mismatch: step 14 says 4 mm bolts, but the parts list does not list them. Do not force a longer bolt or improvise a substitute. Ask your teacher to check the actual set.'},
{n:15,p:14,c:0,title:'Position the castor',kit:'Castor wheel assembly',do:'Find the castor mounting holes. Place the castor on the same underside as the line sensor, as shown.',check:'The castor is under the chassis and its mounting holes align.'},
{n:16,p:14,c:1,title:'Secure the castor',kit:'2 × M3 10 mm bolts · 2 × M3 nuts',do:'Fit both bolts and nuts. Hold the castor in position while tightening gently.',check:'The mount is secure and the castor still turns freely.'},
{n:17,p:14,c:2,title:'Make the gripper supports',kit:'2 × M3 20 mm stands · 2 × M3 nuts',do:'Fit the two 20 mm stands at the front of the chassis. Match the holes and upright position to the picture.',check:'The two front stands are the same height and firmly secured.'},
{n:18,p:15,c:0,title:'Add the four pillars',kit:'4 × M3 40 mm stands · 4 × M3 nuts',do:'Fit one tall stand in each of the four corner positions shown. Secure each from underneath with a nut.',check:'All four tall stands are vertical and in the correct holes.'},
{n:19,p:15,c:1,title:'Pause for a chassis check',kit:'Your lower chassis · a partner’s careful eyes',do:'Compare your chassis with the picture. Trace the motor positions, castor, line sensor and six upright stands. Gently check the fixings.',check:'I can point to every pictured part; nothing rocks or catches.'},
{n:20,p:15,c:2,title:'Place the battery holder',kit:'Battery holder · 4 AA batteries when your teacher permits',do:'Match the Velcro dots and attach the holder. Keep its power lead unplugged and the switch OFF. Your teacher will check battery polarity before power is used.',check:'The holder is secure, with no trapped wires, and remains disconnected.',note:'Classroom checkpoint: the booklet inserts batteries here. You may leave batteries out until the final teacher check; do not power the robot while building.'},
{n:21,p:16,c:0,title:'Fit the servo horn',kit:'Servo · servo horn · supplied M2 fixing bolt',do:'With the servo unpowered, fit the horn using its supplied fixing bolt as shown. Ask your teacher if the horn position is unclear.',check:'The horn is fitted securely without forcing the servo shaft.',note:'Never twist the servo gears by force. A teacher may need to calibrate and reposition the horn later using booklet page 49.'},
{n:22,p:16,c:0,title:'Mount the servo',kit:'Gripper Part 1 · servo · supplied M2 bolts and nuts',do:'Match the servo orientation in the picture. Fix it to Part 1 using the supplied M2 bolts and nuts.',check:'The servo sits squarely on Part 1 and its cable is not trapped.'},
{n:23,p:16,c:4,title:'Attach the two jaw gears',kit:'2 × Part 5 · 2 × M3 6 mm bolts · 2 thick spacers · 2 locknuts',do:'For each jaw, fit a bolt, thick spacer and locknut to Part 1 as shown. Match the two gear teeth so the jaws work together. Do not clamp the joints solid.',check:'The jaw gears mesh and their joints are not overtightened. I have not forced the servo.'},
{n:24,p:17,c:0,title:'Raise the jaw supports',kit:'4 × M3 5 mm stands · 4 × M3 nuts, as specified in step 24',do:'Attach the four short stands to the Part 5 pieces in the positions shown. Secure them with nuts.',check:'All four supports match the diagram and have secure fixings.',note:'The booklet parts list and assembly quantities for 5 mm stands differ. If your set is short, stop and show your teacher—do not borrow from another student’s set or substitute a size.'},
{n:25,p:17,c:4,title:'Build the gripper linkage',kit:'Left Part 4 · Part 3 · M3 10 mm bolt · thin spacer · locknut',do:'Connect Part 3 to the left Part 4 using the bolt, thin spacer and locknut. Follow the close-up to keep the parts in the correct order.',check:'The linkage is connected in the pictured order and its joint is not clamped tight.'},
{n:26,p:18,c:0,title:'Add the upper jaw pieces',kit:'Part 4 pieces · 4 × M3 6 mm bolts',do:'Align the Part 4 pieces with the four supports on Part 5. Fit the four bolts carefully.',check:'The upper pieces align with the lower jaws and all four supports are secured.'},
{n:27,p:18,c:4,title:'Link the arm to the horn',kit:'Part 3 linkage · M3 6 mm bolt · fitted servo horn',do:'Follow the close-up. Connect the linkage to the first or second hole from the end of the servo horn. The booklet recommends the first for better grip.',check:'The linkage is attached at the pictured end of the horn, with no forced movement.'},
{n:28,p:19,c:0,title:'Mount the gripper',kit:'Assembled gripper · 2 × M3 6 mm bolts',do:'Place the gripper on the two front 20 mm stands. Align the mounting holes and secure both bolts.',check:'The gripper faces forwards and is supported by both stands.'},
{n:29,p:19,c:1,title:'Join the two decks',kit:'Top plate assembly · lower chassis · 4 × M3 6 mm bolts',do:'Lower the top plate onto the four 40 mm stands. Keep all cables away from the joints. Fit one bolt at each corner.',check:'All four corners are secured, the decks are parallel and no wire is pinched.'},
{n:30,p:19,c:2,title:'Fit the wheels',kit:'2 wheels · assembled chassis',do:'Align each wheel hub with its motor shaft. Support the motor and press the wheel straight on. Do not bend the shaft.',check:'Both wheels are seated and clear of the chassis. If a wheel will not fit, I ask for help.'},
{n:31,p:20,c:5,title:'Connect the motor wires',kit:'Motor leads · small screwdriver · REKA:BIT motor terminals',do:'With power disconnected, connect Motor 1: black → M1A, red → M1B. Connect Motor 2: red → M2A, black → M2B. Match the photo to identify the motors.',check:'Terminals grip bare wire, not insulation. No loose strands touch another terminal.',note:'Trace each wire from its motor to its terminal. Do not swap colours just because the two motors look symmetrical.'},
{n:32,p:21,c:0,title:'Find the power socket—keep it off',kit:'Battery power plug · REKA:BIT power socket',do:'Locate the correct power socket shown in the picture. For our classroom build, leave the plug disconnected until every connection has been checked by your teacher.',check:'I can identify the power socket. The battery is OFF and still disconnected.',note:'Classroom adaptation: the booklet connects power at step 32. We delay connection until after steps 33–36 and the final teacher inspection.'},
{n:33,p:21,c:4,title:'Connect the gripper servo',kit:'Servo cable · REKA:BIT S1 port',do:'Connect the gripper servo to S1. Match orange → S, red → +, brown → −. Check the labels before pushing the connector on.',check:'The connector uses S1, and signal, positive and negative each match the correct pin.'},
{n:34,p:22,c:0,title:'Route the sensor cables',kit:'Sensor cables · assembled chassis',do:'Use the openings in the plate to route the cables as shown. Leave enough slack for the gripper without loops near the wheels.',check:'No cable is pinched, pulled tight or able to catch in a wheel or gear.'},
{n:35,p:22,c:4,title:'Connect the ultrasonic sensor',kit:'Ultrasonic cable · REKA:BIT P2:P12 port',do:'Connect to P2:P12. Match red → Vcc, yellow → Trigger, white → Echo, black → GND. Check the table in the full-page picture.',check:'Both ends match the table. The connector is straight and no pin is exposed by an offset plug.'},
{n:36,p:23,c:5,title:'Connect Maker Line',kit:'Maker Line cable · REKA:BIT P1:P9 port',do:'Connect to P1:P9. Match red → Vcc, yellow → AN, white → CAL, black → GND. Identify your micro:bit version before connecting the white wire.',check:'The wiring matches my micro:bit version and I am ready for a teacher inspection.',note:'micro:bit V1: leave the WHITE cable unconnected. micro:bit V2: follow the full diagram. If you cannot identify the version, stop and ask your teacher.'}
];

const MODULES=[
 {id:'gripper',title:'Gripper',range:[21,27],page:18,crop:0,prompt:'Servo, two jaw gears, four supports and a linkage.',prereq:'You can build this on its own. Attach it only when the two front 20 mm chassis supports are ready.'},
 {id:'chassis',title:'Lower chassis',range:[7,20],page:15,crop:0,prompt:'Battery base, motors, castor, line sensor and upright stands.',prereq:'Work on the lower plate. Keep the battery disconnected.'},
 {id:'deck',title:'Top deck',range:[1,6],page:10,crop:2,prompt:'Controller, micro:bit and ultrasonic “eyes”.',prereq:'Disconnect USB and battery power before seating the micro:bit.'},
 {id:'join',title:'Join the assemblies',range:[28,30],page:19,crop:0,prompt:'Attach the gripper, top deck and wheels.',prereq:'First inspect the gripper, chassis and top deck. Joining needs two front 20 mm stands and four 40 mm corner stands.'},
 {id:'wiring',title:'Wiring',range:[31,36],page:21,crop:4,prompt:'Trace each lead and match the port labels.',prereq:'Only after the mechanical build is secure. Battery OFF and unplugged; USB disconnected. Ask for a teacher inspection before any power.'}
];
const GROUPS=[
 {id:'g1',module:'gripper',range:[21,23],title:'Servo and lower jaw gears',page:16,crop:4,checks:['Point to Part 1, the servo and both Part 5 jaws. Their orientation matches the picture; the cable is not trapped.','Inspect both jaw pivots from the side. Spacers are present and joints are not clamped solid. Do not force movement through the servo.','Compare the gear teeth: both gears mesh and the jaws line up evenly.'],evidence:['I compared both jaw pivots from the side.','I checked cable and servo orientation.','I checked the gear teeth mesh.']},
 {id:'g2',module:'gripper',range:[24,25],title:'Supports and linkage',page:17,crop:4,checks:['Point to all four short supports. Holes and matching lengths agree with the picture and teacher-confirmed set.','Point to Part 3 and the left Part 4. Their orientation matches the guide.','Inspect the linkage pivot from the side: the correct spacer is present and its locknut does not clamp the moving joint solid.'],evidence:['I counted and compared all four supports.','I checked the linkage pivot spacer.','I matched the left jaw and linkage orientation.']},
 {id:'g3',module:'gripper',range:[26,27],title:'Upper jaws and horn connection',page:18,crop:4,checks:['Point to all four bolts holding the upper pieces on their supports. Upper and lower jaw pieces align.','Trace Part 3 to the servo horn. It is attached near the end as pictured, using the teacher-confirmed fixing.','No cable is trapped or part catching. No joint or servo was forced. Powered opening and closing must wait for the teacher.'],evidence:['I checked all four upper jaw fixings.','I traced the linkage to the horn.','I checked no cable is trapped.']},
 {id:'c1',module:'chassis',range:[7,11],title:'Battery base and motors',page:12,crop:2,checks:['Velcro on the holder and base lines up without covering fixing holes.','Both motors are fixed in their brackets and to the chassis; neither mount rocks.','Both shafts face outward on opposite sides. Wires are clear of the shafts.'],evidence:['I checked both motor mounts.','I compared shaft directions.','I checked the battery-holder position.']},
 {id:'c2',module:'chassis',range:[12,16],title:'Line sensor and castor',page:13,crop:2,checks:['Point to both short line-sensor supports underneath. They match the guide; the board sits flat.','The sensing side will face the floor. Teacher-confirmed bolts secure it without bending the board.','The castor mount has both bolts and nuts, is secure, and its ball turns freely.'],evidence:['I checked which sensor side faces the floor.','I checked the castor moves freely.','I inspected the board for bending.']},
 {id:'c3',module:'chassis',range:[17,20],title:'Pillars and battery holder',page:15,crop:0,checks:['Count two front 20 mm supports and four 40 mm corner stands. They are secure and in the pictured holes.','The battery holder sits securely on Velcro. No cable is trapped below it.','Battery OFF and power plug out. Motors, line sensor and castor remain firmly mounted.'],evidence:['I counted and measured the six stands.','I inspected under the battery holder.','I traced the disconnected power lead.']},
 {id:'d1',module:'deck',range:[1,3],title:'Controller mounting',page:9,crop:2,checks:['Count four 10 mm stands in the correct top-plate holes, each secured underneath.','REKA:BIT orientation matches the photo; all four fixing holes align.','The board is flat, does not rock and has not been bent by tightening.'],evidence:['I compared board orientation.','I counted four mounting supports.','I checked the board sits flat.']},
 {id:'d2',module:'deck',range:[4,6],title:'Micro:bit and ultrasonic bracket',page:10,crop:2,checks:['The front ultrasonic bracket is secure with two bolts and nuts.','The micro:bit sits straight and fully in its connector. Battery and USB disconnected.','The ultrasonic sensor faces forwards with two round “eyes”. Pins are clear and not bent.'],evidence:['I checked connector alignment.','I checked both bracket fixings.','I compared sensor orientation.']},
 {id:'j1',module:'join',range:[28,30],title:'Joined body and wheels',page:19,crop:5,checks:['The gripper is secured to both front 20 mm supports, facing forwards.','All four top-plate corners sit on 40 mm stands. Decks are parallel; no cable is pinched.','Both wheels sit straight and clear the chassis. No shaft was bent or forced.'],evidence:['I checked both gripper mounts.','I checked all four deck corners.','I compared wheel clearance.']},
 {id:'w1',module:'wiring',range:[31,33],title:'Motor, power and servo leads',page:21,crop:5,checks:['Trace Motor 1 to M1A black / M1B red and Motor 2 to M2A red / M2B black. Terminals grip bare wire; no stray strands touch.','Identify the power socket, but leave the plug out. Battery OFF and USB disconnected.','Trace servo to S1: orange S, red +, brown −. Compare pin labels, not just colour.'],evidence:['I traced each motor wire.','I compared all S1 pin labels.','I checked for stray wire strands.']},
 {id:'w2',module:'wiring',range:[34,36],title:'Sensor wiring and cable route',page:23,crop:5,checks:['Trace ultrasonic to P2:P12: red Vcc, yellow Trigger, white Echo, black GND. Both ends match.','Trace Maker Line to P1:P9: red Vcc, yellow AN, black GND. V2 white goes to CAL; V1 white stays unconnected. If unsure of version, stop.','No cable can reach wheels or gears. Connectors are straight; cables are not pinched and all power is disconnected.'],evidence:['I identified V1/V2 before checking the white cable.','I traced both ends of the ultrasonic cable.','I checked cables near moving parts.']}
];
const FLAGS={14:'Step 14 says M3 4 mm bolts, but page 7 does not list that length. The teacher must match the actual fixings. Do not force a longer bolt into the sensor board.',21:'The booklet calls this an M2 bolt. Cytron’s separate gripper guide distinguishes a short centre horn screw from a linkage screw. Keep supplied servo screws separate and ask the teacher which is yours. Do not force an ordinary bolt into the servo shaft.',23:'The Beetle:bit booklet specifies 6 mm bolts and thick spacers. Cytron’s separate gripper guide uses 12 mm bolts at jaw pivots. Ask the teacher to check your actual set and complete joint stack before tightening; do not swap lengths by guesswork.',24:'The booklet uses four 5 mm stands here plus two at step 12, but lists only four in total. Cytron’s separate guide uses different supports. Ask the teacher to confirm yours. Do not dismantle a correct sensor mount or borrow parts.',25:'The booklet uses a 10 mm bolt and thin spacer here. Cytron’s separate gripper guide has a different pivot arrangement. Follow the teacher-confirmed arrangement for your kit, not a mixture of guides.',27:'The booklet uses a 6 mm bolt near the horn’s end. Cytron’s separate guide uses the servo’s supplied linkage screw. Ask the teacher to identify yours before tightening.'};
const PARTS=[
 {id:'b6',label:'B6',name:'M3 bolt · 6 mm',family:'bolts',image:[.11,.50,.36,.70],hint:'Raised head: measure 6 mm from under the head to the tip. Threaded shaft nominally 3 mm wide. Flagged gripper joints need teacher confirmation.'},
 {id:'b10',label:'B10',name:'M3 bolt · 10 mm',family:'bolts',image:[.11,.50,.36,.70],hint:'Measure 10 mm under a raised head to the tip. Do not identify length by the head. Used for the castor; step 25 linkage is flagged.'},
 {id:'b12',label:'B12',name:'M3 bolt · 12 mm',family:'bolts',image:[.11,.50,.36,.70],hint:'Measure 12 mm under a raised head to the tip. Page 7 lists this length. Do not substitute it for a 6 mm bolt because the head looks similar.'},
 {id:'m2',label:'M2',name:'M2 bolts and nuts',family:'bolts',image:[.11,.50,.36,.70],hint:'M2 means a nominally 2 mm threaded shaft, not head size or length. Keep separate from M3. Ask the teacher to match a measured sample. Servo screws are separate.'},
 {id:'nut',label:'N3',name:'Ordinary M3 nut',family:'nuts',image:[.12,.595,.32,.675],hint:'Hexagonal nut without a nylon locking insert. Used for fixed stands and brackets. Do not replace a pivot’s locknut with an ordinary nut.'},
 {id:'lock',label:'LN',name:'M3 locknut',family:'nuts',image:[.332,.51,.36,.675],hint:'Look for the nylon insert inside one end. Resists loosening. On a pivot it must not clamp the moving layers solid; ask if the joint binds.'},
 {id:'thin',label:'W1',name:'Thin spacer · 1 mm',family:'spacers',image:[.813,.54,.888,.65],hint:'Measure thickness from the side, not the hole. The booklet lists 1 mm washers/spacers. Step 25 needs teacher confirmation.'},
 {id:'thick',label:'W3',name:'Thick spacer · 3 mm',family:'spacers',image:[.745,.535,.805,.666],hint:'Measure side thickness: 3 mm in the inventory. Leaves space between moving layers. Do not replace with a thin washer because both have holes.'},
 {id:'s5',label:'S5',name:'M3 stand · 5 mm body',family:'stands',image:[.41,.485,.674,.665],hint:'Measure the body only, excluding its threaded stud. The short stands have an inventory/quantity mismatch; ask if yours differ or are short.'},
 {id:'s10',label:'S10',name:'M3 stand · 10 mm body',family:'stands',image:[.41,.485,.674,.665],hint:'Body length 10 mm, excluding the stud. Four support REKA:BIT. Compare on a physical ruler, not this screen.'},
 {id:'s20',label:'S20',name:'M3 stand · 20 mm body',family:'stands',image:[.41,.485,.674,.665],hint:'Body length 20 mm, excluding the stud. Two front chassis supports hold the gripper. Do not mix with 40 mm corner stands.'},
 {id:'s40',label:'S40',name:'M3 stand · 40 mm body',family:'stands',image:[.41,.485,.674,.665],hint:'Body length 40 mm, excluding the stud. Four corner stands support the top deck, matching heights and upright.'},
 {id:'servo',label:'SERVO',name:'Servo’s own screws',family:'servo',image:null,hint:'Keep the short horn centre screw and any supplied linkage/self-tapping screw in a labelled pocket. Not interchangeable with ordinary M2/M3 bolts. Ask the teacher to identify them.'}
];
const HELP_FOR_STEP={1:['s10','nut'],2:['nut','s10'],3:['b6','s10'],4:['b6','nut'],11:['b6'],12:['s5','nut'],16:['b10','nut'],17:['s20','nut'],18:['s40','nut'],21:['servo','m2'],22:['m2'],23:['b6','thick','lock'],24:['s5','nut'],25:['b10','thin','lock'],26:['b6','s5'],27:['servo','b6'],28:['b6','s20'],29:['b6','s40']};
STEPS.find(s=>s.n===14).kit='2 sensor-board fixing bolts · teacher must confirm length (booklet says M3 4 mm)';
STEPS.find(s=>s.n===21).kit='Servo · servo horn · supplied centre fixing, identified by the teacher';
STEPS.find(s=>s.n===21).do='Compare horn and servo orientation with the photograph. Keep the servo unpowered. Ask the teacher to identify the supplied centre fixing and horn position, then fit gently. Do not push the horn around by force.';
STEPS.find(s=>s.n===23).do='Before tightening, ask the teacher to check the bolt length and spacer stack in your kit. For each Part 5 jaw, compare the bolt, thick spacer and locknut arrangement with the side photograph. Match both gear teeth. Tighten only enough to hold the joint without clamping its moving layers solid.';
STEPS.find(s=>s.n===27).do='Ask the teacher to confirm the horn-linkage fixing. Compare the linkage position near the horn’s end with the close-up; the booklet uses the first or second hole from the end. Fit the confirmed fixing gently. Do not force the servo to open or close.';
