(() => {
  'use strict';
  const {stages,fields,drawings,pitActions}=window.LESSON;
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const KEY='y11-topologies-v2', DB='y11-topologies-work-v2';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const plain=html=>{const d=document.createElement('div');d.innerHTML=html;return d.textContent;};
  let state=null,db=null,teacher=false,stage='overview',saveTimer=null,saveQueue=Promise.resolve(),noticeTimer,uploadBusy=0,lastSaveOK=true;
  const pads={};
  const fresh=(name,cls)=>({version:2,id:JSON.stringify([name.trim().toLowerCase(),cls.trim().toLowerCase()]),name,cls,fields:{},photos:{},drawings:{},status:{},feedback:{},date:new Date().toLocaleDateString('en-GB'),updated:new Date().toISOString()});
  function notice(message){$('#notice').textContent=message;$('#notice').hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('#notice').hidden=true,6500);}
  function openDB(){return new Promise(resolve=>{try{const req=indexedDB.open(DB,1);req.onupgradeneeded=()=>req.result.createObjectStore('work',{keyPath:'id'});req.onsuccess=()=>resolve(req.result);req.onerror=()=>resolve(null);req.onblocked=()=>resolve(null);}catch{resolve(null);}});}
  function getRecord(id){return new Promise(resolve=>{if(!db){try{resolve(JSON.parse(localStorage.getItem(KEY+id)||'null'));}catch{resolve(null);}return;}try{const r=db.transaction('work').objectStore('work').get(id);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>resolve(null);}catch{resolve(null);}});}
  function putRecord(record){return new Promise((resolve,reject)=>{if(!db){try{localStorage.setItem(KEY+record.id,JSON.stringify(record));resolve();}catch(e){reject(e);}return;}try{const tx=db.transaction('work','readwrite');tx.objectStore('work').put(record);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);}catch(e){reject(e);}});}
  function save(){clearTimeout(saveTimer);saveTimer=null;if(!state)return saveQueue;state.updated=new Date().toISOString();const record=JSON.parse(JSON.stringify(state));$('#saveState').textContent='Saving…';saveQueue=saveQueue.then(()=>putRecord(record)).then(()=>{lastSaveOK=true;$('#saveState').textContent='Saved on this device';$('#saveState').classList.remove('error');}).catch(()=>{lastSaveOK=false;$('#saveState').textContent='Not saved — download your PDF / backup';$('#saveState').classList.add('error');notice('This browser could not save your latest work. Keep this page open and download a PDF or editable backup now.');});return saveQueue;}
  function changed(){if(!state)return;$('#saveState').textContent='Unsaved changes';clearTimeout(saveTimer);saveTimer=setTimeout(save,450);}
  function statusText(id){return state?.status[id]||'Not yet recorded';}
  function renderShell(){
    $('#navigation').innerHTML=stages.map((s,i)=>`<button data-go="${s.id}" class="${s.optional?'optional':''}"><span class="nav-number">${String(i).padStart(2,'0')}</span><span>${esc(s.id==='overview'?'Your lesson':s.id==='main1'?'Main Task 1':s.id==='main2'?'Main Task 2':s.id==='challenge'?'Fault investigation':s.id==='types'?'Types of Learning':s.id==='pitstop'?'Learning Pitstop':s.id==='starter'?'Do Now':s.id==='exam'?'Exam practice':s.id==='report'?'My evidence':'Plenary')}</span><span class="nav-state" data-nav-state="${s.id}"></span></button>`).join('');
    $('#content').innerHTML=stages.map((s,i)=>`<section id="stage-${s.id}" data-stage="${s.id}" hidden><div class="stage-top"><div><p class="eyebrow">${String(i).padStart(2,'0')} · ${esc(s.time)}</p><h1>${esc(s.title)}</h1></div><span class="badge">${esc(s.screen)}</span></div>${s.html}${s.id!=='report'?`<div class="stage-footer"><button data-attempted="${s.id}">I have attempted this stage</button><span class="status" data-stage-status="${s.id}"></span><button class="primary next" data-go="${s.id==='main2'?'pitstop':s.id==='exam'||s.id==='challenge'?'pitstop':stages[i+1].id}">${s.id==='main2'?'Continue to Pitstop':s.id==='plenary'?'Save my evidence':'Continue'} →</button></div>`:''}</section>`).join('');
    Object.keys(drawings).forEach(setupPad);
    $('#downloadReport').addEventListener('click',downloadPDF);$('#previewReport').addEventListener('click',previewReport);$('#backupWork').addEventListener('click',backup);
    $('#restoreFile').addEventListener('change',restoreBackup);
  }
  function showStage(id,focus=true){if(!stages.some(s=>s.id===id))id='overview';stage=id;$$('[data-stage]').forEach(el=>el.hidden=el.dataset.stage!==id);$$('[data-go]').forEach(el=>{if(el.closest('nav')){if(el.dataset.go===id)el.setAttribute('aria-current','step');else el.removeAttribute('aria-current');}});if(state){state.lastStage=id;changed();}history.replaceState(null,'','#'+id);if(focus){$('#content').focus({preventScroll:true});window.scrollTo({top:0,behavior:'auto'});}if(id==='report')previewReport();}
  function updateStatuses(){let attempted=0;for(const s of stages){const t=statusText(s.id);const a=$(`[data-stage-status="${s.id}"]`);if(a)a.textContent=t;const n=$(`[data-nav-state="${s.id}"]`);if(n)n.textContent=state.status[s.id]?'•':'';if(state.status[s.id]&&!s.optional&&s.id!=='overview'&&s.id!=='report')attempted++;}$('#progressText').textContent=`${attempted} of 6 core learning stages attempted. This tracks work, not a grade.`;}
  function restoreInputs(){$$('[data-field]').forEach(el=>{const v=state.fields[el.dataset.field];if(el.type==='radio')el.checked=v===el.value;else el.value=v??'';});Object.keys(drawings).forEach(k=>redraw(k));for(const s of stages){renderPhotos(s.id);renderFeedback(s.id);}renderPit();updateStatuses();}
  async function enter(name,cls){teacher=name.trim().toLowerCase()==='teacher';if(teacher)cls='Review';const empty=fresh(name.trim(),cls.trim());state=await getRecord(empty.id)||empty;$('#landing').hidden=true;$('#workspace').hidden=false;$('#studentLabel').textContent=teacher?'Teacher review':state.name;$('#studentClassLabel').textContent=state.cls;
    $('.teacher-banner')?.remove();if(teacher){const b=document.createElement('div');b.className='teacher-banner';b.innerHTML='<strong>Teacher review.</strong> All stages are available. Official marking stays in your separate teacher pack. <button id="showAll">Show all stages</button>';$('#content').prepend(b);$('#showAll').onclick=()=>{$$('[data-stage]').forEach(el=>el.hidden=false);notice('All stages are visible. Choose a stage in the menu to return to one at a time.');};}
    restoreInputs();let legacy;try{legacy=JSON.parse(localStorage.getItem('y11-w3s1-network-topologies-v1')||'null');}catch{}const oldName=legacy?.student?.name||legacy?.student?.fullName;const oldClass=legacy?.student?.class||legacy?.student?.className;if(legacy&&(teacher||(String(oldName).toLowerCase()===state.name.toLowerCase()&&String(oldClass).toLowerCase()===state.cls.toLowerCase()))){$('#legacyNotice').innerHTML='<div class="legacy"><h3>Earlier-version work is still available</h3><p>The previous lesson record has not been changed. Save a copy before continuing with this redesigned lesson.</p><button id="legacyBackup">Download earlier work</button></div>';$('#legacyBackup').onclick=()=>downloadBlob(JSON.stringify(legacy,null,2),'Earlier_Topologies_Work.json','application/json');}else $('#legacyNotice').innerHTML='';
    if(!db)notice('Photo storage is limited in this browser. Save an editable backup before closing your work.');showStage(state.lastStage||'overview',false);await save();
  }
  function setupPad(key){const canvas=$(`[data-pad="${key}"]`),ctx=canvas.getContext('2d');const p={canvas,ctx,current:null};pads[key]=p;const pt=e=>{const r=canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(canvas.width,(e.clientX-r.left)*canvas.width/r.width)),y:Math.max(0,Math.min(canvas.height,(e.clientY-r.top)*canvas.height/r.height))};};canvas.addEventListener('pointerdown',e=>{if(!state)return;e.preventDefault();canvas.setPointerCapture(e.pointerId);state.drawings[key]??=[];p.current=[pt(e)];state.drawings[key].push(p.current);redraw(key);});canvas.addEventListener('pointermove',e=>{if(!p.current)return;p.current.push(pt(e));redraw(key);});const finish=()=>{if(p.current){p.current=null;changed();}};canvas.addEventListener('pointerup',finish);canvas.addEventListener('pointercancel',finish);}
  function redraw(key){const p=pads[key];if(!p)return;const {ctx,canvas}=p;ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle='#111';ctx.lineWidth=3;ctx.lineCap='round';ctx.lineJoin='round';for(const points of state?.drawings[key]||[]){if(!points.length)continue;ctx.beginPath();ctx.moveTo(points[0].x,points[0].y);if(points.length===1){ctx.lineTo(points[0].x+.1,points[0].y+.1);}else points.slice(1).forEach(p=>ctx.lineTo(p.x,p.y));ctx.stroke();}}
  function imageData(key){return(state.drawings[key]||[]).length?pads[key].canvas.toDataURL('image/png'):null;}
  function photoId(){return globalThis.crypto?.randomUUID?.()||String(Date.now())+'-'+Math.random().toString(36).slice(2);}
  async function preparePhoto(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error(`${file.name}: use JPG, PNG or WebP. Export HEIC photos as JPG first.`);if(file.size>12*1024*1024)throw Error(`${file.name}: this image is larger than 12 MB.`);const url=URL.createObjectURL(file);try{const img=await new Promise((resolve,reject)=>{const x=new Image();x.onload=()=>resolve(x);x.onerror=()=>reject(Error(`${file.name}: the image could not be read.`));x.src=url;});const scale=Math.min(1,2000/Math.max(img.naturalWidth,img.naturalHeight)),c=document.createElement('canvas');c.width=Math.round(img.naturalWidth*scale);c.height=Math.round(img.naturalHeight*scale);const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(img,0,0,c.width,c.height);return{id:photoId(),name:file.name,data:c.toDataURL('image/jpeg',.9),caption:'',width:c.width,height:c.height};}finally{URL.revokeObjectURL(url);}}
  async function addPhotos(input){const s=input.dataset.photos,owner=state;const error=$(`[data-photo-error="${s}"]`);error.textContent='';const files=[...input.files];owner.photos[s]??=[];if(owner.photos[s].length+files.length>6){error.textContent='You can keep six photos in this stage. Remove one before adding more.';input.value='';return;}uploadBusy++;input.disabled=true;const errors=[];try{for(const file of files){try{owner.photos[s].push(await preparePhoto(file));}catch(e){errors.push(e.message);}}if(state===owner){renderPhotos(s);await save();error.textContent=errors.join(' ');notice(errors.length?'Some photographs could not be added. Check the message beside the upload.':'Photographs added. Check that your writing is readable.');}}finally{uploadBusy--;input.disabled=false;input.value='';}}
  function renderPhotos(s){const list=$(`[data-photo-list="${s}"]`);if(!list)return;list.innerHTML=(state.photos[s]||[]).map(p=>`<article class="photo-item"><a href="${p.data}" target="_blank" rel="noopener" aria-label="Open ${esc(p.name)} at full size"><img src="${p.data}" alt="Your work: ${esc(p.caption||p.name)}"></a><p>${esc(p.name)}</p><label for="caption-${p.id}">What is shown?</label><textarea id="caption-${p.id}" data-caption="${p.id}" data-photo-stage="${s}" rows="2" placeholder="e.g. Q04.2 diagram and correction">${esc(p.caption)}</textarea><button data-remove-photo="${p.id}" data-photo-stage="${s}">Remove photo</button></article>`).join('');}
  function renderPit(){const box=$('#pitAction');if(!box)return;box.innerHTML='<strong>Your next step</strong>'+esc(pitActions[state.fields.phase]||'Select a phase above, then discuss a useful next step with your teacher.');}
  function stageEntries(s){return fields.filter(f=>f.stage===s).map(f=>({...f,value:state.fields[f.key]}));}
  function stageEvidence(s){return stageEntries(s).some(f=>String(f.value??'').trim())||(state.photos[s]||[]).length||Object.keys(drawings).some(k=>drawings[k].stage===s&&(state.drawings[k]||[]).length);}
  function reviewHtml(s,all=false){let h='';for(const f of stageEntries(s)){if(!all&&!String(f.value??'').trim())continue;h+=`<h3>${esc(f.label)}</h3><div class="review-answer">${esc(f.value===0?'0':f.value||'Not recorded')}</div>`;}for(const [k,d]of Object.entries(drawings)){if(d.stage===s){const data=imageData(k);if(data)h+=`<h3>${esc(d.label)}</h3><img src="${data}" alt="${esc(d.label)}">`;}}for(const p of state.photos[s]||[])h+=`<figure><img src="${p.data}" alt="${esc(p.caption||p.name)}"><figcaption>${esc(p.caption||p.name)}</figcaption></figure>`;return h||'<p>No response has been recorded here yet.</p>';}
  function showWork(s){state.reviewSnapshots??={};state.reviewSnapshots[s]=Object.fromEntries(stageEntries(s).filter(f=>!f.key.endsWith('-feedback')&&!f.key.endsWith('-improvement')&&f.value).map(f=>[f.label,f.value]));changed();$('#reviewContent').innerHTML=`<p class="eyebrow">${esc(state.name)} · ${esc(state.cls)}</p><h2>${esc(stages.find(x=>x.id===s).title)}</h2>${reviewHtml(s)}`;$('#reviewDialog').showModal();}
  function recordFeedback(s){const note=state.fields[s+'-feedback']||'',improvement=state.fields[s+'-improvement']||'';if(!note.trim()||!improvement.trim()){notice('Add the feedback you received and your improvement first.');return;}state.feedback[s]??=[];const last=state.feedback[s].at(-1);if(last?.note===note&&last?.improvement===improvement){notice('This feedback is already saved.');return;}const original=state.reviewSnapshots?.[s]||Object.fromEntries(stageEntries(s).filter(f=>!f.key.endsWith('-feedback')&&!f.key.endsWith('-improvement')&&f.value).map(f=>[f.label,f.value]));state.feedback[s].push({at:new Date().toISOString(),note,improvement,original});if(state.reviewSnapshots)delete state.reviewSnapshots[s];state.status[s]='Feedback and improvement recorded';renderFeedback(s);updateStatuses();save();notice('Feedback and your improvement have been kept.');}
  function renderFeedback(s){const el=$(`[data-feedback-log="${s}"]`);if(!el)return;el.innerHTML=(state.feedback[s]||[]).map((x,i)=>`<article class="feedback-item"><strong>Saved feedback ${i+1}</strong><p>${esc(x.note)}</p><strong>My improvement</strong><p>${esc(x.improvement)}</p><details><summary>Responses when this was saved</summary>${Object.entries(x.original).map(([k,v])=>`<h3>${esc(k)}</h3><p>${esc(v)}</p>`).join('')||'<p>See the photographed work.</p>'}</details></article>`).join('');}
  function previewReport(){if(!state)return;$('#reportPreview').innerHTML=`<div class="card"><h2>${esc(state.name)} · ${esc(state.cls)}</h2><p>${esc(state.date)} · Week 3 Session 1</p><p class="small">“Attempted” is a record of participation, not a mastery score. Scores are entered after marking.</p>${stages.filter(s=>!['overview','report'].includes(s.id)).map(s=>`<section class="report-section"><p class="eyebrow">${esc(statusText(s.id))}</p><h2>${esc(s.title)}</h2>${!stageEvidence(s.id)&&s.optional?'<p>Optional task not attempted.</p>':reviewHtml(s.id,true)}${(state.feedback[s.id]||[]).map((x,i)=>`<h3>Saved feedback ${i+1}</h3><p class="review-answer">${esc(x.note)}\n\nMy improvement: ${esc(x.improvement)}</p>`).join('')}</section>`).join('')}</div>`;}
  function downloadBlob(data,name,type){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
  const safeName=name=>name.replace(/[^a-z0-9_-]/gi,'_').slice(0,70)||'Student';
  async function backup(){if(uploadBusy)return notice('Please wait for your photographs to finish processing.');await save();downloadBlob(JSON.stringify(state,null,2),`W3S1_${safeName(state.name)}_backup.json`,'application/json');}
  function validateBackup(v){if(!v||v.version!==2||typeof v.name!=='string'||typeof v.cls!=='string'||!v.name.trim()||!v.cls.trim())throw Error('This is not a Week 3 Session 1 backup.');const target=fresh(v.name.slice(0,80),v.cls.slice(0,30));const record={...target,fields:{},photos:{},drawings:{},status:{},feedback:{},date:typeof v.date==='string'?v.date.slice(0,40):target.date,updated:target.updated};for(const f of fields){const a=v.fields?.[f.key];if(typeof a==='string'||typeof a==='number')record.fields[f.key]=String(a).slice(0,100000);}for(const s of stages){const list=v.photos?.[s.id]||[];if(!Array.isArray(list)||list.length>6)throw Error('The photo list in this backup is not valid.');record.photos[s.id]=list.map(p=>{if(typeof p.data!=='string'||!/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(p.data))throw Error('An image in the backup is not valid.');return{id:photoId(),data:p.data,name:String(p.name||'Photograph').slice(0,150),caption:String(p.caption||'').slice(0,5000),width:Number(p.width)||1,height:Number(p.height)||1};});if(['Attempted - ready to check','Feedback and improvement recorded'].includes(v.status?.[s.id]))record.status[s.id]=v.status[s.id];const log=v.feedback?.[s.id];if(Array.isArray(log))record.feedback[s.id]=log.slice(0,100).map(x=>({at:String(x.at||''),note:String(x.note||'').slice(0,100000),improvement:String(x.improvement||'').slice(0,100000),original:Object.fromEntries(Object.entries(x.original||{}).filter(([k,val])=>typeof val==='string'||typeof val==='number').map(([k,val])=>[k.slice(0,500),String(val).slice(0,100000)]))}));}for(const k of Object.keys(drawings)){const strokes=v.drawings?.[k]||[];if(!Array.isArray(strokes)||strokes.length>20000)throw Error('Drawing data is not valid.');record.drawings[k]=strokes.map(stroke=>{if(!Array.isArray(stroke)||stroke.length>100000)throw Error('Drawing data is not valid.');return stroke.map(p=>{if(!Number.isFinite(p.x)||!Number.isFinite(p.y)||p.x<0||p.x>721||p.y<0||p.y>401)throw Error('Drawing coordinates are not valid.');return{x:p.x,y:p.y};});});}return record;}
  async function restoreBackup(e){const file=e.target.files[0];if(!file)return;if(uploadBusy){e.target.value='';return notice('Please wait for photographs to finish processing before opening a backup.');}try{if(file.size>60*1024*1024)throw Error('This backup is too large (maximum 60 MB).');const record=validateBackup(JSON.parse(await file.text()));if(record.name.trim().toLowerCase()==='teacher')throw Error('Please import a student backup.');const existing=await getRecord(record.id);if(!confirm(`Open the backup for ${record.name}, ${record.cls}?${existing?' This replaces the saved work for that name and class on this device.':''}`))return;await save();if(!lastSaveOK)throw Error('Download a backup of your current work before replacing it: the browser could not save it.');await putRecord(record);await enter(record.name,record.cls);showStage('report');notice('Backup restored.');}catch(err){$('#restoreError').textContent=err.message;}finally{e.target.value='';}}
  async function downloadPDF(){if(!state)return;if(uploadBusy)return notice('Please wait for your photographs to finish processing.');if(!window.jspdf)return notice('The PDF library could not load. Keep your work open and download the editable backup.');const buttons=[$('#downloadTop'),$('#downloadReport')];buttons.forEach(b=>b.disabled=true);try{await save();const {jsPDF}=window.jspdf;const pdf=new jsPDF({unit:'mm',format:'a4',compress:true});let font='helvetica';if(window.PDF_FONTS){pdf.addFileToVFS('Raleway.ttf',window.PDF_FONTS.regular);pdf.addFont('Raleway.ttf','Raleway','normal');pdf.addFileToVFS('RalewayBold.ttf',window.PDF_FONTS.bold);pdf.addFont('RalewayBold.ttf','Raleway','bold');font='Raleway';}const margin=17,width=176,bottom=278;let y=23;
      const clean=v=>String(v??'').replace(/[–—]/g,'-').replace(/[“”]/g,'"').replace(/[‘’]/g,"'").replace(/→/g,' -> ').replace(/[^\u0020-\u007e\u00a0-\u00ff\n\r\t]/g,'');
      const newPage=()=>{pdf.addPage();y=23;};const room=h=>{if(y+h>bottom)newPage();};
      const text=(v,size=11,bold=false)=>{pdf.setFont(font,bold?'bold':'normal');pdf.setFontSize(size);const lines=pdf.splitTextToSize(clean(v),width);const lineH=size*.45;for(const line of lines){room(lineH+1);pdf.text(line,margin,y);y+=lineH;}y+=3;};
      const heading=v=>{room(20);pdf.setDrawColor(150);pdf.line(margin,y,width+margin,y);y+=7;text(v,15,true);};
      const addImage=async(data,label)=>{const props=pdf.getImageProperties(data);const maxH=225;const ratio=Math.min(width/props.width,maxH/props.height);const w=props.width*ratio,h=props.height*ratio;room(Math.min(h+20,bottom-23));text(label,10,true);room(h+7);pdf.addImage(data,props.fileType,margin,y,w,h,undefined,'FAST');y+=h+7;};
      text('YEAR 11 COMPUTER SCIENCE',10,true);text('Network topologies',23,true);text('Term 1 - Week 3 - Session 1 | OxfordAQA 9210 | Paper 2',10);text(`${state.name} | ${state.cls} | ${state.date}`,12,true);text('WAGBA: Explain how network connections affect reliability and performance, and justify a suitable topology.');text('Work status records participation, not mastery. Scores below were entered after marking. Optional tasks may be unfinished.',9);
      for(const s of stages.filter(s=>!['overview','report'].includes(s.id))){heading(s.title);text(statusText(s.id),9);if(s.optional&&!stageEvidence(s.id)){text('Optional task not attempted.');continue;}for(const f of stageEntries(s.id)){room(20);text(f.label,10,true);text(f.value===0?'0':f.value||'Not recorded.',11);}for(const[k,d]of Object.entries(drawings)){if(d.stage===s.id){const data=imageData(k);if(data)await addImage(data,d.label);else if(s.id==='main1'||s.id==='exam')text(`${d.label}: no digital drawing; see any photographs or written alternative.`,9);}}for(const p of state.photos[s.id]||[])await addImage(p.data,p.caption||p.name);for(const [i,log]of(state.feedback[s.id]||[]).entries()){room(20);text(`Saved feedback ${i+1}`,11,true);text(log.note);text('My improvement',10,true);text(log.improvement);if(Object.keys(log.original).length){text('Responses when this feedback was saved',10,true);for(const[k,v]of Object.entries(log.original)){text(k,9,true);text(v,10);}}}}
      const pages=pdf.getNumberOfPages();for(let n=1;n<=pages;n++){pdf.setPage(n);pdf.setFont(font,'normal');pdf.setFontSize(8);pdf.setTextColor(80);const footer=pdf.splitTextToSize(`W3S1 | ${clean(state.name)} | ${clean(state.cls)}`,155)[0];pdf.text(footer,margin,289);pdf.text(`${n} / ${pages}`,193,289,{align:'right'});pdf.setTextColor(0);}pdf.save(`W3S1_Topologies_${safeName(state.name)}.pdf`);notice('PDF downloaded. Open it to check your work, then upload it to Teams.');
    }catch(e){console.error(e);notice('The PDF could not be created. Save an editable backup and try again. Your work is still open.');}finally{buttons.forEach(b=>b.disabled=false);}}
  document.addEventListener('input',e=>{if(!state)return;const el=e.target;if(el.matches('[data-field]')){if(el.type==='radio'&&!el.checked)return;const f=fields.find(f=>f.key===el.dataset.field);if(f?.score&&el.value!==''&&(!Number.isInteger(Number(el.value))||Number(el.value)<0||Number(el.value)>f.max)){state.fields[el.dataset.field]='';changed();el.setCustomValidity(`Enter a whole number from 0 to ${f.max}.`);el.reportValidity();return;}el.setCustomValidity('');state.fields[el.dataset.field]=el.value;if(el.dataset.field==='phase')renderPit();changed();}if(el.matches('[data-caption]')){const p=state.photos[el.dataset.photoStage]?.find(p=>p.id===el.dataset.caption);if(p){p.caption=el.value;changed();}}});
  document.addEventListener('change',e=>{if(e.target.matches('[data-photos]'))addPhotos(e.target);});
  document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||!state)return;if(b.dataset.go)showStage(b.dataset.go);if(b.dataset.showWork)showWork(b.dataset.showWork);if(b.dataset.attempted){const s=b.dataset.attempted;if(!teacher&&!['overview','types'].includes(s)&&!stageEvidence(s)){notice('Record an answer, drawing or photograph first. You can still use Continue to move on.');return;}state.status[s]='Attempted - ready to check';updateStatuses();save();}if(b.dataset.recordFeedback)recordFeedback(b.dataset.recordFeedback);if(b.dataset.undo){state.drawings[b.dataset.undo]?.pop();redraw(b.dataset.undo);changed();}if(b.dataset.clearPad&&confirm('Clear this drawing? This cannot be undone.')){state.drawings[b.dataset.clearPad]=[];redraw(b.dataset.clearPad);changed();}if(b.dataset.removePhoto&&confirm('Remove this photograph from your lesson? The original photo on your device is not deleted.')){state.photos[b.dataset.photoStage]=state.photos[b.dataset.photoStage].filter(p=>p.id!==b.dataset.removePhoto);renderPhotos(b.dataset.photoStage);changed();}});
  $('#studentName').addEventListener('input',()=>{$('#studentClass').required=$('#studentName').value.trim().toLowerCase()!=='teacher';});
  $('#entryForm').addEventListener('submit',async e=>{e.preventDefault();$('#entryError').textContent='';const b=e.submitter;b.disabled=true;try{if(!db)db=await openDB();await enter($('#studentName').value,$('#studentClass').value);}catch{ $('#entryError').textContent='Your lesson could not be opened. Please try again.';}finally{b.disabled=false;}});
  $('#downloadTop').addEventListener('click',downloadPDF);$('#closeReview').onclick=()=>$('#reviewDialog').close();
  $('#closeWork').addEventListener('click',async()=>{if(uploadBusy)return notice('Please wait for photographs to finish processing.');await save();if(!lastSaveOK){notice('Your latest work is not saved. Download a PDF and editable backup before leaving this page.');return;}state=null;teacher=false;$('#workspace').hidden=true;$('#landing').hidden=false;$('#entryForm').reset();$('#studentClass').required=true;$('#studentName').focus();});
  window.addEventListener('beforeunload',e=>{if(saveTimer||uploadBusy||!lastSaveOK){save();e.preventDefault();e.returnValue='';}});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state)save();});
  renderShell();
})();
