/* Lesson content and response labels. Official questions appear only as source-page images. */
(() => {
  const fields = [];
  const F = (stage,key,label,hint='',rows=3) => { fields.push({stage,key,label});return `<div class="field"><label for="${key}">${label}</label>${hint?`<p class="hint" id="${key}-hint">${hint}</p>`:''}<textarea id="${key}" data-field="${key}" rows="${rows}" ${hint?`aria-describedby="${key}-hint"`:''}></textarea></div>`; };
  const figure = (file,alt,caption='') => `<figure class="figure"><img src="assets/images/${file}.png" alt="${alt}" loading="lazy">${caption?`<figcaption>${caption}</figcaption>`:''}</figure>`;
  const pad = (key,label) => `<div class="card"><h3>${label}</h3><canvas class="draw-pad" width="720" height="400" data-pad="${key}" aria-label="${label}; use the text alternative below if drawing is not suitable"></canvas><div class="draw-tools"><button data-undo="${key}">Undo stroke</button><button data-clear-pad="${key}">Clear drawing</button></div></div>`;
  const photos = (stage,title='Add photographs of your paper work') => `<div class="card"><h3>${title}</h3><p class="hint">Use a clear JPG, PNG or WebP. You can add up to six images here (maximum 12 MB each). Keep the whole answer in view. Images are saved on this device, not uploaded to your teacher.</p><label for="photos-${stage}">Choose photographs</label><input id="photos-${stage}" type="file" accept="image/jpeg,image/png,image/webp" multiple data-photos="${stage}"><p class="error" data-photo-error="${stage}" role="alert"></p><div class="photo-list" data-photo-list="${stage}"></div></div>`;
  const feedback = (stage) => `<section class="checkpoint"><p class="eyebrow">PAUSE · SHOW · IMPROVE</p><h2>Show your reasoning</h2><p>Show your teacher the connection or sentence that supports your answer. Ask about anything you cannot yet explain.</p><button data-show-work="${stage}">Show my work</button>${F(stage,stage+'-feedback','What feedback did you receive?','A short note is enough. Leave this blank until you receive feedback.',2)}${F(stage,stage+'-improvement','My improvement','Write a more precise explanation, or describe what you corrected on your drawing.',3)}<button data-record-feedback="${stage}">Keep this feedback and improvement</button><div class="feedback-log" data-feedback-log="${stage}"></div></section>`;
  const mark = (stage,max) => {const key=stage+'-score';fields.push({stage,key,label:`Recorded score out of ${max}`,score:true,max});return `<div class="card"><label for="${key}">Score after marking (optional)</label><div class="toolbar"><input class="number-input" type="number" id="${key}" data-field="${key}" min="0" max="${max}" step="1"><span>out of ${max}</span></div><p class="hint">Enter this after your work has been marked. Leaving it blank does not mean zero.</p></div>`;};
  const starSvg = (fault=false) => `<svg class="diagram" viewBox="0 0 640 310" role="img" aria-label="Four computers each connect separately to a central switch. Computer C's cable ${fault?'has a break':'is intact'}."><g stroke="#222" stroke-width="3" fill="none"><path d="M120 65L320 150L520 65M320 150L520 255"/>${fault?'<path d="M120 255L210 208M248 190L320 150"/>':'<path d="M120 255L320 150"/>'}<rect x="275" y="127" width="90" height="46" fill="white"/>${[[90,40],[490,40],[90,230],[490,230]].map(([x,y])=>`<rect x="${x}" y="${y}" width="60" height="45" fill="white"/>`).join('')}</g><g font-size="18" fill="#111" text-anchor="middle"><text x="120" y="68">A</text><text x="520" y="68">B</text><text x="120" y="258">C</text><text x="520" y="258">D</text><text x="320" y="155" font-size="15">SWITCH</text>${fault?'<text x="235" y="222" font-size="15">BREAK</text>':''}</g></svg>`;
  const examImg=(file,alt)=>`<figure class="figure"><a href="assets/exams/${file}.png" target="_blank" rel="noopener"><img class="exam-page" src="assets/exams/${file}.png" alt="${alt}" loading="lazy"></a><figcaption>Select the page to open it at full size. Use the original question numbers in your answers.</figcaption></figure>`;
  const stages = [
    {id:'overview',title:'Your lesson',time:'60 minutes',screen:'SCREENS UP',html:`
      <p class="lead">Two networks can contain the same devices but respond differently to a fault. Today you will explain why.</p>
      <div class="reading"><p class="eyebrow">WAGBA · WHAT ARE WE GETTING BETTER AT?</p><h2>Explaining how network connections affect reliability and performance, and using this understanding to justify a suitable topology.</h2></div>
      <div class="grid3"><article class="card"><p class="eyebrow">KNOWLEDGE</p><h3>Know the structure</h3><p>Describe star and bus connections and the roles of the switch, backbone and terminators.</p></article><article class="card"><p class="eyebrow">SKILLS</p><h3>Draw and investigate</h3><p>Draw labelled networks, predict the effects of faults and write precise technical explanations.</p></article><article class="card"><p class="eyebrow">UNDERSTANDING</p><h3>Explain the consequence</h3><p>Explain why the location of a fault matters and why a network choice involves trade-offs.</p></article></div>
      <div class="card"><h2>Our route</h2><div class="table-wrap"><table><thead><tr><th>Stage</th><th>Time</th><th>Your evidence</th></tr></thead><tbody><tr><td>Do Now</td><td>6 min</td><td>Recall and predict</td></tr><tr><td>Types of Learning</td><td>3 min</td><td>Choose a strategy</td></tr><tr><td>Main Task 1</td><td>22 min</td><td>Draw both networks; explain faults</td></tr><tr><td>Main Task 2</td><td>18 min</td><td>Recommend a network for the media lab</td></tr><tr><td>Learning Pitstop</td><td>4 min</td><td>Show where you are and take a next step</td></tr><tr><td>Plenary</td><td>5 min</td><td>Apply the idea to a different diagram</td></tr><tr><td>Save and submit</td><td>2 min</td><td>Download your PDF for Teams</td></tr></tbody></table></div><p>When ready, choose <strong>Exam practice (14 marks)</strong> or the <strong>Fault investigation (10 marks)</strong>. You do not need to finish both today.</p></div>
      <div class="card"><h2>Have these ready</h2><p>Paper, a pen and a way to photograph your work. You can type or draw in this app instead. Keep your original attempt and make corrections clearly beside it.</p><p><strong>Keywords:</strong> physical topology, node, link, switch, backbone, terminator, collision, reliability.</p><p><strong>Challenge:</strong> Can you explain why separate connections do not protect a star network from every possible failure?</p></div>
      <div class="card"><h2>Reading and paper resources</h2><div class="resources"><a href="resources/Textbook_230-231.pdf" target="_blank" rel="noopener">Textbook pp. 230–231</a><a href="resources/Topology_Exam_Practice_14_Marks.pdf" target="_blank" rel="noopener">Original exam practice · 14 marks</a><a href="worksheet.html" target="_blank" rel="noopener">Paper worksheet</a></div><p class="hint">Read the correction below before using the textbook page.</p><div class="callout"><strong>A correction to textbook page 230</strong>The bus paragraph says a terminator sends signals back along the cable. A terminator instead absorbs signal energy to prevent unwanted reflections. A star network can also become congested; separate links do not guarantee unlimited speed.</div><p class="small">OxfordAQA International GCSE Computer Science · specification 3.5. This lesson focuses on Paper 2 knowledge and application. Protocols and the TCP/IP layers follow in later sessions.</p></div><div id="legacyNotice"></div>`},
    {id:'starter',title:'What makes a network?',time:'6 minutes',screen:'READ, THEN SCREENS DOWN',html:`
      <div class="reading"><p class="eyebrow">READ FIRST</p><h2>Connect to last lesson</h2><p>A network connects devices so that they can communicate and share resources. <strong>LAN</strong> describes a network's geographical scope. Copper cable, fibre-optic cable and wireless connections describe how data travels. Today we will investigate another feature: how the devices and their connections are arranged.</p><p>A <strong>node</strong> is a device connected to a network. A <strong>link</strong> is a connection between devices.</p></div>
      <p>Read the reminder, then answer on paper or below. Question 4 is a prediction: you are not expected to know the new topic yet.</p>
      ${F('starter','starter1','1. A school connects computers and a shared printer within one building. Is this a LAN or WAN? Explain your choice.')}
      ${F('starter','starter2','2. Give one benefit of sharing a printer through a network.')}
      ${F('starter','starter3','3. Name one wired transmission medium.', '',2)}
      ${F('starter','starter4','4. Two networks contain the same number of computers. Could the way they are connected affect what happens when a cable breaks? Make a prediction.')}
      ${photos('starter')}
      <div class="checkpoint"><h2>Discuss your prediction</h2><p>Be ready to explain which part of the network you think the other computers might depend on. We will return to this idea in Main Task 1.</p><button data-show-work="starter">Show my work</button></div>`},
    {id:'types',title:'How will I get better today?',time:'3 minutes',screen:'SCREENS DOWN · DISCUSS',html:`
      <p class="lead">You will use all three types of learning today. They describe what you are doing, not a fixed type of learner.</p>
      <div class="rule-list"><article><p class="eyebrow">KNOWLEDGE · REMEMBER</p><h2>I need to know what the parts do.</h2><p>Recall the meaning of switch, backbone and terminator, then point to each one on a diagram.</p></article><article><p class="eyebrow">SKILLS · PRACTISE</p><h2>I need to draw the connections accurately.</h2><p>Draw the network, check where every cable goes and correct anything missing.</p></article><article><p class="eyebrow">UNDERSTANDING · EXPLAIN AND APPLY</p><h2>I need to explain why a fault matters.</h2><p>Follow the communication path and identify the connection that is lost. Then explain the consequence.</p></article></div>
      <div class="card"><h2>Talk with your partner</h2><p>Which type of learning did you use in the starter? Which will you need to investigate a broken connection?</p>${F('types','strategy','Which strategy will help you today?','For example: I will follow the cables with my finger before deciding which computers are affected.',2)}</div>`},
    {id:'main1',title:'Build the network. Find the failure.',time:'22 minutes',screen:'READ → DRAW → DISCUSS',html:`
      <p class="lead">First understand the connections. Then draw both networks and explain what changes when something fails.</p>
      <section class="reading"><p class="eyebrow">1 · UNDERSTAND THE STRUCTURE · ABOUT 8 MINUTES</p><h2>Physical topology is about connections</h2><p>The <strong>physical topology</strong> describes how network devices and their communication links are arranged. It is not simply the position of the desks. Computers in a straight row can still form a star network if each has a separate cable to a central switch.</p>${figure('image-1-what-is-network-topology','Overview of network devices and the links connecting them','Look at where each connection goes, not the shape of the room.')}
      <h3>Star: a separate link for each device</h3><p>In a wired star network, every computer has its own cable to a central switch. A switch connects devices on the LAN and forwards data towards its intended destination. For this lesson, consider communication between two connected computers: it passes through the switch.</p><p>If one computer's cable breaks, that computer loses its connection. The other computers still have their own links to the switch and can normally continue communicating. But if the central switch fails, all communication that depends on it stops. The switch is a <strong>single point of failure</strong>.</p><p>Separate links make a fault easier to isolate. New computers can be added using spare switch ports and new cables. Those cables and the switch add to installation cost.</p>${starSvg(false)}
      <h3>Bus: one shared backbone</h3><p>In a traditional bus network, devices connect to one main cable called the <strong>backbone</strong>. A <strong>terminator</strong> at each end absorbs signal energy and prevents unwanted reflections. It does not send the signal back to the sender.</p><svg class="diagram" viewBox="0 0 640 260" role="img" aria-label="Bus network: four computers connect to one continuous backbone, terminated at both ends."><g stroke="#222" stroke-width="3" fill="white"><path d="M70 145H570M170 90V145M340 90V145M255 145V200M460 145V200"/><rect x="60" y="130" width="15" height="30"/><rect x="565" y="130" width="15" height="30"/><rect x="140" y="45" width="60" height="45"/><rect x="310" y="45" width="60" height="45"/><rect x="225" y="200" width="60" height="45"/><rect x="430" y="200" width="60" height="45"/></g><g font-size="16" fill="#111" text-anchor="middle"><text x="170" y="73">A</text><text x="340" y="73">B</text><text x="255" y="229">C</text><text x="460" y="229">D</text><text x="66" y="118" font-size="13">Terminator</text><text x="574" y="118" font-size="13">Terminator</text><text x="380" y="176">Backbone</text></g></svg><p>A computer being switched off normally leaves the backbone intact, so other computers can still communicate. A break in the backbone disrupts the shared connection and can stop the whole network operating correctly.</p><p>Devices share the transmission medium. If two transmit at the same time, their signals can interfere: this is a <strong>collision</strong>. Transmissions may need to be repeated, reducing effective performance as traffic increases. A switched star with full-duplex links avoids these shared-medium collisions, although its equipment and links still have capacity limits.</p><p>Bus can use less cabling and no central switch, but physical bus LANs are mainly a historical comparison today. We study both because they are in your syllabus.</p><p class="small">Reading reference: textbook printed pp. 230–231. Use the corrected terminator explanation above.</p></section>
      <section class="card"><p class="eyebrow">2 · WATCH ONE INVESTIGATION · ABOUT 2 MINUTES</p><h2>Does the break remove this path?</h2>${starSvg(true)}<p>Computer A needs to communicate with B. Follow A → switch → B. Computer C's cable breaks. Is the path between A and B still connected?</p><details><summary>After discussing: follow the explanation</summary><p>Yes. A and B still have working connections to the switch. C's broken link does not remove either of those connections, so A and B can still communicate. C cannot use the network through that link.</p></details></section>
      <section class="card"><p class="eyebrow">3 · YOUR TURN · ABOUT 7 MINUTES</p><h2>Draw two networks for four computers</h2><p>On paper, draw a star and a bus. Label the computers, switch, backbone and terminators where they belong. Use clear lines for connections. Put your name on the page.</p><p>If you prefer to draw here, use these pads. A short written description is also available.</p></section>
      <div class="grid2">${pad('star','Star network · four computers')}${pad('bus','Bus network · four computers')}</div>
      <details><summary>Written alternative to drawing</summary>${F('main1','starDescription','Describe every connection in your star diagram.')}${F('main1','busDescription','Describe every connection in your bus diagram, including the ends of the backbone.')}</details>
      ${F('main1','faultLink','1. Mark a break in one computer’s cable to the star’s switch. Who loses network access, and why?')}
      ${F('main1','faultBus','2. Mark a break in the bus backbone. Explain how this differs from one computer simply being switched off.')}
      ${F('main1','faultSwitch','3. Which component could stop communication between all four computers in the star if it failed? Explain why.')}
      ${photos('main1','Add your diagrams and written explanations')}
      <details><summary>After your attempt: compare the structure and fault effects</summary>${figure('image-2-star-topology-structure-and-faults','Star topology: separate links to a switch; one link fault versus switch failure')}${figure('image-3-bus-topology-structure-and-faults','Bus topology: one backbone with terminators; a failed computer versus a broken backbone')}<p>Check that your star's cables end at the switch, not at another computer. Check that your bus has a continuous backbone, four computers and a terminator at each end. The illustrations show five computers; your task requires four.</p></details>
      ${feedback('main1')}`},
    {id:'main2',title:'Recommend a network for the media lab',time:'18 minutes · 10 marks',screen:'PLAN → WRITE → CHECK',html:`
      <div class="reading"><p class="eyebrow">THE BRIEF</p><h2>A growing digital media lab</h2><p>The school is opening a digital media lab with <strong>12 computers, a shared printer and a file server</strong>. Six more computers will be added next year. Students regularly transfer large video files. A fault in one computer's cable should not interrupt everyone else's work.</p><p>The school can purchase a switch with enough ports for the planned devices, but it still needs to control installation costs. Compare a <strong>switched star network</strong> with a <strong>traditional bus network</strong>.</p><details><summary>View the media-lab illustration</summary>${figure('image-5-growing-digital-media-lab-scenario','Digital media lab with computers, printer and file server, with plans to expand')}<p>Use the written brief above for the task requirements.</p></details></div>
      <div class="card"><p class="eyebrow">BEFORE YOU WRITE · ABOUT 2 MINUTES</p><h2>Make the reason clear</h2><p>“Star is reliable” names a benefit but does not explain it.</p><blockquote>Each computer has a separate connection to the switch, so a fault in one computer's cable normally disconnects only that computer. This allows the other students to continue using the network.</blockquote><p>Notice the link: <strong>feature → consequence → relevance to the lab</strong>. Apply this approach to the other requirements below.</p><details><summary>I need help with the key ideas</summary><p><strong>Traffic:</strong> a traditional bus shares one medium, while a switched star provides separate links. Think about what happens when many computers send data.</p><p><strong>Expansion:</strong> consider both the switch port and cable required for each extra computer.</p><p><strong>Cost:</strong> identify the equipment or materials that must be purchased.</p><p><strong>Failure:</strong> follow the communication path. Which paths depend on the switch?</p></details></div>
      <p>Work independently for about 9 minutes. Answer below or on paper. After Question 2, show your teacher one explanation.</p>
      ${F('main2','lab1','1. Recommend a topology and describe its connections. [2 marks]')}
      ${F('main2','lab2','2. Explain why it suits the lab’s large file transfers compared with a traditional bus. [2 marks]')}
      <div class="callout"><strong>Quick teacher check</strong>Show the feature and consequence in your answer to Question 2. Use the feedback in your next answer.<div class="actions"><button data-show-work="main2">Show my work</button></div></div>
      ${F('main2','lab3','3. Explain how the additional computers could be connected, using the information given. [2 marks]')}
      ${F('main2','lab4','4. Explain one installation-cost disadvantage compared with bus. [2 marks]')}
      ${F('main2','lab5','5. Explain what would happen if the central switch failed. [2 marks]')}
      ${photos('main2')}${feedback('main2')}${mark('main2',10)}`},
    {id:'exam',title:'Original Paper 2 practice',time:'Optional · 14 marks',screen:'INDEPENDENT EXAM PRACTICE',optional:true,html:`
      <p class="lead">Use the original questions to practise accurate diagrams and precise answers. There are 11 marks on topologies and 3 marks revisiting LAN and WAN.</p><div class="callout"><strong>Choose this when you are ready</strong>Allow about 15–20 minutes. Start in class if you finish the main work; your teacher will tell you when to complete anything remaining. Return for the Learning Pitstop and plenary with everyone else.</div>
      <div class="resources"><a href="resources/Topology_Exam_Practice_14_Marks.pdf" target="_blank" rel="noopener">Open / print the 14-mark paper</a></div><p>Answer on the printed paper and add photographs, or use the boxes below. Keep the question numbers. The original pages and marks have not been changed.</p>
      <section class="card"><p class="eyebrow">JUNE 2023 · QUESTION 04 · 8 MARKS</p><h2>LAN/WAN and topology comparison</h2>${examImg('jun23-p06','Original June 2023 Paper 2 page 6, questions 04.1 to 04.3: LAN/WAN, a bus diagram and star advantages')}${examImg('jun23-p07','Original June 2023 Paper 2 page 7, question 04.4: one bus advantage')}${F('exam','exam041','June 2023 · 04.1 [3 marks]')}${pad('examBus','June 2023 · 04.2 [2 marks] · draw here or add a photograph')}${F('exam','exam043','June 2023 · 04.3 [2 marks]')}${F('exam','exam044','June 2023 · 04.4 [1 mark]', '',2)}</section>
      <section class="card"><p class="eyebrow">JUNE 2025 · QUESTIONS 10.1–10.3 · 3 MARKS</p><h2>Interpret Figure 8</h2>${examImg('jun25-p16','Original June 2025 Paper 2 page 16 including Figure 8 and questions 10.1, 10.2 and 10.3')}${F('exam','exam101','June 2025 · 10.1 [1 mark]', '',2)}${F('exam','exam102','June 2025 · 10.2 [1 mark]', '',2)}${F('exam','exam103','June 2025 · 10.3 [1 mark]', '',2)}</section>
      <section class="card"><p class="eyebrow">JUNE 2026 · QUESTION 06 · 3 MARKS</p><h2>Star structure and installation cost</h2>${examImg('jun26-p08','Original June 2026 Paper 2 page 8 containing questions 06.1 and 06.2')}${F('exam','exam061','June 2026 · 06.1 [2 marks]')}${F('exam','exam062','June 2026 · 06.2 [1 mark]', '',2)}</section>
      ${photos('exam','Add your exam answers · up to six photographs')}${feedback('exam')}${mark('exam',14)}`},
    {id:'challenge',title:'The computers work. The files do not.',time:'Optional · 10 marks',screen:'INVESTIGATE',optional:true,html:`
      <div class="reading"><p class="eyebrow">FAULT INVESTIGATION</p><h2>What does the evidence tell you?</h2><p>The media lab now uses a star network. All computers can communicate with one another and use the shared network printer. However, nobody can open files stored on the file server.</p><blockquote>A student concludes: “The central switch must have failed.”</blockquote><p><strong>Reminder:</strong> the file server provides shared files and has its own network connection. A device, its connection or the service it provides can fail without every other network connection failing.</p></div>
      <p>Use the observations to test the conclusion. You do not need specialist commands. Describe a sensible check and what the result would tell you.</p>
      ${F('challenge','investigate1','1. Explain why the observations do not support the student’s conclusion. [2 marks]')}
      ${F('challenge','investigate2','2. Suggest two possible causes consistent with the observations. [2 marks]')}
      ${F('challenge','investigate3','3. Describe a check for each cause and explain what each result could tell you. [4 marks]','Check your own proposed causes, rather than listing unrelated checks.',5)}
      ${F('challenge','investigate4','4. Explain the difference between losing one shared service and losing communication across the whole network. [2 marks]')}
      ${photos('challenge')}${feedback('challenge')}${mark('challenge',10)}`},
    {id:'pitstop',title:'Where is your learning now?',time:'4 minutes',screen:'SCREENS DOWN · DISCUSS',html:`
      <p class="lead">Choose the phase that describes your work now. Point to a diagram or explanation that supports your choice. This is not a grade.</p>
      <fieldset class="card"><legend>Your current phase</legend><div class="choice-grid">${[
        ['new','New learning','I can explain the connections with some support.'],['consolidating','Consolidating','I can draw both networks and explain faults independently.'],['treading','Treading water','I can already explain these examples accurately and need more challenge.'],['drowning','Drowning','I cannot yet follow how the devices communicate and need help.']
      ].map(([v,t,d])=>`<label><input type="radio" name="phase" data-field="phase" value="${v}"><strong>${t}</strong>${d}</label>`).join('')}</div></fieldset>
      ${F('pitstop','pitEvidence','Which part of your work supports your choice?','Name a particular diagram, answer or correction.',2)}
      <div id="pitAction" class="callout"><strong>Your next step</strong>Select a phase above, then discuss a useful next step with your teacher.</div>
      ${F('pitstop','pitNext','What will you try next?','One specific action is enough.',2)}`},
    {id:'plenary',title:'Has the topology changed?',time:'5 minutes',screen:'SCREENS DOWN · NO NOTES',html:`
      <p class="lead">These computers are in a straight row. Look carefully at their connections.</p>
      <svg class="diagram" viewBox="0 0 800 360" role="img" aria-label="Four computers sit in a straight row. Each has a separate cable to a switch at the right side. There is no shared backbone."><g fill="none" stroke="#222" stroke-width="3"><path d="M100 120V270H690V175M255 120V235H675V175M410 120V200H660V175M565 120V165H645V175"/>${[70,225,380,535].map(x=>`<rect x="${x}" y="65" width="60" height="55" fill="white"/>`).join('')}<rect x="625" y="175" width="100" height="50" fill="white"/></g><g fill="#111" font-size="18" text-anchor="middle"><text x="100" y="100">A</text><text x="255" y="100">B</text><text x="410" y="100">C</text><text x="565" y="100">D</text><text x="675" y="205" font-size="15">SWITCH</text></g><text x="45" y="320" font-size="16" fill="#333">Crossing lines without a dot are not joined.</text></svg>
      ${F('plenary','exit1','1. Is this star or bus? Explain using the connections, not the positions of the computers.')}
      ${F('plenary','exit2','2. Computer B is switched off. Can the remaining computers still communicate? Explain.')}
      ${photos('plenary')}<div class="checkpoint"><h2>Ready to finish?</h2><p>Show your independent answer to your teacher. Then download your evidence PDF and submit it in Teams. If you need to revisit something next lesson, keep your teacher's feedback below.</p>${F('plenary','exitFeedback','Feedback to remember (optional)', '',2)}</div>`},
    {id:'report',title:'Your evidence for Teams',time:'2 minutes',screen:'SAVE & SUBMIT',html:`
      <p class="lead">Your PDF includes your answers, drawings, photographs and saved feedback. Blank answers remain labelled as not recorded.</p><div class="actions"><button class="primary" id="downloadReport">Download my PDF</button><button id="previewReport">Preview my evidence</button><button id="backupWork">Save editable backup</button></div>
      <div class="card"><h2>Submit your work</h2><ol><li>Download your PDF and open it to check the pages.</li><li>Make sure your name, class and photographed work are readable.</li><li>Upload it to the correct Microsoft Teams assignment.</li><li>Keep the editable backup if you will continue on another device.</li></ol><p>Your work is <strong>not submitted automatically</strong>. This website cannot see whether you have uploaded your PDF to Teams.</p></div>
      <details><summary>Continue from an editable backup</summary><p>Import your own backup file to continue on this device. You will be asked before it replaces work for the same name and class.</p><label for="restoreFile">Choose a lesson backup</label><input type="file" id="restoreFile" accept="application/json,.json"><p class="error" id="restoreError" role="alert"></p></details><div id="reportPreview"></div>`}
  ];
  fields.push({stage:'pitstop',key:'phase',label:'Current learning phase'});
  window.LESSON={stages,fields,drawings:{star:{stage:'main1',label:'Star diagram'},bus:{stage:'main1',label:'Bus diagram'},examBus:{stage:'exam',label:'June 2023 Q04.2 - bus diagram'}},pitActions:{new:'Try another fault without the model. Follow the communication path before deciding which computers are affected.',consolidating:'Apply your understanding to the fault investigation or check your precision with the original exam practice.',treading:'Investigate why the shared files are unavailable. Use evidence to distinguish two possible causes.',drowning:'Ask your teacher to follow one communication path with you. Identify each device and connection before investigating a break.'}};
})();
