const fs=require('fs'),path=require('path'),assert=require('assert');
const {JSDOM}=require(process.env.JSDOM_PATH||'jsdom');
const base=__dirname;
function boot(saved){const dom=new JSDOM(fs.readFileSync(path.join(base,'index.html'),'utf8'),{url:'https://school.example/year8-week3-project/',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.confirm=()=>true;if(saved)for(const[k,v]of Object.entries(saved))w.localStorage.setItem(k,v);for(const file of ['lesson.js','views.js','visual-lesson.js','report.js','app.js'])w.eval(fs.readFileSync(path.join(base,file),'utf8'));return w;}
const w=boot(),d=w.document;
function set(selector,value){const el=d.querySelector(selector);assert(el,selector);el.value=value;el.dispatchEvent(new w.Event('input',{bubbles:true}));el.dispatchEvent(new w.Event('change',{bubbles:true}));}
function start(name,cls,device='windows',editor='blocks'){set('#studentName',name);set('#studentClass',cls);set('#entryDevice',device);set('#entryEditor',editor);d.querySelector('#entryForm').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));}
start('','8T');assert(!w.BadgeApp.state);start('Ada','');assert(!w.BadgeApp.state);start('Ada','8T');assert(w.BadgeApp.state);
const A=w.BadgeApp,L=w.Lesson,s=A.state;
assert(L.cards.indexOf(L.cards.find(c=>c.id==='extension'))>L.cards.indexOf(L.cards.find(c=>c.id==='pitfocus')));
assert(L.cards.findIndex(c=>c.id==='build-open')+1===L.cards.findIndex(c=>c.id==='build'));
assert(L.cards.findIndex(c=>c.id==='build')+1===L.cards.findIndex(c=>c.id==='build-try'));
let renders=0;
for(const language of ['en','zh','ko'])for(const editor of ['blocks','makepython','micropython']){s.language=language;s.student.editor=editor;for(const c of L.cards){A.go(c.id);assert(d.querySelector('article h2').textContent);assert(d.querySelector('.side-wagba').textContent.includes('WAGBA'));for(const im of d.querySelectorAll('img[src^="assets/"]'))assert(fs.existsSync(path.join(base,im.getAttribute('src'))),im.src);if(c.challenge&&c.phase==='code'){assert(d.querySelector('.editor-launch'));assert(editor==='blocks'?d.querySelector('.guide-figure img'):d.querySelector('pre[id^="code-"]'));}renders++;}}
s.language='en';s.student.editor='blocks';A.go('extension');assert(A.status('ext-teams-brief')==='open');d.querySelector('[data-preview="steps"][data-command="a"]').click();assert(JSON.parse(s.fields.ext_steps_preview).a===1);assert(A.status('ext-teams-brief')==='open');assert(!s.reviewed.extension);d.querySelector('[data-action="next"]').click();assert.equal(s.card,'ext-steps-code');d.querySelector('[data-action="next"]').click();assert.equal(s.card,'ext-steps-try');set('[data-field="ext_steps_result"]','changed');set('[data-field="ext_steps_note"]','I changed 1 to 2; three shakes gave 6.');d.querySelector('[data-action="next"]').click();assert.equal(s.card,'ext-teams-brief');assert.equal(A.status('ext-steps-try'),'recorded');assert.equal(A.status('ext-teams-brief'),'open');
A.go('ext-dial-brief');set('[data-preview-dial="dial"]','512');d.querySelector('[data-preview="dial"][data-command="a"]').click();set('[data-preview-dial="dial"]','900');d.querySelector('[data-preview="dial"][data-command="b"]').click();assert.equal(JSON.parse(s.fields.ext_dial_preview).a,512);assert(d.querySelector('.preview-message').textContent.includes('512'));
const last=s.card;A.save();const saved=Object.fromEntries(Object.entries(w.localStorage));const w2=boot(saved);w2.document.querySelector('[data-action="resume"]').click();assert.equal(w2.BadgeApp.state.card,last);assert.equal(w2.BadgeApp.state.fields.ext_steps_note,s.fields.ext_steps_note);assert.equal(w2.BadgeApp.state.fields.ext_dial_preview,s.fields.ext_dial_preview);
const restored=A.validate(JSON.parse(JSON.stringify(s)));assert.equal(restored.fields.ext_steps_result,'changed');assert.equal(restored.fields.ext_dial_preview,s.fields.ext_dial_preview);
const report=w.Report.blocks(s,A.status,A.percentage()).map(b=>b.text||'').join('\n');assert(report.includes('I changed 1 to 2'));assert(report.includes('Movement detective'));assert(report.includes('freeze a dial reading'));assert(report.indexOf('Learning Pitstop')<report.indexOf('Go Further'));assert(report.includes('Not recorded'));
A.go('ext-signal-code');const image=d.querySelector('.guide-figure img');image.dispatchEvent(new w.Event('error'));assert.equal(image.closest('figure').querySelector('.image-fallback').hidden,false);
A.go('extension');d.querySelector('[data-action="goto"][data-card="explain"]').click();assert.equal(s.card,'explain');assert.equal(A.status('ext-teams-try'),'open');
// Teacher profile uses a different storage key; student work is left untouched.
d.querySelector('[data-action="menu"]').click();d.querySelector('[data-action="home"]').click();start('teacher','');assert(A.state.teacher);assert.equal(A.state.student.name,'teacher');assert(Object.keys(w.localStorage).some(k=>k.endsWith('teacher')));assert(Object.keys(w.localStorage).some(k=>k.includes('ada')));
for(const c of L.cards)A.go(c.id);
const samples={};for(const [k,v]of Object.entries(w.VisualLesson.data)){samples[k]={makepython:v.makepython,micropython:v.micropython,js:v.js};}
console.log(JSON.stringify({ok:true,renders,cards:L.cards.length,codeSamples:samples}));w.close();w2.close();
