'use strict';
(()=>{
 const facts=window.WEEK5_PROJECT_FACTS||[];let selected=null,pending=null,classroomSession='waiting',ownPlace=null,activeDemo=null;
 const baseRender=render,baseReport=report;
 const pageLabel=id=>tx((PAGES.find(p=>p[0]===id)||PAGES[0])[1]);
 const fact=id=>facts.find(f=>f.id===id);
 const factText=(f,key,label)=>`<label class="fact-answer" for="${f.id}_${key}">${esc(tx(label))}<textarea id="${f.id}_${key}" data-answer="${f.id}_${key}" rows="2">${esc(state.answers[f.id+'_'+key]||'')}</textarea></label>`;
 const codeBox=code=>`<pre class="code-sample"><code>${esc(code)}</code></pre>`;
 function factBody(f){return `<div class="fact-slide"><p class="fact-statement">${esc(tx(f.statement))}</p>${f.code?codeBox(f.code):`<div class="fact-rule">${esc(tx(f.rule))}</div>`}${f.values?`<div class="fact-boundaries">${f.values.map(v=>`<span>${esc(v)}</span>`).join('')}</div>`:''}<section class="fact-questions"><h2>${esc(tx(T('Class questions','Soalan kelas','课堂问题')))}</h2><p class="small">${esc(tx(T('Write while the class discusses the example. Your answers remain in this browser and your PDF.','Tulis semasa kelas membincangkan contoh. Jawapan kekal dalam pelayar ini dan PDF anda.','全班讨论示例时作答。答案只保存在此浏览器和你的 PDF 中。')))}</p>${f.questions.map(([k,l])=>factText(f,k,l)).join('')}</section><section class="fact-challenge"><h2>${esc(tx(T('Challenge','Cabaran','挑战')))}</h2>${factText(f,'challenge',f.challenge)}</section></div>`;}
 function ttaPanel(){return `<section class="tta-panel"><div><b>TOPIC</b><p>${esc(tx(LESSON.title))}</p></div><div><b>WAGBA</b><p>${esc(tx(LESSON.wagba))}</p></div><div><b>KEYWORDS</b><p>${esc(tx(T('input · validation · integer · variable · constant · nested selection · boundary · test evidence','input · pengesahan · integer · pemboleh ubah · pemalar · pemilihan bersarang · sempadan · bukti ujian','输入 · 验证 · 整数 · 变量 · 常量 · 嵌套选择 · 边界 · 测试证据')))}</p></div><div><b>CHALLENGE</b><p>${esc(tx(T('Explain why unsuitable input must not produce advice.','Jelaskan mengapa input tidak sesuai tidak boleh menghasilkan nasihat.','解释为什么不合适的输入不能生成建议。')))}</p></div></section>`;}
 render=function(){if(pending&&!entry){selected=pending;pending=null;}document.body.classList.toggle('fact-view',Boolean(selected&&!entry));baseRender();if(!selected||entry){window.dispatchEvent(new Event('lesson:render'));return;}const f=fact(selected);const side=document.querySelector('.sidebar');if(side)side.insertAdjacentHTML('beforeend',ttaPanel());const main=document.getElementById('main');if(main)main.innerHTML=`<div class="page-heading"><div><span class="eyebrow">${esc(tx(T('Teacher presentation','Persembahan guru','教师演示')))}</span><h1 id="page-title" tabindex="-1">${esc(tx(f.title))}</h1></div></div>${factBody(f)}<footer class="page-footer"><button data-page="${state.page}">${esc(tx(T('Return to lesson','Kembali ke pelajaran','返回课程')))}</button></footer>`;window.dispatchEvent(new Event('lesson:render'));};
 function navigate(id,remote=false){if(!remote&&window.ClassroomMode?.locked())return;if(fact(id)){selected=id;render();scrollTo(0,0);document.getElementById('page-title')?.focus();return;}if(!PAGES.some(p=>p[0]===id))return;selected=null;if(live)stopRun('stopped');state.page=id;save();render();scrollTo(0,0);document.getElementById('page-title')?.focus();}
 function placeKey(){return `cm-own:${classroomSession}:${storageKey}`;}
 function captureOwn(){if(entry||ownPlace)return;try{ownPlace=JSON.parse(sessionStorage.getItem(placeKey())||'null');}catch{}if(!ownPlace){ownPlace={page:state.page,scroll:scrollY};try{sessionStorage.setItem(placeKey(),JSON.stringify(ownPlace));}catch{}}}
 function returnOwn(){if(entry)return;if(!ownPlace)try{ownPlace=JSON.parse(sessionStorage.getItem(placeKey())||'null');}catch{}const p=ownPlace;ownPlace=null;try{sessionStorage.removeItem(placeKey());}catch{}selected=null;if(p&&PAGES.some(x=>x[0]===p.page)){navigate(p.page,true);requestAnimationFrame(()=>scrollTo(0,p.scroll||0));}}
 function demoState(){if(!activeDemo)return {open:false};const actual=activeDemo==='core'?'main':'challenge',editor=document.querySelector(`[data-code="${actual}"]`),code=(editor?.value??state.code[actual]??'').slice(0,20000),cursor=Math.max(0,Math.min(code.length,editor?.selectionStart||0)),last=state.runs.filter(r=>r.id===actual).at(-1);return {open:true,program:activeDemo,title:activeDemo==='core'?'Helpdesk adviser':'Helpdesk challenge',code,output:String(live?.id===actual?live.output:(last?.output||last?.error||'')).slice(0,24000),line:code.slice(0,cursor).split('\n').length,selectionStart:cursor,selectionEnd:Math.max(cursor,Math.min(code.length,editor?.selectionEnd||cursor)),running:Boolean(live?.id===actual)};}
 window.LessonClassroom=Object.freeze({
  info:()=>({page:selected||state.page,lang:state.lang,entry,teacher}),pages:()=>[...PAGES.map(p=>p[0]),...facts.map(f=>f.id)],
  destinations:()=>PAGES.map(p=>({id:p[0],title:tx(p[1]),group:tx(GROUPS[p[2]])})),label:()=>selected?tx(fact(selected).title):pageLabel(state.page),teacherPages:()=>facts.map(f=>({id:f.id,title:tx(f.title)})),
  openTeacherPage:id=>{if(teacher&&fact(id))navigate(id,true);},navigate:id=>navigate(id),move:id=>{if(teacher)return;captureOwn();if(entry){pending=id;return;}navigate(id,true);},
  captureOwn,returnOwn,setSession:id=>{if(classroomSession!==id){classroomSession=id||'waiting';ownPlace=null;}},clearTarget:()=>{pending=null;},
  demoPrograms:()=>[{id:'core',title:'Helpdesk adviser'},{id:'extension',title:'Helpdesk challenge'}],startDemo:id=>{if(!teacher||!['core','extension'].includes(id))return false;activeDemo=id;navigate(id==='core'?'main1':'challenge',true);requestAnimationFrame(()=>document.querySelector(`[data-code="${id==='core'?'main':'challenge'}"]`)?.focus());return true;},stopDemo:()=>{activeDemo=null;},demoState
 });
 report=function(){let html=baseReport(),extra='';for(const f of facts){const qs=[...f.questions,['challenge',f.challenge]].filter(([k])=>String(state.answers[f.id+'_'+k]||'').trim());if(qs.length)extra+=`<section><h2>${esc(tx(f.title))}</h2>${qs.map(([k,l])=>`<h3>${esc(tx(l))}</h3><p>${esc(state.answers[f.id+'_'+k])}</p>`).join('')}</section>`;}const at=html.lastIndexOf('</div>');return at<0?html+extra:html.slice(0,at)+extra+html.slice(at);};
 document.addEventListener('click',e=>{const b=e.target.closest('button[data-page]');if(b&&fact(b.dataset.page)){e.preventDefault();e.stopImmediatePropagation();navigate(b.dataset.page);}},true);
 document.addEventListener('input',e=>{if(activeDemo&&e.target.matches('textarea[data-code]'))window.dispatchEvent(new Event('lesson:demo-change'));});
 render();
})();
