(()=>{'use strict';
const plan=window.SESSION_PLAN,clock=window.LessonClock,lesson=window.LessonClassroom;if(!plan||!clock||!lesson)return;
const teacher=lesson.info().teacher,key=teacher?'teacher':'student';
const root=document.createElement('details');root.id='lesson-clock';root.setAttribute('aria-label','Lesson clock');
root.innerHTML=`<summary title="Drag to move; click to open the lesson clock"><span id="clock-time"></span><b id="clock-short"></b><span id="clock-bubble-stage"></span></summary><div class="clock-panel"><div class="clock-heading"><div><span class="clock-kicker">LESSON CLOCK</span><h2>8:50–9:50 a.m.</h2></div><button type="button" id="clock-close" aria-label="Close lesson clock">×</button></div><p class="clock-note">Malaysia time · uses this device’s clock</p><label class="clock-follow"><input id="clock-follow" type="checkbox" checked> Follow the lesson clock</label><p class="clock-note">The clock suggests where to work. It never moves your page automatically.</p><div id="clock-guidance"><h3 id="clock-stage"></h3><strong id="clock-countdown"></strong><p id="clock-current"></p><p id="clock-next"></p><button type="button" id="clock-open">Open suggested page</button><div id="clock-steps"></div></div><fieldset class="clock-corners"><legend>Move the clock</legend><button type="button" data-corner="tl">↖ Top left</button><button type="button" data-corner="tr">↗ Top right</button><button type="button" data-corner="bl">↙ Bottom left</button><button type="button" data-corner="br">↘ Bottom right</button></fieldset><h3>Today’s plan</h3><ol class="clock-plan">${plan.stages.map(s=>`<li><b>${clock.time(s.start)}–${clock.time(s.end)}</b><span>${s.title}</span><small>${s.end-s.start} min</small></li>`).join('')}</ol></div>`;
document.body.append(root);
let following=true;try{following=localStorage.getItem(`y9w5p-${key}-follow-clock`)!=='off';}catch{}
const follow=document.getElementById('clock-follow');follow.checked=following;follow.onchange=()=>{following=follow.checked;try{localStorage.setItem(`y9w5p-${key}-follow-clock`,following?'on':'off');}catch{}update();};
const show=(id,text)=>{const el=document.getElementById(id);if(el)el.textContent=text;};
const isLocked=()=>{const value=window.ClassroomMode?.locked;return typeof value==='function'?value():Boolean(value);};
function update(){const seconds=clock.seconds(),now=clock.at(seconds),left=Math.max(0,Math.ceil(now.remaining)),display=String(Math.floor(left/60)).padStart(2,'0')+':'+String(left%60).padStart(2,'0');
 show('clock-time',clock.time(Math.floor(seconds/60)));show('clock-bubble-stage',following?(now.phase==='before'?'Starts 08:50':now.phase==='after'?'Save & submit':now.stage.title):'Clock only');show('clock-short',following?(now.phase==='after'?'Finished':display):'—');
 document.getElementById('clock-guidance').hidden=!following;show('clock-stage',now.phase==='before'?'Before the lesson':now.phase==='after'?'Lesson time has ended':now.stage.title);show('clock-countdown',now.phase==='before'?display+' until 08:50':now.phase==='after'?'Save any remaining work':display+' remaining');
 const info=lesson.info();show('clock-current',info.entry?'Enter your name and class to open the lesson.':'Your page: '+lesson.label());const next=plan.stages[plan.stages.indexOf(now.stage)+1];show('clock-next',now.phase==='after'?'You can continue studying independently.':next?'Next: '+next.title+' at '+clock.time(next.start):'Finish: save your PDF and submit to Teams.');
 const steps=document.getElementById('clock-steps');steps.innerHTML=now.phase==='active'?`<h4>Focus now</h4><ul>${now.stage.steps.map(step=>`<li>${step}</li>`).join('')}</ul>`:'';
 const button=document.getElementById('clock-open');button.disabled=info.entry||isLocked();button.textContent=isLocked()?'Teacher controls page changes':'Open '+now.stage.title;
}
document.getElementById('clock-open').onclick=()=>{if(following&&!lesson.info().entry&&!isLocked())lesson.navigate(clock.at(clock.seconds()).stage.id);};document.getElementById('clock-close').onclick=()=>{root.open=false;};
let corner=teacher?'tr':'br';try{const saved=localStorage.getItem(`y9w5p-${key}-clock-corner`);if(['tl','tr','bl','br'].includes(saved))corner=saved;}catch{}
function place(value){corner=value;root.dataset.corner=value;root.style.left='';root.style.top='';root.style.right='';root.style.bottom='';try{localStorage.setItem(`y9w5p-${key}-clock-corner`,value);}catch{}}
place(corner);root.querySelectorAll('[data-corner]').forEach(button=>button.onclick=()=>place(button.dataset.corner));
const handle=root.querySelector('summary');let drag=null,suppressClick=false;
handle.addEventListener('pointerdown',event=>{if(event.button!==0)return;const box=root.getBoundingClientRect();drag={x:event.clientX,y:event.clientY,left:box.left,top:box.top,moved:false};handle.setPointerCapture?.(event.pointerId);});
handle.addEventListener('pointermove',event=>{if(!drag)return;const dx=event.clientX-drag.x,dy=event.clientY-drag.y;if(Math.hypot(dx,dy)>6)drag.moved=true;if(!drag.moved)return;root.open=false;root.style.right='auto';root.style.bottom='auto';root.style.left=Math.max(8,Math.min(innerWidth-120,drag.left+dx))+'px';root.style.top=Math.max(8,Math.min(innerHeight-120,drag.top+dy))+'px';});
function drop(event){if(!drag)return;if(drag.moved){suppressClick=true;place((event.clientY<innerHeight/2?'t':'b')+(event.clientX<innerWidth/2?'l':'r'));}drag=null;}
handle.addEventListener('pointerup',drop);handle.addEventListener('pointercancel',()=>{drag=null;place(corner);});handle.addEventListener('click',event=>{if(suppressClick){event.preventDefault();suppressClick=false;}});
setInterval(update,1000);window.addEventListener('lesson:render',update);document.addEventListener('visibilitychange',update);update();
})();
