'use strict';
/* Year 11-style K/S/U check-ins, adapted to this Year 9 program. */
const Y9_TARGETS={
 K:{name:T('Knowledge','Pengetahuan','知识'),target:T('I can identify suitable input, describe an outer and inner if, and recognise normal, boundary and erroneous tests.','Saya boleh mengenal pasti input sesuai, menerangkan if luar dan dalam, serta mengenali ujian normal, sempadan dan ralat.','我能识别合适的输入，说明外层和内层 if，并辨认正常、边界和错误输入测试。'),hint:T('Check your two Do Now knowledge answers. Can you explain why 0 is valid and what “exactly enough” means?','Semak dua jawapan pengetahuan Mula Sekarang. Bolehkah anda menjelaskan mengapa 0 sah dan maksud “cukup tepat”?','查看两道知识题。你能解释为什么 0 有效，以及“刚好够用”的含义吗？'),pit:T('Look at the input examples, the OR/AND model and the test types you used.','Lihat contoh input, model OR/AND dan jenis ujian yang anda gunakan.','回看输入示例、OR/AND 模型和做过的测试类型。'),next:T('Reread the examples, then say what one value or test type means.','Baca semula contoh, kemudian jelaskan maksud satu nilai atau jenis ujian.','重看示例，再说出一个数值或测试类型的含义。')},
 S:{name:T('Skills','Kemahiran','技能'),target:T('I can choose a condition, calculate Sam’s total time, edit the nested if, run code and improve a message.','Saya boleh memilih syarat, mengira jumlah masa Sam, mengubah if bersarang, menjalankan kod dan memperbaiki mesej.','我能选择条件、计算 Sam 的总时间、修改嵌套 if、运行代码并改进提示。'),hint:T('Check your two Do Now code choices. Later use your saved code and test runs.','Semak dua pilihan kod Mula Sekarang. Kemudian gunakan kod yang disimpan dan larian ujian.','查看两道代码选择题。之后参考保存的代码和测试结果。'),pit:T('Look at the code you changed, the console output and the tests you ran.','Lihat kod yang anda ubah, output konsol dan ujian yang dijalankan.','回看你改过的代码、控制台输出和运行过的测试。'),next:T('Practise one code line, run it, then compare output with your prediction.','Latih satu baris kod, jalankan, kemudian bandingkan output dengan ramalan.','练习一行代码，运行，再比较输出与预测。')},
 U:{name:T('Understanding','Pemahaman','理解'),target:T('I can explain why invalid input must not give an estimate, when the inner decision runs, and why a boundary test matters.','Saya boleh menerangkan mengapa input tidak sah tidak boleh menghasilkan anggaran, bila keputusan dalaman berjalan dan kepentingan ujian sempadan.','我能解释为什么无效输入不能得到估计时间、何时运行内层判断，以及边界测试为什么重要。'),hint:T('Check your two Do Now “why” answers. Can you give a reason rather than repeat a rule?','Semak dua jawapan “mengapa” Mula Sekarang. Bolehkah anda memberi sebab dan bukan sekadar mengulang peraturan?','查看两道“为什么”题。你能说明原因，而不只是重复规则吗？'),pit:T('Compare your explanation with the 12-minute boundary result and an unsuitable-input test.','Bandingkan penjelasan anda dengan hasil sempadan 12 minit dan ujian input tidak sesuai.','用 12 分钟边界结果和一个不合适输入测试检查你的解释。'),next:T('Use one real test to explain why a particular advice route ran.','Gunakan satu ujian sebenar untuk menjelaskan sebab sesuatu laluan nasihat berjalan.','用一个实际测试说明程序为何输出某条建议。')}
};
const Y9_START=[
 ['independent',T('I can do this independently','Saya boleh buat sendiri','我能独立完成')],
 ['supported',T('I can do this with an example or reminder','Saya boleh buat dengan contoh atau peringatan','有示例或提醒时我能完成')],
 ['help',T('I need an explanation and practice','Saya perlukan penerangan dan latihan','我需要讲解和练习')],
 ['unattempted',T('I have not tried this yet','Saya belum cuba lagi','我还没有尝试')]
];
function y9Select(key,choices,selected,label){return `<label class="y11-check-label" for="${key}">${esc(tx(label))}</label><select id="${key}" data-y9-reflect="${key}"><option value="">${esc(tx(T('Choose…','Pilih…','请选择…')))}</option>${choices.map(([id,text])=>`<option value="${id}" ${selected===id?'selected':''}>${esc(tx(text))}</option>`).join('')}</select>`;}
function y9StartText(id){const found=Y9_START.find(([k])=>k===state.answers['ksu_start_'+id]);return found?tx(found[1]):tx(T('Not recorded yet','Belum direkod','尚未记录'));}
function y9Score(id){const c=counts()[id];return c.tried?`${c.right}/${c.tried}`:tx(T('Not attempted yet','Belum dicuba lagi','尚未尝试'));}
function y9TargetCard(id,after){const t=Y9_TARGETS[id],score=y9Score(id),runs=state.runs.filter(r=>['main','focus_decide','focus_combine','focus_calculate'].includes(r.id)).length,tests=Object.keys(state.tests).length;return `<section class="card y11-ksu-card"><span class="y11-ksu-letter">${id}</span><h2>${esc(tx(t.name))}</h2><p class="y11-target"><strong>${esc(tx(t.target))}</strong></p><p>${esc(tx(after?t.pit:t.hint))}</p>${after?`<p class="y11-evidence"><b>${esc(tx(T('My starting point','Titik mula saya','我的起点')))}:</b> ${esc(y9StartText(id))}<br><b>${esc(tx(T('Work available to check','Kerja untuk disemak','可回看的作业')))}:</b> ${esc(id==='S'?tx(T(`${runs} code runs · ${tests} planned tests attempted`,`${runs} larian kod · ${tests} ujian terancang dicuba`,`运行代码 ${runs} 次 · 已尝试 ${tests} 项计划测试`)):tx(T(`Do Now ${score}`,`Mula Sekarang ${score}`,`课前练习 ${score}`)))}</p>`:`<p class="y11-evidence"><b>${esc(tx(T('My first Do Now answers','Jawapan pertama Mula Sekarang saya','我的首次课前练习答案')))}:</b> ${esc(score)}${counts()[id].tried?` ${esc(tx(T('from two checks','daripada dua semakan','来自两题检查')))} `:''}</p>`}${y9Select(after?'ksu_phase_'+id:'ksu_start_'+id,after?[...PHASES.map(([k,v])=>[k,v]),['unattempted',T('Not checked yet','Belum disemak','尚未检查')]]:Y9_START,after?state.phase[id]:state.answers['ksu_start_'+id],after?T('My phase now','Fasa saya sekarang','我现在的阶段'):T('My starting point','Titik mula saya','我的起点'))}</section>`;}
typesPage=function(){const selected=state.answers.ksu_focus;return `${card(T('What are we getting better at?','Apakah yang kita sedang perbaiki?','我们正在改进什么？'),`<p><strong>${esc(tx(T('Learning grows when we practise and work through a useful challenge.','Pembelajaran berkembang apabila kita berlatih dan menghadapi cabaran yang berguna.','练习并克服有价值的困难，才能取得进步。')))}</strong></p><p>${esc(tx(T('Look back at Do Now. Knowledge is what the rules mean; skills are the code steps you can carry out; understanding is why a route gives particular advice.','Lihat semula Mula Sekarang. Pengetahuan ialah maksud peraturan; kemahiran ialah langkah kod yang boleh anda buat; pemahaman ialah sebab laluan memberi nasihat tertentu.','回看课前练习：知识是理解规则含义；技能是完成代码步骤；理解是解释程序为何给出某条建议。')))}</p><p>${esc(tx(T('Choose a starting point for each target below. A correct answer with a reminder is progress, but it is different from doing it independently. These are not grades.','Pilih titik mula bagi setiap sasaran di bawah. Jawapan betul dengan peringatan ialah kemajuan, tetapi berbeza daripada melakukannya sendiri. Ini bukan gred.','为下面每个目标选择起点。借助提醒答对也是进步，但与独立完成不同。这不是成绩。')))}</p>`)}${['K','S','U'].map(id=>y9TargetCard(id,false)).join('')}${card(T('Choose today’s focus','Pilih fokus hari ini','选择今天的重点'),`<p>${esc(tx(T('You may need to improve more than one area. Choose the one to start with. Your Do Now results are a clue; you make the choice.','Anda mungkin perlu memperbaiki lebih daripada satu bidang. Pilih satu untuk dimulakan. Hasil Mula Sekarang memberi petunjuk; anda yang memilih.','你可能需要改进不止一个方面。先选一个开始。课前练习只是线索，由你来决定。')))}</p>${y9Select('ksu_focus',[['K',Y9_TARGETS.K.name],['S',Y9_TARGETS.S.name],['U',Y9_TARGETS.U.name]],selected,T('I will focus on','Saya akan fokus pada','我会重点练习'))}${selected&&Y9_TARGETS[selected]?`<p class="y11-next"><b>${esc(tx(T('What will help me improve','怎样 membantu saya bertambah baik','怎样帮助我进步')))}:</b> ${esc(tx(Y9_TARGETS[selected].next))}</p>`:''}`)}`;};
pitPage=function(){const values=['K','S','U'].map(id=>state.phase[id]).filter(v=>v&&v!=='unattempted');const tally=Object.fromEntries(PHASES.map(([id])=>[id,values.filter(x=>x===id).length]));const most=Math.max(0,...Object.values(tally)),winner=most>=2?PHASES.find(([id])=>tally[id]===most):null;return `${card(T('Where am I now?','Di manakah saya sekarang?','我现在处于什么阶段？'),`<p>${esc(tx(T('Return to the same Knowledge, Skills and Understanding targets you chose earlier. Think about the code and tests you actually tried, then choose a phase for each target. One area can feel different from another.','Kembali kepada sasaran Pengetahuan, Kemahiran dan Pemahaman yang sama. Fikirkan kod dan ujian yang anda benar-benar cuba, kemudian pilih fasa bagi setiap sasaran. Setiap bidang mungkin berbeza.','回到之前的知识、技能和理解目标。想想你实际尝试的代码与测试，再为每个目标选择一个阶段。不同方面可以处于不同阶段。')))}</p><div class="y11-phase-key">${PHASES.map(([id,label,desc])=>`<div><b>${esc(tx(label))}</b><span>${esc(tx(desc))}</span></div>`).join('')}</div><p class="small">${esc(tx(T('This is a confidence check, not a grade. Select Not checked yet if you have not attempted an area.','Ini semakan keyakinan, bukan gred. Pilih Belum disemak jika anda belum mencuba sesuatu bidang.','这是信心检查，不是成绩。若尚未尝试某方面，请选择“尚未检查”。')))}</p>`)}${['K','S','U'].map(id=>y9TargetCard(id,true)).join('')}${values.length?card(T('Your most selected phase','Fasa yang paling banyak dipilih','选择最多的阶段'),`<p>${winner?esc(tx(winner[1])):esc(tx(T('Your phases differ; there is no single majority.','Fasa anda berbeza; tiada satu majoriti.','三个方面的阶段不同，没有单一多数。')))}</p><p class="small">${esc(tx(T('Your choice describes how learning feels in each area. A test result does not decide your phase for you.','Pilihan anda menggambarkan pengalaman belajar dalam setiap bidang. Hasil ujian tidak menentukan fasa anda.','你的选择反映各方面的学习感受。测试结果不会替你决定阶段。')))}</p>`):''}`;};
document.addEventListener('change',event=>{const key=event.target.dataset.y9Reflect;if(!key)return;const value=event.target.value;if(key.startsWith('ksu_phase_'))state.phase[key.slice(-1)]=value;else state.answers[key]=value;save();render();});
const y9BaseReport=report;
report=function(){let html=y9BaseReport();const rows=['K','S','U'].map(id=>`<tr><td>${esc(tx(Y9_TARGETS[id].name))}</td><td>${esc(y9StartText(id))}</td><td>${esc(tx(PHASES.find(([key])=>key===state.phase[id])?.[1]||T('Not checked yet','Belum disemak','尚未检查')))}</td></tr>`).join('');const extra=`<h2>${esc(tx(T('Learning reflection','Refleksi pembelajaran','学习反思')))}</h2><p>${esc(tx(T('Today’s focus','Fokus hari ini','今天的重点')))}: ${esc(tx(Y9_TARGETS[state.answers.ksu_focus]?.name||T('Not selected','Belum dipilih','尚未选择')))}</p><table><thead><tr><th>K/S/U</th><th>${esc(tx(T('Starting point','Titik mula','起点')))}</th><th>${esc(tx(T('Phase now','Fasa sekarang','当前阶段')))}</th></tr></thead><tbody>${rows}</tbody></table>`;const at=html.lastIndexOf('</div>');return at<0?html+extra:html.slice(0,at)+extra+html.slice(at);};
render();
