(function(root){
 'use strict';
 const pair=(en,zh)=>({en,zh});
 const goals={topic:pair('My first Python route','我的第一个 Python 路线程序'),wagba:pair('Use Python Turtle commands to draw, test and improve a route from the Main Entrance to a chosen place.','使用 Python Turtle 指令，画出、测试并改进从学校正门到所选地点的路线。'),knowledge:pair('Know how Turtle commands use coordinates.','知道 Turtle 指令如何使用坐标。'),skills:pair('Write, run and change route commands.','编写、运行并修改路线指令。'),understanding:pair('Explain how commands control the line.','解释指令如何控制画出的线。')};
 const terms=[['Python','Python','A programming language: instructions a computer can run.','一种编程语言：编写计算机可以运行的指令。'],['Turtle','海龟绘图','An on-screen drawing tool controlled by Python.','由 Python 指令控制的屏幕绘图工具。'],['command','指令','One instruction, such as t.goto(80, 0).','一个操作指令，例如 t.goto(80, 0)。'],['sequence','顺序','The order in which our instructions run.','指令运行的先后顺序。'],['coordinate','坐标','A position written as (x, y): horizontal first, vertical second.','用 (x, y) 表示位置：先写横坐标，再写纵坐标。'],['route','路线','The path from a starting place to a destination.','从起点到目的地的路径。'],['test','测试','Run the program and compare the result with your plan.','运行程序，将结果与你的想法比较。'],['debug','调试','Find and fix a problem in the program.','找到并修正程序中的问题。']];
 const stages=[pair('Welcome','开始'),pair('Starter','热身'),pair('Learn commands','学习指令'),pair('Draw my route','画路线'),pair('Test & extend','测试与拓展'),pair('Reflect & save','反思与保存')];
 const cards=[];
 function card(id,stage,title,zh,read,readZh,action,actionZh,extra={}){cards.push({id,stage,title:pair(title,zh),read:pair(read,readZh),action:pair(action,actionZh),...extra});}
 const q=(en,zh,choices,correct=0)=>({prompt:pair(en,zh),choices:choices.map(c=>pair(c[0],c[1])),correct});
 card('mission',0,'Help a new student find the classroom','帮助新同学找到教室','Sam is at the Main Entrance. Sam needs to reach the computer room but does not know the way. The map is ready. You will use Python Turtle to draw a line along its corridors.','Sam 在学校正门，需要去电脑教室，但不知道怎么走。地图已经准备好了。你将用 Python Turtle 沿走廊画出路线。','Look for START and CS Room C1 on the practice map. Then begin.','在练习地图上找到 START（起点）和 CS Room C1（电脑教室），然后开始。',{kind:'mission'});
 card('start',1,'Where does the journey begin?','路线从哪里开始？','This is a practice school, not a map to follow around your own school. Sam starts at the Main Entrance. We will test on screen and stay in class.','这是练习地图，不是你学校的实地导航图。Sam 从学校正门出发。我们留在教室里，在屏幕上测试。','Tap the starting place below.','点击下面的起点。',{map:true,question:q('Where does Sam start?','Sam 从哪里出发？',[['Main Entrance','学校正门'],['Library','图书馆'],['CS Room C1','电脑教室 C1']])});
 card('product',1,'What will your program make?','你的程序会画出什么？','Python Turtle is a digital drawing tool. Your code will make a line appear on the map. You do not need to draw a new school or build a phone app.','Python Turtle 是一种数字绘图工具。你的代码将在地图上画出一条线。你不需要重新画学校，也不需要制作手机应用。','Choose what you will create today.','选择你今天要制作的东西。',{map:true,question:q('My program will draw…','我的程序会画出……',[['A route line on the supplied map','给定地图上的路线'],['A new school building','一座新学校'],['A live GPS phone app','实时 GPS 手机应用']])});
 card('strategy',1,'Learning pitstop: choose your help','学习加油站：选择学习方法','Knowledge: remember a command. Skill: practise using it. Understanding: explain what it does. You can use word help and practise explaining with a partner.','知识：记住指令。技能：练习使用指令。理解：解释指令的作用。你可以查看词语帮助，并与同伴练习解释。','Choose one action you will use when something is new.','选择遇到新内容时你会使用的一种方法。',{choiceOnly:true,question:q('I will…','我会……',[['Read the example and try one line','阅读例子，尝试一行代码'],['Use English + 中文 support','使用英语和中文帮助'],['Predict, run, and compare','预测、运行、比较'],['Explain a command to my partner','向同伴解释一条指令']])});
 function learn(n,title,zh,read,rzh,action,azh,code,extra={}){card('learn'+n,2,title,zh,read,rzh,action,azh,{kind:'code',step:n,workspace:'learn'+n,initial:code,run:true,...extra});}
 learn(1,'Meet your drawing tool','认识绘图工具','The code is ready for you. When you run it, Turtle draws a line. You do not need to type anything yet.','代码已经准备好了。运行后，Turtle 会画出一条线。现在还不用打字。','Tap Run. Watch the blue line appear.','点击 Run（运行），观察出现的蓝线。','t.goto(80, 0)',{question:q('What appeared when you ran the code?','运行后出现了什么？',[['A line','一条线'],['A new map','一张新地图']])});
 learn(2,'Read t.goto','读懂 t.goto','We have named the drawing tool t. The dot joins t to its command. goto means move to a position. Keep the spelling exactly as shown.','我们用 t 代表绘图工具。点号把 t 和指令连接起来。goto 表示移动到一个位置。请保持拼写不变。','Find t.goto in the example. Then run it.','在例子中找到 t.goto，然后运行。','t.goto(80, 0)',{anatomy:true,question:q('Which part is the movement command?','哪一部分是移动指令？',[['goto','goto'],['80','80'],['The comma','逗号']])});
 learn(3,'Type your first instruction','输入第一条指令','Brackets hold the two numbers. A comma separates them. Use English letters, ordinary brackets and an ordinary comma when typing Python.','括号里放两个数字，用逗号分开。输入 Python 时，请使用英文字母、英文括号和英文逗号。','TYPE t.goto(80, 0) in the empty editor. Then RUN.','在空白编辑区输入 t.goto(80, 0)，然后运行。','',{example:'t.goto(80, 0)',change:true,hint:pair('Type t, a dot, goto, an opening bracket, 80, a comma, 0, and a closing bracket.','依次输入 t、点号、goto、左括号、80、逗号、0、右括号。')});
 learn(4,'Change the first number: x','修改第一个数字：x','The first number is x, the horizontal position. Larger positive x values are further right of the centre. It is a position, not extra steps to add.','第一个数字是 x，表示水平位置。正数 x 越大，位置越靠右。它是一个位置，不是额外增加的步数。','CHANGE 80 to 120. Predict the endpoint, then RUN.','把 80 改为 120。预测终点位置，然后运行。','t.goto(80, 0)',{change:true,example:'t.goto(120, 0)',question:q('Where should the endpoint move?','终点应该怎样变化？',[['Further right','更靠右'],['Further up','更靠上']])});
 learn(5,'Change the second number: y','修改第二个数字：y','The second number is y, the vertical position. A positive y is above the centre. Keeping x the same lets us draw a vertical line.','第二个数字是 y，表示垂直位置。正数 y 在中心上方。保持 x 不变，就能画出竖直线。','ADD t.goto(120, 60) on a new line. Then RUN.','另起一行，添加 t.goto(120, 60)，然后运行。','t.goto(120, 0)',{change:true,example:'t.goto(120, 60)',target:[120,60]});
 learn(6,'One command after another','按顺序执行指令','Python follows these lines from top to bottom. Turtle starts each new line from where the previous command left it.','Python 从上到下执行这些代码。每条新指令都从上一条指令结束的位置开始。','ADD t.goto(0, 60) below the other commands. Run all three.','在已有代码下面添加 t.goto(0, 60)，然后运行三条指令。','t.goto(120, 0)\nt.goto(120, 60)',{change:true,example:'t.goto(0, 60)',target:[0,60]});
 learn(7,'Fix one punctuation problem','修正一个标点问题','A small typing mistake can stop Python. This example is missing the comma between its coordinates. Errors are useful clues, not a grade.','一个小小的输入错误就可能让 Python 停下来。这个例子的两个坐标之间缺少逗号。错误信息是提示，不是成绩。','ADD the missing comma. Then RUN the corrected instruction.','补上缺少的逗号，然后运行修正后的指令。','t.goto(80 0)',{change:true,hint:pair('Compare the brackets and comma with t.goto(80, 0).','与 t.goto(80, 0) 比较括号和逗号。')});
 learn(8,'Move without drawing','移动，但不画线','penup() lifts the digital pen. pendown() puts it back on the page. We use this to place Turtle at the start without an unwanted line.','penup() 抬起画笔，pendown() 放下画笔。这样可以把 Turtle 放到起点，而不画出多余的线。','RUN the example. Notice the gap before the blue line.','运行例子，注意蓝线前面没有画线的部分。','t.penup()\nt.goto(-80, 60)\nt.pendown()\nt.goto(80, 60)',{question:q('Why is there no line from the centre to (-80, 60)?','为什么中心到 (-80, 60) 之间没有线？',[['The pen was up','画笔处于抬起状态'],['Turtle could not move','Turtle 无法移动']])});
 learn(9,'Try two points yourself','自己尝试两个点','You can now use goto to join positions. Read x first and y second. Use the command reminder if you need it.','现在你可以用 goto 连接不同位置。先读 x，再读 y。需要时可以查看指令提示。','From the centre, draw to (80, 0), then to (80, 80). Write two lines and RUN.','从中心画到 (80, 0)，再画到 (80, 80)。写两行代码，然后运行。','',{change:true,hint:pair('Each new line uses t.goto(x, y). Replace x and y with the numbers for that point.','每行使用 t.goto(x, y)，把 x 和 y 换成该点的数字。'),target:[80,80]});
 learn(10,'Explain your code','解释你的代码','Reading a command helps you understand your own program. You can point, speak or use the bilingual word help.','读懂指令能帮助你理解自己的程序。你可以指着代码、口头解释，或使用双语词语帮助。','RUN your two-line drawing again. Tell a partner what the second line does.','再次运行两行代码。告诉同伴第二行的作用。','',{workspace:'learn9',question:q('What does t.goto(80, 80) mean?','t.goto(80, 80) 是什么意思？',[['Move to position x = 80, y = 80','移动到 x = 80、y = 80 的位置'],['Move 80 extra steps twice','额外移动两次，每次 80 步']])});
 function route(n,title,zh,read,rzh,action,azh,extra={}){card('map'+n,3,title,zh,read,rzh,action,azh,{kind:'code',step:n,map:true,workspace:'route',initial:'',...extra});}
 route(1,'Your map is ready','地图准备好了','Turtle starts at the Main Entrance: (0, -200). The setup lifts the pen, moves to the entrance and lowers the pen for you.','Turtle 从学校正门 (0, -200) 出发。准备代码已经自动抬起画笔、移动到正门并放下画笔。','Tap RUN. Find Turtle at START. You do not need to add code yet.','点击运行，在 START 找到 Turtle。现在还不需要添加代码。',{run:true});
 route(2,'Choose where to finish','选择目的地','Choose one permitted place on the map. You do not have to visit every room. The computer room is the standard challenge.','选择地图上一个允许到达的地点，不需要经过所有房间。电脑教室是标准任务。','CHOOSE your destination below. Find its name on the map. We will mark it FINISH on the next card.','在下面选择目的地，找到地图上对应的名称。下一张卡片会把它标记为 FINISH（终点）。',{kind:'destination'});
 route(3,'Choose your first point','选择第一个点','The grid numbers tell you where a point is. x comes first; y comes second. Negative y is below the centre.','网格上的数字表示点的位置。先写 x，再写 y。负数 y 在中心下方。','TAP the corridor point (0, -100). Read its x and y numbers.','点击走廊上的点 (0, -100)，读出它的 x 和 y。',{kind:'point',pick:true,target:[0,-100]});
 route(4,'Draw the first section','画出第一段路线','Your pen is already down at the Main Entrance. This command draws from there to the next point in the corridor.','画笔已经在学校正门放下。这条指令会从正门画到走廊上的下一个点。','TYPE t.goto(0, -100), then RUN.','输入 t.goto(0, -100)，然后运行。',{run:true,example:'t.goto(0, -100)',target:[0,-100]});
 route(5,'Choose the next point','选择下一个点','A straight line joins one point to the next. Choose a point inside the white corridor. Do not jump across a wall.','两个点之间会连成直线。请在白色走廊里选点，不要让线穿过墙。','SELECT a point on the way to your destination. Use Insert this point, or type its goto command. Then RUN.','选择通往目的地的一个点。点击“插入这个点”，或输入它的 goto 指令，然后运行。',{run:true,picker:true});
 route(6,'Follow the corridor','沿着走廊前进','To go around a corner, first reach the corner, then choose the next point. Turtle does not find a route for you.','要绕过转角，先到达转角，再选择下一个点。Turtle 不会自动寻找路线。','ADD your next safe point and RUN. If you have reached Reception, check that route instead.','添加下一个安全的点并运行。如果已到达 Reception（接待处），请检查已经完成的路线。',{run:true,picker:true});
 route(7,'Continue towards your finish','继续前往终点','Check where your last command ends. Start thinking from that position, not from the entrance again.','检查最后一条指令在哪里结束。从那个位置继续思考，不要重新从正门开始。','ADD another point if needed. If your route is complete, RUN it again and check the corners.','需要时再添加一个点。如果路线已经完成，再次运行并检查转角。',{run:true,picker:true});
 route(8,'Reach your chosen place','到达所选地点','The FINISH marker shows the destination you chose. Stop the route at that marker. You do not need extra lines after reaching it.','FINISH 标记显示你选择的目的地。路线应在该标记处结束，到达后不需要多画线。','Finish your route, then RUN. Compare the endpoint with FINISH.','完成路线后运行，比较线的终点与 FINISH 标记。',{run:true,picker:true});
 route(9,'Test the whole line','测试整条路线','A program can run without an error but still draw the wrong route. Check the drawing as well as the code.','程序没有报错，也可能画出错误路线。除了检查代码，也要检查画出的线。','RUN. Check START, FINISH, corridors and STAFF ONLY. Change one point if needed.','运行。检查起点、终点、走廊和 STAFF ONLY 区域。需要时修改一个点。',{run:true,picker:true,routeCheck:true,choiceOnly:true,question:q('After checking my route…','检查路线后……',[['It follows the route I intended','它符合我想要的路线'],['I changed a point and tested again','我修改了一个点并重新测试'],['I need help with one section','其中一段还需要帮助']])});
 route(10,'Show your route','展示你的路线','Your code and drawing are saved as lesson evidence when you run. You do not need a device screenshot.','运行时，你的代码和图形会保存为学习证据，不需要自己截屏。','RUN your latest code. Choose one command you can explain to a partner.','运行最新代码，选择一条你能向同伴解释的指令。',{run:true,explain:true});
 card('peer',4,'Read, predict, run, explain','阅读、预测、运行、解释','Take turns. One partner points to a goto command and explains its coordinates. The other predicts the line. Run and compare, then swap. Stay seated.','轮流进行。一人指出一条 goto 指令并解释坐标，另一人预测画出的线。运行并比较，然后交换角色。请留在座位上。','Choose a line below and explain it aloud. Then record how the check went.','选择下面一行并口头解释，然后记录检查结果。',{kind:'peer',workspace:'route',choiceOnly:true,question:q('Our check showed…','我们的检查结果是……',[['We could explain where the command moves Turtle','我们能解释指令把 Turtle 移到哪里'],['We found a command to check again','我们发现一条需要再次检查的指令'],['I used the example or teacher help to explain','我借助例子或老师帮助进行解释']])});
 card('extension',4,'Choose an extra challenge','选择拓展任务','These challenges are optional. Your map route stays safe in its own workspace. You can try one challenge, or return and try another.','这些任务是选做的。你的地图路线保存在独立工作区，不会被覆盖。你可以做一个，也可以返回再做另一个。','Choose a challenge, or continue to reflection.','选择一个拓展任务，或继续进行反思。',{kind:'extension'});
 card('reflect',5,'Learning pitstop: where am I now?','学习加油站：我现在的状态','Choose how this coding feels today. This is not a grade. Your teacher will use it to decide what help or challenge comes next.','选择你今天编程时的感受。这不是成绩。老师会据此安排接下来的帮助或挑战。','Choose your learning phase and one next action.','选择你的学习状态，以及下一步行动。',{kind:'reflect',choiceOnly:true,question:q('Right now I am…','现在我处于……',[['New learning: this is new, but I can try the next step','新学习：内容是新的，但我能尝试下一步'],['Consolidating: practice is helping me improve','巩固：练习正在帮助我进步'],['Treading water: I am ready for more challenge','原地踏步：我准备好接受更多挑战'],['Drowning: I need help to move forward','感到困难：我需要帮助才能继续']])});
 card('plenary1',5,'Remember one command','记住一条指令','Think about the command that moves Turtle to a position.','想一想，哪条指令把 Turtle 移动到一个位置。','Choose the correct Python instruction.','选择正确的 Python 指令。',{question:q('Which instruction moves to x = 50, y = 20?','哪条指令移动到 x = 50、y = 20？',[['t.goto(50, 20)','t.goto(50, 20)'],['t.goto(50 20)','t.goto(50 20)'],['Go near the classroom','走到教室附近']])});
 card('plenary2',5,'Predict a change','预测一个变化','Compare t.goto(50, 20) with t.goto(50, 80). Only the second number changed.','比较 t.goto(50, 20) 和 t.goto(50, 80)。只有第二个数字发生了变化。','Where is the new endpoint?','新的终点在哪里？',{question:q('The new endpoint is…','新的终点……',[['Higher, at the same x position','更高，x 位置不变'],['Further right, at the same y position','更靠右，y 位置不变']])});
 card('plenary3',5,'Explain a route problem','解释一个路线问题','Turtle draws straight lines between points. It does not know where the walls are.','Turtle 在点与点之间画直线。它不知道墙在哪里。','Choose a useful way to fix a line that crosses a wall.','选择修正穿墙路线的有效方法。',{question:q('I should…','我应该……',[['Add or move a point at the corridor corner','在走廊转角添加或移动一个点'],['Run the unchanged code until Turtle finds a route','不断运行相同代码，直到 Turtle 自己找到路线'],['Only change the line colour','只改变线的颜色']])});
 card('submit',5,'Save your learning','保存你的学习成果','Your report includes your answers, code, drawing and reflections. No device screenshots are needed. Save your PDF and Python file, then submit both to Teams: Week 2 Practical.','报告包含你的答案、代码、图形和反思，不需要设备截图。保存 PDF 和 Python 文件，然后一起提交到 Teams 的 Week 2 Practical 作业。','Review your evidence, prepare your files, then follow the instructions for your device.','检查学习证据，准备文件，然后按照适合你设备的步骤保存。',{kind:'submit'});
 const extensions=[
  {id:'ext1',title:pair('1 · Practise a rectangle','1 · 练习画长方形'),read:pair('Use goto to join (120, 0), (120, 60), (0, 60), then (0, 0). Complete the missing lines.','用 goto 连接 (120, 0)、(120, 60)、(0, 60)，最后回到 (0, 0)。补全缺少的代码。'),initial:'t.goto(120, 0)\n# Add the next three points'},
  {id:'ext2',title:pair('2 · Explore forward and right','2 · 探索 forward 和 right'),read:pair('forward(80) moves 80 steps in the direction Turtle faces. right(90) turns it clockwise. Run the first side, then add three more sides to make a square.','forward(80) 沿 Turtle 面向的方向前进 80 步。right(90) 顺时针转 90 度。运行第一条边，再添加三条边画出正方形。'),initial:'t.forward(80)\nt.right(90)\n# Add three more sides'},
  {id:'ext3',title:pair('3 · Create a direction sign','3 · 设计方向标志'),read:pair('Make an arrow or a sign that shows a direction. Choose your points. Use penup and pendown if you need a gap. Explain which commands make the direction clear.','设计一个箭头或方向标志。自己选择坐标，需要断开线条时使用 penup 和 pendown。解释哪些指令让方向更清楚。'),initial:'# Create your direction sign here'}
 ];
 const destinations={c1:{label:pair('CS Room C1','电脑教室 C1'),point:[200,100]},library:{label:pair('Library','图书馆'),point:[-200,100]},reception:{label:pair('Reception','接待处'),point:[-200,-100]}};
 function normaliseCode(code){return code.replace(/[（]/g,'(').replace(/[）]/g,')').replace(/[，]/g,',').replace(/[．]/g,'.').replace(/[−–—]/g,'-').replace(/[“”]/g,'"').replace(/[‘’]/g,"'").replace(/\u00a0/g,' ');}
 function inCorridor(x,y){return (x>=-35&&x<=35&&y>=-225&&y<=135)||(x>=-235&&x<=235&&y>=65&&y<=135)||(x>=-235&&x<=35&&y>=-135&&y<=-65);}
 function checkRoute(draws,destination){const seg=draws.filter(d=>d.from&&d.pen&&Math.hypot(d.to[0]-d.from[0],d.to[1]-d.from[1])>0.01);let safe=seg.length>0,continuous=true;for(let i=0;i<seg.length;i++){const d=seg[i],n=Math.max(1,Math.ceil(Math.hypot(d.to[0]-d.from[0],d.to[1]-d.from[1])/4));for(let k=0;k<=n;k++)if(!inCorridor(d.from[0]+(d.to[0]-d.from[0])*k/n,d.from[1]+(d.to[1]-d.from[1])*k/n))safe=false;if(i&&Math.hypot(d.from[0]-seg[i-1].to[0],d.from[1]-seg[i-1].to[1])>2)continuous=false;}const first=seg[0]?.from,last=seg[seg.length-1]?.to,end=destinations[destination||'c1'].point;return {hasLine:!!seg.length,start:!!first&&Math.hypot(first[0],first[1]+200)<16,finish:!!last&&Math.hypot(last[0]-end[0],last[1]-end[1])<16,safe,continuous};}
 cards.find(c=>c.id==='peer').map=true;
 // Stable varied answer positions; never shuffle a saved student's answers on render.
 let quizNumber=0;for(const c of cards){if(c.question&&!c.choiceOnly){const q=c.question,n=q.choices.length,shift=(++quizNumber)%n;q.choices=q.choices.slice(shift).concat(q.choices.slice(0,shift));q.correct=(q.correct-shift+n)%n;}}
 const api={pair,goals,terms,stages,cards,extensions,destinations,normaliseCode,inCorridor,checkRoute};root.Lesson=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
