(() => {
  'use strict';
  const $ = s => document.querySelector(s);
  const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const L = window.LESSON;
  if (!L) { $('#notice').hidden=false; $('#notice').textContent='Lesson content did not load. Refresh or contact your teacher.'; return; }
  const stages=L.stages, order=stages.map(s=>s.id), storageKey='y10-live-for-notebook-v1';
  let activeStorageKey=storageKey;
  let notebook={version:1,name:'',class:'Year 10',stage:'ready',work:{},createdAt:new Date().toISOString()};
  try { const raw=JSON.parse(localStorage.getItem(storageKey)); if(raw?.version===1 && raw.work && typeof raw.work==='object') notebook=raw; } catch {}
  let role='entry', localOnly=false, room=null, learner=null, editor=null, demoEditor=null, runner=null, modelRunner=null;
  let guideIndex=0, current='ready', pollTimer=null, saveTimer=null, teacherTimer=null, selectedStudent=null, teacherStudents=[];
  let saving=false, polling=false, running=false, backendReady=false, extensionId=notebook.work?.extension?.extensionId||L.extensions?.[0]?.id, imageDBPromise=null, demoRun=null;
  let sessionVersion=0, shareSafe=false, demoVersion=0, demoRunning=false,activePupilRun=null;
  let responseStage=null, detailStage=null, responseView='overview',responsePreview='auto';
  const feedbackDrafts=new Map(), feedbackSending=new Set();
  const dirty=new Set(), clock={started:Date.now()}, getStage=id=>stages.find(s=>s.id===id);
  for(const id of notebook.unsynced||[])if(order.includes(id))dirty.add(id);
  function work(id=current) { if (!notebook.work[id]) notebook.work[id]={answers:{},code:getStage(id)?.code||'',inputs:(getStage(id)?.inputs||[]).join('\n'),runs:[],images:[],updatedAt:new Date().toISOString()}; return notebook.work[id]; }
  function notice(text, kind='') { const n=$('#notice'); n.hidden=!text; n.className='notice '+kind; n.textContent=text; }
  function localSave() { notebook.stage=current;notebook.unsynced=[...dirty];try {localStorage.setItem(activeStorageKey,JSON.stringify(notebook)); $('#save-status').textContent=role==='teacher'?'Your separate teacher rehearsal · saved on this device':localOnly||role==='preview'?'Saved on this device':dirty.size?'Saved on device · waiting to sync':'Saved on this device';} catch { $('#save-status').textContent='Device storage is full or blocked · export a backup now'; notice('Your draft is still open here, but device storage could not save it. Download a notebook backup or export PDF before closing this page.','error'); } }
  function changed(id=current) { work(id).updatedAt=new Date().toISOString(); dirty.add(id); localSave(); clearTimeout(saveTimer); saveTimer=setTimeout(flush,1400); }
  function permitted(id) { return localOnly||role==='preview'||role==='teacher'||id==='ready'||Boolean(learner?.status==='admitted' && (room?.released_stages?.includes(id)||learner?.unlocked_stages?.includes(id))); }
  function canEdit(id=current) { return role==='teacher'||localOnly||role==='preview'||Boolean(role==='student'&&learner?.status==='admitted'&&!room?.ended&&room?.mode==='work'&&(room.released_stages?.includes(id)||learner.unlocked_stages?.includes(id))); }
  function snapshotEditor(){if(editor){work().code=editor.getValue();extensionSnapshot();}localSave();}
  // A navigation nonce travels in an empty demonstration's output. The existing
  // teacher-only RPC validates/persists this envelope unchanged; no database or
  // access-policy change is needed. It is never Python output or pupil evidence.
  // Unlike stage equality alone, a new nonce can recall pupils to the same page.
  function classPageCommand(state){const d=state?.demo;return d?.code===''&&/^y10-class-page-v1:[0-9a-f-]{36}$/i.test(d.output||'')?d.output:null;}
  function bringStudentToClassStep(){
    if(role!=='student'||localOnly||learner?.status!=='admitted'||!room||room.ended||!permitted(room.stage))return false;
    snapshotEditor();if(running){if(activePupilRun)activePupilRun.cancelledForPage=true;runner?.stop();}
    if(current!==room.stage)renderStage(room.stage);
    $('#main').focus({preventScroll:true});$('#route').scrollIntoView({block:'start',behavior:'auto'});
    return true;
  }
  function saveFeedbackDraft(){const field=$('#teacher-feedback'),id=$('#student-detail')?.dataset.student;if(field&&id)feedbackDrafts.set(id,field.value);}
  function closePrivatePanel(){saveFeedbackDraft();const panel=$('#teacher-board');if(panel?.open)panel.close();if(panel)panel.hidden=true;document.body.classList.remove('responses-open');editor?.refresh();}
  function openPrivatePanel(){if(role!=='teacher'||shareSafe)return;const panel=$('#teacher-board');panel.hidden=false;panel.dataset.view=responseView;document.body.classList.add('responses-open');renderRoster();if(responseView==='individual')renderDetail(false);editor?.refresh();}
  function changeSession(){snapshotEditor();sessionVersion++;demoVersion++;clearTimeout(saveTimer);clearTimeout(teacherTimer);clearInterval(pollTimer);runner?.stop();modelRunner?.stop();closePrivatePanel();feedbackDrafts.clear();feedbackSending.clear();responseStage=detailStage=null;responseView='overview';editor=null;learner=null;dirty.clear();saving=false;polling=false;running=false;demoRunning=false;activePupilRun=null;shareSafe=false;document.body.classList.remove('share-safe');}
  function restorePupilNotebook(){try{const saved=JSON.parse(localStorage.getItem(storageKey));notebook=saved?.version===1&&saved.work?saved:{version:1,name:'',class:'Year 10',stage:'ready',work:{},createdAt:new Date().toISOString()};}catch{notebook={version:1,name:'',class:'Year 10',stage:'ready',work:{},createdAt:new Date().toISOString()};}activeStorageKey=storageKey;current=order.includes(notebook.stage)?notebook.stage:'ready';extensionId=notebook.work?.extension?.extensionId||L.extensions[0].id;dirty.clear();for(const id of notebook.unsynced||[])if(order.includes(id))dirty.add(id);}
  function teacherNotebook(){activeStorageKey=storageKey+'-teacher';try{const saved=JSON.parse(localStorage.getItem(activeStorageKey));notebook=saved?.version===1&&saved.work?saved:null;}catch{notebook=null;}if(!notebook)notebook={version:1,name:'Teacher rehearsal',class:'Year 10',stage:'ready',work:{},createdAt:new Date().toISOString()};delete notebook.feedback;extensionId=notebook.work?.extension?.extensionId||L.extensions[0].id;}
  async function flush() {
    if(saving||role!=='student'||localOnly||!backendReady||!learner||learner.status!=='admitted') return;
    saving=true;let stageFailure=false;const version=sessionVersion;
    try {
      for(const id of [...dirty]) {
        if(!canEdit(id)) continue;
        const snapshot=JSON.stringify(work(id)); const w=JSON.parse(snapshot);
        $('#save-status').textContent='Saving to your teacher…';
        const clip=(v,n)=>String(v||'').length>n?String(v).slice(0,n-70)+'\n[Cloud preview shortened. Full evidence remains in the PDF.]':String(v||'');
        const runs=(w.runs||[]).slice(-8).map(r=>({...r,code:clip(r.code,20000),stdout:clip(r.stdout,8000),output:clip(r.output,8000),stderr:clip(r.stderr,8000),error:clip(r.error,2000)}));
        try{const saved=await LiveCloud.studentSave({stage:id,answers:{...w.answers,_inputs:w.inputs,_extension:w.extensionId||null},code:w.code||'',runs,submitted:id==='submit'&&w.answers.finalSubmitted==='yes'});
          if(version!==sessionVersion||role!=='student')return;
          learner=saved;
          if(snapshot===JSON.stringify(work(id))) dirty.delete(id);
        }catch(e){if(version!==sessionVersion)return;stageFailure=true;notice((getStage(id)?.title||id)+': '+(e.userMessage||e.message)+'. This draft remains on your device; other released stages can still save.','error');}
      }
      localSave();$('#save-status').textContent=stageFailure?'Some work not synced · device draft retained':dirty.size?'Draft saved locally · waiting for an open work stage':'Saved to teacher';
    } catch(e) {if(version!==sessionVersion)return;$('#save-status').textContent='Not synced · draft remains on this device'; notice(e.userMessage||e.message||'The connection is unavailable. Your draft is safe on this device.','error'); }
    finally {if(version===sessionVersion)saving=false;}
  }
  function fieldsHTML(fields=[],id=current) {
    const values=work(id).answers;
    return fields.map(f=>{const fid='answer-'+f.id; const val=values[f.id]??''; const type=f.type||'textarea'; let control='';
      if(type==='select') { const opts=f.options||[]; control=`<select id="${esc(fid)}" data-answer="${esc(f.id)}"><option value="">Choose when ready…</option>${opts.map(o=>typeof o==='string'?`<option ${val===o?'selected':''}>${esc(o)}</option>`:`<option value="${esc(o.value)}" ${String(val)===String(o.value)?'selected':''}>${esc(o.label)}</option>`).join('')}</select>`; }
      else if(type==='text'||type==='number') control=`<input id="${esc(fid)}" data-answer="${esc(f.id)}" type="${type}" value="${esc(val)}" placeholder="${esc(f.placeholder||'')}">`;
      else control=`<textarea id="${esc(fid)}" data-answer="${esc(f.id)}" rows="${f.rows||3}" placeholder="${esc(f.placeholder||'')}">${esc(val)}</textarea>`;
      return `<div class="field"><label for="${esc(fid)}">${esc(f.label)}</label>${f.help?`<p class="small">${esc(f.help)}</p>`:''}${control}</div>`;
    }).join('');
  }
  function ksuReflection(before=false) {
    const phase=[['new','New learning · this is new and I am making progress'],['consolidating','Consolidating · I am strengthening what I know'],['treading','Treading water · I need a further challenge'],['help','Drowning / needing help · I need a smaller next step']];
    return L.ksu.map(k=>`<section class="reflection-item"><h3>${esc(k.kind)} · ${esc(k.title)}</h3><p>${esc(k.can)}</p><p class="small">Evidence: ${esc(k.evidence||'Use your prediction, code, test or explanation.')}</p>${fieldsHTML([{id:k.id+'-evidence',type:'select',label:before?'What can you currently show?':'What can you now show?',options:[{value:'notyet',label:'Not yet / not sure'},{value:'support',label:'I can show this with a content example or scaffold'},{value:'independent',label:'I can show this independently'}]},...(before?[]:[{id:k.id+'-phase',type:'select',label:'How does this part of the learning feel?',options:phase.map(([value,label])=>({value,label}))}])])}</section>`).join('')+(before?fieldsHTML([{id:'learning-focus',type:'select',label:'Which type of learning is your priority?',options:[{value:'knowledge',label:'Knowledge · remember and distinguish the rules'},{value:'skills',label:'Skills · practise applying the rules in code'},{value:'understanding',label:'Understanding · explain why my code works'}]},{id:'learning-target',type:'text',label:'My next small target',placeholder:'I want to get better at…'}]):fieldsHTML([{id:'pit-evidence',type:'textarea',label:'Point to one piece of evidence',placeholder:'In my test with…, the output… shows…'},{id:'pit-next',type:'text',label:'My next step',placeholder:'I will practise… / Please help me with line…'}]));
  }
  function ideHTML(s, label='Your Python workspace') {
    return `<section class="ide" aria-label="${esc(label)}"><h3>${esc(label)}</h3><p class="small">Real Python runs on this device. Line numbers are guides, not part of your program. Inputs are entered below before Run.</p><div class="editor-shell"><textarea id="code-editor" aria-label="Python source code">${esc(work().code)}</textarea></div><div class="ide-actions"><button id="run-code">Run Python</button><button id="stop-code" class="quiet" disabled>Stop</button><button id="download-code" class="quiet">Download .py</button><button id="reset-code" class="quiet">Restore starting code</button><label class="small" for="code-size">Code size</label><select id="code-size" style="width:auto;margin:0"><option value="18">18</option><option value="20">20</option><option value="22">22</option><option value="24">24</option></select><span id="runtime-status" role="status">Python loads when you run</span></div><label for="run-inputs">Inputs for this run — one value per line, in the order input() asks</label><textarea id="run-inputs" class="inputs" rows="4">${esc(work().inputs)}</textarea><p class="small">${esc(s.inputHelp||'If your code asks for the number of runners first, enter that count on the first line, then one lap value for each runner. Example: 3, then 2, 5, 4, each on its own line.')}</p><h3>Actual output</h3><pre id="run-output" class="output" aria-live="polite">${esc(work().runs.at(-1)?.stdout||work().runs.at(-1)?.output||'Run your code to see its actual output.')}</pre><p id="run-error" class="error-hint"></p><p id="run-check" class="progress-text"></p>${s.tests?.length?`<details><summary>Known tests — compare your actual output</summary>${s.tests.map((t,i)=>`<section><h3>${esc(t.label||t.id||'Test '+(i+1))}</h3><p>Inputs: ${esc((t.inputs||[]).join(', '))}</p><pre>${esc(t.expected)}</pre><button class="quiet" data-test="${i}">Use these inputs</button></section>`).join('')}</details>`:''}<p class="small">${work().runs.length} recorded run(s). Run evidence keeps the code used for that run, even if you edit afterwards. Successful execution alone does not prove the answer meets the task.</p></section>`;
  }
  function extensionHTML() {
    const ext=L.extensions.find(e=>e.id===extensionId)||L.extensions[0];
    const w=work(); w.extensionId=ext.id;
    if(!w.extensionWork)w.extensionWork={};
    if(!w.extensionWork[ext.id])w.extensionWork[ext.id]={code:ext.scaffold||'# Write your program here\n',inputs:(ext.inputs||[]).join('\n'),runs:[]};
    const ew=w.extensionWork[ext.id]; w.code=ew.code;w.inputs=ew.inputs;w.runs=ew.runs;
    return `<label for="extension-choice">Choose one challenge. You do not need to finish all ten today.</label><select id="extension-choice" class="extension-choice">${L.extensions.map((e,i)=>`<option value="${esc(e.id)}" ${e.id===ext.id?'selected':''}>${i+1}. ${esc(e.title)}</option>`).join('')}</select><h3>${esc(ext.title)}</h3><p>${esc(ext.scenario)}</p><ol class="steps">${(ext.requirements||[]).map(r=>`<li>${esc(r)}</li>`).join('')}</ol><h3>Example test</h3><p>Inputs: ${esc((ext.inputs||[]).join(', '))}</p><pre>${esc(ext.expected)}</pre><details><summary>One hint if I need it</summary><p>${esc(ext.hint)}</p></details>${ideHTML({inputHelp:ext.inputHelp||'Use the example input values, one per line. Change them when you test a different case.',tests:ext.tests||[]},'Your extension program')}${fieldsHTML([{id:'extension-explain-'+ext.id,type:'textarea',label:'Explain one choice or correction',placeholder:'I chose… because… My test shows…'}])}`;
  }
  function guideHTML(s) { if(!s.guidedSteps?.length)return '';return `<details class="manual-guide"><summary>Read the model one step at a time</summary><div id="guide-lines"></div><div class="guide-controls"><button id="guide-back" class="quiet">Previous step</button><button id="guide-next" class="quiet">Next step</button></div><p id="guide-description" class="guide-caption"></p><pre id="guide-values"></pre><p class="small">You control the pointer. This is a prepared explanation of the model, not a debugger for your own program.</p></details>`; }
  function guideUpdate(s) { const g=s.guidedSteps; if(!g?.length||!$('#guide-lines'))return;guideIndex=Math.max(0,Math.min(g.length-1,guideIndex));const v=g[guideIndex]; const code=s.modelCode||L.models?.total||s.code||'';$('#guide-lines').innerHTML=`<ol class="line-reader">${code.split('\n').map((l,i)=>`<li class="${i+1===v.line?'current':''}"><span class="ln">${i+1}</span><code>${esc(l||' ')}</code></li>`).join('')}</ol>`;$('#guide-description').textContent=v.explanation;$('#guide-values').textContent=typeof v.values==='string'?v.values:JSON.stringify(v.values,null,2);$('#guide-back').disabled=guideIndex===0;$('#guide-next').disabled=guideIndex===g.length-1; }
  function imageHTML() { return `<details><summary>Add optional screenshot evidence</summary><p class="small">Code and actual outputs are already recorded. You can also attach complete PNG, JPEG or WebP screenshots (maximum 3 MB each). Images stay on this device and are included in your PDF, not sent to the live board.</p><label for="evidence-upload">Choose screenshot evidence</label><input id="evidence-upload" type="file" accept="image/png,image/jpeg,image/webp" multiple><div id="image-evidence" class="image-evidence"></div></details>`; }
  function routeRender(){
    $('#step-position').textContent=`Step ${order.indexOf(current)+1} of ${order.length} · ${getStage(current)?.title||current}`;
    $('#route-list').innerHTML=stages.map((s,i)=>{const available=permitted(s.id),attempted=Boolean(notebook.work[s.id]?.updatedAt);return `<li><button data-stage="${esc(s.id)}" ${!available?'disabled':''} ${current===s.id?'aria-current="step"':''}><span>${i+1}. ${esc(s.title)}</span><span class="step-state">${current===s.id?'You are here':!available?'Not released':attempted?'Visited':'Available'}</span></button></li>`;}).join('');
    const pi=order.indexOf(current)-1;$('#previous').disabled=pi<0||!permitted(order[pi]);
    const ni=order.indexOf(current)+1;$('#next').disabled=ni>=order.length||!permitted(order[ni]);
    $('#next').textContent=role==='teacher'?'Preview next step':ni>=order.length?'End of lesson':!permitted(order[ni])?'Next step · not released':'Next step';
    const classStep=role==='student'&&!localOnly&&room&&!room.ended&&current!==room.stage;
    $('#class-location').hidden=!classStep;$('#class-step-label').textContent=classStep?`The class is on ${getStage(room.stage)?.title||room.stage}. Your current work is saved.`:'';
    $('#join-current').disabled=!classStep||!permitted(room?.stage)||running;
    updateTeacherControls();
  }
  function renderStage(id=current) {
    if(!permitted(id)){notice('Your teacher has not released this stage yet. Your earlier work is saved.');return;}
    clearTimeout(teacherTimer);demoVersion++;if(role==='teacher'&&$('#demo-auto'))$('#demo-auto').checked=false;
    if(editor){work().code=editor.getValue();extensionSnapshot();editor=null;}
    current=id;notebook.stage=id;work();localSave();routeRender();const s=getStage(id);guideIndex=0;$('#lesson-outline').open=false;
    const main=$('#main');main.innerHTML=`<p class="eyebrow">${esc(s.minutes||'')} min · ${esc(s.title)}</p><h2>${esc(s.heading||s.title)}</h2>${s.html||''}${id==='types'?ksuReflection(true):id==='pit'?ksuReflection(false):''}${id==='extension'?extensionHTML():''}${s.code!==undefined&&id!=='extension'?ideHTML(s):''}${guideHTML(s)}${fieldsHTML(['types','pit'].includes(id)?[]:(s.fields||[]))}${id==='submit'?'<button id="submit-notebook">Send completion to teacher</button><p class="small">This marks your in-app notebook complete. Export the PDF and Turn in your assignment separately in Teams.</p>'+`<h3>Study references</h3>${(L.sources||[]).map(r=>`<p>${r.url?`<a href="${esc(r.url)}" target="_blank" rel="noopener noreferrer">${esc(r.title||r.label||'Reference')}</a>`:esc(r.title||r.label||'Reference')}${r.note?'<br>'+esc(r.note):''}</p>`).join('')}`:''}${['task1','task2','extension','submit'].includes(id)?imageHTML():''}<div id="private-feedback"></div>`;
    if($('#code-editor')) {
      editor=CodeMirror.fromTextArea($('#code-editor'),{mode:'python',lineNumbers:true,indentUnit:4,tabSize:4,matchBrackets:true,styleActiveLine:true,viewportMargin:Infinity,readOnly:!canEdit(),extraKeys:{Tab:cm=>{if(!canEdit())return;if(cm.somethingSelected())cm.indentSelection('add');else cm.replaceSelection('    ');},'Shift-Tab':cm=>canEdit()&&cm.indentSelection('subtract')}});
      editor.getInputField().setAttribute('aria-label','Python source code');
      editor.on('change',()=>{work().code=editor.getValue();extensionSnapshot();changed();});
    }
    main.querySelectorAll('[data-answer]').forEach(el=>{el.disabled=!canEdit();el.addEventListener('input',()=>{work().answers[el.dataset.answer]=el.value;changed();});});
    $('#run-inputs')?.addEventListener('input',e=>{work().inputs=e.target.value;extensionSnapshot();changed();});
    $('#run-code')?.addEventListener('click',runCode); $('#stop-code')?.addEventListener('click',()=>runner?.stop());
    $('#download-code')?.addEventListener('click',()=>download(`${safeName(notebook.name)}_${current}.py`,work().code,'text/x-python'));
    $('#reset-code')?.addEventListener('click',()=>{if(!canEdit())return;if(confirm('Restore the starting code? Your recorded earlier runs remain in the notebook. Download your current program first if you want a separate copy.')){const ext=L.extensions.find(e=>e.id===extensionId);editor.setValue(current==='extension'?(ext?.scaffold||'# Write your program here\n'):(s.code||''));}});
    $('#code-size')?.addEventListener('change',e=>{editor.getWrapperElement().style.fontSize=e.target.value+'px';editor.refresh();});
    main.querySelectorAll('[data-test]').forEach(b=>b.addEventListener('click',()=>{if(!canEdit())return;const tests=id==='extension'?L.extensions.find(e=>e.id===extensionId)?.tests:s.tests;const t=tests?.[Number(b.dataset.test)];if(!t)return;work().inputs=t.inputs.join('\n');$('#run-inputs').value=work().inputs;extensionSnapshot();changed();}));
    $('#extension-choice')?.addEventListener('change',e=>{extensionSnapshot();extensionId=e.target.value;changed();renderStage('extension');});
    $('#guide-back')?.addEventListener('click',()=>{guideIndex--;guideUpdate(s);});$('#guide-next')?.addEventListener('click',()=>{guideIndex++;guideUpdate(s);});guideUpdate(s);
    $('#evidence-upload')?.addEventListener('change',addImages);showImages();feedbackRender();demoRender();applyEditing();
    $('#submit-notebook')?.addEventListener('click',async()=>{if(!canEdit()||role==='teacher')return;const version=sessionVersion;work().answers.finalSubmitted='yes';changed();await flush();if(version!==sessionVersion)return;notice(localOnly?'Completion recorded on this device. Export your PDF and submit through Teams.':dirty.has('submit')?'Completion is saved locally and waiting to sync. Keep this page open.':'Completion reached your teacher. Now export and submit your PDF through Teams.',dirty.has('submit')?'':'success');});
    if(['types','pit'].includes(id)){const summary=document.createElement('p');summary.id='reflection-summary';summary.className='coach';main.append(summary);const update=()=>{const answers=work(id).answers,values=L.ksu.map(k=>answers[k.id+'-evidence']);summary.textContent=`Your self-reported evidence: ${values.filter(v=>v==='independent').length}/6 independent; ${values.filter(v=>v==='support').length}/6 with an example or scaffold; ${values.filter(v=>v==='notyet').length}/6 not yet / not sure; ${values.filter(v=>!v).length}/6 not selected. This is not a test mark. Use an actual line or test as evidence, and choose one small next step.`;};update();main.querySelectorAll('[data-answer]').forEach(el=>el.addEventListener('input',update));}
    localSave();if(role==='teacher')renderRoster();
  }
  function extensionSnapshot(){if(current!=='extension')return;const w=work(); if(w.extensionWork?.[extensionId])w.extensionWork[extensionId]={code:w.code,inputs:w.inputs,runs:w.runs};}
  function applyEditing(){const edit=canEdit();editor?.setOption('readOnly',!edit);$('#main').querySelectorAll('[data-answer],#run-inputs,#run-code,#reset-code,#evidence-upload,[data-test],#submit-notebook,#extension-choice').forEach(el=>el.disabled=!edit||running);$('#return-entry').disabled=running;$('#teacher-toggle').disabled=running;$('#run-code')&&( $('#run-code').disabled=!edit||running );$('#stop-code')&&( $('#stop-code').disabled=!running );$('#submit-notebook')&&($('#submit-notebook').hidden=role==='teacher');$('#help').hidden=$('#pause').hidden=role==='teacher';$('#lesson-mode').textContent=role==='teacher'?(shareSafe?'Share-safe teaching view':'Teacher rehearsal · pupil answers are separate'):role==='preview'?'Teacher preview only':localOnly?'Offline practice · not sent to teacher':learner?.status==='pending'?'Waiting for teacher admission':room?.ended?'Lesson ended · export your evidence':room?.mode==='work'?'Work time':room?.mode==='present'?'Watch the teacher · draft protected':'Paused · draft protected';
    const watching=role==='student'&&!localOnly&&room?.mode==='present'&&current===room?.stage&&Boolean(room?.demo?.code);
    const ide=$('#main .ide');if(ide)ide.hidden=watching;
    let message=$('#own-program-note');if(watching&&ide&&!message){message=document.createElement('p');message.id='own-program-note';message.className='coach';ide.before(message);}if(message){message.hidden=!watching;message.textContent='Watch the teacher demonstration above. Your own program is saved and will reappear when your teacher selects Work.';}
    updateTeacherControls();
  }
  async function runCode(){ if(!canEdit()||running)return;running=true;const id=current;const w=work(id),code=editor?.getValue()||w.code,inputs=$('#run-inputs')?.value??w.inputs;
    const version=sessionVersion,runState={cancelledForPage:false};activePupilRun=runState;applyEditing();$('#run-error').textContent='';$('#run-output').textContent='Starting Python…';
    try {
      if(!runner)runner=new PythonRunner({onStatus:s=>{if($('#runtime-status'))$('#runtime-status').textContent=s.message;},echoInputs:true});
      const result=await runner.run(code,inputs,{timeoutMs:10000,echoInputs:true});
      if(version!==sessionVersion)return;
      const run={code,inputs:result.inputs,stdout:result.stdout,output:result.stdout,stderr:result.stderr,error:result.error||'',ok:result.ok,line:result.line||null,at:new Date().toISOString(),durationMs:result.durationMs};
      w.runs.push(run);extensionSnapshot();changed(id);
      if(id===current){const count=$('#main .ide > p.small:last-child');if(count)count.textContent=`${w.runs.length} recorded run(s). Run evidence keeps the code used for that run, even if you edit afterwards. Successful execution alone does not prove the answer meets the task.`;}
      if(id===current){$('#run-output').textContent=result.stdout||'(No printed output.)';$('#run-output').classList.toggle('error',!result.ok&&!runState.cancelledForPage);$('#run-error').textContent=runState.cancelledForPage?'Run stopped for the teacher’s page change. Your code is kept.':result.ok?'':friendlyError(result);$('#run-check').textContent=runState.cancelledForPage?'This stopped run is recorded. Wait for Work to run again.':result.ok?'The program ran. Now compare its results with the requirements and known tests.':'Your attempt is recorded. Fix one issue, then run the same inputs again.';if(result.line&&!runState.cancelledForPage){editor?.setCursor({line:Math.max(0,result.line-1),ch:0});editor?.scrollIntoView({line:Math.max(0,result.line-1),ch:0},80);}}
    }catch(e){if(version!==sessionVersion)return;if(runState.cancelledForPage){w.runs.push({code,inputs:String(inputs).split('\n'),stdout:'',output:'',stderr:'',error:'Python loading was cancelled for the teacher’s page change. The program was not executed; source code is kept.',ok:false,stopped:true,at:new Date().toISOString(),durationMs:0});if(id===current)extensionSnapshot();changed(id);}else{if(id===current){$('#run-error').textContent=e.message;$('#run-output').textContent='Python could not start. Your code remains saved. Use your own IDE if needed.';}notice('The browser Python engine could not run. Your draft is preserved; download the .py file and use your own IDE.','error');}}
    finally{if(version===sessionVersion){if(activePupilRun===runState)activePupilRun=null;running=false;applyEditing();}}
  }
  function friendlyError(r){const msg=r.error||r.stderr||'The run stopped.';let hint='';if(/IndentationError|TabError/.test(msg))hint='Check the indentation on the indicated line. Use four spaces for a block.';else if(/SyntaxError/.test(msg))hint='Check the indicated line for a missing colon, closing bracket or matching quotation mark.';else if(/NameError/.test(msg))hint='Check the identifier spelling and whether it has been assigned before use.';else if(/ValueError/.test(msg))hint='The input could not be converted. Use the whole-number inputs required by this task.';else if(/EOFError|input/i.test(msg))hint='Check your input list: every input() call needs one value, in order.';else if(r.timedOut||r.stopped)hint='The run stopped safely. Your source code is unchanged.';return (hint?hint+'\n\n':'')+msg;}
  function feedbackRender(){const el=$('#private-feedback');if(!el)return;if(role==='teacher'||role==='preview'){el.replaceChildren();return;}const fb=learner?.feedback;let entries=Array.isArray(fb)?fb:typeof fb==='string'?[{text:fb}]:fb&&typeof fb==='object'?Object.values(fb):[];entries=entries.filter(f=>String(typeof f==='string'?f:f?.text||f?.message||'').trim());el.innerHTML=entries.length?'<h3>Private teacher feedback</h3>'+entries.map(f=>`<div class="feedback">${esc(typeof f==='string'?f:f.text||f.message||'')}<p class="small">${esc(f.at||f.created_at||'')}</p></div>`).join(''):'';}
  function demoRender(){const d=room?.demo;const el=$('#demo');if(role==='teacher'||!d?.code||current!==room?.stage){el.hidden=true;return;}el.hidden=false;el.innerHTML=`<p class="eyebrow">${esc(getStage(room.stage)?.title||'')} · TEACHER DEMONSTRATION</p><details ${room.mode==='present'?'open':''}><summary>Teacher code · read only</summary><p class="demo-note">Your own program is separate and has not been overwritten. The highlighted line is a teacher pointer, not an automatic execution trace.</p><pre>${d.code.split('\n').map((l,i)=>`<span class="demo-line ${Number(d.line)===i+1?'current':''}">${String(i+1).padStart(2,' ')}  ${esc(l||' ')}</span>`).join('')}</pre>${d.output?`<h3>Teacher run output</h3><pre>${esc(d.output)}</pre>`:''}</details>`;}
  async function initializeCloud(){try{await LiveCloud.init({config:CLASSROOM_CONFIG,classId:CLASSROOM_CONFIG.classId,pollMs:2500});backendReady=true;}catch(e){backendReady=false;notice(e.userMessage||e.message,'error');}}
  async function join(name){const trimmed=name.trim();if(!trimmed)return;if(trimmed.toLowerCase()==='teacher'){openPreview();return;}const different=notebook.name&&notebook.name!==trimmed;if(different&&Object.keys(notebook.work).length&&!confirm('A different name has a notebook on this browser. Download its backup before starting a separate notebook. Start a new local notebook now?'))return;changeSession();role='entry';room=null;localOnly=false;if(different){LiveCloud.forgetJoin();notebook={version:1,name:trimmed,class:'Year 10',stage:'ready',work:{},createdAt:new Date().toISOString()};current='ready';}for(const id of notebook.unsynced||[])if(order.includes(id))dirty.add(id);
    notebook.name=trimmed;activeStorageKey=storageKey;localSave();const version=sessionVersion;notice('Joining the lesson…');try{if(!backendReady)await initializeCloud();if(version!==sessionVersion)return;if(!backendReady)throw new Error('Classroom connection is not ready. Use offline practice if your teacher directs.');const snapshot=await LiveCloud.joinStudent(trimmed);if(version!==sessionVersion)return;role='student';localOnly=false;learner=snapshot.student;room=snapshot.room;mergeRemote();showWorkspace();current=learner.status==='admitted'&&!room.ended&&permitted(room.stage)?room.stage:permitted(notebook.stage)?notebook.stage:'ready';renderStage(current);demoRender();notice(learner.status==='admitted'?'Joined on the class page. Your teacher can bring everyone to a page; your own work stays saved.':'Your name has reached the teacher board. Wait for admission; read Get ready meanwhile.','success');startPoll();}catch(e){if(version===sessionVersion)notice(e.userMessage||e.message,'error');}}
  function showWorkspace(){closePrivatePanel();document.body.classList.toggle('teacher-view',role==='teacher');$('#join').hidden=true;$('#teacher-login').hidden=true;$('#workspace').hidden=false;$('#teacher-controls').hidden=role!=='teacher';$('#export').hidden=role==='teacher';$('.site-footer').hidden=role==='teacher';$('#return-entry').hidden=role==='teacher';$('#teacher-toggle').hidden=role==='teacher';$('#learner').textContent=role==='teacher'?'Teacher · same lesson, separate rehearsal':role==='preview'?'Teacher preview':notebook.name+' · Year 10';$('#connection').textContent=role==='teacher'?'Teacher controls connected':role==='preview'?'Preview only':localOnly?'Offline practice':'Connecting to classroom';}
  function openPreview(){if(running)return;changeSession();room=null;role='preview';localOnly=true;activeStorageKey=storageKey+'-preview';notebook={version:1,name:'Teacher preview',class:'Year 10',stage:'ready',work:{},createdAt:new Date().toISOString()};extensionId=L.extensions[0].id;showWorkspace();renderStage('ready');notice('Preview: all pages are open. Sign in as the teacher to add classroom controls.');}
  function mergeRemote(){if(!learner?.work)return;for(const[id,remote]of Object.entries(learner.work)){if(!order.includes(id)||dirty.has(id))continue;const local=notebook.work[id];if(!local||new Date(remote.updated_at||0)>new Date(local.updatedAt||0)){const remoteExt=id==='extension'&&L.extensions.some(e=>e.id===remote.answers?._extension)?remote.answers._extension:null;const history=new Map();for(const r of remote.runs||[])history.set(r.at||JSON.stringify(r),r);if(id!=='extension'||!remoteExt||local?.extensionId===remoteExt)for(const r of local?.runs||[])history.set(r.at||JSON.stringify(r),r);const w=notebook.work[id]={...local,...remote,answers:remote.answers||{},code:remote.code||'',inputs:remote.answers?._inputs??local?.inputs??'',runs:[...history.values()].sort((a,b)=>String(a.at||'').localeCompare(String(b.at||''))),images:local?.images||[],updatedAt:remote.updated_at||new Date().toISOString()};if(remoteExt){extensionId=w.extensionId=remoteExt;w.extensionWork={...(local?.extensionWork||{}),[remoteExt]:{code:w.code,inputs:w.inputs,runs:w.runs}};}}}if(learner.feedback)notebook.feedback=learner.feedback;localSave();}
  function startPoll(){clearInterval(pollTimer);pollTimer=setInterval(poll,2500);}
  async function poll(){if(polling||!backendReady||localOnly||role==='entry'||role==='preview')return;polling=true;const version=sessionVersion;try{
      if(role==='teacher'){const snap=await LiveCloud.teacherState();if(version!==sessionVersion||role!=='teacher')return;const oldId=room?.id,oldStage=room?.stage;room=snap.room;teacherStudents=snap.students||[];if(oldId!==room?.id){clearPrivateSelection();demoRun=null;}if(oldId!==room?.id||oldStage!==room?.stage){demoVersion++;clearTimeout(teacherTimer);modelRunner?.stop();if($('#demo-auto'))$('#demo-auto').checked=false;}renderRoster();renderDetail(false);$('#connection').textContent='Teacher controls connected';}
      else{
        const old=room,previousStatus=learner?.status,snap=await LiveCloud.studentPoll();
        if(version!==sessionVersion||role!=='student')return;
        room=snap.room;learner=snap.student;$('#connection').textContent='Live classroom connected';
        const command=classPageCommand(room),commandChanged=Boolean(command&&command!==classPageCommand(old));
        // A Watch update also keeps an active demonstration in view if its
        // content superseded a navigation envelope between pupil polls.
        const watchRecall=room?.mode==='present'&&old?.revision!==room?.revision&&current!==room?.stage;
        const recall=old?.id!==room?.id||old?.stage!==room?.stage||previousStatus!=='admitted'||commandChanged||watchRecall;
        if(recall)snapshotEditor();
        mergeRemote();
        const moved=recall&&bringStudentToClassStep();
        routeRender();demoRender();applyEditing();feedbackRender();
        if(moved)notice(`Your teacher brought the class to ${getStage(room.stage)?.title||room.stage}. Your earlier answers and code are saved on this device. ${room.mode==='work'?'You can continue working.':'Watch the page now; wait for Work before answering.'}`,'success');
        else if(previousStatus==='pending'&&learner.status==='admitted')notice('Your teacher admitted you. Wait for the class page to open.','success');
        if(room?.mode!=='work'&&running)runner?.stop();await flush();
      }
    }catch(e){if(version===sessionVersion)$('#connection').textContent='Connection interrupted · local draft retained';}finally{if(version===sessionVersion)polling=false;}}
  function safeName(v){return String(v||'Student').replace(/[^a-zA-Z0-9_-]+/g,'_').slice(0,60)||'Student';}
  function download(filename,data,type='application/json'){const blob=new Blob([data],{type}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),3000);}
  function getImageDB(){if(!imageDBPromise)imageDBPromise=new Promise((resolve,reject)=>{const req=indexedDB.open('y10-for-evidence',1);req.onupgradeneeded=()=>req.result.createObjectStore('images');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});return imageDBPromise;}
  async function imagePut(id,data){const db=await getImageDB();return new Promise((res,rej)=>{const tx=db.transaction('images','readwrite');tx.objectStore('images').put(data,id);tx.oncomplete=res;tx.onerror=()=>rej(tx.error);});}
  async function imageGet(id){const db=await getImageDB();return new Promise((res,rej)=>{const req=db.transaction('images').objectStore('images').get(id);req.onsuccess=()=>res(req.result);req.onerror=()=>rej(req.error);});}
  async function addImages(e){const id=current,version=sessionVersion;for(const file of [...e.target.files]){if(version!==sessionVersion)return;if(!/^image\/(png|jpeg|webp)$/.test(file.type)||file.size>3*1024*1024){notice('Choose a PNG, JPEG or WebP screenshot no larger than 3 MB.','error');continue;}if(work(id).images.length>=8){notice('Eight images are already attached to this stage. Export your evidence before adding another.');break;}const data=await new Promise((res,rej)=>{const f=new FileReader();f.onload=()=>res(f.result);f.onerror=rej;f.readAsDataURL(file);});if(version!==sessionVersion)return;const key=crypto.randomUUID();try{await imagePut(key,data);if(version!==sessionVersion)return;work(id).images.push({id:key,name:file.name,type:file.type});localSave();}catch{if(version===sessionVersion)notice('Image storage is blocked. Keep the screenshot and submit it alongside your PDF.','error');}}if(version===sessionVersion&&id===current)await showImages();}
  async function showImages(){const el=$('#image-evidence'),version=sessionVersion,id=current;if(!el)return;el.innerHTML='';for(const im of work().images||[]){try{const data=await imageGet(im.id);if(version!==sessionVersion||id!==current)return;if(data){const fig=document.createElement('figure');const img=document.createElement('img');img.src=data;img.alt=im.name;const cap=document.createElement('figcaption');cap.textContent=im.name;fig.append(img,cap);el.append(fig);}}catch{}}}
  function helpForm(){if(role==='teacher')return;if($('#help-form')){$('#help-note').focus();return;}const aside=document.createElement('aside');aside.className='coach';aside.id='help-form';aside.innerHTML='<h3>Send a private written help request</h3><label for="help-note">Which line or idea needs a smaller next step?</label><input id="help-note" maxlength="300" placeholder="Please explain line… / Show one comparison example"><div class="support-row"><button id="send-help">Send to teacher</button><button id="cancel-help" class="quiet">Close</button></div><p class="small">You can ask in writing. You do not need to use your microphone.</p>';$('#main').append(aside);$('#cancel-help').onclick=()=>aside.remove();$('#send-help').onclick=async()=>{const version=sessionVersion,text=$('#help-note').value;work().answers.helpRequest=text;changed();if(role==='student'&&!localOnly)try{const updated=await LiveCloud.setHelp(true,text);if(version!==sessionVersion)return;learner=updated;notice('Your private request reached your teacher.','success');}catch(e){if(version===sessionVersion)notice('Your help request is saved locally but has not reached the teacher. Use Teams chat if the connection is unavailable.','error');}else notice('Offline practice: use Teams chat or contact your teacher to ask for support.');aside.remove();};$('#help-note').focus();}
  async function teacherLogin(e){e.preventDefault();if(running){notice('Stop the Python run before switching to teacher controls.');return;}const version=sessionVersion,submit=$('#teacher-form button');submit.disabled=true;notice('Checking teacher permissions…');try{if(!backendReady)await initializeCloud();if(version!==sessionVersion)return;const snap=await LiveCloud.teacherLogin($('#teacher-email').value,$('#teacher-password').value);$('#teacher-password').value='';if(version!==sessionVersion)return;if(!await LiveCloud.isTeacher())throw new Error('This account is not the approved teacher for this class.');if(version!==sessionVersion)return;changeSession();room=snap?.room||null;teacherStudents=snap?.students||[];role='teacher';localOnly=false;teacherNotebook();current=room?.stage||notebook.stage||'ready';if(!order.includes(current))current='ready';renderBoard();showWorkspace();renderStage(current);openPrivatePanel();startPoll();notice('Lesson content stays beside the class responses. Click a pupil for their full work; Back to class responses returns to everyone. Keep this private view off a shared screen.','success');}catch(e){$('#teacher-password').value='';if(version===sessionVersion)notice(e.userMessage||e.message,'error');}finally{submit.disabled=false;}}
  function renderBoard(){
    $('#teacher-controls').innerHTML=`<div class="control-context"><strong>Teacher controls</strong><span id="teacher-room-status" role="status"></span></div><div class="control-main-row"><button id="start-class">Start / resume lesson</button><button id="release-stage">Bring class to this page</button><div class="mode-buttons" role="group" aria-label="Classroom mode"><button class="quiet" data-class-mode="present">Watch</button><button class="quiet" data-class-mode="work">Work</button><button class="quiet" data-class-mode="paused">Pause</button></div><button id="open-students" class="quiet private-only">Students</button><button id="share-safe-toggle" class="quiet">Share-safe view</button><button id="exit-share-safe" class="quiet" hidden>Exit share-safe</button><details class="private-only"><summary>Lesson setup</summary><button id="end-class" class="quiet">End lesson</button><button id="teacher-signout" class="quiet">Sign out</button></details></div><p id="teacher-step-hint" class="teacher-view-note"></p>`;
    $('#teacher-board').dataset.view='overview';
    $('#teacher-board').innerHTML=`<div class="panel-header"><h2 id="private-panel-title">Class responses</h2><div class="panel-actions"><button id="close-students" class="quiet">Hide responses</button><button id="panel-share-safe" class="quiet">Share-safe view</button></div></div><p class="small">Private teacher view — do not screen-share pupil work. Responses refresh after saving; this is not a live typing indicator or a grade.</p><button id="back-to-class" class="quiet">Back to class responses</button><details class="invitation-details"><summary>Student invitation and admission</summary><label for="invite-link">Student invitation — share in Teams</label><input id="invite-link" readonly><button id="copy-invite" class="quiet">Copy student invitation</button><p class="small">Students enter their name and wait for admission. The invitation expires with the room after four hours. Admit or decline waiting pupils in the class overview.</p></details><section id="class-overview"><div class="response-options"><label class="check-label"><input type="checkbox" id="follow-lesson" checked> Follow the lesson step I’m viewing</label><label for="response-stage">Compare responses for</label><select id="response-stage">${stages.map(st=>`<option value="${st.id}">${esc(st.title)}</option>`).join('')}</select></div><h3 id="roster-count">Students</h3><p id="roster-summary" class="small" role="status"></p><ul id="roster" class="roster"></ul></section><section id="student-detail" class="student-detail"></section>`;
    $('#teacher-model-tools').innerHTML=`<details class="demo-editor"><summary>Teach with a live code demonstration</summary><p id="demo-step-note" class="small"></p><p class="small">Students see a separate read-only model, not your private panel or their classmates' answers. Their own programs are never overwritten.</p><button id="use-workspace-demo" class="quiet">Use my workspace code</button><label for="demo-model">Or choose a prepared model</label><select id="demo-model">${Object.keys(L.models||{}).map(k=>`<option value="${esc(k)}">${esc(k)}</option>`).join('')}</select><button id="load-demo-model" class="quiet">Load model</button><div class="editor-shell"><textarea id="teacher-demo-code" aria-label="Teacher Python demonstration">${esc(L.models?.loop||L.models?.total||'print("Hello")')}</textarea></div><label for="demo-line">Highlight line (0 = none)</label><input id="demo-line" type="number" min="0" max="2000" value="1"><label><input type="checkbox" id="demo-auto" style="display:inline;width:auto"> Share edits automatically after a short pause</label><div class="support-row"><button id="publish-demo">Share demonstration</button><button id="run-demo">Run and share demonstration</button><button id="stop-demo" class="quiet" disabled>Stop run</button><button id="clear-demo" class="quiet">Hide demonstration</button></div><label for="demo-inputs">Demonstration inputs, one per line</label><textarea id="demo-inputs" class="inputs">3\n2\n5\n4</textarea><pre id="demo-output">Not run yet.</pre></details>`;
    demoEditor=CodeMirror.fromTextArea($('#teacher-demo-code'),{mode:'python',lineNumbers:true,indentUnit:4,tabSize:4,matchBrackets:true,styleActiveLine:true,viewportMargin:Infinity});
    demoEditor.getInputField().setAttribute('aria-label','Teacher Python demonstration');
    $('#teacher-model-tools details').addEventListener('toggle',()=>{if($('#teacher-model-tools details').open)demoEditor.refresh();});
    demoEditor.on('change',()=>{demoVersion++;demoRun=null;$('#demo-output').textContent='Code changed. Run again to show matching output.';if($('#demo-auto').checked)scheduleDemo();});$('#demo-line').oninput=()=>{if($('#demo-auto').checked)scheduleDemo();};$('#demo-auto').onchange=()=>{clearTimeout(teacherTimer);if($('#demo-auto').checked)scheduleDemo();};
    $('#start-class').onclick=()=>teacherAction(async()=>{const version=sessionVersion;const snap=await LiveCloud.teacherStart('ready');if(version!==sessionVersion||role!=='teacher')return;if(room?.id!==snap.room?.id)clearPrivateSelection();room=snap.room;teacherStudents=snap.students||[];renderStage(room.stage);renderRoster();});
    $('#release-stage').onclick=()=>{const id=current;demoVersion++;clearTimeout(teacherTimer);$('#demo-auto').checked=false;demoRun=null;modelRunner?.stop();teacherAction(()=>classControl({stage:id,mode:'present',demo:{code:'',line:0,output:'y10-class-page-v1:'+crypto.randomUUID()}}),`Sent ${getStage(id)?.title||id} to the class in Watch mode. Connected pupils move on their next classroom refresh; their drafts stay saved. Select Work when they should answer.`);};
    $('#teacher-controls').querySelectorAll('[data-class-mode]').forEach(b=>b.onclick=()=>teacherAction(()=>classControl({mode:b.dataset.classMode})));
    $('#open-students').onclick=()=>{if(role!=='teacher'||shareSafe)return;if(!$('#teacher-board').hidden)closePrivatePanel();else openPrivatePanel();updateTeacherControls();};$('#close-students').onclick=()=>{closePrivatePanel();updateTeacherControls();};$('#panel-share-safe').onclick=()=>setShareSafe(true);
    $('#back-to-class').onclick=()=>{saveFeedbackDraft();responseView='overview';$('#teacher-board').dataset.view=responseView;renderRoster();$('#teacher-board').scrollTop=0;$('#private-panel-title').focus({preventScroll:true});};$('#private-panel-title').tabIndex=-1;
    $('#follow-lesson').onchange=e=>{responseStage=e.target.checked?null:$('#response-stage').value;renderRoster();};$('#response-stage').onchange=e=>{responseStage=e.target.value;$('#follow-lesson').checked=false;renderRoster();};
    const previewLabel=document.createElement('label');previewLabel.htmlFor='response-preview';previewLabel.textContent='Show in each card';const previewChoice=document.createElement('select');previewChoice.id='response-preview';previewChoice.innerHTML='<option value="auto">Best available response</option><option value="answers">Written responses</option><option value="code">Python code</option><option value="output">Actual run output</option>';previewChoice.value=responsePreview;previewChoice.onchange=e=>{responsePreview=e.target.value;renderRoster();};$('#class-overview .response-options').append(previewLabel,previewChoice);
    const options=$('#class-overview .response-options'),settings=document.createElement('details'),settingsTitle=document.createElement('summary');settings.className='response-settings';settingsTitle.textContent='Response view options';options.before(settings);settings.append(settingsTitle,options);$('#teacher-board > p.small').textContent='Private — do not screen-share. Saved responses, not live typing.';
    $('#share-safe-toggle').onclick=()=>setShareSafe(true);$('#exit-share-safe').onclick=()=>setShareSafe(false);
    $('#end-class').onclick=()=>{if(confirm('End live work? Students keep their drafts and can export evidence.')){demoVersion++;clearTimeout(teacherTimer);$('#demo-auto').checked=false;modelRunner?.stop();teacherAction(()=>classControl({ended:true}));}};
    $('#teacher-signout').onclick=()=>teacherAction(async()=>{await LiveCloud.teacherLogout();modelRunner?.stop();changeSession();role='entry';room=null;teacherStudents=[];selectedStudent=null;demoRun=null;$('#teacher-board').replaceChildren();$('#teacher-controls').replaceChildren();$('#teacher-controls').hidden=true;$('#teacher-model-tools').replaceChildren();$('#teacher-model-tools').hidden=true;$('#workspace').hidden=true;document.body.classList.remove('teacher-view');restorePupilNotebook();$('#student-name').value=notebook.name||'';$('#join').hidden=false;$('#teacher-login').hidden=true;$('#teacher-toggle').hidden=false;$('#export').hidden=false;$('.site-footer').hidden=false;notice('Signed out. Your separate student notebook has been preserved.');});
    $('#publish-demo').onclick=publishDemo;$('#run-demo').onclick=runDemo;$('#stop-demo').onclick=()=>{demoVersion++;modelRunner?.stop();};$('#clear-demo').onclick=()=>{demoVersion++;clearTimeout(teacherTimer);$('#demo-auto').checked=false;modelRunner?.stop();teacherAction(()=>classControl({demo:{code:'',line:0,output:''}}));};
    $('#load-demo-model').onclick=()=>{demoEditor.setValue(L.models[$('#demo-model').value]);$('#demo-output').textContent='Not run yet.';};
    $('#use-workspace-demo').onclick=()=>{if(!editor)return;$('#demo-auto').checked=false;clearTimeout(teacherTimer);demoEditor.setValue(editor.getValue());$('#demo-inputs').value=work().inputs;const last=work().runs.at(-1);demoRun=last?.code===editor.getValue()?{code:last.code,output:last.stdout+(last.ok?'':'\n'+friendlyError(last))}:null;$('#demo-output').textContent=demoRun?.output||'Not run yet. Run the demonstration before sharing output.';demoEditor.refresh();};
    $('#copy-invite').onclick=async()=>{if(role!=='teacher'||shareSafe)return;if(!room||room.ended){notice('Start a live lesson first.');return;}const link=new URL(location.pathname,location.origin);link.searchParams.set('room',room.id);$('#invite-link').value=link.href;try{await navigator.clipboard.writeText(link.href);notice('Student invitation copied. Share it in Teams.','success');}catch{$('#invite-link').focus();$('#invite-link').select();notice('Copy the selected invitation link and share it in Teams.');}};
  }
  function setShareSafe(enabled){if(role!=='teacher')return;shareSafe=enabled;closePrivatePanel();document.body.classList.toggle('share-safe',enabled);notice(enabled?'Share-safe view: private student information is closed and cannot be opened until you exit this view.':'Teacher controls restored. Keep the private student panel off your shared screen.');applyEditing();}
  function clearPrivateSelection(){selectedStudent=null;responseStage=detailStage=null;responseView='overview';feedbackDrafts.clear();feedbackSending.clear();const panel=$('#teacher-board');if(panel)panel.dataset.view='overview';const el=$('#student-detail');if(el){delete el.dataset.student;el.replaceChildren();}}
  function updateTeacherControls(){
    if(role!=='teacher'){if($('#teacher-model-tools'))$('#teacher-model-tools').hidden=true;return;}if(!$('#release-stage'))return;
    const live=Boolean(room&&!room.ended),matching=live&&room.stage===current,panelOpen=!$('#teacher-board').hidden&&!shareSafe;
    $('#release-stage').disabled=!live;$('#start-class').textContent=live?'Resume class step':'Start lesson';
    $('#teacher-room-status').textContent=room?`${room.ended?'Ended':'Class on '+(getStage(room.stage)?.title||room.stage)} · ${{present:'Watch',work:'Work',paused:'Pause'}[room.mode]}`:'Not started yet';
    $('#teacher-step-hint').textContent=shareSafe?'Share-safe: private student information is hidden. Bring class to this page still works.':!live?'Start the lesson, then use Class responses to copy the invitation and admit pupils.':matching?'Bring class to this page recalls pupils here, even if they browsed elsewhere. Work = students can answer; Watch/Pause = drafts protected.':'You are previewing privately. Bring class to this page moves connected pupils here in Watch mode. Previous/Next only changes your view.';
    $('#teacher-controls').querySelectorAll('[data-class-mode]').forEach(b=>{b.disabled=!live;b.setAttribute('aria-pressed',String(room?.mode===b.dataset.classMode));});
    $('#share-safe-toggle').hidden=shareSafe;$('#exit-share-safe').hidden=!shareSafe;
    $('#open-students').disabled=shareSafe;$('#open-students').setAttribute('aria-expanded',String(panelOpen));$('#open-students').setAttribute('aria-controls','teacher-board');
    $('#open-students').textContent=`${panelOpen?'Hide':'Show'} class responses (${teacherStudents.length})${teacherStudents.some(s=>s.status==='pending')?' · waiting':''}${teacherStudents.some(s=>s.help_requested)?' · help':''}`;
    $('#teacher-model-tools').hidden=shareSafe||!editor;const note=$('#demo-step-note');if(note)note.textContent=matching?`Sharing to ${getStage(current)?.title}. Use my workspace code, then Share or Run and share. During Watch, students see the model instead of their editable workspace.`:'Bring class to this page before sharing a demonstration. You can rehearse privately in your workspace.';
    for(const id of ['publish-demo','run-demo','demo-auto','clear-demo'])if($('#'+id))$('#'+id).disabled=!matching||demoRunning;$('#stop-demo')&&($('#stop-demo').disabled=!demoRunning);
  }
  async function classControl(patch){const version=sessionVersion,id=room?.id;const updated=await LiveCloud.teacherControl(patch);if(version!==sessionVersion||role!=='teacher'||room?.id!==id)return;room=updated;renderRoster();}
  async function teacherAction(fn,message='Classroom updated.'){const version=sessionVersion;try{await fn();if(version!==sessionVersion||role!=='teacher')return;$('#connection').textContent='Teacher controls connected';notice(message,'success');}catch(e){if(version===sessionVersion)notice(e.userMessage||e.message,'error');}}
  function scheduleDemo(){clearTimeout(teacherTimer);const version=sessionVersion,generation=demoVersion,id=room?.id,stage=room?.stage;teacherTimer=setTimeout(()=>{if(version===sessionVersion&&generation===demoVersion&&role==='teacher'&&room?.id===id&&room?.stage===stage&&current===stage)publishDemo();},650);}
  async function publishDemo(){if(role!=='teacher'||!room||room.ended||current!==room.stage){notice('Bring class to your current page before sharing its demonstration.');return;}const code=demoEditor.getValue();await teacherAction(()=>classControl({demo:{code,line:Math.max(0,Math.min(2000,Math.floor(Number($('#demo-line').value)||0))),output:demoRun?.code===code?demoRun.output:''}}));}
  async function runDemo(){if(demoRunning||role!=='teacher'||!room||room.ended||current!==room.stage)return;const version=sessionVersion,generation=demoVersion,id=room.id,stage=room.stage;demoRunning=true;updateTeacherControls();try{if(!modelRunner)modelRunner=new PythonRunner({echoInputs:true});const code=demoEditor.getValue();const r=await modelRunner.run(code,$('#demo-inputs').value,{timeoutMs:10000,echoInputs:true});if(version!==sessionVersion||generation!==demoVersion||role!=='teacher'||room?.id!==id||room?.stage!==stage||current!==stage)return;const text=r.stdout+(r.ok?'':'\n'+friendlyError(r));if(demoEditor.getValue()===code){demoRun={code,output:text};$('#demo-output').textContent=text;await publishDemo();}else{demoRun=null;$('#demo-output').textContent='The code changed during that run. Run the current code again before sharing its output.';}}catch(e){if(version===sessionVersion)notice(e.message,'error');}finally{if(version===sessionVersion){demoRunning=false;updateTeacherControls();}}}
  const excerpt=(value,limit=420)=>{const text=String(value??'');return text.length>limit?text.slice(0,limit)+'…':text;};
  function responseValue(key,value){const evidence={notyet:'Not yet / not sure',support:'With an example or scaffold',independent:'Independently'},phases={new:'New learning',consolidating:'Consolidating',treading:'Treading water',help:'Drowning / needing help'};return key.endsWith('-evidence')&&evidence[value]?evidence[value]:key.endsWith('-phase')&&phases[value]?phases[value]:typeof value==='string'?value:JSON.stringify(value);}
  function savedResponses(w){return Object.entries(w?.answers||{}).filter(([key,value])=>!key.startsWith('_')&&value!==''&&value!==null&&value!==undefined);}
  function cardHTML(s,id){
    const w=s.work?.[id],answers=savedResponses(w),run=w?.runs?.at(-1),code=w?.code||'',lines=code.split('\n'),stamp=Date.parse(w?.updated_at||''),seen=Date.parse(s.last_seen_at||''),ext=L.extensions.find(e=>e.id===w?.answers?._extension);
    const preview=responsePreview==='auto'?(answers.length?'answers':code.trim()?'code':run?'output':'answers'):responsePreview;
    let content='';
    if(preview==='answers')content=answers.length?`<span class="response-label">${esc(questionLabel(id,answers[0][0]))} · excerpt</span><span class="response-excerpt">${esc(excerpt(responseValue(answers[0][0],answers[0][1]),220))}</span>`:'<span class="response-empty">No written response saved for this step.</span>';
    if(preview==='code')content=code.trim()?`<span class="response-label">Latest saved code · excerpt${ext?' · '+esc(ext.title):''}</span><span class="response-excerpt code-preview">${esc(lines.slice(0,7).map((line,i)=>`${i+1}  ${line}`).join('\n'))}</span>`:'<span class="response-empty">No Python code saved for this step.</span>';
    if(preview==='output')content=run?`<span class="response-label">Most recent recorded output · final lines</span><span class="response-excerpt code-preview">${esc(excerpt((run.stdout||run.output||'(No printed output.)').split('\n').slice(-5).join('\n'),350))}${run.error?'\n'+esc(excerpt(run.error,150)):''}</span><span class="status">Output belongs to the code saved with that run.</span>`:'<span class="response-empty">No run evidence saved for this step.</span>';
    return `<button class="select-student ${selectedStudent===s.id?'selected':''}" data-student="${esc(s.id)}" aria-label="View ${esc(s.name)}’s full response"><span class="response-heading"><strong>${esc(s.name)}</strong><span class="badge">${esc(s.status)}</span></span><span class="status">${Number.isFinite(stamp)?'Step saved '+new Date(stamp).toLocaleTimeString():'No saved attempt for this step'} · ${Number.isFinite(seen)&&Date.now()-seen<15000?'Connected recently':'No recent connection'}</span>${s.help_requested?'<span class="badge help">Written help requested</span>':''}${content}<span class="status">${answers.length} written response(s) · ${code.trim()?lines.length+' code lines':'no saved code'} · ${w?.runs?.length||0} recorded run(s)</span><span class="response-open">Open full response →</span></button>${s.status==='pending'?`<div class="support-row"><button data-admit="${esc(s.id)}">Admit ${esc(s.name)}</button><button class="quiet" data-reject="${esc(s.id)}">Decline ${esc(s.name)}</button></div>`:''}`;
  }
  function renderRoster(){
    updateTeacherControls();const panel=$('#teacher-board'),list=$('#roster');if(role!=='teacher'||shareSafe||panel?.hidden||!list)return;
    const students=teacherStudents,id=responseStage||current;if(panel.dataset.responseStage!==id&&responseView==='overview')panel.scrollTop=0;panel.dataset.responseStage=id;$('#response-stage').value=id;$('#follow-lesson').checked=responseStage===null;
    $('#roster-count').textContent=`${students.filter(s=>s.status==='admitted').length} admitted · ${students.filter(s=>s.status==='pending').length} waiting`;
    const attempted=students.filter(s=>{const w=s.work?.[id];return savedResponses(w).length||w?.code?.trim()||w?.runs?.length;}).length;
    $('#roster-summary').textContent=`${getStage(id)?.title||id} · ${attempted}/${students.length} with saved work. Open a card for the full response.`;
    if(room){const link=new URL(location.pathname,location.origin);link.searchParams.set('room',room.id);$('#invite-link').value=room.ended?'Room ended — start a new lesson':link.href;}else $('#invite-link').value='Start the lesson to create an invitation.';
    const existing=new Map([...list.children].map(li=>[li.dataset.studentRow,li]));
    students.forEach((s,index)=>{let li=existing.get(s.id);if(!li){li=document.createElement('li');li.className='response-card';li.dataset.studentRow=s.id;}existing.delete(s.id);const html=cardHTML(s,id);if(li.responseMarkup!==html){const active=li.contains(document.activeElement)?document.activeElement:null,action=active?['student','admit','reject'].find(a=>active.hasAttribute('data-'+a)):null;li.innerHTML=html;li.responseMarkup=html;if(action)li.querySelector('[data-'+action+']')?.focus({preventScroll:true});}if(list.children[index]!==li)list.insertBefore(li,list.children[index]||null);});
    for(const li of existing.values())li.remove();if(!students.length){const li=document.createElement('li');li.className='response-empty';li.textContent='Waiting for students to join by name. Open Student invitation and admission above to copy the link.';list.replaceChildren(li);}
    list.onclick=e=>{if(role!=='teacher'||shareSafe)return;const b=e.target.closest('button');if(!b)return;if(b.dataset.student){saveFeedbackDraft();selectedStudent=b.dataset.student;detailStage=id;responseView='individual';panel.dataset.view=responseView;renderDetail(true);panel.scrollTop=0;$('#student-detail h3')?.focus({preventScroll:true});}else if(b.dataset.admit||b.dataset.reject){const pupilId=b.dataset.admit||b.dataset.reject,allow=Boolean(b.dataset.admit);teacherAction(async()=>{await LiveCloud.teacherAdmit(pupilId,allow);await poll();});}};
  }
  function renderDetail(force=false){
    const panel=$('#teacher-board'),s=teacherStudents.find(s=>s.id===selectedStudent),el=$('#student-detail');if(role!=='teacher'||shareSafe||panel?.hidden||responseView!=='individual'||!s||!el)return;
    const id=detailStage||responseStage||current;
    if(!force&&el.dataset.student===s.id){$('#student-help-state').textContent=s.help_requested?'Private help request: '+(s.help_note||'Please give a written next step.'):'No current help request.';updateDetailEvidence(s,id);updateFeedbackState(s);return;}
    el.dataset.student=s.id;el.innerHTML=`<h3 tabindex="-1">${esc(s.name)}</h3><p id="student-help-state">${s.help_requested?'Private help request: '+esc(s.help_note||'Please give a written next step.'):'No current help request.'}</p><label for="student-stage">Review this pupil’s saved stage</label><select id="student-stage">${stages.map(st=>`<option value="${st.id}" ${st.id===id?'selected':''}>${esc(st.title)}</option>`).join('')}</select><div id="student-evidence"></div><details><summary>Feedback already shared with this pupil</summary><div id="sent-feedback"></div></details><label for="teacher-feedback">Private feedback — one small next step</label><textarea id="teacher-feedback" class="teacher-note" maxlength="2000" placeholder="Look at line… Try… Then check…">${esc(feedbackDrafts.get(s.id)||'')}</textarea><p class="small">Unsent feedback stays here when you switch pupils, until you sign out or start another room. It is not sent automatically.</p><button id="send-feedback">Send private feedback</button><label for="individual-stage">Allow this student to revisit or extend</label><select id="individual-stage">${stages.map(st=>`<option value="${st.id}" ${st.id===id?'selected':''}>${esc(st.title)}</option>`).join('')}</select><button id="unlock-student" class="quiet">Unlock selected stage for this student</button><p class="small">Individual access still respects demonstration/pause mode. These are lesson pacing controls, not exam browser lockdown.</p>`;
    $('#teacher-feedback').oninput=()=>feedbackDrafts.set(s.id,$('#teacher-feedback').value);
    $('#student-stage').onchange=e=>{detailStage=e.target.value;const latest=teacherStudents.find(p=>p.id===selectedStudent);if(latest)updateDetailEvidence(latest,detailStage);};
    $('#send-feedback').onclick=()=>teacherAction(async()=>{const version=sessionVersion,roomId=room?.id,target=s.id,raw=$('#teacher-feedback').value,text=raw.trim();if(!text)throw new Error('Write one clear next step before sending.');if(feedbackSending.has(target))return;feedbackDrafts.set(target,raw);feedbackSending.add(target);updateFeedbackState(s);try{await LiveCloud.teacherFeedback(target,text);if(version!==sessionVersion||role!=='teacher'||room?.id!==roomId)return;if(feedbackDrafts.get(target)===raw){feedbackDrafts.delete(target);if(selectedStudent===target&&$('#student-detail')?.dataset.student===target&&$('#teacher-feedback').value===raw)$('#teacher-feedback').value='';}await poll();}finally{if(version===sessionVersion){feedbackSending.delete(target);const latest=teacherStudents.find(p=>p.id===selectedStudent);if(latest)updateFeedbackState(latest);}}});
    $('#unlock-student').onclick=()=>teacherAction(async()=>{const target=s.id,stage=$('#individual-stage').value;await LiveCloud.teacherUnlock(target,stage,true);await poll();});updateDetailEvidence(s,id);updateFeedbackState(s);
  }
  function updateFeedbackState(s){if($('#student-detail')?.dataset.student!==s.id)return;const send=$('#send-feedback');if(send){send.disabled=s.status!=='admitted'||feedbackSending.has(s.id);send.textContent=feedbackSending.has(s.id)?'Sending feedback…':'Send private feedback';}if($('#unlock-student'))$('#unlock-student').disabled=s.status!=='admitted';const sent=$('#sent-feedback');if(sent){const feedback=s.feedback,items=Array.isArray(feedback)?feedback:typeof feedback==='string'?[feedback]:Object.values(feedback||{});sent.replaceChildren();for(const item of items){const p=document.createElement('p');p.className='feedback';p.textContent=typeof item==='string'?item:item?.text||item?.message||JSON.stringify(item);if(p.textContent)sent.append(p);}if(!sent.childElementCount)sent.textContent='No feedback shared yet.';}}
  function updateDetailEvidence(s,id){const w=s.work?.[id],el=$('#student-evidence');if(!el)return;const signature=JSON.stringify([s.id,id,w]);if(el.evidenceSignature===signature)return;el.evidenceSignature=signature;const code=w?.code||'',r=w?.runs?.at(-1);el.innerHTML=w?`<p class="small">Saved ${esc(w.updated_at||'')} · ${w.runs?.length||0} recorded runs</p>${code.trim()?`<h3>Latest saved code</h3><pre>${code.split('\n').map((l,i)=>`${i+1}  ${esc(l)}`).join('\n')}</pre>`:''}<h3>Responses</h3>${savedResponses(w).map(([k,v])=>`<p><strong>${esc(questionLabel(id,k))}</strong><br>${esc(responseValue(k,v))}</p>`).join('')||'<p>No written responses yet.</p>'}${r?`<h3>Most recent actual run</h3><p>Inputs: ${esc((r.inputs||[]).join(', '))}</p><pre>${esc(r.stdout||r.output||'(No printed output.)')}</pre>${r.error?`<pre class="error">${esc(r.error)}</pre>`:''}<details><summary>Code used for that run (may differ from latest draft)</summary><pre>${esc(r.code||'(Not recorded.)')}</pre></details>`:'<p>No run evidence recorded for this stage.</p>'}`:'<p>No saved attempt in this stage yet.</p>';}
  function questionLabel(id,key){const labels={'learning-focus':'My priority type of learning','learning-target':'My next small target','pit-evidence':'Evidence of progress','pit-next':'My next step','finalSubmitted':'Completion sent in app','pauseRequested':'Pause requested','helpRequest':'Written help request'};const k=L.ksu.find(k=>key.startsWith(k.id));return labels[key]||getStage(id)?.fields?.find(f=>f.id===key)?.label||(k?k.can+(key.endsWith('-phase')?' — current learning phase':' — current evidence'):null)||(key.startsWith('extension-explain-')?'Explanation: '+(L.extensions.find(e=>key==='extension-explain-'+e.id)?.title||key):key);}
  async function exportPDF(){const b=$('#export'),version=sessionVersion;b.disabled=true;try{snapshotEditor();const evidence=JSON.parse(JSON.stringify(notebook)),offlineExport=localOnly,exportFeedback=JSON.parse(JSON.stringify(learner?.feedback||evidence.feedback||null));const {jsPDF}=window.jspdf;const doc=new jsPDF({unit:'mm',format:'a4',compress:true});let font='helvetica';try{for(const[style,file]of [['normal','Raleway-Regular.ttf'],['bold','Raleway-Bold.ttf']]){const ab=await(await fetch('assets/'+file)).arrayBuffer();const bytes=new Uint8Array(ab);let bin='';for(let i=0;i<bytes.length;i+=8192)bin+=String.fromCharCode(...bytes.subarray(i,i+8192));doc.addFileToVFS(file,btoa(bin));doc.addFont(file,'Raleway',style);}font='Raleway';}catch{}
      const left=17,width=176,bottom=278;let y=20,page=1;
      const normalize=t=>String(t??'').replace(/←/g,'<-').replace(/→/g,'->').replace(/≥/g,'>=').replace(/≤/g,'<=').replace(/…/g,'...').replace(/[–—]/g,'-').replace(/[“”]/g,'"').replace(/[‘’]/g,"'");
      const newPage=()=>{doc.addPage();page++;y=20;};
      const canvasFont=(size,isCode,bold)=>`${bold?'700':'400'} ${size*96/72}px ${isCode?'ui-monospace, Menlo, Consolas, monospace':'Raleway, Arial, sans-serif'}`;
      const rasterLine=(line,size,isCode,bold,atY,color)=>{const scale=4,cssW=width*96/25.4,cssH=size*0.48*96/25.4,c=document.createElement('canvas');c.width=Math.ceil(cssW*scale);c.height=Math.ceil(cssH*scale);const cx=c.getContext('2d');cx.scale(scale,scale);cx.fillStyle='#fff';cx.fillRect(0,0,cssW,cssH);cx.font=canvasFont(size,isCode,bold);cx.fillStyle=color||(bold?'#086437':'#18231d');cx.textBaseline='alphabetic';cx.fillText(line,0,cssH*.77);doc.addImage(c.toDataURL('image/png'),'PNG',left,atY-size*.37,width,size*.48);};
      const text=(value,size=10,isCode=false,bold=false)=>{doc.setFont(isCode?'courier':font,bold?'bold':'normal');doc.setFontSize(size);const source=(isCode?String(value??''):normalize(value))||'Not answered.';const unicode=/[^\u0000-\u00ff]/.test(source);let lines;if(unicode){const measure=document.createElement('canvas').getContext('2d');measure.font=canvasFont(size,isCode,bold);lines=[];const limit=width*96/25.4;for(const paragraph of source.replace(/\t/g,'    ').split('\n')){let line='';for(const char of paragraph){if(line&&measure.measureText(line+char).width>limit){lines.push(line);line='';}line+=char;}lines.push(line);}}else lines=doc.splitTextToSize(source,width);for(const line of lines){if(y>bottom)newPage();if(unicode)rasterLine(line,size,isCode,bold,y);else doc.text(line,left,y);y+=size*0.48;}y+=2;};
      const heading=t=>{if(y>bottom-20)newPage();doc.setTextColor(8,100,55);text(t,14,false,true);doc.setTextColor(24,35,29);};
      heading('Year 10 - Live Python Programming Evidence');text('Name: '+(evidence.name||'Not entered')+'   Class: '+(evidence.class||'Year 10'));text('Exported: '+new Date().toLocaleString());text('Topic: '+(L.topic||L.title));text('WAGBA: '+L.wagba);text(offlineExport?'Offline practice: this notebook was not sent to the teacher board.':'Live lesson: export contains this device notebook. Teacher saving and Teams submission are separate.');heading('Knowledge, Skills and Understanding');L.ksu.forEach(k=>text(k.kind+': '+k.can));
      const answerText=(id,key,value)=>{const opts=key.endsWith('-evidence')?{notyet:'Not yet / not sure',support:'With an example or scaffold',independent:'Independently'}:key.endsWith('-phase')?{new:'New learning',consolidating:'Consolidating',treading:'Treading water',help:'Drowning / needing help'}:null;return opts?.[value]||String(value??'');};
      const printRun=r=>{text('Time: '+(r.at||'Not recorded')+'\nInputs: '+(r.inputs||[]).join(', '));text('Source used in this run:',10);text(r.code||'Not recorded.',9,true);text('Actual output:',10);text(r.stdout||r.output||'(No printed output.)',9,true);if(r.error)text('Error / stopped run:\n'+r.error,9,true);if(r.stderr)text('Python diagnostic output:\n'+r.stderr,9,true);};
      for(const s of stages){
        newPage();heading(s.title);if(s.heading&&s.heading!==s.title)text(s.heading,11);
        const w=evidence.work[s.id];if(!w){text('Not attempted.');continue;}
        const fs=['types','pit'].includes(s.id)?[]:(s.fields||[]);
        for(const f of fs)text(f.label+'\n'+(w.answers[f.id]||'Not answered.'));
        const known=new Set(fs.map(f=>f.id));
        for(const[k,v]of Object.entries(w.answers||{})){if(!known.has(k)&&!k.startsWith('_'))text(questionLabel(s.id,k)+'\n'+answerText(s.id,k,v));}
        if(w.code){heading('Latest source code'+(s.id==='extension'?' — '+(L.extensions.find(e=>e.id===w.extensionId)?.title||'Chosen extension'):''));text(w.code,9,true);}
        for(let i=0;i<(w.runs||[]).length;i++){heading('Recorded run '+(i+1));printRun(w.runs[i]);}
        if(s.id==='extension'&&w.extensionWork){for(const[id,ew]of Object.entries(w.extensionWork)){if(id===w.extensionId)continue;heading('Additional extension: '+(L.extensions.find(e=>e.id===id)?.title||id));text(ew.code,9,true);for(const r of ew.runs||[])printRun(r);}}
        for(const im of w.images||[]){const data=await imageGet(im.id);if(!data){text('Attached image unavailable: '+im.name);continue;}const img=await new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=data;});const maxH=230,scale=Math.min(width/img.naturalWidth,maxH/img.naturalHeight),iw=img.naturalWidth*scale,ih=img.naturalHeight*scale;if(y+ih+12>bottom)newPage();text('Screenshot: '+im.name,9);doc.addImage(data,'',left,y,iw,ih);y+=ih+6;}
      }
      const feedback=exportFeedback;if(feedback){newPage();heading('Private teacher feedback');const list=Array.isArray(feedback)?feedback:typeof feedback==='string'?[feedback]:Object.values(feedback);for(const f of list)text(typeof f==='string'?f:(f.text||f.message||JSON.stringify(f)));}
      newPage();heading('Save and submit in Microsoft Teams');text('1. Save this PDF and open it. Check your name, source code, outputs and complete screenshots.\n2. Open Teams > Year 10 Computer Science > the correct lesson assignment.\n3. Select Add work, upload this PDF (and .py files if requested), then select Turn in.\n4. Check the submitted status in Teams. Exporting or pressing Submit in this app does not turn in a Teams assignment.\n5. Keep a downloaded notebook backup if you will change devices.');
      const total=doc.getNumberOfPages();for(let p=1;p<=total;p++){doc.setPage(p);doc.setFont(font,'normal');doc.setFontSize(8);doc.setTextColor(80,90,83);const footer='Year 10 · '+(evidence.name||'Student')+' · '+p+' / '+total;if(/[^\u0000-\u00ff]/.test(footer))rasterLine(footer,8,false,false,290,'#505a53');else doc.text(footer,17,290);}
      doc.save(`Year10_FOR_Loops_${safeName(evidence.name)}_${new Date().toISOString().slice(0,10)}.pdf`);if(version===sessionVersion)notice('PDF exported. Open it to check your evidence, then upload and Turn in through Teams.','success');
    }catch(e){if(version===sessionVersion)notice('PDF export could not finish: '+e.message+'. Download a notebook backup now; your work remains open.','error');}finally{b.disabled=false;}}
  if(window.ResizeObserver){const controlsObserver=new ResizeObserver(entries=>{document.body.style.setProperty('--teacher-controls-height',Math.ceil(entries[0].target.getBoundingClientRect().height)+'px');});controlsObserver.observe($('#teacher-controls'));}
  $('#topic').textContent=L.topic||L.title;$('#wagba').textContent='WAGBA · '+L.wagba;
  $('#ksu-strip').innerHTML=`<div class="ksu-summary">${['Knowledge','Skills','Understanding'].map(kind=>`<strong>${kind}</strong><span>${esc(L.ksu.filter(k=>k.kind.toLowerCase()===kind.toLowerCase()).map(k=>k.title).join(' · '))}</span>`).join('')}</div>`;$('#keywords').textContent='Keywords: '+(Array.isArray(L.keywords)?L.keywords.map(k=>typeof k==='string'?k:k.word+' — '+k.meaning).join('; '):L.keywords);$('#challenge').textContent='Challenge: '+L.challenge;
  $('#join-form').onsubmit=e=>{e.preventDefault();join($('#student-name').value);};$('#student-name').value=notebook.name||'';
  $('#local-start').onclick=()=>{const name=$('#student-name').value.trim();if(!name){notice('Enter your name first so your evidence is labelled.');$('#student-name').focus();return;}if(name.toLowerCase()==='teacher'){openPreview();return;}if(notebook.name&&notebook.name!==name){if(Object.keys(notebook.work).length&&!confirm('Start a separate notebook? Download the current student backup first.'))return;changeSession();LiveCloud.forgetJoin();notebook={version:1,name,class:'Year 10',stage:'ready',work:{},createdAt:new Date().toISOString()};current='ready';}else changeSession();for(const id of notebook.unsynced||[])if(order.includes(id))dirty.add(id);room=null;activeStorageKey=storageKey;notebook.name=name;role='student';localOnly=true;extensionId=notebook.work?.extension?.extensionId||L.extensions[0].id;showWorkspace();renderStage(permitted(notebook.stage)?notebook.stage:'ready');notice('Offline practice: your teacher cannot see this notebook live. Export your evidence and submit it in Teams.');};
  $('#teacher-toggle').onclick=()=>{if(running)return;snapshotEditor();$('#join').hidden=true;$('#workspace').hidden=true;$('#teacher-model-tools').hidden=true;$('#teacher-login').hidden=false;};$('#login-back').onclick=()=>{$('#teacher-login').hidden=true;if(role==='student'||role==='preview'){showWorkspace();applyEditing();}else $('#join').hidden=false;};$('#preview').onclick=openPreview;$('#teacher-form').onsubmit=teacherLogin;
  function navigate(id){if(!order.includes(id)||!permitted(id))return;renderStage(id);$('#main').focus({preventScroll:true});$('#route').scrollIntoView({block:'start',behavior:'auto'});}
  $('#route').onclick=e=>{const b=e.target.closest('[data-stage]');if(b&&!b.disabled)navigate(b.dataset.stage);};$('#previous').onclick=()=>navigate(order[order.indexOf(current)-1]);$('#next').onclick=()=>navigate(order[order.indexOf(current)+1]);$('#join-current').onclick=()=>{if(room&&permitted(room.stage)&&!running)navigate(room.stage);};$('#help').onclick=()=>{if(role!=='teacher')helpForm();};$('#pause').onclick=async()=>{if(role==='teacher')return;const version=sessionVersion;work().answers.pauseRequested='Please allow a pause and send one written next step.';changed();if(!localOnly&&role==='student')try{const updated=await LiveCloud.setHelp(true,'I need a pause. Please send one written next step.');if(version!==sessionVersion)return;learner=updated;notice('Your teacher has received a private pause request. Your draft remains saved.','success');}catch{if(version===sessionVersion)notice('Connection unavailable. Use Teams chat for your pause request. Your draft remains saved.');}else notice('Take a pause. Your draft remains saved; contact your teacher through Teams if needed.');};
  $('#export').onclick=exportPDF;$('#download-backup').onclick=async()=>{if(editor)work().code=editor.getValue();const backup=JSON.parse(JSON.stringify(notebook));backup.imageData={};for(const w of Object.values(backup.work))for(const im of w.images||[]){try{backup.imageData[im.id]=await imageGet(im.id);}catch{}}download(`Year10_FOR_${safeName(notebook.name)}_backup.json`,JSON.stringify(backup,null,2));};
  $('#return-entry').onclick=()=>{if(running||role==='teacher')return;changeSession();role='entry';room=null;restorePupilNotebook();$('#workspace').hidden=true;$('#teacher-model-tools').hidden=true;$('#teacher-controls').hidden=true;$('#teacher-login').hidden=true;$('#join').hidden=false;$('#return-entry').hidden=true;$('#student-name').value=notebook.name||'';notice('Your draft is saved. Download a backup before changing the student name. Use your teacher’s invitation to reconnect live.');};
  $('#restore-backup').onchange=async e=>{
    const file=e.target.files[0],version=sessionVersion;if(!file)return;
    try{
      if(role==='teacher'||role==='preview'||running)throw new Error('Restore a student backup from the student entry page after stopping any Python run.');
      if(file.size>40*1024*1024)throw new Error('Choose a notebook backup smaller than 40 MB.');
      const backup=JSON.parse(await file.text());if(version!==sessionVersion)return;
      if(backup?.version!==1||typeof backup.name!=='string'||!backup.name.trim()||!backup.work||typeof backup.work!=='object'||Array.isArray(backup.work))throw new Error('This is not a recognised Year 10 notebook backup.');
      for(const[id,w]of Object.entries(backup.work))if(!order.includes(id)||!w||typeof w!=='object'||!w.answers||typeof w.answers!=='object'||!Array.isArray(w.runs)||!Array.isArray(w.images)||typeof w.code!=='string')throw new Error('The backup contains an unrecognised stage or data format.');
      if(!confirm('Restore this notebook for '+backup.name+'? Download a backup of your current work first. Live access will require teacher admission again.'))return;
      for(const[id,data]of Object.entries(backup.imageData||{})){if(typeof data!=='string'||!/^data:image\/(png|jpeg|webp);base64,/.test(data)||data.length>4200000)throw new Error('An image in the backup is unsupported or too large.');await imagePut(id,data);if(version!==sessionVersion)return;}
      delete backup.imageData;changeSession();LiveCloud.forgetJoin();notebook=backup;activeStorageKey=storageKey;current=order.includes(backup.stage)?backup.stage:'ready';extensionId=backup.work.extension?.extensionId||L.extensions[0].id;role='entry';room=null;$('#workspace').hidden=true;$('#teacher-model-tools').hidden=true;$('#join').hidden=false;$('#student-name').value=backup.name;localSave();notice('Notebook restored on this device. Use offline practice, or rejoin with your teacher’s live invitation and wait for admission.','success');
    }catch(err){if(version===sessionVersion)notice('Backup could not be restored: '+err.message,'error');}finally{e.target.value='';}
  };
  window.addEventListener('beforeunload',()=>localSave());document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'){localSave();flush();}});
  initializeCloud();
})();
