window.LESSON = {
 id:'tta-y11-t1w5-s1-cyber-protection-9210-v1',version:1,
 title:'Cyber-security protection',
 wagba:'Explaining cyber-security protection methods and justifying which method is appropriate for a particular security risk.',
 challenge:'Why is there no single security measure that can protect a system from every threat?',
 stages:[
  {id:'start',title:'Do Now',subtitle:'Threats from last lesson',time:'00–05',min:5},
  {id:'before',title:'Types of Learning',subtitle:'Choose your starting point',time:'05–08',min:3},
  {id:'learn',title:'Main Task 1',subtitle:'Protect the user',time:'08–26',min:18},
  {id:'apply',title:'Main Task 2',subtitle:'Protect and test the system',time:'26–46',min:20},
  {id:'feedback',title:'Feedback & Improvement',subtitle:'Use the mark scheme precisely',time:'46–50',min:4},
  {id:'pit',title:'Learning Pitstop',subtitle:'Evidence of progress',time:'50–54',min:4},
  {id:'exit',title:'Plenary',subtitle:'Choose, explain and test',time:'54–58',min:4},
  {id:'submit',title:'Save & submit',subtitle:'Check your evidence',time:'58–60',min:2},
  {id:'extension',title:'Extension',subtitle:'Layered protection',time:'Optional',min:0}
 ],
 before:['Already knew / could do independently','With reading or a prompt','New to me','Not sure / not checked yet'],
 phases:['New learning — a good struggle','Consolidating','Treading water — I need more challenge','Drowning — I need help','Not attempted yet'],
 checks:[
  {id:'measures',type:'Knowledge',title:'Five protection measures',statement:'I can explain password systems, biometrics, CAPTCHA, email confirmation and automatic software updates.',hint:'Use the four Main Task 1 cards and the automatic-update card.',start:'Choose one method you are least able to explain.',actions:['Reopen one method and complete: it checks / prevents … by …','Explain all five methods without the headings.','Compare two methods and identify what each does not protect against.','Ask your teacher to model one protection mechanism step by step.']},
  {id:'pentest',type:'Knowledge',title:'Penetration testing',statement:'I can explain the purpose of penetration testing and distinguish its two testing situations.',hint:'Use the inside/basic-credentials versus outside/no-credentials comparison.',start:'Focus on why an organisation deliberately tests its own security.',actions:['Explain purpose first, then how the test is carried out.','Compare inside/basic credentials with outside/no credentials.','Explain why a successful test is useful rather than a failure of the exercise.','Ask your teacher to trace one penetration-testing scenario.']},
  {id:'match',type:'Skills',title:'Match method to risk',statement:'I can select a suitable protection method for a specific threat or scenario.',hint:'Use the comparison grid and scenario checks.',start:'Identify the risk before naming a control.',actions:['For one scenario write: risk → measure → how it helps.','Choose between two plausible measures and justify the better fit.','Explain why one control cannot solve every risk.','Ask your teacher to identify the key clue in one scenario.']},
  {id:'explain',type:'Skills',title:'Linked explanation',statement:'I can write a linked explanation showing what a security measure does and how that reduces a risk.',hint:'Use your original and improved assessment answers.',start:'Avoid vague phrases such as “it makes it safer”.',actions:['Add the missing mechanism to one answer.','Rewrite one explanation without a sentence starter.','Explain why an answer names a control but still misses the causal link.','Explain your answer aloud first, then record one precise sentence.']},
  {id:'layered',type:'Understanding',title:'Different risks need different controls',statement:'I can explain why different security threats need different forms of protection.',hint:'Think about bots, stolen passwords, software flaws and identity checks.',start:'Compare what each protection actually checks or changes.',actions:['Name one limitation of a chosen measure.','Build a two-control response for one scenario and explain each role.','Explain residual risk after one protection is in place.','Ask your teacher to compare CAPTCHA with email confirmation.']},
  {id:'testing',type:'Understanding',title:'Protection versus testing',statement:'I can explain why penetration testing is different from directly preventing an attack.',hint:'Penetration testing deliberately looks for weaknesses in existing protection.',start:'Separate “protect” from “test whether protection can be bypassed”.',actions:['Write one sentence beginning “Penetration testing does not directly…”','Explain what should happen after a weakness is discovered.','Compare penetration testing with automatic software updates.','Ask your teacher to distinguish the test from the fix.']}
 ],
 quizzes:[
  {id:'threat0',stage:'start',question:'A fake message asks a staff member to enter login details. Which threat is shown?',options:['Phishing','Adware','Shouldering','Outdated software'],correct:0,feedback:'Phishing fraudulently seeks private information, often through email or SMS.',source:'Week 4 retrieval · specification 3.6.1.1. Teacher-created scenario.'},
  {id:'threat1',stage:'start',question:'A student account can edit confidential staff files. Which threat is shown?',options:['Computer virus','Misconfigured access rights','Pharming','Weak Wi-Fi signal'],correct:1,feedback:'The permissions give the wrong user the wrong level of access.',source:'Week 4 retrieval · specification 3.6.1. Teacher-created scenario.'},
  {id:'threat2',stage:'start',question:'Software still contains a known security flaw because an update has not been installed. Which threat is shown?',options:['Unpatched / outdated software','Blagging','Shouldering','Default username'],correct:0,feedback:'Unpatched or outdated software may retain exploitable security weaknesses.',source:'Week 4 retrieval · specification 3.6.1. Teacher-created scenario.'},
  {id:'threat3',stage:'start',question:'Someone watches another user entering a password. Which threat is shown?',options:['Pharming','Shouldering','Trojan','Adware'],correct:1,feedback:'Shouldering means observing private information over someone’s shoulder.',source:'Week 4 retrieval · specification 3.6.1.1. Teacher-created scenario.'},
  {id:'passwordCheck',stage:'learn',question:'Which is an organisational password-system control rather than only advice to an individual?',options:['Require passwords to meet defined rules','Tell users to be careful','Hide the keyboard'],correct:0,feedback:'A secure system can enforce password rules instead of relying only on user choice.',source:'Textbook printed p.246 (uploaded PDF p.251). Teacher-created check.'},
  {id:'bioCheck',stage:'learn',question:'Why can a biometric check be useful on a mobile device?',options:['It uses a physical characteristic linked to the user','It makes the battery larger','It prevents every type of malware'],correct:0,feedback:'Biometrics use physical characteristics such as a fingerprint, iris or face to confirm identity.',source:'Textbook printed p.246 (uploaded PDF p.251). Teacher-created check.'},
  {id:'captchaCheck',stage:'learn',question:'What is the main purpose of a CAPTCHA?',options:['Confirm the exact identity of the account owner','Distinguish a human user from an automated program or bot','Encrypt every file on a device'],correct:1,feedback:'CAPTCHA is intended to check that the interaction is being performed by a person rather than automated software.',source:'Textbook printed p.247 (uploaded PDF p.252). Teacher-created check.'},
  {id:'emailCheck',stage:'learn',question:'What does an email confirmation directly show?',options:['The user can access the supplied email account','The user owns every device they use','The user can never be phished'],correct:0,feedback:'It checks access to the email address supplied. It does not perfectly prove identity.',source:'Textbook printed p.247; June 2025 9210/2 Q08.1–08.2. Teacher-created check.'},
  {id:'updateCheck',stage:'apply',question:'Why are automatic security updates useful?',options:['They can install fixes for known security flaws without relying on the user to remember','They stop all social engineering','They make every user an administrator'],correct:0,feedback:'Updates can patch known flaws; automatic updates also reduce reliance on a user remembering or agreeing to install them.',source:'June 2025 9210/2 Q08.3 mark scheme. Teacher-created check.'},
  {id:'pentestPurpose',stage:'apply',question:'What is the main purpose of penetration testing?',options:['Deliberately damage the organisation’s data','Test how effectively security can resist attempted access','Replace all passwords with biometrics'],correct:1,feedback:'Penetration testing attempts to get past security measures so weaknesses can be identified and fixed.',source:'Specification 3.6.1; November 2023 9210/2 Q11.2. Teacher-created check.'},
  {id:'pentestMode',stage:'apply',question:'A tester is given basic credentials and some knowledge of the target system. Which situation is being simulated?',options:['An attack from inside the system','An external attack with no knowledge','A CAPTCHA check'],correct:0,feedback:'The specification uses knowledge/basic credentials to simulate an attack from inside the system.',source:'Specification 3.6.1, p.29. Teacher-created check.'},
  {id:'choiceCheck',stage:'apply',question:'A website wants to reduce automated account creation. Which measure best matches that risk?',options:['CAPTCHA','MAC address filtering','Read-only access','Penetration testing'],correct:0,feedback:'CAPTCHA is designed to distinguish a human user from automated software.',source:'Specification 3.6.2; textbook printed p.247. Teacher-created scenario.'}
 ],
 fields:{
  focusReason:{stage:'before',label:'Optional: What helped you choose this focus?'},
  passwordWhy:{stage:'learn',label:'Why is enforcing password rules stronger than only telling users to choose good passwords?',help:'Think about what the system can require automatically.'},
  biometricLimit:{stage:'learn',label:'Give one limitation of biometric security compared with a password system.',help:'Use the textbook comparison if needed.'},
  emailSteps:{stage:'learn',label:'Describe how an email confirmation can be used to check access to an email address.'},
  updateLink:{stage:'apply',label:'Complete the link: known vulnerability → update / patch → …',help:'Explain what changes in the software.'},
  pentestDifference:{stage:'apply',label:'Explain the difference between the two penetration-testing situations in the specification.'},
  scenarioReason:{stage:'apply',label:'Choose one scenario from the comparison table. Explain why the selected measure fits the risk.'},
  pitEvidence:{stage:'pit',label:'Which answer or activity shows what you can now do?'},pitNext:{stage:'pit',label:'What specific action will you take next?'},
  plMeasure:{stage:'exit',label:'1. A school uses strong passwords and automatic updates. It wants to check whether someone outside the organisation could still gain access. Identify the most appropriate additional security activity.'},
  plHow:{stage:'exit',label:'2. Explain how that activity would be carried out.'},
  plFindings:{stage:'exit',label:'3. Explain what the school should do with any weaknesses found.'},
  extension:{stage:'extension',label:'Design a layered response for an online school portal. Choose three different security measures and explain the distinct role of each.'}
 },
 questions:[
  {id:'emailPurpose',group:'practice',stage:'apply',number:'08.1',official:true,prompt:'Describe the purpose of email confirmations.',marks:1,source:'June 2025 · 9210/2 · p.12 · Q08.1',image:'jun25-q08',msImage:'ms-jun25-q08',context:'Email confirmations are a cyber security measure.',guidance:'Award 1 mark for a clear purpose.',points:['To check the identity of a user, or to check that a user has access to a specific email address.'],hint:'What does following the message/link demonstrate about the email address?'},
  {id:'emailLimit',group:'practice',stage:'apply',number:'08.2',official:true,prompt:'Describe one limitation of the use of email confirmations.',marks:1,source:'June 2025 · 9210/2 · p.12 · Q08.2',image:'jun25-q08',msImage:'ms-jun25-q08',guidance:'Award 1 mark for one accepted limitation.',points:['It only confirms access to the email address and does not really confirm identity.','People can easily create fake email accounts.','It relies on the user’s email account being secure.','A confirmation may take time to arrive.','The user may be unable to access their email account.'],hint:'What does email confirmation fail to prove, or what does it depend on?'},
  {id:'autoUpdate',group:'practice',stage:'apply',number:'08.3',official:true,prompt:'Explain how automatic software updates can improve the security of a computer system.',marks:2,source:'June 2025 · 9210/2 · p.12 · Q08.3',image:'jun25-q08',msImage:'ms-jun25-q08',guidance:'Award up to 2 distinct points.',points:['Updating software fixes known security flaws/errors that could be exploited by malware or hackers.','Automatic updates can ensure flaws are fixed/patched as soon as a fix is available.','Automatic updates reduce reliance on the user remembering or agreeing to install updates.'],hint:'Link a known flaw to the patch, then explain why automatic delivery matters.'},
  {id:'pentest',group:'practice',stage:'apply',number:'11.2',official:true,prompt:'Describe what penetration testing is used for and how penetration testing is carried out.',marks:2,source:'November 2023 · 9210/2 · p.22 · Q11.2',image:'nov23-q11a',msImage:'ms-nov23-q11',guidance:'Award 1 mark for purpose and 1 mark for method.',points:['Used to check how effective cyber security is, or how effectively the system is protected against hacking.','Someone tries to break/get past the security measures that have been put in place.'],hint:'Why do the test, and what does the tester deliberately try to do?'},
  {id:'biometric',group:'practice',stage:'apply',number:'11.3',official:true,prompt:'State three advantages of biometric systems over password systems.',marks:3,source:'November 2023 · 9210/2 · p.23 · Q11.3',image:'nov23-q11b',msImage:'ms-nov23-q11',guidance:'Award up to 3 distinct advantages.',points:['Cannot be forgotten.','Cannot be shouldered.','Cannot be easily stolen.','The user cannot write down their biometric data.','Cannot be guessed.','Can be quicker to use than a password.'],hint:'Think about remembering, observing, stealing, guessing and speed.'},
  {id:'captcha',group:'practice',stage:'apply',number:'T1',official:false,prompt:'State the purpose of a CAPTCHA.',marks:1,source:'Teacher-written check · based on OxfordAQA 9210 3.6.2 and textbook p.247',guidance:'Award 1 mark for the core purpose.',points:['To check whether a user is a real human rather than a bot / automated computer program.'],hint:'What kind of user is CAPTCHA trying to distinguish from a person?'}
 ],
 glossary:[
  ['Password system','Rules and controls used to improve password security, for example enforcing stronger passwords.','Textbook p.246'],
  ['Biometric measure','A check using a physical characteristic to confirm identity, such as a fingerprint, iris or face.','Textbook p.246'],
  ['CAPTCHA','A check intended to distinguish a human user from automated software or a bot.','Textbook p.247'],
  ['Email confirmation','A message sent to a supplied email address so access to that address can be checked.','Textbook p.247; Jun25 Q08'],
  ['Automatic software update','A software update delivered automatically, helping patches/fixes be installed without relying on the user to remember.','Textbook p.247; Jun25 Q08.3'],
  ['Security patch','An update that fixes a security problem or known flaw.','Textbook p.241'],
  ['Penetration testing','Deliberately attempting to get past security measures in order to test how effective the protection is and identify weaknesses.','Spec 3.6.1; Nov23 Q11.2'],
  ['Credentials','Information used to authenticate or access a system, such as a username and password.','Spec 3.6.1 context'],
  ['Internal threat simulation','Tester has system knowledge and possibly basic credentials, simulating an attack from inside the system.','Spec 3.6.1'],
  ['External threat simulation','Tester has no knowledge of credentials, simulating an attack from outside the system.','Spec 3.6.1']
 ]
};