'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='y7-week5-theory-v1:',WAGBA='Use a loop to repeat Turtle instructions, and test and fix a simple program so that its drawing matches what we expect.';
let state=null,key='',worker=null,playback=null,timeout=null,running=false,traceIndex=0,pdfBlob=null;
const teacherMode=new URLSearchParams(location.search).get('teacher')==='1';
let classroomTarget=null;
const classroomLocked=()=>!teacherMode&&!!window.ClassroomMode?.locked();
const classroomChanged=()=>window.dispatchEvent(new Event('lesson:render'));
window.LESSON={stages:cards.map(c=>[c.id,c.title])};
window.LessonClassroom=Object.freeze({
 info:()=>({teacher:teacherMode,lang:state?.lang||'en',page:window.TeacherPresentation?.current()||cards[state?.card||0].id,entry:!state}),
 pages:()=>[...cards.map(c=>c.id),...(window.TeacherPresentation?.ids()||[])],
 label:()=>window.TeacherPresentation?.current()?window.TeacherPresentation.title():cards[state?.card||0].title,
 answer:id=>state?.notes['discussion-'+id]||'',
 setAnswer:(id,value)=>{if(state&&window.TeacherPresentation?.questions[id]){state.notes['discussion-'+id]=value;pdfBlob=null;save();}},
 move:id=>{if(teacherMode||(!cards.some(c=>c.id===id)&&!window.TeacherPresentation?.ids().includes(id)))return;if(!state){classroomTarget=id;return;}if(id.startsWith('slide-')){stop();$('#dialog')?.close();window.TeacherPresentation.open(id);return;}go(cards.findIndex(c=>c.id===id),true);},
 navigate:id=>{if(state&&cards.some(c=>c.id===id))go(cards.findIndex(c=>c.id===id));},
 clearTarget:()=>{classroomTarget=null;}
});
for(const type of ['click','change'])document.addEventListener(type,e=>{if(classroomLocked()&&e.target.closest('#jump,#back,#next,#leave,#restore,#resume,[data-return]')){e.preventDefault();e.stopImmediatePropagation();if(e.target.id==='jump')e.target.value=state.card;}},true);
const blank=(name,cls,lang)=>({name,cls,lang,card:0,answers:{},attempts:{},code:{},runs:{},ratings:{},done:{},notes:{},events:[],phases:{},levels:{},teacher:name.toLowerCase()==='teacher'});
function record(type,data){state.events.push({at:new Date().toISOString(),type,...data});save()}
function save(){try{localStorage.setItem(key,JSON.stringify(state));localStorage.setItem(KEY+'last',key);if($('#saved'))$('#saved').textContent='Saved on this device';}catch(e){if($('#saved'))$('#saved').textContent='Storage full/unavailable — download a backup now';}}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),60000)}
function filename(ext){return `Year7_${state.cls}_${state.name}_Week5_Theory.${ext}`.replace(/[^\w.\-]/g,'_')}
function landing(){stop();state=null;classroomChanged();$('#app').innerHTML=`<div class="landing"><section><div class="eyebrow">Year 7 · Week 5 · Theory · 60 minutes</div><h1>Repeat, check<br>and fix.</h1><p>Use Python Turtle to draw shapes with loops. Find mistakes, make one change and test again.</p><div class="read"><strong>WAGBA</strong><p>${WAGBA}</p></div><h3>What is learning?</h3><p>Amazing Learning happens when we practice, try hard and use good struggle to get better.</p><p class="small">Your work stays in this browser. No student account. Live classroom shares anonymous connection and page-control signals only. Download a backup on shared devices. Submit your PDF to <strong>Week 5 Theory</strong> in Teams.</p></section><form id="entry"><label for="name">Full name</label><input id="name" autocomplete="name" required><label for="class">Class</label><input id="class" placeholder="For example, 7T"><label for="language">Language support</label><select id="language"><option value="en">English</option><option value="zh">English + 中文 support</option></select><p class="small">Python commands stay in English. Support can be changed during the lesson.</p><div class="actions"><button class="primary">Start / resume my lesson</button><button type="button" id="resume">Resume last saved work</button></div><label for="restore">Restore a lesson backup (.json)</label><input type="file" id="restore" accept=".json"><p id="entry-error" class="notice" role="alert"></p></form></div>`;
$('#entry').onsubmit=e=>{e.preventDefault();const n=$('#name').value.trim(),c=$('#class').value.trim(),l=$('#language').value;if(!n||(!c&&n.toLowerCase()!=='teacher')){$('#entry-error').textContent='Enter your name and class to start.';return;}key=KEY+JSON.stringify([n.toLowerCase(),c.toLowerCase()]);try{state=JSON.parse(localStorage.getItem(key))||blank(n,c,l)}catch{state=blank(n,c,l)}state.lang=l;record('entry',{});render()};$('#resume').onclick=()=>{try{key=localStorage.getItem(KEY+'last');state=JSON.parse(localStorage.getItem(key));if(!validState(state))throw Error();render()}catch{$('#entry-error').textContent='No saved lesson found. Enter your details to start.'}};$('#restore').onchange=async e=>{try{const f=e.target.files[0];if(f.size>15000000)throw Error();const s=JSON.parse(await f.text());if(!validState(s))throw Error();state=s;state.teacher=state.name.toLowerCase()==='teacher';key=KEY+JSON.stringify([state.name.toLowerCase(),state.cls.toLowerCase()]);save();render()}catch{$('#entry-error').textContent='This is not a valid Week 5 lesson backup.'}}}
function validState(s){return s&&typeof s.name==='string'&&typeof s.cls==='string'&&Number.isInteger(s.card)&&s.card>=0&&s.card<cards.length&&['answers','attempts','code','runs','ratings','done','notes','phases','levels'].every(k=>s[k]&&typeof s[k]==='object'&&!Array.isArray(s[k]))&&Array.isArray(s.events)}
function field(id,label,placeholder=''){return `<label for="${id}">${label}</label><textarea id="${id}" data-note="${id}" placeholder="${esc(placeholder)}">${esc(state.notes[id]||'')}</textarea>`}
function render(){stop();let slideTarget=null;if(classroomTarget){if(classroomTarget.startsWith('slide-'))slideTarget=classroomTarget;else state.card=cards.findIndex(c=>c.id===classroomTarget);classroomTarget=null;}pdfBlob=null;const c=cards[state.card];traceIndex=0;$('#app').innerHTML=`<header><strong>Repeat, check & fix <span class="small">· Year 7</span></strong><span>${esc(state.name)} ${esc(state.cls)}</span><div class="toolbar"><button id="help">Device help</button><select id="lang" aria-label="Language support"><option value="en">English</option><option value="zh">English + 中文</option></select><button id="backup">Save backup</button><button id="leave">Change student</button><span class="save" id="saved" role="status">Saved on this device</span></div></header><div class="shell"><aside class="targets"><div class="eyebrow">Today's target · WAGBA</div><p>${WAGBA}</p><div class="extra-target">${Object.entries(objectives).map(([k,v])=>`<strong>${k}</strong><p>${v}</p>`).join('')}</div><p class="keyword-line"><strong>Keywords</strong><br>loop · range · counter · indentation · syntax · runtime · logic · debug</p><button id="words">Vocabulary / 词汇</button><p class="small">Card ${state.card+1} of ${cards.length}</p><progress class="progress" value="${Object.keys(state.done).length}" max="${cards.length-1}"></progress><label for="jump">Go to a card</label><select id="jump">${cards.map((x,i)=>`<option value="${i}" ${i===state.card?'selected':''}>${state.done[x.id]?'✓ ':''}${i+1}. ${esc(x.title)}</option>`).join('')}</select><p class="small">You may revisit any card. Missing core work is listed at submission.</p></aside><main class="card"><div class="eyebrow">${c.group} · ${c.time}</div><h2 tabindex="-1" id="title">${c.title}</h2><div class="read"><strong>READ FIRST</strong><p>${c.read}</p></div>${state.lang==='zh'?`<p class="translation" lang="zh">${c.zh}</p>`:''}${body(c)}<p id="notice" class="notice" role="alert"></p><div class="nav"><button id="back" ${state.card===0?'disabled':''}>← Back</button><button class="primary" id="next">${c.export?'Check submission':c.optional?'Save & continue →':'Complete & continue →'}</button></div></main></div><dialog id="dialog"></dialog>`;
$('#lang').value=state.lang;$('#lang').onchange=e=>{state.lang=e.target.value;record('language',{value:state.lang});render()};$('#backup').onclick=()=>download(new Blob([JSON.stringify(state)],{type:'application/json'}),filename('json'));$('#leave').onclick=()=>{save();landing()};$('#words').onclick=()=>modal('<h2>Vocabulary / 词汇</h2>'+[['Loop 循环','A group of instructions repeated.'],['Counter 计数变量','Here, i takes the next value from range each repetition.'],['Indentation 缩进','Spaces at the start show which lines belong together.'],['Syntax 语法','Rules for writing Python.'],['Runtime 运行时','When the program is executing.'],['Logic 逻辑','How your instructions produce the intended result.'],['Debug 调试','Find, change and retest a problem.']].map(([k,v])=>`<h3>${k}</h3><p>${v}</p>`).join(''));$('#help').onclick=()=>modal('<h2>Device help</h2><p><strong>iPad:</strong> Tap inside the code box. Use the four-space button to indent. No screenshots are needed: every run saves code and drawing automatically.</p><p><strong>PDF:</strong> Try Share PDF → Save to Files, or share to Teams if available. If Safari opens a preview, use Share → Save to Files. A website cannot choose a folder or bypass device permissions.</p><p><strong>Laptop:</strong> Download PDF, then find it in Downloads. Upload in Teams and press Turn in.</p><p><strong>Stuck?</strong> Open a hint, ask a partner to read one line, or ask your teacher. You can revisit cards without losing answers.</p>');$('#jump').onchange=e=>go(Number(e.target.value));$('#back').onclick=()=>go(state.card-1);$('#next').onclick=()=>next(c);
document.querySelectorAll('[data-note]').forEach(el=>el.oninput=()=>{state.notes[el.dataset.note]=el.value;save()});document.querySelectorAll('[data-rating]').forEach(el=>el.onchange=()=>{state.ratings[el.dataset.rating]=el.value;record('self-rating',{target:el.dataset.rating,value:el.value})});
(c.questions||[]).forEach(q=>{document.querySelectorAll(`[name="${q.id}"]`).forEach(el=>el.onchange=()=>{state.answers[q.id]=Number(el.value);record('answer',{question:q.id,value:Number(el.value)})});$(`#check-${q.id}`).onclick=()=>check(q)});
if(c.editor)bindEditor(c);if(c.trace){paint($('#drawing'),[]);$('#trace-next').onclick=trace;$('#trace-reset').onclick=()=>{traceIndex=0;paint($('#drawing'),[]);$('#trace-text').textContent='Turtle starts at (0, 0), facing right.';record('trace-reset',{})}}if(c.phase)$('#phase').onchange=e=>{state.phases.current=e.target.value;record('phase',{value:e.target.value})};if(c.poster)$('#poster-print').onclick=printPoster;if(c.export)bindExport();setupQuestions(c);save();classroomChanged();if(slideTarget)window.TeacherPresentation.open(slideTarget)}
function setupQuestions(c){const qs=c.questions||[];if(qs.length<2)return;const fields=qs.map(q=>$('#question-'+q.id));const controls=document.createElement('div');controls.className='actions';controls.innerHTML='<button id="qprev">← Previous question</button><span id="qcount" role="status"></span><button id="qnext">Next question →</button>';fields.at(-1).after(controls);let n=0;function show(i){n=Math.max(0,Math.min(qs.length-1,i));fields.forEach((f,j)=>f.hidden=j!==n);$('#qcount').textContent=`Question ${n+1} of ${qs.length}`;$('#qprev').disabled=n===0;$('#qnext').disabled=n===qs.length-1}fields.forEach((f,i)=>f.reveal=()=>show(i));$('#qprev').onclick=()=>show(n-1);$('#qnext').onclick=()=>{if(!state.attempts[qs[n].id]?.length){mark(fields[n],'Select an answer and press Check my thinking first.');return;}record('question-next',{card:c.id,question:qs[n].id});show(n+1)};show(0)}
function body(c){let h='';if(c.code)h+=`<pre>${esc(c.code)}</pre>`;if(c.compare)h+=`<div class="compare"><div><h3>Square: long</h3><pre>${esc(Array(4).fill('t.forward(80)\nt.right(90)').join('\n'))}</pre></div><div><h3>Square: loop</h3><pre>${esc(square)}</pre><h3>Triangle: loop</h3><pre>for i in range(3):\n    t.forward(80)\n    t.right(120)</pre><details><summary>Show the triangle's long version</summary><pre>${esc(Array(3).fill('t.forward(80)\nt.right(120)').join('\n'))}</pre></details></div></div>`;
if(c.ratings)h+=Object.entries(objectives).map(([k,v])=>`<div class="rating"><label for="${c.id}-${k}">${k}: ${v}</label><select id="${c.id}-${k}" data-rating="${c.id}-${k}"><option value="">Choose…</option>${ratings.map(r=>`<option ${state.ratings[c.id+'-'+k]===r?'selected':''}>${r}</option>`).join('')}</select></div>`).join('');
if(c.phase)h+=`<label for="phase">My current phase</label><select id="phase"><option value="">Choose…</option>${['New learning — I am trying something new','Consolidating — I am improving with practice','Treading water — I need a harder challenge','Drowning — I need help to take the next step'].map(r=>`<option ${state.phases.current===r?'selected':''}>${r}</option>`).join('')}</select>${field('next-action','My next step','For example: trace one loop with my teacher / try the harder challenge.')}`;
if(c.trace)h+=`<pre>${esc(square)}</pre><div class="actions"><button id="trace-next">Next instruction</button><button id="trace-reset">Restart trace</button></div><p id="trace-text" class="step-line" role="status">Turtle starts at (0, 0), facing right.</p><canvas id="drawing" class="canvas" width="640" height="400" aria-label="Step-by-step square trace"></canvas>`;
if(c.errorTable)h+='<table><tr><th>Problem</th><th>First check</th></tr><tr><td>Syntax / indentation</td><td>Colon, brackets and leading spaces</td></tr><tr><td>Runtime</td><td>Names and values used by the failing line</td></tr><tr><td>Logic</td><td>Expected shape, coordinates, turns and repetition count</td></tr></table>';
if(c.questions)h+=c.questions.map(q=>`<fieldset class="question" id="question-${q.id}"><legend>${q.text}</legend>${q.options.map((o,i)=>`<label><input type="radio" name="${q.id}" value="${i}" ${state.answers[q.id]===i?'checked':''}>${esc(o)}</label>`).join('')}<button id="check-${q.id}">Check my thinking</button><div id="feedback-${q.id}" aria-live="polite">${feedback(q)}</div></fieldset>`).join('');
if(c.levels||c.debugLevels)h+=`<h3>Choose one level</h3><div class="levels">${(c.levels||[['Incomplete shape'],['Indentation'],['Wrong direction']]).map((l,i)=>`<button data-level="${i}" class="${(state.levels[c.id]||0)===i?'selected':''}">Level ${i+1} · ${l[0]}</button>`).join('')}</div><div id="level-hint" class="read">${c.levels?c.levels[state.levels[c.id]||0][1]:debugHints[state.levels[c.id]||0]}</div>`;
if(c.editor)h+=`<div class="ide"><section><label for="code">Your Python instructions</label><p class="small">Setup supplied: <code>import turtle as t</code>. Every Run starts at (0, 0), facing right.</p><textarea id="code" class="editor" spellcheck="false" autocapitalize="off" autocorrect="off" aria-label="Python code">${esc(state.code[c.id]??c.editor)}</textarea><div class="actions"><button class="token" id="indent-code">4 spaces</button><button class="token" id="newline">New line</button><button id="reset-code">Reset code</button><button id="py-download">Download .py</button></div></section><section><h3>Your drawing</h3><canvas id="drawing" class="canvas" width="640" height="400" aria-label="Turtle output on coordinate axes"></canvas><p class="small">Centre = (0, 0). x: left/right. y: up/down.</p><div class="actions"><button class="primary" id="run">Run</button><button id="stop" disabled>Stop</button><select id="speed" aria-label="Drawing speed"><option value="normal">Watch drawing</option><option value="slow">Slow drawing</option><option value="instant">Instant</option></select></div><div id="console" class="console" role="status">${esc(lastRun(c)?.error||lastRun(c)?.output||'Ready. Your code and drawing are saved each time you run.')}</div></section></div>`;
if(c.hint)h+=`<details><summary>Need a hint?</summary><p>${c.hint}</p></details>`;if(c.reflection)h+=field(c.id+'-note','Explain briefly — a phrase is enough',c.reflection);
if(c.poster)h+=field('poster-title','Poster title','Turtle loops: repeat and check')+field('poster-commands','Three commands and their meanings','t.forward(60): move forward 60 units\nt.right(90): ...')+field('poster-example','One loop example','Write your code here')+field('poster-tip','One debugging tip','Check ... then ...')+'<button id="poster-print">Preview / print my poster</button>';
if(c.export)h+=`<div id="remaining"></div><div class="actions"><button id="review">Review my report</button><button id="pdf" class="primary">Download PDF</button><button id="share">Share PDF / Save to Files</button><a class="btn" href="https://teams.microsoft.com/" target="_blank" rel="noopener">Open Teams</a></div><p class="small">On iPad, a PDF may open as a preview. Tap Share → Save to Files, or use Share PDF above. Then attach it in Teams. No screenshots needed.</p><label><input type="checkbox" id="submitted" style="width:auto" ${state.notes.submitted?'checked':''}> I attached my PDF and selected Turn in in Teams.</label><p class="small">This is your confirmation; the app cannot verify Teams submission.</p>`;return h}
const debugHints=['Goal: complete a square with 60-unit sides. Check the repetitions.','Goal: complete a square. One command is not indented. Put it inside the loop.','Goal: go from (0, 0) to (0, -60). Turtle starts facing right. Check the turn direction.'];
const debugCodes=['for i in range(2):\n    t.forward(60)\n    t.right(90)','for i in range(4):\n    t.forward(60)\nt.right(90)','t.left(90)\nt.forward(60)'];
function feedback(q){const a=state.attempts[q.id];if(!a?.length)return '';const last=a[a.length-1];return `<p class="feedback ${last.correct?'':'retry'}">${last.correct?'Correct.':'Not quite — read the clue and try again.'} ${esc(q.why)}</p>`}
function check(q){const v=state.answers[q.id];if(v===undefined){mark($(`#question-${q.id}`),'Choose an answer, then check your thinking.');return;}state.attempts[q.id]??=[];state.attempts[q.id].push({value:v,correct:v===q.answer,at:new Date().toISOString()});record('check',{question:q.id,value:v});$(`#feedback-${q.id}`).innerHTML=feedback(q);$(`#question-${q.id}`).classList.remove('missing')}
function mark(el,msg){$('#notice').textContent=msg;if(el){el.reveal?.();el.classList.add('missing');el.scrollIntoView({block:'center',behavior:'smooth'});(el.matches('input,select,textarea,button')?el:el.querySelector('input,select,textarea,button'))?.focus()}}
function missing(c){const list=[];for(const q of c.questions||[])if(!state.attempts[q.id]?.length)list.push([`#question-${q.id}`,'Choose an answer and press Check my thinking.']);if(c.ratings)for(const k of Object.keys(objectives))if(!state.ratings[c.id+'-'+k])list.push([`#${c.id}-${k}`,'Choose how you feel about this target. Every choice is valid.']);if(c.editor&&!state.runs[c.id]?.length)list.push(['#run','Run your code once. An attempt counts even if you need more help.']);if(c.reflection&&!state.notes[c.id+'-note']?.trim())list.push([`#${c.id}-note`,'Add a short phrase. Use the sentence starter; spelling is not marked.']);if(c.phase&&!state.phases.current)list.push(['#phase','Choose your current learning phase.']);if(c.phase&&!state.notes['next-action']?.trim())list.push(['#next-action','Write a short next step, such as “ask for help”.']);return list}
function next(c){if(classroomLocked())return;if(c.export){$('#notice').textContent=state.notes.submitted?'Thank you. Keep your PDF and backup until your teacher checks them.':'Attach your PDF in Teams, select Turn in, then tick the confirmation.';return;}if(running){mark($('#stop'),'Wait for the drawing to finish or press Stop.');return;}const m=missing(c);if(m.length&&!c.optional&&!state.teacher){mark($(m[0][0]),m[0][1]);return;}if(!c.optional||state.runs[c.id]?.length||c.poster&&state.notes['poster-title'])state.done[c.id]=true;record('complete',{card:c.id,optional:!!c.optional});go(state.card+1)}
function go(i,remote=false){if(!state||(!remote&&classroomLocked()))return;window.TeacherPresentation?.close();state.card=Math.max(0,Math.min(cards.length-1,i));record('navigate',{card:cards[state.card].id});render();$('#title').focus();window.scrollTo(0,0)}
function modal(html){const d=$('#dialog');if(html.includes('Vocabulary /'))html='<h2>Learning targets</h2>'+Object.entries(objectives).map(([k,v])=>`<h3>${k}</h3><p>${v}</p>`).join('')+html;d.innerHTML=html+'<p><button id="close-dialog">Close</button></p>';d.showModal();$('#close-dialog').onclick=()=>d.close()}
function lastRun(c){return state.runs[c.id]?.at(-1)}
function bindEditor(c){const e=$('#code');paint($('#drawing'),lastRun(c)?.draws||[]);e.oninput=()=>{state.code[c.id]=e.value;save()};function insert(s){e.setRangeText(s,e.selectionStart,e.selectionEnd,'end');e.dispatchEvent(new Event('input'));e.focus()}$('#indent-code').onclick=()=>insert('    ');$('#newline').onclick=()=>insert('\n');e.onkeydown=v=>{if(v.key==='Tab'){v.preventDefault();insert('    ')}if((v.ctrlKey||v.metaKey)&&v.key==='Enter'){v.preventDefault();run(c)}};$('#run').onclick=()=>run(c);$('#stop').onclick=()=>{stop();$('#console').textContent='Stopped. Check your instructions, then run again.';record('stop',{card:c.id})};$('#reset-code').onclick=()=>{if(confirm('Replace this code with the starter? Previous runs remain in your report.')){state.code[c.id]=c.editor;record('reset-code',{card:c.id});render()}};$('#py-download').onclick=()=>download(new Blob(['import turtle as t\n\n'+e.value+'\n\nt.done()\n'],{type:'text/x-python'}),filename(c.id+'.py'));document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{const n=Number(b.dataset.level);if(c.debugLevels&&state.code[c.id]&&!confirm('Load this challenge? Your previous runs remain saved.'))return;state.levels[c.id]=n;if(c.debugLevels)state.code[c.id]=debugCodes[n];record('level',{card:c.id,value:n});render()})}
function stop(){clearTimeout(timeout);worker?.terminate();worker=null;playback?.cancel();playback=null;running=false;if($('#run'))$('#run').disabled=false;if($('#stop'))$('#stop').disabled=true}
async function run(c){if(running)return;if(c.predict&&state.answers.p1===undefined){mark($('#question-p1'),'Make your prediction before running.');return;}const code=$('#code').value;state.code[c.id]=code;running=true;$('#run').disabled=true;$('#stop').disabled=false;$('#console').textContent='Running Python…';paint($('#drawing'),[]);record('run-start',{card:c.id});const fail=msg=>{stop();if($('#console'))$('#console').textContent=msg};try{const url=URL.createObjectURL(new Blob([window.PYTHON_RUNNER_SOURCE],{type:'application/javascript'}));worker=new Worker(url);URL.revokeObjectURL(url);worker.onerror=()=>fail('Python could not load. Host the extracted folder on a static web server; direct file opening may be blocked. Your answers are saved.');timeout=setTimeout(()=>fail('Execution stopped after 6 seconds. Check for too many repetitions. Your code is saved.'),6000);worker.onmessage=e=>{if(e.data.type==='ready'){worker.postMessage({type:'run',code:'import turtle as t\n'+code});return;}if(e.data.type!=='result')return;clearTimeout(timeout);const r=e.data;worker.terminate();worker=null;const error=(r.error||'').replace(/line (\d+)/g,(_,n)=>'line '+Math.max(1,Number(n)-1));const run={code,ok:r.ok,error,output:r.output,draws:r.draws,at:new Date().toISOString(),level:state.levels[c.id]||0};state.runs[c.id]??=[];state.runs[c.id].push(run);record('run-result',{card:c.id,ok:r.ok});$('#console').textContent=error?error+'\nRead the line, change one thing, then run again.':(r.output||'')+'\nPython finished. Watch and compare your drawing with the target.';playback=TurtlePlayback.start(r.draws,{speed:()=>$('#speed')?.value||'instant',paint:ds=>paint($('#drawing'),ds),done:()=>{running=false;$('#run').disabled=false;$('#stop').disabled=true;playback=null;save()}})};}catch(e){fail('This browser blocked the Python worker. Open the hosted app instead of the file preview.')}}
function paint(canvas,draws){if(!canvas)return;const ctx=canvas.getContext('2d'),w=640,h=400;ctx.fillStyle='white';ctx.fillRect(0,0,w,h);ctx.lineWidth=1;ctx.font='12px Arial';for(let x=20;x<640;x+=50){ctx.strokeStyle='#eef1f4';ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<400;y+=50){ctx.strokeStyle='#eef1f4';ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}ctx.strokeStyle='#9baec0';ctx.beginPath();ctx.moveTo(0,200);ctx.lineTo(640,200);ctx.moveTo(320,0);ctx.lineTo(320,400);ctx.stroke();ctx.fillStyle='#61768c';for(let x=-300;x<=300;x+=100)ctx.fillText(x,320+x+3,216);for(let y=-100;y<=100;y+=100)if(y)ctx.fillText(y,325,200-y);ctx.fillText('x',625,190);ctx.fillText('y',330,14);let pos=[0,0];const lastClear=draws.map(x=>!!x.clear).lastIndexOf(true);for(const d of draws.slice(lastClear+1)){if(!d.to)continue;if(d.pen){ctx.strokeStyle=d.color;ctx.lineWidth=d.width;ctx.beginPath();ctx.moveTo(320+d.from[0],200-d.from[1]);ctx.lineTo(320+d.to[0],200-d.to[1]);ctx.stroke()}pos=d.to}ctx.fillStyle='#164f3b';ctx.beginPath();ctx.arc(320+pos[0],200-pos[1],5,0,7);ctx.fill()}
function trace(){if(traceIndex>=8)traceIndex=0;traceIndex++;const n=traceIndex,p=[[0,0],[80,0],[80,-80],[0,-80],[0,0]],draws=[];for(let i=0;i<Math.ceil(n/2);i++)draws.push({from:p[i],to:p[i+1],pen:true,color:'#216ca5',width:3});paint($('#drawing'),draws);$('#trace-text').textContent=`Repetition ${Math.ceil(n/2)} · i = ${Math.floor((n-1)/2)} · ${n%2?'t.forward(80) moves one side.':'t.right(90) turns ready for the next side.'}`;record('trace',{instruction:n})}
function reportLines(){const a=[['Year 7 · Week 5 Theory',state.name+' | '+state.cls],['WAGBA',WAGBA],...Object.entries(objectives),['Record','Self-ratings are student reflections, not verified grades. Runs record attempts, not automatic proof of a correct shape.']];for(const c of cards){if(c.export)continue;const lines=[];for(const q of c.questions||[]){if(state.answers[q.id]!==undefined)lines.push(q.text+'\nLatest choice: '+q.options[state.answers[q.id]]);const attempts=state.attempts[q.id]||[];if(attempts.length)lines.push('Checks: '+attempts.map((x,i)=>`${i+1}. ${q.options[x.value]} (${x.correct?'correct':'review needed'})`).join(' | '))}for(const k of Object.keys(objectives))if(state.ratings[c.id+'-'+k])lines.push(k+': '+state.ratings[c.id+'-'+k]);if(c.phase)lines.push('Phase: '+(state.phases.current||'Not selected'),'Next step: '+(state.notes['next-action']||'Not answered'));if(state.notes[c.id+'-note'])lines.push('Explanation: '+state.notes[c.id+'-note']);const runs=state.runs[c.id]||[];if(runs.length){lines.push('Run attempts: '+runs.length);runs.forEach((r,i)=>lines.push(`Run ${i+1} (${r.at}) — ${r.ok?'ran':'error'}\n${r.code}\n${r.output||''}\n${r.error||''}`))}if(state.code[c.id]!==undefined)lines.push('Latest editor code (may differ from last run):\n'+state.code[c.id]);if(c.poster)for(const k of ['title','commands','example','tip'])if(state.notes['poster-'+k])lines.push(k+': '+state.notes['poster-'+k]);if(lines.length)a.push([c.title,lines.join('\n\n')]);}for(const[id,question]of Object.entries(window.TeacherPresentation?.questions||{})){if(state.notes['discussion-'+id])a.push(['Class discussion',question+'\n\n'+state.notes['discussion-'+id]]);}a.push(['Activity record',state.events.map(e=>e.at+' '+e.type+' '+JSON.stringify(Object.fromEntries(Object.entries(e).filter(([k])=>!['at','type'].includes(k))))).join('\n')]);a.push(['Teams submission',state.notes.submitted?'Student confirmed Turn in. Not independently verified.':'Not yet confirmed. Upload this PDF to Week 5 Theory in Teams and select Turn in.']);return a}
function bindExport(){const incomplete=cards.filter(c=>!c.optional&&!c.export&&missing(c).length);$('#remaining').innerHTML=incomplete.length?`<div class="question"><strong>Core cards to revisit</strong><p>You can save a draft PDF now. These cards still have missing work:</p>${incomplete.map(c=>`<button data-return="${cards.indexOf(c)}">${c.title}</button>`).join(' ')}</div>`:'<p class="feedback">All required responses have been attempted. Review your evidence before submitting.</p>';document.querySelectorAll('[data-return]').forEach(b=>b.onclick=()=>go(Number(b.dataset.return)));$('#review').onclick=()=>modal('<h2>Evidence review</h2>'+reportLines().filter(([t])=>t!=='Activity record').map(([t,v])=>`<h3>${esc(t)}</h3><pre>${esc(v)}</pre>`).join(''));$('#pdf').onclick=()=>{record('pdf-download',{});download(makePDF(),filename('pdf'));$('#notice').textContent='Next: save the PDF, attach it to Week 5 Theory in Teams, then press Turn in.'};$('#share').onclick=async()=>{try{const f=new File([makePDF()],filename('pdf'),{type:'application/pdf'});if(navigator.canShare?.({files:[f]})){await navigator.share({files:[f],title:'Week 5 Theory evidence'});record('pdf-share',{})}else{download(f,filename('pdf'));$('#notice').textContent='Sharing is unavailable here. If the PDF opens, use Share → Save to Files.'}}catch(e){$('#notice').textContent='Sharing was cancelled or unavailable. Your work is safe; try Download PDF.'}};$('#submitted').onchange=e=>{state.notes.submitted=e.target.checked;record('teams-self-confirmation',{value:e.target.checked})}}
function makePDF(){const {jsPDF}=window.jspdf;const doc=new jsPDF();let y=18;doc.setFont('helvetica');function text(s,size=10){s=String(s);if(/[^\x20-\x7E\n]/.test(s)){const cv=document.createElement('canvas');cv.width=1500;cv.height=55;const cx=cv.getContext('2d');cx.font='28px Arial, sans-serif';const lines=[];for(const paragraph of s.split('\n')){let line='';for(const char of paragraph){if(cx.measureText(line+char).width>1460){lines.push(line);line=''}line+=char}lines.push(line)}for(const line of lines){if(y>280){doc.addPage();y=18}cx.fillStyle='white';cx.fillRect(0,0,1500,55);cx.fillStyle='#17212b';cx.fillText(line,0,35);doc.addImage(cv.toDataURL('image/png'),'PNG',16,y-4,178,6.5);y+=6.5}y+=4;return;}doc.setFontSize(size);const lines=doc.splitTextToSize(s,178);for(const l of lines){if(y>280){doc.addPage();y=18}doc.text(l,16,y);y+=size*.48}y+=4}text('Year 7 Week 5 Theory',18);text('Exported '+new Date().toLocaleString(),9);for(const [title,value]of reportLines()){text(title,13);text(value);const c=cards.find(c=>c.title===title);if(c&&lastRun(c)){if(y>175){doc.addPage();y=18}const cv=document.createElement('canvas');cv.width=640;cv.height=400;paint(cv,lastRun(c).draws);doc.addImage(cv.toDataURL('image/png'),'PNG',16,y,160,100);y+=107;text('Drawing from the latest recorded run; compare with the task target.',9)}}return doc.output('blob')}
function printPoster(){const p=['title','commands','example','tip'].map(k=>state.notes['poster-'+k]||'');if(!p[0].trim()){mark($('#poster-title'),'Add your poster title first.');return;}const w=window.open('','_blank');if(!w){$('#notice').textContent='Allow pop-ups to preview your poster, or include it in your PDF report.';return;}w.document.write('<!doctype html><title>My Turtle poster</title><style>body{font:22px Arial;margin:50px;color:#17212b}pre{white-space:pre-wrap;padding:20px;background:#f2f5f7}button{padding:15px}</style><button onclick="window.print()">Print / Save as PDF</button><h1>'+esc(p[0])+'</h1><h2>Commands</h2><pre>'+esc(p[1])+'</pre><h2>Loop example</h2><pre>'+esc(p[2])+'</pre><h2>Debugging tip</h2><p>'+esc(p[3])+'</p>');w.document.close();record('poster-preview',{})}
landing();
