/* Local-only lesson. No analytics, accounts, external execution or teacher dashboard. */
(()=>{'use strict';
const L=Lesson,$=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ROOT='y7-w3-first-route-v1:',STEPS=L.cards;let s=null,lang='en',extension=null,worker=null,workerURL=null,frame=null,frameListener=null,runTimer=null,startTimer=null,busy=false,pdfFile=null,dbPromise=null,shots=new Map(),storageIssue='',notice='',saveTimer=null,focusWorkspace=false,playback=null,playbackDraws=null,playbackReplay=false;
const pair=(en,zh)=>L.p(en,zh),both=p=>esc(p.en)+(lang==='zh'&&p.zh?`<span class="zh" lang="zh-Hans">${esc(p.zh)}</span>`:''),t=(en,zh)=>both(pair(en,zh)),plain=(en,zh)=>lang==='zh'?en+' / '+zh:en;
const b=(en,zh,action,cls='',extra='')=>`<button type="button" data-action="${action}" class="${cls}" ${extra}>${t(en,zh)}</button>`;
const safeName=x=>x.normalize('NFKC').replace(/[^\p{L}\p{N}_-]+/gu,'_').slice(0,65)||'Student';
const filename=suffix=>`Year7_${safeName(s.klass||'Test')}_${safeName(s.name)}_Week3_${suffix}`;
const key=(name,klass)=>ROOT+(name.trim().toLowerCase()==='teacher'?'teacher':encodeURIComponent(klass.trim().toLowerCase())+':'+encodeURIComponent(name.trim().toLowerCase()));
function fresh(name,klass){return {schema:1,sequenceVersion:2,name,klass,teacher:name.toLowerCase()==='teacher',lang,device:'auto',current:0,done:{},answers:{},checked:{},attempts:[],checks:{},support:{},work:{practice:{code:'',runs:[],draws:[]},route:{code:'# My first journey\n',runs:[],draws:[]}},events:[],extensions:[],snapshots:[],created:new Date().toISOString(),updated:new Date().toISOString()};}
function migrate(state){if(!state.sequenceVersion){if(state.current>=11)state.current++;if(state.done.pitstop||state.done.export)state.done.drawing=state.done.pitstop||state.done.export;state.sequenceVersion=2;}return state;}
function challenge(id){return [...L.extensions,...L.drawings].find(x=>x.id===id);}
function cur(){if(extension){const e=challenge(extension);return {id:'ext-'+e.id,title:e.title,stage:e.drawing?'Optional extension 2':'Optional extension',kind:'code',drawing:!!e.drawing,sample:e.sample,workspace:'ext-'+e.id,read:e.read,action:e.drawing?pair('RUN the example. Then follow YOUR CHALLENGE below to make a new drawing. RUN again and check its position.','运行示例，然后按照下方挑战创作新图画。再次运行并检查位置。'):pair('EDIT your practice copy. RUN to test. Add a short note, then return to the choices.','修改练习副本并运行测试。写一个简短说明，然后返回选择。')};}return STEPS[s?.current||0];}
function wk(){return s.work[cur().workspace||'route'];}
function log(action,value='',card=cur().id){if(!s)return;s.events.push({at:new Date().toISOString(),card,action,value:String(value).slice(0,4000)});if(s.events.length>1000){s.events.shift();s.olderEvents=(s.olderEvents||0)+1;}save();}
function save(now=false){if(!s)return;clearTimeout(saveTimer);const go=()=>{if(extension){const att=[...s.extensions].reverse().find(x=>x.id===extension&&!x.ended),w=s.work['ext-'+extension];if(att&&w)Object.assign(att,{code:w.code,draws:w.draws,lastCode:w.lastCode,note:s.answers['note-'+extension]||'',runs:w.runs.slice(att.runStart)});}try{s.lang=lang;s.updated=new Date().toISOString();localStorage.setItem(key(s.name,s.klass),JSON.stringify(s));localStorage.setItem(ROOT+'last',JSON.stringify({name:s.name,klass:s.klass}));storageIssue='';if($('saved'))$('saved').textContent=plain('Saved on this browser','已保存到本浏览器');}catch(e){storageIssue=plain('Saving is blocked or storage is full. Keep this page open and download a backup before leaving.','保存被阻止或空间已满。请保持页面打开，并在离开前下载备份。');if($('saved'))$('saved').textContent=plain('Not saved — make a backup','未保存，请备份');}if($('storage-warning'))$('storage-warning').textContent=storageIssue;};if(now)go();else saveTimer=setTimeout(go,180);}
function db(){if(!dbPromise)dbPromise=new Promise((res,rej)=>{const r=indexedDB.open('y7-w3-route-evidence',1);r.onupgradeneeded=()=>r.result.createObjectStore('images');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});return dbPromise;}
async function putShot(id,image){const k=key(s.name,s.klass)+':'+id;shots.set(k,image);try{const d=await db();await new Promise((res,rej)=>{const tx=d.transaction('images','readwrite');tx.objectStore('images').put(image,k);tx.oncomplete=res;tx.onerror=()=>rej(tx.error);});return true;}catch(e){notice=plain('Your picture is held in this open page only. Export the PDF or a backup before closing.','图片只暂存在当前页面。关闭前请导出 PDF 或备份。');return false;}}
async function getShot(id){const k=key(s.name,s.klass)+':'+id;if(shots.has(k))return shots.get(k);try{const d=await db();return await new Promise((res,rej)=>{const r=d.transaction('images').objectStore('images').get(k);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}catch{return null;}}
function say(msg){$('announcement').textContent=msg;}
function header(){return `<header class="topbar"><div><strong>Year 7 · Week 3 Project</strong><div class="identity">${s?esc(s.name)+(s.klass?' · '+esc(s.klass):''):t('My first working route','我的第一段路线')}</div></div><div class="tools"><label for="language" class="sr-only">Language support</label><select id="language"><option value="en" ${lang==='en'?'selected':''}>English</option><option value="zh" ${lang==='zh'?'selected':''}>English + 中文</option></select>${b('Device & saving help','设备与保存帮助','help','small')}${s?b('Lesson cards','课程卡片','journey','small'):''}${s?b('Change student','切换学生','logout','small'):''}</div></header>`;}
function learning(){return `<aside class="learning" aria-label="Learning goals"><div class="brand">My first working route</div><strong>WAGBA</strong><p class="wagba">${both(L.goals.wagba)}</p><div class="words"><strong>${t('Keywords','关键词')}: </strong>${L.terms.map((x,i)=>`<button class="word" data-action="word:${i}">${esc(x[0])}${lang==='zh'?' · '+esc(x[1]):''}</button>`).join(' ')}</div><details><summary>${t('Knowledge · Skills · Understanding','知识 · 技能 · 理解')}</summary><span class="mobile-expand"></span></details><div class="ksu">${['knowledge','skills','understanding'].map(k=>`<p><strong>${{knowledge:'Knowledge',skills:'Skills',understanding:'Understanding'}[k]}</strong><br>${both(L.goals[k])}</p>`).join('')}<p><strong>${t('Today’s outcome','今天的成果')}</strong><br>${t('A first route, version 1, and code + drawing evidence.','一段路线、第 1 版以及代码和图形证据。')}</p></div></aside>`;}
function landing(){let last=null;try{last=JSON.parse(localStorage.getItem(ROOT+'last'));}catch{}$('app').innerHTML=header()+`<main id="main" class="landing"><div class="card hero"><div><div class="stage">60 minutes · Python Turtle</div><h1>${t('Help Sam reach Reception.','帮助 Sam 到达接待处。')}</h1><p class="lead">${t('Write a short route. Test your drawing. Save your first working version.','编写一段路线，测试图形，保存第一个可运行版本。')}</p><p>${both(L.goals.wagba)}</p><form id="entry" class="entry" novalidate><div><label for="name">${t('Your full name','你的姓名')}</label><input id="name" type="text" maxlength="80" autocomplete="name" required></div><div><label for="klass">${t('Class','班级')}</label><input id="klass" type="text" maxlength="40" placeholder="e.g. 7T" required></div><label for="device">${t('Your device','你的设备')}</label><select id="device"><option value="auto">Choose / 选择</option><option value="ipad">iPad / tablet</option><option value="computer">Mac / laptop / computer</option></select><p class="note">${t('Use English or English + 中文 above. You can change support at any time.','在上方选择 English 或 English + 中文。随时可以更改。')}</p><div id="entry-error" role="alert"></div><button type="submit" class="primary">${t('Start / resume my lesson','开始 / 继续学习')}</button>${last?b('Resume my saved work','继续已保存的学习','resume','secondary'):''}${b('Restore a backup','恢复备份','restore','small')}<input id="restore-file" type="file" accept=".json" hidden></form></div><div><img src="assets/practice-school-picture.png" alt="Practice school with Main Entrance below Reception, Library and Computer Room C1, connected by corridors."><p class="note">${t('You will use a matching coordinate map inside the lesson. No account or manual screenshot is needed.','课程内会使用对应的坐标地图。不需要账户或手动截图。')}</p><p class="note">${t('Work stays in this browser. On shared devices, enter your own name and class. Export before clearing browser data. Your teacher sees only what you submit.','作品保存在本浏览器。共用设备时请输入自己的姓名和班级。清理浏览数据前请导出。老师只能看到你提交的作品。')}</p><p><strong>${t('Submit','提交')}:</strong> PDF + Python (.py)<br>Teams → <strong>Week 3 Project</strong></p></div></div></main>`;}
function enter(name,klass,device='auto'){name=name.trim();klass=klass.trim();if(!name||(!klass&&name.toLowerCase()!=='teacher')){$('entry-error').innerHTML=`<p class="validation">${t('Enter your name and class before starting.','开始前请输入姓名和班级。')}</p>;`;(name?$('klass'):$('name')).focus();return;}let saved=null;try{saved=JSON.parse(localStorage.getItem(key(name,klass)));}catch{}s=saved&&saved.schema===1?migrate(saved):fresh(name,klass);s.teacher=name.toLowerCase()==='teacher';if(s.teacher)s.klass='';if(device!=='auto')s.device=device;lang=saved?.lang||lang;extension=null;s.current=Math.max(0,Math.min(STEPS.length-1,s.current||0));log(saved?'Resumed lesson':'Started lesson');save(true);render();}
function mapHTML(id='map'){if(cur().drawing)return `<div class="map-box"><canvas id="${id}" width="800" height="600" role="img" aria-label="Blank drawing grid with x and y axes"></canvas><p class="map-caption">${t('Blank grid. Start (0, 0), facing right. Each small square = 50.','空白网格。从 (0, 0) 开始，面向右方。每小格 = 50。')}</p></div>`;return `<div class="map-box"><canvas id="${id}" width="800" height="600" role="img" aria-label="Coordinate map: Main Entrance (0, -200), corner (0, -100), Reception (-200, -100), Library (-200, 100), Computer Room C1 (200, 100). Corridors join these places."></canvas><p class="map-caption">${t('x: left / right. y: up / down. Each small square = 50.','x 表示左右，y 表示上下。每小格为 50。')}</p><div class="map-key"><span>${t('START (0, -200)','起点 (0, -200)')}</span><span>${t('Corner (0, -100)','转角 (0, -100)')}</span><span>${t('Reception (-200, -100)','接待处 (-200, -100)')}</span></div></div>`;}
function question(q){const val=s.answers[q.id],checked=s.checked[q.id]===val;return `<fieldset class="question" id="field-${q.id}"><legend>${both(q.label)}</legend>${q.choices.map((x,i)=>`<label class="option"><input type="radio" name="${q.id}" value="${i}" data-answer="${q.id}" ${String(val)===String(i)?'checked':''}><span>${both(x)}</span></label>`).join('')}${checked?`<div class="feedback">${t(Number(val)===q.correct?'You have it.':'Let’s compare your idea with the example.',Number(val)===q.correct?'答对了。':'把你的想法和示例比较一下。')} ${both(q.feedback)}</div>`:''}</fieldset>`;}
function textAnswer(id,label,zh,placeholder='',rows=2){return `<div class="question" id="field-${id}"><label for="${id}">${t(label,zh)}</label>${placeholder?`<p class="note">${esc(placeholder)}</p>`:''}<textarea id="${id}" data-answer="${id}" rows="${rows}" maxlength="3000">${esc(s.answers[id]||'')}</textarea></div>`;}
function choice(id,label,zh,options){return `<fieldset class="question" id="field-${id}"><legend>${t(label,zh)}</legend>${options.map((x,i)=>`<label class="option"><input type="radio" name="${id}" value="${i}" data-answer="${id}" ${String(s.answers[id])===String(i)?'checked':''}><span>${t(x[0],x[1])}</span></label>`).join('')}</fieldset>`;}
function checkButton(){return b('Check my thinking','检查我的想法','check','secondary');}
function codeTokens(){return cur().drawing?['t.forward(', 't.right(', 't.circle(', ')', ', ', '-', '\n']:['t.goto(', ')', ', ', '-', '\n'];}
function codeEditor(){const w=wk();return `<div class="split work-grid"><div><div class="editor"><label for="code">${t('Your Python instructions','你的 Python 指令')}<span>t = Turtle</span></label><textarea id="code" spellcheck="false" autocapitalize="off" autocorrect="off" translate="no" aria-describedby="codehelp">${esc(w.code)}</textarea><div class="tokens">${codeTokens().map((x,i)=>`<button type="button" data-token="${i}" aria-label="${x==='\n'?'Insert new line':'Insert '+esc(x)}">${x==='\n'?'↵':esc(x)}</button>`).join('')}</div></div><p id="codehelp" class="note">${t('One command per line. Check the dot, brackets and comma. Ctrl/⌘ + Enter runs your code.','每行一条指令，检查点号、括号和逗号。Ctrl/⌘ + Enter 可运行代码。')}</p><div class="runbar">${b('Run','运行','run','primary',busy?'disabled':'')}${b('Stop','停止','stop','',busy?'':'disabled')}${b('Undo edit','撤销编辑','undo','small')}${b('Show a hint','提示','hint','small')}</div>${playbackControls()}<div id="console" class="console" role="status">${esc(w.message||plain('Ready. Type your command, then press Run.','准备就绪。输入指令后点击运行。'))}</div><details class="setup"><summary>${t('See the setup prepared for me','查看已准备好的代码')}</summary><pre>${esc(setup(!!cur().drawing))}</pre><p class="note">${t('This runs before your commands. You do not need to type this setup.','这些代码会先运行，你不需要输入准备代码。')}</p></details>${b('I need help with this run','我需要运行方面的帮助','support','small')}<div id="support-note">${s.support[cur().id]?`<p class="note">${t('Support need recorded. Raise your hand. Your report will show this was completed with support.','已记录需要帮助。请举手。报告将注明此步骤需要支持。')}</p>`:''}</div>${extension?textAnswer('note-'+extension,'What did you try or learn?','你尝试或学到了什么？',cur().drawing?plain(challenge(extension).task.note.en,challenge(extension).task.note.zh):plain('I changed… / I noticed… / I need help with…','我改变了…… / 我注意到…… / 我需要帮助……')):''}</div>${mapHTML()}</div>`;}
function setup(drawing=false){return 'import turtle as t\nt.speed(0)\nt.pensize(4)\nt.color("blue")\nt.penup()\nt.goto(0, '+(drawing?'0':'-200')+')\nt.pendown()\n';}
function program(code,drawing=false){return setup(drawing)+'\n# Your '+(drawing?'drawing':'route')+' commands\n'+code+'\n\nt.done()\n';}
function snapshot(){return s.snapshots.at(-1);}
function body(c){switch(c.kind){
case 'mission':return `<div class="split"><div><h3>${t('Your three things to keep','需要保存的三样东西')}</h3><ol><li>${t('Your first working route','第一段可运行路线')}</li><li>${t('A version 1 Python file','第 1 版 Python 文件')}</li><li>${t('A PDF showing code, drawing and your thinking','展示代码、图形和想法的 PDF')}</li></ol><p>${t('No folder setup today. We will show you how to save on your device at the end.','今天不需要建立文件夹。最后会示范如何在你的设备保存文件。')}</p></div>${mapHTML()}</div>`;
case 'starter':return `<div class="split"><div>${c.questions.map(question).join('')}${checkButton()}</div>${mapHTML()}</div>`;
case 'types':return `<div class="grid3">${[['Knowledge','知识','Remember: x first, y second.','记住：先 x，后 y。'],['Skills','技能','Practise: type one line and run it.','练习：输入一行并运行。'],['Understanding','理解','Explain: why does the line end there?','解释：为什么线在这里结束？']].map(a=>`<div class="tile"><h3>${t(a[0],a[1])}</h3><p>${t(a[2],a[3])}</p></div>`).join('')}</div>${choice('strategy','What will help you next?','下一步什么方法能帮助你？',[['Point to x and y before typing','输入前指出 x 和 y'],['Run and check one line at a time','每次运行并检查一行'],['Explain a command to my partner','向同伴解释一条指令']])}`;
case 'readcode':return `<pre class="mini-code">t.goto(-200, -100)</pre><div class="grid3"><div class="tile"><h3>t.goto</h3><p>${t('Move Turtle to a position.','把 Turtle 移动到一个位置。')}</p></div><div class="tile"><h3>x = -200</h3><p>${t('200 units left of the centre.','中心左侧 200 个单位。')}</p></div><div class="tile"><h3>y = -100</h3><p>${t('100 units below the centre.','中心下方 100 个单位。')}</p></div></div>${c.questions.map(question).join('')}${checkButton()}`;
case 'code':return `${c.example?`<p class="note">${t('Command guide','指令提示')}: <code>${esc(c.example)}</code></p>`:''}${c.questions?c.questions.map(question).join('')+checkButton():''}${cur().drawing?drawingTask()+drawingGuide():''}${codeEditor()}`;
case 'pen':return `<div class="split"><div class="tile"><h3>A</h3><pre>t.penup()\nt.goto(0, -100)</pre></div><div class="tile"><h3>B</h3><pre>t.pendown()\nt.goto(0, -100)</pre></div></div>${c.questions.map(question).join('')}${checkButton()}`;
case 'test':return `<div class="split"><div><pre>${esc(s.work.route.code||'# Your route code will appear here')}</pre>${['start','corridor','finish'].map((id,i)=>choice('test-'+id,['Does my line start at the Main Entrance?','Does it stay inside the corridor and rooms, without crossing walls?','Does it end at Reception?'][i],['路线是否从学校正门开始？','是否沿走廊和房间行走，没有穿墙？','是否在接待处结束？'][i],[['Yes — I checked the drawing','是，我检查过图形'],['Not yet — I need to change it or ask for help','还没有，需要修改或求助']])).join('')}${textAnswer('explain','Explain one of your commands.','解释其中一条指令。',plain('My command t.goto(____, ____) moves Turtle to _____.','我的指令 t.goto(____, ____) 将 Turtle 移动到……'))}${b('Return to my code','返回代码','goto:7','small')}</div>${mapHTML()}</div>`;
case 'save':return `<div class="split"><div><ol><li>${t('Capture code + drawing. Check that both match your latest run.','捕获代码和图形，检查它们是否对应最近一次运行。')}</li><li>${t('Save version 1. This creates a protected copy inside this lesson.','保存第 1 版，在课程内保留副本。')}</li><li>${t('Download the Python file and check where it was saved.','下载 Python 文件，检查保存位置。')}</li></ol><div class="buttons">${b('1. Capture code + drawing','1. 捕获代码和图形','capture','primary')}${b('2. Save version 1','2. 保存第 1 版','version','secondary')}</div>${snapshot()?`<p class="success">${t('Version 1 is saved in this lesson.','第 1 版已保存在课程中。')} ${snapshot().working?'':t('It is labelled “needs support” in the report.','报告中标记为“需要支持”。')}</p>${b('3. Download Python (.py)','3. 下载 Python (.py)','py','primary')}`:''}<div class="buttons">${b('Preview captured evidence','预览已捕获证据','preview-shot','small')}${b('Return to my code','返回代码','goto:7','small')}</div><div id="capture-status" class="status-line">${s.capture?t('Evidence captured. A new edit or run requires a fresh capture.','证据已捕获。如果再次编辑或运行，需要重新捕获。'):t('No evidence captured yet.','尚未捕获证据。')}</div><label class="inlinecheck" id="field-evidenceReviewed"><input type="checkbox" data-check="evidenceReviewed" ${s.checks.evidenceReviewed?'checked':''}>${t('I opened the preview and checked that the code and drawing match.','我打开了预览，确认代码和图形一致。')}</label><p class="note">${t('A picture alone cannot be run. Keep the .py file too.','只有图片无法运行，请同时保留 .py 文件。')}</p></div>${mapHTML()}</div>`;
case 'drawing':return `<div class="drawing-choices">${L.drawings.map(e=>`<article class="tile">${shapeIcon(e.icon)}<h3>${both(e.title)}</h3><p>${both(e.task.brief)}</p>${b('Try this drawing','尝试绘图','ext:'+e.id,'secondary')}<p class="note">${s.extensions.filter(a=>a.id===e.id).length} ${t('attempts started','次尝试')}</p></article>`).join('')}</div><p class="note">${t('Your code, drawing, runs and short note are included in your PDF. You can return and try again. No screenshot is needed.','代码、图形、运行记录和简短说明会加入 PDF。可以返回再试。不需要截图。')}</p>`;
case 'extension':return `<div class="grid3">${L.extensions.map(e=>`<div class="tile"><div class="brand">Level ${e.level}</div><h3>${both(e.title)}</h3><p>${both(e.read)}</p>${b('Try this challenge','尝试这个挑战','ext:'+e.id,'secondary')}<p class="note">${s.extensions.filter(a=>a.id===e.id).length} ${t('attempts started','次尝试')}</p></div>`).join('')}</div><p class="note">${t('Optional: you do not need to finish every challenge. Your report includes only the ones you try.','选做：不需要完成所有挑战。报告只包括你尝试过的挑战。')}</p>`;
case 'pitstop':return choice('phase','Which phase describes your learning right now?','哪个阶段最符合你目前的学习情况？',[['New Learning — I can use a coordinate with some help.','新学习：在帮助下可以使用坐标。'],['Consolidating — I can draw and explain the route.','巩固：可以画出并解释路线。'],['Treading Water — This is easy; I need more challenge.','原地踏步：这很容易，需要更有挑战的任务。'],['Drowning — I do not yet know which numbers to use.','感到困难：还不知道该用哪些数，需要帮助。']])+choice('nextstep','What will you do next?','下一步会做什么？',[['Use the coordinate table to try one more command.','参考坐标表，再尝试一条指令。'],['Explain a line without looking at the help.','不看提示，解释一行代码。'],['Try a new route or an order challenge.','尝试新路线或指令顺序挑战。'],['Ask the teacher to model one command with me.','请老师和我一起示范一条指令。']]);
case 'plenary':return c.questions.map(question).join('')+textAnswer('exit-evidence','What should your evidence show?','你的证据应该展示什么？',plain('My evidence shows my ______ and the ______ it produces.','我的证据展示我的……以及它产生的……。'))+checkButton();
case 'export':return `<div class="do"><strong>${t('Teams assignment: Week 3 Project','Teams 作业：Week 3 Project')}</strong><p>${t('Upload TWO files: your PDF evidence report and your v01 Python (.py) file. Then select Turn in.','上传两个文件：PDF 证据报告和 v01 Python (.py) 文件，然后点击提交。')}</p></div><div class="buttons">${b('Review all my work','查看全部作品','review','secondary')}${b('Create my PDF','生成 PDF','pdf','primary')}${b('Download Python (.py)','下载 Python (.py)','py')}${b('Download backup','下载备份','backup','small')}</div><div id="pdf-actions"></div><div class="helpbox">${savingHelp()}</div><label class="inlinecheck"><input type="checkbox" data-check="pdfSaved" ${s.checks.pdfSaved?'checked':''}>${t('I found and opened my saved PDF.','我找到了保存的 PDF 并打开检查。')}</label><label class="inlinecheck"><input type="checkbox" data-check="uploaded" ${s.checks.uploaded?'checked':''}>${t('I uploaded both files to Teams, checked the attachments and selected Turn in.','我已把两个文件上传到 Teams，检查附件并点击提交。')}</label><p class="note">${t('This is your confirmation. The app cannot check Teams or upload files for you.','这是你的自我确认。应用不能检查 Teams 或代替你上传文件。')}</p>${b('Print / Save as PDF fallback','打印 / 存为 PDF 备用方式','print','small')}<div id="gimkit-area">${gimkitCard()}</div><div id="review"></div>`;
default:return '';
}}

function gimkitCard(){return s.checks.uploaded?`<section class="gimkit-card" aria-live="polite"><h3>${t('Submitted? Time for Gimkit!','已提交？来玩 Gimkit！')}</h3><p>${t('Ask your teacher for today’s game code. Join when your teacher is ready.','向老师索取今天的游戏代码，老师准备好后再加入。')}</p><a class="gimkit-link" href="https://www.gimkit.com/join" target="_blank" rel="noopener noreferrer">${t('Join Gimkit ↗','加入 Gimkit ↗')}</a><p class="note">${t('Opens in a new tab. Keep this lesson open. Gimkit is a separate website; your lesson answers are not sent to it.','将在新标签页打开，请保持本课程页面打开。Gimkit 是独立网站，不会收到你的课程答案。')}</p></section>`:'';}
function shapeIcon(kind){const shapes={square:'<rect x="55" y="15" width="80" height="80"/>',rectangle:'<rect x="30" y="25" width="140" height="65"/>',circle:'<circle cx="100" cy="55" r="42"/>',picture:'<rect x="35" y="30" width="60" height="60"/><circle cx="145" cy="60" r="30"/>'};return '<svg class="shape-preview" viewBox="0 0 200 110" aria-hidden="true"><g fill="none" stroke="currentColor" stroke-width="3">'+shapes[kind]+'</g></svg>';}
function drawingTask(){const task=challenge(extension).task;return `<section class="drawing-task"><h3>${t('YOUR CHALLENGE: ','你的挑战：')}${both(task.scenario)}</h3><p>${both(task.brief)}</p><ol>${task.steps.map(p=>'<li>'+both(p)+'</li>').join('')}</ol><details><summary>${t('Show the starting-position help','显示起点提示')}</summary><pre>${esc(task.guide)}</pre></details><p class="success">${both(task.check)}</p></section>`;}
function animationSpeed(){return s?.animationSpeed||(matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'steady');}
function playbackControls(){return `<div class="playback-controls"><label for="drawing-speed">${t('Drawing speed','绘图速度')}</label><select id="drawing-speed">${[['slow','Slow · watch carefully','慢速 · 仔细观察'],['steady','Steady','正常慢速'],['instant','Show immediately','立即显示']].map(([v,en,zh])=>`<option value="${v}" ${animationSpeed()===v?'selected':''}>${esc(plain(en,zh))}</option>`).join('')}</select>${b('Replay drawing','重播绘图','replay','small',busy||!wk().draws?.length?'disabled':'')}</div><p class="note">${t('Watch the moving dot. Use Stop to stop playback. Speed here changes the preview, not your Python code.','观察移动的圆点。点击停止可停止播放。此处速度改变预览，不改变 Python 代码。')}</p>`;}
function playDrawing(draws,card,done,replay=false){playbackReplay=replay;playbackDraws=[];busy=true;wk().message=plain('Drawing… watch the line appear.','正在绘图……观察线条逐渐出现。');render();playback=TurtlePlayback.start(draws,{speed:animationSpeed,paint:partial=>{playbackDraws=partial;if($('map'))RouteMap.paint($('map'),partial,{map:!card.drawing});},done:()=>{playback=null;playbackDraws=null;playbackReplay=false;busy=false;done();}});}
function drawingGuide(){return `<details class="drawing-guide"><summary>${t('Drawing command help','绘图指令帮助')}</summary><dl><dt>t.forward(100)</dt><dd>${t('Move 100 in the direction Turtle faces.','沿面向的方向移动 100。')}</dd><dt>t.right(90) / t.left(90)</dt><dd>${t('Turn 90 degrees without moving.','转 90 度，不移动。')}</dd><dt>t.circle(60)</dt><dd>${t('Draw a circle with radius 60.','画半径为 60 的圆。')}</dd><dt>t.penup() → t.goto(x, y) → t.pendown()</dt><dd>${t('Move to a new place without a joining line, then draw again.','抬笔移动到新位置，不画连接线，再放笔绘图。')}</dd></dl><p>${t('Every Run starts a fresh drawing. Your latest code is saved.','每次运行都会重新绘图。最新代码会被保存。')}</p></details>`;}

function savingHelp(){return `<h3>${t('Saving on your device','在设备上保存')}</h3><p><strong>iPad / Safari:</strong> ${t('After creating the PDF, tap Share / Save to Files. Choose Save to Files, select a folder and tap Save. If a PDF preview opens instead, use its Share button → Save to Files. Then in Teams choose Add work → Upload from this device / Files.','生成 PDF 后，点击分享 / 存储到“文件”。选择文件夹并保存。如果打开 PDF 预览，请使用其中的分享按钮 → 存储到“文件”。之后在 Teams 中选择添加作品 → 从此设备 / 文件上传。')}</p><p><strong>Mac / laptop:</strong> ${t('Download the PDF. Look in Downloads. In Teams, attach that PDF and your Python file, then Turn in.','下载 PDF，在“下载”文件夹找到它。在 Teams 添加 PDF 和 Python 文件，然后提交。')}</p><p class="note">${t('Your browser controls the save location. This app cannot silently place files into an iPad folder. If you are inside the Google app, open the lesson in Safari or Chrome first.','保存位置由浏览器控制。应用不能自动把文件放入 iPad 文件夹。如果在 Google 应用内，请先用 Safari 或 Chrome 打开课程。')}</p>`;}
function render(){if(!s)return landing();const c=cur(),n=Object.keys(s.done).length;$('app').innerHTML=header()+`<div id="storage-warning" role="alert">${esc(storageIssue)}</div><div class="layout">${learning()}<main class="content" id="main"><div class="progress-top"><span>${extension?t('Challenge workspace','挑战工作区'):t(`Card ${s.current+1} of ${STEPS.length}`,`第 ${s.current+1} 张，共 ${STEPS.length} 张`)}</span><span id="saved">${t('Saved on this browser','已保存到本浏览器')}</span></div><div class="progress" role="progressbar" aria-label="Completed lesson cards" aria-valuenow="${n}" aria-valuemin="0" aria-valuemax="${STEPS.length}"><span style="width:${n/STEPS.length*100}%"></span></div><section class="card"><div class="stage">${esc(c.stage)}</div><h2 class="card-title" tabindex="-1">${both(c.title)}</h2><div class="read"><span class="tag">${t('READ','阅读')}</span>${both(c.read)}</div><div class="do"><span class="tag">${t('YOUR NEXT ACTION','下一步做什么')}</span>${both(c.action)}</div><div id="notice" role="status">${notice?`<p class="feedback">${esc(notice)}</p>`:''}</div><div id="validation" role="alert"></div>${body(c)}${c.id!=='export'?`<nav class="nav" aria-label="Lesson navigation">${extension?b('Return to choices','返回选择','ext-back'):b('Back','返回','back','',s.current===0?'disabled':'')}${extension?b('Finish this attempt','完成本次尝试','ext-finish','primary'):b(c.id==='extension'?'Continue to drawing choices':c.id==='drawing'?'Continue to Learning Pitstop':'Complete & continue',c.id==='extension'?'继续到绘图选择':c.id==='drawing'?'继续到学习反思':'完成并继续','next','primary')}</nav>`:''}</section><p class="status-line">${t('Progress is local to this browser. Need help? Raise your hand.','进度保存在此浏览器。需要帮助请举手。')}</p></main></div>`;paint();if(c.id==='export'&&pdfFile)pdfActions();}
function paint(){if(!$('map'))return;const c=cur(),w=s.work[c.workspace||'route'];RouteMap.paint($('map'),['mission','starter'].includes(c.kind)?[]:playbackDraws??w?.draws??[],{map:!c.drawing});if(c.kind==='code'){
  document.querySelector('.card').classList.toggle('focus-mode',focusWorkspace);
  document.querySelector('.do').insertAdjacentHTML('afterend',`<div class="workspace-tools">${b(focusWorkspace?'Show the reading again':(c.drawing?'Focus on code + drawing':'Focus on code + map'),focusWorkspace?'再次显示阅读内容':'专注代码和地图','focus','small secondary')}${b(c.drawing?'Enlarge drawing':'Enlarge map',c.drawing?'放大图画':'放大地图','enlarge-map','small')}</div>`);
  if(extension)document.querySelector('.runbar').insertAdjacentHTML('afterend',b('Download this version (.py)','下载这个版本 (.py)','ext-py','small'));
  if(w.lastCode&&w.code!==w.lastCode)document.querySelector('.map-caption').insertAdjacentHTML('beforebegin',`<p class="error-text">${t('Previous drawing — Run to update it.','这是之前的图形，请运行以更新。')}</p>`);
  if(c.workspace==='route'&&w.ok&&w.lastCode===w.code){const ck=RouteMap.check(w.draws);$('console').insertAdjacentHTML('afterend',`<p class="note">${Object.values(ck).every(Boolean)?t('Route check: starts at the entrance, stays in the corridor and reaches Reception.','路线检查：从正门出发，沿走廊到达接待处。'):t('Python ran. Check the map: start at the entrance, use the corridor corner, and finish at Reception.','Python 已运行。请检查地图：从正门开始，经过走廊转角，最后到接待处。')}</p>`);}
}}
function has(id){return s.answers[id]!==undefined&&String(s.answers[id]).trim().length>0;}
function requirements(c=cur()){
 const list=[];if(busy)return [{id:'console',msg:plain('Wait for the drawing to finish, or press Stop. Then Run again before completing this task.','等待绘图完成，或点击停止。完成任务前需重新运行。')}];const need=(ok,id,en,zh)=>{if(!ok)list.push({id,msg:plain(en,zh)});};
 if(c.questions)c.questions.forEach(q=>{need(has(q.id),'field-'+q.id,'Choose an answer: '+q.label.en,'请选择答案：'+q.label.zh);if(has(q.id))need(s.checked[q.id]===s.answers[q.id],'field-'+q.id,'Press “Check my thinking” to see feedback.','点击“检查我的想法”查看反馈。');});
 if(c.id==='types')need(has('strategy'),'field-strategy','Choose one action to help your learning.','选择一种学习方法。');
 if(c.kind==='code'){const w=wk();need(w.code.trim().length>0,'code','Type at least one command.','请至少输入一条指令。');need(w.lastCode===w.code&&(w.ok||s.support[c.id]),'code','Run this version of your code. If it fails, use a hint or record that you need help.','运行当前代码。如果失败，请查看提示或记录需要帮助。');if(c.id==='change')need(w.lastCard==='change','code','Run your changed command on this card.','在本卡片运行修改后的指令。');if(extension)need(has('note-'+extension),'field-note-'+extension,'Add a short note about your attempt.','简短说明这次尝试。');}
 if(c.id==='test'){['start','corridor','finish'].forEach(id=>need(has('test-'+id),'field-test-'+id,'Choose Yes or Not yet for each check.','为每项选择“是”或“还没有”。'));need(has('explain'),'field-explain','Explain one command. You can use the sentence starter.','解释一条指令，可以使用句子开头。');}
 if(c.id==='save'){need(!!s.capture&&s.capture.code===s.work.route.code&&s.capture.runAt===s.work.route.runAt,'capture-status','Capture the latest code and drawing.','捕获最新的代码和图形。');need(!!snapshot()&&snapshot().code===s.work.route.code,'capture-status','Press “Save version 1”.','点击“保存第 1 版”。');need(s.checks.evidenceReviewed,'field-evidenceReviewed','Open the preview, then confirm you checked it.','打开预览，再确认已检查。');}
 if(c.id==='pitstop'){need(has('phase'),'field-phase','Choose your current learning phase.','选择学习阶段。');need(has('nextstep'),'field-nextstep','Choose one useful next step.','选择下一步行动。');}
 if(c.id==='plenary')need(has('exit-evidence'),'field-exit-evidence','Finish the evidence sentence in your own words.','用自己的话完成证据句子。');return list;
}
function showMissing(list){$('validation').innerHTML=`<div class="validation"><strong>${t('One more step before you continue','继续之前还差一步')}</strong><ul>${list.map(x=>`<li><a href="#${x.id}" data-focus="${x.id}">${esc(x.msg)}</a></li>`).join('')}</ul></div>`;list.forEach(x=>$(x.id)?.classList.add('invalid'));const el=$(list[0].id);(el?.querySelector('input,textarea,button')||el)?.focus?.();$('validation').scrollIntoView({block:'nearest'});say(list[0].msg);log('Continue blocked',list.map(x=>x.msg).join('; '));}
function navigate(i){stop(false);notice='';focusWorkspace=false;s.current=i;extension=null;log('Opened card',STEPS[i].title.en);save(true);render();document.querySelector('.card-title')?.focus();$('main').scrollIntoView({block:'start'});}
function next(){const missing=requirements();if(missing.length&&!s.teacher)return showMissing(missing);s.done[cur().id]=new Date().toISOString();log('Completed card',missing.length?'Teacher review bypass':'Requirements attempted');navigate(Math.min(s.current+1,STEPS.length-1));}
function modal(title,html){$('dialog').innerHTML=`<div class="dialog-top"><h2 id="dialog-title">${esc(title)}</h2>${b('Close','关闭','close','small')}</div>${html}`;$('dialog').showModal();}
function updateCode(value){const w=wk();if(w.code===value)return;if(busy)stop(false);w.undo=w.code;w.code=value;pdfFile=null;delete s.done[cur().id];if(cur().workspace==='route')s.checks.evidenceReviewed=false;save();if($('console'))$('console').textContent=plain('Edited. Run again to update the drawing.','已修改。请再次运行以更新图形。');}
function sync(){if($('code')&&s)updateCode($('code').value);}
function stop(show=true){if(playback){playback.cancel();if(!playbackReplay){wk().draws=playbackDraws||[];wk().ok=false;wk().lastCode=null;}playback=null;playbackDraws=null;playbackReplay=false;}clearTimeout(runTimer);clearTimeout(startTimer);worker?.terminate();worker=null;if(workerURL)URL.revokeObjectURL(workerURL);workerURL=null;if(frameListener)window.removeEventListener('message',frameListener);frameListener=null;frame?.remove();frame=null;const was=busy;busy=false;document.querySelector('[data-action="run"]')?.removeAttribute('disabled');document.querySelector('[data-action="stop"]')?.setAttribute('disabled','');if(was&&show){wk().message=plain('Stopped. Your code is still here. Run again to see the complete drawing.','已停止，代码仍保留。再次运行以查看完整图形。');log('Stopped Python');render();}}
function run(){sync();if(busy)return;const c=cur(),w=wk(),code=w.code;w.ok=false;w.lastCode=null;w.draws=[];pdfFile=null;w.message=plain('Loading the Python runner…','正在加载 Python 运行环境……');busy=true;log('Run requested',code);render();let sent=false;const commit=result=>{w.lastCode=code;w.lastCard=c.id;w.runAt=new Date().toISOString();w.ok=result.ok;w.draws=result.draws||[];w.output=result.output||'';const line=result.line?Math.max(1,result.line-(setup(!!c.drawing).split('\n').length+1)):null;w.error=result.error||'';w.message=result.ok?(c.drawing?plain('Run finished. Check your drawing against the challenge.','运行完成。请对照挑战检查图画。'):plain('Run finished. Compare the blue line with the corridor.','运行完成。请比较蓝线与走廊。'))+(result.output?'\n'+result.output:''):friendly(result.error,line);w.runs.push({at:w.runAt,card:c.id,code,ok:result.ok,output:w.output,error:w.error,checks:c.drawing?{drawing:true}:RouteMap.check(w.draws)});if(w.runs.length>60){w.runs.shift();w.olderRuns=(w.olderRuns||0)+1;}if(c.workspace==='route')s.checks.evidenceReviewed=false;log('Python result',result.ok?'Successful execution':w.error,c.id);save(true);render();};
 const finish=result=>{stop(false);if(result.ok&&result.draws?.length)playDrawing(result.draws,c,()=>commit(result));else commit(result);};
 const ready=send=>{if(sent)return;sent=true;clearTimeout(startTimer);w.message=plain('Running your instructions…','正在运行指令……');if($('console'))$('console').textContent=w.message;runTimer=setTimeout(()=>finish({ok:false,error:'EXECUTION_TIMEOUT: The program did not finish. Check for a loop that never stops.',draws:[]}),5000);send({type:'run',code:program(code,!!c.drawing)});};
 const message=(r,send)=>{if(r.type==='ready')ready(send);else if(r.type==='startup-error')finish({ok:false,error:'STARTUP: The Python runner could not load. Your code is not the problem. Reopen this lesson from the hosted school link.',draws:[]});else if(r.type==='result')finish(r);};
 const fallback=()=>{worker?.terminate();worker=null;frame=document.createElement('iframe');frame.hidden=true;frame.sandbox='allow-scripts';frame.srcdoc='<!doctype html><meta charset="utf-8"><script>'+window.PYTHON_RUNNER_SOURCE.replace(/<\/script/gi,'<\\/script')+'</script>';frame.title='Isolated Python runtime';frameListener=e=>{if(e.source===frame?.contentWindow)message(e.data,r=>frame.contentWindow.postMessage(r,'*'));};window.addEventListener('message',frameListener);document.body.append(frame);};
 startTimer=setTimeout(()=>finish({ok:false,error:'STARTUP: The Python runner did not load. This is an app/browser issue, not too many instructions. Try the hosted lesson link or ask your teacher.',draws:[]}),20000);
 try{if(!window.PYTHON_RUNNER_SOURCE)throw new Error('Missing runtime bundle');workerURL=URL.createObjectURL(new Blob([window.PYTHON_RUNNER_SOURCE],{type:'application/javascript'}));worker=new Worker(workerURL);worker.onmessage=e=>message(e.data,r=>worker.postMessage(r));worker.onerror=()=>{if(!sent)fallback();else finish({ok:false,error:'RUNTIME: The Python runner stopped unexpectedly. Try Run again.',draws:[]});};}catch{if(window.PYTHON_RUNNER_SOURCE)fallback();else finish({ok:false,error:'STARTUP: The local Python files are missing. Extract the complete ZIP and try again.',draws:[]});}
}
function friendly(error,line){const e=String(error||'Unknown error');if(e.startsWith('STARTUP:')||e.startsWith('RUNTIME:'))return e.replace(/^[A-Z]+: /,'');if(/TimeLimit|EXECUTION_TIMEOUT/.test(e))return plain('The program did not finish. Check any repetition. A single goto should finish quickly; if it does not, ask your teacher to check the app.','程序未完成。请检查重复指令。一条 goto 应很快完成；如果没有，请老师检查应用。');return (line?plain(`Check your line ${line}. `,`请检查第 ${line} 行。 `):'')+e+'\n'+plain('Compare the dot, brackets, comma and numbers. Your code is kept.','检查点号、括号、逗号和数字。代码已保留。');}
function download(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name||blob.name;a.rel='noopener';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),120000);}
async function share(file){try{if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'Week 3 Project'});log('Shared file',file.name);}else{download(file);notice=plain('Use the browser download, or Share → Save to Files if a preview opens.','使用浏览器下载；如果打开预览，点击分享 → 存储到“文件”。');render();}}catch(e){if(e.name!=='AbortError'){notice=plain('Sharing was unavailable. Use Download, then check Files / Downloads.','分享不可用，请下载后检查“文件 / 下载”。');render();}}}
async function capture(){const w=s.work.route;if(!w.lastCode||w.lastCode!==w.code){notice=plain('Run your current route first, then capture its code and drawing.','请先运行当前路线，再捕获代码和图形。');render();return;}const image=document.createElement('canvas');image.width=1400;const codeLines=wrapCanvasLines(program(w.code),650,'20px monospace');image.height=Math.max(750,160+codeLines.length*29);const ctx=image.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,image.width,image.height);ctx.fillStyle='#152e3a';ctx.font='bold 28px Arial';ctx.fillText('Year 7 • Week 3 • Code and drawing',28,44);ctx.font='19px Arial';ctx.fillText(s.name+' · '+s.klass+' · '+new Date().toLocaleString(),28,76);ctx.font='20px monospace';codeLines.forEach((line,i)=>ctx.fillText(line,28,135+i*29));const map=document.createElement('canvas');RouteMap.paint(map,w.draws);ctx.drawImage(map,720,100,650,487.5);ctx.font='18px Arial';ctx.fillText(w.ok?'Python ran. Check the route against the map.':'Run needs support: '+w.error.slice(0,58),720,620);const id='capture-'+Date.now();const persisted=await putShot(id,image.toDataURL('image/png'));s.capture={id,code:w.code,runAt:w.runAt,at:new Date().toISOString(),persisted};s.checks.evidenceReviewed=false;log('Captured code/output',id);notice=plain('Captured! Open the preview to check it, then save version 1.','已捕获！打开预览检查，然后保存第 1 版。');save(true);render();}
function wrapCanvasLines(text,width,font){const c=document.createElement('canvas').getContext('2d');c.font=font;const lines=[];for(const para of String(text).split('\n')){let line='';for(const ch of para){if(c.measureText(line+ch).width>width&&line){lines.push(line);line='';}line+=ch;}lines.push(line);}return lines;}
async function previewShot(){if(!s.capture){notice=plain('Capture the code and drawing first.','请先捕获代码和图形。');render();return;}const img=await getShot(s.capture.id);modal(plain('Your captured evidence','已捕获证据'),img?`<div class="evidence"><img src="${img}" alt="Your captured Python code alongside its route drawing"></div><p>${t('Check the code is readable and the drawing is the one you intended. Close this preview, then tick the review box.','检查代码是否清晰，图形是否正确。关闭预览后勾选确认。')}</p>`:`<p>${t('The picture is no longer available. Return to your code, run it and capture again.','图片已不可用。请返回代码，运行并重新捕获。')}</p>`);log('Previewed evidence',s.capture.id);}
async function version(){const w=s.work.route;if(!s.capture||s.capture.code!==w.code||s.capture.runAt!==w.runAt){notice=plain('Capture your latest code and drawing before saving version 1.','保存第 1 版之前，请先捕获最新代码和图形。');render();return;}if(snapshot()&&!confirm(plain('Replace the saved version 1 with this new snapshot? Your earlier snapshot stays in the report history.','用当前作品更新第 1 版？之前的快照仍保留在报告记录中。')))return;const ck=RouteMap.check(w.draws);s.snapshots.push({at:new Date().toISOString(),code:w.code,draws:w.draws,shot:s.capture.id,working:!!w.ok&&Object.values(ck).every(Boolean),checks:ck,ok:w.ok});log('Saved version 1',snapshot().working?'Working route':'Needs support / draft');notice=plain('Version 1 saved. Now download the Python file.','第 1 版已保存，现在请下载 Python 文件。');save(true);render();}
function pythonFile(ext=false){const snap=snapshot(),code=ext?wk().code:snap?.code||s.work.route.code;const drawing=ext&&cur().drawing;return new File([(drawing?'':RouteMap.pythonBackground())+program(code,drawing)],filename(drawing?'Drawing_'+extension+'.py':ext?'Route_v02.py':'Route_v01.py'),{type:'text/x-python'});}
function answerLabel(id){for(const c of STEPS){const q=c.questions?.find(x=>x.id===id);if(q)return q.label.en;}return ({strategy:'My learning action',explain:'Explanation of one command','test-start':'Start check','test-corridor':'Corridor check','test-finish':'Destination check',phase:'My learning phase',nextstep:'My next step','exit-evidence':'What my evidence should show'})[id]||id;}
function answerValue(id,value){for(const c of STEPS){const q=c.questions?.find(x=>x.id===id);if(q)return q.choices[Number(value)]?.en||String(value);}const maps={strategy:['Point to x and y','Test one line at a time','Explain to a partner'],phase:['New Learning','Consolidating','Treading Water','Drowning'],nextstep:['Try another coordinate command','Explain without help','Try a challenge','Ask the teacher to model one command']};if(id.startsWith('test-'))return Number(value)===0?'Yes — checked':'Not yet — needs a change or help';return maps[id]?.[Number(value)]||String(value);}
function reportSections(){const out=[{title:'Year 7 · Week 3 Project',text:`My first working route\nName: ${s.name}\nClass: ${s.klass||'Teacher review'}\nReport created: ${new Date().toLocaleString()}\nWAGBA: ${L.goals.wagba.en}\nKnowledge: ${L.goals.knowledge.en}\nSkills: ${L.goals.skills.en}\nUnderstanding: ${L.goals.understanding.en}\nKeywords: ${L.terms.map(x=>x[0]).join(', ')}`}];for(const c of STEPS){if(['export','extension','drawing'].includes(c.id))continue;const ids=(c.questions||[]).map(q=>q.id).concat({types:['strategy'],test:['test-start','test-corridor','test-finish','explain'],pitstop:['phase','nextstep'],plenary:['exit-evidence']}[c.id]||[]);const text=ids.filter(has).map(id=>answerLabel(id)+': '+answerValue(id,s.answers[id])).join('\n\n');out.push({title:c.stage+' — '+c.title.en,text:(s.done[c.id]?'Completed':'Not marked complete')+(s.support[c.id]?' · Support requested':'')+(text?'\n'+text:'')});}
 const snap=snapshot();if(snap){out.push({title:'Saved version 1',text:`Saved: ${snap.at}\nRoute check: ${snap.working?'start, safe corridor and Reception reached':'needs support / not yet a complete safe route'}\nFilename: ${filename('Route_v01.py')}`});out.push({title:'Version 1 Python code',text:program(snap.code),code:true});out.push({title:'Version 1 code and output evidence',imageId:snap.shot});}else out.push({title:'Version 1',text:'No saved version 1 yet.'});
 out.push({title:'Runs and improvements',text:Object.entries(s.work).filter(([k])=>!k.startsWith('ext-')).map(([id,w])=>`${id}: ${w.runs.length+(w.olderRuns||0)} runs\n`+w.runs.map((r,i)=>`Run ${i+1} (${r.at}) — ${r.ok?'ran successfully':r.error}\n${r.code}${r.output?'\nOutput: '+r.output:''}`).join('\n\n')).join('\n\n')});
 if(s.extensions.length)for(const a of s.extensions){out.push({title:`Extension: ${a.id} · attempt ${s.extensions.filter(x=>x.id===a.id&&x.started<=a.started).length}`,text:(a.challengeBrief?`Challenge: ${a.challengeBrief}\nCheck: ${a.challengeCheck}\n\n`:'')+`Started: ${a.started}\nStatus: ${a.status||'in progress'}\nNote: ${a.note||s.answers['note-'+a.id]||'No note yet'}\nRuns this attempt: ${a.runs?.length??0}`});out.push({title:'Extension code',text:a.code||s.work['ext-'+a.id]?.code||'',code:true});if(a.runs?.length)out.push({title:'Extension run record',text:a.runs.map((r,i)=>`Run ${i+1}: ${r.ok?'ran successfully':r.error}\n${r.code}${r.output?'\nOutput: '+r.output:''}`).join('\n\n'),code:true});if(a.draws?.length)out.push({title:'Extension drawing',text:a.lastCode===null?'Playback stopped before completion. Run again to obtain the full drawing.':a.lastCode&&a.lastCode!==a.code?'Last-run output: code was edited after this drawing.':undefined,draws:a.draws,drawing:!!challenge(a.id)?.drawing});}
 out.push({title:'Knowledge check attempts',text:s.attempts.map(a=>`${a.at} · ${answerLabel(a.id)}\nAnswer: ${answerValue(a.id,a.value)}\n${a.correct?'Correct at this check':'Feedback shown; review needed'}`).join('\n\n')||'No checked attempts yet.'});
 out.push({title:'Submission check',text:`PDF saved: ${s.checks.pdfSaved?'student confirmed':'not yet confirmed'}\nTeams: ${s.checks.uploaded?'student confirmed upload and Turn in':'not yet confirmed'}\nThese are student confirmations, not verified Teams status.\nSubmit PDF + Route_v01.py to Week 3 Project.`});
 out.push({title:'Interaction record',text:(s.olderEvents?`${s.olderEvents} earlier events omitted from this bounded local log.\n`:'')+s.events.map(e=>`${e.at} · ${e.card} · ${e.action}${e.value?' — '+e.value:''}`).join('\n')});return out;}
async function reportHTML(){let html='';for(const section of reportSections()){html+=`<div class="review-entry"><h3>${esc(section.title)}</h3>`;if(section.text)html+=section.code?`<pre>${esc(section.text)}</pre>`:`<p>${esc(section.text)}</p>`;if(section.imageId){const image=await getShot(section.imageId);html+=image?`<img style="max-width:100%" src="${image}" alt="Saved code and output evidence">`:'<p>Evidence image unavailable: recapture before final submission.</p>';}if(section.draws){const cv=document.createElement('canvas');RouteMap.paint(cv,section.draws,{map:!section.drawing});html+=`<img style="max-width:100%" src="${cv.toDataURL()}" alt="Extension drawing">`;}html+='</div>';}return html;}
async function createPDF(){if(!window.jspdf){notice=plain('The PDF library did not load. Use Print / Save as PDF instead.','PDF 组件未加载，请使用打印 / 存为 PDF。');render();return;}log('Prepared PDF');notice=plain('Preparing your report. Please keep this page open…','正在准备报告，请保持页面打开……');render();await new Promise(r=>setTimeout(r,30));try{const doc=new jspdf.jsPDF({unit:'pt',format:'a4'});let cv,ctx,y,page=0;const pageW=1240,pageH=1754,margin=76;function newPage(){if(cv)commit();cv=document.createElement('canvas');cv.width=pageW;cv.height=pageH;ctx=cv.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,pageW,pageH);y=85;page++;}function commit(){ctx.font='20px Arial';ctx.fillStyle='#59666a';ctx.fillText(`${s.name} · ${s.klass} · Week 3 Project`,margin,pageH-45);ctx.textAlign='right';ctx.fillText(String(page),pageW-margin,pageH-45);ctx.textAlign='left';if(page>1)doc.addPage();doc.addImage(cv.toDataURL('image/jpeg',.88),'JPEG',0,0,595.28,841.89);}function line(text,font='25px Arial',height=37){ctx.font=font;for(const l of wrapCanvasLines(text,pageW-2*margin,font)){if(y+height>pageH-100)newPage();ctx.font=font;ctx.fillStyle='#18252c';ctx.fillText(l,margin,y);y+=height;}}newPage();for(const section of reportSections()){const font=section.code?'23px monospace':'25px Arial';const estimate=(section.text?wrapCanvasLines(section.text,pageW-2*margin,font).length*(section.code?33:37)+70:70)+(section.draws?(pageW-2*margin)*.75:section.imageId?150:0);if(y>pageH-220||(estimate<pageH-190&&y+estimate>pageH-100))newPage();line(section.title,'bold 31px Arial',44);if(section.text)line(section.text,section.code?'23px monospace':'25px Arial',section.code?33:37);let src;if(section.imageId)src=await getShot(section.imageId);if(section.draws){const c=document.createElement('canvas');RouteMap.paint(c,section.draws,{map:!section.drawing});src=c.toDataURL();}if(src){const img=await loadImage(src);const targetW=pageW-2*margin,scale=targetW/img.width;let offset=0;while(offset<img.height){if(y>pageH-250)newPage();const sourceH=Math.min(img.height-offset,(pageH-110-y)/scale);ctx.drawImage(img,0,offset,img.width,sourceH,margin,y,targetW,sourceH*scale);y+=sourceH*scale+15;offset+=sourceH;if(offset<img.height)newPage();}}else if(section.imageId)line('Evidence image unavailable — recapture before submitting.');y+=26;await new Promise(r=>setTimeout(r,0));}commit();pdfFile=new File([doc.output('arraybuffer')],filename('Project.pdf'),{type:'application/pdf'});notice=plain('Your PDF is ready. Save it below, then upload it and your Python file to Week 3 Project.','PDF 已准备好。请在下方保存，再把它和 Python 文件上传到 Week 3 Project。');render();$('pdf-actions')?.scrollIntoView({block:'nearest'});}catch(e){notice='PDF could not be created: '+e.message+'. Use Print / Save as PDF.';render();}}
function loadImage(src){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=reject;im.src=src;});}
function pdfActions(){if(!$('pdf-actions'))return;$('pdf-actions').innerHTML=`<div class="success"><strong>${t('PDF ready','PDF 已准备好')}</strong><p>${esc(pdfFile.name)}</p><div class="buttons">${b('Download PDF','下载 PDF','download-pdf','primary')}${b('Share / Save to Files','分享 / 存储到文件','share-pdf','secondary')}</div><p>${t('Next: upload this PDF AND your Python file to Teams → Week 3 Project.','下一步：把 PDF 和 Python 文件上传到 Teams → Week 3 Project。')}</p></div>`;}
async function backup(){const images={};for(const id of new Set([s.capture?.id,...s.snapshots.map(x=>x.shot)].filter(Boolean))){const img=await getShot(id);if(img)images[id]=img;}download(new Blob([JSON.stringify({lesson:'y7-w3',state:s,images})],{type:'application/json'}),filename('Backup.json'));log('Downloaded backup');}
async function restore(file){try{if(file.size>25000000)throw new Error('Backup too large');const data=JSON.parse(await file.text());if(data.lesson!=='y7-w3'||data.state?.schema!==1||!Array.isArray(data.state.events)||!data.state.work?.route||!data.state.name)throw new Error('Choose a backup from this lesson.');if(!confirm('Restore this lesson backup for '+data.state.name+'? It will replace their saved progress in this browser.'))return;s=migrate(data.state);s.teacher=s.name.toLowerCase()==='teacher';lang=s.lang||'en';for(const [id,img] of Object.entries(data.images||{}))if(typeof img==='string'&&/^data:image\/(png|jpeg);base64,/.test(img))await putShot(id,img);save(true);render();}catch(e){modal('Could not restore backup',`<p>${esc(e.message)}</p>`);}}
document.addEventListener('submit',e=>{if(e.target.id==='entry'){e.preventDefault();enter($('name').value,$('klass').value,$('device').value);}});
document.addEventListener('input',e=>{if(e.target.id==='code'){updateCode(e.target.value);return;}const id=e.target.dataset.answer;if(id&&s){s.answers[id]=e.target.value;delete s.checked[id];delete s.done[cur().id];pdfFile=null;e.target.closest('.invalid')?.classList.remove('invalid');save();}});
document.addEventListener('change',e=>{if(e.target.id==='drawing-speed'&&s){s.animationSpeed=e.target.value;log('Drawing speed',s.animationSpeed);save(true);return;}if(e.target.id==='language'){sync();lang=e.target.value;if(s){log('Language support',lang);save(true);render();}else{const name=$('name')?.value,klass=$('klass')?.value,device=$('device')?.value;landing();$('name').value=name||'';$('klass').value=klass||'';$('device').value=device||'auto';}return;}if(e.target.id==='restore-file'&&e.target.files[0])restore(e.target.files[0]);if(e.target.dataset.answer&&s){s.answers[e.target.dataset.answer]=e.target.value;delete s.checked[e.target.dataset.answer];log('Answer',e.target.dataset.answer+': '+e.target.value);e.target.closest('.invalid')?.classList.remove('invalid');}if(e.target.dataset.check&&s){s.checks[e.target.dataset.check]=e.target.checked;log('Confirmation',e.target.dataset.check+': '+e.target.checked);if(e.target.dataset.check==='uploaded'){if(e.target.checked)s.done.export=new Date().toISOString();else delete s.done.export;if($('gimkit-area'))$('gimkit-area').innerHTML=gimkitCard();if(e.target.checked)$('gimkit-area')?.scrollIntoView({block:'nearest'});const n=Object.keys(s.done).length;const bar=document.querySelector('.progress');if(bar){bar.setAttribute('aria-valuenow',n);bar.firstElementChild.style.width=n/STEPS.length*100+'%';}save();}e.target.closest('.invalid')?.classList.remove('invalid');}});
document.addEventListener('focusout',e=>{if(e.target.id==='code'&&s)log('Code edit',e.target.value);else if(e.target.tagName==='TEXTAREA'&&e.target.dataset.answer&&s)log('Written response',e.target.dataset.answer+': '+e.target.value);});
document.addEventListener('keydown',e=>{if(e.target.id==='code'&&(e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();run();}if(e.target.id==='code'&&e.key==='Tab'){e.preventDefault();const v=e.target,a=v.selectionStart,z=v.selectionEnd;v.setRangeText('    ',a,z,'end');updateCode(v.value);}});
document.addEventListener('click',async e=>{if(e.target.closest('.gimkit-link')){log('Opened Gimkit join page');save(true);return;}const focus=e.target.closest('[data-focus]');if(focus){e.preventDefault();const el=$(focus.dataset.focus);el?.scrollIntoView({block:'center'});(el?.querySelector('input,textarea,button')||el)?.focus?.();return;}const token=e.target.closest('[data-token]');if(token){const x=codeTokens()[Number(token.dataset.token)],box=$('code');box.setRangeText(x,box.selectionStart,box.selectionEnd,'end');updateCode(box.value);box.focus();log('Inserted token',x);return;}const button=e.target.closest('[data-action]');if(!button)return;const a=button.dataset.action;if(s)log('Button',a);
 if(a==='close'){$('dialog').close();return;}if(a==='focus'){sync();focusWorkspace=!focusWorkspace;render();document.querySelector('.workspace-tools')?.scrollIntoView({block:'nearest'});return;}if(a==='enlarge-map'){modal(plain('Your coordinate map','你的坐标地图'),`<img style="width:100%" src="${$('map').toDataURL()}" alt="Enlarged coordinate map and your current route">`);return;}if(a==='help'){modal(plain('Device and saving help','设备与保存帮助'),savingHelp()+(s?`<hr><p>${t('Work is stored on this browser, not a school server. Download a backup to move devices.','作品保存在浏览器，不是学校服务器。换设备前请下载备份。')}</p>${b('Download backup','下载备份','backup')} ${b('Reset my lesson','重置我的课程','reset','small')}`:''));return;}
 if(a==='resume'){try{const last=JSON.parse(localStorage.getItem(ROOT+'last'));if(last)enter(last.name,last.klass);}catch{}return;}if(a==='restore'){$('restore-file').click();return;}if(a.startsWith('word:')){const x=L.terms[+a.split(':')[1]];modal(x[0]+' · '+x[1],`<p>${t(x[2],x[3])}</p>`);return;}if(!s)return;
 sync();if(a==='next')next();else if(a==='back')navigate(Math.max(0,s.current-1));else if(a==='journey')modal(plain('Lesson cards','课程卡片'),`<div class="journey">${STEPS.map((c,i)=>`<button data-action="goto:${i}" ${!s.teacher&&i>0&&!s.done[STEPS[i-1].id]&&!s.done[c.id]&&i!==s.current?'disabled':''}>${s.done[c.id]?'✓ ':''}${i+1}. ${both(c.title)}</button>`).join('')}</div>`);
 else if(a.startsWith('goto:')){const i=+a.split(':')[1];if(Number.isInteger(i)&&i>=0&&i<STEPS.length&&(s.teacher||i===0||s.done[STEPS[i-1].id]||s.done[STEPS[i].id]||i===s.current)){$('dialog').close();navigate(i);}}
 else if(a==='check'){const c=cur(),missing=(c.questions||[]).filter(q=>!has(q.id));if(missing.length)return showMissing(missing.map(q=>({id:'field-'+q.id,msg:'Choose an answer: '+q.label.en})));for(const q of c.questions||[]){s.checked[q.id]=s.answers[q.id];s.attempts.push({id:q.id,value:s.answers[q.id],correct:Number(s.answers[q.id])===q.correct,at:new Date().toISOString()});}log('Checked answers');render();}
 else if(a==='replay'){if(!busy&&wk().draws.length){const w=wk(),message=w.message;playDrawing(w.draws,cur(),()=>{w.message=message;render();},true);}}else if(a==='run')run();else if(a==='stop')stop();else if(a==='undo'){stop(false);const w=wk();if(w.undo!==undefined){const prev=w.undo;w.undo=w.code;w.code=prev;render();save();}}else if(a==='hint'&&cur().drawing){modal(plain('Your example','你的示例'),`<p>${both(challenge(extension).read)}</p><pre>${esc(cur().sample)}</pre>`);}else if(a==='hint'){modal(plain('One small step','一小步'),cur().id==='build'?`<p>${t('Keep your corner command first. Reception is at x = -200, y = -100. Put those numbers into t.goto(x, y) on the next line.','先保留到转角的指令。接待处的 x = -200，y = -100。把这两个数写入下一行的 t.goto(x, y)。')}</p><pre>t.goto(0, -100)\nt.goto(____, ____)</pre>`:`<p>${t('Use a dot after t, then goto, two brackets and a comma between x and y. x comes first.','t 后加点号，再写 goto，用括号括住两个坐标，中间加逗号。先写 x。')}</p><pre>${cur().id==='change'?'t.goto(0, -150)':'t.goto(0, -100)'}</pre>`);}
 else if(a==='support'){s.support[cur().id]=true;log('Requested support');notice=plain('Your need for help is recorded. Raise your hand; the app does not notify your teacher. After trying Run, you can continue with your attempt recorded as needing support.','已记录需要帮助，请举手。应用不会通知老师。尝试运行后，可以继续，报告会注明需要支持。');render();}
 else if(a==='capture')await capture();else if(a==='preview-shot')await previewShot();else if(a==='version')await version();else if(a==='ext-py'){const file=pythonFile(true);download(file);log('Requested extension Python download',file.name);}else if(a==='py'){if(!snapshot()&&!s.teacher){notice=plain('Save version 1 on the evidence card first.','请先在证据卡片保存第 1 版。');render();return;}const file=pythonFile();if(s.device==='ipad'&&navigator.canShare?.({files:[file]}))await share(file);else download(file);log('Requested Python download',file.name);}
 else if(a.startsWith('ext:')){extension=a.split(':')[1];const e=challenge(extension);if(!e){extension=null;return;}delete s.answers['note-'+extension];pdfFile=null;const id='ext-'+extension;if(!s.work[id])s.work[id]={code:e.sample??(snapshot()?.code||s.work.route.code||'# Try your route here\n'),draws:[],runs:[]};s.extensions.push({id:extension,started:new Date().toISOString(),runStart:s.work[id].runs.length,drawing:!!e.drawing,challengeBrief:e.task?.brief.en,challengeCheck:e.task?.check.en});log('Started extension',extension);notice='';render();}
 else if(a==='ext-back'||a==='ext-finish'){if(busy){if(a==='ext-finish')return showMissing([{id:'console',msg:plain('Wait for the drawing to finish.','请等待绘图完成。')}]);stop(false);}if(a==='ext-finish'&&!s.teacher){const miss=requirements();if(miss.length)return showMissing(miss);}const att=[...s.extensions].reverse().find(x=>x.id===extension&&!x.ended),w=wk();if(att)Object.assign(att,{ended:new Date().toISOString(),status:a==='ext-finish'?'Student finished':'Returned without finishing',lastCode:w.lastCode,code:w.code,draws:w.draws,note:s.answers['note-'+extension]||'',runs:w.runs.slice(att.runStart)});extension=null;notice='';render();save();}
 else if(a==='review'){$('review').innerHTML=await reportHTML();$('review').scrollIntoView({block:'start'});}
 else if(a==='pdf')await createPDF();else if(a==='download-pdf'&&pdfFile){const f=pdfFile;download(f);log('Requested PDF download',f.name);pdfFile=f;pdfActions();}else if(a==='share-pdf'&&pdfFile){const f=pdfFile;await share(f);pdfFile=f;pdfActions();}
 else if(a==='print'){$('print-report').innerHTML=await reportHTML();window.print();}else if(a==='backup')await backup();else if(a==='logout'){stop(false);save(true);s=null;extension=null;pdfFile=null;notice='';landing();}
 else if(a==='reset'&&confirm(plain('Reset only this student’s lesson? Download a backup first if you want to keep it.','只重置这个学生的课程？如需保留，请先下载备份。'))){const k=key(s.name,s.klass);localStorage.removeItem(k);s=fresh(s.name,s.klass);shots.clear();$('dialog').close();save(true);render();}
});
window.addEventListener('pagehide',()=>{if(s){sync();stop(false);save(true);}});
window.addEventListener('error',e=>{if($('app')&&!$('app').textContent.trim())$('app').innerHTML='<p class="validation">The lesson could not load. Your saved work has not been deleted. Please reload or tell your teacher.</p>';});
landing();
})();
