window.LESSON = {
 id:'y11-year10-systems-review-v1',title:'Computer systems and translators',
 wagba:'Explaining what computer components and translators do, using accurate terminology and applying it to a situation.',
 stages:[['read','Read first','4 min'],['starter','Do Now','6 min'],['types','Types of learning','2 min'],['systems','Main Task 1','18 min'],['translators','Main Task 2','20 min'],['pit','Learning pit stop','3 min'],['extension','Extension','If ready'],['plenary','Plenary','7 min'],['record','My revision record','After the lesson']],
 objectives:[
 ['Knowledge','Recall CPU component functions, memory/storage differences and the roles of the three translators.'],
 ['Skills','Annotate a diagram, explain a sequence, compare methods and write a precise justification.'],
 ['Understanding','Explain how components work together and why a memory or translator choice suits its purpose.']],
 reading:{
  cpu:[
   'A program contains instructions. In a stored-program computer, instructions and data are held in main memory. The CPU repeatedly fetches an instruction, decodes it and carries it out. A whole calculation or purchase normally needs many instructions, not just one cycle.',
   'The arithmetic logic unit (ALU) carries out arithmetic operations, such as addition, and logical operations, such as comparisons. The control unit decodes instructions and sends control signals to coordinate their execution. The clock supplies regular pulses that synchronise operations. Buses carry signals between components.',
   'RAM holds instructions and data currently in use. It is read/write and volatile: its contents are lost when power is removed. ROM is non-volatile and read-only in the model used here; it holds fixed instructions such as startup instructions. Secondary storage, such as an SSD, retains saved programs and files without power. Data and instructions needed for processing are brought into main memory.'],
  translators:[
   'Machine code consists of binary instructions for a particular processor or processor family. Assembly language uses mnemonics representing machine instructions and is also processor-specific. In the specification model, each assembly instruction corresponds to one machine-code instruction. High-level languages use more human-readable constructs and let programmers express a task without specifying every machine instruction.',
   'An assembler translates assembly-language instructions into machine code. A compiler translates a high-level program into machine code, producing output that can be saved and run later. Changing the source program requires it to be compiled again before the executable reflects the change.',
   'An interpreter carries out high-level statements as it processes them, using appropriate machine-code routines in the interpreter itself. It does not directly generate a separate machine-code executable from the source. An interpreted program needs the interpreter when it is run. This supports frequent editing and testing during development.'],
  web:[
   'HTML describes the structure and content of a web page. Tags identify elements such as headings, paragraphs and lists. CSS controls presentation. A CSS rule has a selector identifying the element, a property describing what to change, and a value specifying the setting. For example, h1 { color: black; } sets the text colour of h1 headings.']
 },
 starter:[
  {id:'starter-alu',skill:'CPU functions',marks:2,prompt:'State the two types of operation performed by the ALU.',model:'Arithmetic operations, such as addition (1); logical operations, such as comparisons (1).',ref:'Printed textbook pp. 194–195; specification 3.4.4.'},
  {id:'starter-memory',skill:'Memory and storage',marks:2,prompt:'Give two differences between RAM and secondary storage.',model:'RAM is volatile whereas secondary storage is non-volatile (1). RAM holds current working instructions/data and is directly accessible by the CPU; secondary storage retains saved programs/files for longer-term use and is not directly accessible by the CPU (1). Credit two distinct accurate paired differences.',ref:'Printed textbook pp. 198–199; specification 3.4.4.'},
  {id:'starter-languages',skill:'Language levels',marks:2,prompt:'Distinguish machine code from assembly language.',model:'Machine code uses binary instructions (1); assembly language uses mnemonics representing instructions (1). Both are low-level and processor-specific: that similarity alone is not a difference.',ref:'Printed textbook pp. 188–191; specification 3.2.13.'},
  {id:'starter-translators',skill:'Translator functions',marks:2,prompt:'State what an assembler translates and what a compiler translates.',model:'An assembler translates assembly language into machine code (1). A compiler translates a high-level program into machine code (1).',ref:'Printed textbook pp. 192–193; specification 3.2.13.'},
  {id:'starter-web',skill:'HTML and CSS',marks:2,prompt:'State the purpose of HTML and the purpose of CSS.',model:'HTML provides the structure/content of a web page (1). CSS controls its style/presentation (1).',ref:'Printed textbook pp. 272–275; specification 3.8.1–3.8.2.'}],
 systems:[
  {id:'systems-functions',skill:'CPU functions',marks:4,prompt:'Use the diagram to explain the function of each component: ALU, control unit, clock and buses. Link the ALU explanation to this purchase.',model:'ALU: arithmetic/logical operations, including adding the three prices (1). Control unit: decodes instructions and coordinates execution using control signals (1). Clock: regular pulses synchronise operations (1). Buses: carry signals such as data, addresses and control signals between components (1).',ref:'Printed textbook pp. 194–195 and 200; specification 3.4.4.'},
  {id:'systems-cycle',skill:'Fetch–decode–execute',marks:3,prompt:'Explain fetch, decode and execute for a machine-code instruction involved in processing this purchase. State where the instruction is fetched from; do not describe fetching the entire application.',model:'Fetch: bring the next instruction from main memory into the CPU (1). Decode: the control unit works out what the instruction requires (1). Execute: carry out the instruction, for example an arithmetic operation, comparison or memory transfer (1). Not every instruction performs arithmetic in the ALU.',ref:'Printed textbook pp. 196–197; specification 3.4.4.'},
  {id:'systems-memory',skill:'Memory and storage',marks:3,prompt:'Explain why the running application uses RAM, why completed transactions are saved on the SSD, and why ROM is suitable for startup instructions.',model:'RAM holds the current working instructions/data with read/write access (1). The SSD retains completed transactions when power is removed (1). ROM retains startup instructions without power and protects the fixed instructions from ordinary writing (1).',ref:'Printed textbook pp. 198–199; specification 3.4.4.'}],
 translators:[
  {id:'translator-assembler',skill:'Translator functions',marks:2,prompt:'A developer has written an assembly-language program for a particular processor. Name the required translator and explain what it does.',model:'Assembler (1); translates assembly-language instructions into machine code for the processor, with the specified 1:1 instruction correspondence (1).',ref:'Printed textbook pp. 192–193; specification 3.2.13.'},
  {id:'translator-compiler',skill:'Translator functions',marks:2,prompt:'A developer uses a compiled high-level language and wants to distribute an executable for compatible computers. Explain what the compiler produces and why that is useful.',model:'It translates the high-level program into machine code that can be saved as an executable (1). The compatible target computer can run that output without translating the source again each time (1). Do not claim that every executable works on every processor/operating system.',ref:'Printed textbook pp. 192–193; specification 3.2.13.'},
  {id:'translator-interpreter',skill:'Translator functions',marks:2,prompt:'A learner uses an interpreted high-level language and frequently changes and tests statements. Explain how the interpreter executes statements and why this supports development.',model:'It carries out statements using machine-code routines in the interpreter as it processes the program (1). Changed source can be tested without first rebuilding a separate executable (1). It does not directly create a standalone machine-code executable.',ref:'Printed textbook pp. 192–193, with specification 3.2.13 taking precedence for the execution mechanism.'},
  {id:'translator-comparison',skill:'Translator comparison',marks:4,prompt:'Give two paired differences between compilation and interpretation. Address when instructions are executed and whether a separate machine-code executable is produced.',model:'Compilation creates translated output before that executable is run; interpretation carries out statements as the source is processed (2 for the paired difference). Compilation can produce a separate machine-code executable; the interpreter model does not directly create one from the source and needs the interpreter to run the program (2 for the paired difference).',ref:'Printed textbook pp. 192–193; specification 3.2.13.'}],
 misconceptions:[['An assembler translates any high-level language.','An assembler translates assembly language. A compiler or interpreter is used for high-level source.'],['A compiler executes the program while translating it.','Compilation produces translated output. Running the resulting program is a separate step.'],['An interpreter creates a separate machine-code executable.','The interpreter executes statements using its own machine-code routines; it does not directly generate a separate machine-code executable.']],
 exit:[
  {id:'exit-control',skill:'CPU functions',prompt:'Without notes, explain the control unit’s role during decoding.'},
  {id:'exit-memory',skill:'Memory and storage',prompt:'A café saves its completed sales only in RAM. Explain why this is unsuitable and identify a suitable storage type.'},
  {id:'exit-translators',skill:'Translator comparison',prompt:'Without notes, distinguish a compiler from an interpreter. Include what happens to the source and how the program runs.'}],
 skills:['CPU functions','Fetch–decode–execute','Memory and storage','Language levels','Translator functions','Translator comparison','HTML and CSS'],
 refs:[['Languages and translators','188–193','3.2.13'],['CPU components and fetch–execute','194–197','3.4.4'],['Memory and performance','198–201','3.4.4'],['HTML and CSS follow-up','272–275; 278–285','3.8.1–3.8.2']],
 phases:['New learning','Consolidating','Treading water','Drowning'],
 phaseActions:{'New learning':'Name the new distinction, then explain it in your own words using one example.','Consolidating':'Try a fresh example without notes and check whether your explanation still holds.','Treading water':'Try the clock-speed challenge or the HTML/CSS repair. Explain why, not just what.','Drowning':'Name the first unclear term or step. Reopen the relevant reading and ask me for one worked example.'}
};
