(() => {
 const L=window.LESSON,esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function page(title,body){return `<section class="sheet"><header><p class="eyebrow">YEAR 11 · TERM 1 · WEEK 7 · SESSION 1</p><h1>${title}</h1><p class="identity"><span>Name: ____________________</span><span>Class: ________</span><span>Date: __________</span></p><p class="ref">WAGBA: ${esc(L.wagba)}</p></header>${body}</section>`;}
 function qs(items){return items.map((q,i)=>`<section class="q"><h3>${i+1}. ${q.marks?'['+q.marks+' marks]':''}</h3><p>${esc(q.prompt)}</p><div class="space ${q.marks>=3?'large':''}"></div></section>`).join('');}
 const brief='<h2>Inside the computer</h2><p>The ALU performs arithmetic and logical operations. The control unit decodes instructions and coordinates execution. The clock supplies regular pulses to synchronise operations. Buses carry signals between components. Instructions are fetched from main memory, decoded, then executed.</p><p>RAM is volatile working memory. ROM is non-volatile memory used for fixed instructions, such as startup instructions. Secondary storage retains saved programs and files without power.</p><h2>Languages and translators</h2><p>Machine code uses binary instructions; assembly language uses mnemonics. Both are processor-specific. An assembler translates assembly language into machine code. A compiler translates high-level source into machine-code output that can be saved and run later. An interpreter executes statements using machine-code routines in its own code as it processes the source; it does not directly create a separate executable.</p><h2>HTML and CSS</h2><p>HTML provides structure/content. CSS controls presentation. A rule has a selector, property and value.</p><p class="ref">Textbook: printed pp. 188–201 and 272–275. Specification: 3.2.13, 3.4.4, 3.8.1–3.8.2.</p><h2>Two details I had forgotten</h2><div class="space large"></div>';
 const systems='<p>The school shop’s application and price list are saved on an SSD. On opening, instructions and required data are loaded into RAM. A customer buys items costing £12, £8 and £5. The computer calculates £25. The cashier saves the completed transaction on the SSD.</p><p>Explain the component roles to a partner first. Then write your own answers.</p><div style="border:1px solid #555;padding:2mm;margin-bottom:3mm;font-size:9pt"><strong>CPU:</strong> [ ALU ] &nbsp; [ Control unit ] &nbsp; [ Clock ]<br><strong>↕ Buses carry signals ↕</strong><br><strong>Main memory:</strong> RAM and ROM &nbsp; | &nbsp; <strong>Secondary storage:</strong> SSD</div>'+qs(L.systems);
 const trans='<p>Use the reading for the first attempt. Compare both sides when asked for a difference. Check only after attempting all four questions.</p>'+qs(L.translators);
 const plenary='<p>Close the reference sheet. Answer these fresh questions independently.</p>'+qs(L.exit)+'<h2>My next step</h2><p>My next revision priority is __________________ because my answer to __________________ showed __________________.</p><div class="space"></div><p>Current phase: New learning / Consolidating / Treading water / Drowning</p><p>Evidence: ____________________________________________________</p>';
 const extension='<p>Correct the heading closing tag, the incomplete list item and the CSS punctuation. The heading should be black and 24 px. Then identify the selector, one property and its value.</p><pre class="code">'+esc('<h1>School shop</h2>\n<ul>\n  <li>Notebook</li>\n  <li>Pen\n</ul>\n\nh1 {\n  color black;\n  font-size: 24px;\n}')+'</pre><h2>My corrected extracts</h2><div class="space large"></div><h2>My explanation</h2><div class="space large"></div><h2>Further challenge</h2><p>One computer has a higher clock speed than another, but their core counts and cache sizes differ. Explain why clock speed alone does not guarantee better performance.</p><div class="space large"></div>';
 document.querySelector('#sheets').innerHTML=page('Read first',brief)+page('Do Now · 10 marks',qs(L.starter))+page('Main Task 1 · 10 marks',systems)+page('Main Task 2 · 10 marks',trans)+page('Fresh check and next step',plenary)+page('Extension · HTML/CSS repair',extension);
})();
