(() => {
  'use strict';
  const APP = 'y6-t1-week5-choice-repeat-v1';
  const $ = id => document.getElementById(id);
  const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const pages = [
    ['do-now','Do Now','4 min'],
    ['types','Types of Learning','3 min'],
    ['read-choice','Read: choosing a route','5 min'],
    ['plan-choice','Main Task 1: plan','5 min'],
    ['scratch-choice','Main Task 1: Scratch','9 min'],
    ['pitstop','Learning Pitstop','3 min'],
    ['read-repeat','Read: repeating a signal','4 min'],
    ['predict-repeat','Main Task 2: predict','3 min'],
    ['scratch-repeat','Main Task 2: Scratch','12 min'],
    ['extension','Extension','Within task time'],
    ['plenary','Plenary','5 min'],
    ['reflection','Exit Reflection','3 min'],
    ['submit','Save & submit','4 min']
  ];
  const labels = {
    doNowChoice:'Do Now: which action needs selection?', doNowLoop:'Do Now: which action needs repetition?',
    typeKnowledge:'Types of Learning: knowledge', typeSkill:'Types of Learning: skills', typeUnderstanding:'Types of Learning: understanding', typeGoal:'How I will improve',
    choiceMeaning:'What a condition checks', leftMessage:'My message for left', rightMessage:'My message for right', leftTest:'Scratch test: left', rightTest:'Scratch test: right',
    pitPhase:'Learning Pitstop phase', pitNext:'My next step', repeatMeaning:'What repeat (3) does', repeatPrediction:'Predicted flashes', observedFlashes:'Observed flashes in Scratch', loopFix:'What I changed or checked',
    extensionPlan:'Extension level being viewed', extension1:'Extension Level 1 test', extension2:'Extension Level 2 test', extension3:'Extension Level 3 test', extensionResult:'What I changed or fixed in the extension', plenaryChoice:'Why selection is needed', plenaryRepeat:'Why repetition is needed', plenaryTest:'How I know both routes work', exitPhase:'My learning at the end', reflection:'What I can now do'
  };
  let state = null;
  let pendingRestore = null;
  const teacher = () => state?.name.trim().toLowerCase() === 'teacher';
  const t = (en, zh) => `${esc(en)}${state?.language === 'bi' && zh ? `<span class="chinese" lang="zh-Hans">${esc(zh)}</span>` : ''}`;
  const card = (title, body, extra='') => `<section class="card ${extra}"><h2>${title}</h2>${body}</section>`;
  const question = (key, prompt, placeholder='Write a short answer') => `<div class="question"><label for="a-${key}">${prompt}</label><textarea id="a-${key}" data-a="${key}" placeholder="${esc(placeholder)}">${esc(state.answers[key] || '')}</textarea></div>`;
  const options = (key, prompt, choices, correct, explanation) => {
    const answer = state.answers[key] || '';
    return `<fieldset class="card options"><legend><strong>${prompt}</strong></legend><div class="option-grid">${choices.map(([value,label]) => `<label class="option"><input type="radio" name="${key}" data-a="${key}" value="${esc(value)}" ${answer === value ? 'checked' : ''}><span>${label}</span></label>`).join('')}</div>${answer ? `<p class="feedback" role="status">${answer === correct ? 'Yes. ' : 'Look again. '}${explanation}</p>` : ''}</fieldset>`;
  };
  const select = (key, prompt, choices) => `<label for="a-${key}">${prompt}</label><select id="a-${key}" data-a="${key}"><option value="">Choose one...</option>${choices.map(([value,label]) => `<option value="${esc(value)}" ${state.answers[key] === value ? 'selected' : ''}>${label}</option>`).join('')}</select>`;
  const map = () => `<svg class="museum-map" viewBox="0 0 600 300" role="img" aria-label="Museum entrance with Star Room to the left and Ocean Room to the right"><rect width="600" height="300" fill="#fff"/><path class="path" d="M300 252 L300 170 L150 170 L150 102 M300 170 L450 170 L450 102"/><rect class="room" x="57" y="35" width="186" height="68" rx="8"/><rect class="room" x="357" y="35" width="186" height="68" rx="8"/><text x="92" y="75">STAR ROOM</text><text x="385" y="75">OCEAN ROOM</text><circle class="bot" cx="300" cy="250" r="24"/><circle fill="#fff" cx="292" cy="246" r="3"/><circle fill="#fff" cx="308" cy="246" r="3"/><text x="252" y="291" class="label">VISITOR + ROBOT</text><text x="107" y="154" class="label">LEFT</text><text x="438" y="154" class="label">RIGHT</text></svg>`;
  const scratchShot = (kind, caption, alt) => `<figure class="scratch-figure"><a class="scratch-crop ${kind}" href="assets/scratch-${kind}-screen.jpg" target="_blank" rel="noopener" aria-label="Open full Scratch screenshot: ${esc(caption)}"><img src="assets/scratch-${kind}-screen.jpg" alt="${esc(alt)}" loading="lazy"></a><figcaption>${esc(caption)} <a href="assets/scratch-${kind}-screen.jpg" target="_blank" rel="noopener">Open full Scratch screen ↗</a></figcaption></figure>`;
  const blocksChoice = () => scratchShot('choice', 'One possible choice script, shown in Scratch 3.', 'Connected Scratch blocks: green flag, show, go to entrance, say introduction, ask Left or right, then if answer equals left say Star Room, else say Ocean Room.');
  const blocksRepeat = () => scratchShot('repeat', 'One possible repeat script, shown in Scratch 3.', 'Connected Scratch blocks: green flag, show, go to entrance, say introduction, then repeat three times: hide, wait 0.2 seconds, show, wait 0.2 seconds.');
  const blocksComplete = () => scratchShot('complete', 'The repeat block goes after the whole if/else choice.', 'Connected Scratch blocks showing the completed visitor choice, followed by repeat three times containing hide, wait, show, wait.');
  const extensionLevel = () => {
    const level = ['1','2','3'].includes(state.answers.extensionPlan) ? state.answers.extensionPlan : '1';
    const tabs = `<div class="extension-levels" role="group" aria-label="Choose an extension level">${[['1','Level 1 · Count five flashes'],['2','Level 2 · Give clearer directions'],['3','Level 3 · Handle another answer']].map(([n,label]) => `<button type="button" data-level="${n}" aria-pressed="${level===n}">${label}</button>`).join('')}</div>`;
    const tasks = {
      '1': `<h3>Level 1: Change three flashes to five</h3><p>The Scratch example shows <strong>repeat (3)</strong>. Your job is to change the number, not to add five separate hide blocks.</p>${blocksRepeat()}<ol class="step-list"><li>Open <strong>your own Scratch project</strong> and click Explorer.</li><li>Find the orange <strong>repeat (3)</strong> block after your room-choice blocks. Keep <strong>hide → wait → show → wait</strong> inside it.</li><li>Click the white <strong>3</strong> on that repeat block. Type <strong>5</strong>.</li><li>Click the green flag. Try <strong>left</strong> and count five full flashes. Run again with <strong>right</strong>.</li></ol><p class="action"><strong>Check:</strong> Both room messages still work and Explorer disappears and returns five times. If not, check the number and which blocks are inside repeat.</p>`,
      '2': `<h3>Level 2: Write directions a visitor can follow</h3><p>The example shows two purple <strong>say</strong> blocks. They sit in different branches of the orange <strong>if / else</strong> block.</p>${blocksChoice()}<ol class="step-list"><li>Open <strong>your own Scratch project</strong> and find the purple <strong>say</strong> block under <strong>answer = left</strong>.</li><li>Click its white message space. Write your own clear direction that names the <strong>Star Room</strong> and the left path.</li><li>Change the purple <strong>say</strong> block under <strong>else</strong> so it names the <strong>Ocean Room</strong> and the right path.</li><li>Run with <strong>left</strong>, then run again with <strong>right</strong>. Read both messages against the museum map.</li></ol><p class="action"><strong>Check:</strong> The two answers give different, correct directions. The example is a model; use your own helpful words.</p>`,
      '3': `<h3>Level 3: Do not send “middle” to a room</h3><p>Right now, anything except <strong>left</strong> takes the <strong>else</strong> path. That means “middle” wrongly gets the Ocean Room message. The model adds one more question inside <strong>else</strong>.</p>${scratchShot('invalid', 'A second if / else checks for right before giving the Ocean Room message.', 'Scratch blocks: ask Left or right; if answer equals left say Star Room; else if answer equals right say Ocean Room; otherwise say Type left or right and press the flag to try again.')}<ol class="step-list"><li>In <strong>your own Scratch project</strong>, keep the first <strong>if answer = left</strong> block.</li><li>Move the Ocean Room <strong>say</strong> block out of its <strong>else</strong> space. Put a new orange <strong>if / else</strong> block in that space.</li><li>Build <strong>answer = right</strong> using the blue <strong>answer</strong> block from Sensing and the green <strong>=</strong> block from Operators.</li><li>Put the Ocean Room message in the new <strong>then</strong> space. In the new <strong>else</strong> space, add a purple <strong>say</strong> block: “Type left or right. Press the flag to try again.”</li><li>Run three times: enter <strong>left</strong>, <strong>right</strong>, then <strong>middle</strong>.</li></ol><p class="action"><strong>Check:</strong> “Middle” gives the retry message, not a room direction. Your existing flash loop may still run afterwards; this level is about fixing the message.</p>`
    };
    const next = level === '1' ? '<button type="button" data-level="2">Try Level 2 →</button>' : level === '2' ? '<button type="button" data-level="3">Try Level 3 →</button>' : '';
    return tabs + `<section class="extension-task">${tasks[level]}${select('extension'+level,'How did this level go in Scratch?', [['not-yet','I have not tried it yet'],['working','I built it and still need to test'],['tested','I tested it and it worked'],['help','I need help with one step']])}<div class="toolbar extension-next">${next}<span class="hint">The extension is optional. Use the lesson’s Next button when you are ready for the Plenary.</span></div></section>`;
  };
  const launch = () => `<div class="toolbar"><a class="button" href="assets/Year6_T1W5_Choose_and_Repeat_Starter.sb3" download>1. Download Scratch starter (.sb3)</a><a class="button primary" href="https://scratch.mit.edu/projects/editor/" target="_blank" rel="noopener">2. Open Scratch ↗</a></div><p class="hint">${t('In Scratch, choose File > Load from your computer. Select the .sb3 file from Downloads. Already using Scratch Desktop? Open the same file there.','在 Scratch 中选择 File > Load from your computer，然后打开下载的 .sb3 文件。')}</p>`;
  const status = (key, label) => `<fieldset class="card options"><legend><strong>${label}</strong></legend><div class="option-grid"><label class="option"><input type="radio" name="${key}" data-check="${key}" value="done" ${state.checks[key] === 'done' ? 'checked' : ''}>I did it and tested it in Scratch.</label><label class="option"><input type="radio" name="${key}" data-check="${key}" value="help" ${state.checks[key] === 'help' ? 'checked' : ''}>I cannot use Scratch right now. I need help or will continue later.</label></div></fieldset>`;
  function content(id) {
    switch (id) {
      case 'do-now': return card('Your museum mission', `<p>${t('A visitor stands at the entrance. The robot needs to tell the visitor which room to visit. After it gives a direction, it should flash three times so the visitor notices.','访客站在入口。机器人要告诉访客去哪个房间，然后闪烁三次来提醒访客。')}</p>${map()}<p><strong>Today’s big question:</strong> Which part needs a choice, and which part needs repeating?</p>`, 'accent')+
        options('doNowChoice', 'Which action needs a condition (a choice)?', [['rooms','Choose the Star Room or Ocean Room'],['welcome','Say the same welcome message']], 'rooms', 'A condition lets the robot choose a different action for each route.')+
        options('doNowLoop', 'Which action needs a repeat block?', [['flash','Flash three times'],['choose','Choose one room']], 'flash', 'A repeat block is useful when the same action happens several times.');
      case 'types': return card('What type of learning am I doing?', `<p>${t('Knowledge means learning a new idea. Skills grow when you practise. Understanding means you can explain why something works. Choose where you are starting today; these are not grades.','知识是学习新概念；技能通过练习提高；理解是能解释原因。这些选择不是分数。')}</p>`, 'accent')+
        `<div class="three">${card('Knowledge','<p>I can tell someone what a condition and a repeat block do.</p>'+select('typeKnowledge','My starting point',[['new','New to me'],['some','I know a little'],['ready','I can explain it']]))}${card('Skills','<p>I can add blocks and test both visitor routes.</p>'+select('typeSkill','My starting point',[['new','New to me'],['some','I need practice'],['ready','I can do this']]))}${card('Understanding','<p>I can explain why the choice and flash help the visitor.</p>'+select('typeUnderstanding','My starting point',[['new','New to me'],['some','I have an idea'],['ready','I can explain why']]))}</div>`+
        card('How will I get better?', question('typeGoal','Choose one action you will try today.','For example: I will test both routes before moving on.'));
      case 'read-choice': return card('A condition helps a program choose', `<p>${t('A condition asks a question that can be true or false. In our program: “Did the visitor type left?” If yes, the robot says how to reach the Star Room. Otherwise, it says how to reach the Ocean Room. These are two branches.','条件会检查一个问题是否成立。例如：访客输入了 left 吗？如果是，机器人说出星星房间的方向；否则说出海洋房间的方向。')}</p>${map()}${blocksChoice()}<p class="small">This is a real Scratch screenshot of one possible answer. Your downloaded starter has only the opening blocks; you will add the choice yourself. For now, ask visitors to type only left or right. An unexpected word will follow the “else” route; the extension improves that.</p>`, 'accent')+
        options('choiceMeaning','What does this condition check?', [['typed-left','Whether the visitor typed left'],['flash-count','How many times the robot flashes'],['sprite-name','The robot’s name']], 'typed-left', 'The answer from the visitor decides which message runs.');
      case 'plan-choice': return card('Plan both outcomes before coding', `<p>${t('The visitor may choose left or right. Write one short, helpful robot message for each answer. Your messages should name the room, not just say “correct”.','访客可以选择左边或右边。请为每个选择写一句清楚的指路信息。')}</p>${map()}${question('leftMessage','If the visitor types left, what should the robot say?','Go left to the Star Room.')}${question('rightMessage','If the visitor types right, what should the robot say?','Go right to the Ocean Room.')}<div class="toolbar"><button type="button" data-action="preview-left">Preview left</button><button type="button" data-action="preview-right">Preview right</button></div><p id="previewResult" class="feedback" aria-live="polite"></p><p class="hint">This preview only checks your plan. The next page is where you build and test the program in Scratch.</p>`, 'accent');
      case 'scratch-choice': return card('Now build Main Task 1 in Scratch', `<p class="lead">${t('Stop answering on the website for now. Your job is to make the visitor choice in Scratch.','现在先停下网页答题，在 Scratch 中制作访客选择功能。')}</p>${launch()}${scratchShot('starter', 'This is what the starter looks like when opened in Scratch 3.', 'Scratch starter project showing the Glitch Museum backdrop, Explorer at the entrance, and only four connected opening blocks.') }<ol class="step-list"><li>Click the green flag. Check that you can see the entrance, two rooms and Explorer.</li><li>On Explorer, add <strong>ask [Left or right?] and wait</strong>.</li><li>Add <strong>if &lt;answer = left&gt; then / else</strong> and your two planned messages.</li><li>Run twice. Type <strong>left</strong> once and <strong>right</strong> once. Check the message each time.</li></ol><div class="warning">Do not mark the task done after only answering this website. Your real program must work in Scratch.</div>${select('leftTest','When you tested “left” in Scratch...', [['not-yet','Not tested yet'],['pass','The robot gave the Star Room message'],['issue','It gave the wrong message; I need to fix it']])}${select('rightTest','When you tested “right” in Scratch...', [['not-yet','Not tested yet'],['pass','The robot gave the Ocean Room message'],['issue','It gave the wrong message; I need to fix it']])}${status('choice','Before you go on')}`, 'accent');
      case 'pitstop': {
        const phase = state.answers.pitPhase || '';
        const actions = {new:'Try one more test and explain what the condition checks.',consolidating:'Hide the example and explain your blocks to a partner.',treading:'Try the unexpected-answer challenge on the Extension page.',drowning:'Ask for a smaller step: show the teacher your ask block and condition.'};
        return card('Learning Pitstop', `<p>${t('Pause after Main Task 1. Choose the description that fits your learning now. This is not a grade; it helps you choose your next step.','完成主任务一后先暂停。选择最符合你现在学习情况的一项。这不是分数。')}</p>${select('pitPhase','Where are you now?', [['new','New learning - I am trying a new idea'],['consolidating','Consolidating - I can do it and want to make it secure'],['treading','Treading water - I am ready for more challenge'],['drowning','Drowning - I need help with a smaller step']])}${phase ? `<p class="action"><strong>Your next step:</strong> ${actions[phase]}</p>` : ''}${question('pitNext','What will you do next?','One small step is enough.')}`, 'accent');
      }
      case 'read-repeat': return card('A repeat block does a job more than once', `<p>${t('The robot has given its direction. Now it needs to flash exactly three times. Put “hide, wait, show, wait” inside repeat (3). Scratch runs everything inside the repeat block three times.','机器人给出方向后，需要闪烁三次。把“隐藏、等待、显示、等待”放进重复三次的积木中。')}</p>${blocksRepeat()}<div class="flash-demo"><span id="flashDot" class="flash-dot" aria-label="Robot signal"></span><button type="button" data-action="flash">Watch three flashes</button><div class="count-track" aria-label="Flashes 1, 2, 3"><span>1</span><span>2</span><span>3</span></div></div><p class="hint">One flash is one full hide-and-show. The repeat number is the count, not the speed.</p>`, 'accent')+
        options('repeatMeaning','What happens when hide and show are inside repeat (3)?', [['three','The robot flashes three times'],['once','The robot flashes once'],['six','The robot flashes six times']], 'three', 'The two blocks together make one flash; Scratch repeats that pair three times.');
      case 'predict-repeat': return card('Predict before you run', `<p>${t('Read the model blocks. The robot is visible at the start. Every time through the loop it hides, waits, shows and waits. How many times will it disappear and return?','阅读积木：机器人一开始是可见的。每次循环都会隐藏、等待、显示、等待。它会闪烁几次？')}</p>${blocksRepeat()}${options('repeatPrediction','How many complete flashes do you predict?', [['two','2'],['three','3'],['six','6']], 'three', 'There are three repeats. Each repeat has one complete hide-and-show flash.')}<p class="hint">Next, test your prediction in Scratch. Clicking a choice here does not build the loop in your project.</p>`, 'accent');
      case 'scratch-repeat': return card('Now build Main Task 2 in Scratch', `<p class="lead">${t('Return to your Scratch project. Add the repeated signal after the visitor choice.','回到 Scratch 项目，在访客选择之后加入重复信号。')}</p><ol class="step-list"><li>On Explorer, place a <strong>repeat (3)</strong> block after the whole if/else choice.</li><li>Put <strong>hide, wait (0.2), show, wait (0.2)</strong> inside the repeat block.</li><li>Run the program. Choose left, count the flashes, then run again and choose right.</li><li>If the count or message is wrong, move one block and test again.</li></ol>${blocksComplete()}${select('observedFlashes','How many complete flashes did you see in Scratch?', [['not-yet','Not tested yet'],['3','3 flashes'],['different','A different number - I need to debug it']])}${question('loopFix','What did you check or change after testing?','For example: I moved show inside the repeat block.')}${status('repeat','Before you leave Main Task 2')}<div class="warning">The PDF records your thinking and tests. It does not contain your Scratch code. Save your project as a separate .sb3 file.</div>`, 'accent');
      case 'extension': return card('Try a Scratch extension', `<p>${t('First finish and test both main tasks in Scratch. Then choose a level below. Each level shows real Scratch blocks, tells you exactly what to change in your own project, and gives you a test. You can try more than one level.','先在 Scratch 中完成并测试两项主任务，再选择下面的挑战。每一关都有真实的 Scratch 积木、清楚的操作步骤和测试方法。你可以尝试多关。')}</p><p class="hint">These pictures are examples, not a new project to download. Keep working in the Scratch file you already made.</p>${extensionLevel()}${question('extensionResult','What did you change or fix while testing?','For example: I changed repeat from 3 to 5. I tested both routes.')}`, 'accent');
      case 'plenary': return card('Explain your choices', `<p>${t('Answer in your own words. A short, clear explanation is better than copying the block names.','用自己的话简短说明，不要只抄积木名称。')}</p>${question('plenaryChoice','Why does the robot need a condition for the visitor’s route?')}${question('plenaryRepeat','Why is repeat (3) better than writing hide and show three separate times?')}${question('plenaryTest','How do you know both routes work? Name the tests you ran.')}`, 'accent');
      case 'reflection': return card('Exit Reflection', `<p>${t('Think about what you can do now. If a part was difficult, describe the next small step you need.','想一想你现在能做到什么；若有困难，写下你需要的下一小步。')}</p>${select('exitPhase','My learning now', [['new','I learned a new idea'],['consolidating','I can do it with growing confidence'],['challenge','I am ready for another challenge'],['help','I need help with one step']])}${question('reflection','Complete this: Today I can..., and next I will...','Today I can test a choice. Next I will...')}`, 'accent');
      case 'submit': return card('Save your work and hand it in', `<ol class="step-list"><li>In Scratch, select <strong>File > Save to your computer</strong>. Check you have an <code>.sb3</code> project.</li><li>At the top of this page, select <strong>Full backup</strong>. Keep the <code>.json</code> file if you will continue on another device.</li><li>Select <strong>Save PDF</strong>. Open it and check your answers are readable.</li><li>In your teacher’s Teams assignment, attach both the <strong>PDF</strong> and the <strong>Scratch .sb3</strong> file, then select <strong>Turn in</strong>.</li></ol><div class="grid">${card('PDF','<p>Your plan, test notes, pitstop and explanations. This website creates it.</p>')}${card('SB3','<p>Your working Scratch program. Save it from Scratch, not from this website.</p>')}</div><p class="small">A JSON file restores website progress. It is not your Scratch project. The website does not upload or submit files automatically.</p><p><a href="https://teams.microsoft.com/" target="_blank" rel="noopener">Open Microsoft Teams ↗</a></p>`, 'accent');
      default: return card('Page unavailable','<p>Return to the previous page.</p>');
    }
  }
  function keyFor(name, cls) { return APP + ':' + name.trim().toLowerCase() + '|' + cls.trim().toLowerCase(); }
  function blank(name, cls, mode, partner, language) { return {version:1,name,cls,mode,partner,language,page:0,maxPage:0,answers:{},checks:{},started:new Date().toISOString()}; }
  function validate(s) {
    if (!s || s.version !== 1 || typeof s.name !== 'string' || !s.name.trim() || typeof s.cls !== 'string' || !Number.isInteger(s.page) || s.page < 0 || s.page >= pages.length || !Number.isInteger(s.maxPage) || s.maxPage < 0 || s.maxPage >= pages.length || !['solo','pair'].includes(s.mode) || !['en','bi'].includes(s.language) || typeof s.partner !== 'string' || !s.answers || typeof s.answers !== 'object' || Array.isArray(s.answers) || !s.checks || typeof s.checks !== 'object' || Array.isArray(s.checks)) throw Error('This is not a Week 5 lesson backup.');
    for (const [k,v] of Object.entries(s.answers)) if (!(k in labels || ['pitPhase','extensionPlan','exitPhase'].includes(k)) || typeof v !== 'string' || v.length > 3000) throw Error('This backup contains an invalid answer.');
    for (const [k,v] of Object.entries(s.checks)) if (!['choice','repeat'].includes(k) || !['done','help'].includes(v)) throw Error('This backup contains an invalid task status.');
    return s;
  }
  function save() {
    if (!state) return;
    try { localStorage.setItem(keyFor(state.name,state.cls),JSON.stringify(state)); $('saveStatus').textContent='Saved on this device'; }
    catch { $('saveStatus').textContent='Device save unavailable - download a Full backup'; }
  }
  function render(preserve=false) {
    if (!state) return;
    const y = window.scrollY;
    const [id,title,time] = pages[state.page];
    $('identity').textContent = `${state.name}${state.mode === 'pair' && state.partner ? ' + ' + state.partner : ''} · ${state.cls || 'Teacher preview'}`;
    $('content').innerHTML = `<div class="stage-head"><p class="eyebrow">${esc(time)} · YEAR 6 · WEEK 5</p><h1 tabindex="-1">${esc(title)}</h1><p>${state.page + 1} of ${pages.length} lesson pages</p><div class="progress-track" role="progressbar" aria-label="Lesson position" aria-valuemin="1" aria-valuemax="${pages.length}" aria-valuenow="${state.page+1}"><span style="width:${Math.round((state.page+1)/pages.length*100)}%"></span></div></div>${content(id)}<p id="gateMessage" class="error" role="alert"></p>`;
    $('nav').innerHTML = pages.map(([pid,label],i) => `<button type="button" data-page="${i}" data-complete="${i < state.maxPage}" ${i === state.page ? 'aria-current="step"' : ''} ${i > state.maxPage && !teacher() ? 'disabled title="Follow the lesson steps in order"' : ''}>${String(i+1).padStart(2,'0')} · ${esc(label)}</button>`).join('');
    $('prev').disabled = state.page === 0;
    $('next').disabled = state.page === pages.length-1;
    $('position').textContent = `${state.page+1} / ${pages.length} · ${title}`;
    if (preserve) window.scrollTo(0,y);
  }
  function show() { $('landing').hidden=true; $('lesson').hidden=false; $('backup').disabled=false; $('pdf').disabled=false; render(); }
  function go(n) { if (!state) return; state.page=Math.max(0,Math.min(pages.length-1,n)); state.maxPage=Math.max(state.maxPage,state.page); render(); save(); window.scrollTo(0,0); $('content').querySelector('h1')?.focus({preventScroll:true}); }
  function advance() {
    if (!teacher() && pages[state.page][0] === 'scratch-choice' && !state.checks.choice) return $('gateMessage').textContent='Choose whether you tested Main Task 1 in Scratch or need help before moving on.';
    if (!teacher() && pages[state.page][0] === 'scratch-repeat' && !state.checks.repeat) return $('gateMessage').textContent='Choose whether you tested Main Task 2 in Scratch or need help before moving on.';
    go(state.page+1);
  }
  function download(blob, name) { const url=URL.createObjectURL(blob),a=document.createElement('a'); a.href=url; a.download=name; a.click(); setTimeout(()=>URL.revokeObjectURL(url),30000); }
  const fileStem = () => `Y6_Week5_${state.name}_${state.cls}`.replace(/[^a-z0-9_-]/gi,'_');
  function backup() { download(new Blob([JSON.stringify({app:APP,state},null,2)],{type:'application/json'}),fileStem()+'_backup.json'); }
  function pdf() {
    if (!window.jspdf?.jsPDF) return alert('The PDF tool did not load. Download a Full backup and ask your teacher for help.');
    const d=new window.jspdf.jsPDF({unit:'mm',format:'a4',compress:true});
    let y=20;
    const line=(value,size=11,bold=false) => { d.setFont('helvetica',bold?'bold':'normal'); d.setFontSize(size); const rows=d.splitTextToSize(String(value||'Not recorded'),174); for(const row of rows){if(y>269){d.addPage();y=20;}d.text(row,18,y);y+=size*.47+1;} y+=2;};
    const head=title => { if(y>240){d.addPage();y=20;} line(title,15,true); };
    line('YEAR 6 COMPUTING - TERM 1 WEEK 5',11,true);line('Selection and repetition',22,true);line(`${state.name}${state.mode==='pair'&&state.partner?' + '+state.partner:''} | ${state.cls || 'Teacher preview'}`);line('WAGBA: Make a program choose and repeat an action for a reason.');line('This report records website answers. The Scratch .sb3 project is separate.',10);y+=4;
    for(const [id,title] of pages){if(id==='submit')continue;const keys=Object.keys(labels).filter(k=>({
      'do-now':['doNowChoice','doNowLoop'],'types':['typeKnowledge','typeSkill','typeUnderstanding','typeGoal'],'read-choice':['choiceMeaning'],'plan-choice':['leftMessage','rightMessage'],'scratch-choice':['leftTest','rightTest'],'pitstop':['pitPhase','pitNext'],'read-repeat':['repeatMeaning'],'predict-repeat':['repeatPrediction'],'scratch-repeat':['observedFlashes','loopFix'],'extension':['extension1','extension2','extension3','extensionResult'],'plenary':['plenaryChoice','plenaryRepeat','plenaryTest'],'reflection':['exitPhase','reflection']
    })[id]?.includes(k));if(!keys.length&& !['scratch-choice','scratch-repeat'].includes(id))continue;head(title);for(const k of keys){line(labels[k],10,true);line(state.answers[k] || 'Not recorded',10);}if(id==='scratch-choice'||id==='scratch-repeat'){line('Scratch task status',10,true);line(state.checks[id==='scratch-choice'?'choice':'repeat']==='done'?'Student reports built and tested in Scratch':state.checks[id==='scratch-choice'?'choice':'repeat']==='help'?'Needs help or will continue later':'Not recorded',10);}y+=3;}
    const total=d.getNumberOfPages();for(let i=1;i<=total;i++){d.setPage(i);d.setDrawColor(190,204,194);d.line(18,282,192,282);d.setFont('helvetica','normal');d.setFontSize(8);d.text('Year 6 Week 5 | '+state.name.slice(0,45),18,288);d.text(`${i} / ${total}`,192,288,{align:'right'});}d.save(fileStem()+'.pdf');$('saveStatus').textContent='PDF downloaded - open it and check it';
  }
  $('login').addEventListener('submit',e => { e.preventDefault(); const name=$('name').value.trim(),cls=$('className').value.trim(),mode=document.querySelector('[name="mode"]:checked').value,partner=$('partner').value.trim(),language=$('language').value;if(!name||(!cls&&name.toLowerCase()!=='teacher'))return $('loginError').textContent='Enter your name and class.';let s=blank(name,cls,mode,partner,language);try{const old=localStorage.getItem(keyFor(name,cls));if(old)s=validate(JSON.parse(old));}catch{}s.mode=mode;s.partner=mode==='pair'?partner:'';s.language=language;state=s;show();save(); });
  document.querySelectorAll('[name="mode"]').forEach(r => r.addEventListener('change',() => $('partnerWrap').hidden=document.querySelector('[name="mode"]:checked').value!=='pair'));
  $('restore').addEventListener('change',async e => { pendingRestore=null;$('restorePanel').hidden=true;try{const f=e.target.files[0];if(!f)return;if(f.size>2*1024*1024)throw Error('This backup is too large.');const o=JSON.parse(await f.text());if(o.app!==APP)throw Error('Choose a Year 6 Week 5 backup.');pendingRestore=validate(o.state);$('restoreSummary').textContent=`Restore work for ${pendingRestore.name} (${pendingRestore.cls})? This replaces that learner's saved progress on this device.`;$('restorePanel').hidden=false;$('loginError').textContent='';}catch(err){$('loginError').textContent=err.message;} });
  $('confirmRestore').addEventListener('click',() => {if(!pendingRestore)return;state=pendingRestore;pendingRestore=null;$('restorePanel').hidden=true;show();save();});
  $('cancelRestore').addEventListener('click',() => {pendingRestore=null;$('restorePanel').hidden=true;});
  document.addEventListener('input',e => {if(!state)return;if(e.target.dataset.a){state.answers[e.target.dataset.a]=e.target.value;save();}});
  document.addEventListener('change',e => {if(!state)return;const target=e.target;if(target.dataset.a){state.answers[target.dataset.a]=target.value;save();if(target.matches('select,input[type=radio]'))render(true);}if(target.dataset.check){state.checks[target.dataset.check]=target.value;save();render(true);}});
  document.addEventListener('click',e => {const b=e.target.closest('button');if(!b)return;if(b.id==='backup'&&state)return backup();if(b.id==='pdf'&&state)return pdf();if(b.id==='switch'){state=null;$('lesson').hidden=true;$('landing').hidden=false;$('backup').disabled=true;$('pdf').disabled=true;$('identity').textContent='YEAR 6 · TERM 1 · WEEK 5';$('saveStatus').textContent='Your work stays on this device until you save it.';return;}if(!state)return;
    if(b.id==='prev')return go(state.page-1);if(b.id==='next')return advance();if(b.dataset.page!==undefined)return go(Number(b.dataset.page));
    if(b.dataset.action==='preview-left'||b.dataset.action==='preview-right'){const left=b.dataset.action==='preview-left';$('previewResult').textContent=left?(state.answers.leftMessage||'Write your left message first.'):(state.answers.rightMessage||'Write your right message first.');}
    if(b.dataset.action==='flash'){const dot=$('flashDot');dot.classList.remove('run');void dot.offsetWidth;dot.classList.add('run');}
    if(b.dataset.level){state.answers.extensionPlan=b.dataset.level;save();render(true);}
  });
})();
