(()=>{
 'use strict';
 const L=ConsolidationLesson,P=ConsolidationProgress,$=q=>document.querySelector(q),e=ConsolidationReport.escape;
 const PREFIX='consolidation:'+L.id+':',INDEX=PREFIX+'profiles';
 let s=null,worker=null,workerURL=null,watchdog=null,playback=null,activeRun=null,banner='',missingShown=false,quizIndex=0,exitIndex=0,pdf=null,layoutObserver=null;
 const uuid=()=>StudentWorkCloud.uuid();
 const allCards=[...L.cards,...L.extras],card=()=>allCards.find(c=>c.id===s?.current);
 function profiles(){try{return JSON.parse(localStorage.getItem(INDEX)||'[]');}catch{return [];}}
 function record(type,cardId=s?.current,details={}){if(!s||!['response','python-run','feedback-open','code-reset','python-download','backup-restored','lesson-finished','quiz-answer','quiz-check','quiz-start','external-game-open','drawing-style'].includes(type))return;s.events.push({id:uuid(),type,cardId,at:new Date().toISOString(),...details});if(s.events.length>180)s.events.splice(0,s.events.length-180);s.eventCounts[type]=(s.eventCounts[type]||0)+1;}
 function save(){if(!s)return false;s.updatedAt=new Date().toISOString();try{localStorage.setItem(PREFIX+s.student.id,JSON.stringify(s));localStorage.setItem(PREFIX+'last',s.student.id);s.saveError=false;status('Saved on this device');StudentWorkCloud.changed(s);return true;}catch{s.saveError=true;status('Device saving unavailable — download a JSON backup','error');return false;}}
 function status(text,cls=''){const t=$('#save-status');if(t){t.textContent=text;t.className='save-status '+cls;}}
 function reopenDraft(){s.finished=false;delete s.finishedAt;delete s.completed.finish;}
 function finishStatus(){const submitted=StudentWorkCloud.submitted(s),connected=StudentWorkCloud.validCloud(s.cloud);return {title:submitted?'Submitted to teacher ✓':s.finished?(connected?'Finished on device · waiting for class save':'Finished on this device'):'Finish your lesson',message:submitted?'Your teacher can open your latest saved work. No PDF upload is required for this submission.':connected?'Tap Finish and save. We only confirm submission after your class save succeeds. If the internet is unavailable, your device copy and backup remain available.':'This is a device-only session. Finish saves here; use a private backup or your teacher’s current class link.'};}
 function refreshFinishStatus(){if(!s)return;const x=finishStatus();if($('#finish-status-title'))$('#finish-status-title').textContent=x.title;if($('#finish-status-message'))$('#finish-status-message').textContent=x.message;}
 function newState(name,klass,lang,device){return {schemaVersion:1,lessonId:L.id,lessonVersion:L.version,student:{id:uuid(),name,class:klass},teacher:name.toLowerCase()==='teacher',language:lang,device,current:'welcome',frontier:0,answers:{},answerHistory:{},completed:{},checks:{},orders:{},codes:{},runs:{},drawingStyles:{},events:[],eventCounts:{},visits:{},hints:{},quiz:{attempts:[],active:null},finished:false,startedAt:new Date().toISOString(),updatedAt:new Date().toISOString(),speed:'normal'};}
 function normalise(x){if(!x||x.schemaVersion!==1||x.lessonId!==L.id||!x.student?.id||!x.student?.name||!x.answers||typeof x.answers!=='object'||!Array.isArray(x.events))throw Error('Choose a backup from this consolidation lesson.');for(const k of ['answerHistory','completed','checks','orders','codes','runs','drawingStyles','eventCounts','visits','hints'])x[k]??={};x.quiz??={attempts:[],active:null};x.frontier=Math.max(0,Math.min(L.cards.length-1,Number(x.frontier)||0));if(!allCards.some(c=>c.id===x.current)&&x.current!=='quiz')x.current='welcome';x.teacher=x.student.name.toLowerCase()==='teacher';if(x.lessonVersion!==L.version){x.previousLessonVersion=x.lessonVersion;x.lessonVersion=L.version;x.finished=false;x.current='welcome';delete x.completed.finish;delete x.completed.welcome;if(x.quiz.attempts.length||x.quiz.active)x.previousQuiz=x.quiz;x.quiz={attempts:[],active:null};}if(x.support&&Object.keys(x.support).length)x.legacySupport=x.support;delete x.support;return x;}
 function start(name,klass,lang,device){const teacher=name.toLowerCase()==='teacher',known=profiles().find(p=>p.name.trim().toLowerCase()===name.toLowerCase()&&p.class.trim().toLowerCase()===klass.toLowerCase()&&!!p.teacher===teacher);try{s=known?normalise(JSON.parse(localStorage.getItem(PREFIX+known.id))):newState(name,klass,lang,device);}catch{s=newState(name,klass,lang,device);}s.language=lang;s.device=device;if(teacher)s.student.class='';register();record('session-start');save();render();connectCloud();}
 function register(){try{const list=profiles().filter(p=>p.id!==s.student.id);list.push({...s.student,teacher:s.teacher});localStorage.setItem(INDEX,JSON.stringify(list));}catch{}}
 function zh(text){return s?.language==='zh'&&text?'<p class="zh" lang="zh-Hans">'+e(text)+'</p>':'';}
 function code(text){return '<pre translate="no"><code>'+e(text)+'</code></pre>';}
 function button(text,action,cls=''){return '<button type="button" class="'+cls+'" data-action="'+action+'">'+text+'</button>';}
 function landing(){s=null;$('#app').innerHTML='<main id="main" class="landing"><section><span class="eyebrow">Year 7 · Term 1 · Week 7 · Theory · 60 minutes</span><h1>Plan, check<br>and improve.</h1><p>Three graphics, three different patterns. Plan a triangle, create a hexagon and repair a zigzag. Pick your own drawing colours, then explore rainbow and sparkle designs.</p>'+gallery()+'<div class="goal"><strong>WAGBA</strong><p>'+e(L.wagba)+'</p></div><p class="small" style="margin-top:15px">Use your teacher’s private class link to save online. Your work also saves on this device. No screenshots or PDF upload are needed for class saving.</p></section><form class="entry" id="entry"><h2>Start or continue your lesson</h2><label for="student-name">Full name</label><input id="student-name" autocomplete="name" maxlength="100" required><label for="student-class">Class</label><input id="student-class" placeholder="For example, 7T" maxlength="30"><div class="support-choice"><label for="entry-language">Language support</label><select id="entry-language"><option value="en">English</option><option value="zh">English + 中文 help</option></select><label for="entry-device">Your device</label><select id="entry-device"><option value="computer">Laptop / computer</option><option value="tablet">iPad / tablet</option></select><p class="small">You can change these choices during the lesson.</p></div><button class="primary" type="submit">Start / continue lesson →</button><p class="entry-status" id="entry-error" role="alert"></p><div class="tools">'+(profiles().length?button('How to resume','resume'):'')+button('Restore JSON backup','restore')+'</div><p class="small" style="margin-top:14px">On a shared device, check that the displayed name is yours. No email or password is required.</p></form></main>';$('#entry').onsubmit=ev=>{ev.preventDefault();const name=$('#student-name').value.trim(),klass=$('#student-class').value.trim();if(!name||(!klass&&name.toLowerCase()!=='teacher')){$('#entry-error').textContent='Enter your full name and class before starting.';return;}start(name,name.toLowerCase()==='teacher'?'':klass,$('#entry-language').value,$('#entry-device').value);};const launch=StudentWorkCloud.launch;if(launch?.label){$('#student-class').value=launch.label;$('#student-class').readOnly=true;}bindActions();}
 function goals(){return '<h2>Today’s learning</h2><h3>Key topic</h3><p>'+e(L.topic)+'</p><h3>Knowledge</h3><p>'+e(L.k)+'</p><h3>Skills</h3><p>'+e(L.s)+'</p><h3>Understanding</h3><p>'+e(L.u)+'</p><h3>Keywords · tap a word</h3>'+Object.entries(L.keywords).map(([word,v])=>'<details><summary>'+e(word)+'</summary><p>'+e(v[0])+'</p>'+zh(v[1])+'</details>').join('');}
 function sectionFor(id=s.current){return L.sections.find(x=>x.cards.includes(id))||L.sections.find(x=>x.id===(L.extras.some(c=>c.id===id)?'extension':'finish'));}
 function journey(){const active=sectionFor(),required=P.required(),done=required.filter(c=>P.complete(s,c)).length;return '<nav class="journey" aria-label="Lesson stages">'+L.sections.map((sec,i)=>{const defs=sec.cards.map(id=>allCards.find(c=>c.id===id)),n=defs.filter(c=>P.complete(s,c)).length;return '<button data-section="'+sec.id+'" class="stage-button '+(active?.id===sec.id?'current':'')+'" '+(active?.id===sec.id?'aria-current="step"':'')+' title="'+e(sec.detail)+'"><span class="stage-number">'+(i+1)+'</span><span>'+e(sec.label)+'<small>'+e(sec.detail)+' · '+n+'/'+defs.length+'</small></span></button>';}).join('')+'</nav><div class="journey-progress"><span>'+done+' / '+required.length+' activities recorded · not a grade</span><span>Use any stage to revisit or continue.</span><div class="progress-track" role="progressbar" aria-label="Activities recorded" aria-valuemin="0" aria-valuemax="'+required.length+'" aria-valuenow="'+done+'"><span style="width:'+Math.round(done/required.length*100)+'%"></span></div></div>';}
 function subnav(c){const sec=sectionFor(c.id);if(!sec||sec.cards.length<2)return '';return '<nav class="subnav" aria-label="Practice cards within '+e(sec.label)+'">'+sec.cards.map((id,i)=>{const d=allCards.find(x=>x.id===id);return '<button data-go="'+id+'" '+(id===c.id?'aria-current="page"':'')+'>'+ (i+1)+' · '+e(d.title.replace(/^(Main task [12]|Read first) · /,'').replace(/^Practice [123] · /,''))+' <span aria-label="'+(P.complete(s,d)?'Response recorded':'Not yet complete')+'">'+(P.complete(s,d)?'✓':'○')+'</span></button>';}).join('')+'</nav>';}
 function render(){if(!s)return landing();const c=card(),quiz=s.current==='quiz',sec=sectionFor();
  $('#app').innerHTML='<div class="shell"><header class="topbar"><div class="toolbar"><div><button class="learner-button" data-action="profile" aria-label="Your saved work and learner settings">'+e(s.student.name)+' '+e(s.student.class)+'</button><div id="save-status" class="save-status">Saved on this device</div></div><div class="toolbar-actions">'+button(s.language==='zh'?'English + 中文':'Language help','language','quiet')+button('Device help','device','quiet')+button('↓ Download backup','json','quiet backup-button')+(s.teacher?'<a class="button quiet" href="teacher.html" target="_blank" rel="noopener noreferrer">Teacher dashboard ↗</a>':'')+'</div></div><p class="compact-goal"><strong>WAGBA:</strong> '+e(L.wagba)+'</p><details class="mobile-learning"><summary>Knowledge · Skills · Understanding · Keywords</summary><div class="goals">'+goals()+'</div></details></header>'+journey()+'<div class="lesson-layout"><aside class="learning-panel" aria-label="Learning goals">'+goals()+'</aside><main id="main" class="activity"><div class="stage-line"><strong>'+e(quiz?'After finishing · revision practice':sec.label+' · '+sec.detail)+'</strong><span>'+e(quiz?'15 questions':sec.cards.length>1?'Card '+(sec.cards.indexOf(c.id)+1)+' of '+sec.cards.length:'')+'</span></div>'+(quiz?'':subnav(c))+'<div class="card-header"><h1 id="card-title" tabindex="-1">'+e(quiz?'Play the revision questions':c.title)+'</h1><div class="goal"><strong>Your goal · 你的目标</strong><p>'+e(quiz?'Choose an answer, check the explanation and try again if useful.':c.goal)+'</p></div></div>'+(banner?'<div class="notice" role="alert">'+e(banner)+'</div>':'')+cloudPanel()+(quiz?quizBody():body(c))+'<nav class="bottom-nav">'+button(quiz?'Back to finish':L.extras.some(x=>x.id===c?.id)?'Back to extension':'← Back','back')+'<span class="save-note">'+(s.teacher?'Preview · every stage available':'Your work saves automatically')+'</span>'+(quiz||c.id==='finish'?'':button(c.kind==='exit'&&exitIndex<c.questions.length-1?'Next question →':'Save and continue →','next','primary'))+'</nav></main></div></div>';
  bind();measureLayout();if(c?.kind==='editor')paintEditor(c);if(missingShown&&c)showRequirements(c);if(s.saveError)status('Device saving unavailable — download a JSON backup','error');else if(StudentWorkCloud.status().text)status(StudentWorkCloud.status().text,StudentWorkCloud.status().kind);
 }
 function measureLayout(){layoutObserver?.disconnect();const header=$('.topbar'),nav=$('.journey');const update=()=>{for(const [el,key]of [[header,'--header-height'],[nav,'--journey-height']])if(el)document.documentElement.style.setProperty(key,Math.ceil(el.getBoundingClientRect().height)+'px');};update();if(globalThis.ResizeObserver){layoutObserver=new ResizeObserver(update);layoutObserver.observe(header);layoutObserver.observe(nav);}}
 function navigate(id){if(!P.allowed(s,id)){banner='Finish and save the lesson before opening the practice game.';render();return;}stopRun();s.current=id;banner='';missingShown=false;exitIndex=0;save();render();window.scrollTo({top:0,behavior:'auto'});$('#card-title')?.focus({preventScroll:true});}
 function next(){if(s.current==='quiz')return;const c=card();if(c.id==='finish')return;
  let gaps=P.requirements(s,c).filter(x=>!x.done);
  if(c.kind==='exit'&&exitIndex<c.questions.length-1){gaps=gaps.filter(x=>x.id===c.questions[exitIndex].id);if(!gaps.length){exitIndex++;banner='';missingShown=false;render();$('#card-title')?.scrollIntoView({block:'start'});return;}}
  if(gaps.length&&!s.teacher){banner='Before continuing: '+gaps[0].label+' You can also use the stage bar and return to this activity later.';missingShown=true;if(c.kind==='exit'){const n=c.questions.findIndex(q=>q.id===gaps[0].id);if(n>=0)exitIndex=n;}render();focusField(gaps[0].id);return;}
  s.completed[c.id]={at:new Date().toISOString(),kind:'attempt'};save();const i=L.cards.findIndex(x=>x.id===c.id);if(i>=0)navigate(L.cards[Math.min(i+1,L.cards.length-1)].id);else navigate('extras');
 }
 function back(){if(s.current==='quiz')return navigate('finish');const c=card();if(L.extras.some(x=>x.id===c.id))return navigate('extras');const i=L.cards.findIndex(x=>x.id===c.id);if(i>0)navigate(L.cards[i-1].id);else changeLearner();}
 function answer(c,id,value){const a=s.answers[c.id]??={},wasChecked=!!s.checks[c.id];a[id]=value;reopenDraft();s.checks[c.id]=false;const key=c.id+':'+id;const h=s.answerHistory[key]??=[];h.push({value,at:new Date().toISOString()});if(h.length>12)h.splice(1,1);record('response',c.id,{questionId:id});save();if(wasChecked)render();else if(missingShown)showRequirements(c);}
 function choice(c,q){const value=s.answers[c.id]?.[q.id],checked=s.checks[c.id];return '<fieldset class="task question" data-field="'+q.id+'"><legend>'+e(q.label)+'</legend><span class="question-tag">'+(q.selfAssess?'COMPARE · 比较':'YOUR TURN · 作答')+'</span>'+zh(q.zh)+q.options.map((v,i)=>{const selected=String(value)===String(i),mark=selected&&checked&&!q.selfAssess?(i===q.answer?'answer-correct':'answer-incorrect'):'';return '<label class="option '+mark+'"><input type="radio" name="'+q.id+'" data-answer="'+q.id+'" value="'+i+'" '+(selected?'checked':'')+'><span>'+e(v)+'</span></label>';}).join('')+'</fieldset>';}
 function textField(c,t){return '<section class="task question" data-field="'+t.id+'"><label for="field-'+t.id+'"><strong>'+e(t.label)+'</strong></label><p class="small">'+e(t.prompt)+'</p><textarea id="field-'+t.id+'" data-text="'+t.id+'" rows="2" maxlength="2000" placeholder="A short phrase is enough. 短语也可以。">'+e(s.answers[c.id]?.[t.id]||'')+'</textarea></section>';}
 function questions(c){return (c.questions||[]).map(q=>choice(c,q)).join('')+(c.text?textField(c,c.text):'');}
 function read(c){return c.read?'<section class="reading"><span class="reading-tag">READ · 理解</span><p>'+e(c.read)+'</p>'+zh(c.zh)+'</section>':'';}
 function feedback(c,only=null){if(!s.checks[c.id])return '';if(c.kind==='multi'){const vals=s.answers[c.id]?.sections||[],ok=vals.length===c.answers.length&&c.answers.every(v=>vals.includes(v));return '<div class="feedback '+(ok?'correct':'review')+'"><h3>'+(ok?'✓ These jobs belong to the collection.':'↻ Not quite yet — compare the smaller jobs.')+'</h3><p>'+e(c.why)+'</p><p class="small">You may improve your choices or continue with your attempt.</p></div>';}
  return (only||c.questions||[]).filter(q=>P.filled(s.answers[c.id]?.[q.id])).map(q=>{const val=s.answers[c.id][q.id],neutral=q.selfAssess,ok=+val===q.answer;return '<section class="feedback '+(neutral?'neutral':ok?'correct':'review')+'"><h3>'+(neutral?'Observation saved — compare for yourself.':ok?'✓ That answer matches.':'↻ Not quite yet — try this idea.')+'</h3><p>'+e(q.why)+'</p>'+(neutral?'':'<p class="small">You can change your answer. Your attempt is saved either way.</p>')+'</section>';}).join('');
 }
 function targetPanel(c){return c.target?'<figure class="target-panel"><figcaption><strong>Target · what you are aiming for</strong></figcaption><img src="assets/targets/'+e(c.target)+'.svg" alt="'+e(c.targetNotes||c.goal)+'"><p>'+e(c.targetNotes||'Compare your output with this drawing.')+'</p>'+(c.kind==='editor'?'<p class="colour-note">Match the shape. Your colours can differ.</p>':'')+'</figure>':'';}
 function exitBody(c){const q=c.questions[exitIndex];return '<nav class="question-tabs" aria-label="Plenary questions">'+c.questions.map((x,i)=>'<button data-exit="'+i+'" '+(i===exitIndex?'aria-current="page"':'')+'>'+ (i+1)+' '+(P.filled(s.answers[c.id]?.[x.id])?'✓':'○')+'</button>').join('')+'</nav><p class="small">Question '+(exitIndex+1)+' of '+c.questions.length+' · choose first, then check the explanation.</p>'+choice(c,q)+(exitIndex===c.questions.length-1&&c.text?textField(c,c.text):'')+button('Check this answer','check')+feedback(c,[q]);}
 function body(c){const out=read(c)+(c.visual?visual(c.visual):'')+(c.code?code(c.code):'');switch(c.kind){
  case 'welcome':return out+'<section class="task"><h2>How to work through the lesson</h2><p>Follow the stage bar from left to right. <strong>Read first</strong> prepares you for each task. The smaller buttons inside a main task show its practice cards.</p><p>Read <strong>Your goal</strong>, do the action, then choose <strong>Save and continue</strong>. You can revisit any stage. Incorrect answers are useful attempts, not locks.</p><p>Your code and drawing evidence are captured automatically. <strong>Download backup</strong> at the top right saves a JSON copy. The finish page offers a PDF.</p></section>';
  case 'read':return out+targetPanel(c);
  case 'questions':return out+questions(c)+button('Check my answer','check')+feedback(c);
  case 'ratings':return out+[['k','Knowledge',L.k],['s','Skills',L.s],['u','Understanding',L.u]].map(([id,label,t])=>'<section class="task question" data-field="rating-'+id+'"><label for="rating-'+id+'"><strong>'+label+'</strong> · '+e(t)+'</label><select id="rating-'+id+'" data-select="rating-'+id+'"><option value="">Choose…</option>'+['I can do this on my own','I can do this with an example','I need help to start','I have not tried this yet'].map(v=>'<option '+(s.answers[c.id]?.['rating-'+id]===v?'selected':'')+'>'+v+'</option>').join('')+'</select></section>').join('');
  case 'multi':return out+'<fieldset class="task question" data-field="sections"><legend>Choose the three drawing jobs.</legend>'+c.options.map((v,i)=>'<label class="option '+(s.checks[c.id]&&s.answers[c.id]?.sections?.includes(i)?c.answers.includes(i)?'answer-correct':'answer-incorrect':'')+'"><input type="checkbox" data-multi="'+i+'" '+(s.answers[c.id]?.sections?.includes(i)?'checked':'')+'><span>'+e(v)+'</span></label>').join('')+'</fieldset>'+button('Check my choices','check')+feedback(c);
  case 'parsons':{s.orders[c.id]??=[2,4,1,0,3];const order=s.orders[c.id];return out+'<div class="planning-layout">'+targetPanel(c)+'<div data-field="order">'+order.map((v,i)=>'<div class="strip"><span class="strip-number">'+(i+1)+'</span><pre>'+e(c.strips[v])+'</pre><div class="arrows"><button data-shift="'+i+',-1" '+(i===0?'disabled':'')+' aria-label="Move strip '+(i+1)+' up">↑ Up</button><button data-shift="'+i+',1" '+(i===order.length-1?'disabled':'')+' aria-label="Move strip '+(i+1)+' down">↓ Down</button></div></div>').join('')+button('Check my order','check')+(s.checks[c.id]?'<div class="feedback '+(order.every((v,i)=>v===i)?'correct':'review')+'"><h3>'+(order.every((v,i)=>v===i)?'✓ Your order follows the plan.':'↻ Review the order, then try again.')+'</h3><p>START → setup → repeat move and turn three times → finish at the start → END.</p><p class="small">You can rearrange, or continue with your attempt.</p></div>':'')+'</div></div>';}
  case 'flow':return out+'<div class="planning-layout">'+targetPanel(c)+flow(c)+'</div>';
  case 'editor':return '<section class="action-steps"><strong>DO THIS · 按步骤做</strong><ol>'+c.steps.map(v=>'<li>'+e(v)+'</li>').join('')+'</ol>'+zh(c.zh)+'</section>'+editor(c);
  case 'extras':return out+'<div class="card-grid">'+L.extras.map(x=>'<section class="challenge-card">'+targetPanel(x)+'<h2>'+e(x.title)+'</h2><p>'+e(x.goal)+'</p><button data-go="'+x.id+'">Try this design →</button><p class="small">'+(P.complete(s,x)?'Attempt recorded':s.runs[x.id]?.length?'Started · '+s.runs[x.id].length+' runs':'Not started')+'</p></section>').join('')+'</div>';
  case 'pitstop':return out+choice(c,{id:'phase',label:'My current phase of learning…',selfAssess:true,options:['New learning · I am learning through a useful challenge','Consolidating · I am getting better at what I already know','Treading water · I need a harder challenge','Drowning · I need help to move forward']})+'<section class="task question" data-field="next"><label for="next-step"><strong>Choose one useful next step</strong></label><select id="next-step" data-select="next"><option value="">Choose…</option>'+['Trace one loop with an example','Explain one correction to a partner','Try a new drawing challenge','Ask my teacher to demonstrate a difficult part'].map(v=>'<option '+(s.answers[c.id]?.next===v?'selected':'')+'>'+v+'</option>').join('')+'</select></section>';
  case 'exit':return exitBody(c);case 'finish':return finishBody();default:return out;
 }}
 function flow(c){const g=c.flow,select=(id,opts)=>'<select data-select="'+id+'" aria-label="'+id+' flowchart choice"><option value="">Choose…</option>'+opts.map(v=>'<option '+(s.answers[c.id]?.[id]===v?'selected':'')+'>'+v+'</option>').join('')+'</select>';const a=s.answers[c.id]||{},ok=a.move==='Move forward '+g.distance&&a.turn==='Turn right '+g.angle+' degrees'&&a.no==='Draw the next side';return '<section class="task"><div class="flow"><div class="flow-node oval">START</div><div class="flow-arrow">↓</div><div class="flow-node">Set Turtle at (0, 0), facing right.<br>Set sides drawn to 0.</div><div class="flow-arrow">↓</div><div class="flow-node" data-field="move">'+select('move',['Move forward '+g.distance,'Move forward '+g.count,'Turn left '+g.distance])+'</div><div class="flow-arrow">↓</div><div class="flow-node" data-field="turn">'+select('turn',['Turn right '+g.angle+' degrees','Turn right '+g.count+' degrees','Move forward '+g.angle])+'</div><div class="flow-arrow">↓</div><div class="flow-node">Add 1 to sides drawn.</div><div class="flow-arrow">↓</div><div class="flow-node decision">Have '+g.count+' sides been drawn?</div><div class="flow-arrow">Yes ↓</div><div class="flow-node oval">END</div><div class="return" data-field="no"><strong>No → go back to…</strong>'+select('no',['Draw the next side','START and reset the drawing','END'])+'</div></div>'+button('Check my flowchart','check')+(s.checks[c.id]?'<section class="feedback '+(ok?'correct':'review')+'"><h3>'+(ok?'✓ The flow follows the triangle plan.':'↻ Compare with the triangle plan.')+'</h3><p>Move forward 100 → turn right 120 → add one to the side count. No returns to drawing the next side; Yes ends after three sides.</p></section>':'')+'</section>';}
 function errorCards(c){const examples=[['syntax','A · Python cannot read this heading','for i in range(4)\n    t.forward(120)','The colon is missing from the for heading.'],['runtime','B · An instruction fails when it runs','t.forwad(120)','forwad is misspelled. Turtle has forward, so that method call fails when reached.'],['logic','C · Runs, but gives three sides','for i in range(3):\n    t.forward(120)\n    t.right(90)','It executes, but three repeats do not make a four-sided border.']];return examples.map(([id,title,example,why])=>'<section class="task question" data-field="'+id+'"><h2>'+title+'</h2>'+code(example)+'<label for="error-'+id+'">Choose the error type</label><select id="error-'+id+'" data-select="'+id+'"><option value="">Choose…</option>'+['Syntax error','Runtime error','Logic error'].map(v=>'<option '+(s.answers[c.id]?.[id]===v?'selected':'')+'>'+v+'</option>').join('')+'</select>'+(s.checks[c.id]?'<div class="feedback"><p>'+id.charAt(0).toUpperCase()+id.slice(1)+' error: '+why+'</p></div>':'')+'</section>').join('')+button('Check the explanations','check');}
 function latest(c){return s.runs[c.id]?.at(-1);}
 function ensureCode(c){if(!Object.hasOwn(s.codes,c.id))s.codes[c.id]=c.carry?(s.codes[c.carry]||c.initial):c.initial;return s.codes[c.id];}
 function editor(c){const value=ensureCode(c),r=latest(c),running=activeRun?.cardId===c.id,predictions=(c.questions||[]).filter(q=>!q.selfAssess);return '<section class="task editor-task"><div class="editor-grid"><section class="code-box">'+'<div class="code-heading"><label for="python">Your Python · edit here</label>'+button('▶ Run','run','primary')+button('Stop','stop','quiet')+'</div><div class="colour-launch"><span class="rainbow-dot" aria-hidden="true"></span>'+button('Colour studio · make it yours','colours','quiet')+'<span>Choose a colour or rainbow.</span></div>'+(predictions.length?'<div class="prediction-box">'+predictions.map(q=>predictionChoice(c,q)).join('')+'</div>':'')+'<div class="code-input"><div id="line-numbers" class="line-numbers" aria-hidden="true">'+value.split('\n').map((_,i)=>i+1).join('\n')+'</div><textarea id="python" class="python" spellcheck="false" autocapitalize="off" autocorrect="off" translate="no" aria-describedby="run-hint">'+e(value)+'</textarea></div><div class="code-tools"><p id="run-hint" class="small"><strong>Next:</strong> change the value or indentation named in your goal, then tap <strong>Run</strong> above the code.</p><details><summary>Typing buttons and file tools</summary><div class="tokens"><button data-insert="    ">4 spaces</button><button data-insert="for i in range():">for loop</button><button data-insert="t.forward()">forward</button><button data-insert="t.right()">right</button><button data-insert="t.left()">left</button><button data-insert="\n">New line</button></div><div class="tools">'+button('Reset starter','reset-code')+button('Download .py','python-download')+button('Open .py','python-upload')+'</div><label for="speed" class="small">Drawing speed</label><select id="speed"><option value="normal" '+(s.speed==='normal'?'selected':'')+'>Watch drawing</option><option value="slow" '+(s.speed==='slow'?'selected':'')+'>Slow</option><option value="instant" '+(s.speed==='instant'?'selected':'')+'>Instant</option></select><p class="small">Tab inserts four spaces. Return after a colon indents the next line. Ctrl/⌘ + Enter runs.</p></details></div></section><section class="drawing"><div class="output-comparison">'+targetPanel(c)+'<figure class="actual-output"><figcaption><strong>Your output · compare here</strong></figcaption><canvas id="turtle" width="800" height="600" role="img" aria-label="Your actual Python Turtle output"></canvas></figure></div><p class="console '+(r&&!r.ok?'error':'')+'" id="run-message" role="status">'+e(running?'Python is running…':r?friendlyError(r):'Ready. Tap Run to see your output.')+'</p>'+(r?.output?'<pre class="program-output">'+e(r.output)+'</pre>':'')+(r?'<p class="drawing-summary">'+e(summary(r))+'</p>':'')+(c.hint?'<details class="hint" data-hint="'+c.id+'"><summary>Show exactly what to change</summary><p>'+e(c.hint)+'</p>'+zh(c.hintZH)+'</details>':'')+button('↑ Back to code','code-view','quiet code-view')+resultQuestions(c)+'</section></div></section>';}
 function predictionChoice(c,q){const value=s.answers[c.id]?.[q.id],mark=s.checks[c.id]&&P.filled(value)?(+value===q.answer?'answer-correct':'answer-incorrect'):'';return '<section class="prediction-input '+mark+'" data-field="'+q.id+'"><label for="prediction-'+q.id+'"><strong>Before Run:</strong> '+e(q.label)+'</label>'+zh(q.zh)+'<select id="prediction-'+q.id+'" data-answer="'+q.id+'"><option value="">Choose your prediction…</option>'+q.options.map((v,i)=>'<option value="'+i+'" '+(String(value)===String(i)?'selected':'')+'>'+e(v)+'</option>').join('')+'</select></section>';}
 function resultQuestions(c){const r=latest(c),qs=(c.questions||[]).filter(q=>q.selfAssess);return r?'<section id="observations"><h2>Compare with your target</h2><p class="small">Your code and output were saved automatically. A run finishing does not tell you whether the drawing is right.</p>'+qs.map(q=>choice(c,q)).join('')+button('Save observation / check answer','check')+feedback(c)+(c.text?textField(c,c.text):'')+'</section>':'<p class="read-status">After Run, choose how your drawing compares. If Python fails, the error is saved as an attempt. You can revisit another stage and return here.</p>';}
 function summary(r){if(card()?.id==='extra-rainbow')return 'Compare the number of arcs and where they finish. Python draws each arc as many small line segments.';if(card()?.id==='extra-sparkle')return 'One ray uses forward and backward. Compare the number of rays with your target; each repeat returns to the centre.';const lines=r.draws.filter(d=>d.pen&&d.from&&d.to&&Math.hypot(d.to[0]-d.from[0],d.to[1]-d.from[1])>.01);return lines.length+' drawn movements. Compare the shape and repeat count with the target. Some designs intentionally cross or retrace lines.';}
 function friendlyError(r){if(r.ok)return 'Run finished. Now compare the drawing with your goal.';const err=r.error||'The run did not finish.';if(/too long|time/i.test(err))return err+' Use a small repeat count. If it is a device problem, tell your teacher and use another stage while it is checked.';if(/SyntaxError|bad token/i.test(err))return err+' Check the colon after the for heading, brackets and normal keyboard punctuation.';if(/IndentationError/i.test(err))return err+' Keep four spaces before each command inside the loop.';if(/AttributeError/i.test(err))return err+' Check the spelling: t.forward, t.right or t.left.';return err+' Your attempt is saved. Use the change hint or ask your teacher.';}

 function focusField(id){document.querySelectorAll('.needs-attention').forEach(x=>x.classList.remove('needs-attention'));let box=id==='run'?$('[data-action="run"]'):document.querySelector('[data-field="'+CSS.escape(id)+'"]');if(!box)box=$('#card-title');if(!box)return;box.classList.add('needs-attention');const control=box.matches('button,input,select,textarea')?box:box.querySelector('input,select,textarea,button,summary');if(control)control.focus({preventScroll:true});box.scrollIntoView({block:'center',behavior:'smooth'});}
 function showRequirements(c){let box=$('#requirements');if(!box){box=document.createElement('section');box.id='requirements';box.className='requirements';$('.bottom-nav')?.before(box);}const r=P.requirements(s,c);box.innerHTML='<strong>Before you continue</strong><ul>'+r.map(x=>'<li>'+(x.done?'<span class="status-mark">✓</span>'+e(x.label):'<button data-focus="'+x.id+'">'+e(x.label)+' →</button>')+'</li>').join('')+'</ul><p class="small">Only an attempt is required, not a particular correct answer or exact code. Use the stage bar to work elsewhere and return.</p>';box.querySelectorAll('[data-focus]').forEach(b=>b.onclick=()=>{if(c.kind==='exit'){const i=c.questions.findIndex(q=>q.id===b.dataset.focus);if(i>=0&&i!==exitIndex){exitIndex=i;render();}}focusField(b.dataset.focus);});}
 function finishBody(){
  const pending=P.required().filter(c=>!P.complete(s,c)),submitted=StudentWorkCloud.submitted(s),connected=StudentWorkCloud.validCloud(s.cloud);
  return '<section class="reading"><span class="reading-tag">YOUR EVIDENCE</span><p>Answers, code and drawings are captured for you. '+(connected?'Class saving runs in the background. Check the save message at the top.':'This is a device-only session. Open your teacher’s class link for online saving.')+' '+(pending.length?'Some activities need an attempt. Revisit them below, or submit a clearly labelled partial lesson.':'Your core activities have recorded attempts.')+'</p></section><section class="task"><h2>'+pending.length+' activities still to complete</h2>'+(pending.length?'<div class="unfinished-list">'+pending.map(c=>'<button data-go="'+c.id+'">'+e(c.title)+' →</button>').join('')+'</div>':'<p>Review your drawings and explanations. Recorded does not mean automatically graded.</p>')+'<div class="tools">'+button('Review my evidence','review')+button('Download private backup JSON','json')+'</div></section><section class="task"><h2 id="finish-status-title">'+finishStatus().title+'</h2><p id="finish-status-message">'+finishStatus().message+'</p><div class="tools">'+button(s.finished?'Save latest work to teacher':'Finish and save','finish','primary')+button('Create PDF backup','pdf')+'</div><div id="pdf-tools"></div></section><details class="task"><summary><strong>PDF backup and Microsoft Teams — only if requested</strong></summary><ol><li>Create and save your PDF. On iPad, use <strong>Share / Save to Files</strong> if a preview opens.</li><li>Check your name, class, answers and drawing evidence.</li><li>If requested: open <strong>Week 7 Theory</strong> in Teams → Add work → Upload PDF → Turn in.</li></ol><p class="small">Do not upload your private JSON recovery file to a public place. It contains the key for your saved work.</p></details><section class="task"><h2>After finishing · 15-question practice</h2><p>Practice here saves your answers. For a class game, ask your teacher which platform to use and for the code.</p><div class="tools">'+button('Practice here →','quiz','primary')+'<a class="button" href="https://www.gimkit.com/join" target="_blank" rel="noopener noreferrer" data-external="gimkit">Gimkit ↗</a><a class="button" href="https://play.blooket.com/play" target="_blank" rel="noopener noreferrer" data-external="blooket">Blooket ↗</a></div></section><div id="evidence-preview" class="report"></div>';
 }
 function quizBody(){if(!s.quiz.active)return '<section class="reading"><p>Play the same 15 topic questions in a shuffled order. Read the explanation after checking. You can revise an answer, then move on. Every completed round is recorded.</p>'+zh('15 道题会打乱顺序。检查后读解释，可以修改答案。每轮记录都会保存。')+'</section><section class="task"><h2>Your practice rounds</h2><p>'+s.quiz.attempts.length+' completed rounds.</p>'+button('Start a new round','quiz-start','primary')+'</section>';
  const a=s.quiz.active;quizIndex=Math.min(a.index||0,a.order.length-1);const q=L.quiz.find(x=>x.id===a.order[quizIndex]),r=a.responses[q.id],options=a.options[q.id];return '<p class="small">Question '+(quizIndex+1)+' of 15 · Round '+(s.quiz.attempts.length+1)+'</p><fieldset class="task question"><legend>'+e(q.label)+'</legend>'+options.map((original,i)=>'<label class="option '+(r?.checked&&r.latest===original?(original===q.answer?'answer-correct':'answer-incorrect'):'')+'"><input type="radio" name="quiz-answer" data-quiz="'+original+'" '+(r?.latest===original?'checked':'')+'><span>'+e(q.options[original])+'</span></label>').join('')+'</fieldset>'+button('Check this answer','quiz-check','primary')+(r?.checked?'<section class="feedback '+(r.latest===q.answer?'correct':'review')+'"><h3>'+(r.latest===q.answer?'Your answer matches.':'Use this explanation to improve.')+'</h3><p>'+e(q.why)+'</p><p class="small">Your first answer is preserved. You can change your choice.</p></section>':'')+'<div class="quiz-nav">'+button(quizIndex?'Previous question':'Pause round','quiz-back')+button(quizIndex===14?'Finish this round':'Next question →','quiz-next')+'</div>';}
 function shuffled(arr){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
 function stopRun(){if(activeRun){const job=activeRun;terminate();storeRun(job,{ok:false,error:'Run stopped by the learner. Try a smaller repeat count or ask for help.',draws:[]});}else terminate();if(playback){playback.cancel();playback=null;}}
 function terminate(){worker?.terminate();worker=null;clearTimeout(watchdog);watchdog=null;if(workerURL)URL.revokeObjectURL(workerURL);workerURL=null;activeRun=null;}
 function storeRun(job,result){reopenDraft();const list=s.runs[job.cardId]??=[],def=allCards.find(c=>c.id===job.cardId);list.push({id:uuid(),at:new Date().toISOString(),code:job.code,ok:!!result.ok,error:String(result.error||''),output:String(result.output||''),draws:Array.isArray(result.draws)?result.draws:[],view:def?.camera,durationMs:Date.now()-job.started});if(list.length>4)list.splice(1,list.length-4);record('python-run',job.cardId,{ok:!!result.ok});save();}
 function run(){const c=card();if(c.kind!=='editor')return;stopRun();const source=$('#python').value;s.codes[c.id]=source;if(!source.trim()){banner='The code box is empty. Add an instruction or use Reset this editor to restore the starter. You can use another stage and return to this practice.';render();focusField('run');return;}const job={cardId:c.id,code:source,started:Date.now()};activeRun=job;let ended=false;
  const finish=result=>{if(ended||activeRun!==job)return;ended=true;terminate();storeRun(job,result);banner='';render();const r=latest(c);if(r.ok&&r.draws.length&&s.speed!=='instant'&&!matchMedia('(prefers-reduced-motion: reduce)').matches)playback=TurtlePlayback.start(r.draws,{speed:()=>s.speed,paint:draws=>{if(s.current===c.id){ConsolidationReport.paint($('#turtle'),draws,c.camera);const msg=$('#run-message');if(msg)msg.textContent='Drawing slowly… watch the lines appear, then compare with the target.';}},done:()=>{playback=null;const stop=$('[data-action="stop"]');if(stop)stop.disabled=true;const msg=$('#run-message');if(msg&&s.current===c.id)msg.textContent='Drawing finished. Now compare your output with the target.';}});if(playback){const stop=$('[data-action="stop"]');if(stop)stop.disabled=false;}if(innerWidth<768)$('.drawing')?.scrollIntoView({block:'start',behavior:'smooth'});};
  try{workerURL=URL.createObjectURL(new Blob([PYTHON_RUNNER_SOURCE],{type:'text/javascript'}));worker=new Worker(workerURL);worker.onmessage=ev=>{if(ev.data.type==='ready'){clearTimeout(watchdog);watchdog=setTimeout(()=>finish({ok:false,error:'This run took too long. Use a small repeat count and try again.'}),8000);worker.postMessage({type:'run',code:source});}else if(ev.data.type==='result')finish(ev.data);};worker.onerror=()=>finish({ok:false,error:'Python could not start on this device. Your code is saved. Tell your teacher; you can use the stage bar and return.'});watchdog=setTimeout(()=>finish({ok:false,error:'Python did not load. Your code is saved. Refresh once or tell your teacher; the other stages remain available.'}),15000);render();}catch(err){finish({ok:false,error:err.message});}
 }
 function paintEditor(c){const r=latest(c);ConsolidationReport.paint($('#turtle'),playback?.current()||r?.draws||[],c.camera);if(playback&&$('#run-message'))$('#run-message').textContent='Drawing slowly… watch the lines appear, then compare with the target.';const runButton=$('[data-action="run"]'),stopButton=$('[data-action="stop"]');if(runButton)runButton.disabled=!!activeRun;const studio=$('[data-action="colours"]');if(studio)studio.disabled=!!activeRun;if(stopButton)stopButton.disabled=!activeRun&&!playback;}
 function insert(text){const py=$('#python');if(!py||py.readOnly)return;py.setRangeText(text,py.selectionStart,py.selectionEnd,'end');py.dispatchEvent(new Event('input'));py.focus();}
 function bindActions(){document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));}
 function bind(){bindActions();document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>navigate(b.dataset.go));document.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>{const sec=L.sections.find(x=>x.id===b.dataset.section);navigate(sec.cards[0]);});document.querySelectorAll('[data-exit]').forEach(b=>b.onclick=()=>{exitIndex=+b.dataset.exit;banner='';missingShown=false;render();});const c=card();if(c){document.querySelectorAll('[data-answer]').forEach(el=>el.onchange=()=>answer(c,el.dataset.answer,el.value===''?'':+el.value));document.querySelectorAll('[data-string]').forEach(el=>el.onchange=()=>answer(c,el.dataset.string,el.value));document.querySelectorAll('[data-text]').forEach(el=>el.oninput=()=>{const a=s.answers[c.id]??={};a[el.dataset.text]=el.value;reopenDraft();save();if(missingShown)showRequirements(c);});document.querySelectorAll('[data-select]').forEach(el=>el.onchange=()=>answer(c,el.dataset.select,el.value));document.querySelectorAll('[data-multi]').forEach(el=>el.onchange=()=>{const values=[...document.querySelectorAll('[data-multi]:checked')].map(x=>+x.dataset.multi);answer(c,'sections',values);});document.querySelectorAll('[data-shift]').forEach(b=>b.onclick=()=>{const [i,d]=b.dataset.shift.split(',').map(Number),arr=s.orders[c.id];[arr[i],arr[i+d]]=[arr[i+d],arr[i]];s.checks[c.id]=false;reopenDraft();record('parsons-move',c.id);save();render();});document.querySelectorAll('[data-hint]').forEach(d=>d.ontoggle=()=>{if(d.open){s.hints[c.id]=(s.hints[c.id]||0)+1;record('hint-open',c.id);save();}});const py=$('#python');if(py&&!py.readOnly){py.oninput=()=>{s.codes[c.id]=py.value;reopenDraft();$('#line-numbers').textContent=py.value.split('\n').map((_,i)=>i+1).join('\n');save();};py.onscroll=()=>{$('#line-numbers').scrollTop=py.scrollTop;};py.onkeydown=ev=>{if(ev.key==='Tab'){ev.preventDefault();insert('    ');}if(ev.key==='Enter'&&(ev.ctrlKey||ev.metaKey)){ev.preventDefault();run();}else if(ev.key==='Enter'){ev.preventDefault();const previous=py.value.slice(0,py.selectionStart).split('\n').at(-1),spaces=(previous.match(/^ */)||[''])[0]+(previous.trimEnd().endsWith(':')?'    ':'');insert('\n'+spaces);}};}document.querySelectorAll('[data-insert]').forEach(b=>b.onclick=()=>insert(b.dataset.insert));if($('#speed'))$('#speed').onchange=()=>{s.speed=$('#speed').value;save();};if($('#teams-confirm'))$('#teams-confirm').onchange=ev=>{s.teamsConfirmed=ev.target.checked;record('teams-self-report','finish',{value:ev.target.checked});save();};}
  document.querySelectorAll('[data-quiz]').forEach(el=>el.onchange=()=>{const a=s.quiz.active,qid=a.order[a.index];const r=a.responses[qid]??={first:+el.dataset.quiz,latest:+el.dataset.quiz,history:[],checked:false};r.latest=+el.dataset.quiz;r.history.push(r.latest);if(r.history.length>12)r.history.splice(1,1);r.checked=false;a.responses[qid]=r;record('quiz-answer','quiz',{questionId:qid});save();render();});document.querySelectorAll('[data-external]').forEach(a=>a.onclick=()=>{record('external-game-open','finish',{platform:a.dataset.external});save();});
 }
 function dialog(title,html){const d=document.createElement('dialog');d.className='dialog';d.innerHTML='<div class="dialog-head"><h2>'+e(title)+'</h2><button data-close aria-label="Close dialog">Close</button></div>'+html;document.body.append(d);d.showModal();d.querySelector('[data-close]').onclick=()=>{d.close();d.remove();};d.oncancel=()=>d.remove();return d;}
 function progress(){const d=dialog('Your saved work','<p>Your answers save on this device and, with a current class link, to your class. Keep a private JSON backup when changing devices.</p><div class="tools"><button id="draft-json">Download backup JSON</button><button id="draft-pdf">Create PDF</button><button id="change-learner">Change learner</button><button id="reset-lesson">Reset my lesson</button><button id="leave-device">Leave a shared device safely</button></div>');d.querySelector('#draft-json').onclick=()=>downloadJSON();d.querySelector('#draft-pdf').onclick=()=>{d.close();d.remove();pdfBackup();};d.querySelector('#change-learner').onclick=()=>{d.close();d.remove();changeLearner();};d.querySelector('#reset-lesson').onclick=()=>{if(!confirm('Reset your current lesson answers on this device and on the next class save? Download a JSON backup first to keep them.'))return;stopRun();const source=s,cloud=s.cloud,id=s.student.id;StudentWorkCloud.detach();s=newState(source.student.name,source.student.class,source.language,source.device);s.student.id=id;s.cloud=cloud;if(cloud){cloud.pendingWrite=null;cloud.dirty=true;}register();save();connectCloud();d.close();d.remove();banner='Your lesson was reset. Other saved learners are unchanged.';render();window.scrollTo(0,0);};d.querySelector('#leave-device').onclick=()=>{d.close();d.remove();leaveDevice();};}
 function deviceHelp(){const d=dialog('Device help','<p><strong>Run:</strong> use the green Run button above the code. Compare your drawing with the target next to it.</p><p><strong>iPad typing:</strong> tap the code and use the 4 spaces button under Typing buttons. Use normal keyboard punctuation.</p><p><strong>Saving:</strong> With a class link, wait for Saved to class. Download backup saves a private JSON recovery file; do not share it. Each browser keeps its own device copy.</p><p><strong>PDF:</strong> Safari may preview it. Use Share → Save to Files. A website cannot choose your iPad folder.</p><p>If Python cannot run, tell your teacher. The rest of the lesson remains available in the stage bar; no help form is required.</p><label for="device-choice">Your device</label><select id="device-choice"><option value="computer">Laptop / computer</option><option value="tablet">iPad / tablet</option></select>');d.querySelector('#device-choice').value=s.device;d.querySelector('#device-choice').onchange=ev=>{s.device=ev.target.value;save();};}
 function colourStudio(){
  const c=card(),C=TurtleColourStudio,selection={...(s.drawingStyles[c.id]||s.drawingStyleDefault||{mode:'solid',colour:'#6252c9'})};
  const d=dialog('Colour studio · make it yours','<p>Choose colours for your drawing. <strong>The shape is still your goal.</strong> Colour does not affect completion.</p>'+zh('选择你喜欢的线条颜色。目标图形不变，颜色不会影响进度。')+'<div class="studio-swatches" role="group" aria-label="Line colours">'+C.palette.map(([name,hex])=>'<button type="button" data-studio-colour="'+hex+'" style="--swatch:'+hex+'" aria-pressed="false"><span aria-hidden="true"></span>'+name+'</button>').join('')+'</div><label class="custom-colour" for="studio-custom">Or choose your own colour <input type="color" id="studio-custom" value="'+e(selection.colour||'#6252c9')+'"></label><button type="button" class="rainbow-choice" id="studio-rainbow" aria-pressed="false"><span class="rainbow-dot" aria-hidden="true"></span>Rainbow · a new colour each repeat</button><section class="studio-summary"><strong id="studio-summary-title"></strong><p id="studio-summary-text"></p></section><p class="small">The tool adds real Python colour instructions. You can inspect them in the editor. The rainbow colour line is prepared for you; lists are not assessed today.</p><p id="studio-error" class="notice" role="alert" hidden></p><button id="studio-apply" class="primary">Apply colour to my code →</button>');
  const update=()=>{d.querySelectorAll('[data-studio-colour]').forEach(b=>b.setAttribute('aria-pressed',String(selection.mode==='solid'&&selection.colour===b.dataset.studioColour)));d.querySelector('#studio-rainbow').setAttribute('aria-pressed',String(selection.mode==='rainbow'));d.querySelector('#studio-summary-title').textContent=selection.mode==='rainbow'?'Rainbow colours':'One line colour';d.querySelector('#studio-summary-text').textContent=selection.mode==='rainbow'?'Each loop repeat uses the next colour. Your moves and turns stay the same.':'Python will start with t.pencolor("'+selection.colour+'"). Choose a colour you can see on white.';d.querySelector('#studio-error').hidden=true;};
  d.querySelectorAll('[data-studio-colour]').forEach(b=>b.onclick=()=>{selection.mode='solid';selection.colour=b.dataset.studioColour;d.querySelector('#studio-custom').value=selection.colour;update();});d.querySelector('#studio-custom').oninput=ev=>{selection.mode='solid';selection.colour=ev.target.value;update();};d.querySelector('#studio-rainbow').onclick=()=>{selection.mode='rainbow';update();};
  d.querySelector('#studio-apply').onclick=()=>{const result=C.apply(ensureCode(c),selection);if(!result.ok){const err=d.querySelector('#studio-error');err.textContent=result.message;err.hidden=false;return;}stopRun();s.codes[c.id]=result.code;reopenDraft();s.drawingStyles[c.id]={...selection};s.drawingStyleDefault={...selection};record('drawing-style',c.id,{mode:selection.mode,colour:selection.mode==='solid'?selection.colour:null});save();d.close();d.remove();banner=result.message;render();const runButton=$('[data-action="run"]');runButton?.focus({preventScroll:true});runButton?.scrollIntoView({block:'center',behavior:'smooth'});};update();
 }
 function reviewTeacher(){window.open('teacher.html','_blank','noopener,noreferrer');}
 function resume(){dialog('Continue your work','<p>On your own device, enter the same full name and class to reopen its saved copy. Refreshing does not lose saved work.</p><p>On a different device, use <strong>Restore JSON backup</strong> with your private recovery file. A name alone cannot unlock cloud work.</p><p>On a shared device, use <strong>Leave a shared device safely</strong> in your learner settings before handing it to someone else.</p>');}
 function changeLearner(){stopRun();save();StudentWorkCloud.detach();banner='';landing();}
 function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
 function filename(suffix){const clean=v=>String(v).replace(/[^\p{L}\p{N}_-]/gu,'_').slice(0,45);return 'Year7_'+clean(s.student.class||'Preview')+'_'+clean(s.student.name)+'_Week7_'+suffix;}
 function downloadJSON(){save();download(new Blob([JSON.stringify({format:'y7-consolidation-backup',version:1,state:s},null,2)],{type:'application/json'}),filename('Private_Backup.json'));s.backupDownloadedAt=new Date().toISOString();persistOnly();}
 function chooseFile(accept,handler){const input=document.createElement('input');input.type='file';input.accept=accept;input.onchange=()=>input.files[0]&&handler(input.files[0]);input.click();}
 async function restore(file){try{if(file.size>3000000)throw Error('Choose a lesson JSON backup smaller than 3 MB.');const b=JSON.parse(await file.text());if(b.format!=='y7-consolidation-backup')throw Error('Choose this lesson’s JSON backup.');const restored=normalise(b.state);if(s&&!confirm('Open the backup? Your current work stays saved separately.'))return;stopRun();save();s=restored;register();record('backup-restored');save();banner='Private backup restored. Check that the displayed name and class are yours.';render();connectCloud();}catch(err){if($('#entry-error'))$('#entry-error').textContent=err.message;else{banner=err.message;render();}}}
 async function pdfBackup(){stopRun();save();try{pdf=ConsolidationReport.pdf(s);record('pdf-backup');save();const host=$('#pdf-tools');const html='<section class="feedback"><h3>PDF backup ready</h3><p>Save it, check your name and class, then upload only if your teacher requests it.</p><div class="tools">'+button('Download PDF','pdf-download')+button('Share / Save to Files','pdf-share')+button('Print / Save as PDF','print')+'</div></section>';if(host){host.innerHTML=html;bindActions();host.scrollIntoView({block:'nearest'});}else{const d=dialog('PDF backup ready',html);d.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));}}catch(err){banner='PDF export did not finish. Your work is still saved. Use the print fallback or JSON backup.';render();const d=dialog('Backup choices',button('Print / Save as PDF','print')+button('Download JSON','json'));d.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));}}
 async function action(a){const c=card();switch(a){
  case 'sync':await StudentWorkCloud.flush();render();break;case 'cloud-conflict':cloudConflict();break;case 'next':next();break;case 'back':back();break;case 'profile':progress();break;case 'language':s.language=s.language==='zh'?'en':'zh';record('language-changed');save();render();break;case 'device':deviceHelp();break;case 'resume':resume();break;case 'teacher-review':reviewTeacher();break;case 'restore':chooseFile('.json',restore);break;
  case 'check':{const needed=P.requirements(s,c).filter(r=>r.id!=='run'&&r.id!=='order'&&!r.done&&(c.kind!=='exit'||r.id===c.questions[exitIndex].id));if(c.kind==='multi'&&(s.answers[c.id]?.sections?.length||0)>0)needed.splice(0,needed.length);if(needed.length){banner='Choose a response first. A guess is useful: '+needed[0].label;missingShown=true;render();focusField(needed[0].id);break;}s.checks[c.id]=true;record('feedback-open',c.id);save();banner='';render();break;}
  case 'colours':colourStudio();break;case 'code-view':$('#python')?.scrollIntoView({block:'center',behavior:'smooth'});break;case 'run':run();break;case 'stop':stopRun();render();break;
  case 'reset-code':if(confirm('Restore this starter? Your earlier code/output runs stay in the evidence.')){stopRun();s.codes[c.id]=c.initial;reopenDraft();record('code-reset',c.id);save();render();}break;
  case 'python-download':download(new Blob([ensureCode(c)+'\n'],{type:'text/x-python'}),filename(c.id+'.py'));record('python-download',c.id);save();break;
  case 'python-upload':chooseFile('.py',async f=>{if(f.size>50000){banner='Choose a Python file smaller than 50 KB.';render();return;}s.codes[c.id]=await f.text();reopenDraft();record('python-open',c.id);save();render();});break;
  case 'finish':stopRun();s.finished=true;s.finishedAt=new Date().toISOString();s.completed.finish={at:s.finishedAt,kind:'finish'};record('lesson-finished','finish');const ok=save();render();await StudentWorkCloud.flush();banner=StudentWorkCloud.submitted(s)?'Submitted to your teacher. Your revision practice is ready.':ok?'Finished on this device. If class saving is waiting, keep this page open or download a private backup. You can still practise.':'Device storage is unavailable. Download your private backup now.';render();break;
  case 'review':$('#evidence-preview').innerHTML=ConsolidationReport.html(s);$('#evidence-preview').scrollIntoView({block:'start'});record('evidence-review','finish');save();break;
  case 'json':downloadJSON();break;case 'pdf':await pdfBackup();break;case 'pdf-download':if(pdf)download(pdf,filename('Evidence.pdf'));break;
  case 'pdf-share':if(pdf){try{const file=new File([pdf],filename('Evidence.pdf'),{type:'application/pdf'});if(navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:'Year 7 lesson evidence'});else download(pdf,file.name);}catch{banner='Sharing closed. Your PDF backup is still available.';}}break;
  case 'print':document.querySelector('.print-report')?.remove();{const div=document.createElement('div');div.className='print-report';div.innerHTML=ConsolidationReport.html(s);document.body.append(div);window.print();}break;
  case 'final-python':{const source=s.codes['zigzag-build']||s.codes['hexagon-build']||s.codes['triangle-build'];if(!source){banner='No drawing draft yet. Revisit a coding card or download your JSON backup.';render();break;}download(new Blob([source+'\n'],{type:'text/x-python'}),filename('Drawing.py'));}break;
  case 'quiz':if(!s.finished&&!s.teacher){banner='Finish and save your lesson first, then start revision practice.';render();}else navigate('quiz');break;
  case 'quiz-start':{const order=shuffled(L.quiz.map(q=>q.id)),options={};for(const q of L.quiz)options[q.id]=shuffled(q.options.map((_,i)=>i));s.quiz.active={id:uuid(),startedAt:new Date().toISOString(),index:0,order,options,responses:{}};record('quiz-start','quiz');save();render();}break;
  case 'quiz-check':{const qa=s.quiz.active,qid=qa.order[qa.index],r=qa.responses[qid];if(!r){banner='Choose an answer first. You can change it after feedback.';render();break;}r.checked=true;record('quiz-check','quiz',{questionId:qid});save();banner='';render();}break;
  case 'quiz-next':{const qa=s.quiz.active,qid=qa.order[qa.index];if(!qa.responses[qid]?.checked){banner='Choose an answer and tap Check this answer before moving on.';render();break;}if(qa.index===14){qa.finishedAt=new Date().toISOString();qa.firstScore=L.quiz.filter(q=>qa.responses[q.id]?.first===q.answer).length;qa.latestScore=L.quiz.filter(q=>qa.responses[q.id]?.latest===q.answer).length;s.quiz.attempts.push(qa);if(s.quiz.attempts.length>6)s.quiz.attempts.splice(1,1);s.quiz.active=null;banner='Round saved: first answers '+qa.firstScore+'/15; latest answers '+qa.latestScore+'/15. Read explanations and try another round when ready.';}else qa.index++;save();render();}break;
  case 'quiz-back':if(s.quiz.active.index>0){s.quiz.active.index--;save();render();}else navigate('finish');break;
 }}
 function svg(inner,label,view='0 0 620 230'){return '<svg class="visual" viewBox="'+view+'" role="img" aria-label="'+e(label)+'" xmlns="http://www.w3.org/2000/svg">'+inner+'</svg>';}
 function gallery(){return '<div class="gallery-preview">'+[['triangle','Triangle badge'],['hexagon','Hexagon tile'],['zigzag','Zigzag divider']].map(([id,label])=>'<figure><img src="assets/targets/'+id+'.svg" alt="'+label+' target"><figcaption>'+label+'</figcaption></figure>').join('')+'</div>';}
 function visual(kind){if(kind==='gallery')return gallery();if(kind==='parts')return '<div class="card-grid">'+['Triangle badge','Hexagon tile','Zigzag divider'].map((t,i)=>'<section class="challenge-card"><h3>'+ (i+1)+' · '+t+'</h3><p>Plan, draw and test this part.</p></section>').join('')+'</div>';if(kind==='routes')return '<div class="route-choices">'+[['A','M30 20H110V60','110','60'],['B','M30 60H110V20','110','20'],['C','M30 20V100H70','70','100']].map(([label,path,x,y])=>'<figure><svg viewBox="0 0 145 115" role="img" aria-label="Route '+label+'"><path d="'+path+'" stroke="#176b45" stroke-width="5" fill="none"/><circle cx="30" cy="'+(label==='B'?'60':'20')+'" r="5" fill="#b77819"/><circle cx="'+x+'" cy="'+y+'" r="4" fill="#245f97"/></svg><figcaption>Route '+label+' · orange start</figcaption></figure>').join('')+'</div>';if(kind==='symbols')return '<div class="symbol-grid">'+[['Start / End','<ellipse cx="75" cy="36" rx="60" ry="25"/>'],['Action','<rect x="15" y="12" width="120" height="48" rx="3"/>'],['Question','<path d="M75 3L140 36L75 69L10 36Z"/>'],['Next step','<path d="M15 36H130M110 18L130 36L110 54"/>']].map(([label,shape])=>'<div><svg viewBox="0 0 150 75" aria-hidden="true"><g fill="white" stroke="#176b45" stroke-width="3">'+shape+'</g></svg><strong>'+label+'</strong></div>').join('')+'</div>';if(kind==='anatomy')return '<div class="anatomy">'+[['for','Start the loop'],['i','Counter name'],['in','Take each value'],['range(3)','Three repeats'],[':','Body comes next']].map(([term,meaning])=>'<div><code>'+term+'</code><span aria-hidden="true">↓</span><p>'+meaning+'</p></div>').join('')+'</div>'+code('for i in range(3):\n    t.forward(100)  # move: draw one side\n    t.right(120)    # turn: face the next side');if(kind==='debug-summary')return '<div class="card-grid">'+[['Syntax','Missing colon','for i in range(3)'],['Runtime','Method does not exist','t.forwad(100)'],['Logic','Only two triangle sides','for i in range(2):']].map(([name,meaning,example])=>'<section class="challenge-card"><h3>'+name+' error</h3><p>'+meaning+'</p>'+code(example)+'</section>').join('')+'</div>';return '';}
 function persistOnly(){if(!s)return false;try{localStorage.setItem(PREFIX+s.student.id,JSON.stringify(s));register();return true;}catch{return false;}}
 function connectCloud(){const source=s;StudentWorkCloud.attach(source,{persist:()=>source===s?persistOnly():false,status:(text,kind)=>{if(source!==s)return;status(text,kind);refreshFinishStatus();const old=$('#cloud-attention');if(old)old.remove();const html=cloudPanel();if(html){$('.card-header')?.insertAdjacentHTML('afterend',html);bindActions();}},remote:r=>{if(source!==s)return;const identity={...s.student,name:r.learner_name},cloud=s.cloud;const restored=normalise({...r.payload,student:identity,teacher:false,events:r.payload.events||[]});Object.assign(s,restored);s.cloud=cloud;persistOnly();render();}}).catch(()=>status('Saved on device · connection needs checking','error'));}
 function cloudPanel(){if(!s||s.teacher)return '';const x=StudentWorkCloud.status();if(x.kind!=='error'&&x.kind!=='conflict')return '';return '<section id="cloud-attention" class="cloud-attention" role="status"><strong>'+e(x.text)+'</strong><p>Your lesson cards remain available. Keep a private backup before changing devices.</p>'+button('Download backup','json')+(x.conflict?button('Choose which copy to keep','cloud-conflict'):button('Try saving again','sync'))+'</section>';}
 function cloudConflict(){const d=dialog('Two saved copies — keep your work','<p>A newer class save was found. Nothing has been overwritten. Download your device backup before choosing.</p><div class="tools"><button id="conflict-backup">Download device backup</button><button id="use-class">Use newer class copy</button><button id="use-device">Keep my device copy</button></div>');d.querySelector('#conflict-backup').onclick=downloadJSON;for(const [id,remote]of [['use-class',true],['use-device',false]])d.querySelector('#'+id).onclick=()=>{if(!confirm(remote?'Replace this device draft with the newer class copy? Keep a backup first.':'Replace the class copy with this device draft? Keep a backup first.'))return;StudentWorkCloud.resolve(remote);d.close();d.remove();render();};}
 function leaveDevice(){const d=dialog('Leave a shared device safely','<p>First download your private recovery file. Keep it in your own school storage, not on the shared device.</p><p>Then remove this device copy. Your class record stays in Supabase; the private file is needed to reopen it on another device. Never share it with classmates.</p><div class="tools"><button id="leave-backup">1. Download private backup</button><button id="leave-clear" disabled>2. Remove this device copy</button></div>');d.querySelector('#leave-backup').onclick=()=>{downloadJSON();d.querySelector('#leave-clear').disabled=false;};d.querySelector('#leave-clear').onclick=()=>{if(!confirm('Have you kept your private backup? Remove only your current lesson and save key from this device?'))return;stopRun();StudentWorkCloud.detach();localStorage.removeItem(PREFIX+s.student.id);localStorage.setItem(INDEX,JSON.stringify(profiles().filter(p=>p.id!==s.student.id)));localStorage.removeItem(PREFIX+'last');d.close();d.remove();landing();};}
 window.ConsolidationApp={exportRecord:()=>s?JSON.parse(JSON.stringify(s)):null};
 landing();
})();
