(() => {
'use strict';
const L=window.LESSON,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>globalThis.crypto?.randomUUID?.()||Date.now()+'-'+Math.random().toString(36).slice(2);
const key='y11-w3-protocols-merged-v1';let state,db,teacher=false,timer,queue=Promise.resolve(),uploadBusy=0,saved=true,noticeTimer;
const core=['starter','types','main1','main2','pitstop','plenary'];
const fresh=(name,cls)=>({version:1,lesson:key,id:JSON.stringify([name.toLowerCase(),cls.toLowerCase()]),name,cls,date:new Date().toLocaleDateString('en-GB'),updated:new Date().toISOString(),fields:{},cards:[],peers:[],photos:{},feedback:{},status:{},lastStage:'overview'});
function notice(t){$('#notice').textContent=t;$('#notice').hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('#notice').hidden=true,7000);}
const ready=new Promise(resolve=>{try{const r=indexedDB.open(key,1);r.onupgradeneeded=()=>r.result.createObjectStore('work',{keyPath:'id'});r.onsuccess=()=>{db=r.result;resolve();};r.onerror=r.onblocked=()=>resolve();}catch{resolve();}});
function get(id){return new Promise(resolve=>{if(!db){try{resolve(JSON.parse(localStorage.getItem(key+id)||'null'));}catch{resolve(null);}return;}try{const r=db.transaction('work').objectStore('work').get(id);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>resolve(null);}catch{resolve(null);}});}
function put(record){return new Promise((resolve,reject)=>{if(!db){try{localStorage.setItem(key+record.id,JSON.stringify(record));resolve();}catch(e){reject(e);}return;}try{const tx=db.transaction('work','readwrite');tx.objectStore('work').put(record);tx.oncomplete=()=>resolve();tx.onerror=tx.onabort=()=>reject(tx.error);}catch(e){reject(e);}});}
function save(){clearTimeout(timer);if(!state)return queue;statuses();state.updated=new Date().toISOString();const copy=JSON.parse(JSON.stringify(state));$('#saveStatus').textContent='Saving…';queue=queue.then(()=>put(copy)).then(()=>{saved=!!state&&JSON.stringify(state)===JSON.stringify(copy);$('#saveStatus').textContent=saved?'Saved on this device':'Unsaved changes';}).catch(()=>{saved=false;$('#saveStatus').textContent='Not saved — download a backup';notice('This browser could not save your latest work. Keep the page open and download your PDF and editable backup.');});return queue;}
function changed(){saved=false;$('#saveStatus').textContent='Unsaved changes';clearTimeout(timer);timer=setTimeout(save,450);if(state)statuses();}
function download(data,name,type){const u=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),15000);}
const safeName=v=>v.replace(/[^a-z0-9_-]/gi,'_').slice(0,60)||'Student';
function render(){
 $('#nav').innerHTML=L.stages.map(s=>`<button data-go="${s.id}"><span>${s.nav}</span><span class="dot" data-dot="${s.id}"></span></button>`).join('');
 $('#stages').innerHTML=L.stages.map((s,i)=>`<section class="stage" data-stage="${s.id}" hidden><header class="stage-heading"><p class="eyebrow">${String(i).padStart(2,'0')} · ${s.time}</p><span class="badge">${s.screen}</span><h1>${s.title}</h1></header>${s.html}${s.id==='report'?'':`<footer class="stage-footer">${core.includes(s.id)||s.optional?`<button data-done="${s.id}">Record this stage as attempted</button><span class="status" data-status="${s.id}"></span>`:''}<button class="primary next" data-go="${s.id==='main2'||s.id==='exam'?'pitstop':L.stages[i+1].id}">Continue →</button></footer>`}</section>`).join('');
}
function go(id,focus=true){if(!L.stages.some(s=>s.id===id))id='overview';$$('[data-stage]').forEach(x=>x.hidden=x.dataset.stage!==id);$$('nav [data-go]').forEach(x=>x.dataset.go===id?x.setAttribute('aria-current','step'):x.removeAttribute('aria-current'));state.lastStage=id;changed();if(id==='report')$('#reportSummary').innerHTML=`<div class="panel"><h2>Your record</h2><p>${esc(state.name)} · ${esc(state.cls)} · ${esc(state.date)}</p><p>${state.cards.length} on-screen card(s), ${state.peers.length} partner recall record(s), ${Object.values(state.photos).flat().length} photograph(s).</p><p>Check the evidence preview before exporting. A participation record is not a mastery score.</p></div>`;if(focus){$('#content').focus({preventScroll:true});window.scrollTo(0,0);}}
function hasWork(s){return L.fields.some(f=>f.stage===s&&String(state.fields[f.key]??'').trim())||(state.photos[s]||[]).length>0||(s==='main1'&&(state.cards.some(c=>c.prompt.trim()||c.purpose.trim())||state.peers.some(r=>r.first.trim()||r.retry.trim())));}
function statuses(){[...core,'exam'].forEach(s=>{$(`[data-dot="${s}"]`).textContent=state.status[s]||hasWork(s)?'✓':'';const x=$(`[data-status="${s}"]`);if(x)x.textContent=hasWork(s)?'Work recorded':state.status[s]?'Attempted':'Not recorded';});$('#progress').textContent=`${core.filter(s=>state.status[s]||hasWork(s)).length} of 6 core stages have work or an attempt recorded. This is not a grade.`;}
async function enter(name,cls){await ready;teacher=name.toLowerCase()==='teacher';if(teacher)cls='Review';state=await get(fresh(name,cls).id)||fresh(name,cls);$('#landing').hidden=true;$('#workspace').hidden=false;$('#identity').textContent=teacher?'Teacher review':state.name+' · '+state.cls;$('#teacherTools').hidden=!teacher;$$('[data-field]').forEach(el=>{const v=state.fields[el.dataset.field]??'';if(el.type==='radio')el.checked=el.value===v;else el.value=v;});cards();peers();L.stages.forEach(s=>{photos(s.id);feedbackLog(s.id);});pit();statuses();go(state.lastStage,false);await save();}
function cards(){ $('#cards').innerHTML=state.cards.map((c,i)=>`<article class="made-card"><header><h3>My card ${i+1}</h3><button data-remove-card="${c.id}">Remove</button></header><label for="card-${c.id}-protocol">Protocol</label><select id="card-${c.id}-protocol" data-card="${c.id}" data-prop="protocol"><option value="">Choose your allocated protocol</option>${L.protocols.map(p=>`<option ${c.protocol===p.id?'selected':''}>${p.id}</option>`).join('')}</select>${[['prompt','Front: my question or situation'],['purpose','Back: the purpose, explained clearly'],['follow','Follow-up question for my partner']].map(([k,label])=>`<label for="card-${c.id}-${k}">${label}</label><textarea id="card-${c.id}-${k}" data-card="${c.id}" data-prop="${k}" rows="2">${esc(c[k])}</textarea>`).join('')}<label for="card-${c.id}-layer">Back: the layer</label><select id="card-${c.id}-layer" data-card="${c.id}" data-prop="layer"><option value="">Choose after reading</option>${L.layers.map(l=>`<option ${c.layer===l[0]?'selected':''}>${l[0]}</option>`).join('')}</select><label class="checkline"><input type="checkbox" data-card="${c.id}" data-prop="checked" ${c.checked?'checked':''}>I checked the purpose and layer against the reading.</label><div class="actions"><button data-preview-card="${c.id}">Use this card to quiz a partner</button></div></article>`).join('')||'<p>You have not made an on-screen card yet. Choose “Add a protocol card”, or make a paper card and upload a photograph.</p>'; }
function previewCard(id){const c=state.cards.find(x=>x.id===id);if(!c)return;$('#reviewBody').innerHTML=`<h2>Ask your partner</h2><div class="card-face"><p>${esc(c.prompt||'Write your question first.')}</p></div><p>Give your partner thinking time. Ask them to explain the purpose and layer before revealing your answer.</p><button id="revealCard">Reveal my answer</button><div id="cardBack" hidden class="card-face"><h3>${esc(c.protocol||'Protocol not recorded')} · ${esc(c.layer||'Layer not recorded')}</h3><p>${esc(c.purpose||'Purpose not recorded')}</p><p><strong>Follow-up:</strong> ${esc(c.follow||'Not recorded')}</p><p class="small">${c.checked?'You recorded that you checked this against the reading.':'Check this card against the reading before using it with a partner.'}</p></div>`;$('#revealCard').onclick=()=>{$('#cardBack').hidden=false;$('#revealCard').disabled=true;};$('#reviewDialog').showModal();}
function peers(){ $('#peerRows').innerHTML=state.peers.map((r,i)=>`<article class="peer-row"><header><h3>Recall ${i+1}</h3><button data-remove-peer="${r.id}">Remove</button></header>${[['protocol','Protocol I was asked about'],['first','My first answer, without notes'],['correction','What I corrected after checking'],['retry','What I recalled when asked again later']].map(([k,label])=>`<label for="peer-${r.id}-${k}">${label}</label><textarea id="peer-${r.id}-${k}" data-peer="${r.id}" data-prop="${k}" rows="2">${esc(r[k])}</textarea>`).join('')}</article>`).join('')||'<p>No on-screen recall records yet. Record a few helpful exchanges here or on paper.</p>'; }
async function preparePhoto(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('Use JPG, PNG or WebP.');if(file.size>12*1024*1024)throw Error('This image exceeds 12 MB.');const url=URL.createObjectURL(file);try{const img=await new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(Error('This image could not be read.'));i.src=url;});const scale=Math.min(1,2000/Math.max(img.naturalWidth,img.naturalHeight)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.naturalWidth*scale));c.height=Math.max(1,Math.round(img.naturalHeight*scale));const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(img,0,0,c.width,c.height);return{id:uid(),name:file.name,data:c.toDataURL('image/jpeg',.92),caption:'',width:c.width,height:c.height};}finally{URL.revokeObjectURL(url);}}
async function addPhotos(input){const s=input.dataset.photos,owner=state,list=[...input.files],errors=[];owner.photos[s]??=[];if(owner.photos[s].length+list.length>6){notice('Keep up to six photographs per stage.');input.value='';return;}uploadBusy++;input.disabled=true;try{for(const file of list){try{owner.photos[s].push(await preparePhoto(file));}catch(e){errors.push(file.name+': '+e.message);}}if(state===owner){photos(s);await save();$(`[data-photo-error="${s}"]`).textContent=errors.join(' ');notice(errors.length?'Check the photograph message.':'Photographs added. Check your writing is readable.');}}finally{uploadBusy--;input.disabled=false;input.value='';}}
function photos(s){const el=$(`[data-photo-list="${s}"]`);if(el)el.innerHTML=(state.photos[s]||[]).map(p=>`<article class="photo"><a href="${p.data}" target="_blank" rel="noopener"><img src="${p.data}" alt="${esc(p.caption||p.name)}"></a><p class="small">${esc(p.name)}</p><label for="cap-${p.id}">What does this show?</label><textarea id="cap-${p.id}" data-caption="${p.id}" data-photo-stage="${s}" rows="2">${esc(p.caption)}</textarea><button data-remove-photo="${p.id}" data-photo-stage="${s}">Remove photo</button></article>`).join('');}
function pit(){ $('#pitAction').textContent=L.pitActions[state.fields.phase]||'Choose a phase to see a next step.'; }
function evidence(s,all=false){let html=L.fields.filter(f=>f.stage===s&&(all||String(state.fields[f.key]??'').trim())).map(f=>`<h3>${esc(f.label)}</h3><div class="answer">${esc(state.fields[f.key]??'Not recorded')||'Not recorded'}</div>`).join('');if(s==='main1'){state.cards.forEach((c,i)=>{html+=`<h3>Card ${i+1}: ${esc(c.protocol)}</h3><div class="answer">${esc(c.prompt)}\n${esc(c.purpose)}\nLayer: ${esc(c.layer)}\nFollow-up: ${esc(c.follow)}\nChecked against reading: ${c.checked?'Yes':'Not recorded'}</div>`;});state.peers.forEach((r,i)=>{html+=`<h3>Recall ${i+1}: ${esc(r.protocol)}</h3><div class="answer">First: ${esc(r.first)}\nCorrection: ${esc(r.correction)}\nRetry: ${esc(r.retry)}</div>`;});}html+=(state.photos[s]||[]).map(p=>`<figure><img src="${p.data}" alt="${esc(p.caption||p.name)}"><figcaption>${esc(p.caption||p.name)}</figcaption></figure>`).join('');return html||'<p>No evidence recorded yet.</p>';}
function showWork(s){$('#reviewBody').innerHTML=`<p>${esc(state.name)} · ${esc(state.cls)}</p><h2>${esc(L.stages.find(x=>x.id===s).title)}</h2>${evidence(s)}`;$('#reviewDialog').showModal();}
function feedbackLog(s){const el=$(`[data-feedback-log="${s}"]`);if(el)el.innerHTML=(state.feedback[s]||[]).map((x,i)=>`<div class="callout"><strong>Feedback ${i+1}</strong><p class="answer">${esc(x.note)}</p><strong>My improvement</strong><p class="answer">${esc(x.improvement)}</p></div>`).join('');}
function recordFeedback(s){const note=state.fields[s+'-feedback']||'',improvement=state.fields[s+'-improvement']||'';if(!note.trim()||!improvement.trim())return notice('Add both the feedback and your improved explanation first.');state.feedback[s]??=[];if(state.feedback[s].some(x=>x.note===note&&x.improvement===improvement))return notice('This feedback is already kept.');const original=Object.fromEntries(L.fields.filter(f=>f.stage===s&&!f.key.endsWith('feedback')&&!f.key.endsWith('improvement')).map(f=>[f.label,state.fields[f.key]||'']));state.feedback[s].push({at:new Date().toISOString(),note,improvement,original});feedbackLog(s);save();notice('Feedback, your original responses and your improvement have been kept.');}
async function pdf(cardsOnly=false){if(uploadBusy)return notice('Wait for your photographs to finish processing.');if(!window.jspdf||!window.REPORT)return notice('The PDF library did not load. Download the editable backup instead.');if(cardsOnly&&!state.cards.length)return notice('Make an on-screen card first. Photographs of paper cards are included in the evidence PDF.');try{await save();const doc=window.REPORT.build(state,L,cardsOnly);doc.save(`Week3_Protocols_${safeName(state.name)}_${cardsOnly?'Cards':'Evidence'}.pdf`);notice('PDF downloaded. Open it to check it, then submit your evidence PDF in Teams.');}catch(e){notice('The PDF could not be created. Download an editable backup and try again.');console.error(e);}}
async function backup(){if(uploadBusy)return notice('Wait for photographs to finish processing.');await save();download(JSON.stringify(state,null,2),`Week3_Protocols_${safeName(state.name)}_backup.json`,'application/json');}
function validate(v){if(!v||v.lesson!==key||v.version!==1||typeof v.name!=='string'||!v.name.trim()||typeof v.cls!=='string'||!v.cls.trim()||v.name.trim().toLowerCase()==='teacher')throw Error('Choose a student backup from this merged lesson.');const r=fresh(v.name.trim().slice(0,80),v.cls.trim().slice(0,30)),str=(x,n=60000)=>typeof x==='string'?x.slice(0,n):'';r.date=str(v.date,40)||r.date;for(const f of L.fields)r.fields[f.key]=str(v.fields?.[f.key]);for(const [k,props,max] of [['cards',['protocol','prompt','purpose','layer','follow'],20],['peers',['protocol','first','correction','retry'],40]]){if(v[k]&&!Array.isArray(v[k]))throw Error('Invalid record list.');r[k]=(v[k]||[]).slice(0,max).map(x=>({id:uid(),...Object.fromEntries(props.map(p=>[p,str(x[p])])),...(k==='cards'?{checked:x.checked===true}:{})}));}for(const s of L.stages){r.status[s.id]=v.status?.[s.id]===true;const a=v.photos?.[s.id]||[];if(!Array.isArray(a)||a.length>6)throw Error('Invalid photograph list.');r.photos[s.id]=a.map(p=>{if(typeof p.data!=='string'||!/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(p.data))throw Error('Invalid photograph.');return{id:uid(),data:p.data,name:str(p.name,200),caption:str(p.caption,5000),width:Number(p.width)||1,height:Number(p.height)||1};});const logs=v.feedback?.[s.id]||[];if(!Array.isArray(logs))throw Error('Invalid feedback list.');r.feedback[s.id]=logs.slice(0,50).map(x=>({at:str(x.at,80),note:str(x.note),improvement:str(x.improvement),original:Object.fromEntries(Object.entries(x.original||{}).filter(([k,v])=>typeof v==='string').map(([k,v])=>[k.slice(0,400),str(v)]))}));}return r;}
async function restore(input){const file=input.files[0];if(!file)return;if(uploadBusy){input.value='';return notice('Wait for photographs to finish processing.');}try{if(file.size>70*1024*1024)throw Error('This backup exceeds 70 MB.');const r=validate(JSON.parse(await file.text()));const old=await get(r.id);if(!confirm(`Open the backup for ${r.name}, ${r.cls}?${old?' This replaces their saved work on this device.':''}`))return;await save();if(!saved)throw Error('Download your current editable backup before replacing work.');await put(r);await enter(r.name,r.cls);go('report');notice('Backup restored.');}catch(e){$('#restoreError').textContent=e.message;}finally{input.value='';}}
render();
$('#entry').addEventListener('submit',async e=>{e.preventDefault();const n=$('#name').value.trim(),c=$('#className').value.trim();if(!n||(!c&&n.toLowerCase()!=='teacher')){$('#entryError').textContent='Please enter your name and class.';return;}$('#entryError').textContent='';const b=$('#entry button');b.disabled=true;try{await enter(n,c);}catch{notice('Your lesson could not open. Please try again.');}finally{b.disabled=false;}});
document.addEventListener('input',e=>{if(!state)return;const el=e.target;if(el.dataset.field){state.fields[el.dataset.field]=el.value;changed();if(el.dataset.field==='phase')pit();}if(el.dataset.card){const c=state.cards.find(x=>x.id===el.dataset.card);if(c){c[el.dataset.prop]=el.type==='checkbox'?el.checked:el.value;changed();}}if(el.dataset.peer){const r=state.peers.find(x=>x.id===el.dataset.peer);if(r){r[el.dataset.prop]=el.value;changed();}}if(el.dataset.caption){const p=state.photos[el.dataset.photoStage]?.find(x=>x.id===el.dataset.caption);if(p){p.caption=el.value;changed();}}});
document.addEventListener('change',e=>{if(e.target.dataset.photos)addPhotos(e.target);if(e.target.id==='restore')restore(e.target);});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||!state)return;if(b.dataset.go)go(b.dataset.go);if(b.dataset.done){state.status[b.dataset.done]=true;statuses();save();}if(b.dataset.review)showWork(b.dataset.review);if(b.dataset.previewCard)previewCard(b.dataset.previewCard);if(b.dataset.feedback)recordFeedback(b.dataset.feedback);if(b.id==='addCard'){if(state.cards.length>=20)return notice('You can keep twenty cards.');state.cards.push({id:uid(),protocol:'',prompt:'',purpose:'',layer:'',follow:'',checked:false});cards();changed();}if(b.id==='addPeer'){if(state.peers.length>=40)return notice('You can keep forty recall records.');state.peers.push({id:uid(),protocol:'',first:'',correction:'',retry:''});peers();changed();}if(b.dataset.removeCard&&confirm('Remove this card?')){state.cards=state.cards.filter(x=>x.id!==b.dataset.removeCard);cards();save();}if(b.dataset.removePeer&&confirm('Remove this recall record?')){state.peers=state.peers.filter(x=>x.id!==b.dataset.removePeer);peers();save();}if(b.dataset.removePhoto&&confirm('Remove this photograph?')){state.photos[b.dataset.photoStage]=state.photos[b.dataset.photoStage].filter(x=>x.id!==b.dataset.removePhoto);photos(b.dataset.photoStage);save();}if(['pdfTop','downloadPDF'].includes(b.id))await pdf();if(b.id==='cardsPDF')await pdf(true);if(b.id==='backup')await backup();if(b.id==='previewPDF'){$('#reviewBody').innerHTML=L.stages.filter(s=>!['overview','resources','report'].includes(s.id)).map(s=>`<h2>${s.title}</h2>${evidence(s.id,true)}`).join('');$('#reviewDialog').showModal();}if(b.id==='closeDialog')$('#reviewDialog').close();if(b.id==='showAll'&&teacher){$$('[data-stage]').forEach(x=>x.hidden=false);notice('All stages are visible. Choose a menu item to return to one stage.');}if(b.id==='closeWork'){if(uploadBusy)return notice('Wait for photographs to finish processing.');await save();if(!saved)return notice('Download an editable backup before closing.');state=null;teacher=false;$('#workspace').hidden=true;$('#landing').hidden=false;$('#entry').reset();$('#name').focus();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&state)save();});window.addEventListener('beforeunload',e=>{if(state&&(!saved||uploadBusy)){e.preventDefault();e.returnValue='';}});
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'open_lesson_stage',description:'Navigate within the currently open protocols lesson. Does not complete work or submit anything.',inputSchema:{type:'object',properties:{stage:{type:'string',enum:L.stages.map(s=>s.id)}},required:['stage'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!state)throw Error('Open the lesson with your name and class first.');if(!input||!L.stages.some(s=>s.id===input.stage))throw Error('Unknown stage.');go(input.stage);return{stage:input.stage};}})).catch(()=>{});}catch{}}
})();
