input.onButtonPressed(Button.A, function () {
    basic.showIcon(IconNames.Diamond)
    basic.pause(500)
    basic.clearScreen()
    basic.pause(500)
    basic.showIcon(IconNames.Diamond)
    basic.pause(500)
    basic.clearScreen()
    basic.pause(500)
    basic.showIcon(IconNames.Yes)
})
basic.showIcon(IconNames.Yes)
