(() => {
  'use strict';
  const APP = 'year6-checkpoint-2026-v1';
  const $ = id => document.getElementById(id);
  const cards = [
    ['guide','Get ready','Start'],
    ['files','Files and folders','Organise'],
    ['clear','Clear instructions','Organise'],
    ['algorithm','Algorithm or program?','Plan'],
    ['jobs','Smaller jobs','Plan'],
    ['route','Build a robot route','Plan'],
    ['ipo','Input, process, output','Plan'],
    ['predict','Predict a coordinate','Scratch'],
    ['scratch-open','Open and run Scratch','Scratch'],
    ['scratch-fix','Fix and test Scratch','Scratch'],
    ['explain','Explain your test','Explain'],
    ['review','Review your answers','Finish'],
    ['submit','Save and submit','Finish'],
  ];
  const reviewIndex = cards.findIndex(c => c[0] === 'review');
  const routeMap = {width:6,height:5,start:[0,4],key:[3,2],portal:[5,0],walls:new Set(['1,4','1,3','3,3','2,1','4,1','4,3'])};
  const movements = {N:[0,-1],E:[1,0],S:[0,1],W:[-1,0]};
  const moveNames = {N:'Up',E:'Right',S:'Down',W:'Left'};
  let state = null, returnToReview = false, toastTimer;

  function esc(value){return String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function bilingual(en,zh){return `<span class="en">${en}</span><span class="zh" lang="zh-Hans">${zh}</span>`;}
  function field(name){return esc(state?.answers?.[name] ?? '');}
  function choice(name,value,label){return `<label class="choice"><input type="radio" name="${name}" data-field="${name}" value="${esc(value)}" ${state.answers[name]===value?'checked':''}>${label}</label>`;}
  function input(name,placeholder='',type='text'){return `<input class="text-field" type="${type}" data-field="${name}" value="${field(name)}" placeholder="${esc(placeholder)}" ${type==='number'?'inputmode="numeric"':''}>`;}
  function area(name,placeholder=''){return `<textarea data-field="${name}" placeholder="${esc(placeholder)}">${field(name)}</textarea>`;}
  function select(name,values){return `<select data-field="${name}"><option value="">Choose...</option>${values.map(([v,l])=>`<option value="${esc(v)}" ${state.answers[name]===v?'selected':''}>${esc(l)}</option>`).join('')}</select>`;}
  function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),4000);}
  function key(name,cls){return `${APP}:${name.trim().toLowerCase().replace(/\s+/g,' ')}:${cls.trim().toLowerCase().replace(/\s+/g,' ')}`;}
  function save(){if(!state)return;try{localStorage.setItem(key(state.name,state.cls),JSON.stringify(state));}catch{toast('This browser could not save automatically. Download a JSON backup.');}}
  function validate(data){if(!data||data.app!==APP||!data.state)throw Error('Choose a Year 6 checkpoint backup.');const s=data.state;if(s.version!==1||typeof s.name!=='string'||!s.name.trim()||s.name.length>60||typeof s.cls!=='string'||!s.cls.trim()||s.cls.length>30||!Number.isInteger(s.current)||s.current<0||s.current>=cards.length||!s.answers||typeof s.answers!=='object'||Array.isArray(s.answers)||!Array.isArray(s.route)||s.route.length>30||!s.route.every(x=>Object.hasOwn(movements,x))||!Array.isArray(s.routeRuns)||!Array.isArray(s.flags))throw Error('This backup is incomplete.');s.answers=Object.fromEntries(Object.entries(s.answers).filter(([k,v])=>typeof k==='string'&&typeof v==='string'&&v.length<=4000));s.routeRuns=s.routeRuns.filter(r=>r&&Array.isArray(r.commands)&&r.commands.every(x=>Object.hasOwn(movements,x))&&Array.isArray(r.trail)&&r.trail.every(p=>Array.isArray(p)&&p.length===2&&p.every(Number.isFinite))&&Array.isArray(r.final)&&r.final.length===2&&r.final.every(Number.isFinite)&&typeof r.message==='string').slice(-30);s.flags=s.flags.filter(x=>cards.some(c=>c[0]===x));s.maxVisited=Math.min(cards.length-1,Math.max(s.current,Number(s.maxVisited)||0));s.language=s.language==='bi'?'bi':'en';s.scratchFileName=typeof s.scratchFileName==='string'?s.scratchFileName.slice(0,200):'';s.startedAt=Number.isFinite(s.startedAt)&&s.startedAt>0?s.startedAt:Date.now();return s;}
  function start(s){state=s;save();$('welcome').hidden=true;$('assessment').hidden=false;document.body.classList.toggle('bilingual',state.language==='bi');$('studentBadge').textContent=`${state.name} · ${state.cls}`;$('elapsed').textContent=`${Math.floor((Date.now()-state.startedAt)/60000)} min elapsed`;render(true);}

  $('startForm').addEventListener('submit',e=>{
    e.preventDefault();const name=$('studentName').value.trim(),cls=$('studentClass').value.trim();
    if(!name||!cls)return;
    const language=document.querySelector('input[name="language"]:checked').value;
    const stored=localStorage.getItem(key(name,cls));let s;
    try{if(stored&&confirm('Continue the saved assessment for this name and class? Choose Cancel to start again.'))s=validate({app:APP,state:JSON.parse(stored)});}catch{toast('Saved work could not be opened. A new assessment will start.');}
    if(!s)s={version:1,name,cls,language,current:0,maxVisited:0,answers:{},route:[],routeRuns:[],flags:[],scratchFileName:'',startedAt:Date.now()};
    s.language=language;start(s);
  });
  $('restoreFile').addEventListener('change',async e=>{
    const file=e.target.files[0];if(!file)return;
    try{if(file.size>2_000_000)throw Error('The backup is too large.');const s=validate(JSON.parse(await file.text()));if(!confirm(`Restore work for ${s.name} (${s.cls})? This will replace saved work for that learner on this device.`))return;$('studentName').value=s.name;$('studentClass').value=s.cls;document.querySelector(`input[name="language"][value="${s.language}"]`).checked=true;start(s);toast('Backup restored.');}
    catch(err){$('restoreMessage').textContent=err.message;}
  });
  $('saveBackup').addEventListener('click',downloadBackup);
  $('previous').addEventListener('click',()=>{if(state.current>0){state.current--;returnToReview=false;save();render(true);}});
  $('next').addEventListener('click',()=>{
    if(state.current>=cards.length-1)return;
    const id=cards[state.current][0];
    if(!answered(id)&&!['guide','review'].includes(id)&&!confirm('You have not finished this step. Go on and return to it later?'))return;
    state.current=returnToReview?reviewIndex:state.current+1;returnToReview=false;
    state.maxVisited=Math.max(state.maxVisited,state.current);save();render(true);
  });
  $('flag').addEventListener('click',()=>{const id=cards[state.current][0],i=state.flags.indexOf(id);if(i>=0)state.flags.splice(i,1);else state.flags.push(id);save();render(false);toast(i>=0?'Flag removed.':'Step flagged for review.');});
  setInterval(()=>{if(state){const mins=Math.floor((Date.now()-state.startedAt)/60000);$('elapsed').textContent=`${mins} min elapsed`;}},30000);

  function answered(id){const a=state.answers;
    if(id==='files')return !!(a.projectFile&&a.folder&&a.filename?.trim());
    if(id==='clear')return !!a.clearInstruction?.trim();
    if(id==='algorithm')return !!(a.algorithmChoice&&a.algorithmWhy?.trim());
    if(id==='jobs')return !!(a.decompositionWord&&a.jobOne?.trim()&&a.jobTwo?.trim());
    if(id==='route')return state.routeRuns.at(-1)?.commands.join(',')===state.route.join(',');
    if(id==='ipo')return !!(a.ipoInput&&a.ipoProcess&&a.ipoOutput);
    if(id==='predict')return a.predictX!==undefined&&a.predictX!==''&&a.predictY!==undefined&&a.predictY!=='';
    if(id==='scratch-open')return a.actualX!==undefined&&a.actualX!==''&&a.actualY!==undefined&&a.actualY!=='';
    if(id==='scratch-fix')return !!(a.changedBlock&&a.fixedX!==undefined&&a.fixedX!==''&&a.fixedY!==undefined&&a.fixedY!=='');
    if(id==='explain')return !!a.retestReason?.trim();
    return true;
  }
  function render(scroll){
    const [id,title,section]=cards[state.current];$('progressText').textContent=`Step ${state.current+1} of ${cards.length}`;$('sectionLabel').textContent=section;$('progress').value=Math.round((state.current+1)/cards.length*100);
    $('journeyList').innerHTML=cards.map(([cid,ctitle],i)=>`<li class="${i===state.current?'current':i<=state.maxVisited?'done':''} ${state.flags.includes(cid)?'flagged':''}">${esc(ctitle)}</li>`).join('');
    $('taskCard').innerHTML=`<div class="card-kicker">${esc(section.toUpperCase())}</div><h1>${esc(title)}</h1>${content(id)}`;
    $('previous').disabled=state.current===0;$('next').hidden=id==='submit';$('next').textContent=returnToReview?'Return to review →':id==='review'?'Go to submission →':'Next step →';$('flag').hidden=['guide','review','submit'].includes(id);$('flag').textContent=state.flags.includes(id)?'Remove flag':'Flag for later';
    bindCard(id);if(scroll){$('taskCard').scrollIntoView({block:'start'});$('taskCard').focus({preventScroll:true});}
  }
  function content(id){
    switch(id){
      case 'guide':return `<p class="instruction">${bilingual('You will complete one small task at a time. Read the question, make your own choice, then use Next step. You may go Back or Flag for later.','你会一次完成一个小任务。先读题，再自己作答，然后按“下一步”。你可以返回或标记稍后再做。')}</p><div class="hint"><strong>Practice the controls:</strong> Press the practice button below. It is not part of the test.<br><span class="zh">先按下面的练习按钮。这不计分。</span></div><button type="button" class="secondary" id="practiceButton">I can press a button</button><p id="practiceResponse" class="small-note" role="status"></p><div class="warning">${bilingual('Work independently. The website saves your answers, but save your Scratch code as a separate file too.','请独立完成。网页会保存答案，但 Scratch 程序也要另外存档。')}</div>`;
      case 'files':return `<p class="instruction">${bilingual('A friend wants to open their Scratch code next week. Look at the three file endings.','一位同学下周想重新打开 Scratch 程序。看这三种文件扩展名。')}</p><div class="files" aria-label="File endings"><div class="file-chip">PDF</div><div class="file-chip">SB3</div><div class="file-chip">JSON</div></div><fieldset class="question"><legend>${bilingual('1. Which file opens the Scratch project?','1. 哪个文件可以打开 Scratch 项目？')}</legend><div class="choice-grid">${choice('projectFile','pdf','PDF')}${choice('projectFile','sb3','SB3')}${choice('projectFile','json','JSON')}</div></fieldset><fieldset class="question"><legend>${bilingual('2. Where should your Year 6 Computing project go?','2. 你的六年级计算项目应该保存在哪里？')}</legend><div class="choice-grid">${choice('folder','computing','Documents → Year 6 Computing → My name')}${choice('folder','photos','Photos → Random pictures')}${choice('folder','downloads','Downloads → Old files')}</div></fieldset><div class="form-block"><label class="field-label">${bilingual('3. Give your Scratch project a clear file name. Include the ending you chose in Question 1.','3. 为 Scratch 项目取一个清楚的文件名，并加上你在第 1 题选择的扩展名。')}</label>${input('filename','Your file name')}</div>`;
      case 'clear':return `<p class="instruction">${bilingual('A robot hears: “Move a bit.” That is too vague. Study this tiny route.','机器人听到：“移动一点。”这不够清楚。看看下面的小路线。')}</p><div class="mini-path" aria-label="Robot route"><span>START</span><span>□</span><span>⭐ GOAL</span><span>□</span><span>▥ WALL</span></div><div class="form-block"><label class="field-label" for="clearInstruction">${bilingual('Write one clear instruction that takes the robot from START to the star. Include a direction and a number of spaces.','写一条清楚的指令，让机器人从起点到星星。说明方向和格数。')}</label>${area('clearInstruction','The robot should...')}</div><p class="small-note">${bilingual('Use your own words. A short sentence is enough.','用自己的话写，简短一句即可。')}</p>`;
      case 'algorithm':return `<p class="instruction">${bilingual('Read the two cards. They show the same idea in different ways.','阅读两张卡片。它们用不同方式表达同一个想法。')}</p><div class="visual-grid"><div class="hint"><strong>Card A</strong><p>When the green flag starts, place Explorer at x = −200, y = −135.</p></div><div class="code-preview"><strong>Card B</strong><img src="assets/algorithm-program-blocks.png" alt="Real Scratch blocks: when green flag clicked, go to x negative 200 y negative 135"></div></div><fieldset class="question"><legend>${bilingual('Which card is an algorithm written in words?','哪张卡是用文字写的算法？')}</legend><div class="choice-grid">${choice('algorithmChoice','A','Card A')}${choice('algorithmChoice','B','Card B')}</div></fieldset><div class="form-block"><label class="field-label">${bilingual('Why did you choose it?','你为什么这样选？')}</label>${area('algorithmWhy','My reason...')}</div><p class="small-note">Card B is a genuine Scratch screenshot. It is an example, not the solution to your later Scratch task.</p>`;
      case 'jobs':return `<p class="instruction">${bilingual('Big mission: the robot must collect a key before it can reach a locked portal. Break this into two smaller jobs.','大任务：机器人必须先拿到钥匙，才能到达上锁的传送门。把任务分成两个小任务。')}</p><div class="hint"><strong>START</strong> → <strong>KEY</strong> → <strong>PORTAL</strong><span class="zh">从起点到钥匙，再到传送门。</span></div><fieldset class="question"><legend>${bilingual('What do we call breaking a big problem into smaller jobs?','把大问题分成小任务叫什么？')}</legend><div class="choice-grid">${choice('decompositionWord','decomposition','Decomposition')}${choice('decompositionWord','debugging','Debugging')}${choice('decompositionWord','output','Output')}</div></fieldset><div class="field-row"><div class="form-block"><label class="field-label">${bilingual('First job','第一个小任务')}</label>${input('jobOne','First, the robot...')}</div><div class="form-block"><label class="field-label">${bilingual('Second job','第二个小任务')}</label>${input('jobTwo','Then, the robot...')}</div></div><p class="small-note">${bilingual('Do not write code here. Plan what needs to happen.','这里不用写代码。先计划要做什么。')}</p>`;
      case 'route':return `<p class="instruction">${bilingual('Now make your own route. Add steps to reach the key, then the portal. Walls cannot be crossed. Press Run route to test your plan.','现在自己规划路线。先到钥匙，再到传送门。不能穿过墙。按“运行路线”测试。')}</p><div class="route-layout"><div><div class="maze" id="maze" role="img" aria-label="Six by five grid, start at bottom left, key near the centre, portal at top right, with marked walls">${routeGrid()}</div><p class="small-note">START = robot · KEY = collect first · PORTAL = finish · striped = wall</p></div><div><h3>Add one step</h3><div class="command-buttons"><button type="button" data-move="N">↑ Up</button><button type="button" data-move="E">→ Right</button><button type="button" data-move="W">← Left</button><button type="button" data-move="S">↓ Down</button></div><ol class="command-list" id="commandList">${commandList()}</ol><button class="primary" type="button" id="runRoute">Run route</button> <button class="secondary" type="button" id="clearRoute">Clear steps</button><div class="route-status hint" id="routeStatus">${state.routeRuns.length?(state.routeRuns.at(-1).commands.join(',')===state.route.join(',')?esc(state.routeRuns.at(-1).message):'You changed the route. Run it again to test the new steps.'):'Build a route, then test it.'}</div></div></div>`;
      case 'ipo':return `<p class="instruction">${bilingual('A pupil presses an arrow key. The computer checks the key, then the robot moves. Choose the job of each part.','一位同学按方向键。计算机检查按键，然后机器人移动。为每一步选择名称。')}</p><div class="field-row"><div class="form-block"><label class="field-label">① Pupil presses →</label>${select('ipoInput',[['input','Input'],['process','Process'],['output','Output']])}</div><div class="form-block"><label class="field-label">② Code checks key →</label>${select('ipoProcess',[['input','Input'],['process','Process'],['output','Output']])}</div></div><div class="form-block"><label class="field-label">③ Robot moves →</label>${select('ipoOutput',[['input','Input'],['process','Process'],['output','Output']])}</div>`;
      case 'predict':return `<p class="instruction">${bilingual('Explorer starts at x = −120, y = −80. The goal is to move 80 steps RIGHT and stay at the same height. Predict the finishing coordinate before opening Scratch.','探索者从 x = −120、y = −80 开始。目标是向右移动 80 步，高度不变。打开 Scratch 前预测终点坐标。')}</p><div class="visual-grid"><div>${coordinateGrid()}</div><div><div class="field-row"><div class="form-block"><label class="field-label">Final x</label>${input('predictX','x','number')}</div><div class="form-block"><label class="field-label">Final y</label>${input('predictY','y','number')}</div></div><div class="hint">${bilingual('Think: right changes which coordinate? Which coordinate stays the same?','想一想：向右移动会改变哪个坐标？哪个坐标保持不变？')}</div></div></div>`;
      case 'scratch-open':return `<p class="instruction">${bilingual('This is the practical part. Open the unfinished Scratch starter, run it once, and record where Explorer actually finishes. The starter contains a mistake. Do not fix it yet.','现在做实践部分。打开未完成的 Scratch 模板，运行一次，记录探索者实际停在哪里。模板中有一个错误，先不要修改。')}</p><div class="submit-actions"><a class="primary" href="assets/Year6_Checkpoint_Coordinate_Starter.sb3" download>1 · Download Scratch starter (.sb3)</a><a class="secondary" href="https://scratch.mit.edu/projects/editor/" target="_blank" rel="noopener noreferrer">2 · Open Scratch editor ↗</a></div><ol class="step-list"><li>In Scratch, choose File → Load from your computer, then select the starter .sb3. Scratch Desktop can open the same file.</li><li>Click Explorer below the stage. Press the green flag.</li><li>Look at Explorer's x and y numbers under the stage. Type both numbers here.</li></ol><details><summary>Where should I look? Show a Scratch interface guide</summary><div class="guide-shot stage" aria-label="Real Scratch interface showing stage and sprite controls"><img src="assets/scratch-interface.jpg" alt="Scratch interface with the stage and sprite information below it"></div><p class="small-note">This screenshot shows where the controls are. Your checkpoint project has a different stage.</p></details><div class="field-row"><div class="form-block"><label class="field-label">Actual x after running the starter</label>${input('actualX','x','number')}</div><div class="form-block"><label class="field-label">Actual y after running the starter</label>${input('actualY','y','number')}</div></div>`;
      case 'scratch-fix':return `<p class="instruction">${bilingual('Fix the starter in Scratch. Explorer should move 80 steps RIGHT from its starting position and stay at the same height. Change one wrong block. Run the green flag again.','在 Scratch 中修正模板。探索者应该从起点向右移动 80 步，高度不变。只改一个错误的积木，再按绿旗运行。')}</p><div class="warning">${bilingual('Do the change in your Scratch project, not just on this webpage.','要在 Scratch 项目里修改，不只是填写网页。')}</div><details><summary>Need help finding the blocks? Show a screenshot guide</summary><div class="guide-shot motion" aria-label="Real Scratch interface showing the blue Motion category"><img src="assets/scratch-interface.jpg" alt="Scratch Motion category with blue movement blocks"></div><p class="small-note">Look in the blue Motion category. The screenshot does not show your answer.</p></details><div class="form-block"><label class="field-label">Which type of block did you change?</label>${select('changedBlock',[['x','A block that changes x'],['y','A block that changes y'],['go','The go to x/y block'],['other','Something else']])}</div><div class="field-row"><div class="form-block"><label class="field-label">Final x after your fix</label>${input('fixedX','x','number')}</div><div class="form-block"><label class="field-label">Final y after your fix</label>${input('fixedY','y','number')}</div></div><div class="form-block"><label class="field-label">What did you change?</label>${area('fixNote','I changed...')}</div><p class="small-note">Later, save this project as a separate .sb3 file.</p>`;
      case 'explain':return `<p class="instruction">${bilingual('After changing a block, why is it important to run the program again? Answer in one short sentence.','改动积木之后，为什么还要再次运行程序？用简短一句回答。')}</p><div class="form-block"><label class="field-label">My explanation</label>${area('retestReason','I test again to find out whether...')}</div><div class="hint">${bilingual('Think about the result you expected and the result you saw.','想一想你预期的结果和实际看到的结果。')}</div>`;
      case 'review':return `<p class="instruction">${bilingual('Check your work before submitting. A yellow step needs an answer or a final check. You may return to any step here.','提交前检查作答。黄色步骤需要答案或最后检查。你可以从这里返回任一步骤。')}</p><div class="review-list">${cards.slice(1,reviewIndex).map(([cid,title],i)=>`<div class="review-row"><span>${esc(title)}</span><span class="pill ${answered(cid)?'done':'todo'}">${answered(cid)?'Recorded':'Check'}</span><button type="button" data-jump="${i+1}">Open</button></div>`).join('')}</div><p class="small-note">This page checks whether you entered work. It does not tell you whether an answer is correct.</p>`;
      case 'submit':return `<p class="instruction">${bilingual('You have two pieces of work: your assessment PDF and your Scratch project. Download and upload both to your Teams assignment.','你有两个文件：测评 PDF 和 Scratch 项目。下载后把两个文件都上传到 Teams 作业。')}</p><ol class="submit-checklist"><li><strong>1 · Scratch file:</strong> In Scratch choose File → Save to your computer. Give it a clear name ending in <code>.sb3</code>.</li><li><strong>2 · Assessment PDF:</strong> Download your answer report below. Open it and check your name and answers.</li><li><strong>3 · Teams:</strong> Upload BOTH the PDF and .sb3. A JSON backup is for continuing later, not for the teacher's main submission.</li></ol><div class="file-picker"><label class="field-label" for="scratchFile">Check that you have your saved .sb3 file</label><input id="scratchFile" type="file" accept=".sb3"><p id="scratchFileStatus" class="small-note">${state.scratchFileName?'Selected earlier: '+esc(state.scratchFileName)+' (select again on this device to verify)':'No .sb3 file selected yet.'}</p></div><div class="submit-actions"><button class="primary" type="button" id="downloadPdf">Download assessment PDF</button><button class="secondary" type="button" id="printPdf">Print / save PDF (for Chinese text)</button><button class="secondary" type="button" id="downloadBackup2">Download JSON backup</button></div><p class="small-note" id="pdfStatus" role="status"></p><div class="warning">This webpage cannot upload to Teams for you. Check both attachments in Teams before you leave.</div>`;
    }
  }

  function routeGrid(){const latest=state.routeRuns.at(-1),trail=latest?.commands?.join(',')===state.route.join(',')?latest.trail:[];let html='';for(let y=0;y<routeMap.height;y++)for(let x=0;x<routeMap.width;x++){const k=`${x},${y}`,wall=routeMap.walls.has(k),start=x===routeMap.start[0]&&y===routeMap.start[1],key=x===routeMap.key[0]&&y===routeMap.key[1],portal=x===routeMap.portal[0]&&y===routeMap.portal[1],step=trail.findLastIndex(p=>p[0]===x&&p[1]===y);html+=`<div class="maze-cell ${wall?'wall':''} ${start?'start':''} ${key?'key':''} ${portal?'portal':''} ${step>=0?'trail':''} ${latest?.final?.[0]===x&&latest?.final?.[1]===y?'robot':''}" data-step="${step>0?step:''}" aria-label="${wall?'wall':start?'start':key?'key':portal?'portal':'open square'}">${wall?'':start?'START':key?'KEY':portal?'PORTAL':''}</div>`;}return html;}
  function commandList(){return state.route.length?state.route.map((cmd,i)=>`<li><span>${i+1}. ${moveNames[cmd]}</span><span><button type="button" data-up="${i}" aria-label="Move step ${i+1} up">↑</button> <button type="button" data-down="${i}" aria-label="Move step ${i+1} down">↓</button> <button type="button" data-remove="${i}" aria-label="Remove step ${i+1}">×</button></span></li>`).join(''):'<li>Your route is empty. Add the first step.</li>';}
  function runRoute(){let x=routeMap.start[0],y=routeMap.start[1],hasKey=false,trail=[[x,y]],message='The robot stopped before the portal.';for(let i=0;i<state.route.length;i++){const [dx,dy]=movements[state.route[i]];x+=dx;y+=dy;if(x<0||x>=routeMap.width||y<0||y>=routeMap.height){x-=dx;y-=dy;message=`Step ${i+1} left the map. Edit your route and try again.`;break;}if(routeMap.walls.has(`${x},${y}`)){x-=dx;y-=dy;message=`Step ${i+1} hit a wall. Edit your route and try again.`;break;}trail.push([x,y]);if(x===routeMap.key[0]&&y===routeMap.key[1])hasKey=true;if(x===routeMap.portal[0]&&y===routeMap.portal[1]){message=hasKey?'The robot reached the portal with the key.':'The robot reached the portal without the key. Try again.';break;}if(i===state.route.length-1)message=hasKey?'The robot has the key but has not reached the portal.':'The robot has not reached the key yet.';}const run={commands:[...state.route],trail,final:[x,y],hasKey,message,at:new Date().toISOString()};state.routeRuns.push(run);if(state.routeRuns.length>30)state.routeRuns.shift();save();render(false);}
  function coordinateGrid(){let lines='',labels='';for(let x=-200;x<=200;x+=40){const px=280+x;lines+=`<line x1="${px}" y1="20" x2="${px}" y2="360" stroke="${x===0?'#19372a':'#d5e4d9'}" stroke-width="${x===0?2:1}"/>`;if(x%80===0)labels+=`<text x="${px}" y="378" text-anchor="middle">${x}</text>`;}for(let y=-160;y<=160;y+=40){const py=190-y;lines+=`<line x1="40" y1="${py}" x2="520" y2="${py}" stroke="${y===0?'#19372a':'#d5e4d9'}" stroke-width="${y===0?2:1}"/>`;if(y%80===0)labels+=`<text x="28" y="${py+5}" text-anchor="end">${y}</text>`;}return `<svg class="grid-figure" viewBox="0 0 560 390" role="img" aria-label="Coordinate grid with Explorer starting at x negative 120, y negative 80. Positive x goes right and positive y goes up."><rect x="0" y="0" width="560" height="390" fill="white"/>${lines}<g font-family="Arial" font-size="15" fill="#18422d">${labels}<text x="525" y="184">+x</text><text x="286" y="14">+y</text></g><circle cx="160" cy="270" r="18" fill="#2378bd" stroke="#153a57" stroke-width="3"/><text x="160" y="276" fill="white" text-anchor="middle" font-size="17" font-weight="700">E</text><text x="184" y="263" fill="#17432d" font-family="Arial" font-size="17" font-weight="700">START (-120, -80)</text></svg>`;}

  function bindCard(id){
    $('taskCard').querySelectorAll('[data-field]').forEach(el=>{el.addEventListener(el.type==='radio'||el.tagName==='SELECT'?'change':'input',()=>{state.answers[el.dataset.field]=el.value;save();});});
    $('practiceButton')?.addEventListener('click',()=>{$('practiceResponse').textContent='Great. The Next step button is at the bottom right.';});
    if(id==='route'){
      $('taskCard').querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>{if(state.route.length>=30)return toast('Use no more than 30 steps. Remove a step before adding another.');state.route.push(b.dataset.move);save();render(false);});
      $('taskCard').querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>{const i=+b.dataset.up;if(i>0)[state.route[i-1],state.route[i]]=[state.route[i],state.route[i-1]];save();render(false);});
      $('taskCard').querySelectorAll('[data-down]').forEach(b=>b.onclick=()=>{const i=+b.dataset.down;if(i<state.route.length-1)[state.route[i+1],state.route[i]]=[state.route[i],state.route[i+1]];save();render(false);});
      $('taskCard').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{state.route.splice(+b.dataset.remove,1);save();render(false);});
      $('runRoute').onclick=()=>{if(!state.route.length)return toast('Add at least one step first.');runRoute();};
      $('clearRoute').onclick=()=>{if(state.route.length&&confirm('Clear every step in this route? Previous test records will stay in your report.')){state.route=[];save();render(false);}};
    }
    if(id==='review')$('taskCard').querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>{state.current=+b.dataset.jump;returnToReview=true;save();render(true);});
    if(id==='submit'){
      $('scratchFile').onchange=e=>{const f=e.target.files[0];if(!f)return;if(!/\.sb3$/i.test(f.name)){$('scratchFileStatus').textContent='Choose a Scratch .sb3 project, not a PDF or JSON file.';e.target.value='';return;}state.scratchFileName=f.name;save();$('scratchFileStatus').textContent=`Ready: ${f.name}. Remember to upload this file separately to Teams.`;};
      $('downloadPdf').onclick=downloadPdf;$('printPdf').onclick=printPdf;$('downloadBackup2').onclick=downloadBackup;
    }
  }
  function download(name,type,text){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);}
  function fileStem(){return `Y6_Checkpoint_${state.cls}_${state.name}`.replace(/[^A-Za-z0-9_-]+/g,'_').slice(0,80);}
  function downloadBackup(){if(!state)return;download(`${fileStem()}_Backup.json`,'application/json',JSON.stringify({app:APP,exportedAt:new Date().toISOString(),state},null,2));toast('JSON backup downloaded. Keep it if you need to continue later.');}
  const reportFields=[['Files','projectFile','folder','filename'],['Clear instruction','clearInstruction'],['Algorithm or program','algorithmChoice','algorithmWhy'],['Smaller jobs','decompositionWord','jobOne','jobTwo'],['Input, process, output','ipoInput','ipoProcess','ipoOutput'],['Coordinate prediction','predictX','predictY'],['Scratch starter result','actualX','actualY'],['Scratch fix and test','changedBlock','fixedX','fixedY','fixNote'],['Why test again?','retestReason']];
  function reportSections(){const sections=reportFields.map(([title,...keys])=>({title,lines:keys.map(k=>`${k.replace(/([A-Z])/g,' $1')}: ${String(state.answers[k]??'Not recorded')}`)}));const run=state.routeRuns.at(-1);sections.splice(4,0,{title:'Robot route',lines:[`Current steps: ${state.route.map(x=>moveNames[x]).join(', ')||'None'}`,`Test runs: ${state.routeRuns.length}`,`Last tested steps: ${run?.commands.map(x=>moveNames[x]).join(', ')||'None'}`,`Latest result: ${run?.message||'Not tested'}`,`Current steps retested: ${run?.commands.join(',')===state.route.join(',')?'Yes':'No'}`]});sections.push({title:'Files and submission',lines:[`Scratch .sb3 chosen: ${state.scratchFileName||'Not recorded'}`,'Teacher should receive the PDF and the separately saved .sb3 project.']});return sections;}
  function downloadPdf(){if(!window.jspdf?.jsPDF){$('pdfStatus').textContent='PDF maker did not load. Use Print / save PDF instead.';return;}const values=[state.name,state.cls,...reportSections().flatMap(s=>s.lines.map(String))];if(values.some(v=>/[^\u0000-\u00ff]/.test(v))){$('pdfStatus').textContent='Your name or answers contain characters this PDF font may not show. Choose Print / save PDF instead so every character stays visible.';return;}const doc=new window.jspdf.jsPDF({unit:'mm',format:'a4'}),margin=17,max=178;let y=20;const add=(txt,size=11,bold=false)=>{doc.setFont('helvetica',bold?'bold':'normal');doc.setFontSize(size);const lines=doc.splitTextToSize(String(txt),max);for(const line of lines){if(y>274){doc.addPage();y=19;}doc.text(line,margin,y);y+=size*.48;}y+=3;};add('YEAR 6 COMPUTING - LEARNING CHECKPOINT',11,true);add(`${state.name} | ${state.cls}`,19,true);add(`Saved: ${new Date().toLocaleString('en-GB')}`,9);add('This report records website answers. The Scratch .sb3 project is separate.',9);for(const sec of reportSections()){if(y>255){doc.addPage();y=19;}y+=3;add(sec.title,14,true);for(const line of sec.lines)add(line,10);}const total=doc.getNumberOfPages();for(let i=1;i<=total;i++){doc.setPage(i);doc.setFontSize(8);doc.setTextColor(110);doc.text(`${i} / ${total}`,191,287,{align:'right'});}doc.save(`${fileStem()}.pdf`);$('pdfStatus').textContent='PDF downloaded. Open it and check your answers.';}
  function printPdf(){const wrap=$('printReport');wrap.replaceChildren();const h=document.createElement('h1');h.textContent='Year 6 Computing - Learning Checkpoint';wrap.append(h);const p=document.createElement('p');p.textContent=`${state.name} | ${state.cls}\nThe Scratch .sb3 project is separate.`;wrap.append(p);for(const sec of reportSections()){const h2=document.createElement('h2');h2.textContent=sec.title;wrap.append(h2);for(const line of sec.lines){const para=document.createElement('p');para.textContent=line;wrap.append(para);}}wrap.hidden=false;window.addEventListener('afterprint',()=>wrap.hidden=true,{once:true});window.print();}
})();
