(() => {
  'use strict';
  if(document.documentElement.dataset.appVersion!=='3')throw Error('Lesson file versions do not match. Refresh without cached files.');
  const APP='year6-checkpoint-2026-v1', STORE='year6-checkpoint-2026-v2';
  const $=id=>document.getElementById(id), mission=window.CheckpointMission;
  const phases=[['Ready','准备'],['Try code','试读代码'],['Plan','计划'],['Create','编程'],['Test','测试'],['Explain','解释'],['Hand in','提交']];
  const previousCards=['guide','files','words','clear','jobs','plan','read','open','build','test','explain','review','submit'];
  const cards=[
    ['guide','Your mission','你的任务',0],['words','A quick warm-up','快速热身',1],
    ['read','Read these blocks','读这段积木',1],['open','Open Scratch now','现在打开 Scratch',1],
    ['jobs','Split your mission','拆分你的任务',2],['plan','Make your route plan','制定路线计划',2],
    ['build-key','Code to the key','编程到钥匙',3],['build','Code to the portal','编程到传送门',3],['test','Test and improve your journey','测试并改进路线',4],
    ['create-extra','Create your own challenge','设计自己的挑战',4],['explain','Explain your program','解释你的程序',5],['review','Check your evidence','检查你的学习证据',6],
    ['submit','Save and hand in','保存并提交',6]
  ];
  cards.splice(cards.findIndex(c=>c[0]==='review'),0,['files','Name your Scratch file','命名 Scratch 文件',6]);
  const reviewIndex=cards.findIndex(c=>c[0]==='review');
  let state=null,toastTimer,returnToReview=false,fileObject=null,importBusy=false;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const korean=en=>window.CheckpointKorean.text(en);
  const b=(en,zh)=>`<span class="en">${en}</span><span class="zh" lang="zh-Hans">${zh}</span><span class="ko" lang="ko">${korean(en)}</span>`;
  const t=(en,zh,language=state?.language)=>language==='bi'?`${en}\n${zh}`:language==='ko'?`${en}\n${korean(en)}`:en;
  function languageClass(language){document.body.classList.toggle('bilingual',language==='bi');document.body.classList.toggle('korean',language==='ko');document.documentElement.dataset.readingLanguage=language;}
  document.querySelectorAll('[data-en]').forEach(el=>el.innerHTML=b(el.dataset.en,el.dataset.zh));
  const moveNames={N:['↑ Up','↑ 向上'],E:['→ Right','→ 向右'],S:['↓ Down','↓ 向下'],W:['← Left','← 向左']};
  const normal=s=>s.trim().toLowerCase().replace(/\s+/g,' ');
  const key=(name,cls,prefix=STORE)=>`${prefix}:${normal(name)}:${normal(cls)}`;
  const value=name=>esc(state.answers[name]??'');
  function inp(name,en='',zh='',type='text'){return `<input class="text-field" id="${name}" data-field="${name}" type="${type}" value="${value(name)}" placeholder="${esc(t(en,zh))}" ${type==='number'?'inputmode="numeric"':'maxlength="1000"'}>`;}
  function area(name,en='',zh=''){return `<textarea id="${name}" data-field="${name}" maxlength="1000" placeholder="${esc(t(en,zh))}">${value(name)}</textarea>`;}
  function field(name,en,zh,control){return `<div class="form-block"><label class="field-label" for="${name}">${b(en,zh)}</label>${control}</div>`;}
  function choice(name,val,en,zh){return `<label class="choice"><input type="radio" name="${name}" data-field="${name}" value="${esc(val)}" ${state.answers[name]===val?'checked':''}><span>${b(en,zh)}</span></label>`;}
  function question(en,zh,choices){return `<fieldset class="question"><legend>${b(en,zh)}</legend><div class="choice-grid">${choices}</div></fieldset>`;}
  function toast(en,zh=''){const el=$('toast');el.textContent=t(en,zh||en);el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),4500);}
  function save(){if(!state)return;try{localStorage.setItem(key(state.name,state.cls),JSON.stringify(state));$('saveStatus').textContent=t('Answers saved on this device.','答案已保存在这台设备上。');}catch{$('saveStatus').textContent=t('Device storage is full. Download a backup.','设备存储已满。请下载备份。');}}
  function cleanAnswers(data){return Object.fromEntries(Object.entries(data||{}).filter(([k,v])=>k.length<80&&typeof v==='string'&&v.length<=4000));}
  function cleanLegacy(s){return {answers:cleanAnswers(s.answers),route:(Array.isArray(s.route)?s.route:[]).filter(x=>Object.hasOwn(mission.moves,x)).slice(0,30),routeRuns:(Array.isArray(s.routeRuns)?s.routeRuns:[]).slice(-30).filter(r=>r&&Array.isArray(r.commands)&&r.commands.length<=30&&r.commands.every(x=>Object.hasOwn(mission.moves,x))).map(r=>({commands:[...r.commands],message:String(r.message||'').slice(0,1000),outcome:String(r.outcome||'').slice(0,50),final:Array.isArray(r.final)?r.final.filter(Number.isFinite).slice(0,2):[],at:String(r.at||'').slice(0,40)})),scratchFileName:String(s.scratchFileName||'').slice(0,200)};}
  function fresh(name,cls,language){return {version:3,name,cls,language,current:0,maxVisited:0,answers:{},plan:[],planHistory:[],tests:[],flags:[],scratchEvidence:null,startedAt:Date.now(),teacher:normal(name)==='teacher'};}
  function validate(wrapper){
    if(!wrapper||wrapper.app!==APP||!wrapper.state)throw Error('Choose a Year 6 checkpoint backup / 请选择六年级测评备份 / 6학년 백업 파일을 골라 주세요.');
    const s=wrapper.state;
    if(![1,2,3].includes(s.version)||typeof s.name!=='string'||!s.name.trim()||s.name.length>60||typeof s.cls!=='string'||!s.cls.trim()||s.cls.length>30||!s.answers||typeof s.answers!=='object'||Array.isArray(s.answers))throw Error('This backup is incomplete / 这个备份不完整 / 백업이 완전하지 않습니다.');
    if(s.version===1){const n=fresh(s.name,s.cls,s.language==='bi'?'bi':'en');n.legacy=cleanLegacy(s);n.migrated=true;return n;}
    if(!Number.isInteger(s.current)||s.current<0||s.current>=(s.version===2?previousCards.length:cards.length)||!Array.isArray(s.plan)||s.plan.length>30||!s.plan.every(x=>Object.hasOwn(mission.moves,x)))throw Error('This backup is incomplete / 这个备份不完整 / 백업이 완전하지 않습니다.');
    const n=fresh(s.name,s.cls,['bi','ko'].includes(s.language)?s.language:'en');
    // The card order changed. Preserve the work, not an index that could skip Scratch.
    n.current=s.version===2?0:s.current;n.migrated=s.version===2;
    n.maxVisited=s.version===2?0:Math.min(cards.length-1,Math.max(n.current,Number(s.maxVisited)||0));n.answers=cleanAnswers(s.answers);n.plan=[...s.plan];
    n.planHistory=(Array.isArray(s.planHistory)?s.planHistory:[]).filter(p=>p&&Array.isArray(p.moves)&&p.moves.length<=30&&p.moves.every(x=>Object.hasOwn(mission.moves,x))).slice(-20).map(p=>({moves:[...p.moves],at:String(p.at||'').slice(0,40)}));
    n.tests=(Array.isArray(s.tests)?s.tests:[]).slice(-10).filter(a=>a&&typeof a==='object').map(a=>cleanAnswers(a));
    n.flags=(Array.isArray(s.flags)?s.flags:[]).map(x=>x==='clear'?'words':x).filter(x=>cards.some(c=>c[0]===x));
    if(s.scratchEvidence&&typeof s.scratchEvidence==='object'){
      const e=s.scratchEvidence;n.scratchEvidence={filename:String(e.filename||'').slice(0,200),sprite:String(e.sprite||'').slice(0,100),scripts:(Array.isArray(e.scripts)?e.scripts:[]).slice(0,20).map(x=>Array.isArray(x)?x.filter(y=>typeof y==='string').map(y=>y.slice(0,500)).slice(0,100):[]),motionCount:Math.max(0,Math.min(1000,Number(e.motionCount)||0)),at:String(e.at||'').slice(0,40)};
    }
    if(s.legacy&&typeof s.legacy==='object')n.legacy=cleanLegacy(s.legacy);
    n.startedAt=Number.isFinite(s.startedAt)&&s.startedAt>0?s.startedAt:Date.now();return n;
  }
  function start(s){state=s;fileObject=null;returnToReview=false;languageClass(s.language);$('welcome').hidden=true;$('assessment').hidden=false;$('studentBadge').textContent=`${s.name} · ${s.cls}${s.teacher?' · Teacher preview':''}`;save();render(true);if(s.migrated)toast('Your earlier answers are safe. Start the new mission; earlier answers stay in your report.','旧答案已保留。请从新任务开始，旧答案仍会放入报告。');}
  document.querySelectorAll('input[name=language]').forEach(el=>el.addEventListener('change',()=>{if(!el.checked)return;languageClass(el.value);$('welcomeMap').innerHTML=mission.mapSvg(el.value);}));
  $('welcomeMap').innerHTML=mission.mapSvg();
  $('studentName').addEventListener('input',()=>{$('studentClass').required=normal($('studentName').value)!=='teacher';});
  $('startForm').addEventListener('submit',event=>{
    event.preventDefault();const name=$('studentName').value.trim(),cls=$('studentClass').value.trim()||(normal(name)==='teacher'?'Teacher preview':'');if(!name||!cls)return;
    const language=document.querySelector('input[name=language]:checked').value;
    let stored;try{stored=localStorage.getItem(key(name,cls))||localStorage.getItem(key(name,cls,APP));}catch{}
    if(stored){try{const s=validate({app:APP,state:JSON.parse(stored)});if(!confirm(t('Continue your saved work? Cancel will keep your saved answers unchanged.','继续之前保存的作答？取消后不会覆盖旧答案。',language)))return;s.language=language;start(s);return;}catch{$('startMessage').textContent=t('Saved work could not be opened. Use a JSON backup, or a different name to start.','无法打开保存的作答，请用 JSON 备份或另一个姓名开始。',language);return;}}
    start(fresh(name,cls,language));
  });
  $('restoreFile').addEventListener('change',async event=>{
    const file=event.target.files[0];if(!file)return;try{if(file.size>2_000_000)throw Error('Backup too large / 备份太大 / 백업 파일이 너무 큽니다.');const s=validate(JSON.parse(await file.text()));if(!confirm(`${s.name} (${s.cls})\n${t('Restore this learner’s backup? Saved work for this name and class will be replaced.','恢复此学生的备份？此姓名和班级的作答将被替换。',s.language)}`))return;$('studentName').value=s.name;$('studentClass').value=s.cls;document.querySelector(`input[name=language][value=${s.language}]`).checked=true;start(s);}catch(err){$('restoreMessage').textContent=err.message;}finally{event.target.value='';}
  });
  $('previous').onclick=()=>{if(state.current>0){state.current--;returnToReview=false;save();render(true);}};
  $('next').onclick=()=>{
    if(state.current>=cards.length-1||importBusy)return;
    const id=cards[state.current][0];if(!answered(id)&&!confirm(t('Some evidence is missing. Continue and come back later?','还有未完成的内容。先继续，稍后回来？')))return;
    if(id==='plan'&&state.plan.length){state.planHistory.push({moves:[...state.plan],at:new Date().toISOString()});state.planHistory=state.planHistory.slice(-20);}
    state.current=returnToReview?reviewIndex:state.current+1;returnToReview=false;state.maxVisited=Math.max(state.current,state.maxVisited);save();render(true);
  };
  $('flag').onclick=()=>{const id=cards[state.current][0];state.flags=state.flags.includes(id)?state.flags.filter(x=>x!==id):[...state.flags,id];save();render(false);toast('Your help note is saved. You can continue or ask your teacher.','已记录需要帮助。你可以继续，也可以向老师求助。');};
  $('changeLanguage').onchange=()=>{state.language=$('changeLanguage').value;languageClass(state.language);save();render(false);};
  $('saveBackup').onclick=downloadBackup;
  setInterval(()=>{if(state)$('elapsed').textContent=t('Work saved locally','作答保存在本机');},30000);
  const present=k=>typeof state.answers[k]==='string'&&state.answers[k].trim().length>0;
  function answered(id){switch(id){
    case 'files':return ['projectFile','folder','filename'].every(present);
    case 'words':return ['algorithmChoice','clearInstruction'].every(present);
    case 'jobs':return ['decompositionWord','jobOne','jobTwo'].every(present);
    case 'plan':return state.plan.length>0&&present('planWhy');
    case 'read':return ['predictX','predictY','readWhy'].every(present);
    case 'open':return state.answers.scratchOpened==='yes';
    case 'build-key':return state.answers.keyBuilt==='yes';
    case 'build':return state.answers.builtInScratch==='yes';
    case 'test':return state.tests.length>0;
    case 'create-extra':return present('extraChoice');
    case 'explain':return ['ipoInput','ipoProcess','ipoOutput','codeExplain'].every(present);
    case 'submit':return !!state.scratchEvidence;
    default:return true;
  }}
  function render(scroll){
    const [id,en,zh,phase]=cards[state.current];
    $('progressText').textContent=t(`Card ${state.current+1} of ${cards.length} · ${phases[phase][0]}`,`第 ${state.current+1} 张，共 ${cards.length} 张 · ${phases[phase][1]}`);$('progress').value=(state.maxVisited+1)/cards.length*100;
    $('changeLanguage').value=state.language;
    $('journeyList').innerHTML=phases.map(([p,z],index)=>{const first=cards.findIndex(c=>c[3]===index),available=state.teacher||first<=state.maxVisited;return `<li class="${index===phase?'current':''}">${available?`<button type="button" data-stage="${first}" ${index===phase?'aria-current="step"':''}>${index+1}. ${b(p,z)}</button>`:`${index+1}. ${b(p,z)}`}</li>`;}).join('');
    $('journeyList').querySelectorAll('[data-stage]').forEach(button=>button.onclick=()=>{state.current=+button.dataset.stage;returnToReview=false;save();render(true);});
    $('missionStrip').innerHTML=b('<strong>Your mission:</strong> START → key → portal. Plan here. Build and test in Scratch.','<strong>你的任务：</strong>起点 → 钥匙 → 传送门。在这里计划，在 Scratch 编程并测试。');
    $('taskCard').innerHTML=`<p class="card-kicker">${b(phases[phase][0].toUpperCase(),phases[phase][1])}</p><h1>${b(en,zh)}</h1>${content(id)}`;
    if(id==='open'||id==='build-key'||id==='build')$('taskCard').insertAdjacentHTML('beforeend',interfaceGuide());
    $('previous').disabled=state.current===0;$('previous').innerHTML=b('← Back','← 返回');$('next').hidden=id==='submit';$('next').disabled=importBusy;$('next').innerHTML=b(returnToReview?'Return to review →':id==='read'?'Next: open Scratch →':id==='review'?'Save and hand in →':'Save & continue →',returnToReview?'回到检查页 →':id==='read'?'下一步：打开 Scratch →':id==='review'?'保存并提交 →':'保存并继续 →');
    $('flag').hidden=['guide','review','submit'].includes(id);$('flag').innerHTML=b(state.flags.includes(id)?'Help noted ✓':'I need help',state.flags.includes(id)?'已记录求助 ✓':'我需要帮助');
    bindCard(id);if(scroll){$('taskCard').scrollIntoView({block:'start',behavior:'auto'});$('taskCard').focus({preventScroll:true});}
  }
  function map(){return `${mission.mapSvg(state.language)}<div class="mission-key"><span>${b('1 square = 40 Scratch steps','1 格 = 40 个 Scratch 步')}</span><span>${b('Striped squares = walls','斜线格子 = 墙')}</span></div>`;}
  function interfaceGuide(){return `<details class="interface-guide"><summary>${b('Show the real Scratch mission: blocks, stage and x/y boxes','查看真实 Scratch 任务：积木、舞台与 x/y 数字框')}</summary><p>${b('Choose Explorer below the stage. The x and y boxes are beside its name. Motion blocks are in the blue category on the left. This is the same starter you downloaded.','在舞台下选择 Explorer。x 和 y 数字框在角色名称旁。运动积木在左边的蓝色类别中。这就是你下载的模板。')}</p><img class="scratch-guide" src="assets/scratch-mission-guide.jpg" alt="The actual Explorer mission loaded in Scratch: Motion palette on left, two reset blocks in the centre, matching map on right, Explorer x minus 160 and y minus 80 below the stage."></details>`;}
  function routeList(){return state.plan.length?`<ol class="command-list">${state.plan.map((cmd,index)=>`<li><span>${index+1}. ${b(...moveNames[cmd])}</span><span class="command-edit"><button type="button" data-up="${index}" aria-label="${esc(t('Move earlier','向前移动'))}" ${index===0?'disabled':''}>↑</button><button type="button" data-down="${index}" aria-label="${esc(t('Move later','向后移动'))}" ${index===state.plan.length-1?'disabled':''}>↓</button><button type="button" data-remove="${index}" aria-label="${esc(t('Remove move','删除指令'))}">×</button></span></li>`).join('')}</ol>`:`<p class="notice">${b('Add your first move. This is a plan, not a running Scratch program.','添加第一步。这是计划，还不是运行中的 Scratch 程序。')}</p>`;}
  function shortRoute(){return state.plan.map(cmd=>t(...moveNames[cmd])).join(' · ');}
  function simplePath(){return `<svg class="mission-map" viewBox="0 0 480 120" role="img" aria-label="Robot in square one. Star in square three. Wall in square five."><defs><pattern id="simpleHatch" width="8" height="8" patternUnits="userSpaceOnUse"><rect width="8" height="8" fill="#ddd"/><path d="M0 8L8 0" stroke="#777"/></pattern></defs>${[0,1,2,3,4].map(i=>`<rect x="${i*96}" y="0" width="96" height="85" fill="${i===4?'url(#simpleHatch)':i===2?'#fff5d0':'#fff'}" stroke="#829b8c"/>`).join('')}<circle cx="48" cy="42" r="22" fill="#4c97ff"/><circle cx="40" cy="36" r="3" fill="white"/><circle cx="56" cy="36" r="3" fill="white"/><path d="m240 15 8 17 19 3-14 13 3 20-16-9-16 9 3-20-14-13 19-3Z" fill="#ffd75c" stroke="#956b11"/><g font-family="Arial,sans-serif" font-size="14" text-anchor="middle" fill="#18352b"><text x="48" y="109">${state.language==='ko'?'START / 출발':state.language==='bi'?'START / 起点':'START'}</text><text x="240" y="109">${state.language==='ko'?'STAR / 별':state.language==='bi'?'STAR / 星星':'STAR'}</text><text x="432" y="109">${state.language==='ko'?'WALL / 벽':state.language==='bi'?'WALL / 墙':'WALL'}</text></g></svg>`;}
  function codingPanel(){return `<div class="task-grid"><div>${map()}<h2>${b('My route','我的路线')}</h2><p class="saved-route">${esc(shortRoute()||t('No moves saved yet. Return to Plan.','还没有保存步骤。请回到计划。'))}</p></div><div><h2>${b('Choose your moves','选择移动')}</h2><div class="movement-reference"><div>${b('Right → change x by a positive number','向右 → change x by 正数')}</div><div>${b('Left → change x by a negative number','向左 → change x by 负数')}</div><div>${b('Up → change y by a positive number','向上 → change y by 正数')}</div><div>${b('Down → change y by a negative number','向下 → change y by 负数')}</div></div><p class="small-note">${b('One square is 40 steps. You choose how many squares.','一格是 40 步。自己选择格数。')}</p><details><summary>${b('Show a real block example','显示真实积木例子')}</summary><img class="code-photo" src="assets/extension-left-blocks.jpg" alt="Scratch blocks: go to x 100 y 40, then change x by minus 40"><p>${b('Example only: −40 moves left one square. Use your own plan, not these starting coordinates.','仅作例子：−40 表示向左一格。使用自己的计划，不要照抄这个起点坐标。')}</p></details></div></div>`;}
  function content(id){switch(id){
    case 'guide':return `<p class="instruction">${b('Create a Scratch journey: START → key → portal. Avoid the walls.','编写 Scratch 路线：起点 → 钥匙 → 传送门。避开墙。')}</p><div class="task-grid"><div>${map()}</div><div><h2>${b('Your project today','今天的作品')}</h2><ul class="requirements"><li>${b('Plan two parts.','计划两个部分。')}</li><li>${b('Build both parts in Scratch.','在 Scratch 编写两个部分。')}</li><li>${b('Run, check and improve your code.','运行、检查并改进代码。')}</li></ul><p class="small-note">${b('Your ideas and code matter. Short answers are enough.','思路和代码很重要。简短回答即可。')}</p></div></div><div class="learning-grid"><div><strong>${b('Knowledge: remember','知识：记住')}</strong><p>${b('Use the words you learned.','使用学过的词语。')}</p></div><div><strong>${b('Skills: create','技能：创造')}</strong><p>${b('Make and test your code.','编写并测试代码。')}</p></div><div><strong>${b('Understanding: explain','理解：解释')}</strong><p>${b('Say why your code works.','说出代码为什么有效。')}</p></div></div><div class="language-permission">${b('Think, talk and answer in English, Mandarin, Korean, or a mix. Keep Scratch block names beside your ideas.','可以用英语、中文、韩语或混合语言思考、交流和作答。表达思路时保留 Scratch 积木名称。')}</div><details><summary>${b('Help using these cards','卡片操作帮助')}</summary><p>${b('Use Back or Save & continue. You can return to unfinished work.','使用返回或保存并继续。可以回来完成遗漏内容。')}</p><button class="secondary" id="practiceButton" type="button">${b('Try a button','试按按钮')}</button><p class="practice-result" id="practiceResponse" role="status"></p></details>`;
    case 'words':return `<p class="instruction">${b('Quick warm-up: look at the plan and blocks.','快速热身：看计划和积木。')}</p><div class="task-grid"><section class="sample-plan"><h2>${b('A: written steps','A：文字步骤')}</h2><p>${b('Start at the entrance. Move up three squares. Stop.','从入口开始。向上移动三格。停下。')}</p></section><section><h2>${b('B: Scratch blocks','B：Scratch 积木')}</h2><img class="code-photo" src="assets/algorithm-program-blocks.png" alt="Scratch green flag and go to position blocks"></section></div>${question('Which is the algorithm written as a plan?','哪个是用计划形式写出的算法？',choice('algorithmChoice','a','A: written steps','A：文字步骤')+choice('algorithmChoice','b','B: Scratch blocks','B：Scratch 积木'))}<h2>${b('Give the robot one clear move','给机器人一条明确移动指令')}</h2>${simplePath()}${field('clearInstruction','Reach the star. Write a direction and number of squares.','到达星星。写出方向和格数。',inp('clearInstruction','Move...','向……移动……格'))}<details><summary>${b('Need a reminder?','需要提示？')}</summary><p>${b('An algorithm is a plan with ordered steps. A program is code a computer can run. A clear move says where and how far.','算法是按顺序排列的步骤计划。程序是电脑可运行的代码。明确移动要说明方向和距离。')}</p><p>${b('For a different route: “Move left 4 squares.” Use YOUR picture.','另一条路线的例子：“向左移动 4 格”。请根据你的图作答。')}</p></details>`;
    case 'read':return `<p class="instruction">${b('Read from top to bottom. Where will this sprite stop?','从上到下读积木。角色会停在哪里？')}</p><div class="task-grid"><img class="code-photo" src="assets/read-code.png" alt="Scratch: when green flag clicked; go to x minus 160 y minus 100; change x by 120"><div><div class="field-row">${field('predictX','Final x','最后的 x',inp('predictX','x','x','number'))}${field('predictY','Final y','最后的 y',inp('predictY','y','y','number'))}</div>${field('readWhy','Which coordinate stays the same? Why?','哪个坐标保持不变？为什么？',inp('readWhy','... stays the same because...','……不变，因为……'))}</div></div><p class="small-note">${b('A warm-up, not your mission code. Next: open Scratch and create your own.','这是热身，不是任务代码。下一步：打开 Scratch，编写自己的代码。')}</p>`;
    case 'open':return `<div class="task-callout">${b('Open Scratch now. Create your program there.','现在打开 Scratch。在那里制作程序。')}</div><div class="submit-actions"><a class="primary" href="assets/Year6_Explorer_Mission_Starter.sb3" download>${b('1. Download mission file (.sb3)','1. 下载任务文件（.sb3）')}</a><a class="primary" href="https://scratch.mit.edu/projects/editor/" target="_blank" rel="noopener noreferrer">${b('2. Open Scratch ↗','2. 打开 Scratch ↗')}</a></div><ol class="step-list"><li><span>${b('Choose File → Load from your computer. Open the downloaded mission.','选择 File（文件）→ Load from your computer（从电脑上传）。打开下载的任务。')}</span></li><li><span>${b('Choose Explorer. Press the green flag: it should reset at START.','选择 Explorer。按绿旗：它应该回到起点。')}</span></li><li><span>${b('Keep Scratch open. Return here for your next small task.','保持 Scratch 打开。回到这里查看下一个小任务。')}</span></li></ol>${question('Ready to create?','准备好编程了吗？',choice('scratchOpened','yes','My mission is open in Scratch.','任务已在 Scratch 打开。')+choice('scratchOpened','help','Help me open the file.','请帮我打开文件。'))}<details><summary>${b('Continuing at home?','在家继续？')}</summary><p>${b('Load your own saved .sb3 in Scratch. JSON restores these cards only.','在 Scratch 载入自己的 .sb3。JSON 只恢复这些卡片。')}</p></details>`;
    case 'jobs':return `<p class="instruction">${b('Name two jobs for your mission. You will code each job next.','写出任务的两个部分。接着编写每部分的代码。')}</p><div class="task-grid"><div>${map()}</div><div>${field('jobOne','Part 1: reach...','第一部分：到达……',inp('jobOne','First, Explorer...','首先，探索者……'))}${field('jobTwo','Part 2: reach...','第二部分：到达……',inp('jobTwo','Then, Explorer...','然后，探索者……'))}${question('Breaking a big problem into smaller parts is called...','把大问题拆成小部分叫……',choice('decompositionWord','decomposition','Decomposition','分解')+choice('decompositionWord','debugging','Debugging','调试')+choice('decompositionWord','output','Output','输出'))}</div></div><details><summary>${b('Need a reminder?','需要提示？')}</summary><p>${b('Decomposition means smaller jobs. A different mission might have “reach the bridge” and “cross the bridge”. Choose jobs for YOUR map.','分解就是拆成小任务。另一任务可拆成“到达桥边”和“过桥”。请根据你的地图选择任务。')}</p></details>`;
    case 'plan':return `<p class="instruction">${b('Add moves for START → key → portal. One move = one square. Avoid the walls.','添加起点 → 钥匙 → 传送门的移动步骤。一步一格，避开墙。')}</p><div class="task-grid"><div>${map()}</div><div><h2>${b('My route','我的路线')}</h2><div class="plan-buttons">${Object.entries(moveNames).map(([cmd,names])=>`<button type="button" class="secondary" data-move="${cmd}">${b(...names)}<small> · ${b('1 square','1 格')}</small></button>`).join('')}</div>${routeList()}<p class="small-note">${b('↑ ↓ reorder. × removes a move. Test in Scratch.','↑ ↓ 调整顺序。× 删除。在 Scratch 中测试。')}</p></div></div>${field('planWhy','Why visit the key first?','为什么先到钥匙？',inp('planWhy','The key...','钥匙……'))}`;
    case 'build-key':return `<div class="task-callout">${b('Create in Scratch · about 10 minutes','在 Scratch 编程 · 约 10 分钟')}</div><p class="instruction">${b('Code Part 1: START → key. Choose your own movement blocks and numbers.','编写第一部分：起点 → 钥匙。自己选择移动积木和数字。')}</p>${codingPanel()}<ol class="step-list"><li><span>${b('Keep the two starter blocks. Add your moves underneath.','保留模板的两个积木。在下面添加移动积木。')}</span></li><li><span>${b('Press the green flag. Reach the key without crossing a wall.','按绿旗。不穿墙到达钥匙。')}</span></li><li><span>${b('Change one move if needed. At the key: x = −40, y = 40.','需要时修改一个移动。钥匙位置：x = −40，y = 40。')}</span></li></ol>${question('After trying my code...','试过代码后……',choice('keyBuilt','yes','I coded and tested the first part.','我已编写并测试第一部分。')+choice('keyBuilt','help','I tried, and need help with one move.','我试过了，需要一个移动步骤的帮助。'))}`;
    case 'build':return `<div class="task-callout">${b('Create in Scratch · about 10 minutes','在 Scratch 编程 · 约 10 分钟')}</div><p class="instruction">${b('Code Part 2: key → portal. Keep Part 1 and add to it.','编写第二部分：钥匙 → 传送门。保留第一部分，在后面添加。')}</p>${codingPanel()}<ol class="step-list"><li><span>${b('After Part 1, add “wait 2 seconds” from Control to see the key stop.','第一部分后，加 Control（控制）里的“等待 2 秒”，方便看到钥匙位置。')}</span></li><li><span>${b('Add portal moves below the wait. Do not reset to START again.','在等待后添加到传送门的移动。不要再次回到起点。')}</span></li><li><span>${b('Run both parts. At the portal: x = 160, y = 40.','运行两个部分。传送门位置：x = 160，y = 40。')}</span></li></ol>${question('After creating both parts...','编写两个部分后……',choice('builtInScratch','yes','My whole program is ready to test.','完整程序已准备好测试。')+choice('builtInScratch','help','I tried both parts and need help.','我试过两个部分，需要帮助。'))}<details class="pitstop"><summary>${b('Quick learning pitstop — not graded','快速学习检查 — 不计分')}</summary><div class="choice-grid">${choice('learningPhase','new','New learning: I am trying something new.','新学习：我在尝试新内容。')}${choice('learningPhase','consolidating','Consolidating: practice is helping.','巩固：练习让我更熟练。')}${choice('learningPhase','easy','Treading water: I need more challenge.','原地踏步：我需要更多挑战。')}${choice('learningPhase','help','Drowning: I need one small step of help.','感到吃力：我需要一个小步骤的帮助。')}</div><p class="small-note" id="phaseHelp"></p></details>`;
    case 'create-extra':return `<p class="instruction">${b('Finished the main mission? Choose something new to build. Save a second .sb3 so you keep your main version.','主要任务完成了吗？选择一个新挑战。另存第二个 .sb3，保留原来的版本。')}</p>${question('My next creation','我的下一个创作',choice('extraChoice','return','A: code a return journey','A：编写返回路线')+choice('extraChoice','target','B: design my own target','B：设计自己的目标')+choice('extraChoice','skip','Not today: go to Explain','今天不做：进入解释'))}<div class="task-grid"><div><img class="code-photo" src="assets/extension-left-blocks.jpg" alt="Scratch: when green flag clicked; go to x 100 y 40; change x by minus 40"><p class="small-note">${b('Example only: −40 moves left one square. Use your own plan, not these starting coordinates.','仅作例子：−40 表示向左一格。使用自己的计划，不要照抄这个起点坐标。')}</p></div><div><details><summary>${b('A: code a return journey','A：编写返回路线')}</summary><ol class="step-list"><li><span>${b('Read your route backwards. Swap right/left and up/down.','倒着读路线。左右、上下方向对调。')}</span></li><li><span>${b('Add return moves after the portal. Do not use “go to START” to jump back.','在传送门后添加返回移动。不要用“移到起点”直接跳回。')}</span></li><li><span>${b('Test it: key → portal → START (−160, −80), without crossing walls.','测试：钥匙 → 传送门 → 起点（−160，−80），不穿墙。')}</span></li></ol></details><details><summary>${b('B: design my own target','B：设计自己的目标')}</summary><ol class="step-list"><li><span>${b('In Scratch, paint a small target sprite. Choose a clear name and an empty grid square.','在 Scratch 绘制一个小目标角色。起个清楚的名字，选择一个空格。')}</span></li><li><span>${b('Set the target’s x and y boxes to multiples of 40, inside the map and not on a wall. Record your coordinates below.','把目标的 x 和 y 设为 40 的倍数，放在地图内，不在墙上。在下面记录坐标。')}</span></li><li><span>${b('Select Explorer. After the portal code, add moves to reach YOUR target. Run and check the target coordinates.','选择 Explorer。在传送门代码后添加移动，到达自己的目标。运行并检查目标坐标。')}</span></li></ol><div class="field-row">${field('targetX','My target x','目标 x',inp('targetX','x','x','number'))}${field('targetY','My target y','目标 y',inp('targetY','y','y','number'))}</div></details></div></div>${field('extensionNote','What did you create? What happened when you tested it?','你创作了什么？测试结果怎样？',inp('extensionNote','Optional: a short note','可选：简短说明'))}`;
    case 'explain':return `<p class="instruction">${b('Use your own program. Four short answers are enough. Any language or a mix is welcome.','用自己的程序作答。四个简短答案即可。可以用任何语言或混合语言。')}</p>${field('ipoInput','Input: what starts your code?','输入：什么启动代码？',inp('ipoInput','I click...','我点击……'))}${field('ipoProcess','Process: what does your code do?','处理：代码做什么？',inp('ipoProcess','My code...','我的代码……'))}${field('ipoOutput','Output: what happens on the stage?','输出：舞台上发生什么？',inp('ipoOutput','I see...','我看到……'))}${field('codeExplain','Pick one movement block. Why did you choose its number?','选择一个移动积木。为什么选这个数字？',inp('codeExplain','My ... block uses ... because...','我的……积木使用……因为……'))}<details><summary>${b('Prefer to explain aloud?','想用口头解释？')}</summary><p>${b('Tell your teacher in your preferred language. Ask them to record your idea here.','用你喜欢的语言告诉老师，请老师在这里记录你的思路。')}</p></details>`;
    default:return previousContent(id);
  }}
  function previousContent(id){switch(id){
    case 'files':return `<p class="instruction">${b('You want to open and change your Scratch program next week. Choose the file and folder you would use.','你想在下周重新打开并修改 Scratch 程序。选择要用的文件和文件夹。')}</p><div class="file-icons"><div class="file-icon"><strong>PDF</strong></div><div class="file-icon"><strong>SB3</strong></div><div class="file-icon"><strong>JSON</strong></div></div>${question('1. Which file lets you open the Scratch code?','1. 哪个文件可以打开 Scratch 代码？',choice('projectFile','pdf','PDF','PDF')+choice('projectFile','sb3','SB3','SB3')+choice('projectFile','json','JSON','JSON'))}${question('2. Which folder helps you find your Computing work?','2. 哪个文件夹方便你找到计算课的作业？',choice('folder','computing','Documents → Year 6 Computing → My name','文档 → 六年级计算 → 我的姓名')+choice('folder','photos','Photos → Holiday pictures','照片 → 假期照片')+choice('folder','random','Downloads → Mixed old files','下载 → 各种旧文件'))}${field('filename','3. Write a clear name for your mission file. Include its file ending.','3. 给任务文件起一个明确名称，并写出文件扩展名。',inp('filename','Your file name','你的文件名'))}<p class="small-note">${b('Use the topic and your name. A short name is enough.','使用任务主题和你的姓名。简短名称就可以。')}</p>`;
    case 'test':return `<p class="instruction">${b('Run your code in Scratch. Watch the key and portal. Record this test.','在 Scratch 运行。观察钥匙和传送门，记录这次测试。')}</p><div class="task-grid"><div>${map()}<ul class="requirements"><li>${b('Starts again at START','重新从起点开始')}</li><li>${b('Visits the key before the portal','先到钥匙，再到传送门')}</li><li>${b('Does not go through a wall','不穿墙')}</li></ul></div><div>${question('What happened in this run?','这次运行发生了什么？',choice('testResult','worked','It visited the key, then reached the portal.','先到钥匙，再到传送门。')+choice('testResult','key','It missed the key.','错过了钥匙。')+choice('testResult','wall','It went through a wall.','穿过了墙。')+choice('testResult','finish','It stopped somewhere else.','停在其他地方。')+choice('testResult','none','It did not move as expected.','没有按预期移动。'))}<div class="field-row">${field('testX','Actual final x','实际最后的 x',inp('testX','x','x','number'))}${field('testY','Actual final y','实际最后的 y',inp('testY','y','y','number'))}</div></div></div>${field('testNote','What will you change? If it worked, what showed you that it worked?','你要改什么？如果成功了，什么现象说明它成功？',area('testNote','I noticed... so...','我发现……所以……'))}<button class="primary" id="recordTest" type="button">${b('Save this test','保存这次测试')}</button><p id="testStatus" class="small-note" role="status"></p><div id="testHistory">${testHistory()}</div><div class="notice">${b('Try again: change one move if needed, then save another test. A first-time success? Run again to check it.','再试一次：需要时修改一个移动，再保存测试。第一次就成功？再运行一次确认。')}</div>`;
    case 'review':return `<p class="instruction">${b('Check for missing work. “Recorded” is not a mark. Your teacher will run your Scratch file.','检查遗漏内容。“已记录”不是分数。老师会运行你的 Scratch 文件。')}</p><div class="review-list">${cards.slice(1,reviewIndex).map(([cid,en,zh],i)=>`<div class="review-row"><strong>${b(en,zh)}</strong><span class="pill ${answered(cid)?'done':''}">${cid==='create-extra'&&state.answers.extraChoice==='skip'?b('Skipped (optional)','已跳过（可选）'):b(answered(cid)?'Recorded':'Not finished',answered(cid)?'已记录':'未完成')}</span><button class="text-button" type="button" data-jump="${i+1}">${b('Open','打开')}</button></div>`).join('')}</div><div class="warning">${b('Next: choose your saved .sb3. Your report will include its code details. Upload the actual file in Teams too.','下一步：选择保存的 .sb3。报告会包含代码信息。还要在 Teams 上传实际文件。')}</div>`;
    case 'submit':return `<p class="instruction">${b('Hand in two files: your report and your Scratch program. A backup is only for continuing later.','提交两个文件：报告和 Scratch 程序。备份只用于以后继续。')}</p><div class="file-icons"><div class="file-icon"><strong>▤ PDF</strong><p>${b('Your plan, answers, tests and explanation','你的计划、答案、测试和解释')}</p></div><div class="file-icon"><strong>▣ SB3</strong><p>${b('Your Scratch code — your teacher can run it','你的 Scratch 代码 — 老师可以运行')}</p></div><div class="file-icon"><strong>↻ JSON</strong><p>${b('Your webpage backup — not your Scratch file','网页备份 — 不是 Scratch 文件')}</p></div></div><ol class="step-list"><li><span>${b('In Scratch: File → Save to your computer. Use a clear name, for example Y6_Explorer_Aisha.sb3. Replace Aisha with your name.','在 Scratch：File（文件）→ Save to your computer（保存到电脑）。例如 Y6_Explorer_Aisha.sb3，把 Aisha 换成你的姓名。')}</span></li><li><span>${b('Choose that saved .sb3 below. The website reads its code details on this device. Nothing is uploaded here.','在下面选择保存的 .sb3。网页只在这台设备读取代码信息，不在这里上传。')}</span></li><li><span>${b('Save your PDF report. Open it and check your name and work.','保存 PDF 报告。打开检查姓名和作答。')}</span></li><li><span>${b('In Teams: open the checkpoint assignment → Add work → upload BOTH the PDF and .sb3 → Turn in. Check both attachments before you finish.','在 Teams：打开测评作业 → Add work（添加作业）→ 上传 PDF 和 .sb3 两个文件 → Turn in（提交）。结束前检查两个附件。')}</span></li></ol><div class="file-picker"><label class="field-label" for="scratchFile">${b('Choose my saved Scratch file (.sb3)','选择保存的 Scratch 文件（.sb3）')}</label><input id="scratchFile" type="file" accept=".sb3"><p id="scratchFileStatus" class="small-note" role="status">${evidenceStatus()}</p></div><div class="submit-actions"><button class="primary" id="downloadPdf" type="button">${b('Save my PDF report','保存我的 PDF 报告')}</button><button class="secondary" id="printPdf" type="button">${b('Print / Save as PDF','打印 / 另存为 PDF')}</button><button class="secondary" id="downloadBackup2" type="button">${b('Download backup (.json)','下载备份（.json）')}</button></div><p id="pdfStatus" class="small-note" role="status"></p><p class="small-note">${b('For Mandarin or Korean, choose Save as PDF in the print window. No screenshots needed.','中文或韩语报告：在打印窗口选择另存为 PDF。不需要截图。')}</p>${question('My final check','我的最后检查',choice('submission','ready','I have both files ready to upload in Teams.','两个文件都已准备好上传 Teams。')+choice('submission','submitted','I uploaded both files and pressed Turn in.','已上传两个文件并点击提交。')+choice('submission','help','I need help saving or handing in.','保存或提交时需要帮助。'))}`;
  }}
  const resultLabels={worked:['Key, then portal','先到钥匙，再到传送门'],key:['Missed the key','错过钥匙'],wall:['Crossed a wall','穿过墙'],finish:['Stopped elsewhere','停在其他地方'],none:['Did not move as expected','移动不符合预期']};
  function testHistory(){return state.tests.map((test,i)=>`<section class="test-history"><strong>${b(`Saved test ${i+1}`,`已保存测试 ${i+1}`)}</strong><p>${esc(t(...(resultLabels[test.result]||[test.result,test.result])))} · (${esc(test.x)}, ${esc(test.y)})</p><p>${esc(test.note)}</p></section>`).join('');}
  function bindCard(id){
    $('taskCard').querySelectorAll('[data-field]').forEach(el=>el.addEventListener(el.type==='radio'?'change':'input',()=>{state.answers[el.dataset.field]=el.value;save();if(el.dataset.field==='learningPhase')phaseHelp();}));
    $('practiceButton')?.addEventListener('click',()=>{$('practiceResponse').innerHTML=b('The button worked. Next, use Save & continue below.','按钮有效。接着按下方的“保存并继续”。');});
    if(id==='plan'){
      const edit=fn=>{fn();save();const y=window.scrollY;render(false);window.scrollTo(0,y);};
      $('taskCard').querySelectorAll('[data-move]').forEach(btn=>btn.onclick=()=>{if(state.plan.length>=30)return toast('Use at most 30 moves. Remove one before adding more.','最多 30 步，请先删除再添加。');edit(()=>state.plan.push(btn.dataset.move));});
      $('taskCard').querySelectorAll('[data-up]').forEach(btn=>btn.onclick=()=>edit(()=>{const i=+btn.dataset.up;if(i>0)[state.plan[i-1],state.plan[i]]=[state.plan[i],state.plan[i-1]];}));
      $('taskCard').querySelectorAll('[data-down]').forEach(btn=>btn.onclick=()=>edit(()=>{const i=+btn.dataset.down;if(i<state.plan.length-1)[state.plan[i],state.plan[i+1]]=[state.plan[i+1],state.plan[i]];}));
      $('taskCard').querySelectorAll('[data-remove]').forEach(btn=>btn.onclick=()=>edit(()=>state.plan.splice(+btn.dataset.remove,1)));
    }
    if(id==='build')phaseHelp();
    if(id==='test')$('recordTest').onclick=()=>{
      if(!['testResult','testX','testY','testNote'].every(present)){$('testStatus').textContent=t('Choose a result, enter both coordinates and add a short note.','请选择结果、填两个坐标，并写简短说明。');return;}
      const test={result:state.answers.testResult,x:state.answers.testX,y:state.answers.testY,note:state.answers.testNote,at:new Date().toISOString(),plan:state.plan.join(',')};state.tests.push(test);state.tests=state.tests.slice(-10);save();$('testHistory').innerHTML=testHistory();$('testStatus').textContent=t('Test saved. If you run again, update these boxes and save another test.','测试已保存。再运行后，更新这些框并保存另一轮测试。');
    };
    if(id==='review')$('taskCard').querySelectorAll('[data-jump]').forEach(btn=>btn.onclick=()=>{state.current=+btn.dataset.jump;returnToReview=true;save();render(true);});
    if(id==='submit'){
      $('scratchFile').onchange=async event=>{const file=event.target.files[0];if(!file)return;importBusy=true;$('next').disabled=true;$('downloadPdf').disabled=true;$('printPdf').disabled=true;$('scratchFileStatus').textContent=t('Reading your saved code…','正在读取保存的代码……');try{const evidence=await inspectScratch(file);state.scratchEvidence=evidence;fileObject=file;save();$('scratchFileStatus').innerHTML=evidenceStatus();}catch(err){fileObject=null;$('scratchFileStatus').textContent=err.message;}finally{importBusy=false;$('next').disabled=false;$('downloadPdf').disabled=false;$('printPdf').disabled=false;event.target.value='';}};
      $('downloadPdf').onclick=downloadPdf;$('printPdf').onclick=printPdf;$('downloadBackup2').onclick=downloadBackup;
    }
  }
  function phaseHelp(){if(!$('phaseHelp'))return;const messages={new:['Try one movement, then test it.','先试一个移动，再测试。'],consolidating:['Use your plan and check the two goals.','使用计划，检查两个目标。'],easy:['Finish the main mission first. Then try the optional return journey.','先完成主要任务，再尝试可选的返回路线。'],help:['Ask for help with one small part: opening Scratch, finding a block, or checking a move.','请人帮一个小部分：打开 Scratch、找积木或检查一步移动。']};$('phaseHelp').textContent=messages[state.answers.learningPhase]?t(...messages[state.answers.learningPhase]):'';}
  async function inspectScratch(file){
    if(!/\.sb3$/i.test(file.name)||file.size>8_000_000)throw Error(t('Choose a Scratch .sb3 file smaller than 8 MB.','请选择小于 8 MB 的 Scratch .sb3 文件。'));
    if(!window.JSZip)throw Error(t('The file reader did not load. Keep the file and upload it to Teams.','文件读取器未载入。请保留文件并上传 Teams。'));
    const zip=await window.JSZip.loadAsync(await file.arrayBuffer());const entry=zip.file('project.json');
    if(!entry||entry._data?.uncompressedSize>2_000_000)throw Error(t('This is not a supported Scratch project.','这不是受支持的 Scratch 项目。'));
    const project=JSON.parse(await entry.async('string'));if(!Array.isArray(project.targets))throw Error(t('This file does not contain Scratch code.','这个文件没有 Scratch 代码。'));
    const sprites=project.targets.filter(target=>!target.isStage&&target.blocks&&typeof target.blocks==='object');const sprite=sprites.find(s=>s.name==='Explorer')||sprites.find(s=>Object.values(s.blocks).some(block=>String(block.opcode).startsWith('motion_')))||sprites[0];
    if(!sprite)throw Error(t('No sprite code found. Save your mission from Scratch first.','没有找到角色代码。请先从 Scratch 保存任务。'));
    const blocks=sprite.blocks;const scripts=[];
    function literal(input){if(!Array.isArray(input))return '?';const v=input[1];if(Array.isArray(v))return String(v[1]).slice(0,150);if(typeof v==='string'&&blocks[v])return `[${String(blocks[v].opcode).slice(0,80)}]`;return '?';}
    const top=Object.entries(blocks).filter(([,block])=>block.topLevel&&!block.shadow).slice(0,20);
    for(const [startId] of top){let id=startId;const seen=new Set(),lines=[];while(id&&blocks[id]&&!seen.has(id)&&lines.length<100){seen.add(id);const block=blocks[id],i=block.inputs||{},op=block.opcode;
      const known={event_whenflagclicked:'when green flag clicked',motion_gotoxy:`go to x: ${literal(i.X)} y: ${literal(i.Y)}`,motion_changexby:`change x by ${literal(i.DX)}`,motion_changeyby:`change y by ${literal(i.DY)}`,motion_setx:`set x to ${literal(i.X)}`,motion_sety:`set y to ${literal(i.Y)}`,motion_movesteps:`move ${literal(i.STEPS)} steps`,control_wait:`wait ${literal(i.DURATION)} seconds`,looks_sayforsecs:`say ${literal(i.MESSAGE)} for ${literal(i.SECS)} seconds`,looks_say:`say ${literal(i.MESSAGE)}`};
      lines.push(known[op]||`${String(op).slice(0,80)} ${Object.entries(i).map(([k,v])=>`${k}: ${literal(v)}`).join(' ')}`);id=block.next;
    }scripts.push(lines);}
    return {filename:file.name,sprite:String(sprite.name).slice(0,100),scripts,motionCount:Object.values(blocks).filter(block=>String(block.opcode).startsWith('motion_')).length,at:new Date().toISOString()};
  }
  function evidenceStatus(){const e=state.scratchEvidence;if(!e)return b('No Scratch file chosen yet.','尚未选择 Scratch 文件。');return `<strong>${esc(e.filename)} · ${esc(e.sprite)}</strong><br>${b(`Read ${e.motionCount} Motion blocks.`,`已读取 ${e.motionCount} 个运动积木。`)}${fileObject?b('File read on this device.','已在本机读取文件。'):b('Earlier code record restored; choose your latest file again.','已恢复旧代码记录，请重新选择最新文件。')}${e.motionCount<=1?b('This may be the unchanged starter. Save YOUR journey in Scratch first.','这可能还是未修改的模板。请先在 Scratch 保存自己的路线。'):''}${b('Your teacher will run your program. This is not an automatic mark.','老师会运行你的程序。这不是自动评分。')}`;}
  function download(name,type,data){const blob=new Blob([data],{type}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function stem(){const safe=`Y6_Explorer_${state.cls}_${state.name}`.replace(/[^\p{L}\p{N}_-]+/gu,'_').slice(0,100);return safe||'Y6_Explorer_Report';}
  function downloadBackup(){if(!state)return;download(`${stem()}_Backup.json`,'application/json',JSON.stringify({app:APP,exportedAt:new Date().toISOString(),state},null,2));toast('Backup saved. Save your .sb3 in Scratch too — it is not inside this backup.','备份已保存。还要在 Scratch 保存 .sb3，它不包含在这个备份中。');}
  function reportSections(){
    const a=state.answers;const line=(en,zh,key)=>`${t(en,zh)}: ${a[key]||t('Not recorded','未记录')}`;
    const sections=[
      {title:t('Knowledge: files and instructions','知识：文件与指令'),lines:[line('Scratch file type','Scratch 文件类型','projectFile'),line('Folder choice','文件夹选择','folder'),line('My filename','我的文件名','filename'),line('Clear instruction','明确指令','clearInstruction'),line('Written algorithm','文字算法','algorithmChoice'),...(present('algorithmWhy')?[line('Earlier algorithm explanation','之前的算法解释','algorithmWhy')]:[]),line('Decomposition term','分解术语','decompositionWord')]},
      {title:t('My mission plan','我的任务计划'),lines:[line('Part 1','第一部分','jobOne'),line('Part 2','第二部分','jobTwo'),`Movement plan: ${state.plan.map(cmd=>moveNames[cmd][0].slice(2)).join(', ')||'Not recorded'}`,line('Why key first','为什么先到钥匙','planWhy'),`Saved plan versions: ${state.planHistory.length}`]},
      {title:t('Read code','读代码'),lines:[`Code shown: when flag clicked -> go to (-160, -100) -> change x by 120`,line('Predicted x','预测 x','predictX'),line('Predicted y','预测 y','predictY'),line('Coordinate explanation','坐标解释','readWhy')]},
      {title:t('Practical work','实际操作'),lines:[line('Scratch loaded','Scratch 已载入','scratchOpened'),line('Part 1 coded and tested','第一部分已编写并测试','keyBuilt'),line('Two-part code built','已编写两部分代码','builtInScratch'),t('These are pupil confirmations. Teacher verification is required.','这些是学生确认，需要教师检查。')]},
      {title:t('Tests: expected and actual','测试：预期与实际'),lines:[`Expected: starts at (-160, -80), visits key (-40, 40), finishes at portal (160, 40), avoids the three wall squares.`,...(state.tests.length?state.tests.flatMap((test,i)=>[`Test ${i+1}: ${test.result}; actual finish (${test.x}, ${test.y}); ${test.at}`,`Observation / change: ${test.note}`,`Plan during this test: ${test.plan}`]):['No test saved.']),...(present('testResult')?[`Current test form (may not be saved as an attempt): ${a.testResult}; (${a.testX||'?'}, ${a.testY||'?'}); ${a.testNote||''}`]:[])]},
      {title:t('Understanding: explain my program','理解：解释我的程序'),lines:[line('Input','输入','ipoInput'),line('Process','处理','ipoProcess'),line('Output','输出','ipoOutput'),line('My movement block','我的移动积木','codeExplain')]},
      {title:t('My extra creation — optional','我的额外创作 — 可选'),lines:[line('Chosen challenge','所选挑战','extraChoice'),line('My target x','目标 x','targetX'),line('My target y','目标 y','targetY'),line('What I created and tested','我创作和测试的内容','extensionNote')]},
      {title:t('Learning reflection — not graded','学习反思 — 不计分'),lines:[line('Learning phase','学习阶段','learningPhase'),`Help requested: ${state.flags.join(', ')||'None'}`]},
      {title:t('Saved Scratch code evidence','已保存的 Scratch 代码证据'),lines:state.scratchEvidence?[`File: ${state.scratchEvidence.filename}`,`Sprite: ${state.scratchEvidence.sprite}; read at ${state.scratchEvidence.at}`,...state.scratchEvidence.scripts.flatMap((script,i)=>[`Script ${i+1}:`,...script.map((text,j)=>`${j+1}. ${text}`)]),'Code details were read from a saved file. This is not a live screenshot or an automatic grade. The actual .sb3 must be submitted separately.']:['No saved Scratch file read. Teacher needs the .sb3 file.']},
      {title:t('Submission','提交'),lines:[line('Pupil hand-in check','学生提交检查','submission'),'Teacher should receive BOTH PDF and SB3. JSON restores webpage answers only.']}
    ];
    if(state.planHistory.length)sections.push({title:t('Plan versions','计划版本'),lines:state.planHistory.map((p,i)=>`Plan ${i+1} (${p.at}): ${p.moves.map(cmd=>moveNames[cmd][0].slice(2)).join(', ')}`)});
    if(state.legacy)sections.push({title:'Earlier assessment evidence (different task; retained, not graded as this mission)',lines:[...Object.entries(state.legacy.answers).map(([k,v])=>`${k}: ${v}`),`Earlier route: ${state.legacy.route.join(', ')}`,`Earlier Scratch filename: ${state.legacy.scratchFileName||'Not recorded'}`,...state.legacy.routeRuns.map((run,i)=>`Earlier test ${i+1}: ${run.commands.join(', ')}; ${run.message}; (${run.final.join(', ')}); ${run.at}`)]});
    return sections;
  }
  async function mapPng(){return new Promise((resolve,reject)=>{const svg=mission.mapSvg(),url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'})),img=new Image();img.onload=()=>{try{const canvas=document.createElement('canvas');canvas.width=960;canvas.height=720;canvas.getContext('2d').drawImage(img,0,0,960,720);resolve(canvas.toDataURL('image/png'));}catch(err){reject(err);}finally{URL.revokeObjectURL(url);}};img.onerror=()=>{URL.revokeObjectURL(url);reject(Error('Map could not be exported'));};img.src=url;});}
  async function downloadPdf(){
    if(importBusy)return;const sections=reportSections();
    if(!state.scratchEvidence&&!confirm(t('No Scratch file has been read yet. Save an incomplete report anyway?','还没有读取 Scratch 文件。仍保存不完整报告吗？')))return;
    if(state.language!=='en'||[state.name,state.cls,...sections.flatMap(s=>s.lines)].some(v=>/[^\u0000-\u00ff]/.test(v))){$('pdfStatus').textContent=t('Choose Save as PDF in the print window.','请在打印窗口选择另存为 PDF。');printPdf();return;}
    if(!window.jspdf?.jsPDF){$('pdfStatus').textContent=t('Use Print / Save as PDF.','请使用打印 / 另存为 PDF。');return;}
    $('downloadPdf').disabled=true;try{
      const doc=new window.jspdf.jsPDF({unit:'mm',format:'a4'});let y=20;
      const add=(text,size=10,bold=false)=>{doc.setFont('helvetica',bold?'bold':'normal');doc.setFontSize(size);for(const line of doc.splitTextToSize(String(text).replace(/[↑→↓←]/g,' '),176)){if(y>275){doc.addPage();y=20;}doc.text(line,17,y);y+=size*.48;}y+=3;};
      add('YEAR 6 COMPUTING - EXPLORER MISSION',12,true);add(`${state.name} | ${state.cls}`,18,true);add(`Saved: ${new Date().toLocaleString('en-GB')}`,9);add('Plan -> code in Scratch -> test -> explain',11,true);
      try{doc.addImage(await mapPng(),'PNG',17,y,115,86);y+=92;}catch{add('START (-160,-80); KEY (-40,40); PORTAL (160,40).');}
      add('Teacher: assess the pupil plan, actual Scratch code, tests and explanation. Recorded answers are not automatic marks.',10);
      for(const section of sections){if(y>235){doc.addPage();y=20;}add(section.title,14,true);for(const line of section.lines)add(line);}
      for(let i=1;i<=doc.getNumberOfPages();i++){doc.setPage(i);doc.setFontSize(8);doc.text(`${i} / ${doc.getNumberOfPages()}`,190,286,{align:'right'});}doc.save(`${stem()}.pdf`);$('pdfStatus').textContent=t('Report saved. Open it; then upload the PDF and SB3 in Teams.','报告已保存。检查后把 PDF 和 SB3 上传 Teams。');
    }catch{$('pdfStatus').textContent=t('Report could not download. Use Print / Save as PDF.','报告未能下载。请使用打印 / 另存为 PDF。');}finally{$('downloadPdf').disabled=false;}
  }
  function printPdf(){if(importBusy)return;const wrap=$('printReport');wrap.innerHTML=`<div class="print-intro"><h1>${b("Explorer's mission checkpoint",'探索者任务测评')}</h1><p>${esc(state.name)} · ${esc(state.cls)}</p>${mission.mapSvg(state.language)}<p>${b('The actual Scratch file must be submitted separately. This report records evidence, not automatic grades.','实际 Scratch 文件需另行提交。报告记录学习证据，不自动评分。')}</p></div>${reportSections().map(section=>`<section class="report-section"><h2>${esc(section.title)}</h2>${section.lines.map(line=>`<p>${esc(line)}</p>`).join('')}</section>`).join('')}`;wrap.hidden=false;window.addEventListener('afterprint',()=>wrap.hidden=true,{once:true});window.print();}
})();
