/* English stays beside Korean. Pupils may use either language, or mix them. */
(() => {
  'use strict';
  const entries = [
    ['Use your Scratch tab, or allow this page to open Scratch.','내 Scratch 탭을 쓰거나 이 페이지가 Scratch를 열도록 허용해요.'],['Use your existing Scratch tab. Keep your project open.','이미 열린 Scratch 탭을 써요. 작품은 열어 둬요.'],
    ['Code a rescue','구조 프로그램 만들기'],['Get the key. Reach the portal. Bring Explorer home.','열쇠를 거쳐 포털로 가요. Explorer를 집으로 데려와요.'],
    ['Help Explorer get home','Explorer가 집에 가게 도와요'],['Give a clear instruction','정확한 명령을 써요'],['Predict a move','이동을 예상해요'],['Open your mission in Scratch','Scratch에서 미션 열기'],['Two smaller jobs','두 개의 작은 일'],['Draw your route with moves','이동으로 경로 그리기'],['Mission 1 · Reach the key','미션 1 · 열쇠까지 가기'],['Mission 2 · Reach the portal','미션 2 · 포털까지 가기'],['Test your rescue','구조 코드를 시험해요'],['Choose a new world','새 세계를 골라요'],['Show what you understand','내가 이해한 것 보여 주기'],['Keep your project safe','내 작품 저장하기'],['Check before handing in','제출 전에 확인해요'],['Hand in your rescue project','내 구조 작품 제출하기'],
    ['Your goal','내 목표'],['Answer here','여기서 답해요'],['Think here','여기서 생각해요'],['Open Scratch','Scratch 열기'],['Plan here','여기서 계획해요'],['Build in Scratch','Scratch에서 만들어요'],['Run in Scratch','Scratch에서 실행해요'],['Create in Scratch','Scratch에서 창작해요'],['Explain here','여기서 설명해요'],['Save in Scratch','Scratch에서 저장해요'],['Check here','여기서 확인해요'],['Save here · hand in on Teams','여기서 저장 · Teams에서 제출'],
    ['Start the warm-up →','준비 활동 시작 →'],['Next: read some code →','다음: 코드 읽기 →'],['My file is open · plan next →','파일을 열었어요 · 다음: 계획 →'],['Next: plan my route →','다음: 경로 계획 →'],['Next: build this in Scratch →','다음: Scratch에서 만들기 →'],['I tried Part 1 · build Part 2 →','1부를 해 봤어요 · 2부 만들기 →'],['I tried both parts · test next →','두 부분을 해 봤어요 · 다음: 시험 →'],['Next: extra challenges →','다음: 추가 도전 →'],['Next: explain my code →','다음: 내 코드 설명 →'],['Next: save my project →','다음: 작품 저장 →'],['Next: check my work →','다음: 내 작업 확인 →'],['Next: hand in →','다음: 제출 →'],
    ['Knowledge','지식'],['Skills','기능'],['Understanding','이해'],['Remember the words.','배운 낱말을 기억해요.'],['Build and test code.','코드를 만들고 시험해요.'],['Explain a choice.','선택한 이유를 설명해요.'],['Go to Scratch ↗','Scratch로 가기 ↗'],['Already open? Use your Scratch tab. Do not start a new project.','이미 열었나요? 그 Scratch 탭을 사용해요. 새 작품을 만들지 않아요.'],
    ['Block help','블록 도움'],['Right / up','오른쪽 / 위'],['Left / down','왼쪽 / 아래'],['Pause','잠깐 멈추기'],['Positive numbers move right or up. 40 steps = one square.','양수는 오른쪽이나 위로 이동해요. 40걸음 = 한 칸이에요.'],['Negative numbers move left or down. −40 steps = one square.','음수는 왼쪽이나 아래로 이동해요. −40걸음 = 한 칸이에요.'],['Find wait in orange Control. Pause after reaching the first stop.','주황색 Control에서 wait를 찾아요. 첫 장소에 도착하면 잠깐 멈춰요.'],['Copy the block idea, not the whole example. Keep your own start blocks.','블록의 사용법을 참고해요. 예시 전체를 따라 쓰지 않아요. 내 시작 블록은 남겨 둬요.'],
    ['Blue dots show your PLAN, not a running program. P is its end.','파란 점선은 내 계획이에요. 실행 중인 프로그램이 아니에요. P는 계획의 끝이에요.'],['Goal: stop at the key','목표: 열쇠에서 멈추기'],['Goal: key first, then portal','목표: 열쇠를 거쳐 포털로 가기'],
    ['Explorer needs a key to get home through the portal. You are the programmer. Find a safe route and make it work in Scratch.','Explorer는 포털로 집에 가려면 열쇠가 필요해요. 내가 프로그래머예요. 안전한 경로를 찾고 Scratch에서 만들어요.'],['Your rescue rules','구조 미션 규칙'],['Visit the key before the portal.','포털보다 열쇠에 먼저 가요.'],['Stay out of the striped walls.','줄무늬 벽을 지나가지 않아요.'],['The green flag must start the rescue again.','초록 깃발로 구조를 다시 시작할 수 있어야 해요.'],['Most of today is making and testing, not typing long answers.','오늘은 긴 답을 쓰기보다 코드를 만들고 시험하는 시간이 많아요.'],['Use English, Mandarin, Korean, or a mix. Short answers are welcome.','영어, 중국어, 한국어를 쓰거나 섞어 써도 돼요. 짧게 답해도 좋아요.'],
    ['A robot cannot guess “move a bit”. Tell it where to go and how far.','로봇은 “조금 움직여”를 짐작하지 못해요. 방향과 거리를 알려 줘요.'],['What one move reaches the star?','어떤 이동 하나로 별에 갈 수 있나요?'],['See a different example','다른 예시 보기'],['“Move left 4 squares” gives a direction and a distance. Your picture needs a different move.','“왼쪽으로 네 칸 가”에는 방향과 거리가 있어요. 내 그림에는 다른 이동이 필요해요.'],['A · Written plan','A · 글로 쓴 계획'],['B · Runnable code','B · 실행할 수 있는 코드'],['Which shows an algorithm written as steps, not code?','코드가 아니라 글로 쓴 알고리즘 단계는 어느 쪽인가요?'],['A program carries out an algorithm. Here, we are comparing words with runnable blocks.','프로그램은 알고리즘을 실행해요. 여기서는 글과 실행할 수 있는 블록을 비교해요.'],
    ['Read these blocks from top to bottom. Choose where the sprite will stop. Do not run them yet.','블록을 위에서 아래로 읽어요. 스프라이트가 멈출 곳을 골라요. 아직 실행하지 않아요.'],['x = left / right · y = up / down','x = 왼쪽 / 오른쪽 · y = 위 / 아래'],['My prediction','내 예상'],['Why does one coordinate stay the same?','왜 좌표 하나는 그대로인가요?'],['Only ... changes.','...만 바뀌어요.'],['Prefer to type my coordinates','좌표를 직접 입력할래요'],
    ['A whole rescue can feel big. Split it into two useful jobs before you code. This is decomposition.','구조 전체는 크게 느껴질 수 있어요. 코딩 전에 두 개의 작은 일로 나눠요. 이것이 decomposition이에요.'],['KEY','열쇠'],['PORTAL','포털'],['FINISH','도착'],['The key must come first. Name one job for each part of your rescue.','열쇠가 먼저예요. 구조의 각 부분에서 할 일을 써요.'],['Job 1: what must Explorer reach first?','일 1: Explorer가 먼저 어디에 가야 하나요?'],['Job 2: what happens after that?','일 2: 그다음에는 무엇을 하나요?'],['First...','먼저...'],['Then...','그다음...'],['What does decomposition help you do?','decomposition은 무엇을 도와주나요?'],['Split a big job into smaller jobs.','큰 일을 작은 일들로 나눠요.'],['Find and fix a mistake in code.','코드의 실수를 찾고 고쳐요.'],['See what the computer does.','컴퓨터가 하는 일을 봐요.'],
    ['Tap moves to draw your route: START → key → portal. Each tap is one square. Look for a path around the walls.','이동을 눌러 경로를 그려요: 출발 → 열쇠 → 포털. 한 번 누르면 한 칸이에요. 벽을 돌아가는 길을 찾아요.'],['Undo last move','마지막 이동 취소'],['Start my plan again','계획 다시 시작'],['Each square is 40 Scratch steps. You will turn this plan into blocks next.','한 칸은 Scratch 40걸음이에요. 다음에 이 계획을 블록으로 만들어요.'],['Edit the order of my moves','이동 순서 바꾸기'],['Why does your route visit the key before the portal?','왜 내 경로는 포털보다 열쇠에 먼저 가나요?'],['Start a new plan? Your saved earlier plan versions stay in the report.','계획을 다시 만들까요? 이전에 저장한 계획은 보고서에 남아요.'],
    ['Build the first part of YOUR plan in Scratch. Stop at the key.','내 계획의 첫 부분을 Scratch에서 만들어요. 열쇠에서 멈춰요.'],['Select Explorer. Keep its two start blocks.','Explorer를 골라요. 시작 블록 두 개는 남겨 둬요.'],['Add blue change x / change y blocks for your route. Choose the numbers yourself.','내 경로에 파란 change x / change y 블록을 넣어요. 숫자는 내가 골라요.'],['Press the green flag. Check the key’s x and y. Fix a move if needed.','초록 깃발을 눌러요. 열쇠의 x, y를 확인해요. 필요하면 이동을 고쳐요.'],['Show my saved plan','저장한 내 계획 보기'],['After trying Part 1 in Scratch','Scratch에서 1부를 해 본 뒤'],['I built it and ran it.','만들고 실행했어요.'],['I tried. I need help with one move.','해 봤어요. 이동 하나에 도움이 필요해요.'],
    ['Keep Part 1. Add code after it to reach the portal. Your two jobs now become one rescue program.','1부는 남겨 둬요. 그 뒤에 포털로 가는 코드를 넣어요. 두 일이 하나의 구조 프로그램이 돼요.'],['After the key moves, add wait 2 seconds.','열쇠까지 이동한 뒤 wait 2 seconds를 넣어요.'],['Add moves to the portal. Do not jump back to START.','포털까지 이동을 넣어요. 출발로 바로 돌아가지 않아요.'],['Run the whole program. Watch both stops.','전체 프로그램을 실행해요. 두 장소에서 멈추는지 봐요.'],['After trying both parts in Scratch','Scratch에서 두 부분을 해 본 뒤'],['I built both parts and ran them.','두 부분을 만들고 실행했어요.'],['I tried. I need some help.','해 봤어요. 도움이 필요해요.'],['Learning pitstop','배움 잠깐 확인'],['How is this challenge feeling? Choose your next step.','이 도전은 어떻게 느껴지나요? 다음 단계를 골라요.'],['New learning · try one small move.','새로 배우기 · 작은 이동 하나를 해 봐요.'],['Consolidating · practise the whole route.','익히기 · 전체 경로를 연습해요.'],['Treading water · ready for a harder task.','너무 쉬워요 · 더 어려운 일에 도전할래요.'],['Drowning · ask for one small hint.','너무 어려워요 · 작은 힌트 하나를 요청해요.'],
    ['Does your rescue really work? Run it in Scratch twice. A working first try still needs a second check.','구조가 정말 되나요? Scratch에서 두 번 실행해요. 처음에 됐어도 한 번 더 확인해요.'],['Starts again','다시 시작'],['Key first','열쇠 먼저'],['Portal next','포털 그다음'],['No wall crossing','벽을 지나지 않기'],['What did you see in this run?','이번 실행에서 무엇을 봤나요?'],['Key, then portal.','열쇠, 그다음 포털.'],['Missed the key.','열쇠를 놓쳤어요.'],['Crossed a wall.','벽을 지나갔어요.'],['Stopped elsewhere.','다른 곳에서 멈췄어요.'],['Did not move as expected.','생각한 대로 움직이지 않았어요.'],['Read final x in Scratch','Scratch에서 마지막 x 읽기'],['Read final y in Scratch','Scratch에서 마지막 y 읽기'],['What did you change, or check again?','무엇을 바꾸거나 다시 확인했나요?'],['I changed... / I checked...','...를 바꿨어요. / ...를 확인했어요.'],['My saved test attempts','내가 저장한 시험 기록'],['Optional: see a route preview from my saved .sb3','선택: 저장한 .sb3의 경로 미리 보기'],['Save in Scratch first. Choose that .sb3 here. This previews simple movement code only; your teacher still checks the real project.','먼저 Scratch에서 저장해요. 그 .sb3를 여기서 골라요. 간단한 이동 코드만 미리 봐요. 선생님은 실제 작품도 확인해요.'],['Replay my saved moves','저장한 이동 다시 보기'],['Preview needs one green-flag script with go to, change x/y and wait blocks. Other code can be tested in Scratch.','미리 보기는 go to, change x/y, wait를 쓰는 초록 깃발 스크립트 하나가 필요해요. 다른 코드는 Scratch에서 시험해요.'],['Preview from the SAVED file, not live Scratch.','저장한 파일의 미리 보기예요. 실시간 Scratch 화면은 아니에요.'],['Check it yourself: key first, portal next, no wall crossing.','직접 확인해요: 열쇠 먼저, 포털 그다음, 벽을 지나지 않기.'],
    ['Finished your rescue? Pick a world. Build, return, then design a new ending. These are extra tasks, not a new test.','구조를 끝냈나요? 세계를 골라요. 만들고 돌아온 뒤 새 도착점을 설계해요. 추가 도전이며 새 시험은 아니에요.'],['One thing I made or changed','내가 만들거나 바꾼 것 하나'],['1 · Deliver','1 · 보내기'],['2 · Return','2 · 돌아오기'],['3 · My ending','3 · 내 도착점'],['Download new template (.sb3)','새 시작 파일 받기 (.sb3)'],['Open a NEW Scratch tab ↗','새 Scratch 탭 열기 ↗'],['Save your main Explorer file first. In the new tab: File → Load from your computer → choose this template.','먼저 기본 Explorer 파일을 저장해요. 새 탭에서 파일 → 컴퓨터에서 가져오기 → 이 시작 파일을 골라요.'],['Use the SAME Scratch project. Keep the code you made in earlier challenges.','같은 Scratch 작품을 써요. 앞 도전에서 만든 코드는 남겨 둬요.'],['Select the moving sprite. Keep its start blocks.','움직일 스프라이트를 골라요. 시작 블록은 남겨 둬요.'],['Make your own route to the first stop. Add wait 2 seconds.','첫 장소까지 내 경로를 만들어요. wait 2 seconds를 넣어요.'],['Add moves to FINISH. Run and check both stops.','도착점까지 이동을 넣어요. 실행하고 두 장소를 확인해요.'],['After FINISH, add wait 2 seconds.','도착점에 간 뒤 wait 2 seconds를 넣어요.'],['Add moves back to START. Do not use go to to jump home.','출발로 돌아오는 이동을 넣어요. go to로 바로 돌아가지 않아요.'],['Run again: first stop → FINISH → START. Check x and y at the end.','다시 실행해요: 첫 장소 → 도착 → 출발. 마지막 x와 y를 확인해요.'],['Pick a new empty square for your ending.','새 도착점으로 빈 칸을 골라요.'],['In Scratch, select the FINISH sprite. Set its x/y to your new coordinates.','Scratch에서 도착 스프라이트를 골라요. x/y를 새 좌표로 바꿔요.'],['Select the moving sprite. Change its route to reach your new ending after the first stop.','움직일 스프라이트를 골라요. 첫 장소를 거쳐 새 도착점으로 가게 경로를 바꿔요.'],['Test it. Then use Costumes to change a colour or draw a new face.','시험해요. 그다음 모양에서 색을 바꾸거나 새 얼굴을 그려요.'],['Moving sprite','움직일 스프라이트'],['I ran this challenge in Scratch','이 도전을 Scratch에서 실행했어요'],['It worked. I checked the stops.','잘 됐어요. 멈추는 곳을 확인했어요.'],['I tried. It still needs a change.','해 봤어요. 아직 바꿀 것이 있어요.'],['Save my try · next challenge →','내 시도 저장 · 다음 도전 →'],['Save my design try ✓','내 설계 시도 저장 ✓'],['A try is saved. This is your record, not a grade.','시도를 저장했어요. 내 기록이며 점수가 아니에요.'],['Save this as a separate .sb3. Your MAIN Explorer project is still the assessment file.','별도의 .sb3로 저장해요. 기본 Explorer 작품이 배움 확인용 파일이에요.'],['This is a design plan. Move the sprite in Scratch yourself.','이것은 설계 계획이에요. 스프라이트는 Scratch에서 직접 옮겨요.'],['Choose what happened when you tried it first.','먼저 해 봤을 때 무슨 일이 있었는지 골라요.'],['Your try is saved. Keep building in Scratch.','시도를 저장했어요. Scratch에서 계속 만들어요.'],
    ['Explain YOUR rescue, not a made-up example. A few words in any language are enough.','예시가 아니라 내 구조 작품을 설명해요. 어떤 언어로든 몇 마디면 돼요.'],['Input · what starts it?','입력 · 무엇으로 시작하나요?'],['Process · what does your code do?','처리 · 내 코드는 무엇을 하나요?'],['Output · what do you see?','출력 · 무엇이 보이나요?'],['I...','나는...'],['Explorer...','Explorer는...'],['Choose one move. Why did you use that number?','이동 하나를 골라요. 왜 그 숫자를 썼나요?'],['My block uses... because...','내 블록은 ...를 써요. 이유는 ...예요.'],['You may explain aloud to your teacher instead. Ask them to record your idea.','선생님께 말로 설명해도 돼요. 내 생각을 기록해 달라고 해요.'],
    ['Comet Courier','혜성 배달'],['Moon Garden','달 정원'],['Fuel dock','연료 정거장'],['Launch pad','발사대'],['Star seed','별 씨앗'],['Moon flower','달 꽃'],['START','출발'],
    ['1. Download this template (.sb3)','1. 이 시작 파일 받기 (.sb3)'],
    ['2. Open a NEW Scratch tab','2. 새 Scratch 탭 열기'],
    ['A real Scratch view. One square = 40 steps.','실제 Scratch 화면이에요. 한 칸 = 40걸음이에요.'],
    ['Choose your new mission','새 미션을 골라요'],
    ['Comet Courier: help Nova reach the fuel dock, then the launch pad.','혜성 배달: Nova가 연료 정거장을 거쳐 발사대로 가게 해요.'],
    ['Moon Garden: help Pip visit the star seed, then the moon flower.','달 정원: Pip이 별 씨앗을 거쳐 달 꽃으로 가게 해요.'],
    ['Download the new template below. Open a NEW Scratch tab. Choose File → Load from your computer, then choose this template.','아래 시작 파일을 받아요. 새 Scratch 탭을 열어요. 파일 → 컴퓨터에서 가져오기를 누르고 이 파일을 골라요.'],
    ['Left, then down: −40 means one square.','왼쪽, 그다음 아래: −40은 한 칸이에요.'],
    ['Right, then up: +40 means one square.','오른쪽, 그다음 위: +40은 한 칸이에요.'],
    ['Make it your own — after your route works','경로가 잘 되면 나만의 작품으로 바꿔요'],
    ['More ideas using my main mission','기본 미션으로 더 만들어 보기'],
    ['Move the FINISH sprite to a new empty square. Use x/y values in 40s. Change your code to reach it, then test again.','도착 스프라이트를 새 빈 칸으로 옮겨요. x/y는 40씩 맞춰요. 새 도착점으로 가도록 코드를 바꾸고 다시 시험해요.'],
    ['Need a block example?','블록 예시가 필요해요?'],
    ['Press the green flag. Check both stops and the x/y boxes. Change a move and test again if needed.','초록 깃발을 눌러요. 두 곳과 x/y 칸을 확인해요. 필요하면 이동을 바꾸고 다시 시험해요.'],
    ['Save this as a SECOND .sb3 with a new name. Upload it as an extra project if your teacher asks. The MAIN Explorer .sb3 is still your assessment file.','새 이름으로 두 번째 .sb3 파일을 저장해요. 선생님이 요청하면 추가 작품으로 제출해요. 기본 Explorer .sb3가 배움 확인용 파일이에요.'],
    ['Save your MAIN Explorer file first: File → Save to your computer. Keep it for hand-in.','먼저 기본 Explorer 파일을 저장해요: 파일 → 컴퓨터에 저장하기. 제출할 때 필요해요.'],
    ['Select a sprite, then Costumes. Change its colours or draw a new face. Keep it small enough to fit one square.','스프라이트를 고르고 모양을 눌러요. 색을 바꾸거나 새 얼굴을 그려요. 한 칸 안에 들어가게 작게 만들어요.'],
    ['Select the moving sprite. Keep its two start blocks. Add your own moves to the first stop, wait 2 seconds, then move to FINISH.','움직일 스프라이트를 골라요. 시작 블록 두 개는 그대로 둬요. 첫 장소까지 이동을 만들고, 2초 기다린 뒤 도착점으로 가게 해요.'],
    ['Show the template inside Scratch','Scratch에서 시작 파일 보기'],
    ['The orange wait block pauses between moves. Put a pause after your first job.','주황색 기다리기 블록은 잠깐 멈추게 해요. 첫 일을 마친 뒤에 넣어요.'],
    ['These start at (0, 0). Keep YOUR template’s start blocks and choose your own moves.','이 예시는 (0, 0)에서 시작해요. 내 시작 파일의 블록은 그대로 두고 이동을 직접 골라요.'],
    ['Your main mission is finished? Choose a new world to create in Scratch. These extra missions are optional.','기본 미션을 끝냈나요? Scratch에서 만들 새 세계를 골라요. 추가 미션은 원하면 해요.'],
    ['Your new mission: visit the first stop, pause, then reach FINISH. Stay out of the striped walls.','새 미션: 첫 장소에 가서 잠깐 멈춘 뒤 도착점으로 가요. 줄무늬 벽은 지나가지 않아요.'],
    ['Computing checkpoint','컴퓨팅 배움 확인'],
    ['YEAR 6 · CREATE IN SCRATCH','6학년 · Scratch로 만들기'],
    ["Explorer's mission",'Explorer의 미션'],
    ["Explorer's mission checkpoint",'Explorer 미션 배움 확인'],
    ['Your plan. Your code. Your journey.','내 계획. 내 코드. 내 이동 경로.'],
    ['Start or continue','시작하거나 이어 하기'],
    ['Your name','이름'],['Your class','반'],
    ['Reading support','읽기 도움'],
    ['Think, talk and answer in English, Mandarin, Korean, or a mix.','영어, 중국어, 한국어로 생각하고 이야기하고 답해도 돼요. 언어를 섞어 써도 돼요.'],
    ['Think, talk and answer in English, Mandarin, Korean, or a mix. Keep Scratch block names beside your ideas.','영어, 중국어, 한국어를 골라 쓰거나 섞어 써도 돼요. 설명할 때 Scratch 블록 이름도 함께 써 주세요.'],
    ['Start my mission →','내 미션 시작 →'],
    ['Create, test, improve','만들기, 테스트하기, 고치기'],
    ['Guide Explorer to the key, then the portal. Most of your work happens in Scratch.','Explorer를 열쇠로, 그다음 포털로 이동시켜요. 대부분의 활동은 Scratch에서 해요.'],
    ['Continue with a backup (.json)','백업 파일로 이어 하기 (.json)'],
    ['Teacher preview: type teacher as your name. No password.','교사 미리 보기: 이름에 teacher를 입력해요. 비밀번호는 없어요.'],
    ['Ready','준비'],['Try code','코드 살펴보기'],['Plan','계획'],['Create','만들기'],['Test','테스트'],['Explain','설명'],['Hand in','제출'],
    ['Your mission','내 미션'],['A quick warm-up','짧은 준비 활동'],['Read these blocks','블록 읽기'],['Open Scratch now','지금 Scratch 열기'],
    ['Split your mission','미션 나누기'],['Make your route plan','이동 경로 계획하기'],['Code to the key','열쇠까지 코딩하기'],['Code to the portal','포털까지 코딩하기'],
    ['Test and improve your journey','이동을 테스트하고 고치기'],['Create your own challenge','나만의 도전 만들기'],['Explain your program','내 프로그램 설명하기'],['Name your Scratch file','Scratch 파일 이름 짓기'],
    ['Check your evidence','내 작업 확인하기'],['Save and hand in','저장하고 제출하기'],
    ['<strong>Your mission:</strong> START → key → portal. Plan here. Build and test in Scratch.','<strong>내 미션:</strong> 출발 → 열쇠 → 포털. 여기서 계획하고 Scratch에서 만들고 테스트해요.'],
    ['Create a Scratch journey: START → key → portal. Avoid the walls.','Scratch로 이동 경로를 만들어요: 출발 → 열쇠 → 포털. 벽을 피해요.'],
    ['Your project today','오늘 만들 작품'],['Plan two parts.','두 부분으로 계획해요.'],['Build both parts in Scratch.','두 부분 모두 Scratch에서 만들어요.'],['Run, check and improve your code.','코드를 실행하고 확인하고 고쳐요.'],
    ['Your ideas and code matter. Short answers are enough.','내 생각과 코드가 중요해요. 답은 짧게 써도 돼요.'],
    ['Knowledge: remember','지식: 기억하기'],['Use the words you learned.','배운 낱말을 사용해요.'],['Skills: create','기능: 만들기'],['Make and test your code.','코드를 만들고 테스트해요.'],['Understanding: explain','이해: 설명하기'],['Say why your code works.','코드가 왜 그렇게 움직이는지 설명해요.'],
    ['Help using these cards','카드 사용 도움'],['Use Back or Save & continue. You can return to unfinished work.','Back 또는 Save & continue를 눌러요. 끝내지 못한 활동은 나중에 다시 할 수 있어요.'],['Try a button','버튼 눌러 보기'],
    ['The button worked. Next, use Save & continue below.','버튼이 작동했어요. 이제 아래의 Save & continue를 눌러요.'],
    ['Quick warm-up: look at the plan and blocks.','짧은 준비 활동: 계획과 블록을 살펴봐요.'],['A: written steps','A: 글로 쓴 단계'],['B: Scratch blocks','B: Scratch 블록'],
    ['Start at the entrance. Move up three squares. Stop.','입구에서 시작해요. 위로 세 칸 이동해요. 멈춰요.'],
    ['Which is the algorithm written as a plan?','알고리즘을 글로 쓴 계획은 어느 것인가요?'],
    ['Give the robot one clear move','로봇에게 정확한 이동 명령 주기'],['Reach the star. Write a direction and number of squares.','별까지 가게 해 주세요. 방향과 칸 수를 써요.'],['Move...','…쪽으로 …칸 이동해요.'],
    ['Need a reminder?','도움말이 필요한가요?'],
    ['An algorithm is a plan with ordered steps. A program is code a computer can run. A clear move says where and how far.','알고리즘은 순서대로 쓴 단계예요. 프로그램은 컴퓨터가 실행하는 코드예요. 정확한 이동 명령에는 방향과 거리가 있어요.'],
    ['For a different route: “Move left 4 squares.” Use YOUR picture.','다른 경로의 예: “왼쪽으로 4칸 이동해요.” 내 그림에 맞게 써 주세요.'],
    ['Read from top to bottom. Where will this sprite stop?','위에서 아래로 읽어요. 스프라이트는 어디에서 멈출까요?'],['Final x','마지막 x'],['Final y','마지막 y'],
    ['Which coordinate stays the same? Why?','어느 좌표가 바뀌지 않나요? 왜 그런가요?'],['... stays the same because...','…는 바뀌지 않아요. 왜냐하면…'],
    ['A warm-up, not your mission code. Next: open Scratch and create your own.','준비 활동이지 미션의 정답 코드는 아니에요. 다음에는 Scratch에서 내 코드를 만들어요.'],
    ['Open Scratch now. Create your program there.','지금 Scratch를 열어요. 그곳에서 내 프로그램을 만들어요.'],
    ['1. Download mission file (.sb3)','1. 미션 파일 받기 (.sb3)'],['2. Open Scratch ↗','2. Scratch 열기 ↗'],
    ['Choose File → Load from your computer. Open the downloaded mission.','File → Load from your computer를 선택해요. 받은 미션 파일을 열어요.'],
    ['Choose Explorer. Press the green flag: it should reset at START.','Explorer를 선택하고 초록 깃발을 눌러요. 출발점으로 돌아오는지 확인해요.'],
    ['Keep Scratch open. Return here for your next small task.','Scratch는 열어 두세요. 다음 활동을 보려면 이 페이지로 돌아와요.'],
    ['Ready to create?','만들 준비가 됐나요?'],['My mission is open in Scratch.','Scratch에서 미션을 열었어요.'],['Help me open the file.','파일 여는 것을 도와주세요.'],
    ['Continuing at home?','집에서 이어 하나요?'],['Load your own saved .sb3 in Scratch. JSON restores these cards only.','Scratch에서 내가 저장한 .sb3를 열어요. JSON은 이 카드의 답만 복원해요.'],
    ['Show the real Scratch mission: blocks, stage and x/y boxes','실제 Scratch 보기: 블록, 무대, x/y 칸'],
    ['Choose Explorer below the stage. The x and y boxes are beside its name. Motion blocks are in the blue category on the left. This is the same starter you downloaded.','무대 아래에서 Explorer를 선택해요. 이름 옆에 x와 y 칸이 있어요. 왼쪽 파란 Motion에서 이동 블록을 찾아요. 내가 받은 시작 파일과 같아요.'],
    ['Name two jobs for your mission. You will code each job next.','미션을 두 가지 작은 일로 나눠 써요. 다음에 각 일을 코딩해요.'],
    ['Part 1: reach...','1부: …에 도착하기'],['Part 2: reach...','2부: …에 도착하기'],['First, Explorer...','먼저 Explorer는…'],['Then, Explorer...','그다음 Explorer는…'],
    ['Breaking a big problem into smaller parts is called...','큰 문제를 작은 부분으로 나누는 것을 뭐라고 하나요?'],
    ['Decomposition','문제 나누기 (Decomposition)'],['Debugging','오류 찾고 고치기 (Debugging)'],['Output','출력 (Output)'],['Input','입력 (Input)'],['Process','처리 (Process)'],
    ['Decomposition means smaller jobs. A different mission might have “reach the bridge” and “cross the bridge”. Choose jobs for YOUR map.','문제 나누기는 작은 일로 나누는 거예요. 다른 미션은 “다리까지 가기”와 “다리 건너기”로 나눌 수 있어요. 내 지도에 맞게 나눠 보세요.'],
    ['Add moves for START → key → portal. One move = one square. Avoid the walls.','출발 → 열쇠 → 포털로 가는 이동을 추가해요. 이동 하나는 한 칸이에요. 벽을 피해요.'],
    ['My route','내 이동 경로'],['1 square','한 칸'],['1 square = 40 Scratch steps','한 칸 = Scratch 40스텝'],['Striped squares = walls','줄무늬 칸 = 벽'],
    ['↑ Up','↑ 위'],['→ Right','→ 오른쪽'],['↓ Down','↓ 아래'],['← Left','← 왼쪽'],
    ['↑ ↓ reorder. × removes a move. Test in Scratch.','↑ ↓로 순서를 바꿔요. ×는 이동을 지워요. 테스트는 Scratch에서 해요.'],
    ['Add your first move. This is a plan, not a running Scratch program.','첫 이동을 추가해요. 이것은 계획이에요. 실행은 Scratch에서 해요.'],
    ['Move earlier','순서 앞으로'],['Move later','순서 뒤로'],['Remove move','이동 지우기'],
    ['Why visit the key first?','왜 열쇠에 먼저 가나요?'],['The key...','열쇠는…'],
    ['No moves saved yet. Return to Plan.','저장한 이동이 없어요. Plan으로 돌아가요.'],
    ['Create in Scratch · about 10 minutes','Scratch에서 만들기 · 약 10분'],
    ['Code Part 1: START → key. Choose your own movement blocks and numbers.','1부 코딩: 출발 → 열쇠. 이동 블록과 숫자는 내가 정해요.'],
    ['Code Part 2: key → portal. Keep Part 1 and add to it.','2부 코딩: 열쇠 → 포털. 1부를 남겨 두고 뒤에 추가해요.'],
    ['Choose your moves','이동 고르기'],
    ['Right → change x by a positive number','오른쪽 → change x by에 양수 넣기'],['Left → change x by a negative number','왼쪽 → change x by에 음수 넣기'],['Up → change y by a positive number','위 → change y by에 양수 넣기'],['Down → change y by a negative number','아래 → change y by에 음수 넣기'],
    ['One square is 40 steps. You choose how many squares.','한 칸은 40스텝이에요. 몇 칸 갈지는 내가 정해요.'],
    ['Show a real block example','실제 블록 예 보기'],
    ['Example only: −40 moves left one square. Use your own plan, not these starting coordinates.','예시: −40이면 왼쪽 한 칸이에요. 이 시작 좌표를 따라 쓰지 말고 내 계획을 사용해요.'],
    ['Keep the two starter blocks. Add your moves underneath.','처음 두 블록은 남겨 둬요. 그 아래에 내 이동을 추가해요.'],
    ['Press the green flag. Reach the key without crossing a wall.','초록 깃발을 눌러요. 벽을 지나지 않고 열쇠까지 가요.'],
    ['Change one move if needed. At the key: x = −40, y = 40.','필요하면 이동 하나를 고쳐요. 열쇠 좌표: x = −40, y = 40.'],
    ['After trying my code...','내 코드를 실행한 뒤…'],['I coded and tested the first part.','1부를 코딩하고 테스트했어요.'],['I tried, and need help with one move.','해 봤지만 이동 하나에 도움이 필요해요.'],
    ['After Part 1, add “wait 2 seconds” from Control to see the key stop.','1부 뒤에 Control의 wait 2 seconds를 넣어요. 열쇠에서 멈추는 모습을 볼 수 있어요.'],
    ['Add portal moves below the wait. Do not reset to START again.','기다리기 블록 아래에 포털로 가는 이동을 넣어요. 출발점으로 다시 보내지 마세요.'],
    ['Run both parts. At the portal: x = 160, y = 40.','두 부분을 실행해요. 포털 좌표: x = 160, y = 40.'],
    ['After creating both parts...','두 부분을 만든 뒤…'],['My whole program is ready to test.','전체 프로그램을 테스트할 준비가 됐어요.'],['I tried both parts and need help.','두 부분을 해 봤지만 도움이 필요해요.'],
    ['Quick learning pitstop — not graded','잠깐 배움 확인 — 점수 없음'],
    ['New learning: I am trying something new.','새로운 배움: 새로운 것을 해 보고 있어요.'],
    ['Consolidating: practice is helping.','다지기: 연습하며 더 잘하고 있어요.'],
    ['Treading water: I need more challenge.','제자리: 더 어려운 도전이 필요해요.'],
    ['Drowning: I need one small step of help.','벅참: 작은 한 단계의 도움이 필요해요.'],
    ['Try one movement, then test it.','이동 하나를 넣고 테스트해 봐요.'],['Use your plan and check the two goals.','내 계획을 쓰고 두 목표를 확인해요.'],
    ['Finish the main mission first. Then try the optional return journey.','먼저 기본 미션을 끝내요. 그다음 돌아오는 경로에 도전해 봐요.'],
    ['Ask for help with one small part: opening Scratch, finding a block, or checking a move.','작은 한 부분의 도움을 요청해요: Scratch 열기, 블록 찾기, 이동 확인하기.'],
    ['Run your code in Scratch. Watch the key and portal. Record this test.','Scratch에서 내 코드를 실행해요. 열쇠와 포털을 보고 이번 테스트를 기록해요.'],
    ['Starts again at START','출발점에서 다시 시작해요'],['Visits the key before the portal','포털 전에 열쇠에 가요'],['Does not go through a wall','벽을 지나지 않아요'],
    ['What happened in this run?','이번 실행에서 무슨 일이 있었나요?'],
    ['It visited the key, then reached the portal.','열쇠를 거쳐 포털에 도착했어요.'],['It missed the key.','열쇠에 가지 못했어요.'],['It went through a wall.','벽을 지나갔어요.'],['It stopped somewhere else.','다른 곳에 멈췄어요.'],['It did not move as expected.','생각한 대로 움직이지 않았어요.'],
    ['Actual final x','실제 마지막 x'],['Actual final y','실제 마지막 y'],
    ['What will you change? If it worked, what showed you that it worked?','무엇을 고칠 건가요? 성공했다면 무엇을 보고 알았나요?'],['I noticed... so...','…을 봤어요. 그래서…'],['Save this test','이번 테스트 저장'],
    ['Choose a result, enter both coordinates and add a short note.','결과를 고르고 x와 y를 써요. 짧은 메모도 써 주세요.'],
    ['Test saved. If you run again, update these boxes and save another test.','테스트를 저장했어요. 다시 실행하면 이 칸을 바꾸고 새 테스트를 저장해요.'],
    ['Try again: change one move if needed, then save another test. A first-time success? Run again to check it.','필요하면 이동 하나를 고치고 다시 테스트를 저장해요. 처음에 성공했나요? 다시 실행해 확인해요.'],
    ['Key, then portal','열쇠를 거쳐 포털'],['Missed the key','열쇠를 놓침'],['Crossed a wall','벽을 지남'],['Stopped elsewhere','다른 곳에 멈춤'],['Did not move as expected','예상과 다르게 움직임'],
    ['Finished the main mission? Choose something new to build. Save a second .sb3 so you keep your main version.','기본 미션을 끝냈나요? 새로 만들 것을 골라요. 원래 작품은 남겨 두고 두 번째 .sb3로 저장해요.'],
    ['My next creation','다음에 만들 것'],['A: code a return journey','A: 돌아오는 경로 코딩'],['B: design my own target','B: 나만의 목표 만들기'],['Not today: go to Explain','오늘은 건너뛰고 설명하기로'],
    ['Read your route backwards. Swap right/left and up/down.','내 경로를 거꾸로 읽어요. 오른쪽과 왼쪽, 위와 아래를 바꿔요.'],
    ['Add return moves after the portal. Do not use “go to START” to jump back.','포털 뒤에 돌아오는 이동을 추가해요. go to START로 바로 돌아오지 마세요.'],
    ['Test it: key → portal → START (−160, −80), without crossing walls.','테스트해요: 열쇠 → 포털 → 출발 (−160, −80). 벽을 지나지 않아야 해요.'],
    ['In Scratch, paint a small target sprite. Choose a clear name and an empty grid square.','Scratch에서 작은 목표 스프라이트를 그려요. 이름을 짓고 빈 칸을 골라요.'],
    ['Set the target’s x and y boxes to multiples of 40, inside the map and not on a wall. Record your coordinates below.','목표의 x와 y 칸에 40의 배수를 넣어요. 지도 안에서 벽이 아닌 칸을 골라요. 아래에 좌표를 기록해요.'],
    ['Select Explorer. After the portal code, add moves to reach YOUR target. Run and check the target coordinates.','Explorer를 선택해요. 포털 코드 뒤에 내 목표로 가는 이동을 넣어요. 실행해서 목표 좌표를 확인해요.'],
    ['My target x','내 목표 x'],['My target y','내 목표 y'],
    ['What did you create? What happened when you tested it?','무엇을 만들었나요? 테스트 결과는 어땠나요?'],['Optional: a short note','선택: 짧은 메모'],
    ['Use your own program. Four short answers are enough. Any language or a mix is welcome.','내 프로그램으로 답해요. 짧은 답 네 개면 돼요. 어떤 언어든, 섞어서 써도 돼요.'],
    ['Input: what starts your code?','입력: 무엇이 내 코드를 시작하나요?'],['I click...','나는 …을 눌러요.'],
    ['Process: what does your code do?','처리: 내 코드는 무엇을 하나요?'],['My code...','내 코드는…'],
    ['Output: what happens on the stage?','출력: 무대에서 무엇이 일어나나요?'],['I see...','나는 …을 봐요.'],
    ['Pick one movement block. Why did you choose its number?','이동 블록 하나를 골라요. 왜 그 숫자를 넣었나요?'],['My ... block uses ... because...','내 … 블록에는 …을 넣었어요. 왜냐하면…'],
    ['Prefer to explain aloud?','말로 설명하고 싶나요?'],['Tell your teacher in your preferred language. Ask them to record your idea here.','편한 언어로 선생님께 설명해요. 내 생각을 여기에 적어 달라고 부탁해요.'],
    ['You want to open and change your Scratch program next week. Choose the file and folder you would use.','다음 주에 내 Scratch 프로그램을 열어 고치려 해요. 사용할 파일과 폴더를 골라요.'],
    ['1. Which file lets you open the Scratch code?','1. Scratch 코드를 열 수 있는 파일은 무엇인가요?'],
    ['2. Which folder helps you find your Computing work?','2. 컴퓨팅 작업을 찾기 쉬운 폴더는 어느 것인가요?'],
    ['Documents → Year 6 Computing → My name','문서 → 6학년 컴퓨팅 → 내 이름'],['Photos → Holiday pictures','사진 → 휴가 사진'],['Downloads → Mixed old files','다운로드 → 여러 옛 파일'],
    ['3. Write a clear name for your mission file. Include its file ending.','3. 알아보기 쉬운 미션 파일 이름을 써요. 확장자도 넣어요.'],['Your file name','내 파일 이름'],['Use the topic and your name. A short name is enough.','주제와 내 이름을 넣어요. 짧은 이름이면 돼요.'],
    ['Check for missing work. “Recorded” is not a mark. Your teacher will run your Scratch file.','빠진 작업을 확인해요. Recorded는 점수가 아니에요. 선생님이 내 Scratch 파일을 실행해요.'],
    ['Recorded','기록됨'],['Not finished','아직 안 끝남'],['Skipped (optional)','선택 활동 건너뜀'],['Open','열기'],
    ['Next: choose your saved .sb3. Your report will include its code details. Upload the actual file in Teams too.','다음에는 저장한 .sb3를 골라요. 코드 정보가 보고서에 들어가요. 실제 파일도 Teams에 올려요.'],
    ['Hand in two files: your report and your Scratch program. A backup is only for continuing later.','보고서와 Scratch 프로그램, 두 파일을 제출해요. 백업은 나중에 이어 할 때만 써요.'],
    ['Your plan, answers, tests and explanation','내 계획, 답, 테스트와 설명'],['Your Scratch code — your teacher can run it','내 Scratch 코드 — 선생님이 실행할 수 있어요'],['Your webpage backup — not your Scratch file','웹페이지 백업 — Scratch 파일은 아니에요'],
    ['In Scratch: File → Save to your computer. Use a clear name, for example Y6_Explorer_Aisha.sb3. Replace Aisha with your name.','Scratch에서 File → Save to your computer를 눌러요. 예: Y6_Explorer_Aisha.sb3. Aisha 대신 내 이름을 넣어요.'],
    ['Choose that saved .sb3 below. The website reads its code details on this device. Nothing is uploaded here.','아래에서 저장한 .sb3를 골라요. 이 기기에서만 코드 정보를 읽어요. 여기서는 파일이 전송되지 않아요.'],
    ['Save your PDF report. Open it and check your name and work.','PDF 보고서를 저장해요. 열어서 이름과 작업을 확인해요.'],
    ['In Teams: open the checkpoint assignment → Add work → upload BOTH the PDF and .sb3 → Turn in. Check both attachments before you finish.','Teams에서 과제 열기 → Add work → PDF와 .sb3 둘 다 올리기 → Turn in. 끝내기 전에 두 파일을 확인해요.'],
    ['Choose my saved Scratch file (.sb3)','내가 저장한 Scratch 파일 고르기 (.sb3)'],['No Scratch file chosen yet.','아직 Scratch 파일을 고르지 않았어요.'],
    ['Reading your saved code…','저장한 코드를 읽고 있어요…'],['File read on this device.','이 기기에서 파일을 읽었어요.'],
    ['Earlier code record restored; choose your latest file again.','이전 코드 기록을 복원했어요. 최신 파일을 다시 골라 주세요.'],
    ['This may be the unchanged starter. Save YOUR journey in Scratch first.','바꾸지 않은 시작 파일일 수 있어요. 먼저 Scratch에서 내가 만든 이동을 저장해요.'],
    ['Your teacher will run your program. This is not an automatic mark.','선생님이 프로그램을 실행해요. 자동으로 점수가 매겨지지는 않아요.'],
    ['Save my PDF report','내 PDF 보고서 저장'],['Print / Save as PDF','인쇄 / PDF로 저장'],['Download backup (.json)','백업 파일 받기 (.json)'],
    ['For Mandarin or Korean, choose Save as PDF in the print window. No screenshots needed.','중국어나 한국어는 인쇄 창에서 PDF로 저장을 골라요. 스크린샷은 필요 없어요.'],
    ['My final check','마지막 확인'],['I have both files ready to upload in Teams.','Teams에 올릴 두 파일이 준비됐어요.'],['I uploaded both files and pressed Turn in.','두 파일을 올리고 Turn in을 눌렀어요.'],['I need help saving or handing in.','저장이나 제출에 도움이 필요해요.'],
    ['Answers saved on this device.','이 기기에 답을 저장했어요.'],['Device storage is full. Download a backup.','기기 저장 공간이 가득 찼어요. 백업을 받아 주세요.'],
    ['Work saved locally','이 기기에 작업 저장됨'],
    ['Some evidence is missing. Continue and come back later?','빠진 작업이 있어요. 먼저 계속하고 나중에 돌아올까요?'],
    ['Your help note is saved. You can continue or ask your teacher.','도움 요청을 저장했어요. 계속하거나 선생님께 물어봐도 돼요.'],
    ['Use at most 30 moves. Remove one before adding more.','이동은 최대 30개예요. 더 넣으려면 하나를 지워요.'],
    ['Backup saved. Save your .sb3 in Scratch too — it is not inside this backup.','백업을 저장했어요. Scratch의 .sb3도 저장해요. 이 백업에는 들어 있지 않아요.'],
    ['Your earlier answers are safe. Start the new mission; earlier answers stay in your report.','이전 답을 보관했어요. 새 미션을 시작해요. 이전 답은 보고서에 남아요.'],
    ['Choose a Scratch .sb3 file smaller than 8 MB.','8 MB보다 작은 Scratch .sb3 파일을 골라요.'],
    ['The file reader did not load. Keep the file and upload it to Teams.','파일 읽기 기능이 열리지 않았어요. 파일을 보관하고 Teams에 올려요.'],
    ['This is not a supported Scratch project.','읽을 수 있는 Scratch 프로젝트가 아니에요.'],['This file does not contain Scratch code.','이 파일에는 Scratch 코드가 없어요.'],['No sprite code found. Save your mission from Scratch first.','스프라이트 코드를 찾지 못했어요. 먼저 Scratch에서 미션을 저장해요.'],
    ['No Scratch file has been read yet. Save an incomplete report anyway?','아직 Scratch 파일을 읽지 않았어요. 미완성 보고서를 저장할까요?'],
    ['Choose Save as PDF in the print window.','인쇄 창에서 PDF로 저장을 골라요.'],
    ['← Back','← 뒤로'],['Return to review →','확인 페이지로 →'],['Next: open Scratch →','다음: Scratch 열기 →'],['Save and hand in →','저장하고 제출하기 →'],['Save & continue →','저장하고 계속 →'],['Help noted ✓','도움 요청 기록됨 ✓'],['I need help','도움이 필요해요'],
    ['Knowledge: files and instructions','지식: 파일과 명령'],['Scratch file type','Scratch 파일 종류'],['Folder choice','고른 폴더'],['My filename','내 파일 이름'],['Clear instruction','정확한 명령'],['Written algorithm','글로 쓴 알고리즘'],['Why the blocks are a program','블록이 프로그램인 이유'],['Decomposition term','문제 나누기 낱말'],
    ['My mission plan','내 미션 계획'],['Part 1','1부'],['Part 2','2부'],['Why key first','열쇠에 먼저 가는 이유'],['Read code','코드 읽기'],['Predicted x','예상 x'],['Predicted y','예상 y'],['Coordinate explanation','좌표 설명'],
    ['Practical work','실제 코딩 활동'],['Scratch loaded','Scratch 열기'],['Two-part code built','두 부분 코딩'],['Tests: expected and actual','테스트: 예상과 실제'],
    ['Understanding: explain my program','이해: 내 프로그램 설명'],['My movement block','내 이동 블록'],['Optional extension','선택 도전'],
    ['Learning reflection — not graded','배움 돌아보기 — 점수 없음'],['Learning phase','지금 나의 배움 상태'],['Saved Scratch code evidence','저장한 Scratch 코드 기록'],['Submission','제출'],['Pupil hand-in check','학생 제출 확인'],['Plan versions','계획 기록'],['Not recorded','기록 없음'],
    ['Continue your saved work? Cancel will keep your saved answers unchanged.','저장한 작업을 이어 할까요? 취소하면 이전 답은 그대로 남아요.'],
    ['Saved work could not be opened. Use a JSON backup, or a different name to start.','저장한 작업을 열지 못했어요. JSON 백업을 사용하거나 다른 이름으로 시작해요.'],
    ['Restore this learner’s backup? Saved work for this name and class will be replaced.','이 학생의 백업을 복원할까요? 같은 이름과 반의 저장된 작업이 바뀌어요.'],
    ['Use Print / Save as PDF.','인쇄 / PDF로 저장을 사용해요.'],['Report saved. Open it; then upload the PDF and SB3 in Teams.','보고서를 저장했어요. 열어 확인하고 PDF와 SB3를 Teams에 올려요.'],['Report could not download. Use Print / Save as PDF.','보고서를 받지 못했어요. 인쇄 / PDF로 저장을 사용해요.'],
    ['The actual Scratch file must be submitted separately. This report records evidence, not automatic grades.','실제 Scratch 파일도 따로 제출해요. 이 보고서는 작업 기록이며 자동 점수는 아니에요.'],
    ['Earlier algorithm explanation','이전에 쓴 알고리즘 설명'],['Part 1 coded and tested','1부 코딩과 테스트'],
    ['These are pupil confirmations. Teacher verification is required.','학생이 직접 확인한 내용이에요. 선생님의 확인이 필요해요.'],
    ['My extra creation — optional','내 추가 작품 — 선택'],['Chosen challenge','고른 도전'],['What I created and tested','내가 만들고 테스트한 것']
  ];
  const dictionary=new Map(entries),lowercase=new Map(entries.map(([en,ko])=>[en.toLowerCase(),ko]));
  function text(en){
    if(dictionary.has(en))return dictionary.get(en);
    if(lowercase.has(String(en).toLowerCase()))return lowercase.get(String(en).toLowerCase());
    let match=/^Card (\d+) of (\d+) · (.+)$/.exec(en);
    if(match)return `${match[2]}개 중 ${match[1]}번 카드 · ${text(match[3])}`;
    match=/^Saved test (\d+)$/.exec(en);if(match)return `저장한 테스트 ${match[1]}`;
    match=/^Read (\d+) Motion blocks\.$/.exec(en);if(match)return `Motion 블록 ${match[1]}개를 읽었어요.`;
    return en;
  }
  window.CheckpointKorean={text};
})();
